Dockerfile-step2-build, dockerfiles/Dockerfile-step2-build
Dockerhub is having trouble with adding content outside the directory the Dockerfile lives in.
This symlinks up the Dockerfile needed to the root as a workaround/test.
=> Dockerfile location in root

src/lib/merkle_ledger_tests/test_mask.ml, src/lib/merkle_mask/maskable_merkle_tree.ml, src/lib/merkle_mask/masking_merkle_tree.ml, src/lib/merkle_mask/masking_merkle_tree_intf.ml
yet.
The mask code was correctly storing Merkle hashes in its local tables. But the function `merkle_path` was simply delegating to the mask parent, not taking into account the stored hashes.
This PR adds a function to fixup Merkle paths using those stored hashes for `merkle_path`, also used by `merkle_path_at_addr_exn` and `merkle_path_at_index_exn`.
That change simplifies some other code. Added a test to compare the parent and mask Merkle paths after adding an account.
Checklist:
=> Report accurate Merkle path from mask

src/lib/merkle_ledger/database.ml, src/lib/merkle_ledger_tests/test_mask.ml, src/lib/merkle_mask/masking_merkle_tree.ml
There were some mask operations that delegated to the mask parent. Those operations are implemented here. 
There is still some work to be done for these operations. In particular, the allocation of account locations, as is done in the database implementation of Merkle ledgers, still needs some corresponding operation in the mask. The issue #1053 captures this work to be done.
Checklist:
=> Fix some other mask delegations

Makefile, scripts/get_keys.sh
`get_keys.sh` only runs on master (so we can make ci pass on forks)
=> No-op get_keys.sh if not master

src/lib/kademlia/membership.ml
`don't_wait_for @@ (exit 1)` was intentional, despite `Core.exit 1` being "cleaner". When Core's exit is used the file log line doesn't get printed out before the process dies, while the former method does allow this.
To detect the kademlia process dying, look for the following log message:
```
((attributes((module membership)(module-Gossip_net true)(module-membership true)))(path(membership Gossip_net))(level Fatal)(pid 23204)(host 2a76262a9d02)(time(2018-11-04 21:54:21.479253Z))(location())(message"Kademlia process died: (Signal sigterm)"))
```
and the daemon will exit with code 1.
Tests weren't added, but I tested by `kill`-ing the child kademlia process and witnessing the daemon dying after printing the log message.
Closes #550
=> Kill the daemon when kademlia dies

src/app/cli/src/coda.ml
Removing eager debug note. 
Compiled and ran locally, no longer emits POS info.
Closes #1098
=> QUICK: quiet pos reporting

src/lib/ledger_builder_controller/ledger_builder_controller.ml
we spend a surprising amount of time looking up
the local ledger for that hash. for now, cache
the most recent one you saw. this is good enough
to speed up the tests, and almost all cases with
posig (not postake).
tested by looking at a trace view (from my in-progress
tracer) and seeing that the slow bits went away.
=> speed up sync ledger answering

src/lib/coda_base/account.ml
There were two definitions of `empty_hash` in `Merkle_ledger.Account`. The second shadowed the first, so only the second was used.
Probably the first definition was the correct one, so this PR removes the second one. Maybe that's the wrong way around!
Checklist:
No tests added, because unsure how to test.
=> Remove shadowing empty_hash in Account

src/lib/ledger_builder/ledger_builder.ml, src/lib/proposer/proposer.ml, src/protocols/coda_pow.ml
Sparse_ledger.of_ledger_subset_exn is slow, and synchronous.
So is apply_transaction_and_get_statement. Yield immediately
after each of these to give the scheduler a chance to run some
other code.
This makes `create_diff` async.
Tested by looking at the tracing output (PR forthcoming) and
noticing that the large "proposer" block gets split into three pieces.
=> make Lb.create_diff async

src/lib/merkle_ledger/database.ml, src/lib/merkle_ledger_tests/test_database.ml, src/lib/merkle_ledger_tests/test_mask.ml, src/lib/merkle_mask/masking_merkle_tree.ml
`remove_accounts_exn` had not been implemented for the database Merkle ledger and for the Merkle mask.
In the database, each public key has two entries. The first is an encoding of the key, whose value is an account location. The second is the account location, whose value is the account. Those are removed, and the affected hashes in the database are updated. A possible optimization, removing hashes no longer needed in the database, was not implemented. If any of the keys does not map to a location, no changes to the database are made.
For the mask, we partition the keys into two lists, those that have an entry in the mask, and the rest. We try to remove the non-mask keys from the mask parent. If that raises an exception, we're done, and no changes have been made to the mask or parent. …
=> Implement remove_accounts_exn for database and mask

README-dev.md, scripts/update-toolchain-references.sh
The `update-toolchain-references` script wasn't updating `README-dev.md`, which uses a SHA in the docker image name.
In that file, the image name ends with a backtick, so the regexp for `sed` in the script needs to exclude that character.
I ran `make update-deps` to confirm the SHA was updated, and the backtick preserved.
Checklist:
=> Update docker SHA in README-dev.md

src/lib/ledger_builder/ledger_builder.ml, src/lib/ledger_builder_controller/inputs.ml, src/lib/ledger_builder_controller/ledger_builder_controller.ml, src/lib/ledger_builder_controller/tip_ops.ml, src/lib/proposer/proposer.ml, src/protocols/coda_pow.ml
Step one of Staged_ledger world domination
These are the minimum required changes to make `create_diff` of ledger-builder not auto-apply a diff afterwards (as we're moving towards isolating diff creation)
Unit tests change guided by types
=> Ledger builder `create_diff` doesn't apply it too

src/lib/merkle_ledger_tests/test_database.ml, src/lib/merkle_ledger_tests/test_mask.ml, src/lib/merkle_mask/masking_merkle_tree.ml
`Base_ledger_intf` requires `foldi` and `fold_until`, which had not been implemented for the mask. Added `foldi`, marked `fold_until` as not-implemented, for reasons given in a comment.
Added a test for the mask `foldi`, and tests for the database versions of both these functions.
Possible nit: I didn't try to control for overflow when summing balances, which generated in the tests. I can add that, if desired.
Checklist:
=> Add fold funs in mask; test mask and database folds

src/app/cli/src/client.ml, src/app/cli/src/coda_main.ml, src/lib/client_lib/client_lib.ml
Adds a basic RPC for stopping the daemon approximately graceful.
Tested by spinning up a daemon and then running `coda client stop-daemon` and watching the daemon process die.
Checklist:
Closes #673
=> Add a stop-daemon command

src/config/testnet_posig.mlh, src/config/testnet_postake.mlh, src/config/testnet_public.mlh, src/lib/genesis_ledger/testnet_posig_ledger.ml, src/lib/genesis_ledger/testnet_postake_ledger.ml
Since we auto-generate keypairs anyway in SampleKeypairs and we're using
these to seed all our genesis ledgers, there's no point hiding behind a
global_signer_private_key.ml file.
For now, global_signer_real is set to false on all profiles, and we use
the secret-key exposing genesis ledgers everywhere.
I didn't test the changes manually, but seeing as this goes through the same code-path now as the working genesis ledgers, we should be good.
=> Fix failing signature check in testnets

src/lib/merkle_mask/masking_merkle_tree_intf.ml
Noticed an inaccurate comment in #1225. Corrected here.
=> Fix bad copy comment

src/lib/coda_base/user_command_memo.ml, src/lib/consensus/proof_of_stake.ml, src/lib/snarky/src/sha256.ml
This PR closes https://github.com/CodaProtocol/coda/issues/1127. It uses the last VRF evaluation as a tie breaker when choosing between equal-length chains.
=> use vrf eval as a tie breaker

.circleci/config.yml, .circleci/config.yml.jinja, scripts/getkeys.sh, src/lib/coda_base/sparse_ledger.ml
Work around for non-deterministic proving/verifying keys being built for every build.
TODO: Generate a hash signature of snark codes to determine when this key set is invalid.
=> SIMPLE: use stable keys (workaround)

src/app/cli/src/client.ml, src/lib/blockchain_snark/blockchain_transition.ml, src/lib/snarky/src/jbuild, src/lib/snarky/src/snark0.ml, src/lib/transaction_snark/transaction_snark.ml, src/lib/transaction_snark/transaction_snark.mli
This is step 1 of more robust SNARK key handling.
Tested by running `coda client constraint-system-digests` and noting the output.
=> add command for printing out constraint system digests

src/lib/ledger_builder/ledger_builder.ml, src/lib/ledger_builder/result_with_rollback.ml, src/lib/ledger_builder/result_with_rollback.mli, src/lib/ledger_builder_controller/catchup.ml, src/lib/ledger_builder_controller/ledger_builder_controller.ml, src/lib/ledger_builder_controller/tip_ops.ml, src/lib/proposer/proposer.ml, src/lib/transition_frontier/transition_frontier.ml, src/lib/transition_handler/processor.ml, src/protocols/coda_pow.ml, src/protocols/coda_transition_frontier.ml
Let the slowness wash over yourself.
This is temporary while we wait for @deepthiskumar's change to get in.
The intent here is to only Async.Thread_safe over the part of the code that doesn't do mutations as the OCaml compiler will incorrectly optimize away mutations.
=> Remove deferreds from ledger-builder

src/lib/transition_frontier/transition_frontier.ml, src/protocols/coda_transition_frontier.ml
Be explicit about transition_frontier interface at the end of the functor. I had to do a funky delegation thing with a few of the types of the signatures because they're created within the functor.
=> Constrain the transition_frontier to an interface

README-dev.md
Trivial: Removed space, fixing link formatting.
> Explain how you tested your changes here.
In Emacs markdown mode, link appears correctly now.
=> Fix link formatting

src/app/cli/src/coda.ml, src/app/cli/src/coda_main.ml, src/app/cli/src/jbuild, src/lib/coda_lib/coda_lib.ml, src/lib/proposer/proposer.ml, src/lib/transition_frontier/transition_frontier.ml, src/protocols/coda_pow.ml, src/protocols/coda_transition_frontier.ml
After several restarts, I found a good path to hooking in transition frontier that won't take 100 hours. I'll include the minimal signatures required as needed -- those `sig type t end`s -- and I'll decompose `Ledger_intf` into `Ledger_base_intf` in such a way to only expose the things needed for coda_lib.
Currently WIP.
=> Hook in transition frontier

src/app/cli/src/coda_main.ml, src/app/cli/src/jbuild, src/lib/coda_base/ledger_transfer.ml, src/lib/coda_lib/coda_lib.ml, src/lib/ledger_catchup/dune, src/lib/ledger_catchup/ledger_catchup.ml, src/lib/proposer/proposer.ml, src/lib/sync_handler/dune, src/lib/sync_handler/sync_handler.ml, src/lib/transition_frontier/transition_frontier.ml, src/lib/transition_frontier_controller/dune, src/lib/transition_frontier_controller/transition_frontier_controller.ml, src/lib/transition_handler/catchup_monitor.ml, src/lib/transition_handler/dune, src/lib/transition_handler/inputs.ml, src/lib/transition_handler/processor.ml, src/lib/transition_handler/transition_handler.ml, src/lib/transition_handler/validator.ml, src/protocols/coda_pow.ml, src/protocols/coda_transition_frontier.ml
Transition frontier controller is entirely hooked in but there are failwith holes present (see `coda_lib.ml`). These holes can be filled in by people in parallel.
For reviewers: You should be able to read the commits chronologically and it should make sense.
It compiles
Thanks @nholland94 for fixing up the transition_handler stuff
=> Transition frontier controller hooked in with holes

src/lib/merkle_mask/masking_merkle_tree.ml
Remove `recompute_tree` and the call to it from `merkle_root`.
That was added because it appeared needed for integration tests to pass. Locally, the integration tests pass for me after making the changes in this PR. The CI will verify whether it was needed, in fact.
> Explain how you tested your changes here.
Ran unit and integration tests locally.
Checklist:
Closes #1219. (That is, if the CI passes here and the PR merged.)
=> Remove gratuitious recompute tree

src/lib/transition_frontier/transition_frontier.ml
Compute the snarked hash properly in transition frontier.
It compiles
=> Properly compute snarked-ledger-hash

src/lib/sync_handler/dune, src/lib/sync_handler/sync_handler.ml, src/protocols/coda_transition_frontier.ml
Since the proofs for Ancestor proof can be retrieved in the
transition_frontier, a prove implementation was created to specifically
interact with transtion_frontier
Finishing https://github.com/CodaProtocol/coda/pull/1248
Checklist:
=> Created ancestor_prove within sync_handler

src/app/cli/src/coda.ml, src/app/cli/src/coda_main.ml, src/app/cli/src/coda_worker.ml, src/app/cli/src/full_test.ml, src/lib/coda_lib/coda_lib.ml, src/lib/coda_networking/coda_networking.ml, src/lib/pipe_lib/strict_pipe.ml, src/lib/pipe_lib/strict_pipe.mli, src/lib/proposer/jbuild, src/lib/proposer/proposer.ml, src/lib/transition_frontier_controller/transition_frontier_controller.ml, src/protocols/coda_transition_frontier.ml
Rips out old pipes from coda_lib, and makes transition frontier controller return a pipe
=> Rip out old pipes from coda_lib

src/app/cli/src/coda_main.ml, src/app/cli/src/coda_worker.ml, src/app/cli/src/full_test.ml, src/app/cli/src/web_pipe.ml, src/lib/coda_lib/coda_lib.ml
Removes the last failwiths in coda_lib that are independent of hooking sync ledger into network (which @cmr is working on) and the "best_ledgers" set of failwiths (which @nholland94 is working on)
=> No failwiths for pipes except network

src/lib/ledger_builder/ledger_builder.ml
Logging around parallel-scan state includes:
Spots available for transactions, Proofs Waiting To Be Solved, Proofs Ready For Purchase
In `Block Info` and `Block Stats`
=> Better logging around tree state

docs/demo.md
This trivial change tripped me up when first testing this so adding the default password (or lack thereof) for clarification.
=> Clarifying default password for demo account

src/lib/coda_base/ledger_transfer.ml, src/lib/coda_lib/coda_lib.ml, src/lib/rocksdb/database.ml, src/lib/rocksdb/jbuild
The bigarrays it was returning referenced unowned memory, which was getting invalidated by the call to `Iterator.prev`. Classic iterator invalidation bug!
=> Fix Rocksdb_database.to_alist

src/lib/snark_worker_lib/worker.ml
Reduce logging for quiesced snark workers by half. 
Include information about sleep time.
=> Simple: reduce worker log, give sleep time

src/lib/coda_base/external_transition.ml, src/lib/non_zero_curve_point/non_zero_curve_point.ml
Makes the protocol state proof opaque, sexps public keys (well, any Non_zero_curve_point) as b64 instead of decimal.
=> make external transition sexps smaller

scripts/merlin-fixup.sh, src/lib/snark_worker_lib/worker.ml
adds a random extra delay when workers do not connect. (max 20% of usual delay)
fixes GNU-SED-ism with BSD-SED-ism-compat way to perform inplace edits
=> SIMPLE: add random to worker delay, BSD compat inplace for sed

src/app/cli/src/coda.ml, src/app/cli/src/coda_process.ml, src/app/cli/src/coda_processes.ml, src/app/cli/src/coda_worker.ml, src/app/cli/src/full_test.ml, src/lib/coda_lib/coda_lib.ml
Stabilization of nodes currently means all nodes see all other nodes in
the kademlia network. This ensures that we don't have late joiners.
Eventually when we want late joiners in tests, we can make this
configurable.
This is achieved by breaking coda_lib's create into `create` and
`start`. `start` currently only begins proposing, `create` still does
all other initialization. If we ever add new modules that send
information across the network, we should put that initialization into
`start` as well.
The following test which triggered catchup most of the time:
```
$ CODA_PROPOSAL_INTERVAL=8000 dune exec --profile=test_sigs coda -- integration-tests coda-shared-prefix-test -who-proposes 0
```
Now never triggers the catchup path.
=> Stabalize nodes before starting tests

src/lib/merkle_ledger_tests/test_database.ml, src/lib/merkle_ledger_tests/test_ledger.ml, src/lib/merkle_ledger_tests/test_mask.ml
These unit tests (hopefully) expose a bug. In theory, associating a key with an empty account should do nothing -- the merkle trees are supposed to use (hash Account.empty) when an account isn't present, and when `get_or_create_account l k Account.empty = `Added` the root hash of `l` shouldn't change. I haven't made much headway debugging this yet, any insight @psteckler ?
=> fix create_empty in mask

src/lib/snarky/src/field_intf.ml, src/lib/snarky/src/libsnark.ml, src/lib/snarky/src/snark0.ml
This PR
- refactors the libsnark bindings a little
- moves the bin_io instance for field into libsnark.ml
- adds a bin_io instance for G1
=> Clean up libsnark bindings and move bin io into libsnark.ml

src/app/cli/src/coda_worker_testnet.ml, src/lib/transition_handler/validator.ml
I loosened the epsilon in coda_worker_testnet and also fixed some log statements that were printing unconditionally.
=> Fix coda shared state test in tfc-staging

src/app/cli/src/coda_main.ml, src/app/cli/src/coda_worker.ml, src/app/cli/src/web_pipe.ml, src/lib/coda_base/external_transition.ml, src/lib/coda_lib/coda_lib.ml, src/lib/ledger_builder_controller/catchup.ml, src/lib/ledger_builder_controller/inputs.ml, src/lib/ledger_builder_controller/ledger_builder_controller.ml, src/lib/ledger_builder_controller/tip_ops.ml, src/lib/ledger_builder_controller/transition_logic.ml, src/lib/ledger_builder_controller/transition_logic_state.ml, src/lib/ledger_builder_controller/transition_logic_state_intf.ml, src/lib/ledger_catchup/dune, src/lib/ledger_catchup/inputs.ml, src/lib/ledger_catchup/ledger_catchup.ml, src/lib/proposer/proposer.ml, src/lib/staged_ledger/staged_ledger.ml, src/lib/staged_ledger/staged_ledger_diff.ml, src/lib/sync_handler/sync_handler.ml, src/lib/transition_frontier/transition_frontier.ml, src/lib/transition_frontier_controller/transition_frontier_controller.ml, src/lib/transition_handler/catchup_monitor.ml, src/lib/transition_handler/inputs.ml, src/lib/transition_handler/processor.ml, src/lib/transition_handler/transition_handler.ml, src/lib/transition_handler/validator.ml, src/protocols/coda_pow.ml, src/protocols/coda_transition_frontier.ml
Transitions are verified in the Validator, by calling `verified_diff_of_diff`. To accomdate that change, there's a new submodule `Verified` in the functor to create `External_transitions`, which contains a verified staged ledger diff. Similarly, `Staged_ledger_diff` contains a `Verified` submodule.
There was a function `forget` in `Staged_ledger_diff`, that forgot about the "validated signatures and proofs" of a diff, now renamed to `forget_validated`. There's a new function `forget_verified`, which forgets about the "verified"-ness of a diff.
Transitions sent on the network are unverified. See the comment "remove verified status" in `coda_lib.ml`.
Many of the changes are simply pushing through the verified status through the code. For example, breadcrumbs …
=> Verify transitions in validator

src/lib/coda_base/sparse_ledger.ml, src/lib/merkle_ledger/any_ledger.ml, src/lib/merkle_ledger/base_ledger_intf.ml, src/lib/merkle_ledger/database.ml, src/lib/merkle_ledger/ledger.ml, src/lib/merkle_mask/masking_merkle_tree.ml
The ledger mask code was writing the new empty account at location 0, which conflicted with the base.
=> [WIP]fix create_empty mask bug

src/app/cli/src/coda_receipt_chain_test.ml, src/lib/transition_frontier/transition_frontier.ml
(also fixes the type error in coda_receipt_chain_test that I let sneak in)
=> transition_frontier: don't raise Already_exists in attach_node_to

src/lib/coda_base/gen/gen.ml
The keypairs generator was not flushing the json pipe before dying, so the json file would not actually get written all the time. This PR fixes that.
=> Fix keypairs generator to properly write json file

src/app/cli/src/coda.ml
Some stderr logs have no context. (being called directly from Async, bypassing our Logger lib)
This makes debugging some errors difficult.
This change will merge stderr and stdout in to one common/share log file by default. (coda.log)
=> SIMPLE: use a common log file for stdout and stderr

src/lib/merkle_ledger/intf.ml, src/lib/merkle_ledger_tests/test_mask.ml, src/lib/merkle_ledger_tests/test_stubs.ml, src/lib/merkle_mask/masking_merkle_tree.ml
In masks, `to_list` was appending accounts from the mask and parent. Instead, accounts in the mask with the same key as an account in the parent should mask the parent version of the account.
> Explain how you tested your changes here.
Added a test where the parent accounts have a non-zero balance. After adding accounts with the same keys to the mask, but with a zero balances, `to_list` has the same number of accounts, all with a zero balance.
Note: there still needs to be similar changes made for the mask folds, and there should be a testing facility to show all accounts at all levels.
Checklist:
Closes #1307
=> to_list masks accounts in parent

src/lib/coda_base/ledger.ml, src/lib/merkle_ledger/any_ledger.ml, src/lib/merkle_ledger/base_ledger_intf.ml, src/lib/merkle_ledger/database.ml, src/lib/merkle_ledger/jbuild, src/lib/merkle_ledger/ledger.ml, src/lib/merkle_ledger_tests/test_database.ml, src/lib/merkle_ledger_tests/test_ledger.ml, src/lib/merkle_ledger_tests/test_mask.ml, src/lib/merkle_ledger_tests/test_stubs.ml, src/lib/merkle_mask/maskable_merkle_tree.ml, src/lib/merkle_mask/masking_merkle_tree.ml, src/lib/merkle_mask/masking_merkle_tree_intf.ml
For masks, `foldi` was folding over mask accounts and all accounts in mask parents. With this PR, `foldi` folds over mask accounts and only those parent accounts that don't have corresponding accounts in the mask.
To accomplish that change, the base ledger interface adds `foldi_with_ignored_keys`, which takes a set of keys that should be ignored when folding. The mask passes all its keys to its parent.
So `foldi` now calls this new function, and passes an empty set of keys to ignore.
> Explain how you tested your changes here.
There's a new test that creates accounts in the parent, and accounts in the mask, with the same keys, so all parent accounts are masked. The parent accounts all have non-zero balances, while the mask accounts all have a zero balance. …
=> foldi in mask does not include masked accounts in parent

src/lib/blockchain_snark/blockchain_state.ml, src/lib/blockchain_snark/jbuild, src/lib/coda_base/blockchain_state.ml, src/lib/coda_base/data_hash.ml, src/lib/coda_base/jbuild, src/lib/coda_base/ledger_hash.ml, src/lib/coda_base/payment_payload.ml, src/lib/coda_base/schnorr.ml, src/lib/coda_base/transition_system.ml, src/lib/consensus/jbuild, src/lib/consensus/proof_of_work.ml.ignore, src/lib/non_zero_curve_point/jbuild, src/lib/non_zero_curve_point/non_zero_curve_point.ml, src/lib/ppx_snarky/jbuild, src/lib/ppx_snarky/ppx_snarky.ml, src/lib/ppx_snarky/snarkydef.ml, src/lib/signature_lib/checked.ml, src/lib/signature_lib/jbuild, src/lib/snark_bits/bits.ml, src/lib/snark_bits/jbuild, src/lib/snarky/src/curves.ml, src/lib/snarky/src/jbuild, src/lib/snarky/src/snark0.ml, src/lib/transaction_snark/jbuild, src/lib/transaction_snark/transaction_snark.ml, src/ppx_snarky.opam
This PR
* adds `[%with_label label]`, that expands to `with_label (label ^ ": " ^ __LOC__)`
* adds `let%snarkydef name arg = ...`, that expands to `let name arg = with_label ("name: " ^ __LOC__) ...`
* replaces the simplest cases (`with_label __LOC__` at the top of a function definition) with `let%snarkydef ... = ...`.
- The diffs are overinflated by the formatter after this change; `git diff -w` (or [here](https://github.com/CodaProtocol/coda/pull/1362/files?w=1)) gives a much more representative view of what is actually different.
Checklist:
=> Add a ppx for snarky with_label

src/lib/snarky/src/snark0.ml, src/lib/snarky/src/snark_intf.ml, src/lib/snarky_field_extensions/field_extensions.ml, src/lib/snarky_field_extensions/intf.ml
This PR adds functions for checking whether a 'checked' value is a constant. This is convenient for implementing optimizations in library functions and sound from the point of view of the semantics.
=> Add 'to_constant' function to snarky

src/lib/snarky/src/jbuild, src/lib/snarky/src/libsnark.ml
This PR removes reference to config.mlh from snarky. We can add it back in if we need to profile again but it was blocking merging changes into the snarky repo.
=> Remove use config.mlh from snarky

src/lib/coda_base/snark_transition.ml, src/lib/snark_params/snark_params.ml, src/lib/snarky/src/as_prover.mli, src/lib/snarky/src/boolean.ml, src/lib/snarky/src/boolean.mli, src/lib/snarky/src/constraint.ml, src/lib/snarky/src/cvar.ml, src/lib/snarky/src/free_monad.ml, src/lib/snarky/src/handle.ml, src/lib/snarky/src/provider.ml, src/lib/snarky/src/restrict_monad.ml, src/lib/snarky/src/snark0.ml, src/lib/snarky/src/snark_intf.ml, src/lib/snarky/src/typ_monads.ml, src/lib/snarky/src/types.ml
This PR lifts the main snarky types out of the snarky functor so that typs and checked functions can be reused across multiple proof systems with the same field. This is necessary for a snarkitecture change I'm making where we use Groth16 in some places and the BG snark in others.
=> Lift snarky types out of the functor

src/lib/snarky_verifier/dune, src/lib/snarky_verifier/groth.ml, src/lib/snarky_verifier/inputs.ml, src/snarky_verifier.opam
This PR implements the groth16 verifier in snarky. It will be used as part of the new snarkitecture. The verifier is described at the bottom of page 14 here: https://eprint.iacr.org/2016/260.pdf
Note that we use a version without gamma, as gamma is not actually necessary.
=> Groth 16 verifier in snarky

docs/res/transition_frontier_controller.dot, docs/res/transition_frontier_controller.dot.png, rfcs/0008-transition-frontier-controller.md, src/lib/transition_frontier/transition_frontier.ml, src/lib/transition_handler/catchup_scheduler.ml, src/lib/transition_handler/processor.ml
Rename `catchup monitor` to `catchup scheduler`, which may be a better name.
Checklist:
=> Rename catchup monitor to scheduler

src/app/cli/src/coda.ml
otherwise async_unix will print to stderr, which we don't want.
gives better insight into #1336
=> use our logger to report long async cycles

src/app/cli/src/coda_main.ml, src/lib/ledger_builder/inputs.ml, src/lib/ledger_builder/ledger_builder.ml, src/lib/precomputed_values/gen_values/gen_values.ml, src/lib/snark_keys/gen_keys/gen_keys.ml, src/protocols/coda_pow.ml
This is the first of all the PRs related to the refactoring of the `create_diff` function in `Ledger_builder`. None of these PRs will compile because they don't have all the changes. They will be merged to a different branch and then to master. It is split this way to make it relatively easy to review.
>Changes
Coinbase in the diff now just has the fee transfer (instead of `Completed_work.t`) for the work required to include it in the diff. This is then subtracted from the fee transfers for the work required to add user commands.
=> Create-diff refactoring PART 1: change the type of ledger builder diff

src/lib/ledger_builder/ledger_builder.ml
Part 2 of the PR consists of the following changes to the `apply_diff` function
1. Changes because of the new diff type
2. Deducting coinbase fee from other fee transfers
=> Create-diff refactoring PART 2: apply_diff changes

src/lib/ledger_builder/ledger_builder.ml
This PR consists of the major refactoring change made to create diff. 
The new algorithm first fetches all the completed work and filters valid transactions. These are then checked against three main constraints:
1. Static work constraint: based on maximum number of jobs existing in the system and space available
2. Dynamic work constraint: based on a certain set of user commands and completed work
3. Space constraint: if everything fits in the given space
4. Budget constraint: if the payment fees can pay for the proofs
if any of the constraints do not satisfy, then either a user command or a proof is discarded (See `check_constraints_and_update` function). This is sort of a bottom up approach if we call the previous one top down where transactions were added one by one if proofs were …
=> Create-diff refactoring PART 3: create diff changes

src/lib/coda_base/ledger_hash.ml, src/lib/snarky/src/request.ml, src/lib/snarky/src/request.mli
This PR changes the name to be closer to its actual function. This should be a no-op.
Checklist:
=> Rename Snarky.Request.Reraise to Delegate

src/lib/coda_base/ledger.ml, src/lib/coda_base/ledger.mli, src/lib/genesis_ledger/functor.ml, src/lib/merkle_ledger/null_ledger.ml
Implemented as a mask on top of a 'null ledger', which is
the ledger you can't add accounts to. This prevents writing
ledger dbs outside of the conf dir. There's no reason these
shouldn't be in memory anyway.
I edited https://github.com/CodaProtocol/coda/issues/872 to include testing what this fixes.
Tested by running `coda daemon` and seeing that it wasn't writing UUID directories to cwd.
=> make the genesis ledgers ephemeral

scripts/ocamlformat, src/app/cli/src/client.ml, src/app/cli/src/coda_main.ml, src/lib/cli_lib/flag.ml, src/lib/coda_networking/coda_networking.ml, src/lib/daemon_rpcs/daemon_rpcs.ml, src/lib/perf_histograms/intf.ml, src/lib/perf_histograms/jbuild, src/lib/perf_histograms/perf_histograms.ml, src/lib/perf_histograms/perf_histograms.mli, src/lib/perf_histograms/perf_histograms0.ml, src/lib/perf_histograms/rpc.ml
All two-way RPCs (that we currently have) now automatically record two performance histograms, one on the dispatch side and one on the implementation side. These are all reported in the `coda client status`
=> Instrument two way rpcs

src/lib/snarkette/elliptic_curve.ml
Slightly tweaks the elliptic curve module in snarkette, exposing a to_affine_coordinates function and shrinking the interface of the arguments to the functor.
=> tweak snarkette elliptic_curve.ml

src/lib/snarky/src/camlsnark_c/camlsnark_linker_flags_gen.ml, src/lib/snarky/src/camlsnark_c/jbuild
This does changes similar to the ones made with rocksdb in https://github.com/CodaProtocol/coda/pull/1433. This should make the snarky build work ootb with dune on macos.
=> macos compatible camlsnark_c

src/external/ocaml-sodium/myocamlbuild.ml
we don't build this dep ourselves, which makes the fixed path we'd need a
bit weird. for now, this seems to work on the frankenbuild. doesn't
break the container or linux builds.
=> don't try and statically link to libsodium on mac

src/external/ocaml-sodium/myocamlbuild.ml, src/lib/snarky/src/camlsnark_c/camlsnark_linker_flags_gen.ml, src/lib/snarky/src/camlsnark_c/jbuild
This dynamically links to libsodium on macos, and adds the necessary bash changes to build libsnark. Currently hardcodes some homebrew paths, which is unfortunate.
=> working macos build

src/external/dune
The directory `src/external` contained a `dune` file that told `dune` to ignore the `ocaml-dune` directory, which contained its own `dune` files.
Now that `ocaml-dune` is gone, we don't need this `dune` file.
Tested by building with `dune b`, which succeeded.
=> remove dune file that said to ignore now-removed pinned dune

Makefile
`make ml-docs` got removed from the Makefile. This re-adds it.
@bkase I think your commit removed it; was this causing problems for the mac build or something?
Checklist:
=> Add ml-docs target to Makefile (again)

Makefile
My builds have been failing at the `ulimit -n` command on linux. This PR lets the build continue regardless.
Checklist:
=> Don't bail on the build if ulimit -n fails

.circleci/config.yml, .circleci/config.yml.jinja, Makefile, scripts/check-snarky-submodule.sh
I wish we had a monorepo, but since we don't: In an attempt to prevent me (or anyone) from accidentally landing Coda with a version of Snarky that is off master, we can lint to make sure it's at least an ancestor (as sometimes Coda will be on an older version of snarky than the snarky repo)
I tested this script by changing the `git rev-parse origin/master` to `git rev-parse HEAD^^` and observing the make failure.
=> Snarky submodule always ancestor of master (lint)

src/app/cli/src/coda.ml, src/app/cli/src/jbuild, src/lib/coda_base/hash_prefix.ml, src/lib/coda_base/ledger_hash.ml, src/lib/coda_base/receipt.ml, src/lib/crypto_params/gen/gen.ml, src/lib/snark_params/pedersen.ml, src/lib/snark_params/pedersen.mli, src/lib/snark_params/snark_params.ml
In the client, the deserialization of the chunk table for Pedersen hashing was taking enough time to be annoying.
In this PR, `update_fold` dispatches to either a chunked or unchunked version through a reference. By default, it uses the unchunked version. In the daemon startup code, a call updates the reference to use the chunked version. Obtaining the chunk table is through a thunk, which does the deserialization the first time the thunk is run.
The time for running `coda client get-public-keys` is reduced from about 4 seconds to less than 0.5 seconds on my laptop.
Closes #1490.
=> Use chunked hashing only in daemon

src/lib/merkle_mask/masking_merkle_tree.ml
`num_accounts` for masks gave incorrect results when masks were composed.
The solution is to have `keys` include keys from the mask and all of its ancestors.
@jkrauska has verified the fix works by repeating the experiment that failed in #1464.
Closes #1464.
=> Accumulate keys from ancestors

src/lib/staged_ledger/staged_ledger.ml
- Previously, it returned the hash of the old staged_ledger. Now, it returns the hash of the new ledger
yet.
Checklist:
=> Fixed output hash of staged_ledger

src/lib/parallel_scan/parallel_scan.ml, src/lib/parallel_scan/parallel_scan.mli, src/lib/parallel_scan/state.ml, src/lib/transition_frontier_controller_tests/stubs.ml
This is one of the four pr implementing a fix to take snark worker delay into consideration when creating a diff.
This pr adds a sequence number field to the nodes of the parallel scan tree. All the jobs new jobs created will have `curr_job_seq_no`. This field corresponds to the block number in which a particular Base or a Merge job was added. It was initially used to implement the delay-factor but now remains just for debugging purposes.
=> Snark work delay 1: added a sequence number to the jobs

src/lib/transaction_snark_scan_state/inputs.ml, src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
Changes:
1.added work-delay-factor to the scan state. 
Work-delay-factor is the number of slots it takes for a considerable number of proofs to be done. Considerable because it depends on how many transactions we always want in a block. For instance, we always want a coinbase and so there has to be at least two proofs available. If it takes 2 slots to generate two proofs then work-delay-factor = 2.  
Work delay factor essentially increases the tree size (therefore, we need to minimize the delay) so that transactions can be en-queued while snark workers are still generating the required proofs.
2. added work-capacity to the scan state 
In order to control this behaviour so as to not allow free transactions beyond a point, `Work-capacity` is introduced. Work-capacity is the maximum number …
=> Snark work delay 2: Added work-delay factor and Work capacity to the scan state

src/lib/blockchain_snark/blockchain_state.ml, src/lib/bootstrap_controller/bootstrap_controller.ml, src/lib/coda_base/blockchain_state.ml, src/lib/consensus/proof_of_stake.ml, src/lib/external_transition_validation/external_transition_validation.ml, src/lib/lite_compat/lite_compat.ml, src/lib/proposer/proposer.ml, src/lib/transition_frontier/transition_frontier.ml, src/lib/transition_frontier_controller_tests/stubs.ml, src/protocols/coda_pow.ml
In this PR, I did a refactor which renamed `ledger_hash` to `snarked_ledger_hash`.
Closes #1530
=> renaming ledger_hash to snarked_ledger_hash

src/lib/coda_networking/coda_networking.ml, src/lib/gossip_net/gossip_net.ml, src/lib/network_peer/peered.ml
Somehow, PR #1534 didn't remove the file `peered.ml`, which is no longer needed.
This PR does the removal.
Also, mention IP forgery in comments.
=> Remove peered.ml

src/lib/crypto_params/gen/gen.ml
When `fake_hash` is true, don't build the hash chunk table, which takes 8 seconds of compile time on my laptop.
=> Empty chunk table for fake hash

scripts/getkeys.sh
Master build broken -- variable was removed, use a similar variable.
=> QUICKFIX: CODA_CONSENSUS removed, use DUNE_PROFILE

src/lib/merkle_ledger_tests/test_mask.ml, src/lib/merkle_mask/masking_merkle_tree.ml
Somehow, the correct version of `foldi` for the mask wasn't actually being used.
Removed the old, invalid version, fixed the name of the correct one.
Closes #1563.
=> Remove wrong version of foldi

src/lib/logger/logger.ml
Saves a syscall, which is significant in some tests.
Checklist:
=> [easy] Don't check the current time when using null logger

src/dummy.sh, src/lib/kademlia/membership.ml
Use /usr/bin/env bash over /bin/bash for systems (e.g. NixOS) where it's in a
different place. Search for dune-project rather than README-dev.md because dune
copies that file into _build/default when you build the executable. Fix finding
the kademlia executable when outside the Coda source tree.
Tested by running the tests inside and outside of `src` and running `coda daemon` inside and outside a source tree.
Checklist:
=> More fixes for Kademlia tests

src/app/cli/src/coda.ml
This way when a SNARK fails in testnets we'll know why. We believe the performance cost of this is ~20% slower, but haven't measured recently.
=> Turn on snark debugging in prod temporarily

src/app/cli/src/coda_main.ml, src/lib/coda_base/ledger.ml, src/lib/coda_base/transaction_logic.ml, src/lib/coda_base/transaction_validator.ml, src/lib/coda_base/transaction_validator.mli, src/lib/staged_ledger/inputs.ml, src/lib/staged_ledger/staged_ledger.ml, src/lib/transition_frontier_controller_tests/stubs.ml, src/protocols/coda_pow.ml
This pulls all of the logic for applying transactions and creating undos from `Coda_base.Ledger` and into `Transaction_logic` functor. We only use it in one new place: the `Transaction_validator`.  The `Transaction_validator` has no notion of `undo` and avoids all hashing.
This prevents a substantial amount of hashing when creating a diff.
=> staged_ledger: no hashing while validating txns

scripts/rebuild-deb.sh
We were preferring files in /var to /tmp (swapped).
Also using a more careful check to look for files in a directory instead of just existence of dir.
=> SIMPLE: use bash expansion to look for files

Makefile, scripts/test_all.sh
This tweaks `run_ppx_tests` from #1609 to make sure the tests get run.
/cc @psteckler
Checklist:
=> Make sure that ppx tests are run

.github/PULL_REQUEST_TEMPLATE.md
The PR template mentions putting serialized types in stable-versioned modules.
That's mentioned in RFC 0013 for versioned modules (not yet merged). This is a first step to implementing that RFC.
=> Mention versioned modules in PR template

src/lib/coda_base/account.ml, src/lib/coda_base/jbuild, src/lib/module_version/dune, src/lib/module_version/registration.ml, src/module_version.opam
Creates a registration mechanism for versioned modules that do `bin_io` serialization. 
A registered module serializes data with a version number prepended. A particular module is designated as the latest, and deserialization can be from any version's data, but always to the latest version's type.
There is a test module that shows usage. `coda_base/account.ml` uses the registration mechanism for the versioned type there.
Not yet done: serialization with JSON or S-exps in versioned modules.
RFC 0013, still unmerged, is about versioned modules, but doesn't explicitly mention the mechanism here. That could be added to the RFC.
=> Registration mechanism for versioned modules

src/lib/coda_base/account.ml, src/lib/coda_base/sparse_ledger.ml, src/lib/module_version/registration.ml
Refined the module versioning mechanism:
- added functors to generate bin_io boilerplate, one for older versions, one for latest version
- the boilerplate goes in the *unregistered* module, so it can contain arbitrary other code
- registration is just for taking old bin_io strings and deserializing them to the latest version type
- in code, you just use the latest unregistered module
The module version tests were modified accordingly.
Will update the RFC to match this implementation.
Checklist:
=> Refine module versioning

src/lib/coda_base/blockchain_state.ml, src/lib/coda_base/ledger.ml
Use new module versioning for `Coda_base.Blockchain_state`.
Also removed a commented-out module in `Coda_base.Ledger`, which no longer seemed relevant.
=> Version blockchain_state module

src/lib/transition_frontier/transition_frontier.ml, src/protocols/coda_transition_frontier.ml
The previous version of this variant had more overlap than necessary and didn't account for some cases. This one recognizes that `new root` and `new best tip` almost always happen at the same time.
As an bonus, this also simplifies the dispatch logic.
=> Fix Transition_frontier_diff variant

src/lib/currency/currency.ml, src/lib/currency/currency.mli, src/lib/currency/dune
Use versioning for modules in `Currency`.
Note that one of those modules is inside a functor, which is a little funny. But that functor, `Make`, is not exported. It is applied twice internally, and with the same arguments in both cases.
=> Version Currency modules

src/lib/coda_base/ancestor.ml
Version the modules in `coda_base/ancestor`.
Checklist:
=> Version Ancestor modules

src/lib/coda_base/data_hash.ml, src/lib/coda_base/data_hash.mli, src/lib/coda_base/receipt.ml
Version modules in `coda_base/data_hash`
=> Version data_hash modules

.mergify.yml
from the docs:
The delete_head_branch action deletes the head branch of the pull request, that is the branch which hosts the commits. This only works if the branch is stored in the same repository that the pull request target, i.e., if the pull request comes from the same repository and not form a fork.
This action takes no configuration options. The action will happen when the pull request is closed or merged: you can decide what suits you best using Conditions.
=> mergify: delete branch after merge

src/lib/coda_base/signature.mli, src/lib/coda_base/transaction_union.ml, src/lib/coda_base/user_command.mli
Versioned modules in `signature_lib/public_key`
Checklist:
=> Version Public_key modules

src/lib/coda_base/sok_message.ml
Version modules in `coda_base/sok_message`.
Checklist:
=> Version sok_message modules

src/lib/coda_base/sok_message.mli, src/lib/transaction_snark/transaction_snark.ml, src/lib/transaction_snark/transaction_snark.mli
Changed mentions of `Stable.V1` in `Transaction_snark` to `Stable.Latest`.
=> Latest versions in Transaction_snark

src/protocols/coda_pow.ml
Changed `Stable.V1` to `Stable.Latest` in `Coda_pow`.
=> Use Latest versions in Coda_pow

src/lib/daemon_rpcs/daemon_rpcs.ml
There were several `Stable.V1` modules mentioned in `Daemon_rpcs`. Changed those to `Stable.Latest`.
Checklist:
=> Use Latest versions in Daemon_rpcs

src/lib/merkle_mask/masking_merkle_tree.ml
Fail faster when there's a dangling mask floating around. The idea is that any stack traces we get now will help us pinpoint which modules are keeping references too long to masks.
=> Fail faster when dangling mask

src/lib/parallel_scan/state.ml
Add versioning of types in `Parallel_scan.State`.
Because these types have parameters, the existing serialization-with-version and module registration mechanism won't work. 
And because serialization and deserialization need to work with data for particular instantiations of those type parameters, we really can't do the serialization-with-version and module registration when those parameters are left uninstantiated. Will work on making those work for the case that the parameters are known.
=> Version Parallel_scan.State

.circleci/config.yml, .circleci/config.yml.jinja
Something changed in nix land invalidating most of the nix cache and making builds take a long time.
This will help resolve the issue.
=> Simple: Fix/nix cache

src/lib/transaction_snark_scan_state/dune, src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
Versioned modules in `Transaction_snark_scan_state`.
=> Version Transaction_snark_scan_state modules

src/lib/coda_base/sok_message.ml, src/lib/coda_base/transaction_union.ml, src/lib/coda_base/user_command.ml, src/lib/coda_base/user_command.mli, src/lib/transaction_snark/transaction_snark.ml, src/lib/transaction_snark/transaction_snark.mli
When a versioned module refers to types within other versioned modules, those types must belong to a specific version (specifically, not `Latest`). Otherwise, the same-versioned module might produce varying serializations.
Checklist:
=> Use specific versioned modules within other versioned modules

rfcs/0015-module-versioning.md
Type parameters are not really an issue for module versioning, as long as we version types where the parameters have been instantiated. Revised the second on type parameters to reflect that.
Added a section on using specific versions, rather than `Latest`, within versioned types that contain versioned types.
Checklist:
=> [RFC] Update comment re type parameters; add section on using fixed versions

src/lib/blockchain_snark/blockchain.ml, src/lib/blockchain_snark/dune
Versioning for `Blockchain_snark` module.
=> Version blockchain_snark module

src/app/cli/src/coda.ml
In order to better diagnose the "dangling reference" error we'll need to see async backtraces. I don't know the performance penalty for recording them, but I suspect we can just bump up the slot time a bit if we see really strange things happening in testnets.
=> Record async backtraces for the daemon

src/app/cli/src/coda.ml
This reverts commit f2085d1f22ee01659a82a23ae3af634b4502dcdd.
It seems as though this could be responsible for flaking fulltest-withsnark. Hopefully we'll figure out how to repro dangling ref assertion locally to better debug it.
=> Revert "Record async backtraces for the daemon (#1729)"

src/lib/consensus/proof_of_stake.ml, src/lib/network_pool/network_pool.ml, src/lib/proposer/proposer.ml
From now on, all large sexps within %s's should be relgated to trace calls. In
the future we will print these in a more structured manner.
=> Move messy logs to trace

src/app/cli/src/coda_main.ml, src/lib/coda_base/account.ml, src/lib/coda_base/ledger.ml, src/lib/coda_base/sync_ledger.ml, src/lib/daemon_rpcs/daemon_rpcs.ml, src/lib/merkle_ledger_tests/test.ml, src/lib/merkle_ledger_tests/test_database.ml, src/lib/merkle_ledger_tests/test_mask.ml, src/lib/merkle_ledger_tests/test_stubs.ml, src/lib/transition_frontier_controller_tests/test_bootstrap_controller.ml
`Account.t` should not be used in types with `bin_io`. To prevent that, in `account.ml`, instead of
```
include Stable.Latest
```
we define
```
type t = Stable.Latest.t [@@deriving ...]
```
where the `deriving` list does not include `bin_io`.
In the places in the code where `Account.t` required `bin_io`, we use `Account.Stable.V1` instead. In some places, we construct a Frankenstein `Account` consisting of `Stable.V1.t` plus some functionality from `Account`.
=> No bin_io for Account.t

src/app/cli/src/coda_worker_testnet.ml, src/lib/consensus/constants.ml, src/lib/consensus/constants.mli
In integration tests, we need to make sure to handle the case where
all nodes lose some `i < c` slots in a row. This can and does happen
frequently and comes up specifically when the slot time is pushed a bit
low.
In the "no recent blocks", check we should also wait an extra `c-1`
slots before reporting an error.
Here we're using `c = 1` for sig as sig does expect a block to be
created every slot (and therefore doesn't change the old check).
Checklist:
=> No recent blocks check should obey stake semantics

src/app/cli/src/coda_main.ml, src/lib/bootstrap_controller/bootstrap_controller.ml, src/lib/coda_base/user_command.ml, src/lib/coda_base/user_command.mli, src/lib/coda_lib/coda_lib.ml, src/lib/ledger_catchup/inputs.ml, src/lib/network_pool/network_pool.ml, src/lib/proposer/proposer.ml, src/lib/root_prover/root_prover.ml, src/lib/snark_pool/snark_pool.ml, src/lib/snark_pool/snark_pool.mli, src/lib/sync_handler/sync_handler.ml, src/lib/transaction_pool/transaction_pool.ml, src/lib/transition_frontier/best_tip_diff.ml, src/lib/transition_frontier/snark_pool_refcount.ml, src/lib/transition_frontier/transition_frontier.ml, src/lib/transition_handler/inputs.ml, src/lib/transition_router/initial_validator.ml, src/lib/transition_router/transition_router.ml, src/protocols/coda_transition_frontier.ml
Remove transactions from the pool when we see a new best tip that contains them. This is a hacky solution to unblock running longer PoS tests with transactions. There are a few things wrong with it: removing transactions is super inefficient, we don't handle backtracking in external transitions, and we don't do anything special when bootstrapping is engaged. See also #1734.
Tested at the command line by running a proposer and submitting transactions, then watching the log to verify they're dropped. There's a commented out automated test that is broken because of #1748.
Checklist:
=> Remove transactions from pool when they're committed to a block

src/app/cli/src/coda_main.ml, src/lib/ledger_catchup/ledger_catchup.ml, src/lib/snark_worker_lib/worker.ml
Noisy logs go to trace (so `.level != "Trace"` is a useful filter for
watching logs), snark-worker logs are passed through cleanly so jq
doesn't barf on those as they come in. Logs are clearer.
=> Improve logging on integration tests

src/lib/ledger_catchup/ledger_catchup.ml, src/lib/non_empty_list/non_empty_list.ml, src/lib/non_empty_list/non_empty_list.mli, src/lib/sync_handler/sync_handler.ml, src/lib/transition_frontier/transition_frontier.ml, src/lib/transition_frontier_controller_tests/stubs.ml, src/lib/transition_frontier_controller_tests/test_ledger_catchup.ml, src/protocols/coda_transition_frontier.ml
I also wrote more code for visualizations to help me debug my tests. Namely, I created a visualization for a list of breadcrumbs and a rose_tree of breadcrumbs.
Checklist:
Closes #1745
=> integrate root history into ledger catchup

src/lib/consensus/proof_of_stake.ml, src/lib/proposer/proposer.ml, src/lib/transition_frontier/transition_frontier.ml
This one is potentially-mergeable but note that it is very inefficient with updating the db.
1. supply_increase was accidentally ignored on (some?) epoch boundaries.
2. a bug with epoch snapshot selection in the first `k` blocks of an epoch. 
3. something undiagnosed that makes the `db_mask` we used to construct have the wrong merkle root the second time we go to update the db. i'll resume investigating this in the morning.
4. wrong snarked ledger hash in blockchain state
=> fix the "empty epoch bug"

src/lib/coda_base/block_time.ml
No `bin_io` for `Block_time.t`.
=> No bin_io in blocktime

.circleci/config.yml, .circleci/config.yml.jinja, scripts/macos-setup.sh, src/app/kademlia-haskell/README.md
Set up a Nix binary cache on S3. Mac build times go from 1h01m to 19m, and the cache won't become broken every time nixpkgs changes. The new paths will be built and added to S3, and future builds will be fast.
We can start using Nix for getting Kademlia on Linux too, rather than having the docker images + .deb packages, but that's a problem for another day.
Tested by running the build, changing something, seeing that it cached the dependencies, then running it again after changing nothing and seeing it cached the whole thing.
Checklist:
=> Set up a Nix cache for the Mac builds

src/lib/coda_base/coinbase.ml, src/lib/coda_base/coinbase.mli, src/lib/coda_base/transaction.ml, src/lib/coda_base/transaction_logic.ml, src/lib/transition_frontier_controller_tests/stubs.ml, src/protocols/coda_pow.ml
Remove `bin_io` for `Coinbase.t`.
That forces `Stable.V1` to be used for some type definitions, which should eventually be versioned.
=> Remove bin_io for Coinbase.t

src/lib/pipe_lib/broadcast_pipe.ml, src/lib/pipe_lib/broadcast_pipe.mli, src/lib/transaction_pool/transaction_pool.ml
=> Fix #1748: writing to a broadcast pipe waits for all consumers before returning

src/lib/proposer/proposer.ml
These may or may not catch what I was seeing with `slot 0` blocks.
=> assert some properties about proposed consensus states

src/config/consensus/postake_tiny.mlh
we're currently seeing plenty of issues with k=2, and they are by design.
with a bigger k, we won't see that as often.
=> turn tiny k up to 8

.circleci/config.yml, .circleci/config.yml.jinja, Makefile, scripts/artifacts.sh, scripts/test_all.sh
- Capture the constraint system digests for debugging
- Use /tmp/artifacts more efficiently (for GC saves too)
- Use the json version of the sample_keypairs
=> simple: store constraint system digests, use /artifacts

src/lib/merkle_mask/masking_merkle_tree.ml
This second assert is supposed to look up the new merkle root of the mask, not use the old cached value.
=> fix Mask.Attached.commit assert

src/lib/merkle_ledger/database.ml, src/lib/merkle_ledger_tests/test_mask.ml, src/lib/merkle_mask/maskable_merkle_tree.ml, src/lib/merkle_mask/masking_merkle_tree.ml
The first is that `set_batch` and related methods on `maskable` weren't causing write notifications. The second is that write notification handling was too liberal. It would forget about the mask's copy if just the PKs match. For correctness, the entire account needs to match.
=> Fix two bugs related to write notifications in masks

src/lib/non_empty_list/non_empty_list.ml, src/lib/non_empty_list/non_empty_list.mli, src/lib/transaction_pool/transaction_pool.ml, src/lib/transition_frontier/best_tip_diff.ml, src/lib/transition_frontier/snark_pool_refcount.ml, src/lib/transition_frontier/transition_frontier.ml, src/protocols/coda_transition_frontier.ml
I modified the transition frontier extension interface to expose changes in the
best tip path, modified the best tip diff view to expose changes in the user
commands, and used the data in the transaction pool. This should do the right
thing when the best tip change involves backtracking now.
I wrote tests for the transaction pool logic with mocks, and did some informal testing of the daemon, but there are a bunch of bugs in other stuff which prevent you from running test networks with transactions for very long so I'm not totally confident this is correct.
Checklist:
=> Use best tip path changes in transaction pool

src/lib/coda_base/block_time.ml, src/lib/coda_base/block_time.mli, src/lib/coda_base/fake_time.ml, src/lib/coda_base/timeout.ml
This PR creates a new time functor `fake_time` that basically the same as the existing `block_time.ml`, except that when `now` is called, `fake_time` would returns the `current time - offset`, where `offset` is the input of this functor.
Checklist:
=> fake system time

Makefile
Asks git which files have been updated since last commit and reformats just those. The bash stuff just filters out files that were deleted because otherwise ocamlformat gets upset.
Also added reformat before build because otherwise I always forget to reformat and then build and then have to build again after reformatting.
Thought I'd share in case anyone was interested. On my machine it's like 30x faster than running `make reformat`.
=> Add ability to just reformat modified files

Makefile
Was causing an issue with gnu make having a different default shell, this seems to make it work.
Was using `&>` which wasn't redirecting properly when build on a non-mac machine.
=> Make reformat-diff not depend on bash

src/app/cli/src/coda_restart_node_test.ml, src/lib/ledger_catchup/ledger_catchup.ml
In this PR, I made 2 changes:
1. I make the test time for ledger catchup to 4 min instead of 30 sec.
2. I delete the unnecessary `Breadcrumb.copy` in ledger catchup.
For 2, `copy` is unwanted because it would create extra layers of mask, which may cause move-root to fail. And since we already did the checks for dangling mask, we don't have to make a copy anyway.
=> A one-line change for the integration test of ledger catchup and another one-line change in ledger_catchup itself

src/lib/transition_handler/catchup_scheduler.ml
The current implementation might have bug that `collected_transitions` and `parent_root_timeouts` do not sync. This PR is an easy fix to avoid crashing the program because of this bug.
=> A one-line fix to avoid using add-exn

src/lib/coda_base/account.ml, src/lib/lite_base/account.ml, src/lib/lite_compat/lite_compat.ml, src/lib/transaction_snark/transaction_snark.ml
This adds a field `participated : bool` to `Account.t`. It is currently always false. It is to be used to track whether an account has won a block in a given epoch.
=> "Participated" bit

Makefile
We were merging debs in from all master builds.  Only publish postake to stable.
=> SIMPLE: Only publish postake to stable

Makefile
Use the full path'd deb file name (to maintain multiple versions)
eg.
coda-testnet-postake_0.1.56007-CI.deb
vs
coda.deb
=> SIMPLE: minor change, use fully spec deb name

src/app/cli/src/coda.ml, src/app/cli/src/coda_five_nodes_restarts_txns.ml, src/app/cli/src/coda_five_nodes_test.ml, src/app/cli/src/coda_restart_node_test.ml, src/app/cli/src/coda_restarts_and_txns_holy_grail.ml, src/app/cli/src/coda_shared_state_test.ml, src/app/cli/src/coda_worker_testnet.ml
Shared logic between integration tests is moved into functions under
submodules of `Coda_worker_testnet`, those are all mixed together to
make the holy-grail test.
The goal is for the holy grail test to work under 2 proposers with check
on and 5 proposers with fast-hash.
Note that with this in place + the bootstrap test @ghost-not-in-the-shell 
is working on and the txn test @enolan is working on, we should have 
essentially have coverage on the scaffolding.
These tests are intentionally not turned on for CI at this time.
=> Holy grail test in place, share logic

src/lib/consensus/proof_of_stake.ml
Should_bootstrap check had the wrong equation in it. The left-hand side of the `>` was always negative, so `should_bootstrap` was always false. This means we have never _once_ actually tested bootstrap in a real network or integration test.
I added a unit test so this doesn't regress.
=> Fix bootstrap check

src/lib/cli_lib/fee.ml
Increase default payment fee so they don't get stuck when the scan state is full
Checklist:
=> increase default payment fee

src/lib/daemon_rpcs/daemon_rpcs.ml
For the longest time this annoying things was happening:
```
Histograms:                 Performance HistogramsAccepted remote block Latencies (hist.):  Total: 212 (overflow:0) (underflow:0)
```
Now it's not
=> Newline in histogram title

src/app/reformat/reformat.ml
This PR stops us from trying to reformat files within a `node_modules` subdirectory.
Checklist:
=> Don't reformat in the node_modules subdir

src/lib/transition_router/transition_router.ml
When we transition from bootstrap -> not bootstrap we should assert the
opposite as the other case.
This was found while trying to get the bootstrap integration test to
work. The bootstrap integration test will exercise this code when it
lands.
They will be added when bootstrap integration test finishes
=> Transition router set phase copy-paste error

src/app/cli/src/coda.ml, src/app/cli/src/coda_bootstrap_test.ml, src/config/test_postake_bootstrap.mlh
Use the test_postake_boostrap.mlh config file
This will be enabled after we fix all the bugs with it.
=> Coda bootstrap test (disabled for now)

src/lib/blockchain_snark/blockchain_transition.ml, src/lib/cache_lib/impl.ml, src/lib/kademlia/membership.ml, src/lib/network_pool/network_pool.ml, src/lib/snark_pool/snark_pool.ml, src/lib/staged_ledger/staged_ledger.ml, src/lib/transition_frontier_controller_tests/test_bootstrap_controller.ml, src/lib/transition_frontier_controller_tests/test_catchup_scheduler.ml, src/lib/transition_frontier_controller_tests/test_ledger_catchup.ml, src/lib/transition_frontier_controller_tests/test_root_prover.ml, src/lib/transition_frontier_controller_tests/test_sync_handler.ml, src/lib/transition_frontier_controller_tests/test_transition_frontier.ml
Noisy tests are annoying and rarely informative. A few of the tests already did this, but most didn't.
Checklist:
=> Use null logger in unit tests

src/app/website/src/main.ml, src/lib/pipe_lib/strict_pipe.ml
In this PR, I fixed a bug in `Strict_pipe.Reader.Merge.iter`.
When we are doing `iter`, some pipe maybe closed, we need to filter out the closed pipes so that we only `iter` on the open ones.
=> fixing the Strict_pipe.Reader.Merge.iter

src/app/cli/src/coda_main.ml, src/app/cli/src/dune, src/app/cli/src/ledger_proof.ml, src/lib/staged_ledger/inputs.ml, src/lib/staged_ledger/staged_ledger.ml, src/lib/transaction_snark_scan_state/inputs.ml, src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml, src/lib/transition_frontier/inputs.ml, src/lib/transition_frontier_controller_tests/stubs.ml, src/protocols/coda_pow.ml
Remove `bin_io` from `Debug` and `Prod` modules in `Ledger_proof`. Use versioned type for the module in places needing `bin_io`.
The TFC test stubs have a Ledger_proof.t` with `bin_io`, still, because some functors in those tests require it.
=> Remove bin_io from Ledger_proof

src/lib/coda_networking/coda_networking.ml, src/lib/parallel_scan/parallel_scan.mli, src/lib/parallel_scan/state.ml, src/lib/staged_ledger/staged_ledger.ml, src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml, src/protocols/coda_pow.ml
Within `Rpcs` functor, choose a version of `Staged_ledger_aux`. There's a comment to explain why that's justifiable.
Finish version-izing types used by that type.
=> Finish versioning of Staged_ledger_aux in RPC types

scripts/skip_if_only_frontend.sh
This will be hooked into the CI when the new system, #1838, lands. We
can expand this script in the future to skip other CI jobs in certain
scenarios.
I tested by making a branch off of an older commit than origin/master -- change just a frontend file, the command doesn't run. If I change something that includes another file, the command does end up running.
=> Skip a command if just frontend files touched

src/app/cli/src/coda_main.ml, src/lib/coda_networking/coda_networking.ml, src/lib/staged_ledger/staged_ledger.ml, src/protocols/coda_pow.ml
`Ledger_hash` is another type that occurs in RPC types. Use specific version of that type in the RPC types.
=> Use version of Ledger_hash in RPC

src/lib/bootstrap_controller/bootstrap_controller.ml, src/lib/coda_base/sync_ledger.ml, src/lib/coda_lib/coda_lib.ml, src/lib/coda_networking/coda_networking.ml, src/lib/ledger_catchup/inputs.ml, src/lib/sync_handler/sync_handler.ml, src/lib/transition_frontier_controller/transition_frontier_controller.ml, src/lib/transition_router/transition_router.ml
Create versions for `Sync_ledger` answer and query types, use those in RPC types.
Still have to make sure that the types contained these versions are themselves versioned; but here's a bite-sized PR.
=> Add versions for Sync_ledger answer and query

src/app/cli/src/client.ml, src/app/cli/src/coda_main.ml, src/lib/daemon_rpcs/daemon_rpcs.ml, src/lib/transition_frontier/transition_frontier.ml
- Made it clearer to client when you are bootstrapping and when you are not
Visualizations should not fail randomly anymore because it should be impossible to throw an exception involving this code
Checklist:
Closes #1842
Closes #1806
=> Removed exn from visualization code

src/lib/coda_networking/coda_networking.ml, src/lib/non_empty_list/non_empty_list.ml, src/lib/non_empty_list/non_empty_list.mli
Added versioning of nonempty lists, used in RPC types.
=> Versioning of nonempty lists

src/lib/coda_base/sync_ledger.ml, src/lib/coda_networking/coda_networking.ml, src/lib/ledger_catchup/inputs.ml, src/lib/syncable_ledger/syncable_ledger.ml, src/lib/syncable_ledger/test.ml, src/lib/transition_frontier_controller_tests/stubs.ml
Added versions for `Sync_ledger` and `Syncable_ledger` query, answer types, used in the `Answer_sync_ledger_query` module in RPC.
=> Versions for syncable/sync_ledger query, answer types in RPC

Makefile, src/lib/coda_base/external_transition.ml, src/lib/coda_networking/coda_networking.ml, src/protocols/coda_pow.ml
Version `External_transition`, used in RPC types.
Still to do: version the functor inputs for that module, namely, `Staged_ledger_diff` and `Protocol_state`.
=> Version External_transition

src/lib/coda_networking/coda_networking.ml
Use versioned `State_hash` in RPC types
=> Versioned State_hash in RPC types

frontend/website/src/Careers.re, frontend/website/src/Page.re, frontend/website/src/Render.re
Removed some duplication to make it a little more manageable. The bulk of this change is just moving a section of layout to a variable so that it can be reused.
- move benefits to a reusable variable
- create component for Career "heading" and Page footer "link" items
=> Some cleanup of careers page

.circleci/config.yml, .circleci/config.yml.jinja
Brew likes to burn a lot of cycles "autoupdating" every time we try to install things on circle. This change lets us skip that autoupdating.
=> Make brew faster on frontend CI job

src/app/cli/src/client.ml, src/app/cli/src/coda.ml, src/app/cli/src/coda_main.ml, src/app/cli/src/coda_worker.ml, src/app/cli/src/visualization_message.ml, src/lib/daemon_rpcs/daemon_rpcs.ml
This will help with debugging the dangling masks errors we see
Checklist:
=>  Added registered_mask visualization to cli and log_shutdown

frontend/website/jobs, frontend/website/src/BlogPost.re, frontend/website/src/CareerPost.re, frontend/website/src/Markdown.re, frontend/website/src/Nav.re, frontend/website/src/Page.re, frontend/website/src/Render.re
- Add generation for job pages using the same list as is used for generating the list of jobs (impossible to have a dead link)
- Reorganize Markdown
- Fix menu selector and adds style to all pages
We might want to have `generateStatic` pass in the page name to Page later so that we don't need to duplicate it, but this seemed simpler for now.
=> Add pages for careers posts

src/app/cli/src/coda_bootstrap_test.ml, src/lib/bootstrap_controller/bootstrap_controller.ml, src/lib/syncable_ledger/syncable_ledger.ml, src/lib/transition_router/transition_router.ml
Extends wait on bootstrap test from 60-180s
Adds minor context to some logging messages.
=> SIMPLE:More context for bootstrap logging, extend wait on bootstrap test

src/lib/bootstrap_controller/dune, src/lib/coda_networking/dune, src/lib/ledger_catchup/dune, src/lib/logger/logger.ml, src/lib/logger/logger.mli, src/lib/peer_trust/peer_trust.ml, src/lib/syncable_ledger/dune, src/lib/transaction_pool/dune, src/lib/transition_handler/dune
I'll be fixing the warnings over the next while, then turning deprecation warnings back into errors when a given library is free of them.
Checklist:
=> Deprecate Logger.faulty_peer

frontend/website/html/Privacy.html, frontend/website/html/TOS.html, frontend/website/src/RawHtml.re, frontend/website/src/Render.re
This adds the privacy and tos pages to the new site. They are slightly styled and include the header and footer, unlike the old ones. The html of the content is completely unchanged, it's just copied from the ml string into its own file and formatted.
=> Add privacy and tos pages

frontend/website/src/CodaNav.re, frontend/website/src/HeroSection.re, frontend/website/src/Home.re, frontend/website/src/LegacyPage.re, frontend/website/src/Style.re
The hero section on the website is starting to look sort of like what it should look like based on the spec. I fully fleshed out the color/font styling from zeplin, but did not do layout completely (if the graphics change we may want to change how this bit is laid out)
I also hacked IBM plex fonts in by copying some styles from the legacy site. It looks like we're missing some of the weights, so we'll have to add those and we should clean up my hack.
=> Start hero section on website

src/app/kademlia-haskell/packages.nix, src/app/kademlia-haskell/release2.nix, src/app/kademlia-haskell/stack.yaml
The build broke because we were using 8.6.3 and they dropped that version from
unstable when 8.6.4 came out. This commit pins nixpkgs to unstable as of today
so underlying versions won't change on us and switches to 8.6.4
Tested modified Nix expressions build on my Ubuntu machine, will see how Mac CI goes.
Checklist:
=> Pin nixpkgs and use GHC 8.6.4

src/app/cli/src/coda_main.ml, src/lib/network_pool/network_pool.ml, src/lib/network_pool/snark_pool_diff.ml, src/lib/snark_pool/snark_pool.ml, src/lib/snark_pool/snark_pool.mli, src/lib/staged_ledger/staged_ledger.ml, src/lib/staged_ledger/staged_ledger_diff.ml, src/lib/staged_ledger/transaction_snark_work.ml, src/lib/transition_frontier_controller_tests/stubs.ml, src/protocols/coda_pow.ml, src/protocols/coda_transition_frontier.ml
Versioning of `Work` parameter to `Snark_pool.Make` and `Snark_pool_diff.Make`.
Inlined `Public_key.Compressed` argument of `Staged_ledger.Make_completed_work`; same module was passed in real and test code.
More types flagged with TODOs for versioning.
Checklist:
=> Versioning of Work

src/lib/coda_networking/coda_networking.ml, src/lib/proof_carrying_data/proof_carrying_data.ml
Version `Proof_carrying_data`, plus mention a version for `Staged_ledger_diff` in a place where I forgot to.
=> Version Proof_carrying_data

scripts/test.py
Fixed the following bugs:
1. test script would crash when no filters were selected by provided whitelist
2. test script would display output from internal `which` command
=> Fix some small bugs in test script

src/app/cli/src/coda_main.ml, src/lib/coda_networking/coda_networking.ml, src/lib/transaction_pool/dune, src/lib/transaction_pool/transaction_pool.ml
Versioning of `Transaction_pool.Diff`, which feeds into RPC types in `Coda_networking`.
=> Versioning for transaction_pool_diff

src/config/test_postake_five_even_snarkless.mlh, src/lib/gossip_net/gossip_net.ml, src/lib/otp_lib/capped_supervisor.ml, src/lib/pipe_lib/dune, src/lib/pipe_lib/strict_pipe.ml, src/lib/pipe_lib/strict_pipe.mli, src/lib/transition_frontier_controller/transition_frontier_controller.ml, src/lib/transition_frontier_controller_tests/stubs.ml, src/lib/transition_handler/validator.ml, src/lib/transition_router/transition_router.ml, src/protocols/coda_transition_frontier.ml
We think our system shouldn't be overflowing these pipes.
I also added a name field to strict pipes, so we can include that when there's a pipe error. I also added some logging to the `Drop_head` behavior so it won't go unnoticed.
=> Crash on Strict_pipe overflow

src/app/cli/src/coda_main.ml, src/app/cli/src/coda_worker.ml, src/lib/envelope/envelope.ml, src/lib/network_peer/peer.ml
Auditing versioning of RPC types, expect more cleanup PRs.
Removed `bin_io` for `Peer.t`. Use versioned `Peer` in `Envelope.Sender`.
=> Version cleanup for Peer

src/app/cli/src/coda_main.ml, src/app/cli/src/ledger_proof.ml, src/lib/coda_base/proof.ml, src/lib/coda_base/proof.mli, src/lib/coda_base/sok_message.ml, src/lib/coda_base/sok_message.mli, src/lib/coda_networking/coda_networking.ml, src/lib/coda_networking/dune, src/lib/envelope/envelope.ml, src/lib/envelope/envelope.mli, src/lib/network_pool/dune, src/lib/network_pool/network_pool.ml, src/lib/network_pool/snark_pool_diff.ml, src/lib/staged_ledger/staged_ledger.ml, src/lib/staged_ledger/transaction_snark_work.ml, src/lib/transaction_pool/dune, src/lib/transaction_pool/transaction_pool.ml, src/lib/transaction_snark/dune, src/lib/transaction_snark/transaction_snark.ml, src/lib/transaction_snark/transaction_snark.mli, src/lib/transition_frontier_controller_tests/dune, src/lib/transition_frontier_controller_tests/stubs.ml, src/protocols/coda_pow.ml
this required some substantial yojsoning. I apologize that it is all in one commit, https://github.com/CodaProtocol/coda/compare/feature/broadcast-logging?expand=1#diff-08521bc469b5bcbc1e7c8528b8df6959R526 has the actually relevant change.
=> improve broadcast logging

src/lib/cli_lib/background_daemon.ml
This will exit client with status code 1 when daemon not found. (helpful in automating tests that check for daemon's existence)
I tried calling exit directly from no_daemon, but I got this complaint about Abort. 
```
Error (warning 37): constructor Abort is never used to build values.
(However, this constructor appears in patterns.)
```
I tried removing Abort, but I got this complaint
```
Error (warning 8): this pattern-matching is not exhaustive.
Here is an example of a case that is not matched:
Abort
```
So as a compromise we keep the go abort and exit in abort.
Closes #1943
=> trivial: exit 1 if daemon not present

src/lib/pipe_lib/dune
dev build currently broken due to new 'name' in strict_pipes
```
File "lib/pipe_lib/strict_pipe.ml", line 42, characters 21-63:
Error (warning 9): the following labels are not bound in this record pattern:
name
Either bind these labels explicitly or add '; _' to the pattern.
File "lib/pipe_lib/strict_pipe.ml", line 184, characters 21-63:
Error (warning 9): the following labels are not bound in this record pattern:
name
Either bind these labels explicitly or add '; _' to the pattern.
File "lib/pipe_lib/strict_pipe.ml", line 210, characters 12-45:
Error (warning 9): the following labels are not bound in this record pattern:
name
Either bind these labels explicitly or add '; _' to the pattern.
File "lib/pipe_lib/strict_pipe.ml", line 225, characters 20-60:
Error (warning 9): the following …
```
=> TRIVIAL: workaround for dev build

src/app/cli/src/transaction_snark_profiler.ml
Description tweak means `coda.exe tra -help` now looks like this
```
coda.exe transaction-snark-profiler
=== flags ===
[-check-only]       Just check base snarks, don't keys or time anything
[-k count]          count = log_2(number of transactions to snark) or none for
the mocked ones
[-repeat count]     number of times to repeat the profile
[-witness-only]     Just generate the witnesses for the base snarks
[-help]             print this help text and exit
(alias: -?)
```
The `-repeat` argument is useful for profiling multiple runs of the snark profiler, e.g. for o1-labs/snarky#148.
Checklist:
=> Add -repeat argument to transaction-snark-profiler, tweak argument descriptions

frontend/website/src/CryptoAppsSection.re, frontend/website/src/Image.re, frontend/website/src/SideText.re, frontend/website/src/Style.re, frontend/website/src/Wrapped.re, frontend/website/static/img/build-illustration.png, frontend/website/static/img/build-illustration@2x.png, frontend/website/static/img/build-illustration@3x.png, frontend/website/static/img/coda.png, frontend/website/static/img/coda@2x.png, frontend/website/static/img/coda@3x.png, frontend/website/static/img/map.png, frontend/website/static/img/map@2x.png, frontend/website/static/img/map@3x.png
* `SideText` component can be reused on the next few sections.
* The PNG background images need to be re-centered when they're exported then it will look a bit better
* I didn't do the line from the code to the coda
* Flex-wrap makes it hard to center, will fix later
Not quite perfect, but much better than before:
=> Better cryptoapps section

src/lib/coda_networking/coda_networking.ml, src/lib/signature_lib/public_key.mli, src/lib/transaction_snark/dune, src/lib/transaction_snark/transaction_snark.ml, src/lib/transaction_snark/transaction_snark.mli, src/protocols/coda_pow.ml
Version `Transaction_snark.Proof_type`. Probably that won't change, but adhering to convention.
Also removed some `yojson`, `eq` annotations that weren't being used.
=> Version Proof_type

src/app/cli/src/ledger_proof.ml, src/app/cli/src/verifier.ml, src/lib/snark_worker_lib/prod.ml, src/lib/transaction_snark/transaction_snark.ml, src/lib/transaction_snark/transaction_snark.mli, src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
Audit of RPC type dependencies found another type that needs versioning.
As a result of this change, `Proof_type` will need to be versioned.
Checklist:
=> Versioning for Transaction_snark

src/lib/merkle_ledger_tests/test_stubs.ml
There are warnings turned on in the `dev` profile that aren't in the others, and CI doesn't build with the `dev` profile. I'll add a CI job for that in a separate PR.
Checklist:
=> Fix building with the dev profile

src/app/cli/src/ledger_proof.ml, src/lib/snark_worker_lib/debug.ml, src/lib/snark_worker_lib/intf.ml, src/lib/snark_worker_lib/rpcs.ml, src/lib/staged_ledger/staged_ledger.ml, src/lib/staged_ledger/transaction_snark_work.ml, src/lib/transaction_snark/transaction_snark.ml, src/lib/transaction_snark/transaction_snark.mli, src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml, src/lib/transition_frontier_controller_tests/stubs.ml, src/protocols/coda_pow.ml
Versioning of `Transaction_snark.Statement`.
=> Version Statement in Transaction_snark

src/lib/coda_base/ledger.mli, src/lib/coda_base/transaction_logic.ml, src/lib/staged_ledger/staged_ledger.ml, src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml, src/protocols/coda_pow.ml
Version the `Undo` module.
This change will require versioning of the types `varying`, `fee_transfer`, and `coinbase` which it depends on.
=> Version Ledger.Undo

src/config/testnet_postake_many_proposers.mlh, src/lib/coda_base/gen/gen.ml, src/lib/genesis_ledger/genesis_ledger.ml, src/lib/genesis_ledger/test_split_two_stakes_ledger.ml, src/lib/genesis_ledger/testnet_posig_ledger.ml, src/lib/genesis_ledger/testnet_postake_ledger.ml, src/lib/genesis_ledger/testnet_postake_ledger_many_proposers.ml
- bumps generated keys up from 40 to 120
- creates a new postake genesis ledger option with 20 large balance accounts
=> Bump generated keypairs and begin many_stakers

src/app/cli/src/coda_main.ml, src/lib/coda_base/coinbase.ml, src/lib/coda_base/coinbase.mli, src/lib/coda_base/fee_transfer.ml, src/lib/coda_base/fee_transfer.mli, src/lib/coda_base/ledger.mli, src/lib/coda_base/sparse_ledger.ml, src/lib/coda_base/transaction.ml, src/lib/coda_base/transaction_logic.ml, src/lib/staged_ledger/inputs.ml, src/lib/staged_ledger/staged_ledger.ml, src/lib/staged_ledger/staged_ledger_diff.ml, src/lib/transaction_snark_scan_state/inputs.ml, src/lib/transition_frontier/inputs.ml, src/protocols/coda_pow.ml
Versioning of `Fee_transfer`, its `Single` submodule, and the `Fee_transfer_undo` submodule of `Undo`.
The type `fee_transfer` inside `Undo`, when versioned, has the name `Fee_transfer_undo` to avoid confusion with the existing module `Fee_transfer`.
=> Version Fee_transfer

src/lib/coda_base/coinbase.mli, src/lib/coda_base/ledger.mli, src/lib/coda_base/transaction_logic.ml
Version `Coinbase_undo` that occurs in `Undo`.
Checklist:
=> Version Coinbase in Undo

frontend/website/src/SustainableSection.re, frontend/website/src/Svg.re
Fonts weren't showing up correctly on the svgs with text and inlining the svg fixed it, but we don't want to blow up our html size.
=> Make svgs inlineable

src/lib/coda_base/ledger.mli, src/lib/coda_base/transaction_logic.ml
Version the `varying` type in `Undo`.
Still need to version `User_command`, which the new module `Varying` contains.
Checklist:
=> Version varying type in Undo

src/lib/module_version/registration.ml
Use correct RFC number in comment.
Checklist:
=> Fix RFC number in module version file

src/lib/coda_base/user_command_payload.ml, src/lib/coda_base/user_command_payload.mli
The modules in `User_command_payload` had types `t` with `bin_io`. Removed the `bin_io`.
Checklist:
=> Remove bin_io from User_command_payload module types

src/app/cli/src/coda_worker.ml, src/lib/coda_base/user_command_payload.ml, src/lib/coda_numbers/nat.ml, src/lib/coda_numbers/nat.mli, src/lib/consensus/proof_of_signature.ml, src/lib/consensus/proof_of_stake.ml
Removed `bin_io` from `Nat.t` (which has aliases `Account_nonce.t`, `Length.t`, ....).
=> Remove bin_io from Nat.t

frontend/website/src/GetInvolvedSection.re, frontend/website/src/InclusiveSection.re, frontend/website/src/Nav.re, frontend/website/src/Page.re, frontend/website/src/SideText.re, frontend/website/src/Style.re, frontend/website/src/SustainableSection.re, frontend/website/src/Svg.re, frontend/website/static/img/chart-blockchain-energy.svg, frontend/website/static/img/chart-blockchain-size.svg
The website looks pretty good on mobile now (including iphone SE 320px width).
* Set root font size to be smaller for iphoneSE sized devices to rescale layout (thank god we used rems)
* SVGs can take rem widths as their width and height (and they need to, to look good at 320)
* Inclusive consensus does the display none hack :( , legend just needed to be in two different spots in the DOM
* Sustainable section SVGs are changed to use width100% in the SVG files and the wrapping div has a maxWidth so they'll look good as we scale down to mobile
* GetInvolved section knowledgebase on mobile is more to spec + I added hover states to the social links
=> More website mobilization

frontend/website/src/CodaNav.re, frontend/website/src/CryptoAppsSection.re, frontend/website/src/HeroSection.re, frontend/website/src/InclusiveSection.re, frontend/website/src/Page.re, frontend/website/src/Style.re
* Too much whitespace after signup button p
* Hero `<p>` too wide
* Red is too dark on other-blockchains
* Font on fixed/increasing is too dark
* Line from coda code to coda icon
* Plus it doesn't look bad on 375 width anymore
=> Signup whitespace shift and various improvements

src/app/cli/src/coda_main.ml, src/app/cli/src/coda_process.ml, src/app/cli/src/coda_worker.ml, src/app/cli/src/coda_worker_testnet.ml, src/app/cli/src/full_test.ml, src/app/cli/src/web_pipe.ml, src/lib/coda_lib/coda_lib.ml
it's not used for much (driving some testnet event loops) but the name is now accurate.
=> renamed strongest_ledgers to verified_transitions

.circleci/config.yml, .circleci/config.yml.jinja
[CircleCI currently has degraded performance](https://status.circleci.com/incidents/9jg85s3m1th8) and we're seeing our mac builds sit in the queue forever. Since they are currently failing anyway, let's just ignore them for now.
=> disable macos while circle is down

src/app/cli/src/coda.ml, src/app/cli/src/coda_worker.ml, src/app/cli/src/full_test.ml
For some reason, in the 5 proposer test with payments, I was seeing transaction diff broadcast timeouts to one particular node. I tripled the timeout and it went away. Looking at the trace, the node was not blocked for an entire second ever, but it seems like there might be some latency problem somewhere in the gossip net control flow.
=> gossip_net: bump up timeout

Makefile
Now it matches what `make reformat` does.
=> Pass --doc-comments=before to ocamlformat in reformat-diff

frontend/website/src/GetInvolvedSection.re, frontend/website/src/Head.re, frontend/website/src/Render.re, frontend/website/src/Style.re, frontend/website/static/font/IBMPlexMono-Medium-Latin1.woff, frontend/website/static/font/IBMPlexMono-Medium-Latin1.woff2
`<legend align=center>` isn't a supported property in reasonreact but is required for the fieldset legend to be centered in firefox, so we have to use `createElement`.
- Removed local font loading for now
- Actually push the IBM plex mono fonts
=> Improve fonts and firefox knowledgebase centering

src/app/cli/src/prover.ml, src/lib/currency/currency.ml, src/lib/snark_params/snark_util.ml
:scream: forgot to push my snarky change that threw an exception instead of using a bool. this makes proof_level=check useful.
=> proof_level=check should complain if check fails

frontend/website/src/HeroSection.re
With eyeballed "bounding box" around the fixed and increasing text.
=> Recentering of hero graphic

frontend/website/src/CryptoAppsSection.re, frontend/website/src/SideText.re, frontend/website/src/Style.re, frontend/website/src/Title.re, frontend/website/src/Wrapped.re
Polished cryptoapps section
(I took the screenshots before I pulled in the new fonts)
=> Polished crypto-apps section

frontend/website/src/Home.re, frontend/website/src/Wrapped.re
Fix annoying cut of built-by-o1 (that I caused)
=> Un-regress bulti-by-o1 overflow hide

frontend/website/src/GetInvolvedSection.re, frontend/website/src/InclusiveSection.re, frontend/website/src/Style.re, frontend/website/src/SustainableSection.re
- Made the svgs change color (see rightmost social link) when hovering. This uses css variables cause I couldn't think of a better way.
- Fixed the hyperlinkHover color as suggested in discord.
- Added a max width to the knowledge base and social links to match zeplin
=> Improve style for GetInvolved, fix alt copy

frontend/website/src/InclusiveSection.re
* No width is messed up (before there were a few pixels with legend in wrong spot)
* Square is 40x40 now
* After the "s" there is sufficient margin
=> Nudges in inclusive section

frontend/website/src/Head.re, frontend/website/src/HeroSection.re, frontend/website/src/Nav.re, frontend/website/static/img/coda_facebook_OG.jpg
* Og updated (we won't be able to confirm image because it's required to be a full url not a relative one)
* Hero section looks closer to the spec + fixed max-width graphic when it overflows
* keepAnnouncement bar on blog too
* Make menu be in the same space on the other pages
=> Hero better

frontend/website/src/AnnouncementBar.re
Fix announcement shifting on firefox
=> Fix announcement shift firefox

src/lib/ppx_coda/dune, src/lib/ppx_coda/tests/Makefile, src/lib/ppx_coda/tests/dune, src/lib/ppx_coda/tests/versioned_bad_module_structure.ml, src/lib/ppx_coda/tests/versioned_bad_option.ml, src/lib/ppx_coda/tests/versioned_bad_wrapped_module_structure.ml, src/lib/ppx_coda/tests/versioned_good.ml, src/lib/ppx_coda/versioned.ml
Instead of using the `Driver` in `Ppxlib`, use `Ppx_deriving`. A deriver gets passed a module path and options, and is invoked only when the particular `deriving` flag is used. That makes a lot of code we had unnecessary.
Small loss:i f a module version name is wrong, like `Vx` instead of `V1`, we don't have the location to highlight in Merlin.
I discovered a dune bug others had reported, mentioned in the `dune` for the tests.  Added a `VERBOSE` flag to the Makefile, allowing confirmation that expected test failures fail for the expected reason.
Checklist:
=> Use deriver for version ppx

src/lib/ppx_coda/tests/Makefile, src/lib/ppx_coda/tests/dune, src/lib/ppx_coda/tests/versioned_bad_contained_types.ml, src/lib/ppx_coda/tests/versioned_bad_module_structure.ml, src/lib/ppx_coda/tests/versioned_good_contained_types.ml, src/lib/ppx_coda/versioned.ml
For types contained in versioned types, generate let-bindings for their `__versioned__` values. For example, if a versioned type is declared with:
```
let t = Foo.Bar.t [@@deriving version]
```
we generate let-bindings
```
let __versioned__ = true
let _ = Foo.Bar.__versioned__
```
Therefore, a type can be versioned only if the types it depends on are versioned (unless those dependencies are wrapped types).
I added good and bad tests for this behavior, and also inspected the preprocessor output to verify these let-bindings are present.
=> Generate declarations for contained versioned types

src/lib/ppx_coda/tests/versioned_good.ml, src/lib/ppx_coda/versioned.ml
For a module signature like:
```
sig
type t [@@deriving version]
end
```
we generate
```
val version : int
val __versioned__ : bool
```
to add to the signature.
There's not much checking to do here. Added such a signature to the "good" test case, and verified these declarations appear in the code after preprocessing.
There's another piece that needs to be added to the ppx: the case where the versioned type `t` instantiates a type with parameters.
Checklist:
=> Generate val declarations for versioned types in module signatures

src/lib/ppx_coda/tests/Makefile, src/lib/ppx_coda/tests/dune, src/lib/ppx_coda/tests/versioned_bad_type_parameters.ml, src/lib/ppx_coda/tests/versioned_good_type_parameters.ml, src/lib/ppx_coda/versioned.ml
Versioned types may depend on types with parameters. Since the latter may change, we require that they be versioned, too. We can't use the versioning registration machinery for them, because we don't know how to serialize them without knowing the instantiations of their type parameters. Aside from that, such types can be treated as versioned like other types.
Removed redundant checking for the name "t" introduced in #2088.
=> Require versioning of types with parameters used by versioned types

src/app/cli/src/coda_main.ml, src/lib/coda_base/coinbase.ml, src/lib/coda_base/data_hash.ml, src/lib/coda_base/dune, src/lib/coda_base/fee_transfer.ml, src/lib/coda_base/fee_transfer.mli, src/lib/coda_base/payment_payload.ml, src/lib/currency/currency.ml, src/lib/currency/currency.mli, src/lib/currency/dune, src/lib/non_zero_curve_point/dune, src/lib/non_zero_curve_point/non_zero_curve_point.ml, src/lib/signature_lib/dune, src/lib/signature_lib/public_key.mli, src/lib/snark_params/pedersen.ml, src/lib/snark_params/pedersen.mli, src/lib/snark_params/snark_params.ml, src/lib/unsigned_extended/dune, src/lib/unsigned_extended/unsigned_extended.ml, src/lib/unsigned_extended/unsigned_extended.mli
Added `deriving version` for `Coinbase.Stable.V1.t`, which required versioning of the types it depends on. This helps show the viability of the version ppx.
For `Non_zero_curve_point`, the type `t_`, which takes type parameters, is now wrapped in `Poly.Stable.V1` and renamed `t`, to conform to the versioning ppx's requirements.
For three of the contained types, `Pedersen.Digest.t`, `Tick.Field.t`, and `Unsigned_extended.t`, the types are not actually versioned. Instead, by hand we write `let __versioned__ = true`, which allows the requirements of the ppx to be fulfilled. I'm not yet sure how to version these, but the strategy here allows versioning of the types that depend on them. It will be easy to find these harder cases via `grep`.
=> Version some types using ppx

src/lib/envelope/dune, src/lib/envelope/envelope.ml, src/lib/envelope/envelope.mli, src/lib/network_peer/peer.ml
Add `deriving version` for `Envelope.Stable.V1.t` and `Envelope.Sender.Stable.V1.t`.
That required asserting that `Peer.Stable.V1.t` is versioned, but it depends on a Jane St library. There's a comment about that.
=> Deriving version for envelopes

src/lib/ppx_coda/tests/versioned_good_type_constructors.ml, src/lib/ppx_coda/versioned.ml
Allow Jane Street `sexp_opaque` as a type constructor for versioning.
Added test to check this case (and fixed tests for other type constructors).
=> Allow sexp_opaque type constructor

.circleci/config.yml, .circleci/config.yml.jinja, .gitattributes, frontend/website/.gitignore, frontend/website/package.json, frontend/website/src/Home.re, frontend/website/src/InvestorsSection.re, frontend/website/src/Page.re, frontend/website/src/Render.re, frontend/website/src/Style.re, frontend/website/src/TeamSection.re, frontend/website/static/font/PragmataPro.zip, frontend/website/static/img/investors/caffeinated.png, frontend/website/static/img/investors/charlie.png, frontend/website/static/img/investors/curious.jpg, frontend/website/static/img/investors/dekrypt.png, frontend/website/static/img/investors/elad.jpg, frontend/website/static/img/investors/electric.png, frontend/website/static/img/investors/fred.jpg, frontend/website/static/img/investors/jack.jpg, frontend/website/static/img/investors/kindred.png, frontend/website/static/img/investors/linda.jpg, frontend/website/static/img/investors/metastable.png, frontend/website/static/img/investors/naval.png, frontend/website/static/img/investors/nima.png, frontend/website/static/img/investors/o.png, frontend/website/static/img/investors/polychain.jpg, frontend/website/static/img/investors/scifivc.png, frontend/website/static/img/sahai.jpg
Section is re-done in the new technical style. Not done are the
equal-sign borders (just a placeholder for now). Looks good on my
iPhone.
The fonts are encrypted inside a zip file to mitigate the
potential pirating of these fonts, ask @bkase for the password if
you have creds to see the font files. Decrypt by running
`npm run decrypt`.
=> O(1) section redesign

src/lib/coda_base/external_transition.ml, src/lib/staged_ledger/staged_ledger.ml, src/protocols/coda_pow.ml
Added `deriving version` for `Staged_ledger_diff` interfaces.
=> Versioning for staged_ledger_diff

src/lib/coda_networking/coda_networking.ml, src/lib/ppx_coda/versioned.ml
For RPC types (a `query`, `response` or `message`), can now write `[@@deriving version {rpc}]`. That will generate definitions that will check that all types it depends on are versioned.
For `response` and `message`, a `let version = n` is also generated from the containing `Vn` module name. We don't do that for `query`, in order not to get an unused value.
I added this annotation to one of the RPC types in `Coda_networking`.
=> Allow option 'rpc' to version ppx

src/lib/ppx_coda/versioned.ml
An RPC type name can be `msg` (not `message`).
Checklist:
=> Type name is msg, not message

src/lib/coda_base/external_transition.ml, src/lib/coda_networking/coda_networking.ml, src/lib/non_empty_list/dune, src/lib/non_empty_list/non_empty_list.ml, src/lib/non_empty_list/non_empty_list.mli, src/lib/staged_ledger/staged_ledger.ml, src/protocols/coda_pow.ml
In `Coda_networking`, added `deriving version {rpc}`, or put that in a comment as a reminder to make that change when possible.
Added version ppx to `Non_empty_list` to allow one of those annotations to work.
=> Add version {rpc} where possible, or in comment

src/lib/pipe_lib/strict_pipe.ml, src/lib/pipe_lib/strict_pipe.mli
`Printexc` doesn't know how to print out `option` values, so it always tells us `_`. Always include some string in the exceptions.
=> strict_pipe: don't use option in exception data

src/lib/coda_base/protocol_state.ml, src/lib/coda_networking/coda_networking.ml, src/lib/consensus/dune, src/lib/consensus/intf.ml
Added `deriving version {rpc]` for get-ancestry RPC call.
=> Rpc-version get-ancestry query type

src/app/cli/src/coda_main.ml, src/lib/coda_networking/coda_networking.ml, src/lib/snark_worker_lib/dune, src/lib/snark_worker_lib/intf.ml, src/lib/snark_worker_lib/rpcs.ml, src/lib/snark_worker_lib/worker.ml
Use Jane Street's versioned-RPC mechanism for snark worker RPCs, like we already have in `Coda_networking`.
@johnwu93 is working on versioning the types contained in these RPC types.
=> Jane St versioned RPC for snark workers

frontend/website/deploy-website.sh, frontend/website/package.json, scripts/artifacts.sh
build-wallet master build's deploy script had bitrotted. That's fixed by
delegating to the new deploy-ci.sh script with a new option for CI.
There is also a short-circuit for 3rd party builds, so we can have
contributors. See https://github.com/CodaProtocol/coda/pull/2174 for an
example PR that should have it's CI jobs succeed after this PR.
I tested the build-wallet staging deploy by running as if I was in the
CI context.
=> build-wallet master + 3rd party PR builds

frontend/wallet/src/App.re
Tested by closing the window and then verifying the menu was still
there. We can later spawn a new application window.
=> Keep app open on window close

src/lib/parallel_scan/parallel_scan.mli, src/lib/parallel_scan/state.ml
Version `Job` in `Parallel_scan.State`.
This is a preface to wrapping the `Queue` and `Array` types so that `State.Stable.V1.t` can rightfully be said to be versioned.
=> Version Job in parallel-scan-state

frontend/wallet/src/App.re, frontend/wallet/src/AppTray.re, frontend/wallet/src/AppWindow.re, frontend/wallet/src/ProjectRoot.re, frontend/wallet/src/Single.re
Tray and window logic was quite similar and not necessary to be inside
of App. Moved it out.
Single is a singleton-like holder (but not quite a singleton) that can
also drop it's cached item. The specific Tray and Window modules we need
have an App prefix because BsElectron will shadow Tray and Window
modules.
=> Refactor App logic a bit

frontend/website/package.json
It's hacky, but it should work. Tested locally and the correct files are written when decrypt-ci is invoked without the PRAGMATA_ZIP_PASSWORD var set. These files are then used by the website render script and it won't error out.
=> Shadow pragmata pro fonts when CI env vars are missing

.gitmodules
This change makes it easier for new contributors to contribute to coda. 
After I forked coda and did `git submodule init && git submodule update --recursive`, I had a failure:
```
ERROR: Repository not found.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:rahulmutt/async_kernel'  ...
```
It turns out that the submodule urls are defined relatively so I had to fork all the submodules in order to make it work.
This PR updates `.gitmodules` to use absolute instead of relative urls so that contributors don't have to fork unnecessarily.
Checklist:
=> Avoid relative urls in the .gitmodules file

src/lib/ppx_coda/tests/versioned_good.ml, src/lib/ppx_coda/versioned.ml
Allow OCaml's built-in array constructor in the version ppx.
The new ocamlformat made some formatting changes that appear in the diffs, sorry.
Checklist:
=> Allow OCaml array constructor in version ppx

src/lib/parallel_scan/state.ml
Substitute `array` for `Array.t` so we don't have to wrap `Array` for versioning.
Checklist:
=> Use OCaml array constructor to avoid wrapping

src/lib/coda_base/pending_coinbase.ml
Use `int` so we don't have to wrap `Int` (and we have actual versioning, instead of asserting it).
Checklist:
=> Use int instead of Int.t to avoid wrapping

src/lib/blockchain_snark/blockchain.ml, src/lib/coda_base/protocol_state.ml
Removed an `asserted` from a `deriving version` in `Blockchain`.
Checklist:
=> Remove asserted from deriving version in Blockchain

src/app/cli/src/coda_main.ml, src/app/cli/src/full_test.ml, src/lib/coda_base/account.ml, src/lib/coda_base/ledger.ml, src/lib/consensus/proof_of_stake.ml, src/lib/genesis_ledger/functor.ml, src/lib/merkle_ledger_tests/test_stubs.ml, src/lib/transaction_snark/transaction_snark.ml, src/lib/transition_frontier_controller_tests/stubs.ml
In `Account`, remove the `asserted` from `deriving version`.
Checklist:
=> Remove asserted from deriving version in Account

src/app/cli/src/coda_main.ml, src/lib/coda_base/payment_payload.ml, src/lib/coda_base/payment_payload.mli, src/lib/coda_base/staged_ledger_hash.ml, src/lib/coda_base/transaction_logic.ml, src/lib/coda_base/transaction_union_payload.ml, src/lib/coda_base/user_command.ml, src/lib/coda_base/user_command_payload.ml, src/lib/coda_base/user_command_payload.mli, src/lib/currency/currency.ml, src/lib/currency/currency.mli, src/lib/lite_base/lite_chain.ml, src/lib/non_zero_curve_point/non_zero_curve_point.ml, src/lib/signature_lib/public_key.mli, src/lib/snarky_blake2/snarky_blake2.ml, src/lib/sparse_ledger_lib/sparse_ledger.ml
In many places, we were using `Poly.Stable.Latest.t` where we can use `Poly.t`, because there's no `bin_io`. The code is less cluttered this way.
Checklist:
=> Use Poly.t not Poly.Stable.Latest.t

src/lib/coda_base/external_transition.ml
Removed `asserted` from `deriving version` for `External_transition` functor result. It was no longer needed.
=> Remove asserted from External_transition deriving version

src/app/cli/src/prover.ml, src/lib/coda_base/internal_transition.ml, src/lib/coda_base/snark_transition.ml
Version `Snark_transition`. This is a step towards removing the `{asserted}` in versioning of `Internal_transition`.
=> Version Snark_transition

src/app/cli/src/prover.ml, src/lib/coda_base/internal_transition.ml, src/lib/coda_base/stake_proof.ml, src/lib/consensus/intf.ml, src/lib/consensus/proof_of_signature.ml, src/lib/consensus/proof_of_stake.ml, src/protocols/coda_pow.ml
Version `Prover_state` for posig and postake. That allows removal of the `{asserted}` versioning of `Internal_transition`. Another `{asserted}` is added for `Stake_proof`, which is further down the tree of types.
=> Version Prover_state

src/lib/ppx_coda/versioned.ml, src/lib/staged_ledger/staged_ledger.ml
We want to get rid of the `asserted` option to `deriving version` wherever possible, yet that option is useful in test code, where the actual versioning is not significant.
This PR creates the `for_test` option, which is a synonym to `asserted`, that we can keep in test code.
Used this option in the `Staged_ledger` tests. There may be other uses of `asserted` where we can use this new option.
Checklist:
=> Add for_test option to version ppx

src/lib/coda_base/protocol_state.ml
Removed two instances of `version {asserted}` from `Protocol_state`.
=> Remove asserted from deriving version in Protocol_state

src/lib/ppx_coda/tests/versioned_good.ml, src/lib/ppx_coda/versioned.ml
You can do `derive bin_io` on OCaml types `int32` and `int64`, so allow these types for `deriving version`.
Checklist:
=> Add int32 and int64 types as OCaml builtins for version ppx

src/lib/coda_networking/coda_networking.ml
Removed `let version = ...`, it's already generated by the version ppx (and the comment told us to remove it come the time).
=> Remove version number, generated by ppx

src/lib/transaction_pool/transaction_pool.ml
yet.
Checklist:
Closes #0000
Closes #0000
=> Removed version{asserted} in Transaction Pool

src/app/cli/src/coda_main.ml, src/lib/staged_ledger/staged_ledger.ml, src/lib/staged_ledger/staged_ledger_diff.ml, src/lib/transition_frontier_controller_tests/stubs.ml, src/protocols/coda_pow.ml
Remove `asserted` from the `Stable.V1.t` in `Staged_ledger_diff`. Several other types had to be versioned, and the change in module structure propagated to the `Staged_ledger` tests.
Checklist:
=> Remove asserted from deriving version in Staged_ledger_diff

src/lib/parallel_scan/ring_buffer.ml
In `Ring_buffer`, use OCaml's `array` constructor instead of `Array.t`, to allow versioning.
Checklist:
=> Use OCaml array instead of Array.t to allow versioning

src/lib/ppx_coda/tests/versioned_good.ml, src/lib/ppx_coda/versioned.ml
Another OCaml builtin type is `bytes`.
=> Add bytes type to version ppx

src/app/cli/src/coda_main.ml, src/lib/network_pool/network_pool.ml, src/lib/network_pool/snark_pool_diff.ml, src/lib/staged_ledger/staged_ledger.ml, src/protocols/coda_pow.ml
=> Remove asserted from deriving version for Snark_pool_diff

src/app/cli/src/coda_worker.ml, src/lib/coda_base/account.ml, src/lib/coda_base/stake_proof.ml, src/lib/signature_lib/private_key.ml
Removed `asserted` from `deriving version` in `Stake_proof`. Added a new `asserted` for `Private_key`, though.
=> Remove asserted from versioning in Stake_proof

frontend/wallet/src/App.re, frontend/wallet/src/AppWindow.re, frontend/wallet/src/Delete.re, frontend/wallet/src/MainCommunication.re, frontend/wallet/src/Messages.re, frontend/wallet/src/Modal.re, frontend/wallet/src/Page.re, frontend/wallet/src/RendererCommunication.re, frontend/wallet/src/Route.re, frontend/wallet/src/Router.re, frontend/wallet/src/Send.re, frontend/wallet/src/StyleGuide.re
Typesafe routes can be sent across the process boundary via a
`Deep_link` message.
Currently all deep links just open different modals. The modals are
simple absolutely positioned divs that sit on top of the whole
application.
Opening the modals from within the webapp works. Opening the modals from
within the tray while the webapp window is open works. Opening the
modals from the tray while the webapp window is closed works.
The MainCommunication and RendererCommunication files must be separate
modules, one for the renderer process (this consumes main communication
to communicate with the main process), and one for the main process
(this consumes renderer communication to communicate with the render
process).
Styling intentionally unimplemented for now.
=> Support for modals and deeplinking

src/lib/parallel_scan/state.ml, src/lib/ppx_coda/tests/versioned_good.ml, src/lib/ppx_coda/versioned.ml
Jane St stable modules of form `Core. ... . Stable.Vn` (or `Core_kernel`) are whitelisted in the version ppx.
Use this feature to remove the `asserted` in versioning of `Parallel_scan.State.t`.
=> Whitelist Jane St stable modules in version ppx

src/lib/network_peer/peer.ml, src/lib/network_pool/network_pool.ml
Use Jane Street `Stable` module for `Inet_addr` in `Peer` to get rid of `{asserted}`. Can no longer derive `hash`, so use the ones in the Jane Street implementation directly.
Also got rid of a couple of `unused value version` in `Network_pool`.
=> In Peer, remove asserted from deriving version

src/lib/transaction_snark/transaction_snark.ml
This switches off `reduce_to_prover`, which (hopefully) might fix #2224.
Checklist:
=> Switch off reduce_to_prover by default

src/lib/merkle_address/merkle_address.ml, src/lib/merkle_ledger/location.ml, src/lib/ppx_coda/versioned.ml
Whitelist `Bitstring` in the version ppx, so that we can remove `asserted` in `deriving version` for `Merkle_address`.
Wrote a unit test that compares the current serialization of a `Bitstring.t` value against one created when we added the whitelist (now, that is). If that ever changes (unlikely), we could wrap the library.
Also removed `bin_io` from `Merkle_address.t`.
=> Whitelist Bitstring; unit test to detect changes

src/lib/coda_base/sync_ledger.ml, src/lib/syncable_ledger/dune, src/lib/syncable_ledger/syncable_ledger.ml
Removed two `{asserted}` instances from `deriving version` in `Sync_ledger`.
=> Remove asserted from Sync_ledger deriving version

src/lib/ppx_coda/versioned.ml
Replace flattening function I'd written for `Longident` with one already available. It's tail-recursive, mine was not.
Checklist:
=> Use Longident flatten fun

src/lib/ppx_coda/tests/versioned_good.ml, src/lib/ppx_coda/versioned.ml
In Jane St libraries, the type `Time.Stable.Span.V1.t` doesn't conform to the format `M.Stable.V1.t`. We special-case this one, since it appears to be a stable versioned type.
=> Special-case Jane St library with unusual module path

.circleci/config.yml, .circleci/config.yml.jinja, frontend/wallet/.gitignore, frontend/wallet/__tests__/wallet_test.re, frontend/wallet/bsconfig.json, frontend/wallet/package-lock.json, frontend/wallet/package.json, frontend/wallet/src/App.re, frontend/wallet/src/AppWindow.re, frontend/wallet/src/Body.re, frontend/wallet/src/CallTable.re, frontend/wallet/src/CallTable.rei, frontend/wallet/src/FlatFileDb.re, frontend/wallet/src/MainCommunication.re, frontend/wallet/src/Messages.re, frontend/wallet/src/Modal.re, frontend/wallet/src/Page.re, frontend/wallet/src/PublicKey.re, frontend/wallet/src/PublicKey.rei, frontend/wallet/src/Route.re, frontend/wallet/src/Router.re, frontend/wallet/src/Settings.re, frontend/wallet/src/SettingsMain.re, frontend/wallet/src/SettingsMain.rei, frontend/wallet/src/SettingsRenderer.re, frontend/wallet/src/SettingsRenderer.rei, frontend/wallet/src/Tc.re
Add a CallTable to make it possible to `Task` across the IPC barrier
and used that to send/receive settings changes. For now, settings is
loaded just once from the tray, but can be updated by the Renderer as
many times as necessary.
Bs-json introduced for managing JSON encode/decode temporarily until we
can get something more automated (be it a ppx or some other sort of
preprocessor like quicktype).
Routes include the settings payload as a query parameter because rather
than being sent it as a separate message because we _need_ settings
information in order to do even the first render of the UI. For example,
imagine there is theming information in there.
Tested manually for now.
TODO: Make a custom react hook for the settings message
TODO: Introduce testing infrastructure and then write …
=> Introduce settings communication

src/lib/coda_base/account.ml, src/lib/coda_base/pending_coinbase.ml, src/lib/coda_base/proof.ml, src/lib/coda_base/sok_message.ml, src/lib/merkle_address/merkle_address.ml, src/lib/network_peer/peer.ml, src/lib/non_zero_curve_point/non_zero_curve_point.ml, src/lib/ppx_coda/define_locally.ml, src/lib/ppx_coda/tests/Makefile, src/lib/ppx_coda/tests/define_locally_good.ml, src/lib/ppx_coda/tests/dune, src/lib/snark_params/pedersen.ml, src/lib/sparse_ledger_lib/sparse_ledger.ml, src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
A ppx to eliminate boilerplate when mirroring definitions from another module.
Write:
```
[%%define_locally M.(x,y,z)]
```
which expands to
```
let x,y,z = M.(x,y,z)
```
I applied this at several places in the code.
Closes #2141
=> Ppx for mirroring definitions locally

frontend/wallet/src/CallTable.re
@cmr noticed that `incr` was applied to shared mutable state inside the
Task context which causes non-determinism.
=> Correctly mutates shared state

src/lib/snark_worker_lib/prod.ml
This prints out the snark worker spec when there is a failure to aid in debugging https://github.com/CodaProtocol/coda/issues/2224
=> print out spec on snark worker failure

src/lib/snark_work_lib/work.ml, src/lib/snark_worker_lib/prod.ml
Make snark worker spec non-opaque for sexp. This is to aid in debugging a SNARK assertion failure @jkrauska had seen
=> Make snark worker spec non-opaque for sexp

src/app/cli/src/coda_main.ml
Spotted a place to use `define_locally` in `Coda_main`.
=> Use define_locally in Coda_main

frontend/wallet/__tests__/wallet_test.re, frontend/wallet/src/AppWindow.re, frontend/wallet/src/CallTable.re, frontend/wallet/src/CallTable.rei, frontend/wallet/src/MainCommunication.re, frontend/wallet/src/MainCommunication.rei, frontend/wallet/src/Messages.re, frontend/wallet/src/Page.re, frontend/wallet/src/SettingsRenderer.rei
CallTable now is typed with GADTs and handles the settings changes by
the tray process responding with the new settings.
Luckily we only need to update the settings after the application starts
via changes initiated by the render process. Whenever this is no longer
true we'll need to handle the extra messages and correctly call
`setSettingsOrError`.
=> Settings reactively updates across processes

frontend/wallet/src/Body.re, frontend/wallet/src/ConsensusState.re, frontend/wallet/src/PublicKey.re, frontend/wallet/src/PublicKey.rei, frontend/wallet/src/StyleGuide.re, frontend/wallet/src/TransactionCell.re, frontend/wallet/src/TransactionsView.re
Logic in place for rendering all transactions in the spec.
Some layout is completed, but styling still needs a ton of work.
Tables were used as this is semantically a table, but it's unclear
whether it should just all be flex or not.
`TransactionsView` for now just hardcodes all the cells present in
the mockup to make sure we can look at all of them (for the
purposes of testing).
=> Put logic in place for transactions view

frontend/wallet/src/Delete.re, frontend/wallet/src/ModalButtons.re, frontend/wallet/src/Page.re, frontend/wallet/src/Send.re, frontend/wallet/src/StyleGuide.re, frontend/wallet/src/Wallet.re
Content in place for Send/Delete modals. Cancel button correctly closes
the modals and clicking outside the content window also closes.
ModalButtons are reused between the two modal states and it seems like
this is the only area with that style Button is used, so I inlined the
"Button" definition in the ModalButtons module.
TODO: to add the + Add memo button on the Send modal
=> Add content to Send/Delete modals

src/lib/coda_networking/coda_networking.ml
In `Coda_networking`, replaced one call of `Logger.faulty_peer` with a call to `Trust_system.record`.
Another, I changed to `Logger.error`, since it's not clear to me it's worthy of punishment.
Checklist:
=> Replace faulty_peer by trust system record in Coda_networking

src/lib/ledger_catchup/ledger_catchup.ml, src/lib/transition_frontier_controller/transition_frontier_controller.ml, src/lib/transition_frontier_controller_tests/test_ledger_catchup.ml, src/lib/transition_router/transition_router.ml, src/protocols/coda_transition_frontier.ml
Replace `Logger.faulty_peer` with calls to trust system in `Ledger_catchup`.
Checklist:
=> Ledger catchup uses trust system

src/app/cli/src/coda_bootstrap_test.ml, src/app/cli/src/coda_process.ml, src/app/cli/src/coda_worker.ml, src/app/cli/src/coda_worker_testnet.ml, src/lib/coda_lib/coda_lib.ml, src/lib/sync_status/dune, src/lib/sync_status/sync_status.ml
A test to show that subscriptions work
Checklist:
Closes #0000
Closes #0000
=> Integrate sync status to bootstrap test

src/lib/coda_networking/coda_networking.ml
Reward preferred, nonpreferred peers returning valid responses to RPC calls.
=> Reward response in RPC calls

src/app/cli/src/ledger_proof.ml
`version` is derived automatically from the `deriving version`, the definition is shadowed, so unused.
Checklist:
=> Remove unused version number in Ledger_proof

src/app/cli/src/coda.ml, src/app/cli/src/coda_inputs.ml, src/app/cli/src/coda_run.ml, src/app/cli/src/coda_worker.ml, src/app/cli/src/full_test.ml, src/app/cli/src/graphql.ml, src/lib/coda_lib/coda_lib.ml
This exposes the snark worker fee and public key when the node has the public key set.
Had to change a couple of places to track the pub key of the snark worker rather than just whether one was running. Feel free to lmk if there's a better way to get it.
=> Add currentSnarkWorker to graphql api

src/app/cli/src/coda.ml, src/app/cli/src/graphql.ml, src/lib/secrets/wallets.ml, src/lib/secrets/wallets.mli
For now, in order to keep things simple, the frontend will restart the
daemon process whenever we wish to switch proposers.
Since the frontend doesn't track private keys, this change will allow
the frontend to start the daemon with propose keys from our tracked
wallet.
=> Support proposing from wallet db

src/app/cli/src/graphql.ml, src/lib/coda_numbers/account_nonce.ml
This includes everything inside the ledger as well as the unknown
balance which for now is the same as the total balance.
Implied schema:
```
type Wallet {
publicKey: String!
balance: AnnotatedBalance!
nonce: String!
receiptChainHash: String!
delegate: String!
participated: Boolean!
}
type AnnotatedBalance {
total: String!
unknown: String!
}
```
=> Wallet graphql API has full account info

src/lib/transaction_snark/transaction_snark.ml, src/lib/transaction_snark/transaction_snark.mli
=> Remove unused binio in transaction_snark

src/lib/coda_base/pending_coinbase.ml, src/lib/coda_base/proof.ml, src/lib/coda_base/snark_transition.ml, src/lib/coda_base/sparse_ledger.ml, src/lib/coda_base/staged_ledger_hash.ml, src/lib/coda_base/user_command.ml, src/lib/coda_networking/coda_networking.ml, src/lib/coda_numbers/nat.ml, src/lib/consensus/proof_of_signature.ml, src/lib/currency/currency.ml, src/lib/currency/currency.mli, src/lib/lite_base/nat.ml, src/lib/merkle_address/merkle_address.ml, src/lib/module_version/registration.ml, src/lib/network_pool/network_pool.ml, src/lib/network_pool/snark_pool_diff.ml, src/lib/ppx_coda/versioned.ml, src/lib/random_oracle/random_oracle.mli, src/lib/snark_params/pedersen.ml, src/lib/sparse_ledger_lib/sparse_ledger.ml, src/lib/staged_ledger/staged_ledger.ml, src/lib/staged_ledger/staged_ledger_diff.ml, src/lib/staged_ledger/transaction_snark_work.ml, src/lib/transaction_pool/transaction_pool.ml, src/lib/unsigned_extended/unsigned_extended.ml, src/protocols/coda_pow.ml
Get rid of "unused value version" warnings as much as possible.
- for versioned types with type parameters, `let version =` is not generated, because we don't register those types; you don't have to write `unnumbered` for these types to get rid of the warning
- in signatures, by default, `val version : int` is not generated, because the only code that needs the version number is the registration machinery; the option "numbered" allows generation of that declaration
- the option `for_tests` implies `asserted`, as before, and now also `unnumbered`
Running `make build` in this branch results in 0 such warnings.
=> Fewer value version warnings

src/lib/gossip_net/gossip_net.ml, src/lib/trust_system/trust_system.ml
Each connection attempt to the TCP server results in a decrease in trust. That helps mitigate against DoS attacks. It also can lead to a ban if a node repeatedly makes a versioned RPC call with no common versions.
The decrease in trust of a connection and request equals the increase in trust of a fulfilled request. Before this PR, a request and fulfillment balanced one another.
=> Decrease in trust on TCP connection

src/lib/gossip_net/gossip_net.ml
Handler for TCP server doesn't allow connections from banned peers.
=> Don't allow banned peers to connect

src/lib/coda_lib/coda_lib.ml, src/lib/consensus/intf.ml, src/lib/consensus/proof_of_stake.ml, src/lib/proposer/proposer.ml, src/lib/trust_system/trust_system.ml, src/protocols/coda_pow.ml
For postake, in `sync_local_state`, reward peers providing an epoch ledger. There's a new constructor, `Epoch_ledger_provided` for this purpose. Tentatively, that gives 10x the reward of `Fulfilled_request`.
=> Trust increase when epoch ledger provided in postake

src/lib/consensus/proof_of_stake.ml, src/lib/snark_worker_lib/rpcs.ml
remove an unneeded `unnumbered` from `deriving version`; add one that is needed
for snark worker RPCs, change module names to `Master`, as we did in `Coda_networking`
=> Fix version warnings; rename RPC modules to Master

src/opam.export
`opam switch src/opam.export` on ocaml version `4.07.1` should work again.
=> Remove unused opam.export deps

src/lib/unsigned_extended/unsigned_extended.ml
Tying up a loose end for versioning.
`Unsigned` is the one place we still have a hand `let _versioned__ = true` declaration, because the whitelisting strategy we use for external modules won't work here: we're passing in the external module, rather than using it in a versioned type.
So we leave in that declaration, and add tests to verify the serializations haven't changed.
Also removed an unused functor, which was generating several compile warnings.
=> Unsigned serialization tests

src/lib/staged_ledger/staged_ledger.ml
We added code to invoke the trust system on staged ledger errors in #2372, including the invalid proof error.
So the punish comment in `Staged_ledger` is no longer a `TODO`.
=> Staged ledger, remove punish comment

frontend/wallet/.gitignore, frontend/wallet/package-lock.json, frontend/wallet/package.json, frontend/wallet/rollup.config.js, frontend/wallet/src/main/ProjectRoot.re
This reduces the wallet dist package size from ~500mb to ~140mb by packing our main process js so that we don't need to include any of the node_modules.
Unfortunately this meant we needed another packer, because fastpack doesn't support packing nodejs packages. Rollup is pretty [light](https://bundlephobia.com/result?p=rollup@1.11.3) so I pulled that in for now. It's slower than fastpack but we only rely on it when building the dist.
=> Wallet: Reduce dist package size

frontend/wallet/src/main/App.re
Tested by making sure `npm run dev` actually starts the client properly.
=> App runs again

scripts/getkeys.sh
Previously we were echoing too much in CI re creds for keys.
=> TRIVIAL: reduce debug of cred info

frontend/wallet/package.json, frontend/wallet/src/common/Bindings.re, frontend/wallet/src/main/App.re, frontend/wallet/src/main/AppWindow.re, frontend/wallet/src/main/ProjectRoot.re, frontend/wallet/src/render/Preload.re
Funnel project root settings path through a query parameter.
The dist builds are happy about preload.js, but fail because the file doesn't exist in `Application Support`.
No more hacking the bool to false in any case.
Made sure `make dev` still works as well.
=> Dist builds preload happy

frontend/wallet/package.json, frontend/wallet/src/main/App.re, frontend/wallet/src/main/DaemonProcess.re
Removes wallet listing from tray menu, removes lag before the tray menu icon appears, fixes graphql-faker in the dist build.
The reducer isn't really used for anything now that we don't use any state in the menu, but I left it in because eventually we'll be subscribing to sync status.
=> Clean up tray menu

frontend/wallet/src/render/components/Header.re, frontend/wallet/src/render/components/TransactionCell.re, frontend/wallet/src/render/components/TransactionsView.re
**What changed**
Updates the `TransactionList` to use CSS Grids instead of `<table>`. Cleans up some styles as well.
=> Refactor TransactionsView to use CSS Grid

frontend/wallet/schema.graphql
In order to support delegation in a simpler way, we've expanded the payments api to support delegations as well.
Since they contain almost exactly the same fields, it seems overkill to use a union type for this currently, we differentiate using a bool and set the amount to 0 when it's a delegation.
=> Change payment to user command in graphql schema

frontend/wallet/src/render/Theme.re, frontend/wallet/src/render/components/TransactionCell.re, frontend/wallet/src/render/components/TransactionsView.re
Transaction cells mostly look like the spec now. Ignore my scrollbar thing, it's specific to my computer and we're not sure why it's happening.
Given that we may change the treatment on the unknown amount cell, I avoided special casing the alignment of that one for now.
=> Cleans up styles on transaction cells

frontend/wallet/README.md
Explain your changes here:
Make it clear within the readme that you must clone the Coda repo via SSH to successfully run `git submodule...`
Explain how you tested your changes here:
Initially cloned the repo via HTTPS, and failed to build the wallet. Then tried SSH and was successful.
Checklist:
Closes #0000
Closes #0000
=> Wallet: Clone repo via SSH only

src/lib/cache_lib/impl.ml
A 1-line change in cache_lib. We should enable peek for consumed/transformed items. This would fix a bug in ledger breadcrumb_builder.ml
=> we can peek at cache that is already consumed but not yet finalized

src/lib/coda_lib/coda_lib.ml, src/lib/consensus/dune, src/lib/consensus/intf.ml, src/lib/consensus/proof_of_stake.ml, src/lib/lite_compat/lite_compat.ml, src/lib/staged_ledger_diff/dune, src/lib/staged_ledger_hash/dune, src/lib/staged_ledger_hash/staged_ledger_hash.ml, src/lib/staged_ledger_hash/staged_ledger_hash.mli, src/lib/transition_frontier_controller_tests/stubs.ml, src/lib/transition_frontier_controller_tests/test_transition_frontier_persistence.ml, src/lib/transition_frontier_persistence/transition_frontier_persistence.ml, src/staged_ledger_hash.opam
- Fixed it by computing the genesis ledger_hash correctly in
staged_ledger_hash
Made a failing test in test_transition_frontier_persistence for this fix
You can also verify this when starting the daemon. Then killing it. And then starting it again.
Checklist:
=> Fixed mismatching merkle root when starting daemon

src/app/cli/src/coda_inputs.ml, src/lib/transaction_pool/dune
The `Snark_worker_lib` was removed at some point. I'm surprised OCaml lets you reference a module that doesn't actually exist but apparently it does. Nathan also added back a dependency on `core_kernel.fheap` in transaction pool when he did the validation refactor, but I removed all use of that with the rewrite.
=> Clean up some dead code/dependencies

src/banlist_lib.opam, src/ccc.opam, src/echo.opam, src/ledger_builder_controller.opam, src/merkle_database.opam, src/pending_coinbase_lib.opam, src/spawner.opam, src/stdout.opam
We had a bunch of dead .opam files laying around. Here's the bash incantation I used to find them:
`for x in src/*.opam; do if ! [ -d $(sed -E 's/src\/([[:alnum:]_]+)\.opam/src\/lib\/\1/' <<< $x) ]; then echo $x; fi; done`
It returns false positives for libraries that aren't in `src/lib/`.
=> Remove a bunch of dead .opam files

src/lib/coda_base/stake_proof.ml, src/lib/consensus/proof_of_stake.ml, src/lib/non_zero_curve_point/non_zero_curve_point.ml, src/lib/signature_lib/public_key.mli
As a step in debugging the delegation integration test under development, add `public_key` to the prover state, and assert in the `Checked` world that this key and the delegate seen in VRF evaluation are the same.
This change probably won't allow the test to succeed, though.
Also changed some `deriving` clauses to remove warnings.
=> Add public key to prover state; assert equality of delegate, pubkey

src/lib/ledger_catchup/ledger_catchup.ml, src/lib/transition_frontier_controller/transition_frontier_controller.ml, src/lib/transition_frontier_controller_tests/test_catchup_scheduler.ml, src/lib/transition_frontier_controller_tests/test_ledger_catchup.ml, src/lib/transition_handler/catchup_scheduler.ml, src/lib/transition_handler/processor.ml, src/lib/transition_router/transition_router.ml, src/protocols/coda_transition_frontier.ml
This PR makes catchup pipes (catchup_job/catchup_breadcrumbs) buffered so that async jobs won't be blocked.
=> make catchup pipes buffered

src/app/cli/src/graphql.ml
1. ownedWallets now also returns accounts that aren't found in the best
ledger.
2. More consistent naming of graphql endpoints
3. userCommand query doesn't crash on public keys that don't exist
Tested via running graphiql on the daemon node.
=> Various small fixes to graphql behavior

frontend/wallet/.gitattributes, frontend/wallet/package.json, frontend/wallet/public/fonts/IBMPlexSans-Medium-Latin1.woff, frontend/wallet/public/fonts/IBMPlexSans-Medium-Latin1.woff2, frontend/wallet/public/fonts/IBMPlexSans-Regular-Latin1.woff, frontend/wallet/public/fonts/IBMPlexSans-Regular-Latin1.woff2, frontend/wallet/public/fonts/OCR A Std Regular.ttf, frontend/wallet/public/index.html, frontend/wallet/src/render/Theme.re
Only bundles the sizes used in the Theme.re file. Doesn't bundle lucida grande because of https://superuser.com/a/486347, we should come up with another solution for this (fallback font or use something else).
Tested it on the dist build and it works there too.
=> Wallet: bundle fonts

src/app/cli/src/coda_commands.ml, src/app/cli/src/graphql.ml, src/lib/transaction_database/intf.ml, src/lib/transaction_database/transaction_database.ml
I made this feature last week, but forgot to push it into our codebase.
I tested the persistence features on a unit test. 
Checklist:
=> Added persistence feature to transaction_database

src/lib/one_or_two/dune, src/lib/one_or_two/intfs.ml, src/lib/one_or_two/one_or_two.ml, src/lib/one_or_two/one_or_two.mli, src/one_or_two.opam
I wrote this for some refactoring of the transaction snark and snark work code, but since that work involves messing with a lot of signatures and the signatures are currently in flux I'm going to set it aside for a bit. Let's merge the library now.
=> Create One_or_two library

src/lib/transition_router/transition_router.ml
After reading the transition router code more carefully. I decided to only do the change that would make "valid transitions" non-block instead of doing a rewrite of the entire file.
This patch should fix the pipe overflow bug in the testnet.
=> [WIP] make the "valid transitions" pipe non-blocking

frontend/website/src/Links.re
Already deployed. See codaprotocol.com and notice that the whitepaper link is no longer dead (points to v2 of cdn assets)
=> Fix dead whitepaper link

frontend/wallet/src/common/PublicKey.re, frontend/wallet/src/render/Preload.re, frontend/wallet/src/render/Theme.re, frontend/wallet/src/render/components/AddWalletModal.re, frontend/wallet/src/render/components/AddressPill.re, frontend/wallet/src/render/components/Button.re, frontend/wallet/src/render/components/Dropdown.re, frontend/wallet/src/render/components/Link.re, frontend/wallet/src/render/components/SendButton.re, frontend/wallet/src/render/components/SettingsPage.re, frontend/wallet/src/render/components/TextField.re, frontend/wallet/src/render/components/TransactionCell.re, frontend/wallet/src/render/components/TransactionsView.re, frontend/wallet/src/render/components/WalletSettings.re
Some more work on settings that I wanted to get done.
- Fixed styling for the daemon version
- Added ability for textfields to have a button
- Copy is hooked up (could use an indicator that the copy happened, after the click)
- Open file is hooked up to the file explorer (right now it opens the location of the executable lol)
- Fixed several styling things
- Added some made-up hover styles to the wallet list selector in general settings -- in general it seems like we need to put some work into getting hover and focus styles for all the interactive elements (and active?)
=> Wallet: Finish up initial settings pass

src/app/cli/src/coda_run.ml
It's not very interesting and something is causing it to emit
way too many trace events (#2583).
=> Turn off tracing for Get_status RPC

src/lib/bootstrap_controller/bootstrap_controller.ml, src/lib/consensus/intf.ml, src/lib/consensus/proof_of_stake.ml
I changed the required_local_state_sync function so that there's no longer a special case for `genesis ledger`.
Close #2581
=> Simplify local_state logic

frontend/wallet/schema.graphql, src/app/cli/src/graphql.ml, src/lib/secrets/wallets.ml, src/lib/secrets/wallets.mli
Here are the commands showing that the private key path is correct.
```graphql
mutation {addWallet{publicKey}}
```
```graphql
{
"data": {
"addWallet": {
"publicKey": "ASgu5t5hlbjC3DZYZ87tASbUX+mGXJUpp+uekWKwtxlJbHxGuedIAQAAAQ=="
}
}
}
```
```graphql
{ownedWallets{publicKey, privateKeyPath}}
```
```
{
"data": {
"ownedWallets": [
{
"publicKey": "ASgu5t5hlbjC3DZYZ87tASbUX+mGXJUpp+uekWKwtxlJbHxGuedIAQAAAQ==",
"privateKeyPath": "/Users/johnwu/.coda-config/wallets/store/ASgu5t5hlbjC3DZYZ87tASbUX+mGXJUpp+uekWKwtxlJbHxGuedIAQAAAQ=="
}
]
}
}
```
This is a valid path showing the public key:
```
ls /Users/johnwu/.coda-config/wallets/store/ASgu5t5hlbjC3DZYZ87tASbUX+mGXJUpp+uekWKwtxlJbHxGuedIAQAAAQ==
/Users/johnwu/.coda-config/wallets/store/ASgu5t5hlbjC3DZYZ87tASbUX+mGXJUpp+uekWKwtxlJbHxGuedIAQAAAQ== …
```
=> Added private key path to wallet type

src/lib/consensus/intf.ml, src/lib/consensus/proof_of_stake.ml, src/lib/transition_router/initial_validator.ml
Log an `error` message when we see an external transition with the same proposer and slot, but a different protocol state hash.
There's a table mapping proposers and slots to the hashes. It's flushed when we see a new epoch, so the table does not grow without bound. (Apparently, there's a smaller window of slots, but I worry about network lag so we might see transitions outside what we think the current window is.)
To achieve this, `Consensus` exports a function to get the epoch and slot (as an option), slightly tarnishing the consensus abstraction.
Closes #2467
=> Log error when duplicate proposer, slot

src/lib/merkle_mask/dune
Remove the `flags` clause in `Merkle_mask`, no errors result.
=> Merkle mask, remove warn-error

src/lib/coda_base/data_hash.ml, src/lib/coda_base/data_hash.mli, src/lib/coda_base/dune, src/lib/coda_base/how_to_obtain_keys.ml, src/lib/coda_base/ledger.ml, src/lib/coda_base/pending_coinbase.ml, src/lib/coda_base/sparse_ledger.ml, src/lib/coda_base/timeout.ml, src/lib/coda_base/transaction_logic.ml, src/lib/coda_base/transaction_validator.ml, src/lib/coda_base/user_command.ml, src/lib/coda_base/user_command.mli, src/lib/coda_base/user_command_intf.ml
Remove the dune `flags` clause containing `warn-error` in `Coda_base`. Fix the code to remove the resulting errors.
Most of the changes are simple. There are two dead-code removals, which we may want to keep. One is `gen` in `User_command`, the other is `add_fee` in `Transaction_logic`.
=> Coda_base, remove warn-error clause

src/app/cli/src/client.ml, src/app/cli/src/coda.ml, src/app/cli/src/coda_batch_payment_test.ml, src/app/cli/src/coda_block_production_test.ml, src/app/cli/src/coda_bootstrap_test.ml, src/app/cli/src/coda_commands.ml, src/app/cli/src/coda_delegation_test.ml, src/app/cli/src/coda_five_nodes_test.ml, src/app/cli/src/coda_inputs.ml, src/app/cli/src/coda_long_fork.ml, src/app/cli/src/coda_peers_test.ml, src/app/cli/src/coda_process.ml, src/app/cli/src/coda_processes.ml, src/app/cli/src/coda_receipt_chain_test.ml, src/app/cli/src/coda_restart_node_test.ml, src/app/cli/src/coda_restarts_and_txns_holy_grail.ml, src/app/cli/src/coda_run.ml, src/app/cli/src/coda_shared_prefix_multiproposer_test.ml, src/app/cli/src/coda_shared_prefix_test.ml, src/app/cli/src/coda_shared_state_test.ml, src/app/cli/src/coda_transitive_peers_test.ml, src/app/cli/src/coda_worker.ml, src/app/cli/src/coda_worker_testnet.ml, src/app/cli/src/dune, src/app/cli/src/find_ip.ml, src/app/cli/src/full_test.ml, src/app/cli/src/graphql.ml, src/app/cli/src/transaction_snark_profiler.ml, src/dune
Remove the `flags` clause in `app/cli/src/dune` and fixed the resulting errors.
Some concerns:
- the clause also had `-g`, which is useful when OCaml better supports gdb, maybe this should be global, and maybe just for some profiles
- `Coda_process.local_config` has an unused optional parameter `proposal_interval`, should that just be removed, or should it be used somehow
- `Client` had a variable `sexp_logging` that was unused, is that an oversight?
=> In cli, remove warn-error

src/app/reformat/dune, src/app/reformat/reformat.ml, src/dune
In `app/reformat`, use the same warnings list as in `src/dune`. Fix the resulting error.
=> Reformat, use src/dune warnings

src/external/ocaml-rocksdb/dune, src/external/ocaml-rocksdb/rocks.ml
The `dune` file for ocaml-rocksdb had `-warn-error -A`, turning off all warnings-as-errors. This PR removes that, and fixes the few errors that appeared as a result.
=> ocaml-rocksdb, warnings as errors

src/lib/coda_base/gen/dune, src/lib/coda_base/gen/gen.ml, src/lib/crypto_params/gen/dune, src/lib/crypto_params/gen/gen.ml, src/lib/dummy_values/gen_values/dune, src/lib/dummy_values/gen_values/gen_values.ml, src/lib/precomputed_values/gen_values/dune, src/lib/snark_keys/gen_keys/dune, src/lib/snark_keys/gen_keys/gen_keys.ml, src/lib/snark_keys/remove_snark_keys_trigger/clear_keys/clear_keys.ml, src/lib/snark_keys/remove_snark_keys_trigger/clear_keys/dune
Remove the `flags` clause containing `-warn-error` from `dune` files in subdirectories of libraries.
After this PR is merged, there should be no warnings when building the `coda` repo.
=> Remove warn-error from lib subdir dunes

src/lib/transition_frontier_controller_tests/test_transition_frontier_persistence.ml, src/lib/transition_frontier_persistence/transition_frontier_persistence.ml
In the TF persistence layer, `with_db` was not using the `Async` monad to obtain the result of the function passed to it, so that database operations could occur after the database had been closed, which resulted in `InvalidObject` exceptions in RocksDB. 
Also, a couple of little cleanups suggested by @johnwu are in this PR.
=> Close database after async fun finishes

src/lib/crypto_params/dune, src/lib/crypto_params/gen/dune, src/lib/crypto_params/gen/gen.ml
Generate the group map parameters at compile time. This must be merged before https://github.com/CodaProtocol/coda/pull/2556.
=> Group map parameters at compile time

src/dune
Replace the ML file `src/dune`, which generated a `dune` file to pass to dune via a plugin feature, with a static file.
The generated file had an identical warnings list for each profile, plus some boilerplate. The static file uses a wildcard to represent all profiles, plus the same boilerplate.
The static file produces the same results.
Closes #2619.
=> Static dune file

src/app/cli/src/coda.ml, src/lib/coda_lib/coda_lib.ml
The proposer has trouble doing bootstrap, see #2642. This is a hack to make the proposer wait for `k` slots to make sure that it would be synced before trying to propose.
The proper change would require us to do some kind of bootstrap eagerly before start the proposer. I still need some time to think about the changes needed to be done.
=> Hack: DO NOT propose until it sync'd with the network

frontend/wallet/.gitignore, frontend/wallet/__tests__/wallet_test.re, frontend/wallet/package.json, frontend/wallet/src/common/Bindings.re, frontend/wallet/src/main/DaemonProcess.re
Copied from comment in the PR:
>child_process.spawn communicates with processes using sockets.
When the proposer process starts up in the daemon, stdout and stderr
are accessed using a helper function from async_unix:
https://github.com/janestreet/async_unix/blob/ff13d69c96f4b857737263910b3f6b08311b5dfc/src/writer0.ml#L1465
This causes async_unix to attempt to infer the type of stdout/err
using and check if it has SO_ACCEPTCONN set using getsockopt.
This flag is not supported on Mac, so it crashes with "Protocol not available"
As a workaround, we have to redirect all output to a file.
If this issue is ever resolved or we stop using async_unix, this code can be simplified:
https://github.com/janestreet/async_unix/issues/15
This bug is triggered by something in the proposer process. The …
=> Wallet: workaround for daemon crash on spawn

src/lib/consensus/proof_of_stake.ml
This is a hack to disable min_length_of_epoch check in consensus selection rule. See #2643
=> Hack: disable min_length_of_epoch check in consensus.select

frontend/wallet/src/common/Route.re, frontend/wallet/src/main/App.re, frontend/wallet/src/main/AppWindow.re, frontend/wallet/src/render/CodaProcess.re, frontend/wallet/src/render/ReactApp.re, frontend/wallet/src/render/components/Dropdown.re, frontend/wallet/src/render/contexts/ProcessDispatchProvider.re, frontend/wallet/src/render/views/settings/NetworkDropdown.re, frontend/wallet/src/render/views/settings/SettingsPage.re
Another step towards connecting to the daemon.
Converts the coda dispatch reducer to a hook instead of a wrapper component and makes a context for the dispatch function.
Now setting the network in the UI restarts the coda daemon. This doesn't work 100% yet but at least exercises the restart code.
Next PR will make it a little possible to run everything against the daemon (optionally).
The network dropdown is somewhat messy, we should look into seeing what it would take to be able to change this from graphql before doing too much more work to patch it (as with the multi-proposers).
Also:
- Fix the deeplink from the taskbar menu
=> Wallet: Hook network to faker

frontend/wallet/package.json, frontend/wallet/schema.graphql, frontend/wallet/src/common/Bindings.re, frontend/wallet/src/main/App.re, frontend/wallet/src/main/DaemonProcess.re, frontend/wallet/src/render/Apollo.re, frontend/wallet/src/render/components/Header.re, frontend/wallet/src/render/components/SideBar.re, frontend/wallet/src/render/views/footer/Footer.re, frontend/wallet/src/render/views/settings/NetworkDropdown.re, frontend/wallet/src/render/views/settings/SettingsPage.re, frontend/wallet/src/render/views/transactions/TransactionCell.re, frontend/wallet/src/render/views/transactions/Transactions.re, scripts/macos-portable.sh, src/app/cli/src/graphql.ml
The wallet build and runs with all endpoints pointing to the daemon!
You can still run against the faker by running `GRAPHQL_BACKEND=faker yarn dev`. As soon as we get the daemon running in the dist properly, I'll remove the faker stuff from the dist.
I could swap the default but this is probably what we want eventually lol
=> Wallet: connect to daemon by default

src/app/cli/src/client.ml, src/app/cli/src/coda_commands.ml, src/app/cli/src/coda_run.ml, src/lib/cli_lib/arg_type.ml, src/lib/daemon_rpcs/daemon_rpcs.ml, src/lib/trust_system/banned_status.ml, src/lib/trust_system/peer_status.ml
Plain text output:
```
coda.exe client get-trust-status -ip-address 192.168.1.1
0.0000, Unbanned
```
JSON:
```
coda.exe client get-trust-status -ip-address 192.168.1.1 -json
{"trust":0.0,"banned":"Unbanned"}
```
Since `Trust_system.Peer_status.t` needs `bin_io` to support this, that becomes a versioned type. But there's an issue versioning `Banned_status.t`, because `Time.t` in `Core` is not versioned, so versioning there is asserted for now. There is a `Time.Stable.some-other-type.V2.t`, which we can probably use, but the version ppx will need changes to handle that.
Partially implements #2658.
=> Add get-trust-status facility to client

src/app/cli/src/coda.ml, src/lib/secrets/wallets.ml, src/lib/secrets/wallets.mli
Only occurs when `-unsafe-track-propose-key` is passed as this is an
unsafe operation that currently strips the passwords from private keys.
Reuses existing key generation code, so not too large of a change.
=> Support tracking pre-existing propose sks

src/app/cli/src/client.ml
We were getting JSON output with miniscule trust scores, like `3.e-6`. Moreover, the tiny values were not being considered as equal to 0.0.
So we always round the trust scores to 4 significant digits, and use an approximate equality against 0 for filtering.
=> Always round trust scores, actually filter out zeroes

src/app/cli/src/client.ml
Same rounding of trust score to 4 decimal digits for one IP, as we have when looking at all trust scores.
=> Round trust score for one IP

src/app/cli/src/graphql.ml, src/lib/base58_check/base58_check.ml, src/lib/base58_check/base58_check.mli, src/lib/codable/codable.ml, src/lib/signature_lib/public_key.mli
Mainly acheived via exposing a safe Base58_check.decode and using that
in the graphql layer as much as possible.
Tested with the following query (which used to crash the backend)
```
{
blocks(after:"", filter:{relatedTo:"8QnLW56B6DaMYMcqgSWhPWf2DDmoFDYHStgZ4NEz2N9nEwnNs4SUJgPsUdGcgvjwsu"}){
totalCount
}
}
```
We now get an error message (that could be improved to report on which field the error occurred in, but that can be done as part of a larger error cleanup later)
```
{
"errors": [
{
"message": "Invalid cursor data (Invalid base58 check length)",
"path": [
"blocks"
]
}
],
"data": null
}
```
=> Purge uncaught exns in GraphQL layer

src/app/cli/src/graphql.ml, src/lib/base58_check/base58_check.ml, src/lib/base58_check/base58_check.mli, src/lib/coda_base/proof.ml, src/lib/codable/codable.ml, src/lib/random_oracle_base/random_oracle_base.ml, src/lib/signature_lib/private_key.ml, src/lib/staged_ledger_hash/staged_ledger_hash.ml
Instead of returning the version byte when decoding a Base58Check string, pass the version byte to the decoder, which checks that the byte is valid. That saves callers the responsibility of verifying the version byte. 
Add an exception `Invalid_base58_version_byte`, which the decoder raises if the byte doesn't match the decoded version byte.
=> Pass version byte to base58 decode

src/lib/transition_frontier_persistence/transition_frontier_persistence.ml
The mismatched hashes for mutant diffs resulted in failures. Until that mismatch is fixed, we just log an error for now.
=> Mutant diff hash mismatch logged only

src/lib/coda_version/gen.sh
`.git` is not a directory if you're using worktrees, so the script would fail. We rely on the exit status of `git rev-parse` to fail when not in a git repo in the new version. `set -e` makes non-zero exits inside `$(foo)` cause the script to fail. Also fixed possible issue if `$1` has spaces.
=> Fix coda_version gen.sh when using git worktree

src/lib/consensus/intf.ml, src/lib/consensus/proof_of_stake.ml, src/lib/transition_router/transition_router.ml
`should_bootstrap` function should always consult consensus first; otherwise, malicious user can trigger bootstrapping on arbitrary nodes by sending out fake transitions with a large `blockchain_count`.
Close #2696
=> make should_bootstrap ask consensus first

src/app/cli/src/coda.ml, src/lib/snark_keys/dune, src/lib/snark_keys/gen_keys/gen_keys.ml
New CLI command `internal snark-hashes [-json]`.
Lists the unique hex strings/hashes that appear in the proving, verification key filenames for the blockchain and transactions.
This PR partly addresses #1492 (nothing to do with Columbus or Isabella, I believe).
Text output:
```
coda.exe internal snark-hashes
1fcfafce88045da8edb21ca60f16364e
5cb02d2fce6f6865d9459434c8279373
791dd47158e4dad32059f8b6d5fef4e8
d54a391ecc01065ad98c490ec10fe56c
d7cee32fe1dccee1745b0c8cc6bbd3b8
```
JSON:
```
coda.exe internal snark-hashes -json
["1fcfafce88045da8edb21ca60f16364e","5cb02d2fce6f6865d9459434c8279373","791dd47158e4dad32059f8b6d5fef4e8","d54a391ecc01065ad98c490ec10fe56c","d7cee32fe1dccee1745b0c8cc6bbd3b8"]
```
There's meaningful output only at full proof level. Otherwise, the list of hashes is empty.
=> CLI command snark-hashes in internal group

src/lib/storage/disk.ml
This increases the maximum file size we will read from disk to 2.5GB. The largest key I've seen generated is 1.1GB, so this gives us plenty of headroom.
Digging into the source of `load_bin_prot`, it is only used to throw an error when a file over that size is met, so this shouldn't be an issue (as long as the user has enough RAM).
Checklist:
=> Bump maximum read size

src/app/cli/src/graphql.ml, src/lib/base58_check/version_bytes.ml, src/lib/coda_base/dune, src/lib/coda_base/user_command.ml, src/lib/coda_base/user_command_memo.ml, src/lib/coda_base/user_command_memo.mli, src/lib/coda_base/user_command_payload.ml, src/lib/network_pool/indexed_pool.ml, src/lib/network_pool/transaction_pool.ml, src/lib/random_oracle/random_oracle.ml, src/lib/random_oracle_base/random_oracle_base.ml, src/lib/transaction_snark/transaction_snark.ml
Allow arbitrary 32-byte strings in user command memos. Can still pass an arbitrary string (up to a max length) to digest.
Can use a `bytes` or `string` to create a memo, the length is checked. 
Length violations raise exceptions.
Perhaps problematic: some code from `Random_oracle.Digest` can't be used directly, so there's a modicum of copied code. There could be a functor to factor out that small amount of commonality, but I'm hesistant to introduce more functors.
Update: the code is different enough that it can't really be shared by functorization.
Closes #2660
Closes #2701
=> Arbitrary 32-byte contents in memos

.circleci/config.yml, .circleci/config.yml.jinja, scripts/link-coredumps.sh
There was an entry in the Circle config file to create artifacts from core files, but it didn't work. First, the core files were not generated in the git root directory, and second, the regexp syntax `core*` doesn't seem to be supported.
Circle does support creating artifacts by giving a directory name, as we were already doing for `test_logs`. If the unit tests fail, a new script `link-coredump.sh` is run, which creates the directory `core_dumps`, and puts in symlinks to each generated core file. Those files are apparently named `core.PID.something`.
The `&& false` in the config entry makes sure that if the unit test fails, the result is still a failure after running that script.
Tested by creating a unit test that segfaults (via `Obj.magic`), and verifying that the artifact is created. …
=> Link core files in directory for CI

src/app/cli/src/coda.ml, src/app/cli/src/coda_run.ml, src/app/cli/src/coda_worker.ml
Moved the monitor above the coda initialization so we can always catch
things.
Tested by throwing an exception asynchronously before coda
initialization finishes.
Later: Handle the exception better and print a nice message
* Please review with "No Whitespace" checked
* I acknowledge we should refactor this code; however, this file is in need of a bigger rewrite to be on top of graphql directly, so I don't want to invest in cleaning this us now
=> Crashing is always caught by our handler

src/lib/coda_transition/external_transition.ml
There was an `open Stable.Latest` in `External_transitions`. That put all the `bin_io` functions in scope, which isn't supposed to happen for non-versioned types that are used in RPC.
=> Remove open of module with bin_io functions

src/lib/coda_intf/staged_ledger_intf.ml, src/lib/coda_lib/coda_lib.ml, src/lib/staged_ledger/staged_ledger.ml, src/lib/staged_ledger_diff/staged_ledger_diff.ml, src/lib/transition_frontier/transition_frontier.ml, src/lib/transition_frontier_controller_tests/stubs.ml
Remove the `prev_hash` field from the type `Staged_ledger_diff.t` (and versioned version of that type).
Closes #2671.
=> Remove prev_hash field from staged ledger diff

src/app/cli/src/graphql.ml, src/app/cli/src/web_pipe.ml, src/lib/base58_check/base58_check.ml, src/lib/base58_check/base58_check.mli, src/lib/coda_base/proof.ml, src/lib/coda_base/user_command_memo.ml, src/lib/codable/codable.ml, src/lib/non_zero_curve_point/non_zero_curve_point.ml, src/lib/random_oracle_base/random_oracle_base.ml, src/lib/signature_lib/private_key.ml, src/lib/staged_ledger_hash/staged_ledger_hash.ml
Instead of passing a `version_byte` for each encode/decode, pass that once to a functor, use when needed. 
Also, no need to label arguments for encode/decode any longer, since there's no danger of mixing up arguments; there's just the string to be encoded or decoded. That simplifies the API.
When raising an exception for an invalid version byte, show the actual and expected byte as hex numbers.
Closes #2752.
=> Base58_check, pass version_byte once in functor

src/app/cli/src/dune, src/lib/base58_check/version_bytes.ml, src/lib/coda_base/receipt.ml, src/lib/coda_base/signature.ml, src/lib/codable/codable.ml, src/lib/codable/dune, src/lib/lite_curve_choice/dune, src/lib/lite_params/dune, src/lib/lite_params/gen/dune, src/lib/lite_params/gen/gen.ml, src/lib/lite_precomputed_values/gen/gen.ml, src/lib/non_zero_curve_point/dune, src/lib/non_zero_curve_point/non_zero_curve_point.ml, src/lib/random_oracle/dune, src/lib/secrets/secret_box.ml, src/lib/signature_lib/dune, src/lib/signature_lib/public_key.mli, src/opam.export
The few remaining uses of `Base64` are replaced by `Base58_check`.
Closes #2690.
=> Remove remaining uses of base64

src/app/cli/src/client.ml, src/app/cli/src/coda.ml
Trying to simplify exploration/discoverability of cli by hiding some lesser-used commands under an "advanced" section.
```
$ coda.exe -help
Coda
coda.exe SUBCOMMAND
=== subcommands ===
daemon                      Coda daemon
client                      Lightweight client commands
advanced                    Advanced client commands
internal                    Internal commands
parallel-worker             internal use only
transaction-snark-profiler  transaction snark profiler
integration-tests           Integration tests
version                     print version information
help                        explain a given subcommand (perhaps recursively)
$ coda.exe client -help
Lightweight client commands
coda.exe client SUBCOMMAND
=== subcommands ===
get-balance       Get balance associated …
```
=> Add 'advanced' subsection to coda cli

src/app/benchmarks/dune, src/app/benchmarks/main.ml, src/lib/vrf_lib/dune, src/lib/vrf_lib/integrated_test.ml, src/vrf_lib_tests.opam
Add benchmarks for vrf unchecked and checked evaluation.
Sample output:
```
┌──────────────────────────────────────────────────────────────────────┬──────────────┬──────────────┬────────────┬────────────┬────────────┐
│ Name                                                                 │     Time/Run │      mWd/Run │   mjWd/Run │   Prom/Run │ Percentage │
├──────────────────────────────────────────────────────────────────────┼──────────────┼──────────────┼────────────┼────────────┼────────────┤
│ [lib/vrf_lib/integrated_test.ml:vrf bench module] vrf eval unchecked │     942.07us │     184.80kw │     4.51kw │     4.22kw │      0.15% │
│ [lib/vrf_lib/integrated_test.ml:vrf bench module] vrf eval checked   │ 622_379.92us │ 203_510.31kw │ 7_308.66kw │ 7_307.85kw │    100.00% │ …
```
=> Add vrf eval benchmarks

frontend/website/posts/zkp.markdown
=> Fixed typos in zkp.markdown

src/app/cli/src/coda_commands.ml, src/lib/base58_check/version_bytes.ml, src/lib/coda_base/ledger_hash.ml, src/lib/coda_base/ledger_hash_intf.ml
Add `to_string`, `of_string` to `Ledger_hash`, using `Codable.Make_base58_check`.
Use `to_string` in `client status`.
Closes #2771. Or maybe there are other places where we want this base58 representation?
=> Base58check rep of ledger hash, use it in client status

src/lib/base58_check/version_bytes.ml, src/lib/coda_base/gen/gen.ml, src/lib/consensus/proof_of_stake.ml, src/lib/genesis_ledger/release_ledger.ml, src/lib/genesis_ledger/test_delegation_ledger.ml, src/lib/genesis_ledger/test_five_even_stakes.ml, src/lib/genesis_ledger/test_ledger.ml, src/lib/genesis_ledger/test_split_two_stakes_ledger.ml, src/lib/genesis_ledger/testnet_postake_ledger.ml, src/lib/genesis_ledger/testnet_postake_ledger_many_proposers.ml, src/lib/lite_lib/account.ml, src/lib/lite_lib/merkle_path.ml, src/lib/lite_params/dune, src/lib/lite_params/gen/dune, src/lib/lite_params/gen/gen.ml, src/lib/lite_precomputed_values/dune
Make `pedersen_params` and `sample_keypairs` lazy, because they're deserialized from strings.
Also, for `sample_keypairs`, remove the base58 encoding/decoding, which isn't needed.
=> Lazy generated data

src/lib/trust_system/trust_system.ml
This should make testnets more stable, especially under NAT.
=> Be more tolerant of network failures and ungraceful shutdown in trust system

scripts/rebuild-deb.sh
Updated deb versioning scheme from: `VERSION="0.1.${CIRCLE_BUILD_NUM}-CI"` to `VERSION="0.0.1-${GITBRANCH}-${GITHASH}"`
=> [FIX] changed deb versioning scheme

src/app/cli/src/coda_commands.ml, src/app/cli/src/graphql.ml, src/lib/coda_base/state_hash.ml, src/lib/coda_base/state_hash.mli
We recently changed the Merkle root in `client status` to be Base58.
This PR changes the `Staged Hash` in that command to also be Base58 (it's been in decimal up to now, as was the Merkle root in the old days).
=> Staged hash in status is base58

src/config/testnet_postake_medium_curves.mlh
Enabled `time_offsets` on the `testnet_postake_medium_curves` profile. 
CC: @nholland94 @bkase
=> turned on time_offsets

src/app/cli/src/coda_commands.ml, src/lib/consensus/intf.ml, src/lib/consensus/proof_of_stake.ml
The consensus human friendly time we were displaying on `client status` was not respecting time offsets (due to it using `Core.Time` instead of `Coda_base.Block_time`). This PR fixes that by replacing uses of `Core.Time`.
=> Consensus human time now respects time offsets

src/lib/snarky_bowe_gabizon_hash/snarky_bowe_gabizon_hash.ml
This PR switches BG hash to use calls through `Snark.Make`, instead of directly on `Snarky.Checked`/`Snarky.Typ`.
This is also necessary for o1-labs/snarky#311.
Checklist:
=> Make BG hash independent of the Checked.t monad chosen in Snarky

src/lib/logger/impl.ml
Fix missing newlines, check for directory existence and permissions before creating/opening log file.
=> Fix dumb logrotate implementation

frontend/wallet/schema.graphql, frontend/wallet/src/common/Wallet.re, frontend/wallet/src/render/Apollo.re, frontend/wallet/src/render/components/RequestCodaModal.re, frontend/wallet/src/render/components/SideBar.re, frontend/wallet/src/render/components/WalletDropdownItem.re, frontend/wallet/src/render/views/footer/Footer.re, frontend/wallet/src/render/views/footer/SendButton.re, frontend/wallet/src/render/views/walletlist/WalletItem.re, frontend/wallet/src/render/views/walletlist/WalletList.re, src/app/cli/src/graphql.ml
Main change: Updating the graphql.ml to treat pubkey and uint64 as scalars
It's actually kinda nice, we can avoid a lot of repeated error checking now!
Later we can see how it goes and consider following up with DateTime etc.
The associated changes are just making the wallet build with the new schema and updating the faker schema to match.
=> GraphQL scalars for PublicKey and UInt64

src/lib/coda_base/transition_system.ml, src/lib/verifier/prod.ml
The investigation finished, we solved the bug, and these logs are too noisy to keep in our codebase and usually won't have useful information
=> Revert investigation logs

src/lib/proposer/proposer.ml, src/lib/transition_router/transition_router.ml
If a daemon was run before the genesis time in the build profile, an exception was raised by the computation of the epoch corresponding to the current time, at the point the transition router decides whether to bootstrap. That exception was fatal.
In this PR, the exception is trapped with a logger warning, and then does sleeps and additional warnings until the genesis time is reached before starting the transition router.
Tested by setting genesis time in profile to the future, running `coda daemon`.
=> Wait to run transition router until genesis

CODEOWNERS
This PR adds @mrmr1993 and @bkase as codeowners on vrf lib (previously @nholland94 was the only one).
=> Add bkase and mrmr1993 as codeowners on VRF lib

src/lib/coda_base/hack_snarky_tests.ml, src/lib/coda_base/ledger_hash.ml, src/lib/coda_base/pending_coinbase.ml
This PR
* bumps snarky to the latest version
- this includes @psteckler's `compress`/`hash` -> `merge` rename in `Snarky.Merkel_tree`
* makes these rename changes to the `Merkel_tree` uses across coda
Checklist:
=> Bump snarky

src/lib/consensus/proof_of_stake.ml
Audit log messages in `postake.ml`. I skipped most of the `debug` logs, since the task is to cleanup `warn` and `error`.
=> Audit logs for postake code

src/app/cli/src/coda.ml, src/app/cli/src/coda_run.ml
We don't want the graphql server just to be ran on one address. So, we allow it to be run on all address for a machine.
Checklist:
Closes #0000
Closes #0000
=> bind rest server to all addresses on a machine

src/lib/cache_dir/cache_dir.ml
Blockingly query the brew install prefix to let us install more properly. Without this we're copying to an arbitrary place on the users disk, which might cause some issues if people have different homebrew configurations.
This isn't an ideal implementation because it blocks while querying but this command is fast so it might be ok?
Also eh if there's a better way to do this feel free to chime in
edit: hmm seems to break integration tests
```
time brew --prefix
/usr/local
real	0m0.030s
user	0m0.012s
sys	0m0.015s
```
=> Find keys using brew prefix

src/app/cli/src/coda.ml, src/lib/coda_version/coda_version.mli, src/lib/coda_version/gen.sh
The `version` command to the CLI executable was printing garbage info, because the Jane St `Command` processor handles that one specially. To use it properly requires generating a C file from a script that's apparently not in the Jane St libraries.
Instead, we intercept `version` (and `version -help`) on the command line, and print the information desired.
There was already a script to generate the git commit as a value in an .ml file, here extended to generate the git branch. So now we have:
```
$ coda version
Commit 087220d on branch release/beta
```
The `-help` message mimics what the Jane Street library would have printed:
```
print version information
coda.exe version
=== flags ===
[-help]  print this help text and exit
(alias: -?)
```
Closes #502.
=> CLI version info

src/app/cli/src/coda.ml, src/app/cli/src/coda_delegation_test.ml, src/app/cli/src/full_test.ml, src/lib/logger/impl.ml
- Fixes a bug with the logging system which was causing logs to be formatted as json when the build included tests (o.O)
- Adds a timestamp to pretty logs
- Increases the max interpolation size from 30 to 50
- Print out uninterpolated variables when they go over the max size
Example (with an interpolation length of 10 to test printing out uninterpolated vars):
```
18:12:45 avery@mbp:~/git/coda $ coda.exe daemon -peer strawberry-milkshake.o1test.net:8302
2019-07-22 18:12:55 [Warn] Long async cycle: $span milliseconds
span: "5.293928s"
2019-07-22 18:12:58 [Info] Starting Bootstrap Controller phase
2019-07-22 18:12:58 [Info] Bootstrapping right now. Cannot generate new blockchains or schedule event until it has finished. Pausing proposer
2019-07-22 18:12:58 [Info] Not running a web client …
```
=> Make pretty logging prettier

src/lib/logger/impl.ml
By popular demand, switching the pretty-printed logs to use UTC (and include a timezone specifier)
```
08:48:02 avery@mbp:~/git/coda $ ./src/_build/default/app/cli/src/coda.exe daemon -peer ...
2019-07-23 15:48:21 UTC [Info] Starting Bootstrap Controller phase
2019-07-23 15:48:21 UTC [Info] Pausing block production while bootstrapping
2019-07-23 15:48:21 UTC [Info] Daemon ready. Clients can now connect
```
=> Pretty-log in UTC time

src/app/cli/src/client.ml
=> Removing get-txn-status as it's too late to test

src/lib/merkle_mask/maskable_merkle_tree.ml, src/lib/transition_frontier/transition_frontier.ml
Prior to this commit we unregistered the masks of the children of the old root
that were not on the winning chain, but ignored any descendants of those
children. This commit correctly unregisters all the masks. I also made the error
messages when you try to remove the parent of a mask that isn't attached
properly more informative.
This won't fix the issue @figitaki was seeing, but it'll at least make debugging easier since there will be less garbage in the visualizations.
=> Properly unregister masks when moving tf root + better error messages

src/app/cli/src/coda_commands.ml, src/app/cli/src/graphql.ml, src/lib/coda_lib/coda_lib.ml, src/lib/coda_lib/coda_lib.mli, src/lib/daemon_rpcs/daemon_rpcs.ml, src/lib/transition_router/transition_router.ml, src/lib/transition_router/transition_router.mli
We keep a record of the most recent transition that has been proof-validated. We compute the blockchain length of that transition. This will give us an indication of how synced a node is to the network
Ran `dune exec coda client status` and it showed this:
```
Coda Daemon Status 
-----------------------------------
Maximum Block Length Encountered from a Valid Block:  1
Local Uptime:                                         53s
GIT SHA1:                                             [DIRTY]a1a7bc64c5448f4b96737daf9cd50fd826fdbb14
Configuration Directory:                              /Users/johnwu/.coda-config
Peers:                                                Total: 0 ()
User_commands Sent:                                   0
Snark Worker Running:                                 false …
```
=> Status shows the highest block length encountered

frontend/website/src/Docs.re, frontend/website/src/Links.re, frontend/website/src/Markdown.re, frontend/website/src/Render.re
This will avoid issues where the cdn prefix is used before it gets set in render (which has happened a couple of times)
- Also fixes an instance of this where the link svgs aren't showing up in the docs.
=> Add website cdn prefix check

src/app/cli/src/coda.ml
Make `-version` on the CLI an alias for `version`, because many people will try that. `-version -help` also works.
It's not advertised: if you run just `coda`, only `version` appears, consistent with the other commands.
Closes #2972.
=> Dash-version on cli

.circleci/config.yml, .circleci/config.yml.jinja, src/app/cli/src/coda.ml, src/lib/logger/impl.ml
Like this:
```
2019-07-25 21:40:59 UTC [Info] Coda daemon is booting up; built with commit "b568c51acceac7fbdf46fbdf40662f5406d4c3d2" on branch "release/beta"
```
Moved registration of log consumers earlier in daemon startup. Early log messages were getting dropped!
Closes #807.
=> Log commit and branch on daemon startup

src/lib/consensus/proof_of_stake.ml, src/lib/daemon_rpcs/daemon_rpcs.ml
Lots of alternatives to the formatting of the Consensus Configuration in this PR, I could swap the `:` back to a `=` too
before:
```
Coda Daemon Status
-----------------------------------
Local Uptime:                     140s
GIT SHA1:                         060e7f34009a0792ddac2698bf4402e57585cc7c
Configuration Directory:          /Users/avery/.coda-config
Peers:                            Total: 0 ()
User_commands Sent:               0
Snark Worker Running:             false
Sync Status:                      Bootstrap
Block Producers Running:          Total: 0 ()
Consensus Time Now (epoch:slot):  13214:9
Consensus Mechanism:              proof_of_stake
Consensus Configuration:          
delta = 3
k = 24
c = 8
c_times_k = 192
slots_per_epoch = 576
slot_duration = 2000
epoch_duration = …
```
=> Improve formatting of coda client status

frontend/website/src/Config.re, frontend/website/src/Links.re, frontend/website/src/Render.re, frontend/website/src/Style.re
https://github.com/CodaProtocol/coda/pull/2988 accidentally made it so that this font is required for dev builds, which seems unnecessary. This makes it so that it is optional unless you're building for prod (so that we don't accidentally deploy the wrong font).
=> Website: Make pragpro font optional for dev build

CODEOWNERS
This got lost from `release/beta` somewhere along the way.
=> put the rpc_parallel submodule back where it was, with the macos bugfix

src/lib/trust_system/peer_trust.ml, src/lib/trust_system/record.ml, src/lib/trust_system/record.mli
If bans are disabled, when an updated trust score is less than or equal to -1, and was greater than that before, log `info` the ban that would have occurred. (It might not be a new ban, since the trust score may have decayed to a value greater than -1.)
Also, check the disabled flag on `add_trust` to prevent `banned_until_opt` from becoming `Some time`. Wrongly, we were checking the flag on `update`, which can only remove the ban time.
Closes #3049.
=> Log not-performed bans; don't ban on add_trust

frontend/website/package.json
We forgot to copy over one of the private font files.
Testing by submitting from my fork (which hopefully should trigger the non-core CI behavior?)
=> Make contributors' PRs pass CI

scripts/artifacts.sh, scripts/pvkeys-download.sh
adds an optional branch name to PV key archive -- lets us maintain different key sets for different branches.
exposes an issue that when running a PR, you can't tell what branch you're merging in to.
but the benefit here is that we can maintain different PV key sets for different branches. (when the snark circuit changes in a branch)
=> SIMPLE: add branch to pv key archive name

src/app/kademlia-haskell/app/Main.hs
Add `dump-peers` startup mode for Kademlia (in addition to `test`), which:
- makes `logTrace` become a no-op
- exits the Kademlia process after dumping the initial live peers
Verified to compile.
=> Add dump-peers start mode for Kademlia

src/lib/coda_intf/network_intf.ml, src/lib/coda_lib/coda_lib.ml, src/lib/coda_networking/coda_networking.ml, src/lib/gossip_net/gossip_net.ml, src/lib/transition_frontier_controller_tests/stubs.ml, src/lib/trust_system/peer_trust.ml, src/lib/trust_system/peer_trust.mli
There's code in `Gossip_net` to read from the ban pipe. When a ban occurs, there's a call to a new Rpc, `Ban_notify`. The ban pipe now passes the banned-until time, as well as the IP address of the banned peer.
Upon notification, the banned peer uses `Logger.warn` to print out the banning peer and the ban expiration time.
Tested by temporarily making the notification occur on every connection, running the five-even-snarkless multiproposer test, and verifying the log message is printed.
The notification is eager, in the sense that it's sent when we get an entry on the ban pipe. Initially, the implementation sent the message when a banned peer tried to connect.
Because the trust system bans by IP addresses, while the network can know of multiple peers at an address, peers may receive ban …
=> Notify peers when they're banned

frontend/website/docs/getting-started.md, frontend/website/docs/troubleshooting.md, src/app/cli/src/coda.ml, src/app/cli/src/find_ip.ml, src/app/cli/src/find_ip.mli
This raises a better exception after failing to find our IP, and documents the error.
Closes #3039
=> Less fatal find_ip

src/config/test_postake_holy_grail.mlh, src/lib/proposer/proposer.ml, src/lib/transition_frontier/transition_frontier.ml
Fixed a dangling mask bug,
Inside the `proposer.ml`, `transitioned_staged_ledger` should be properly discarded by unregistering its mask.
=> discard transitioned_staged_ledger by unregistering its mask

.gitmodules, README-dev.md, dockerfiles/Dockerfile-toolchain, scripts/macos-setup.sh
This adds our fork of `graphql_ppx` as a submodule for pinning. The fork gives us
* 4.07.1/4.08.0 support
* tweaks to make the output compatible with Core.
I haven't been able to generate a `graphql_schema.json` for our schema, so I haven't been able to set up a full test query, but the code generated from a test schema looks how I would expect and compiles inside coda.
Checklist:
=> Add graphql_ppx

.circleci/config.yml, .circleci/config.yml.jinja, scripts/artifacts.sh, scripts/librewrite-macos.sh, scripts/macos-setup.sh
- isolates opam and homebrew in macos script (better for build caching)
- makes macbuild use same keys from linux build
- use cachix binary cache for kademlia (1m30s kadem builds)
- copy results to cloud
- make some build tasks run in background
=> make mac build work again

src/lib/bootstrap_controller/bootstrap_controller.ml, src/lib/pipe_lib/strict_pipe.mli, src/lib/transition_frontier_controller_tests/test_bootstrap_controller.ml
This PR fixed a bug related to bootstrap controller.
Retry bootstrap should first close the transition_reader pipe used by previous bootstrap attempt.
=> close sync_ledger pipe when retry bootstrap

frontend/website/src/Render.re
Adds recursive to the directory creation in `copyFolder`. According to the [node docs](https://nodejs.org/api/fs.html#fs_fs_mkdir_path_options_callback), " Calling fs.mkdir() when path is a directory that exists results in an error only when recursive is false.".
Hopefully this fixes the crash but I don't seem to be able to repro it 100% reliably. Also cleans up the bindings in this file a little.
=> Website: Fix site/static mkdir crash

frontend/website/deploy-website.sh
Avoid terrible accidents deploying prod without cdned assets by detecting `yarn dev` during deploy.
=> Website: detect dev server during deploy

.circleci/config.yml, .circleci/config.yml.jinja
Apparently DUNE_PROFILE environment was never in use in mac build -- fix.
=> SIMPLE:move  dune profile setting in macos build

src/app/cli/src/client.ml, src/app/cli/src/coda_commands.ml, src/app/cli/src/coda_run.ml, src/lib/cli_lib/render.ml, src/lib/daemon_rpcs/daemon_rpcs.ml
We need a quick way to collect nonce summaries.
expanding -with-balances to -with-details (including balances and nonces) was an easy way to accomplish this.
New format:
```
coda.exe advanced get-pub -with-details
8QnLYnzAkhx3moXHHBBpK418LGCEiQZzYDgKggntsNkZqsUJLFos474Mzoy5mWJP9S, 10000000, 0
8QnLTHMZPbBFezS8j8kDPu6iLiwPsTPyX2vMwcFzjiDZbp6GQDEBEyLbYvzApSdTsE, 100, 0
8QnLWWJ33Wm1e4ejaMeYC6RsjpaodiVuYY3RzKZ3ys5UBAmpaupV1SD6LSU2a6KB3L, 1000, 0
8QnLZ1fit1QXTLiFPcSuaR4F7ySgDMK2ZHpDLZU8Jm2ABE1K9n2Fbswme9SaSTd8bJ, 1000, 0
8QnLYLvy4FLKVo3qt9A32yLRLyEFHqf5NZTTFynajH6gNMH3AR4HA2gZTju8NpCgDU, 1000, 0
8QnLTkPLvGe1nAjtLP6WQzaVw2VKxQ9pAPLRPMd3eVbkfUuUL7g4R7mFrzuTZQgByc, 1000, 0
8QnLTnAYna24EdfX9dDMstUtWnQqU39YQBS4G7PjJD2KjQVHKZEhrPDeNSLJFrKiyr, 1000, 0 …
```
=> SIMPLE:expand with-balances to with-details

scripts/pvkeys-download.sh, src/config/testnet_postake_medium_curves.mlh
As discussed with Joel on discord, this bumps the genesis time to 9AM today.
Checklist:
=> Genesis timestamp hotfix

src/app/cli/src/coda.ml
We were looking up a single address of type `Inet_addr.t` for peers passed to the daemon.
Instead, we use `Unix.Host.getbyname` to get an array of addresses for each peer. Often, that's just one address, but might help in some cases.
Closes #3156.
=> Lookup all peer addresses

src/lib/proposer/proposer.ml
Closes #3160
We're seeing large (largest I saw so far was ~17s, @ghost-not-in-the-shell has seen more) async cycles causing this timeout to trigger. I turned it up, so hopefully it won't happen as often on decent CPUs, but also remove the exception. If the timeout fires, we aren't guaranteed to make our next proposal on top of our own block, even if it ended up displacing the best tip. I think this actually can break Ouroboros, and is insecure, but shouldn't be prone to accidental forks with the reasonable k that @nholland94 is adding. I think. We should disable this at some point, which I've created #3167 to track.
=> HACK: non-fatal proposer timeout

src/config/testnet_postake_medium_curves.mlh, src/lib/consensus/proof_of_stake.ml
The following changes were made in order to decrease the probability of a fork happening during the staking testnet:
- 2x artifical inflation on VRF threshold was removed
- `k` was increased to 10 from 3
- `block_window_duration` was increased to 6min from 5min
The artificial 2x inflation on the VRF threshold (which gives all proposers a 2x chance to win a slot) was contributing the the probability of the network forking with a low k value. This was further increased by having a small window of time in between the block proving time and the total slot time. The main effect (at least, as the running theory goes) is that if two proposers keep on winning blocks in a row, but don't process blocks from the other proposers before starting on their next block, they will fork the network if they …
=> Update parameters for new staking testnet release

src/app/cli/src/graphql.ml, src/lib/auxiliary_database/external_transition_database.ml, src/lib/auxiliary_database/intf.ml, src/lib/auxiliary_database/pagination.ml, src/lib/auxiliary_database/transaction_database.ml
Quick fix to query all the blocks that a node has.
So in order to record all seen blocks, run the following command while running the daemon:
```
src/_build/default/app/cli/src/coda.exe daemon -rest 8080
```
Then, you can query the blocks via:
```
{
blocks(first:3) {
nodes {
stateHash
}
pageInfo
{ lastCursor}
}
}
```
As a result, you will get the following:
```
{
"data": {
"blocks": {
"nodes": [
{
"stateHash": "TWog8UE3YdZHKcqJ9xKnQk4yAVpGNxNYjwbFi3CrE8TCrSpHynzjscsVAzHFvN8q"
},
{
"stateHash": "TWogv1wpfnwWK91xa1JjncRWCQxUEiH28Bb3XcfHYYvWFEoMtEAQA7VPXB6YED7x"
},
{
"stateHash": "TWoftHQ2GXDM8v1Ufqp8BcJmhYgDn3BckVMu3NeUrtytRowacKzCWv6J9VoG8UPx"
}
],
"pageInfo": {
"lastCursor": "TWoftHQ2GXDM8v1Ufqp8BcJmhYgDn3BckVMu3NeUrtytRowacKzCWv6J9VoG8UPx"
}
}
}
}
```
=> Can query all blocks in database via blocks graphql command

.circleci/config.yml, scripts/test.py, src/app/cli/src/coda.ml, src/app/cli/src/init/client.ml, src/app/cli/src/init/coda_run.ml, src/app/cli/src/tests/coda_change_snark_worker_test.ml, src/app/cli/src/tests/coda_process.ml, src/app/cli/src/tests/coda_processes.ml, src/app/cli/src/tests/coda_transitive_peers_test.ml, src/app/cli/src/tests/coda_worker.ml, src/app/cli/src/tests/coda_worker_testnet.ml, src/app/cli/src/tests/full_test.ml, src/lib/coda_lib/coda_lib.ml, src/lib/coda_lib/coda_lib.mli, src/lib/coda_lib/config.ml, src/lib/kademlia/membership.ml, src/lib/kademlia/node_addrs_and_ports.ml, src/lib/snark_worker/functor.ml, src/lib/snark_worker/intf.ml, src/lib/snark_worker/rpcs.ml
This PR consists of two PRs, which me unreverting my change for "Setting snark worker dynamically"
I fixed the flakyness that my PR caused for the integration tests. This is what I did:
1.  Snark worker process dies when the snark worker key is set to none
2. Snark worker process will be invoked after rpc servers are setup
=> Re-enable dynamic snark workers (from #2767)

src/app/cli/src/tests/coda_process.ml, src/app/cli/src/tests/coda_worker.ml
Quick fix to stop the flaking tests for bootstrapping.
Checklist:
Closes #0000
Closes #0000
=> Asynchronously stop snark worker

.circleci/config.yml, .circleci/config.yml.jinja
other jobs in whole run were finishing before background job to upload debs -- this stopped the upload job.  :(
removing background was less gross than adding hack step to check for all background jobs to be done.
=> remove background in ci

src/lib/non_zero_curve_point/non_zero_curve_point.ml
`to_yojson` in `Public_key.Compressed` and `Public_key.Compressed.Stable.V1` was producing different results. Strange, because those functions were produced by the same functor, and I verified the functor was being passed identical relevant arguments. 
The functor was passed arguments that also happened to be defined in the functor body, maybe it was using the passed ones, though they're not mentioned in the signature of the functor input.
In any case, a fix is to just import the `to_yojson` from `Stable.Latest` (and other functions created by the functor). I verified the results are the same when that's done.
Closes #3210
Update: changed the approach here. The difference in serialization was due to the different `bin_io` functions in the functor argument. `Stable.Latest` contains …
=> Same yojson encoding in stable and unstable Public_key.Compressed

src/app/cli/src/init/coda_run.ml, src/lib/coda_metrics/coda_metrics.ml, src/lib/coda_networking/coda_networking.ml, src/lib/network_pool/snark_pool.ml, src/lib/staged_ledger/staged_ledger.ml, src/lib/work_selector/work_lib.ml
Added the following metrics:
1. snark_work_received_gossip: # of snark work received from peers
2. snark_work_received_rpc: # of snark work received via rpc 
3. snark_work_sent_rpc: # of snark work sent via rpc
4. snark_pool_size: # of snark works in the snark pool
5. snark_work_per_block: # of snark work purchased per block
6. scan_state_snark_jobs: # of jobs in the scan state after every block
Checklist:
=> snark work prometheus metrics

README.md
.org should redirect but it's having some issues I guess and we should probably be consistent anyway
=> Replace README codaprocotol.org with .com version

src/app/cli/src/tests/coda_process.ml, src/app/cli/src/tests/coda_worker.ml, src/app/cli/src/tests/coda_worker_testnet.ml, src/lib/coda_lib/coda_lib.ml
This PR undos #3219.
The reason we introduced #3219 is that turning off snark worker takes a while, and this would cause some bug in long-fork integration test. So in #3219 we try to asynchronously stop snark worker. But this would cause some other bug as described in #3231. This proper fix is to change the integration test infrastructure, so that once the nodes are offline, prefix-check should also be turned off.
Close #3231
=> Synchronously stop snark workers

src/app/cli/src/coda.ml
Stops redirecting all stdout/stderr to coda.log
We're already writing the logs to coda.log using the logger, this seems
redundant and probably breaks log rotation anyway.
Without this change, we get weird stuff like this in coda.log:
```
{"timestamp":"2019-08-20 01:24:27.231129Z","level":"Warn","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 509, characters 62-69"},"message":"long async cycle 5.682799s","metadata":{"pid":1435}}
2019-08-20 01:24:27 UTC [Warn] long async cycle 5.682799s
```
Fixes #2993
=> Fix double-logging issue

src/app/cli/src/coda.ml, src/app/cli/src/tests/coda_worker.ml, src/app/cli/src/tests/full_test.ml, src/lib/coda_networking/coda_networking.ml, src/lib/gossip_net/gossip_net.ml, src/lib/network_pool/snark_pool_diff.ml, src/lib/transition_frontier_controller_tests/stubs.ml
This is an extension of the snark work log (#3223 ) PR to log received blocks and transaction pool diffs if the flags `log-received-blocks` and `log-txn-pool-gossip` are set resp. 
Snark pool diff log:
```
{"timestamp":"2019-08-20 01:16:50.306045Z","level":"Debug","source":{"module":"Coda_networking","location":"File \"src/lib/coda_networking/coda_networking.ml\", line 792, characters 28-35"},"message":"Received Snark-pool diff $work from $sender","metadata":{"pid":42138,"sender":{"Remote":"10.111.4.160"},"work":{"work_id":441587705,"fee":1,"prover":"8QnLYnzAkhx3moXHHBBpK418LGCEiQZzYDgKggntsNkZqsUJLFos474Mzoy5mWJP9S"}}}
```
Blocks received log
```
{"timestamp":"2019-08-20 01:16:52.318599Z","level":"Debug","source":{"module":"Coda_networking","location":"File …
```
=> Log gossip heard

src/lib/cli_lib/render.ml, src/lib/coda_commands/coda_commands.ml, src/lib/daemon_rpcs/daemon_rpcs.ml
Instead of converting a string to JSON, code the JSON directly, which won't fail.
Closes #3233.
=> Code JSON directly

src/app/cli/src/coda.ml, src/lib/ppx_coda/check_ocaml_word_size.ml
Make sure we're building `coda.exe` with a 64-bit OCaml. Compile-time error if not.
=> Check OCaml word size

src/lib/gossip_net/gossip_net.ml
There was a `failwith` in `remove_peers` that was trying to enforce the invariant that we only removed peers when there was an entry in both the `peers` and `peer_by_ip` tables for the gossip net.
It must be that sometimes we try to remove a peer after it's already been removed from those two tables, triggering the failure.
Remove the `failwith`, update the `peers_by_ip` entry only if there's an existing entry.
Closes #3266.
=> Don't fail when missing entry in peers_by_ip

.circleci/config.yml, .circleci/config.yml.jinja, scripts/rebuild-deb.sh
To follow: coda-logproc in deb dist.
See CodaProtocol/homebrew-coda@10217e7 for homebrew related changes
=> Ship logproc as coda-logproc in mac dist

CODEOWNERS
These are the only two paths that had only Nathan and Corey on them -- I added myself to them as well (I'm comfortable enough with test.py and dev.mlh)
=> Unblock OOO nathan+corey

src/app/cli/src/coda.ml, src/app/cli/src/memprof_helpers.ml
Write the memprof output file to the config dir.
Change flag to `-memory-profiling-sampling-rate`, so it shows up next to `-memory-profiling` in `-help`.
Add comment to file we cribbed from the memprof distribution.
=> Memory profile file in config dir

frontend/bot/Dockerfile, frontend/bot/package.json
Open questions:
- I'm assuming we're passing in env vars with `-e` or something
- This assumes that graphql_schema.json is in the build directory. This isn't true in git, it's actually in the root of the repo. Either we need to build from the repo root and update the dockerfile accordingly, or somehow copy the file into the build directory.
Basically we need to run
```bash
cp coda/graphql_schema.json coda/frontend/bot/graphql_schema.json
```
=> Add basic bot dockerfile

src/app/cli/src/init/client.ml, src/app/cli/src/tests/full_test.ml
User commands (payments, delegations) take an optional `-memo` flag:
```
coda.exe client send-payment 
=== flags ===
-amount VALUE        Payment amount you want to send
-privkey-path FILE   File to read private key from
-receiver PUBLICKEY  Public key address to which you want to send money
[-daemon-port PORT]  Client to daemon local communication (default: 8301)
[-fee FEE]           Amount you are willing to pay to process the transaction
(default: 5)
[-memo STRING]       Memo accompanying the transaction (up to 32 characters)
[-nonce NONCE]       Nonce that you would like to set for your transaction
(default: nonce of your account on the best ledger or the
successor of highest value nonce of your sent
transactions from the transaction pool )
[-help]              print this help text …
```
=> Memos for user commands

src/lib/sync_handler/sync_handler.ml, src/lib/transition_frontier/transition_frontier.ml
This should fix the "received faulty scan state".
This would also allow us to download the scan state even if the peer's root has moved.
Closes #3269
=> fix the merkle_root mismatch

src/lib/proposer/proposer.ml
This PR didn't get into the release-beta2, so I move it to `develop` instead.
The following scenario happened once in the testnet:
proposer comes online, doing bootstrap
bootstrap finishes but catchup is not done yet, the proposer happened to propose at that point
proposer is stuck by doing proof; meanwhile ledger-catchup finishes and updated the transition frontier and, unfortunately, the parent of the proposed transition is dropped.
proposer finally finishes the proof and start doing the validation, but it finds the parent is no longer in the transition frontier.
A crash happens.
I changed the proposer code so that validation failure won't cause crashes, instead we just print some error messages that tells user what happened.
=> make proposer not crash if validation fails

src/app/cli/src/coda.ml
The OCaml memory statistics are given in number of words. The log message was multiplying those by `Sys.word_size`, which is 64. It should be multiplying the number of words by `Sys.word_size / 8` to give the number of bytes.
=> Fix calculation of memory bytes

src/config/testnet_postake_medium_curves.mlh
In order to run nightly testnets, we need time offsets enabled.
=> TRIVIAL: enable time offsets on develop

scripts/rebuild-deb.sh
Stores all build config file and explicitly the DUNE_PROFILE used in a particular build.
Use case: extract genesis timestamp or other build config parameters without needing a running daemon.
=> TRIVIAL: store build config

frontend/website/docs/node-operator.md
Tweaked some links to make them point to the correct pages (under `docs/`).
Checklist:
=> Fix links in node-operator docs page

src/app/cli/src/init/client.ml
We realized at the last minute that we can't use gql for this of CLI command until we have the new accounts system in place. Otherwise you'd only be able to cancel txns sent from "ownedAccounts".
This converts us to using RPC to cancel transactions.
```
$ coda client send-payment -amount 1 -fee 1 -privkey-path tmpkeydir/largest -receiver 8QnLUuaLFKHpRnfAS3NPMh8zpkWgVZ5hMuziZ8m3zum493aib4u5gQcWpCCDqbkf7W
Secret key password: 
Dispatched payment with ID Bf2dBf29M9V796NcNK5Xh3P3N1w7gYHBiun7MEERvS51YhUE9NsuzdCvaECZ8KeFkiDeGRDU97mt9atr5vkKSHjUoVGXjWV6Wpf1dP7kSvKsxkRk7sCK6x3fDaS8XRzZU6oPJDJuouWgdoF5JSvt3PAk6Q7Hep6SGTsfVvVyr6ae7q6fRrPTVDozFpbwg9pDJP1MkWb3WX8hbT36nRzJVoPKPmx9YQeESmsFRq1XJ2UrRNctm5nuGBKj6KeCkNp7AQaFT3pLguf7re9rTQ9WGe7dkGSSeh4d3BQThVH6ydhpL13
Receipt chain hash is now …
```
=> Convert cancel-txn to use rpc

src/app/cli/src/coda.ml, src/app/cli/src/init/client.ml, src/app/cli/src/tests/coda_processes.ml, src/app/cli/src/tests/coda_worker.ml, src/app/cli/src/tests/full_test.ml, src/app/libp2p_helper/src/codanet.go, src/app/libp2p_helper/src/generate_methodidx/main.go, src/app/libp2p_helper/src/libp2p_helper/main.go, src/app/libp2p_helper/src/libp2p_helper/methodidx_jsonenum.go, src/coda_net2.opam, src/lib/cli_lib/port.ml, src/lib/coda_net2/coda_net2.ml, src/lib/coda_net2/coda_net2.mli, src/lib/coda_net2/dune, src/lib/gossip_net/dune, src/lib/gossip_net/gossip_net.ml, src/lib/kademlia/membership.ml, src/lib/kademlia/membership.mli, src/lib/kademlia/node_addrs_and_ports.ml, src/lib/transition_frontier_controller_tests/stubs.ml
use `-libp2p-discovery` as daemon arg to enable. There is a `-libp2p-port` argument but it is IGNORED at the moment in favor of the hardcoded port 28675 (arbitrary). When we remove the Haskell Kademlia, we'll take over the existing port infrastructure.
There's a `-disable-old-discovery` that turns off old discovery as well. Risky!
=> Add optional libp2p discovery

frontend/website/docs/troubleshooting.md
discussion with harold led to some ideas of how to make the custom port forwarding docs a little easier to follow.
- Explicitly repeat the command that should be run with the custom port
- Link to the "next step"
=> Clearer docs for custom port forwarding

frontend/website/docs/getting-started.md
Discussed with Brandon to add a link to the unofficial WSL guide to the docs, so new members will not drop off when they see that Windows is not supported.
=> Add link to unofficial windows instructions to docs

src/app/cli/src/coda.ml, src/lib/proposer/proposer.ml, src/lib/staged_ledger/pre_diff_info.ml, src/lib/staged_ledger/staged_ledger.ml, src/lib/staged_ledger/staged_ledger.mli, src/lib/staged_ledger_diff/staged_ledger_diff.ml, src/lib/staged_ledger_diff/staged_ledger_diff.mli, src/lib/transition_frontier_controller_tests/stubs.ml, src/lib/trust_system/record.ml
Not crashing proposers when the following staged ledger errors occur: 
1. `Non_zero_fee_excess`
2. `Invalid_proof`
3. `Pre_diff of Pre_diff_info.Error.t`
4. `Insufficient_work`
Instead, log the error, drop the block, and continue. 
Proper handling of each of those errors is tracked in #3366
Checklist:
Closes #3350 ?
Closes #3347 ?
=> handle proposer crashes

src/lib/envelope/envelope.ml, src/lib/envelope/envelope.mli
Envelopes are created on message receipt, not when sent, so they're not serializable, hence `Envelope` does not need versioning.
Closes #2361.
=> Remove versioning for envelope

src/lib/coda_base/coinbase.ml
In `coinbase.ml`, we use `Binable.Of_binable` to insert a validity guard in `bin_io` functions. We were passing the unregistered `bin_io` functions, so the registration had no effect.
Use the functions that come from registration instead.
Closes #3388.
=> Use shadowed bin_io functions

src/app/cli/src/coda.ml, src/app/cli/src/tests/coda_worker.ml, src/app/cli/src/tests/full_test.ml, src/lib/auxiliary_database/transaction_database.ml, src/lib/coda_base/block_time.ml, src/lib/coda_base/block_time.mli, src/lib/transition_frontier_controller_tests/stubs.ml, src/lib/transition_frontier_controller_tests/test_catchup_scheduler.ml
Use default of 0 and log that fact if `CODA_TIME_OFFSET` is undefined.
Use `Core.Sys.getenv`, which returns an option, instead of `Unix.getenv`, which raises an exception, which we weren't handling.
Closes #3336.
=> Use default if CODA_TIME_OFFSET undefined

graphql_schema.json, src/app/cli/src/init/client.ml, src/app/cli/src/init/graphql_client.ml, src/lib/cli_lib/flag.ml, src/lib/coda_graphql/coda_graphql.ml, src/lib/secrets/wallets.ml, src/lib/secrets/wallets.mli
First commit:
- Add `reloadWallets` mutation
- Add `locked` field to wallet
- Small refactor to secrets/wallets.ml to allow you to "reload" wallets
Second commit:
- Add ability for graphql_client to return the result of a query so that you can optionally ignore errors
- Fix bug in Encoder for public key
Third commit:
- Add commands to accounts section of the cli. These use graphql and have corresponding additions to the list of queries in `graphql_client.ml`
Usable example of the new commands:
```
avery@mbp $ coda account list
😢 You have no wallets!
You can make a new one using `coda accounts create`
avery@mbp $ coda account create
Password for new private key file: 
Again to confirm: 
👝 Added new account!
Public key: 8QnLXcjiXHe4jsEx2stzSs9j4J5jXPuGTzCD7P2wtAk1AkNFT6SfgsHzJYAxWsDW8z …
```
=> Add commands to new accounts cli section

src/app/cli/src/init/coda_run.ml, src/lib/coda_lib/coda_lib.ml, src/lib/coda_lib/coda_lib.mli, src/lib/work_selector/intf.ml, src/lib/work_selector/random.ml, src/lib/work_selector/sequence.ml, src/lib/work_selector/work_lib.ml
`seen_jobs` which keeps track of the work assigned was not being updated upon receiving completed work causing it to grow indefinitely.
Manually tested by running daemon
Checklist:
=> Remove from seen_jobs after receiving snark work

src/config/ledger_depth/full.mlh, src/config/ledger_depth/small.mlh, src/config/ledger_depth/tiny.mlh, src/config/testnet_postake_medium_curves.mlh, src/lib/genesis_ledger/dune, src/lib/genesis_ledger/fake_accounts.ml, src/lib/genesis_ledger/genesis_ledger.ml, src/lib/genesis_ledger/testnet_postake_ledger.ml
Generate fake accounts for genesis ledgers.
There's a general mechanism to do this via a Quickcheck generator, `Fake_accounts.gen`. Currently, it's used in `Testnet_postake_ledger`.
The number of fake accounts is a new config parameter, `fake_accounts_target`. There's a load-time check in `Genesis_ledger` that this value is no greater than `2**ledger_depth`. The parameter has been added to the `ledger_depth/*.mlh` files, and to `testnet_postake_medium_curves`.
For that last configuration, the ledger depth is 11, so the  number of fake accounts could be, in theory, as much as `2**11 = 2048`. Unfortunately, that choice generates a compile-time error:
```
"unhandled exception in Async scheduler"
("unhandled exception"
((monitor.ml.Error
( "Snarky.Checked_runner.Runtime_error(_, _, _, _)\
\n\ …
```
=> Fake accounts for testnet_postake genesis ledger

src/lib/non_zero_curve_point/non_zero_curve_point.ml
Choose a single sexp representation for public keys, namely, the Base58Check string for compressed keys. The derived `t_of_sexp`s were broken because the field sexps could not be converted back to fields, see #3444.
The Base58Check representation means the sexps look like the yojson representation, which are also Base58Check strings, and we don't need a utility to convert the sexps to Base58Check.
Closes #3442. Closes #3461.
Tested by printing out the sexps for uncompressed, compressed versions of a key, verifying the sexps are identical, inverting the sexps back to the original keys, verifying those inversions are identical to the original keys.
=> Single sexp rep for pubkeys, base58check for compressed

.circleci/config.yml, .circleci/config.yml.jinja, README-dev.md, dockerfiles/Dockerfile, src/app/cli/src/coda.ml
Log long async cycle backtraces, to see if they reveal why we have long async cycles.
Requires https://github.com/CodaProtocol/async_kernel/pull/3, also WIP.
Not clear if this is the right thing to do, see: https://discuss.ocaml.org/t/deducing-provenance-of-async-kernel-jobs/4376/2
=> Log long async cycle backtraces

src/lib/coda_commands/coda_commands.ml, src/lib/coda_graphql/coda_graphql.ml, src/lib/coda_lib/coda_lib.ml, src/lib/coda_lib/coda_lib.mli, src/lib/consensus/intf.ml, src/lib/consensus/proof_of_stake.ml, src/lib/daemon_rpcs/daemon_rpcs.ml, src/lib/proposer/proposer.ml
This PR adds a "next proposal" field to the client status output that says when the next proposal will be if the daemon is configured as a proposer.
I had some trouble testing because I can't get the proposer to produce blocks. Is there an easy way to propose using a key in the test ledger?
=> Add "next proposal" field to status

src/app/cli/src/coda.ml, src/config/testnet_postake_medium_curves.mlh
Enable backtrace recording for `Async`.  Tested by building, running daemon, examining log file.
Use daemon expiration date.
=> Record async backtraces; set expiry to Tuesday, 10-8-2019 14:00 PDT

src/lib/coda_lib/coda_lib.ml, src/lib/network_pool/intf.ml, src/lib/network_pool/network_pool_base.ml, src/lib/network_pool/snark_pool.ml, src/lib/network_pool/snark_pool.mli, src/lib/network_pool/test.ml, src/lib/network_pool/transaction_pool.ml, src/lib/staged_ledger/staged_ledger.ml, src/lib/transition_frontier_controller_tests/test_transaction_status.ml
When verifying the snarks received from snark workers or peers, use the verifier already created for verifying incoming staged ledger diffs.
Ideally we'd want a pool of verifiers for better performance but this, for now, should help deal with the  1.5G memory usage by these processes
Still testing..
Closes #0000
Closes #0000
=> verifier hotfix

src/app/cli/src/coda.ml
Remove the async backtraces, which were not providing useful information, just a lot of entries relating to the scheduler internals.
Also, print just one decimal digit of precision for the long cycle times; the extra digits we were printing are unneeded and, if I might say, unsightly.
=> Remove async backtraces, improve time formatting

frontend/bot/src/Coda.re, frontend/bot/src/Echo.re, frontend/bot/src/Faucet.re, frontend/bot/src/Graphql.re, frontend/bot/src/Repeater.re
The issues with the faucet this week highlighted an issue with how the bot formats errors. Namely:
```
I failed to send you some coda just now :sob:
Please try again later!
Error: Error: Internal Server Error,,[object Response]
```
This is because reason-urql's combinedError type doesn't expose a toString() function. I opened a PR to expose a formatted version of the message (https://github.com/FormidableLabs/reason-urql/pull/105) but in the meantime, we can use a custom one which is very similar (defined in `Graphql.combinedErrorToString`).
Hopefully this improves the debug-ability of the bot.
=> Make bot errors readable

src/app/cli/src/init/coda_run.ml, src/lib/exit_handlers/dune, src/lib/exit_handlers/exit_handlers.ml
Add new function `register_async_shutdown_handler`.
Tested with:
- handler that returns `Deferred.unit`
- handler that raises an exception
The registration and execution of both handlers was logged, and the exception logged.
Verified that these handlers, and the ordinary exit handlers run on both Ctl-C and `client stop-daemon`. The exit code is 130 for Ctl-C and 0 for `stop-daemon`.
=> Registration of async shutdown handlers

src/lib/sparse_ledger_lib/sparse_ledger.ml
This PR tweaks the error messages in `Sparse_ledger` to expose the index and information about the kind of node that was found when there is a mismatch.
Checklist:
=> Expose more information in Sparse_ledger error messages

src/app/cli/src/init/coda_run.ml, src/app/cli/src/init/graphql_internal.ml
It has come to our attention that though it isn't specified in the graphql spec, many (most?) graphql clients expect a status code 200 even when a graphql request returns with some errors.
Unfortunately, ocaml-graphql-server does not support changing the return value in this case, returning 500 and causing issues in both Apollo and Urql (two js graphql clients we use).
This would a 1-line change to `https://github.com/andreas/ocaml-graphql-server/blob/master/graphql-cohttp/src/graphql_cohttp.ml`, so in this PR I have copied that file over and changed the line.
Unfortunately due to a pretty restrictive mli file, it's hard to avoid copying most of the file. I could probably remove some of it, but this seemed easier to understand.
Another option would be doing the fork/vendor/submodule dance …
=> Return status-code 200 on graphql server error

README.md
Looks like some docs got moved around and the README links were dead.  Cleaned them up so they're like new!
yet.
Checklist:
Closes #0000
Closes #0000
=> Cleaning up some broken links on the root README

src/app/libp2p_helper/src/codanet.go
broken compile -- this fixes
```
codanet
./codanet.go:12:2: imported and not used: "github.com/libp2p/go-libp2p-core/network"
```
=> trivial: remove unused import

dockerfiles/Dockerfile-toolchain, scripts/update-opam-in-docker.sh
When running a Docker image, there's a file `/.dockerenv`.
The script `update-opam-in-docker.sh` can use that, instead of `CODA_DOCKER`.
Remove that env variable from `Docker-toolchain`, since it's no longer needed. The image isn't rebuilt here, since nothing else has changed.
=> Use .dockerenv, not CODA_DOCKER

src/config/scan_state/1tps.mlh, src/config/scan_state/standard.mlh, src/lib/snark_params/scan_state_constants.ml
Instead of specifying an integer TPS goal, specify TPS * 10 goal, so we can try TPSs of 1.5, 2.5, etc.
Note: when building locally for `testnet_postake_medium_curves`, I got an error, not certain whether related to this fix:
```
\n  \"Spare_ledger.get: Bad index 0. Expected a node, but got a hash at depth 10.\")\
```
Update: seems to build in CI, so not sure why I got this failure.
=> TPS goal times 10

src/app/cli/src/tests/coda_process.ml, src/lib/coda_lib/coda_lib.ml
@jkrauska observed a `no child processes` error caused by a `waitpid` with `NOHANG`, caught by the outer Async monitor, crashing the daemon.
`Process.wait` calls `waitpid`, and can raise. Wrapped a couple of these in `Monitor.try_with`: one in the integration test code, and one in `Coda_lib` for snark workers (probably the one @jkrauska observed).
There are also such calls in Kademlia code, in `Coda_net2`, and in the `testone` app. I didn't modify those, since they're not the causes of the crash as far as I can see.
=> Wrap Process.wait in Monitor.try_with

src/app/cli/src/coda.ml, src/app/cli/src/tests/coda_worker.ml, src/app/cli/src/tests/full_test.ml, src/lib/child_processes/dune, src/lib/child_processes/termination.ml, src/lib/network_pool/snark_pool.ml, src/lib/network_pool/test.ml, src/lib/prover/prover.ml, src/lib/staged_ledger/staged_ledger.ml, src/lib/transition_frontier_controller_tests/test_bootstrap_controller.ml, src/lib/transition_frontier_controller_tests/test_catchup_scheduler.ml, src/lib/transition_frontier_controller_tests/test_ledger_catchup.ml, src/lib/transition_frontier_controller_tests/test_sync_handler.ml, src/lib/transition_frontier_controller_tests/test_transaction_status.ml, src/lib/transition_frontier_controller_tests/test_transition_frontier.ml, src/lib/transition_frontier_controller_tests/test_transition_frontier_persistence.ml, src/lib/verifier/prod.ml
Associate a "kind" for child processes that are registered to terminate the daemon. Current kinds are `Verifier` and `Prover`.
Closes #3566.
Sample log entries:
```
{"timestamp":"2019-10-04 20:24:34.658280Z","level":"Info","source":{"module":"Prover","location":"File \"lib/prover/prover.ml\", line 248, characters 51-58"},"message":"Daemon started process of kind $process_kind with pid $prover_pid","metadata":{"pid":22050,"process_kind":"Prover","prover_pid":22130}}
```
and
```
{"timestamp":"2019-10-04 20:25:34.045796Z","level":"Error","source":{"module":"Child_processes__Termination","location":"File \"lib/child_processes/termination.ml\", line 21, characters 54-61"},"message":"Child process of kind $process_kind with pid $child_pid has terminated; terminating parent process …
```
=> Kinds for child processes

frontend/website/src/Testnet.re
=> Website: Fix leaderboard table styles

src/app/cli/src/tests/coda_archive_node_test.ml, src/app/cli/src/tests/coda_batch_payment_test.ml, src/app/cli/src/tests/coda_block_production_test.ml, src/app/cli/src/tests/coda_bootstrap_test.ml, src/app/cli/src/tests/coda_change_snark_worker_test.ml, src/app/cli/src/tests/coda_delegation_test.ml, src/app/cli/src/tests/coda_five_nodes_test.ml, src/app/cli/src/tests/coda_long_fork.ml, src/app/cli/src/tests/coda_peers_test.ml, src/app/cli/src/tests/coda_process.ml, src/app/cli/src/tests/coda_receipt_chain_test.ml, src/app/cli/src/tests/coda_restart_node_test.ml, src/app/cli/src/tests/coda_restarts_and_txns_holy_grail.ml, src/app/cli/src/tests/coda_shared_prefix_multiproposer_test.ml, src/app/cli/src/tests/coda_shared_prefix_test.ml, src/app/cli/src/tests/coda_shared_state_test.ml, src/app/cli/src/tests/coda_transitive_peers_test.ml, src/app/cli/src/tests/coda_txns_and_restart_non_proposers.ml, src/app/cli/src/tests/coda_worker_testnet.ml
Use `Monitor.try_with` for the `stop_snark_worker` RPC in `Coda_process.disconnect` used for integration tests.
Log any error, also the error when the connected node terminates.
Closes #3231.
=> Try-with for stop_snark_worker RPC in disconnect

src/lib/coda_graphql/coda_graphql.ml
As discussed here: https://discordapp.com/channels/484437221055922177/601215883939020852/631905317600362509
This resolves the issue where epoch was being used incorrectly for slot.
=> Fix bug where epoch was used instead of slot

src/lib/blockchain_snark/blockchain_transition.ml, src/lib/transaction_snark/transaction_snark.ml
Snarky added `Proof.get_dummy`, which is a stable value that can be used in serialization tests.
Update the Snarky submodule commit to be able to access that.
=> Update snarky for dummy proofs

scripts/pin-external-packages.sh, scripts/update-opam-in-docker.sh
We're not pinning `ppx_optcomp` in the Docker toolchain image; I don't have it pinned locally, and my builds work. @nholland94 says it's not meant to be pinned.
So the `update-opam-in-docker.sh` and `pin-external-packages.sh` scripts should also not pin it.
There are a couple of references to `ppx_optcomp` in the Docker toolchain build that remove the `.git` file and create a hash. Those are harmless, I believe, and @enolan will likely remove those in an upcoming PR.
=> Don't pin ppx_optcomp in scripts

src/config/testnet_postake_medium_curves.mlh
smoketest and other standalone testnets need the normal ledger
=> TRIVIAL: revert to testnet ledger

src/lib/kademlia/membership.ml, src/lib/non_empty_list/dune, src/lib/non_empty_list/non_empty_list.ml, src/lib/non_empty_list/non_empty_list.mli, src/lib/transition_frontier/transition_frontier.ml
This hotfix aims to address some of the issues we have been seeing on the latest testnet, the root cause of which we currently believe to be the extremely long async cycles we are observing. Based on log activity, I have evidence to believe the long async cycles are caused when the root of the transition frontier is moved. This PR does two things to help remediate this: it splits the process of moving the transition frontier root up into multiple deferred's, and it disables some very expensive metrics we were computing when moving the root (sorry @yourbuddyconner, I'll get them back in soon).
I have 1 major concern with this PR, which is that I don't know exactly what would happen if the transition frontier is queried while it is in the middle of updating a root. Implementing a read lock …
=> [HOTFIX] Divide frontier update and disable expensive metrics

src/lib/coda_graphql/coda_graphql.ml, src/lib/sync_status/dune, src/lib/sync_status/sync_status.ml
@figitaki mentioned that sync status could return a null, even though the type is a non-null. This should not happen. However, it is happening because we do not include `Catchup` as a sync status for Graphql. This PR addresses this type of inconsistency once and for all. I created a little program using ppx_deriving.enum to make sure that the Graphql type of Sync_status matches with the actual Sync_status type.
Now, the Catchup status will be shown:
Checklist:
=> Fix the possibility of introducing a null for sync status

src/app/cli/src/tests/coda_worker.ml, src/lib/coda_base/account.ml, src/lib/merkle_ledger_tests/test_stubs.ml
Use the new `[%%versioned` ppx instead of manual registration of versioned modules.
The type `V1.key` was `bin_io` and should have been versioned, but wasn't, fixed here.
Because registration is done via the ppx, we don't have to import `Module_version`, and we don't need the `T` modules inside `Vn` modules.
First of many such PRs to come.
=> versioned ppx for Account

frontend/wallet/src/render/components/Button.re, frontend/wallet/src/render/components/TextField.re
Uses hover state currently on active and focus states for buttons (will have to revisit for design)
=> Wallet: adds active and focus button styles 

.circleci/config.yml, .circleci/config.yml.jinja, README-dev.md, dockerfiles/Dockerfile, dockerfiles/Dockerfile-toolchain, scripts/macos-setup-brew.sh, scripts/rebuild-deb.sh, src/app/cli/src/coda.ml, src/app/cli/src/dune, src/dune, src/lib/coda_metrics/coda_metrics.ml, src/lib/coda_metrics/dune, src/lib/kademlia/membership.ml, src/opam.export
Use Jemalloc in place of glibc malloc and collect stats from it. This improves overall memory use by a lot: the proportional set size is 3.4gb on my test machine with 3h19m uptime, while a node on seared-kobe with 3h11m of uptime is using 5.3gb. It also makes the program less leaky over time, due to reduced heap fragmentation. It may or may not still leak, it's been hard to keep a node up for long enough to tell a clear trend.
=> Jemalloc for develop

src/lib/gossip_net/gossip_net.ml, src/lib/kademlia/membership.ml
It was possible to try restarting the helper twice simultaneously, which led to a crash.
=> Fix another race with kademlia helper restarts

src/lib/network_pool/priced_proof.ml
`%%versioned` in `Priced_proof`.
There are other versioned modules in `Network_pool`, but they're in functors, and so should be hoisted out, before we apply the ppx.
=> Versioned ppx in Priced_proof

Makefile, src/app/cli/src/coda.ml, src/lib/coda_metrics/coda_metrics.ml
This tracks long jobs, not just long cycles (which are a collection of jobs)
=> long job time tracking

frontend/wallet/package.json, frontend/wallet/src/main/DaemonProcess.re, frontend/wallet/src/render/Theme.re
AppImage building successfully on ubuntu and running against apt-get daemon.
Not building deb for now. Had to change the coda-config dir as appimage mounts are read-only.
Tested on ubuntu and arch with at least moderate success.
Future work: Built the appimage in CI.
=> Enable the wallet to build on linux

src/lib/trust_system/peer_trust.ml
Closes #3418 
In trust layer peers are only known by IP.
In communications peers are known by IP and other metadata (gossip and discovery ports).
This change adjusts how trust layer describes bans to use a new metadata keyword peer_id, which is more usable in this context and doesn't overload the other representation of peer used by other parts of the code.
=> Fix metadata.peer in trust to differentiate from communications

frontend/website/docs/my-first-transaction.md
There's some question of whether we should link to https://github.com/CodaProtocol/coda/blob/develop/frontend/bot/src/Echo.re instead but the python one seems a little more digestible.
=> Website: Fix echo service link

src/lib/ppx_coda/versioned.ml
In a versioned type, require that any types mentioned in constraints are also versioned.
Tested by changing the constraint types in `External_transition.Validation.Stable.V1.t` to non-versioned types; the ppx made them red in Emacs.
Not sure if the new case for `Ptyp_any` could be trouble somewhere.
Also, maybe we should only try to generate code for constraints of the form `type-param = some-type` (the usual case, but constraints can mention arbitrary pairs of types).
Closes #3729.
=> Require versioned types in constraints

src/lib/coda_base/block_time.ml, src/lib/coda_base/block_time.mli, src/lib/coda_commands/coda_commands.ml
`Next proposal` in coda client status didn't obey time offsets because it used Core time instead of Block_time. Now it will obey the time offsets.
=> Next proposal status supports time offsets

src/lib/daemon_rpcs/daemon_rpcs.ml, src/lib/signature_lib/keypair.ml, src/lib/signature_lib/keypair.mli
Apply `%%version` to many daemon RPC types. Some are not done, because they rely on a number of other `bin_io` types that need versioning. The linter will remind us to do those.
This is part of the program of versioning all types with `bin_io`.
Removed the definitions of `type error`, which were not used.
Partially addresses #3667: Many of the linter warnings are removed, a number remain.
=> %%versioned many daemon RPC types

.circleci/config.yml, .circleci/config.yml.jinja
We've had several issues deploying because libp2p_helper is only built in prod. We should enforce that it builds every PR.
=> Build libp2p in CI

src/lib/coda_lib/coda_lib.ml, src/lib/staged_ledger/staged_ledger.ml, src/lib/staged_ledger/staged_ledger.mli
just ran `make reformat`
Checklist:
=> fix ocaml format

frontend/website/docs/troubleshooting.md
$ sudo upnpc -r 8302 TCP 8303 TCP
If this command succeeds, you'll see a response indicating that the ports have been successfully redirected:
```
...
InternalIP:Port = 192.168.101.7:8302
external 148.64.99.117:8302 TCP is redirected to internal 192.168.101.7:8302 (duration=0)
InternalIP:Port = 192.168.101.7:8303
external 148.64.99.117:8303 TCP is redirected to internal 192.168.101.7:8303 (duration=0)
``
yet.
Checklist:
Closes #0000
Closes #0000
=> Update Using UPnP

src/app/cli/src/coda.ml, src/app/cli/src/tests/coda_worker.ml, src/app/cli/src/tests/full_test.ml, src/lib/auxiliary_database/external_transition_database.ml, src/lib/auxiliary_database/transaction_database.ml, src/lib/coda_base/ledger.ml, src/lib/kademlia/membership.ml, src/lib/key_value_database/key_value_database.ml, src/lib/merkle_ledger/database.ml, src/lib/merkle_ledger/intf.ml, src/lib/merkle_ledger_tests/test_stubs.ml, src/lib/receipt_chain_database/intf.ml, src/lib/receipt_chain_database/receipt_chain_database.ml, src/lib/receipt_chain_database/receipt_chain_database.mli, src/lib/rocksdb/database.ml, src/lib/rocksdb/serializable.ml, src/lib/test/dune, src/lib/test/test.ml, src/lib/transition_frontier_controller_tests/test_transition_frontier_persistence.ml, src/lib/transition_frontier_persistence/transition_frontier_persistence.ml, src/lib/transition_frontier_persistence/worker.ml, src/lib/trust_system/peer_trust.ml, src/lib/trust_system/peer_trust.mli
- Some instances of Key-value database now need an input of an integer,
so the constructor inputs of the database are now functored
- This made some of the tests cleaner as the client does not have to
input a string value for databases that didn't require a string
- Refactored functor inputs for peer_trust.ml so that it fits to our
coding style
Checklist:
Closes #0000
Closes #0000
=> Functored the inputs for Key-value database

frontend/wallet/src/main/App.re, frontend/wallet/src/main/DaemonProcess.re
Adds a link to view wallet logs from the tray.
=> Wallet: Add log link to tray

src/app/cli/src/coda.ml, src/lib/coda_metrics/coda_metrics.ml
I got confused before about which things were kilobytes and which were bytes. It's right now.
=> Fix units in jemalloc stats

src/lib/auxiliary_database/filtered_external_transition.ml, src/lib/coda_graphql/coda_graphql.ml
=> Displaying proof in external_transition

scripts/rebuild-deb.sh
The PV keys now seem to be of this format:
/var/lib/coda/4e6d9a9afabfcf88877b1c7a490f92cd_step_verification
instead of just HASH_proving and HASH_verifying
This change should find them and install them in debs
=> URGENT/SIMPLE: PV Keys changed names - this tries harder to find them

src/lib/coda_graphql/coda_graphql.ml, src/lib/coda_graphql/dune
Very experimental, unlikely that we will keep this format, but this is necessary for verifying statehash in the browser.
=> Graphql: add experimental verification key

src/lib/ppx_coda/lint_version_syntax.ml, src/lib/secrets/secret_box.ml
Just as we already prohibited `include Stable.Latest`, also disallow `include Stable.Vn`.
Fixed the one occurrence of that. It was benign, because the type was not `bin_io` or versioned, but better to not have that construct.
=> Disallow include Stable.Vn

scripts/compare_versioned_types.py
Assign `mod` in `try/except` block. 
The exception occurs when the module path to a versioned type in the base branch doesn't appear in the PR branch.
=> Assign mod in try/except

src/lib/coda_version/dune
Without this, partial rebuilds won't update the reported git hash and the
version message will be wrong.
Tested by running `dune b` with and without the change and looking at the modification time of the relevant file.
=> Always rebuild coda_version.ml

src/lib/coda_numbers/dune, src/lib/coda_numbers/intf.ml, src/lib/coda_numbers/nat.ml, src/lib/consensus/global_slot.mli
Remove `bin_io` from body of functor `Nat.Make`.
The functors `Make32` and `Make64`  now have the `Stable` modules with `bin_io` types in their bodies. Those are functors of no arguments, where such types are allowed.
The errors-as-warnings flag to `ppx_coda` in the dune file is removed.
There's some tweaking of the interface in `global_slot.mli` to accommodate the change.
=> Nat, no bin_io in Make body

src/lib/trust_system/dune, src/lib/trust_system/peer_trust.ml, src/lib/trust_system/record.ml, src/lib/trust_system/record.mli
Use `%%versioned` for the serialized type in `Trust_system.Record`.
The versioned module is passed to `Rocksdb.Serialized.Make`. We'll see if we can change that in a subsequent PR.
=> Versioned ppx in Trust_system.Record

scripts/test.py
This change makes it so the exit status of integration tests is the exit status of `test.py`. Before it'd always appear to succeed because we were using `;` in the bash script, which swallows the exit status of the previous command.
=> Preserve exit status of integration tests in CI

src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
Since we are passing empty stacks (as part of the pending coinbase hack), when validating the scan state the target stack should be empty
=> fix for "bad statement"

src/lib/snark_params/snark_params.ml
This PR updates snarky to
* fix libsnark JSON printing
* stop libsnark printing from closing stdout.
Checklist:
=> Bump snarky for JSON printing

src/lib/blockchain_snark/blockchain_transition.ml, src/lib/cached/cached.ml, src/lib/cached/cached.mli, src/lib/snark_keys/gen_keys/gen_keys.ml, src/lib/transaction_snark/transaction_snark.ml, src/lib/transaction_snark/transaction_snark.mli
With the record the code looked really messy, so I wrapped it up into
what is essentially a `('a, Track_generated.t) Deferred.Writer.t` and
it's a lot cleaner (no more manual tracking the dirty bits nor messing
with the records)
Tested by running it in CI last time (also the compiler)
=> Fix nits requested by psteckler in #3845

frontend/wallet/src/render/components/Icon.re, frontend/wallet/src/render/views/onboarding/CompletionStep.re
First pass at the public key copier for the last step in onboarding. The current design is sort of confusing because it assumes we would be able to copy into the Discord channel in the next button, then this public key copier is pointless.
=> Make the public key copy button

frontend/wallet/src/render/views/settings/AccountSettings.re
Adds new warning when a node is synced, but the account has not received funds yet (so is not included in the ledger) 
Also fixes staking button refresh after disabling staking
=> Fixes: staking button refetch, and adds new well

frontend/wallet/package.json, frontend/wallet/src/main/DaemonProcess.re
Bump version number to `0.1.1`.
Update the peers for the new network.
Fix the wallet name.
=> Feature/wallet 0.1.1

.circleci/config.yml, .circleci/config.yml.jinja
build-archive has been running in CircleCI for over a month, but has never passed.
approximately 7m of compute time @ ~10x a day for ~30 days adds up.
This PR comments out build-archive so it's easy to re-add once it's working.
=> disable build-archive until its working

.circleci/config.yml, scripts/test.py
Holy Grail's second test fails regularly
```
Running test -- test_postake_holy_grail:coda-restarts-and-txns-holy-grail -num-proposers 5 -- SUCCEEDS
Running test -- test_postake_holy_grail:coda-long-fork -num-proposers 5 - FAILS
```
The first test succeeds - so let's keep it.
We're not learning anything by continually failing the second test - so let's remove it.
=> remove grail test long fork

frontend/website/docs/developers/index.md
Concurrent PR with Developer Portal page
=> Update docs to have Github link

.circleci/config.yml.jinja
* Remove complexity in jinja (skip a few ifs, only use xl)
* Only run docker for primary builds
* doesn't change rendered copy on develop
=> simplify artifact builds

src/lib/coda_networking/coda_networking.ml
Add comment about the "master" types in `Coda_networking`.
Wanted to make it clear that these are the types internal to the code base.
=> Better comment re network master types

src/lib/coda_lib/coda_subscriptions.ml
Fixed a bug that @michellewong793 and @Schmavery. Hopefully this quick fix works :).
Checklist:
Closes #0000
Closes #0000
=> Attempt to fix tuple pipe equality

frontend/bot/src/App.re, frontend/bot/src/Coda.re, frontend/bot/src/Echo.re, frontend/bot/src/Faucet.re, frontend/bot/src/Repeater.re
Since the daemon container can restart independently of the bot, we need to make sure the accounts are unlocked before sending transactions.
=> Bot: Always unlock before sending

README-dev.md
In `README-dev`, mention `libp2p_helper` make target instead of `kademlia`.
=> Mention libp2p, not kademlia build

.circleci/config.yml, .circleci/config.yml.jinja
The new `ppx_optcomp` has been breaking the `lint-opt` task in CI.
It looks like `config.mlh` is not found. Let's see if building that file explicitly fixes the problem.
Update: we weren't actually using the pinned `ppx_optcomp`. Latest commit fixes that.
=> Use pinned ppx_optcomp in lint-opt

scripts/publish-deb.sh
Simpler use cases for publish-deb and command line option to make it easier to use for one-offs.
=> publish deb improvement

src/lib/ppx_coda/versioned_module.ml
While working on the nonconsensus code, I discovered that `%%versioned_asserted` did not work when the type did not have an existing `deriving` list. Fixed here (I tested the fix on such a type).
=> Insert version {asserted} when no deriving list

frontend/website/static/js/leaderboard.js
changes leaderboard.js to pull challenge header from challenge sheet rather than main sheet. Now, they both have to be udpated, but easier to rename release when adding challenges
=> pull challenge header from challenge page

src/lib/non_zero_curve_point/non_zero_curve_point.ml
In `Non_zero_curve_point`, we had no assurance that the `Arg` module contained the same type as the main `Stable` module. I had earlier tried adding a type constraint to the type `t`, but got an error.
The solution is to add the constraint to a dummy type.
=> Add type constraint for Arg

src/lib/base58_check/version_bytes.ml, src/lib/staged_ledger/staged_ledger.ml, src/lib/staged_ledger/staged_ledger.mli, src/lib/transition_frontier/frontier_base/dune, src/lib/transition_frontier/frontier_base/frontier_hash.ml, src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
We don't need to validate the scan state when deserializing from disk since we are assumed to have already validated prior to recording it on disk. This PR changes the persistent frontier loading to construct the staged ledger without verifying the SNARKs in the scan state.
Also included in this PR is proper base58 encoding of frontier hashes so that their JSON representation does not contain binary garbage strings. Additionally, I alphabetically ordered `version_bytes.ml` in the base58_check library, at @psteckler's request.
=> Skip Scan State Validation on Persistent Loads

src/lib/auxiliary_database/external_transition_database.ml
It seems that actually the blocks were already sorted in order of block_time? But in ascending order. Descending seems to make more sense but lmk if you disagree.
Not sure if there's a better way to do this and it's a bit hard to test but it seemed like a small change.
=> Graphql: sort blocks in descending order

src/lib/coda_state/protocol_state.ml
For `Protocol_state`, conditionally compile the snarky-related bits. Nonconsensus code won't use those bits.
=> Protocol state, nonconsensus conditional compilation

src/lib/coda_base/coinbase.ml
Don't use versioned types for definition of `Coinbase.t`.
The definition of the `Stable` types should use `%%versioned`. The reason it's not is the use of `Binable.Of_binable`. That should probably go away, see #1767. The check for validity should go elsewhere, IMHO.
=> No versioned types in Coinbase.t defn

src/app/cli/src/coda.ml, src/app/cli/src/init/client.ml
`coda client` -> `coda client-old`
`coda client2` -> `coda client`
Deprecates current client commands (using rpc) in favour of the new ones. Leaves the old commands accessible for now in case there is an unforeseen issue in transitioning over. Also copies over some commands like `set-snark-worker` and `status` so we still have them in client.
One potential issue might be that this doesn't support CODA_PRIVKEY_PASS, hopefully `coda account unlock` is enough to account for this, but if not we can discuss.
=> CLI: promote client2 to client

src/config/testnet_postake_medium_curves.mlh
9000 accounts was exhibiting the /slow/ responsiveness in the client.
'coda version' taking > 1m
bumping back down to 256
=> TRIVIAL: reduce fake accounts to 256

scripts/rebuild-deb.sh
Currently our CI deb file generate debs the deposit coda binaries and /var/lib/coda content with uid 1001.  While this works for our testnets, most debs install software with uid root.
fakeroot is the common way to build a deb which will install with uid 0 ownership.
=> TRIVIAL: use fakeroot when building deb

frontend/website2/src/components/Page.re, frontend/website2/src/pages/Blog.re, frontend/website2/src/pages/BlogPost.re, frontend/website2/src/pages/Careers.re, frontend/website2/src/pages/Developers.re, frontend/website2/src/pages/Index.re, frontend/website2/src/pages/JobPost.re, frontend/website2/src/pages/MarkdownPage.re, frontend/website2/src/pages/Testnet.re
Copied over several things from the old site and attempted to improve a bit.
Added canonical links to every page (https://yoast.com/rel-canonical/ + [google's advice](http://www.thesempost.com/using-rel-canonical-on-all-pages-for-duplicate-content-protection/)). The way we're doing might not be perfect but gives us a bit of control without too much hassle.
Customized the page title per page -- followed some advice [here](https://www.creativebloq.com/how-to/build-an-seo-friendly-head-component-for-nextjsreact), [here](https://www.searchenginejournal.com/on-page-seo/title-tag-optimization/) pointing out the downsides of duplicate title tags and suggesting that they usually match the h1.
Also added favicon and other og meta tags.
=> Website2: Add page metadata to head

frontend/website2/next.config.js, frontend/website2/src/bindings/Contentful.re, frontend/website2/src/bindings/Next.re
Add the ability to specify the contentful host for use with the contentful preview api. Shouldn't affect the live site at all.
=> Website: Specify contentful host

frontend/website2/pages/docs/getting-started.mdx, frontend/website2/src/components/TeamSection.re
Updates the installation instructions for Linux to temporarily use Docker so we can temporarily use the release candidate testnet.
Additionally updates @emberian's name.
=> Website: Update docs for release candidate

frontend/website2/src/pages/Docs.re
Taking suggestions for other ideas! Just an attempt to make the edit button look a liiiittle better 
Before: <img width="296" alt="Screen Shot 2020-01-21 at 4 24 26 PM" src="https://user-images.githubusercontent.com/12700801/72854852-87c11780-3c6a-11ea-84d5-2cf2ef946260.png">
After: <img width="323" alt="Screen Shot 2020-01-21 at 4 22 27 PM" src="https://user-images.githubusercontent.com/12700801/72854819-67915880-3c6a-11ea-969e-9a37650a3753.png">
=> Change positioning of edit button on mobile

src/lib/transition_handler/processor.ml
This PR increases the waiting time in processor_handler test from 5s to 30s.
I doesn't see anything suspicious from log. Since we are using `Deferred.choose`, which would execute every deferred computation, so the test goes on even though the timeout expires. This give me the confidence to increase the waiting time because the log indicates the test ends successfully.
=> Fix processor_handler test

src/lib/bootstrap_controller/bootstrap_controller.ml, src/lib/transition_router/transition_router.ml
This Hotfix makes bootstrap controller uses existing transitions to initiate the bootstrap processes.
I tested it on my machine. It took approximately 6min to finish bootstrap.
I also added some logs for bootstrap controller to record the time to different steps in bootstrap.
=> [Hotfix] bootstrap using existing transition

frontend/website/src/components/Challenges.re, frontend/website/src/components/Leaderboard.re, frontend/website/src/pages/Testnet.re
This is what the leaderboard will look like if the points service is down. If we have leaderboard info but no active testnet, we'll show what we have. If we have challenge info but no active testnet, we don't show the challenges.
Also discovered an interesting issue in Next.. which means we need to avoid passing option in a tuple/array (which is why I split testnetName into its own prop)
=> Website: Handle points service failure

frontend/website/pages/docs/troubleshooting.mdx
"i tried to forward ports but couldnt figure it out on the troubleshooting page
when I try to run this command : $ sudo upnpc -r 8302 TCP 8303 TCP
i get a command not recognized"
better to just remove the $
=> remove bling from command

frontend/website/.gitignore, frontend/website/package.json, frontend/website/pages/docs/developers/graphql-api.mdx, frontend/website/yarn.lock
We lost the graphql docs when moving to the new website.
There was talk of doing something better than what we had but in the meantime it's better to at least have what we had again :)
=> Website: restore graphql docs

scripts/rebuild-deb.sh
Without this, INTERP is set to a dangling path and you'll see `bash: /usr/local/bin/coda-libp2p_helper: No such file or directory` when trying to run the helper in a container.
=> patchelf the coda-libp2p_helper

src/lib/coda_networking/coda_networking.ml, src/lib/gossip_net/libp2p.ml
I believe all metrics are now implemented.
This implements max blocklength as the max _valid_ block. Should it instead be _any_ block, even invalid ones? This opens the metric up for potential abuse.
Closes #3725
=> Implement gossip_messages_received, and peers metrics

src/lib/coda_intf/transition_frontier_components_intf.ml, src/lib/coda_lib/coda_lib.ml, src/lib/transition_handler/processor.ml
This will hide logs that trigger when we refuse to rebroadcast blocks we receive during catchup. It also heightens the level of logs for when internally generated blocks are not rebroadcast (which is an indication of a serious performance issue or misconfiguration).
=> Improve transition rebroadcasting logging

src/lib/coda_lib/coda_lib.ml, src/lib/transition_frontier/extensions/best_tip_diff.ml, src/lib/transition_frontier/extensions/extensions.ml, src/lib/transition_frontier/extensions/extensions.mli, src/lib/transition_frontier/extensions/identity.ml, src/lib/transition_frontier/extensions/identity.mli, src/lib/transition_frontier/extensions/intf.ml, src/lib/transition_frontier/extensions/ledger_table.ml, src/lib/transition_frontier/extensions/new_breadcrumbs.ml, src/lib/transition_frontier/extensions/root_history.ml, src/lib/transition_frontier/extensions/snark_pool_refcount.ml, src/lib/transition_frontier/extensions/transition_registry.ml, src/lib/transition_frontier/frontier_base/diff.ml, src/lib/transition_frontier/frontier_base/diff.mli, src/lib/transition_frontier/full_frontier/full_frontier.ml, src/lib/transition_frontier/full_frontier/full_frontier.mli, src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml, src/lib/transition_frontier/transition_frontier.ml
The `Best_tip_diff` extension was getting the old best tip from frontier after it was updated with the new best tip, resulting in transactions from the new chain not being added and transactions from the old chain not being removed from the transaction pool. This is another reason for #4298. 
A diff now will contain the mutant as well which in the case of `Best_tip_diff` is the old best tip
Checklist:
=> fix best_tip_diff extension

scripts/run-demo.sh, src/app/cli/src/coda.ml, src/lib/coda_lib/coda_lib.ml, src/lib/coda_lib/config.ml
Adds `-demo-mode` to daemon flags -- for now `demo-mode` means that sync-status is instantly and always `synced` (as it should be for a one-node network). In the future, we can expand on what effects this flag has on the rest of the daemon.
=> Demo mode sync status

src/lib/coda_metrics/coda_metrics.ml
Made a silly mistake when addressing some PR comments for my block latency metrics.
=> Fix times for block latency metrics

frontend/website/pages/docs/contributing.mdx, frontend/website/src/components/StatusBadge.re, frontend/website/src/pages/Testnet.re
Changes links to the old Testnet form to point to the Genesis program per marketing's request. Also fixes the color in the status widget.
=> Website: Remove old testnet form

.mergify.yml, scripts/test.py
Two of the tests added for the client SDK code weren't made required in CI.
I think this change will do that.
=> Add build-client-sdk and noncon unit tests as required

graphql_schema.json, src/app/cli/src/init/client.ml, src/app/cli/src/init/graphql_client.ml, src/app/cli/src/init/graphql_queries.ml, src/lib/coda_commands/coda_commands.ml, src/lib/coda_graphql/coda_graphql.ml
setStaking was giving the impression that it didn't work because it silently failed to stake with keys that were locked. Now we return an indication to the user that those keys failed.
=> GraphQL/CLI: Indicate which keys failed to stake in setStaking

src/app/cli/src/coda.ml, src/app/cli/src/dune, src/lib/memory_stats/dune, src/lib/memory_stats/memory_stats.ml, src/lib/prover/dune, src/lib/prover/prover.ml, src/lib/verifier/dune, src/lib/verifier/prod.ml, src/memory_stats.opam
Take memory stats code that was in `coda.ml`, make it into a library.
Add call to that library in `coda.ml`, and in the prover and verifier process creation code.
=> Add memory stats for prover, verifier

src/lib/coda_base/target.ml, src/lib/coda_base/target.mli
Another removal of the soon-to-be-obsolete `Register` functor for versioning.
=> Target, use %%versioned_asserted

frontend/website/pages/docs/my-first-transaction.mdx
Fixes a broken link to the glossary found by @nat8552, thanks!
Closes #4484 
Co-authored-by: @nat8552 <nat8552@gmail.com>
=> Fix broken glossary link in docs

frontend/website/pages/docs/gui-wallet.mdx, frontend/website/src/pages/Genesis.re
Adds a simple link to the discourse FAQ thread. Can be replaced by the pretty FAQ when that's done.
Also:
- Clean up an old cdn-ed image in the docs
- Convert some internal links to tcGenesis to Next.Link (loads faster)
=> Website: Simple Genesis FAQ link

.circleci/config.yml, .circleci/config.yml.jinja, scripts/skip_if_only_frontend_or_rfcs.sh
Skip CI tests for RFCs, as we already do for frontend code.
Edit and rename skipping script, update CircleCI config to use new name.
=> Skip CI for RFCs

src/app/libp2p_helper/src/codanet.go, src/app/libp2p_helper/src/libp2p_helper/main.go, src/lib/coda_net2/coda_net2.ml, src/lib/gossip_net/libp2p.ml
This is going wrong for some reason, and it's blocking a lot of work. This should unblock that work while the root cause is still being debugged.
Impact: we'll gossip messages we otherwise wouldn't, including messages that cause bans (!!).
Additionally, I switched over from floodsub (tell all peers) to randomsub (tell 6 random peers). This should keep network activity lower, at the expense of not too much latency. I also decreased the libp2p log level, so we'll get debug logs.
=> libp2p: temporarily bypass topic validation

src/app/libp2p_helper/src/libp2p_helper/main.go
our logs are enormous because of all this spam. I'll decrease it locally when I want to debug, for the most part we don't need those logs.
=> decrease libp2p log level

frontend/client_sdk/.gitignore, frontend/client_sdk/README.md, frontend/client_sdk/package.json, frontend/client_sdk/src/CodaSDK.d.ts, frontend/client_sdk/src/CodaSDK.re, frontend/client_sdk/src/TSTypes.d.ts, frontend/client_sdk/src/TSTypes.ts, frontend/client_sdk/test/Test.ts
- Added signPayment example to docs
- Added ability to pass numeric arguments as numbers, automatically normalize them to string on use
- Fix bug in stake delegation signing and add a test for it
- Increase the version number to 0.1.2 in preparation for publishing these fixes to npm
=> SDK: Allow use of numbers and fix stake delegation

src/lib/pickles_types/abc.ml, src/lib/pickles_types/dlog_marlin_types.ml, src/lib/pickles_types/dune, src/lib/pickles_types/matrix_evals.ml, src/lib/pickles_types/pairing_marlin_types.ml
Looked at the recently-merged `Pickles_type` library, noticed the `%%versioned` ppx wasn't being used. Added that in several places. 
(There's a problematic `Binable` functor, not addressed here.)
=> Pickles type lib, cleanup versioning

src/app/libp2p_helper/src/libp2p_helper/main.go
Ran into an issue on the hangry-lobster testnet where the libp2p input buffer size would be exceeded when broadcasting messages from the daemon to the network. For now, I'm just doubling the size. I'm opened #4571 for a longer term solution that will prevent this from happening in the future.
=> Double libp2p input buffer size

frontend/website/src/pages/Genesis.re
This is an update to the page here:
=> Change copy in Genesis page 

src/lib/module_version/serialization.ml
Version-asserted types require tests to show their serialization hasn't changed. There's a function `check_serialization` for that purpose.
Until now, in order to show the expected result, you had to uncomment a line to print out a hash. In this PR, the expected and actual hashes are printed if they differ.
=> Print hashes in check_serialization when they differ

.circleci/config.yml, .circleci/config.yml.jinja
The archive test is disabled due to a typo; this corrects it.
Checklist:
=> Fix typo in archive test

.circleci/config.yml, .circleci/config.yml.jinja
If you pipe a failing command to `tee`, the exit status will be 0, ordinarily. That means CI was not detecting failed tests in some cases.
We add `set -o pipefail` so that a failing command in a pipeline gives the exit status of the failing command.
=> Set pipefail for CI commands using tee

src/config/test_archive_processor.mlh
This fixes the error in CI when compiling the `coda-archive-processor-test`
Checklist:
=> Add a fork_id to the archive test compile-time config

Makefile
This allows for local builds without installing cachix.
Checklist:
=> Don't call cachix for make build if we won't be using it

src/lib/ppx_coda/define_from_scope.ml, src/lib/ppx_coda/tests/Makefile, src/lib/ppx_coda/tests/define_from_scope_good.ml, src/lib/ppx_coda/tests/dune
Resurrect `%%define_from_scope` ppx.
You can write:
```ocaml
let x = ...
let y = ...
module T = struct
[%%define_from_scope (x,y)]
end
```
I originally wrote this so that a module `T` could be used as a functor argument. At the time, @bkase objected, arguing that it would be better to use `include`, and not complicate things.
But #4586 has a statement where some definitions are pulled into a module, not for the purpose of creating a functor argument. In that case, there are 9 items to be defined, so this ppx would help make the code more concise and prevent error.
Note: some the `ppx_coda` tests are failing because of recent changes in the linter; not fixed here. The test added for this ppx succeeds.
=> Resurrect define_from_scope ppx

frontend/website/src/components/MemberProfile.re
Small change to fix, will follow up with another PR to align icon and text on Safari 
Has checked that this doesn't break on Chrome
=> Website: Fix genesis member profile text for Safari 

src/lib/coda_lib/coda_lib.ml, src/lib/coda_networking/coda_networking.ml, src/lib/coda_networking/coda_networking.mli, src/lib/node_addrs_and_ports/node_addrs_and_ports.ml
Include the node's peer ID in the telemetry response.
That's useful for the forthcoming telemetry script, which will build a map from peer IDs to responses.
=> Add peer id for node to telemetry I

.circleci/config.yml, .circleci/config.yml.jinja, Makefile, src/lib/snark_keys/gen_keys/gen_keys.ml
*Edit: Old description removed, retconning this for the actual fix.*
This updates the CircleCI artifacts job to continue after key generation 'fails'. This failure is done deliberately at a strategic point so that we can upload the keys before resuming the build.
=> Don't fail CI when we are generating keys

frontend/bot/src/Constants.re, frontend/bot/src/Messages.re
Fixes two issues with the bot:
- For some reason an extra newline is getting into the publickey env var (gotta fix the configuration but this will help for now)
- We aren't formatting the currency amount. I removed the parse function from CurrencyFormatter because we don't need it and it depends on bs-platform 7.... not the time to upgrade right now.
=> Bot: format currency, trim env vars

.circleci/config.yml, .circleci/config.yml.jinja
This was omitted in #4552, `test-archive` has been broken ever since.
Checklist:
=> Update docker image for test-archive

src/app/libp2p_helper/src/libp2p_helper/main.go, src/lib/gossip_net/libp2p.ml
We're seeing a ton of spam on startup and I think it's degrading the helper performance. Throttle how often we update the peer list instead of on every connection.
Also, unsynchronized map writes :scream_cat:
=> libp2p fixes for issues discovered in 0.0.13-beta

src/app/cli/src/coda.ml, src/app/cli/src/tests/coda_worker.ml, src/app/cli/src/tests/full_test.ml, src/lib/coda_lib/coda_lib.ml, src/lib/coda_lib/config.ml
Add CLI daemon flag `-disable-telemetry`. If set, the telemetry RPC returns an error indicating the disabling.
Note that this PR is against the `release/0.0.13-beta` branch.
Closes #4628.
=> Disable telemetry

src/app/libp2p_helper/src/libp2p_helper/main.go, src/lib/coda_lib/coda_lib.ml, src/lib/coda_transition/external_transition.ml, src/lib/coda_transition/external_transition_intf.ml, src/lib/gossip_net/libp2p.ml, src/lib/transition_frontier_controller/transition_frontier_controller.ml
This incorporates @ghost-not-in-the-shell 's fix for the validation callback duplication and forgotten mutex unlock, and undoes the validation bypass.
=> Re-enable validation

src/app/cli/src/coda.ml, src/app/cli/src/init/coda_run.ml, src/app/cli/src/tests/coda_worker.ml
Was observing that some nodes were occasionally getting stuck in a state where they continued running after a top-level exception was caught. I believe this may be some kind async bug, possibly involving interaction with the gossip net layer (since the gossip net layer is what broke in these scenarios, and the crash report generator does ask the gossip net code for some information). To alleviate this short term, I have added a 30 second timeout to crash report generation, after which it gives up. I've also added temporary trace logs to instrument the control flow and fix the underlying bug, which I plan to remove before the release.
=> Add timeout to crash report generation

frontend/website/pages/docs/hardware-wallet.mdx, frontend/website/pages/hardware-wallet.mdx, frontend/website/src/components/DocsSideNav.re
This PR adds more detailed instructions for getting the coda Ledger app up and running on the hardware wallet.
=> More detailed hardware wallet instructions

src/lib/coda_networking/coda_networking.ml, src/lib/verifier/prod.ml
Fixes these two interpolation errors:
```
logproc interpolation error in File "src/lib/coda_networking/coda_networking.ml", line 1299, characters 65-72: bad interpolation for peer
logproc interpolation error in File "src/lib/verifier/prod.ml", line 192, characters 62-69: bad interpolation for stderr
```
P.S. I was thinking we could add a compile-time setting to the logger to make interpolation errors crash the program when encountered during CI. Could be nice since they can be pretty obtrusive to users.
=> Fix log interpolation

src/lib/coda_networking/coda_networking.ml
previously was missing the block's state hash, and also the key for the block itself mismatched
=> make the -log-received-blocks log metadata match the rebroadcasting log

src/lib/base58_check/version_bytes.ml, src/lib/coda_base/ledger_hash.ml, src/lib/coda_base/receipt.ml, src/lib/coda_base/state_body_hash.ml, src/lib/coda_base/state_hash.ml
The Data_hash functors export to/of_yojson functions that go through the decimal representation of the field element. Avoid those, instead using the base58_check functions. Additionally, use base58_check for the state body hash.
=> data_hash: use b58 check for json

src/app/cli/src/coda.ml, src/app/cli/src/tests/coda_worker.ml, src/app/cli/src/tests/full_test.ml, src/app/libp2p_helper/src/codanet.go, src/app/libp2p_helper/src/libp2p_helper/main.go, src/config/testnet_postake_medium_curves.mlh, src/lib/child_processes/child_processes.ml, src/lib/coda_net2/coda_net2.ml, src/lib/coda_net2/coda_net2.mli, src/lib/gossip_net/libp2p.ml
This includes a few tweaks, most importantly the ability for some nodes to flood (should prevent any randomsub-related forks), and an attempt at avoiding the "subscriber too slow" problem we see by not blocking on acquiring the stdout lock.
=> libp2p tweaks for 3.2 QA

src/lib/snarky_field_extensions/dune, src/lib/sync_handler/dune
I ran an audit of the library and nonconsensus dune files to make sure the `inline_tests` clause was present if there were, in fact, inline tests.
I found missing clauses in `Snarky_field_extensions` and `Sync_handler`. For the latter library, the tests are commented out, but it's probably good to have the clause when the tests are re-enabled.
The missing clause for `Coda_lib_nonconsensus` is already fixed in #4691.
=> Add inline_tests to dune

.circleci/config.yml, .circleci/config.yml.jinja
The daily `test-unit--dev_medium_curves` CI task was failing, because it ran `dune build` without a specific target. That caused dune to try to build the nonconsensus code with a consensus profile, resulting in errors.
Using `make build` should allow this task to succeed.
=> Fix dev medium curves unit tests

src/config/dev.mlh, src/lib/block_time/block_time.ml, src/lib/block_time/block_time.mli, src/lib/coda_graphql/coda_graphql.ml, src/lib/coda_lib/coda_lib.ml, src/lib/coda_lib/coda_lib.mli
Adds utcDate field to blockchain state in graphql. This field adds back the CODA_TIME_OFFSET that gets subtracted from timestamps. This is required to get an accurate picture of the true system time of events in the network.
Also turning time-offsets on dev (as this is we'll need this on for our releases, so we should be dev-ing with it on too)
=> Adds utcDate field to graphql

scripts/run-demo.sh
This fixes the issue @garethtdavies noticed where the run-demo entrypoint depended on compile-time genesis timestamp
=> Rewrites run-demo.sh to use runtime genesis

frontend/website/pages/docs/developers/sandbox-node.mdx
I found a typo in new Docs.
Just fix typo.
Checklist:
=> Fix typo in Sandbox Node Docs

frontend/website/pages/docs/developers/sandbox-node.mdx
Adds instructions on getting a bash instance inside of the docker container. Seen this question asked quite a few times in discord and @garethtdavies has been providing this so I propose adding to the website.
=> Website: More Sandbox Instructions

src/lib/cached/cached.ml, src/lib/cached/cached.mli, src/lib/snark_keys/gen_keys/gen_keys.ml
This PR allows CI to run on external pull requests which change the snark, by overriding the cached keys check in the `snark_keys` for those pull requests. For example, #4783 fails CI because of this check.
Behaviour for internal PRs should be unchanged.
Checklist:
=> Allow CI to generate snark keys for external contributors

frontend/website/src/components/GenesisCTA.re, frontend/website/src/components/Leaderboard.re
Turns out whenever we switched support back to sheets from the api we broke it.
This requires a small edit to the sheet on deploy, so the deploy preview might not work properly. Here's a screenshot instead.
Edit: Actually I forgot that the deploy preview doesn't have permissions to fetch from the api in the first place.
Note: Since it requires an edit to the sheet, don't land this without knowing what change to make :)
=> Website: Display total points in leaderboard

frontend/wallet/src/render/views/settings/DelegationSettings.re
Added client-side validation for the delegate transaction fee. Currently, the delegation goes through if the transaction fee is invalid. Added validation for checking if the transaction fee is empty or below the minimum fee (0.00001). 
Tested by manual testing. Attempted the following:
- Empty transaction fee -> User Error
- Transaction fee that is below the minimum -> User Error
- Malformed transaction fee ->User Error
- Correct transaction fee but invalid delegate key -> User Error
- Correct delegate key and valid transaction fee -> Delegation goes through
Screenshots:
**Zero Transaction Fee**
**Transaction fee below minimum**
**Empty transaction fee**
Checklist:
=> Client side validation for invalid delegation transaction fee 

src/lib/gossip_net/message.ml, src/lib/network_pool/intf.ml, src/lib/network_pool/snark_pool.ml, src/lib/network_pool/snark_pool.mli, src/lib/network_pool/snark_pool_diff.ml, src/lib/network_pool/test.ml, src/lib/ppx_coda/versioned_type.ml, src/lib/transaction_snark_work/transaction_snark_work.ml
Lift versioned types out of `Snark_pool.Make` and `Snark_pool_diff.Make`.
Substituted `%%versioned` for the registration functor in `Transaction_snark_work`.
Change: `ppx_coda` considers `Foo.Stable.V1.{Table,Hash_set,Hash_queue}.t` to be versioned types. Such types are created by `Hashable.Make_binable`. Essentially, this is more whitelisting of Jane St types, though we don't have absolute guarantees they won't change.
=> Lift versioned type out of snark pool, diff functors

src/lib/coda_base/pending_coinbase.ml, src/lib/coda_base/pending_coinbase_intf.ml, src/lib/staged_ledger_hash/staged_ledger_hash.ml, src/lib/transaction_snark/transaction_snark.ml, src/lib/transaction_snark/transaction_snark.mli
Hoist versioned modules, `Stack`, `Hash`, `Merkle_tree`, and the versioned type for `Pending_coinbase` itself outside `Pending_coinbase.Make`, to avoid linter warnings.
There remains one linter warning for `Coda_base`.
=> Pending coinbase, hoist versioned types

src/lib/logger/dune, src/lib/logger/impl.ml
In `Logger.Impl`, use %%versioned_binable` and add stable-versioned module to `Binable.Of_binable` functor.
Removed errors-as-warnings flag from dune file.
=> Logger.Impl, use %%versioned_binable

src/lib/account_config/account_config.ml
This PR makes account-config parsing more flexible. In particular
* `option`al fields now do not need to be present in the JSON
* fields that are not part of the record will be ignored
e.g.
```json
[ {"pk": "some_pk_here", "balance": 20000, "ID": "big account"}
, {"pk": "another_pk_here", "sk": "sk", "balance": 20, "TODO": "Do something"} ]
```
Checklist:
=> Allow flexible account JSON

src/lib/coda_base/data_hash.ml, src/lib/coda_base/dune
The linter in `ppx_coda` flags `Binable.Of...` functor applications outside versioned modules, because those create serializations.
Moved `Binable.Of_stringable` inside `Data_hash.Make_full_size` to a versioned module outside the functor.
Removed the errors-as-warnings flag to `ppx_coda` in the `Coda_base` dune file.
=> Move Binable.Of_stringable to versioned module

src/lib/transaction_snark_scan_state/dune, src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
Replaced module registration with `%%versioned` in `Transaction_snark_scan_state`.
In dune file, removed errors-as-warnings flag to `ppx_coda`.
=> Add %%versioned to Transaction_snark_scan_state.t

.circleci/config.yml, .circleci/config.yml.jinja
Currently, the `update-branch-protection` job fails with an unmet python dependency. This job only runs on `develop`, see e.g. [here](https://app.circleci.com/pipelines/github/CodaProtocol/coda/20381/workflows/32c05370-8895-4ab0-a57c-9f6be2c7c2c7/jobs/383008/steps).
Checklist:
=> Fix update-branch-protection CI job

src/lib/perf_histograms/histogram.ml
For the serialized types in `Perf_histogram`, allow `bin_io_unversioned`, because these types are not persisted, nor sent to other nodes. They're used for local observation of performance. In `Coda_networking`, each RPC type has hooks into the histogram machinery, but the serialization used by the RPC code is not affected.
=> Perf_histograms, unversioned bin_io

src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml, src/config/ledger_depth/full.mlh, src/config/ledger_depth/small.mlh, src/config/ledger_depth/tiny.mlh, src/config/testnet_postake_medium_curves.mlh, src/lib/cache_dir/cache_dir.ml, src/lib/coda_compile_config/coda_compile_config.ml, src/lib/genesis_constants/genesis_constants.ml, src/lib/genesis_ledger/genesis_ledger.ml, src/lib/genesis_ledger/testnet_postake_ledger.ml
This PR
* removes the `fake_accounts_target` compile-time variable
* adds `fake_accounts_target` to `Genesis_constants.t`
* stores the number of accounts in a generated ledger as `fake_accounts_target`
* adds flexible parsing for the configuration file
- ie. missing fields will now be set as none, instead of raising a JSON parsing error
This gives us a way of distinguishing configurations with the same 'base' ledger, but different numbers of fake accounts.
Checklist:
=> Move fake_accounts_target to genesis_constants

src/lib/work_selector/dune, src/lib/work_selector/inputs.ml
The serialization in `Work_selector.Test_inputs.Ledger_proof` was apparently unused, removed it here.
The errors-as-warnings flag to `ppx_coda` in the `dune` file is removed.
=> Remove serialization from Ledger_proof

src/lib/network_pool/network_pool_base.ml
Much thanks to @emberian for finding this one. This appears to have been the culprit of the forky networks we have observed recently when transactions are enabled.
=> Fix network pool rebroadcast loop

src/config/amount_defaults/realistic.mlh, src/config/amount_defaults/standard.mlh, src/lib/coda_base/import.ml, src/lib/coda_base/user_command.ml, src/lib/coda_compile_config/coda_compile_config.ml
This was a required change to stabilize the testnet deployments which was somehow missed during the now-defunct release branch port to develop.
=> Properly configure minimum tx fee

frontend/website/src/components/Leaderboard.re
On our Testnet landing page we want the leaderboard to encourage and recognize participation in the current release. We intend for it to incentivize people who join midway in a phase and who will most likely not get on the top positions of the phase leaderboards that they could meaningfully make it close to the top for the current phase.
We pull directly from the leaderboard spreadsheet, so you may ask: Why not sort in the spreadsheet. Well, we don't pull data from the individual phase sheet, but instead the top-level phase sheet. The purpose of this sheet is different! https://docs.google.com/spreadsheets/d/1CLX9DF7oFDWb1UiimQXgh_J6jO4fVLJEcEnPVAOfq24/edit#gid=1000546858 the front-page sheet is for the full phase, the leaderboard view on our website focuses on the "current" phase. We …
=> Sorts leaderboard by current testnet, not total

src/lib/coda_base/ledger.ml, src/lib/merkle_ledger/database.ml, src/lib/merkle_ledger/dune, src/lib/merkle_ledger/location.ml, src/lib/merkle_ledger/location_intf.ml, src/lib/merkle_ledger/util.ml, src/lib/merkle_ledger_tests/test.ml, src/lib/merkle_ledger_tests/test_database.ml, src/lib/merkle_ledger_tests/test_mask.ml, src/lib/merkle_mask/dune, src/lib/merkle_mask/inputs_intf.ml, src/lib/merkle_mask/masking_merkle_tree.ml, src/lib/merkle_mask/masking_merkle_tree_intf.ml, src/lib/syncable_ledger/test.ml
Removed the `bin_io` on the type inside `Location.Make`. That serializability wasn't being used; further, removing `bin_io` from `Location_intf` doesn't affect compilation. We're also able to remove `bin_io` for `Masking_merkle_tree`.
We do need a `Table` for locations, so create a new module in `Coda_base.Ledger`, named `Location_binable` (`Table` is created via `Hashable.Of_binable`), and pass that through the functors in `Ledger`, ultimately used in `Merkle_ledger.Util`.
Remove the errors-as-warnings flag to `ppx_coda` in `Merkle_ledger` and `Merkle_mask`.
=> Remove bin_io inside Location.Make

.circleci/config.yml, .mergify.yml, scripts/test.py
Make `test_postake_split_snarkless` not required in CI, because it fails too often.
For `test_postake_bootstrap`, keep the required status, but remove the long-fork subtest, because it's not needed.
Closes #4853.
=> Unrequire split_snarkless test, remove long-fork bootstrap test

src/lib/coda_base/ledger.ml, src/lib/merkle_ledger/location.ml
Remove dead-code module `T` in `Location`.
In `Ledger`, rename `Location0` to `Location_at_depth`, remove the alias.
=> Remove some unneeded code

.buildkite/Makefile, .buildkite/agent.nix, .buildkite/docker.nix, .buildkite/hooks/post-checkout, .buildkite/shell.nix, .buildkite/src/Constants/ContainerImages.dhall, .buildkite/src/Lib/Command.dhall, .buildkite/src/Lib/Docker.dhall, .buildkite/src/Monorepo.dhall, .buildkite/src/Prepare.dhall, .buildkite/src/jobs/CheckDhall/Pipeline.dhall, .buildkite/src/jobs/Sample/Pipeline.dhall, .buildkite/src/jobs/Sample2/Pipeline.dhall
All jobs run in containers now. Builds remain quick and short-circuiting.
> This is with a single serial agent running on my laptop. It will be faster with parallel agents. Overhead of checking out with git, submodules etc, cleaning untracked files, and running in docker is ~5s per "command step".
So far all the jobs have minimal shell dependencies. `agent.nix` is extended to support both building of local shell environments and docker containers.
1. Created images are `FROM scratch` by default (the output containers are _tiny_ )
2. They are layered using a [fancy algorithm to minimize annoying rebuilds](https://grahamc.com/blog/nix-and-layered-docker-images).
3. The same specification supports both a local virtualization-free environment (nix) and a containerized one (docker).
4. No …
=> BuildKite jobs in Docker

src/lib/secrets/dune, src/lib/secrets/secret_box.ml, src/lib/secrets/secret_box.mli
`Secret_box` had a module `Stable` that did not have a type with `bin_io`, resulting in a linter warning.
Rename that module to `T` and remove the `V1` contained in it. The `Stable` module wasn't being used elsewhere, so remove that from the interface.
Remove the errors-as-warnings flag to `ppx_coda` in the dune file.
=> Secret_box, rename Stable module

src/app/cli/src/init/transaction_snark_profiler.ml, src/lib/coda_base/sparse_ledger.ml, src/lib/genesis_constants/genesis_constants.ml, src/lib/genesis_ledger/genesis_ledger.ml, src/lib/genesis_ledger_helper/genesis_ledger_helper.ml, src/lib/staged_ledger/staged_ledger.ml, src/lib/test_genesis_ledger/test_genesis_ledger.ml, src/lib/transaction_snark/transaction_snark.ml, src/lib/transition_frontier/tests/full_frontier_tests.ml
=> [TRIVIAL] Move ledger_depth into Genesis_constants.Constraint_constants.t

src/app/cli/src/init/coda_run.ml, src/lib/snark_worker/debug.ml, src/lib/snark_worker/dune, src/lib/snark_worker/functor.ml, src/lib/snark_worker/intf.ml, src/lib/snark_worker/prod.ml, src/lib/snark_worker/rpcs.ml, src/lib/snark_worker/snark_worker.ml
In `Snark_worker`, the `Rpcs.Make` functor was returning versioned Rpc modules with `bin_io` types, generating linter warnings.
Change the functor to return only the non-`bin-io` Master modules, and create the versioned modules after the functor applications (`Functor.Make` calls `Rpcs.Make`).
Remove the errors-as-warnings flag to `ppx_coda` in `dune`.
=> Snark_worker, versioned RPCs outside functors

src/lib/blake2/blake2.ml, src/lib/blake2/dune, src/lib/ppx_coda/versioned_module.ml
For the `Stable` module in `Blake2`, use `%%versioned_binable`. 
Add a serialization test, because the type comes from an external library, and its serialization depends on string functions in the library.
In `ppx_coda`, make sure we don't add `deriving bin_io` for verisioned-binable types.
=> Blake2, use %%versioned_binable

src/app/cli/src/tests/dune, src/lib/coda_transition/dune, src/lib/consensus/dune, src/lib/currency/dune, src/lib/gossip_net/dune, src/lib/group_map/dune, src/lib/merkle_address/dune, src/lib/merkle_ledger_tests/test_stubs.ml, src/lib/perf_histograms/dune, src/lib/pokolog/dune, src/lib/receipt_chain_database/dune, src/lib/signature_lib/dune, src/lib/storage/dune, src/lib/transaction_protocol_state/dune, src/lib/transaction_snark/dune, src/lib/transaction_snark_work/dune, src/lib/transition_frontier/dune, src/lib/unsigned_extended/dune, src/nonconsensus/coda_base/dune, src/nonconsensus/currency/dune, src/nonconsensus/signature_lib/dune, src/nonconsensus/snark_params/dune, src/nonconsensus/snark_params/snark_params_nonconsensus.ml, src/nonconsensus/unsigned_extended/dune
Remove most of the remaining errors-as-warnings flag to `ppx_coda` in dune files.
Fix some warnings.
=> Remove most lint warnings flags

src/lib/coda_lib/coda_lib.ml, src/lib/coda_networking/coda_networking.ml, src/lib/coda_networking/coda_networking.mli, src/lib/coda_transition/external_transition.ml, src/lib/coda_transition/external_transition_intf.ml
we basically _never_ care about a protocol state independent of its hash.
this will do some extra hashing, hopefully that's not too expensive? :\
=> include a state_hash in broadcast log

src/lib/coda_base/account.ml, src/lib/coda_base/user_command_payload.ml, src/lib/pickles_types/dlog_marlin_types.ml, src/lib/pickles_types/dune, src/lib/pickles_types/hlist.ml, src/lib/pickles_types/nat.ml, src/lib/pickles_types/pairing_marlin_types.ml, src/lib/pickles_types/pcs_batch.ml, src/lib/pickles_types/vector.ml
Removed a couple of `[@@warning "-27"]` from the code, which had no effect.
Removed that flag from a `dune` file, because that masks potential errors in the entire library. Changed a variable name for the one unused variable case.
Update: there were a number of other unused variables and opens that showed up in the unit tests, fixed.
=> Remove some 27 errors-as-warnings

frontend/leaderboard/src/Challenges.re, frontend/leaderboard/src/Types.re
This PR adds three new functions to collect metrics for the leaderboard: 
1) Snark Fees collected by each user 
2) Highest snark fee awarded to each user 
3) Transactions received by each user 
I edited some of the types and added some comments to break up reading the Challenges file.
=> Add functions to collect 3 more metrics for leaderboard

src/lib/ppx_coda/lint_version_syntax.ml, src/lib/transition_frontier/persistent_frontier/database.ml, src/lib/verifier/prod.ml
Types may appear in OCaml extensions. Versioned types should not appear in them.
There were several instances like:
```ocaml
[%bin_type_class: Foo.Stable.V1.t]
```
We should use `Foo.Stable.Latest.t` in such instances.
The linter now flags these, and all violations were fixed.
=> Lint versioned types in extension expressions

src/lib/pickles_types/pairing_marlin_types.ml
In `Pickles_types.Pairing_marlin_types`, there were several instances of `include Stable.Latest`. That has the effect of making unversioned types serializable.
(The linter used to catch these, will look again into re-instating that.)
Fixed these instances; removed some unneeded `deriving` items.
=> Pickles_types, don't include Stable.Latest

src/lib/pickles_types/abc.ml, src/lib/pickles_types/dlog_marlin_types.ml, src/lib/pickles_types/matrix_evals.ml, src/lib/pickles_types/pairing_marlin_types.ml, src/lib/pickles_types/scalar_challenge.ml
Fix more uses of `include Stable.Latest` in `Pickles_types`.
See #4891 for justification.
=> Pickles_types, fix more Stable.Latest

frontend/points-hack-april20/lib.js, graphql_schema.json, src/lib/auxiliary_database/filtered_external_transition.ml, src/lib/coda_graphql/coda_graphql.ml
The main goal of this is to add coinbaseReceiverAccount, which is necessary for calculating some leaderboard metrics.
Included in PR:
- Adds coinbaseReceiverAccount, representing who the coinbase for that block went to
- Adds the coinbase fee transfer to the list of fee transfers (cc @deepthiskumar can you let me know if you think this is right/wrong? I just noticed it wasn't being exposed at all)
- Regenerates the graphql schema, looks like several things have been removed since it's been generated last.
- Expose create_hd_account since otherwise the cli doesn't build
Verified using GraphiQL that the new field was added to the schema, will test to see that the value looks sane with the sandbox container when that builds.
Potentially breaking change -- this changes the shape of the data …
=> GraphQL: Add more detail to the coinbase transaction

src/lib/group_map/bw19.ml, src/lib/group_map/group_map.ml, src/lib/group_map/group_map.mli, src/lib/ppx_coda/lint_version_syntax.ml, src/lib/transition_frontier/frontier_base/diff.ml
Some time ago, I'd removed the linter code to detect `include Stable.Latest`, because I'd found instances where I didn't see a better way.
I'm reviving that check, and I've fixed all instances detected on build. The new Snarky backend has instances detected on unit tests, to be fixed later.
=> Lint include Stable.Latest

frontend/leaderboard/src/Challenges.re, frontend/leaderboard/src/Main.re, frontend/leaderboard/src/Metrics.re, frontend/leaderboard/src/Types.re
Implemented functionality for calculating points of users that have completed _atleast n_ of a metric. (example: Producing at least 3 blocks will earn an additional 1000 pts)
Also included a slight refactor of calculating all metrics.
The usage of _addPointsToUsersWithAtleastN_ is:
`let blockCreatedPoints =
addPointsToUsersWithAtleastN(
(metricRecord) => metricRecord.blocksCreated,
10,
1000,
map
);`
**Testing methods:**
To test the output of calculating metrics and challenges, manual testing was done. Block data was pulled in from an S3 bucket and was slightly modified to add additional properties to the blocks. Once the data was mocked, the script is executed and logged output throughout multiple points of the program. 
The output of `calculateMetrics` is a binding of users in the form …
=> Added atleast n functionality and slight refactor

dockerfiles/Dockerfile-coda-demo, scripts/run-demo.sh
Missed the demo image for the new config file format.
NOTE: Not making this PR from my personal fork, because the job doesn't run there, which is how this was missed.
Checklist:
=> Fix dockerfile path

.circleci/config.yml, .circleci/config.yml.jinja
Genesis ledger/proof may now have come from S3, look in the S3 cache dir for them.
Note that the S3 cache dir has `/tmp` hardcoded as a prefix, but the autogen dir uses `$TMPDIR`. This matches the behaviour of `src/lib/cache_dir/cach_dir.ml`. We should probably change it, but not in this PR.
Checklist:
=> Fix mac build

scripts/publish-deb.sh
This fixes a race condition where the CI jobs for 2 branches may both try to modify the `packages.o1test.net` repo, and the packages for one of the jobs are therefore not added to the deb manifests.
See for example [this failed `build-artifacts` run](https://app.circleci.com/pipelines/github/CodaProtocol/coda/21091/workflows/beaa43ba-da8e-44c5-b3c0-ea6879a13dc2/jobs/397357/steps), where the docker file could not find the `.deb` file because the deb manifests were clobbered another simultaneous job.
Checklist:
=> Use deb-s3 --lock to ensure that parallel CI jobs do not race

frontend/points-hack-april20/lib.js
The filenames are too long to actually download, so we need to truncate the hash.
Tested the truncate function though I haven't run the full script
=> Points: Truncate the state hash in the block name

.circleci/config.yml, .circleci/config.yml.jinja
build-artifacts was failing for frontend changes and it's a required CI check.
Example: https://app.circleci.com/pipelines/github/CodaProtocol/coda/21239/workflows/585a87ef-e92a-4ed7-8962-39bf8bf8125a/jobs/399754/steps
This adds the check for frontend-only changes to the genesis upload step.
=> Skip genesis-upload if frontend/rfc

src/lib/logging_events/event_declarations.ml, src/lib/ppx_register_event/register_event.ml
When `deriving register_event`, the location calculation failed when there was an additional attribute besides the `deriving`.
Added an additional `warning` attribute in one of the example event declarations.
=> Handle > 1 attribute when deriving register_event

scripts/upload-genesis.sh
This ports the fix from d76165f in PR #4949 to `develop`. It's not currently needed because of a quirk of the build system, but better safe than sorry.
Checklist:
=> Never fail if generated genesis isn't found

frontend/leaderboard/src/Metrics.re, frontend/leaderboard/src/Types.re
This adds a function that will process all blocks and return a mapping between public keys and whether or not they completed the coinbase receiver challenge by sending a coinbase to a different address.
=> Leaderboard: add coinbase receiver metric 

src/lib/runtime_config/runtime_config.ml
In `Runtime_config`,the field names to be retained via a `filter` operation differed from the actual fields in the record type.
=> Runtime_config, fix typos in field names

.circleci/config.yml, .circleci/config.yml.jinja, frontend/leaderboard/__tests__/blocks/block1.json, frontend/leaderboard/__tests__/blocks/block10.json, frontend/leaderboard/__tests__/blocks/block2.json, frontend/leaderboard/__tests__/blocks/block3.json, frontend/leaderboard/__tests__/blocks/block4.json, frontend/leaderboard/__tests__/blocks/block5.json, frontend/leaderboard/__tests__/blocks/block6.json, frontend/leaderboard/__tests__/blocks/block7.json, frontend/leaderboard/__tests__/blocks/block8.json, frontend/leaderboard/__tests__/blocks/block9.json, frontend/leaderboard/__tests__/leaderboard_test.re, frontend/leaderboard/bsconfig.json, frontend/leaderboard/package.json, frontend/leaderboard/src/Challenges.re
Resurrected from https://github.com/CodaProtocol/coda/pull/4965 by @MartinMinkov 
===
Added unit tests to the leaderboard project with bs-jest.
I found that as I was implementing the challenge requirements from the notion page, I was unsure if the implementation code was rewarded points correctly based on the massive block data that is pulled in. Writing these unit tests is a way to confirm that these challenges are being implemented correctly on the block data is given.
Not all metrics/challenges are included in this PR. This is because I was implementing the specified challenges in a different git branch and wanted the tests to be a separate PR. As more functionality to metrics/challenges is written, we can now write tests.
Note: This PR also includes a small bug fix that was found by …
=> Adds unit tests to leaderboard

src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml
In CI, building `runtime_genesis_ledger.exe` generated an unused variable warning.
Locally, using the `dev` profile, it's a fatal error.
=> Runtime_genesis_ledger, rm unused var

src/lib/coda_base/transaction_union_tag.ml
This PR adds an extra bit to transaction union tag, so that we have space to add more commands.
Checklist:
=> Increase size of transaction union tag

frontend/website/pages/docs/contributing.mdx
Small link fix for CoC. There's no separate doc for the reporting guidelines so I just referred to the section in the document. A better fix might be promoting the coc to its own full page in the docs and then linking to the header but this was faster for now.
=> Website: Fix links to CoC

src/lib/merkle_mask/masking_merkle_tree.ml
`iteri` appears in the base ledger interface, but it wasn't implemented for Merkle masks. The stub that was there was being called in the nightly medium curves unit tests, resulting in failure.
There are some possible `failwith`s called, which shouldn't happen if the mask and ancestors have consistent tables/databases.
Closes #5099.
=> Implement iteri for masks

.mergify.yml, .mergify.yml.jinja
This PR adds support for the `ready-to-merge-into-develop` label to mergify.
This is designed to handle the case of 'PR chains', where we have a pull request from branch `b2` with base `b1` and a pull request from branch `b1` with base `b0`. For example, see the chain #5086 #5088 #5089 #5090 #5091.
Adding the existing `ready-to-merge` label would fold the PRs through eachother down into the root PR (potentially racing on CI, so the order of merges isn't deterministic), so for example all of the above PRs would be combined into #5086, which would then be merged into `develop`.
By using the new `ready-to-merge-into-develop` label, the PR with base `develop` will get merged and have its branch deleted, then the base of the next PR will be reset to `develop` and that will get merged, etc. …
=> Add ready-to-merge-into-develop to mergify

.circleci/config.yml, .circleci/config.yml.jinja
This PR moves docker builds out of the `build-artifacts` CI job into their own jobs. This
* allows the docker builds to run in parallel, speeding up CI
* the docker jobs are not required, so PRs that will not use the images may merge before the step is completed
* avoids CI failure for a PR when parallel PRs' CI jobs race to access the same dockerhub tag
* makes re-running a failed docker build much faster, since it doesn't require a whole re-run of `build-artifacts`
Checklist:
=> Move docker jobs out of build-artifacts CI jobs

src/lib/ppx_register_event/dune, src/lib/ppx_register_event/register_event.ml
We had had troubles mixing `Ppx_deriving` and `Ppxlib.Deriving`, and had changed most derivers to use the latter.
Change `ppx_register_event` to use `Ppxlib.Deriving`.
=> Ppxlib.Deriving for register_event

src/lib/ledger_catchup/ledger_catchup.ml
Validate the protocol versions in catchup blocks in `Ledger_catchup`. On validation failures, log the failure with details.
Closes #5113.
=> Validate protocol versions in catchup

.circleci/config.yml, .circleci/config.yml.jinja
Nix now uses a cross-domain 301 redirect for their install script. Allow it.
Checklist:
=> Fix mac builds on CI

.circleci/config.yml, .circleci/config.yml.jinja
This PR:
Fixes an issue made with cron job for the leaderboard. 
The error reported by circleci is as the following:
=> fixed leaderboard cron job error

src/lib/coda_networking/coda_networking.ml
The older version of `ppx_deriving_yojson` didn't permit per-field `to_yojson` specifications, so an RPC type was forced to write out the entire `to_yojson` spec, instead of deriving it.
We now have a modern version of the deriver, so we just need to write out specs for a few fields.
=> to_yojson per-field annotations for RPC type

buildkite/src/Command/Coda.dhall
We can't run docker in docker in docker! Coda/Command is already in Docker-in-Docker so we shouldn't wrap fix-permissions again.
=> fix command in a Coda/Command is already in docker

buildkite/src/Command/Base.dhall, buildkite/src/Jobs/Sample2.dhall
Since `key` must be globally unique in a composite running buildkite instance, but we're dynamically stitching together different pipelines, I thought it wise to compose the true `key` with the `name` from the spec of a pipeline when it is actually assembled together into yaml.
Since this is opaque from people actually building jobs, it's easy to not know or forget about this behavior and get blocked on steps not running in a pipeline.
To help mitigate this, I changed `depends_on` to take a `TaggedKey`, a key and a name. Now the compiler will help you remember to pass the spec name in. I also included a sample job with a dependency by changing Sample2 (and it works)
=> Buildkite CI: Better depends_on

src/lib/ppx_register_event/dune, src/lib/ppx_register_event/register_event.ml
The event ids for registered events have been SHA-1 hashes containing arbitrary bytes. When examining a log, those hashes print out as unpleasant garbage. If the bytes happen to be control terminal control characters, reading a log can mess up your terminal.
This PR changes the event ids from SHA-1 hashes to MD5 digests converted to ASCII hex strings.
=> Readable event ids

buildkite/scripts/lint-check-format.sh, buildkite/src/Jobs/Lint/OCaml.dhall
Regression caused from the update to the base toolchain container which no longer has any correct opam deps in it.
We need opam init on this step too (this is also reflected on circle)
=> Fixes ocaml lint step

src/app/cli/src/coda.ml, src/app/cli/src/dune, src/lib/ppx_register_event/register_event.ml
Sample output:
```bash
$ _build/default/src/app/cli/src/coda.exe internal dump-structured-events -pretty
```
```json
[
[
"src/lib/coda_lib/coda_lib.ml.Rebroadcast_transition",
"e81a9e94463d8fe61fa3f2ed4f5bfc6a",
[ "state_hash" ]
],
[
"src/lib/coda_lib/coda_lib.ml.Synced",
"34413e73c270eec4ce05ab1c93f6de94", []
],
[
"src/lib/coda_lib/coda_lib.ml.Ledger_catchup",
"501599549a087a4ccd013187a461c363", []
],
[
"src/lib/coda_lib/coda_lib.ml.Bootstrapping",
"e4389364f4c98c689c6556faf4a7ae93", []
],
[
"src/lib/coda_lib/coda_lib.ml.Listening",
"be2b8f8a44380187992bd246e24bede0", []
],
[
"src/lib/coda_lib/coda_lib.ml.Connecting",
"aa6017b1c3e4fd28f14e86e60750c72a", []
],
[
"src/lib/snark_worker/functor.ml.Base_snark_generated",
"885328f9dca84fa1cfb99089080613d6",
[ "time" ]
],
[ …
```
=> Add `coda.exe internal dump-structured-events` command

Makefile, src/app/benchmarks/main.ml
Removed `snark_params` from list of benchmarked libraries. Fix `Makefile` so that `make benchmarks` works.
=> Update benchmark build

buildkite/src/Command/Base.dhall, buildkite/src/Command/Coda.dhall, buildkite/src/Command/Summon/Type.dhall
This change adds a Summon dhall type to represent configuration for Buildkite's Summon secrets management plugin.
**Checklist:**
Closes #4993
=> add Summon Command Type for Buildkite Summon secrets management plugin integration

src/lib/genesis_ledger_helper/genesis_ledger_helper.ml, src/lib/runtime_config/runtime_config.ml
This PR
* removes the existing ledger symlink before attempting to create a new one
- this avoids an error where linking would fail if the file existed
* adds support for naming ledgers via the config file
- now `name` may be used to set as well as retrieve ledgers
- non-built-in names are supported: `"ledger": {"name": "my-release", "accounts": {...}}` can be retrieved with just `"ledger": {"name": "my-release"}` after the first run
* adds the genesis directory to the list of search paths for ledgers
- this is probably the root-cause of the error @yourbuddyconner's was seeing, where the ledger existed in the genesis directory but wasn't being found.
Checklist:
=> Fix error where genesis ledger 'named' file already exists

src/lib/snark_worker/functor.ml
This PR makes the `-proof-level` flag optional, defaulting to the compiled proof level.
Checklist:
=> Optional -proof-level flag for snark worker

src/lib/network_pool/indexed_pool.ml, src/lib/network_pool/indexed_pool.mli, src/lib/network_pool/intf.ml, src/lib/network_pool/network_pool_base.ml, src/lib/network_pool/snark_pool.ml, src/lib/network_pool/snark_pool_diff.ml, src/lib/network_pool/transaction_pool.ml
This PR simplifies the transaction pool in preparation of the token commands. It
* removes the checks on source accounts
- these are inherently racy, since they aren't tied to the fee-paying account
- instead, the transaction logic (and transaction snark) enforce that fees are still charged but the transaction is not applied if it is invalid
* removes the checks on receiver accounts
- these are also checked in the snark/txn logic, charing the fee on both failure and success
- the `Create_token_account` command may result in later commands from a sender being valid even though the account doesn't yet exist
* stored the `constraints_constants` in the indexed pool
- token creation and token account creation are charged to the fee payer, so we need access to the account creation fee there to …
=> [Tokens] Simplify transaction pool

src/app/cli/src/init/transaction_snark_profiler.ml, src/lib/block_producer/block_producer.ml, src/lib/blockchain_snark/blockchain_snark_state.ml, src/lib/coda_base/account.ml, src/lib/coda_base/pending_coinbase.ml, src/lib/coda_base/sparse_ledger.ml, src/lib/coda_base/sparse_ledger.mli, src/lib/coda_base/transaction_union.ml, src/lib/coda_base/transaction_union_payload.ml, src/lib/coda_state/blockchain_state.ml, src/lib/coda_state/blockchain_state.mli, src/lib/coda_state/genesis_protocol_state.ml, src/lib/coda_state/protocol_state.ml, src/lib/coda_state/snark_transition.ml, src/lib/consensus/intf.ml, src/lib/ledger_proof/ledger_proof.ml, src/lib/merkle_mask/masking_merkle_tree.ml, src/lib/snark_worker/prod.ml, src/lib/sparse_ledger_lib/sparse_ledger.ml, src/lib/staged_ledger/staged_ledger.ml, src/lib/staged_ledger/staged_ledger.mli, src/lib/transaction_snark/transaction_snark.ml, src/lib/transaction_snark/transaction_snark.mli, src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml, src/lib/transaction_snark_scan_state/transaction_snark_scan_state.mli, src/lib/transition_frontier/frontier_base/breadcrumb.ml, src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
This PR
* adds support for `next_available_token` to `Sparse_ledger.t`
* adds `next_available_token_before` and `next_available_token_after` to `Transaction_snark.Statement.t`
* adds `next_available_token` to `Blockchain_state.t`
* routes the `next_available_token` data through the system as needed.
Checklist:
=> Expose next_available_token in Blockchain_state.t, route it through to transaction snark

.bazelrc, .gitignore, BUILD.bazel, WORKSPACE
Signed-off-by: Gregg Reynolds <601396+mobileink@users.noreply.github.com>
yet.
This is the initial commit for Bazel support. I'm breaking it into small pieces, lots more on the way. It will take several days at least to add all changes.
The changes needed to support Bazel will not interfere with the current build system. so they can be ignored by those without the time for or interest in testing the Bazel code.  The rare exception is when something needs to be changed in order to conform to Bazel's rules; for example, use of ".." in an include path can cause trouble.  In such cases the changes should be very small and simple, and will be submitted as a separate PR.
There are places where Bazel suggests some …
=> bazel support: initial minimal commit

src/lib/coda_base/new_account_payload.ml, src/lib/coda_base/new_token_payload.ml, src/lib/coda_base/sparse_ledger.ml, src/lib/coda_base/transaction_logic.ml, src/lib/coda_base/transaction_union.ml, src/lib/coda_base/transaction_union_payload.ml, src/lib/coda_base/user_command.ml, src/lib/coda_base/user_command_payload.ml, src/lib/transaction_snark/transaction_snark.ml
This PR augments the `Create_token_account` and `Create_new_token` with booleans for disabling or enabling token accounts. 
```ocaml
Create_token_account
{ token_owner_pk
; token_id
; receiver_pk
; account_disabled (* Newly added in this PR *) }
Create_new_token
{ token_owner_pk
; disable_new_accounts (* Newly added in this PR *) }
```
Disabling an account currently has no effect. An upcoming PR will add commands to toggle this state (by token owners) and disable all other commands running against that account.
The `Create_token_account` will succeed iff
* `account_disabled` matches the `disable_new_accounts` field in the token owner's token permissions field; or
* the fee payer (ie. issuer/signer) was the token owner.
Checklist:
=> Add token permissions to token and account creation functions

frontend/website/src/pages/MemberProfilePage.re
This adds a footer to the member profile page. We should think about a more aligned way to do fonts, i think the design library on figma and the code have been mixed up for a while now.. perhaps we can realign on what we define as H1, H2, H3, H4, H5, H6, in the code
=> Add footer to member profile page 

src/lib/coda_transition/internal_transition.ml, src/lib/consensus/intf.ml, src/lib/consensus/stake_proof.ml, src/lib/prover/prover.ml, src/lib/signature_lib/private_key.ml
This PR switches from encoding private keys using the raw `Inner_curve.Scalar.to_string` to `base58_check`.
Checklist:
=> Use base58-check encoding for private keys (s-expressions and json)

src/config/testnet_postake_medium_curves.mlh
This PR sets `time_offsets=true` in the `testnet_postake_medium_curves` compile-time config file.
The `coda-demo` docker image needs to set a time offset to avoid generating a new genesis proof each startup. Without this enabled, it fails at the first block with an 'empty epoch' error (previously an equivalent constraint failure in the block producer pre-#5329).
Checklist:
=> Fix coda-demo docker image

src/lib/coda_graphql/coda_graphql.ml, src/lib/network_pool/indexed_pool.ml, src/lib/network_pool/indexed_pool.mli, src/lib/network_pool/intf.ml, src/lib/network_pool/transaction_pool.ml
Previously, this used the `transactions` command, which runs the pool
checks and reconstructs a pool after removing each command. We don't
want to do this, for (currently) up to 3000 commands, on each txnpool
GraphQL query
Checklist:
=> Expose all transactions directly from the pool for GraphQL

src/app/cli/src/init/client.ml
This PR changes the `compile-time-constants` command so that
* use a default value if `load_json_config` doesn't find a file
* use the default runtime config if it cannot parse the json config file
* disables the logging for initialisation
- this is unfortunate, but apprently we log to stdout, and so we clobber any actual output
Checklist:
=> Make compile-time-constants fail less, disable logging

src/lib/transition_router/initial_validator.ml
We don't appear to log the reason for validation failures anywhere, which makes debugging forks etc. harder. This PR adds log messages for those validation failures.
Checklist:
=> Add logging for validation errors

WORKSPACE
In preparation for when bazel support for the externals is merged
upstream and pulled into the submodules.
When the time comes to remove the git submodules from the source tree, all we will need to do is change these local_repository rules to http_archive rules.
Signed-off-by: Gregg Reynolds <601396+mobileink@users.noreply.github.com>
=> WORKSPACE: add local_repository for each submodule in src/external

.circleci/config.yml, .circleci/config.yml.jinja, scripts/compare_ci_diff_binables.sh, scripts/compare_ci_diff_types.sh, scripts/compare_pr_diff_binables.py, scripts/compare_pr_diff_items.py, scripts/compare_pr_diff_types.py
This should circumvent the error we were seeing [here](https://app.circleci.com/pipelines/github/CodaProtocol/coda/23847/workflows/ba15bfa1-1e1a-4d39-b76f-8e669a3a6a6e/jobs/454163/parallel-runs/0/steps/0-109).
Checklist:
=> Use CircleCIs pipeline.git.base_revision instead of a JSON query

src/lib/ppx_coda/dune, src/lib/ppx_coda/ppx_representatives/dune, src/lib/ppx_coda/ppx_representatives/ppx_representatives.ml, src/lib/ppx_coda/ppx_representatives/runtime/dune, src/lib/ppx_coda/ppx_representatives/runtime/ppx_representatives_runtime.ml, src/ppx_representatives.opam
This PR adds the ppx `[@@deriving to_representatives]`, which computes a list of the representative values for a type. The built-in types use dummy values (e.g. `string` uses `""`, `bool` uses `false`), but the various forms of user-generated types are exposed in full. The list of representatives is held lazily in a value named after the type, `val to_representatives : t list Lazy.t` for a type `t`, or `val type_name_to_representatives : t list Lazy.t` for a type `type_name`.
@bkase requested this to expose the different cases that should be handled for the rosetta API.
This is implemented recursively, so user-defined types that refer to other user-defined types will also receive their expansions inline. For example,
```ocaml
$ dune utop src/lib/ppx_coda/ppx_representatives/ …
```
=> Add ppx_representatives

src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
This is a sanity check log, so that we can make sure we're starting all nodes with the right runtime config.
Checklist:
=> [Trivial] Log the runtime configuration on startup

src/app/rosetta/dune, src/app/rosetta/lib/dune, src/app/rosetta/lib/errors.ml
* Endpoints support `https` (in theory)
* On macOS I get `LibreSSL SSL_connect: SSL_ERROR_SYSCALL` at
runtime but I suspect that it will work on linux
* Use `to_enum` for errors' `code` function
* Use `to_representatives` for getting all variants (not hooked up yet)
=> Uses new goodies that @mrmr1993 has created

src/app/rosetta/lib/account.ml, src/app/rosetta/lib/errors.ml, src/app/rosetta/lib/network.ml, src/app/rosetta/lib/rosetta.ml, src/app/rosetta/lib/test.ml
All branches for application-level handlers in network are tested.
I also pushed validate_network test to a separate area.
`dune runtest lib/` passes.
=> Completes test coverage on network endpoints

frontend/website/src/components/Leaderboard.re, frontend/website/src/pages/MemberProfilePage.re
This PR includes the following functionality:
1. It makes the leaderboard user participant search case insensitive.
2. Orders the challenge points tables in /memberProfile to be ordered by the proper releases. 
This solves the following issues:
https://github.com/CodaProtocol/coda/issues/5341
https://github.com/CodaProtocol/coda/issues/5343
This was all tested manually.
=> Leaderboard - Case Insensitive Search and In-Order Member Profile Tables

src/app/cli/src/coda.ml, src/lib/block_producer/block_producer.ml
1. Drain `validated_transitions` pipe that is no longer used by daemon (only used in integration tests)
2. correct `Block_produced` metadata
Checklist:
=> fix for qa-net forking

src/lib/coda_lib/coda_lib.ml
This is confusing when analyzing logs for rebroadcast blocks
=> skip reboradcast log for internally generated blocks

frontend/website/src/components/ChallengePointsTable.re, frontend/website/src/components/Leaderboard.re, frontend/website/src/components/ProfileHero.re
This PR addresses the following issues caught in the latest Leaderboard QA:
https://github.com/CodaProtocol/coda/issues/5426 (not included)
https://github.com/CodaProtocol/coda/issues/5427
https://github.com/CodaProtocol/coda/issues/5437
https://github.com/CodaProtocol/coda/issues/5436
Desktop Member Profile - Badge Alignment:
Mobile Member Profile - Badge Alignment:
Desktop - Member Profile Challenge Table - Points Alignment:
Mobile Member Profile Challenge Table - Points Alignment:
Desktop - Leaderboard Row - Badge Alignment
Mobile - Leaderboard Row - Badge Alignment:
=> Website Leaderboard - Style fixes and added last manually updated to sheets and frontend

src/app/archive/dune, src/lib/blake2/blake2.ml, src/lib/blake2/dune, src/lib/coda_base/data_hash.ml, src/lib/coda_base/dune, src/lib/coda_base/proof.ml, src/lib/coda_base/signature.ml, src/lib/genesis_constants/dune, src/lib/genesis_constants/genesis_constants.ml, src/lib/merkle_address/dune, src/lib/merkle_address/merkle_address.ml, src/lib/non_zero_curve_point/dune, src/lib/non_zero_curve_point/non_zero_curve_point.ml, src/lib/signature_lib/dune, src/lib/signature_lib/private_key.ml, src/lib/transaction_snark/dune, src/lib/transaction_snark/transaction_snark.ml, src/lib/trust_system/banned_status.ml, src/lib/trust_system/dune, src/lib/unsigned_extended/dune, src/lib/unsigned_extended/unsigned_extended.ml
Bump `ppx_version` to use separate runtime library. Use that runtime library in Coda.
=> Separate runtime lib, ppx_version

src/app/cli/src/tests/coda_peers_test.ml, src/app/cli/src/tests/coda_receipt_chain_test.ml, src/app/cli/src/tests/coda_transitive_peers_test.ml, src/app/cli/src/tests/coda_worker_testnet.ml, src/lib/genesis_ledger_helper/genesis_ledger_helper.ml, src/lib/genesis_proof/dune, src/lib/genesis_proof/genesis_proof.ml, src/lib/precomputed_values/gen_values/gen_values.ml
This PR
* carries the runtime config in `Precomputed_values.t`
* uses the given runtime config when spawning child processes instead of inferring one from the precomputed values
This removes some spurious warnings about setting constraint constants from the inferred config, and makes the initialisation from these configs more efficient. This will also make it far easier to output the config to the GraphQL API.
Checklist:
=> Use the given runtime config instead of inferring one

frontend/leaderboard/src/Challenges.re, frontend/leaderboard/src/Sheets.re, frontend/leaderboard/src/UploadLeaderboardPoints.re, frontend/website/src/components/ChallengePointsTable.re, frontend/website/src/pages/MemberProfilePage.re
This PR implements the following:
1. An update to the ranges used by the Google Sheets API to reflect the changes made on the actual Google Sheets. We have removed the "Challenge #" from the Challenge titles and instead added a row above the challenge titles that contain the number. See the image below:
2. Small fix to the Challenge Points Table with the alignment of the points. Large numbers were being spaced out by the padding, so padding was reduced. 
Manual Testing was done to verify the correct behavior.
Closes https://github.com/CodaProtocol/coda/issues/5453
Closes https://github.com/CodaProtocol/coda/issues/5383
=> Leaderboard Website - Remove Challenge #s

frontend/website/public/static/img/LeaderboardAwardCommunityMVP.png
This PR:
Changes the Community Badge Icon. 
NEW:
=> changed community badge icon

buildkite/src/Lib/Cmds.dhall
Automatically mount `/var/buildkite/shared` to `/shared` DIR within containers for dedicated volume-share DIR between Buildkite agent & dind containers (note: operations within containers should write to `/shared` DIR for sharing with agent at `/var/buildkite/shared`).
Checklist:
=> Auto add agent-dind pod shared volume DIR within job containers

frontend/website/src/components/ChallengePointsTable.re
Adds the correct amount of padding to the "Points *" column header in the Member Profile Page.
Closes https://github.com/CodaProtocol/coda/issues/5486
=> Website - points right align fix

.circleci/config.yml, .circleci/config.yml.jinja, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, frontend/ci-build-me/README.md, frontend/ci-build-me/src/index.js
In an effort to curb CI spending, we wish to change circle builds to opt-in.
You must either:
a) Add the `ci-build-me` label to your PR (this only works if you are PRing _not_ from a fork for security reasons). A build will trigger the moment you add the label and every time commits are pushed to that branch.
b) Add the comment `!ci-build-me` to your PR. This will trigger one and only one build at that moment.
Tested in production (I temporarily deployed with these changes, tested, and have subsequently reverted to the bot @ develop until this PR is ready to land)
=> Circle ci build me

src/lib/runtime_config/runtime_config.ml
The implementation is not ideal -- it will dump the JSON that failed *and* every enclosing JSON record -- but this error is fatal anyway.
Checklist:
=> Dump the JSON that failed to parse in the runtime config

CODEOWNERS
This shouldn't be owned by crypto. I wrote these originally, @emberian reviewed.
Checklist:
=> Integer_js_stubs owned by protocol

src/lib/pickles/cache.ml, src/lib/pickles/pickles.mli, src/lib/pickles_types/matrix_evals.ml, src/lib/zexe_backend/bn382/dlog_based.ml, src/lib/zexe_backend/bn382/pairing_based.ml, src/lib/zexe_backend/tweedle/dee_based.ml, src/lib/zexe_backend/tweedle/dum_based.ml, src/lib/zexe_backend/zexe_backend_common/dlog_based_keypair.ml, src/lib/zexe_backend/zexe_backend_common/r1cs_constraint_system.ml
This PR
- fixes a few major memory leaks in the new snark
- fixes how "verification ids" were checked for equality
=> Fix major memory leaks in pickles

frontend/website/src/components/Dropdown.re, frontend/website/src/pages/MemberProfilePage.re
This PR includes:
1. A fix to the dropdown menu in the tablet view of the leaderboard.
2. A fix to the order of the releases on the member profile page. They were released as oldest to newest but the order has now switched to newest to oldest releases.
Closes https://github.com/CodaProtocol/coda/issues/5511
=> Website - Leaderboard QA fixes with Dropdown and Release Ordering

buildkite/src/Jobs/UnitTest.dhall, buildkite/src/Jobs/UnitTest.override
**To avoid the relatively long runtimes of unit tests while sufficient infrastructure resources (for increasing Buildkite agent performance) are being evaluated for such compute-heavy jobs, this change disables `UnitTest` jobs for all changes unless an explicit `*.override` file is created.**
**Testing:**
- ensure unit-tests jobs are NOT triggered in absence of *override* (+ change to test file) | [example](https://buildkite.com/o-1-labs-2/coda/builds/655)
- unit-tests jobs are triggered in presence of *override* (+ change to test file) | [example](https://buildkite.com/o-1-labs-2/coda/builds/657)
**Checklist:**
- Mention expected invariants, …
=> rename buildkite unit-test job (Unit -> UnitTest) and disable with capability to override

src/lib/coda_graphql/coda_graphql.ml, src/lib/coda_graphql/dune, src/lib/consensus/proof_of_stake.ml
One level of protection against someone falling into the same trap as I
did (thinking block production was broken)
Tested by disabling via the GraphQL API and observing the better logging behavior, and made sure production still works when it's enabled.
=> Sane logging when no keys are on

buildkite/src/Command/Libp2pHelperBuild.dhall
**Overview:** Update src/app/libp2p_helper ownership in order to provide containerized `make libp2p_helper` operation proper FS access. 
**Testing:** [Buildkite CI](https://buildkite.com/o-1-labs-2/coda/builds/765#_) 
**Checklist:**
=> chown src/app/libp2p_helper DIR to nobody for proper `make libp2p_helper permissions

src/lib/base58_check/dune, src/lib/consensus/dune, src/lib/merkle_mask/dune, src/lib/snark_worker/dune, src/lib/trust_system/dune, src/lib/vrf_lib/dune
This PR alphabetises and deduplicates ppx entries in dune files; thanks to @mobileink for the list.
Checklist:
=> [Trivial] Deduplicate ppx entries in dune files

buildkite/scripts/compare_test_signatures.sh, buildkite/src/Command/OpamInit.dhall, buildkite/src/Jobs/CompareSignatures.dhall
Attempts to fix compare test signatures. I noticed the failure was occurring because the eval wasn't escaped enough.
Compare test sigs test passes now.
=> Fixes compare test signatures job

buildkite/scripts/docker-artifact.sh
Fast-fail docker-artifact.sh on embedded command failures in addition to unset expected EnvVars (expectation is that all environment variables should be set by DOCKER_DEPLOY_ENV).
Checklist:
=> ensure docker-artifact build/release script shares pass/fail fate of embedded commands

buildkite/scripts/build-artifact.sh
Build-artifacts job was erroneously succeeding even though it was actually failing. This is due to a missing `set -e` at the top of the build-artifacts.sh script. There is also an export PATH after the opam eval that should fix the missing cargo binary error.
=> Fail faster + cargo properly on build-artifacts

frontend/website/public/static/img/LeaderboardEmpty.png, frontend/website/src/components/Leaderboard.re, frontend/website/src/pages/LeaderboardPage.re
This PR implements the following functionality:
- Adds an error message when the leaderboard has empty members to show. This error message is present for sorting both by `Release` and `Phase`. 
- Changes the default sort method to be `Phase` instead of `Release`
Closes https://github.com/CodaProtocol/coda/issues/5629
These changes were tested manually. See below for mocks of changes.
**Desktop - Empty Release**
**Mobile - Empty Release**
**Desktop - Empty Phase**
**Desktop - Empty All-Time**
=> [Website] Added empty message for leaderboard

rfcs/0038-rosetta-construction-api.md
In the Random_oracle_input as described by the existing RFC, there is an ambiguity between padding bits and true zero bits in the bitstring. This change aims to eliminate that ambiguity.
=> Fix ambiguity in serialization of Random_oracle_input spec

scripts/compare_ci_diff_binables.sh, scripts/compare_ci_diff_types.sh
Appears as though Buildkite's job-environment scoped [$BUILDKITE_PULL_REQUEST_BASE_BRANCH](https://buildkite.com/docs/pipelines/environment-variables#bk-env-vars-buildkite-pull-request-base-branch) EnvVar is not properly set when builds are triggered against the base branch itself (`develop` in this case) see: [example](https://buildkite.com/o-1-labs-2/coda/builds/1254#e399c11d-cd66-4f3e-be76-ba9e1b349b5b). This change adds a default of `develop`, which should result in a no-op, if so.
**Checklist:**
=> add default value for BASE_BRANCH var within compare_ci_diff scripts

src/app/rosetta/lib/block.ml, src/app/rosetta/lib/user_command_info.ml
Running `start.sh` in `src/app/rosetta` builds several pieces of code. On Linux, those builds failed because `Unsigned.UInt{32,64}` don't export Yojson functions. Using `Unsigned_extended` instead allows the builds to succeed.
=> Rosetta, Unsigned_extended types for Yojson

buildkite/scripts/setup-database-for-archive-node.sh
Fix the following archive unit test failures in Buildkite CI by ensuring `apt` updates prior to the *postgres* package installation.
```
Err:9 http://security.debian.org/debian-security stretch/updates/main amd64 postgresql-client-9.6 amd64 9.6.17-0+deb9u1
--
  | 404  Not Found
  | Err:10 http://security.debian.org/debian-security stretch/updates/main amd64 postgresql-9.6 amd64 9.6.17-0+deb9u1
  | 404  Not Found
  | Get:11 http://deb.debian.org/debian stretch/main amd64 libwrap0 amd64 7.6.q-26 [58.2 kB]
  | Get:12 http://deb.debian.org/debian stretch/main amd64 locales all 2.24-11+deb9u4 [3289 kB]
  | Err:13 http://security.debian.org/debian-security stretch/updates/main amd64 postgresql-contrib-9.6 amd64 9.6.17-0+deb9u1
  | 404  Not Found
```
**Checklist:**
- …
=> add apt update to archive node CI postgres setup script

buildkite/src/Command/Base.dhall, buildkite/src/Jobs/Lint/Fast.dhall
Per #4991, add dhall bindings for Buildkite's command-step `skip` property. Technically, a combination of it, `soft_fail` and `retries` could serve as a basis for Buildkite's job requirement/flake management solution with the capability to develop further (e.g. add a soft-failure message property) in tandem w/ the BK community.
`skip` + `soft-fail` View in *Buildkite UI*:
View in *Github UI* (notice *skips* are NOT shown):
*Dhall* usage:
```
steps = [
Command.build
Command.Config::{
commands = commands
, ...
, soft_fail = Some (B/SoftFail.Boolean True)
, ...
},
Command.build
Command.Config::{
commands = commands
, ...
, soft_fail = Some (B/SoftFail.ListSoft_fail/Type [{ exit_status = Some (B/SoftFail/ExitStatus.Number 1) }])
, ...
},
Command.build
Command.Config::{
commands = commands
, …
```
=> add skip dhall Base Cmd config property

buildkite/src/Jobs/Lint/Fast.dhall, scripts/compare_ci_diff_binables.sh, scripts/compare_ci_diff_types.sh
Remove soft-fails and skips accidentally left within Fast Lint Buildkite jobs.
**Checklist:**
=> remove buildkite cmd soft-fail and skip examples from fast lint jobs

src/app/rosetta/test-agent/operation_expectation.ml, src/app/rosetta/test-agent/signer.ml
Run `test_eq` directly of signatures produced for Rosetta, rather than comparing their hex encodings.
Also removed an unused `open Lib`.
Tested by running `rosetta/start.sh` (verifying that this code was being compiled by introducing an intentional compilation error). Test ran successfully.
=> Simpler signature eq test

src/lib/rosetta_lib/errors.ml, src/lib/rosetta_lib/user_command_info.ml
Add delegation case to `of_operations` in `User_command_info`.
Added roundtrip unit test similar to the one for payments.
Added new error `Invalid_metadata`.
If `of_operations` receives an operations list that produces neither a payment nor a delegation, the error lists are appended.
=> Delegations case in of_operations

src/app/rosetta/test-agent/agent.ml, src/app/rosetta/test-agent/operation_expectation.ml, src/app/rosetta/test-agent/poke.ml, src/lib/rosetta_lib/transaction.ml, src/lib/rosetta_lib/user_command_info.ml
Test agent runs construction end-to-end with delegations and payments
=> Construction delegations in test agent

src/app/rosetta/lib/network.ml, src/app/rosetta/lib/rosetta.ml, src/app/rosetta/rosetta.conf, src/lib/rosetta_lib/errors.ml
* Version number bumped
* Server more robust to disconnecting clients
* Errors has consistent schema for languages lacking sum types
* Adds rosetta.conf
From the CodaProtocol/rosetta-cli fork:
`rosetta-cli --configuration-file rosetta.conf check:data`
deterministically fails after having made it through some initial validation
=> Nits in server config to get rosetta-cli started

src/app/rosetta/lib/block.ml, src/app/rosetta/lib/decoders.ml, src/app/rosetta/lib/network.ml
Test-agent still passes, and rosetta-cli can `view:block 1` successfully
now.
Fixes #5559
=> Serves genesis block from /block

src/app/cli/src/init/client.ml, src/app/cli/src/init/graphql_queries.ml
This is #5787 rebased onto the release branch. We want the `get-tokens` command for release so that users can access the token ID from the CLI when they create a new token.
> This PR
> * enables the token flag for receipt chain and nonce commands
> * adds the token flag to `get-balance`     
> * we only use the `coda` description for the default token (we use `coda+` in rosetta for other tokens, but it reads less well without capitalisation here)
> * adds the command `get-tokens`, to list all of the tokens associated with the give public key.
Checklist:
=> [Release branch] Tokens CLI changes

src/app/rosetta/lib/rosetta.ml
Adds connection pooling on caqti to fix rosetta-cli failures when grabbing blocks
=> Connection pooling to fix sql resource errors

src/app/rosetta/test-agent/agent.ml, src/app/rosetta/test-agent/poke.ml
Add a delegation via GraphQL and subsequent transaction pool check in `Agent.run`.
Other user commands to follow.
Part of #5817.
=> Add delegation to agent run

src/lib/coda_base/sparse_ledger.ml, src/lib/staged_ledger/staged_ledger.ml, src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml, src/lib/transaction_snark_scan_state/transaction_snark_scan_state.mli
1. delegate field to be empty for non-default tokens
2. pass correct `next_available_token` to the scan state `check_invariants` function
Checklist:
Closes #5724
=> hot fix for #5724

.circleci/config.yml, .circleci/config.yml.jinja
This PR updates the apt repos before installing postgresql. Without this, `apt-get` attempts to install the version it currently knows about, which is no longer available from the repo.
Checklist:
=> Fix archive node jobs

src/lib/bootstrap_controller/bootstrap_controller.mli, src/lib/coda_lib/coda_lib.mli, src/lib/coda_networking/coda_networking.ml, src/lib/coda_networking/coda_networking.mli, src/lib/ppx_register_event/register_event.ml, src/lib/trust_system/peer_trust.ml, src/lib/trust_system/peer_trust.mli
This PR
* adds a signature deriver for `ppx_structure_event`
* uses it to expose the structured events and their associated derived values where they were hidden by signatures.
Checklist:
=> Signature deriver for ppx_register_event

frontend/website-redesign/src/Theme.re, frontend/website-redesign/src/components/CookieWarning.re, frontend/website-redesign/src/pages/Demo.re
This PR implements the updated Cookie Consent component. 
Please note that the buttons have not been fully implemented so they will look slightly different compared to the designs.
See the mocks below for reference:
**Desktop**:
**Tablet**:
**Mobile**:
Closes https://github.com/CodaProtocol/coda/issues/5760
=> [Website] Cookie Consent 

src/app/client_sdk/client_sdk.ml, src/app/rosetta/lib/construction.ml, src/app/rosetta/test-agent/agent.ml, src/app/rosetta/test-agent/operation_expectation.ml, src/app/rosetta/test-agent/poke.ml, src/lib/rosetta_lib/transaction.ml, src/lib/rosetta_lib/user_command_info.ml
Add `create token` to Rosetta test agent.
`src/app/rosetta/start.sh` passes locally with these changes.
Implements more of #5817; TODO: `create token account`, `mint tokens`.
=> Add create token to Rosetta test agent

src/app/cli/src/tests/coda_processes.ml
Currently, it's hard to know whether flaky tests are failing because our timeout is too short, or whether the flakes are due to some other cause. This PR logs the initialisation time, so that we can rule out a too-short timeout, or bump the timeout if needed.
Checklist:
=> Log initialisation time when flaky tests are successful

src/app/client_sdk/client_sdk.ml, src/app/rosetta/lib/block.ml, src/app/rosetta/lib/construction.ml, src/app/rosetta/lib/mempool.ml, src/app/rosetta/test-agent/agent.ml, src/app/rosetta/test-agent/poke.ml, src/lib/rosetta_lib/transaction.ml, src/lib/rosetta_lib/user_command_info.ml
Add user command `Create_token_account` to the Rosetta test agent.
Locally, ran `start.sh` successfully.
Implements part of #5817 (only `Mint_tokens` remains to do).
=> Add create token account to Rosetta test agent

buildkite/src/Jobs/Lint/ValidationService.dhall
Prevent known and expected failure of `validation-service lint` jobs from affecting overall Coda pipeline/build status.
**Checklist:**
=> soft-fail validation-service lint tests on exit-status of 1

src/app/client_sdk/client_sdk.ml, src/app/rosetta/lib/construction.ml, src/app/rosetta/test-agent/agent.ml, src/app/rosetta/test-agent/operation_expectation.ml, src/app/rosetta/test-agent/poke.ml, src/lib/rosetta_lib/transaction.ml, src/lib/rosetta_lib/user_command_info.ml
Add `Mint_tokens` user command to Rosetta test agent.
Important change: for requests via the mempool, Rosetta was requesting nonces using a token id apparently from the receiver's account in the `operations` provided. Here, the token id used to get a nonce is always the default. There's a comment in the code, and the original code remains in a comment.
Also, the `Create_token_account` command was not being tested, added here.
`start.sh` sometimes fails with unexpected blocks with type `coinbase_inc`. That failure is not due to the added user command here. There is some nondeterminism that seems responsible for those errors.
Closes #5817.
=> Add Mint_tokens user command to Rosetta test agent

src/app/rosetta/rosetta.conf, src/app/rosetta/test-agent/agent.ml
Plus rosetta.conf updated for new rosetta-cli
./start.sh succeeds and `./start.sh FOREVER` with rosetta-cli check:data
passes
Note: This means that rosetta-cli check:data succeeds for all types of
transactions in Coda. As the test-agent now performs every single
transaction on chain.
=> The test-agent binary is no longer flaky

src/cstubs_applicative.opam, src/lib/cstubs_applicative/cstubs_applicative.ml, src/lib/cstubs_applicative/dune, src/lib/zexe_backend/zexe_backend_common/dlog_based_proof.ml
This PR updates the OCaml-rust bindings so that the OCaml garbage collector always calls the appropriate `delete` function when an object is freed. Zexe PR at o1-labs/zexe#24.
I have compiled this, but not tested it; any feedback from testing would be much appreciated.
Checklist:
=> [Release] Fix leaks in zexe rust bindings

buildkite/src/Monorepo.dhall
=> Use ssl in buildkite monorepo job

frontend/leaderboard/src/Bindings.re, frontend/leaderboard/src/Main.re, frontend/leaderboard/src/Postgres.re, frontend/leaderboard/src/UploadLeaderboardData.re
This PR has 2 fixes:
1. Fixes the column used for computing users in the `Main` spreadsheet. Originally, this was the first column but the second column is a list of unique usernames so that should be used instead. Additionally, moved the call to `uploadUserProfileData` to outside the Postgres query as it's not dependent on the query and we'd like to execute it no matter what.
2. Fixes the Postgres config object to accept a time out parameter. This defaults to 5 seconds. 
These fixes were tested locally.
=> Leaderboard: Fixes to member profile backend and postgres timeout

dockerfiles/Dockerfile-toolchain
Per google cloud sdk deb [package install docs](https://cloud.google.com/sdk/docs/downloads-apt-get#deb-extras) (to go along with the existing toolchain image setup), explicitly install `kubectl` deb package in addition to default `google-cloud-sdk` tooling package to enable *k8s* ops.
**Testing:** TBD
Checklist:
=> add explicit installation of `kubectl` tool along w/ google-cloud-sdk

src/app/rosetta/bootstrap_balances.json, src/app/rosetta/docker-demo-start.sh, src/app/rosetta/lib/block.ml, src/app/rosetta/make-runtime-genesis.sh, src/app/rosetta/run-demo.sh, src/app/rosetta/test-agent/agent.ml, src/app/rosetta/test-agent/operation_expectation.ml, src/lib/rosetta_lib/user_command_info.ml
* Improved demo to use separate snark worker
* Supports "failed txns" properly
* Passes test-agent and rosetta-cli check:data tests
=> Supports "failed txns"

src/lib/coda_base/ledger.mli, src/lib/coda_base/sparse_ledger.ml, src/lib/coda_base/transaction_logic.ml, src/lib/coda_base/transaction_union.ml, src/lib/transaction_snark/transaction_snark.ml
Outside snark,  the timing field is updated only for accounts whose  balance is deducted (when we check if the account still maintains a min balance). In transaction snark this wasn't true for coinbase and fee transfer, where the coinbase/fee receiver account's timing field was getting set to `Untimed` when the tokens were unlocked.
Changed the out-of-snark behaviour to update the timing of fee transfer/coinbase accounts that is encoded as `fee_payer` or `source` account in a transaction to avoid checks in the snark
Checklist:
=> match out-of-snark and in-snark account-timing updates

dockerfiles/Dockerfile-coda-daemon, src/app/cli/src/init/client.ml, src/app/cli/src/tests/coda_processes.ml, src/app/libp2p_helper/src/libp2p_helper/main.go, src/app/libp2p_helper/src/mplex.go, src/config/testnet_postake_medium_curves.mlh, src/lib/child_processes/child_processes.ml, src/lib/coda_lib/coda_subscriptions.ml, src/lib/coda_net2/coda_net2.ml, src/lib/coda_net2/coda_net2.mli, src/lib/coda_networking/coda_networking.ml, src/lib/coda_networking/coda_networking.mli, src/lib/gossip_net/any.ml, src/lib/gossip_net/fake.ml, src/lib/gossip_net/intf.ml, src/lib/gossip_net/libp2p.ml, src/lib/pipe_lib/linear_pipe.ml, src/lib/pipe_lib/strict_pipe.ml
This PR addresses an issue on the QA net in which nodes terminate because their libp2p helper crashes unexpectedly. When that happens, we restart the helper.
=> Restart libp2p

scripts/rebuild-deb.sh, src/app/cli/src/coda.ml, src/lib/cache_dir/cache_dir.ml
Runtime config file look up order
1. daemon flag `-config-file`
2. env variable `CODA_CONFIG_FILE` 
3. one of the install paths
4. config-dir/daemon.json
5. compiled configuration
Checklist:
Closes #0000
Closes #0000
=> [hotfix] Look for the config file in install paths

frontend/website/pages/docs/getting-started.mdx, frontend/website/pages/docs/my-first-transaction.mdx
This PR changes the old echo bot public key to use the newly generated key with the new key pair format. This change was already merged into develop but should also be pushed into master.
Previous commit: #5959
=> Website: Updating website docs with new echo bot pk

.circleci/config.yml, .circleci/config.yml.jinja, scripts/setup-opam.sh
The hosting for the tar files is currently down. This makes CI pull the source from github instead.
Checklist:
=> Fix CI: Manually pin ocamlgraph while ocamlgraph.lri.fr is down
