MinaProtocol/mina

- Dockerfile-step2-build
- Dockerfile-toolchain
- dockerfiles/Dockerfile-toolchain
> rename toolchain, add gc

- README-dev.md
> dev notes about new docker

- docs/demo.md
- src/app/website/src/open_source.ml
Code copy includes Docker commands now, and link in demo.md is correct now.
> Fix code copy and fix link in demo.md

- README-dev.md
- scripts/buildwarns.py
- scripts/container.sh
Minor whitespace changes - responding to issues raised by 'codacity - static code checker'
> markdown and minor py lint

- .circleci/config.yml
- .circleci/render.py
- src/app/cli/src/coda.ml
- src/app/cli/src/coda_block_production_test.ml
- src/app/cli/src/coda_peers_test.ml
- src/app/cli/src/coda_process.ml
- src/app/cli/src/coda_processes.ml
- src/app/cli/src/coda_restart_node_test.ml
- src/app/cli/src/coda_shared_prefix_test.ml
- src/app/cli/src/coda_shared_state_test.ml
- src/app/cli/src/coda_transitive_peers_test.ml
- src/app/cli/src/coda_worker.ml
- src/app/cli/src/coda_worker_testnet.ml
- src/app/cli/src/full_test.ml
- src/lib/consensus/mechanism.ml
- src/lib/consensus/proof_of_signature.ml
- src/lib/consensus/proof_of_stake.ml
- src/lib/snark_params/snark_params.ml
- src/lib/syncable_ledger/syncable_ledger.ml
- src/lib/transaction_snark/transaction_snark.ml
This increases the ledger depth to 30
> increase depth to 30

- Makefile
> only check branch

- src/lib/ledger_builder_controller/ktree.ml
@jkrauska discovered a strange stack overflow in the production testnet that pointed to part of the `add` logic that would only possible occur if the ktree was not properly discarding old information (see #1102). Despite our intentions for the ktree to do so, it was not properly discarding older data in the tree (past the max-depth).
I wrote a failing unit test that reproduced the error (I chose 60_000 as the testnet was on block 58k when it failed). Then I fixed the bug, and the unit test passes.
Checklist:
> Ktree now properly discards data past max-depth

- src/app/cli/src/web_pipe.ml
- src/lib/web_request/s3_put_request.ml
> `chain` will not cache in the browser

- src/app/lite/main.ml
- src/app/lite/verifier.ml
- src/app/website/src/main.ml
Created code to automate build process for the website. Now, the seed node sends javascript files into S3. A client will load the javascript files in S3. This PR implements the client loading javascript files from S3.
Checklist:
> Retrieve javascript code from s3

- src/app/cli/src/client.ml
This is a basic CLI for setting one's delegate
> delegation cli command

- scripts/container.sh
- src/app/website/jobs/business-development.markdown
- src/app/website/jobs/community-manager.markdown
- src/app/website/jobs/engineering-manager.markdown
- src/app/website/jobs/product-manager.markdown
- src/app/website/jobs/protocol-engineer.markdown
- src/app/website/src/main.ml
Added new job postings on `codaprotocol.com` website.
I broke protocol and deployed already because there's some nuance with the static deps until we make the testnet page more robust
> Added new job posts on website

- src/ledger_catchup.opam
- src/lib/ledger_catchup/dune
- src/lib/ledger_catchup/ledger_catchup.ml
- src/lib/sync_handler/dune
- src/lib/sync_handler/sync_handler.ml
- src/sync_handler.opam
Intentionally crashing for now. This will let us better debug the rest
of the transition-frontier-controller system.
> Scaffold for catchup/sync_handler

- src/lib/coda_base/ledger.ml
- src/lib/coda_base/ledger.mli
- src/lib/merkle_ledger/any_ledger.ml
- src/lib/merkle_ledger/base_ledger_intf.ml
- src/lib/merkle_ledger/database_intf.ml
- src/lib/merkle_ledger/ledger.ml
- src/lib/merkle_ledger_tests/test_mask.ml
Once we've unified Maskable and Masking interfaces, we can make an
Any_maskable/Any_masking and then we have the recursion.
`dune runtest` on the test_masks tests pass
> Don't depend on a base, use dynamic dispatch

- Makefile
- dockerfiles/Dockerfile-codaslim
Adjust Makefile to publish master debs to 'stable' and leave others in 'unstable'.
> SIMPLE: stable master deb 

- src/app/cli/src/coda_main.ml
- src/app/cli/src/coda_peers_test.ml
- src/app/cli/src/coda_transitive_peers_test.ml
- src/app/cli/src/coda_worker.ml
- src/app/cli/src/coda_worker_testnet.ml
- src/app/cli/src/prover.ml
- src/app/cli/src/prover.mli
- src/app/cli/src/verifier.ml
- src/app/cli/src/verifier.mli
- src/app/cli/src/web_pipe.ml
- src/lib/blockchain_snark/blockchain.ml
- src/lib/blockchain_snark/blockchain.mli
- src/lib/coda_lib/coda_lib.ml
- src/lib/consensus/intf.ml
- src/lib/consensus/mechanism.ml
- src/lib/consensus/proof_of_signature.ml
- src/lib/consensus/proof_of_signature.mli
- src/lib/consensus/proof_of_stake.ml
- src/lib/consensus/proof_of_stake.mli
- src/lib/ledger_builder_controller/catchup.ml
- src/lib/ledger_builder_controller/inputs.ml
- src/lib/ledger_builder_controller/ledger_builder_controller.ml
- src/lib/ledger_builder_controller/transition_logic.ml
- src/lib/ledger_builder_controller/transition_logic_state.ml
- src/lib/ledger_catchup/ledger_catchup.ml
- src/lib/proposer/proposer.ml
- src/lib/transition_frontier_controller/transition_frontier_controller.ml
- src/protocols/coda_pow.ml
As a result, the following happened:
-  Made Blockchain, Prover, and Verifier into regular modules
- Removed unnecessary inputs for Coda_main
Checklist:
> Removed Consensus.Mechanism Functor

- src/lib/pipe_lib/strict_pipe.ml
- src/lib/pipe_lib/strict_pipe.mli
- src/lib/sync_handler/dune
- src/lib/sync_handler/sync_handler.ml
- src/lib/transition_frontier_controller/transition_frontier_controller.ml
- src/protocols/coda_transition_frontier.ml
Added more functions into Strict_pipe
Checklist:
> Implemented sync_handler

- Makefile
Quick change to Makefile to add cache-control header to deb uploads.
> SIMPLE:add cache-control

- src/app/cli/src/client.ml
Leftover debug code from #1125.
Closes #1239
> fix generate-keypair

- README-dev.md
Add pinned dune to `README-dev`. Also mention install script for RocksDB C libraries.
Checklist:
> custom dune; mention RocksDB lib install

- src/app/cli/src/coda.ml
Quick fix to say goodbye before going to the background.
> SIMPLE: Say goodbye before daemonizing

- src/lib/pipe_lib/strict_pipe.ml
- src/lib/pipe_lib/strict_pipe.mli
Added fork on strict-pipe
Not tested, but follows similar logic to fork on linear-pipe
> Fork on strict-pipe

- Makefile
> wrap deb-s3 commands to check for AWS creds in environment

- src/lib/coda_lib/coda_lib.ml
- src/lib/non_zero_curve_point/non_zero_curve_point.ml
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/transition_frontier_controller/transition_frontier_controller.ml
- src/lib/transition_handler/processor.ml
- src/protocols/coda_transition_frontier.ml
Passes full-test :heart_eyes_cat: 
See each commit.
> 3 tfc bugfixes

- src/app/cli/src/coda_process.ml
- src/app/cli/src/coda_receipt_chain_test.ml
- src/app/cli/src/coda_worker.ml
> Created a failing test for coda_receipt_chain_test

- src/lib/transition_handler/validator.ml
makes coda-shared-prefix-test pass!
> validator: don't pass on transitions to states we know

- src/app/cli/src/client.ml
- src/app/cli/src/coda_main.ml
- src/app/cli/src/coda_receipt_chain_test.ml
- src/app/cli/src/coda_worker.ml
- src/app/cli/src/coda_worker_testnet.ml
- src/app/cli/src/full_test.ml
- src/lib/daemon_rpcs/daemon_rpcs.ml
Tested by hand. If there's a good way to test the CLI I'll write an automated test, but the test suite is confusing me so I'll need some guidance.
Checklist:
Closes #1001
> Fix #1001: Client now reports invalid payments to user rather than crashing daemon

- scripts/jqproc.sh
This script is quick and dirty, but it will at least give me something to work off of when debugging logs from the devnet. A better print format and level based coloring would be the next steps.
> Add jqproc, a temporary json replacement for logproc

- src/lib/snarky/src/cvar.ml
- src/lib/snarky/src/monad_sequence.ml
- src/lib/snarky/src/snark0.ml
This PR
1. Adds a new optimization where no constraints are created for multiplication or division of constants.
2. Adds a checked `fold_map` function.
> New optimization in snarky + fold_map

- src/app/cli/src/transaction_snark_profiler.ml
- src/lib/snarky/src/gm_verifier_gadget.ml
- src/lib/snarky/src/libsnark.ml
Cleans up a few logging statements as requested by @jkrauska. Closes https://github.com/CodaProtocol/coda/issues/983
> clean up logs

- src/lib/coda_lib/coda_lib.ml
- src/lib/proposer/proposer.ml
- src/lib/transition_frontier_controller/transition_frontier_controller.ml
- src/lib/transition_handler/processor.ml
- src/lib/transition_router/transition_router.ml
- src/protocols/coda_transition_frontier.ml
This is dependent on #1353 and needs to be rebased after that is merged. For now, the 2 most recent commits can be reviwed. This is actually a small PR, the line diff is just big because my other PR is included right now.
> Optimize Proposer Pipe

- src/lib/snarky/src/jbuild
- src/lib/snarky/src/snark0.ml
Failed to remove all traces 😉 of these libraries in my last PR
> Remove o1trace and coda debug from snarky

- src/lib/snarky_verifier/groth_maller.ml
- src/lib/snarky_verifier/inputs.ml
this pr implements the groth maller 2017 verifier in snarky. see [page 18 here](https://eprint.iacr.org/2017/540.pdf)
> implement gm verifier in snarky

- src/lib/ledger_builder/ledger_builder.ml
Ledger builder diff related changes
> Create-diff refactoring PART 4: ledger builder test changes

- src/lib/coda_lib/coda_lib.ml
I shouldn't have removed this, sorry.
> put directory_name back

- src/lib/snarky/src/camlsnark_c/libsnark-caml/libsnark/zk_proof_systems/ppzksnark/r1cs_gg_ppzksnark/r1cs_gg_ppzksnark.tcc
This fixes an error I made in removing gamma, wherein it was not fully removed.
> Fix groth16 gamma removal

- .gitattributes
- Makefile
- docs/res/ledgers_in_frontier.png
- docs/res/ledgers_in_frontier.tex
- docs/res/ledgers_in_frontier.tex.png
Diagram showing ledgers within transition-frontier to make it clear where the snarked database is vs the masks.
> Diagram showing ledgers within transition-frontier

- src/lib/snarky_curves/snarky_curves.ml
Just a rename and two convenience functions
> Tweaks to snarky curves lib (small)

- Makefile
- scripts/macos-setup.sh
Don't run brew when you don't need to. (previously ran with whitespace)
> only run brew when needed

- .circleci/config.yml
- .circleci/config.yml.jinja
- Makefile
- scripts/getkeys.sh
- scripts/rebuild-deb.sh
- Splits build_withsnark in to two separate flows (one for sig, one for snark)
- adjusts deb build to note consensus
> split snark with steak and sig

- .circleci/config.yml
- .circleci/config.yml.jinja
Forgot to enable the new lint job in my last PR
> Enable lint job

- README-dev.md
In `README-dev.md`, added mention of a git configuration item, so that updating the repo automatically updates the snarky submodule.
> Config for submodule auto-updates

- src/app/website/jobs/product-manager.markdown
- src/app/website/src/team.ml
Fixed tiny grammar mistake.
Checklist:
Closes #0000
Closes #0000
> Made tweaks to the website

- scripts/test_all.sh
right now master is red because jqproc fails to parse a line?
> only fail run_integration_test if coda fails

- src/config/debug.mlh
- src/config/dev.mlh
- src/config/dev_snark.mlh
- src/config/fake_hash.mlh
- src/config/ledger_depth/full.mlh
- src/config/ledger_depth/tiny.mlh
- src/config/test_posig.mlh
- src/config/test_posig_snarkless.mlh
- src/config/test_postake_snarkless.mlh
- src/config/testnet_posig.mlh
- src/config/testnet_postake.mlh
- src/config/testnet_postake_snarkless.mlh
- src/config/testnet_public.mlh
- src/lib/snark_params/jbuild
- src/lib/snark_params/snark_params.ml
use ledger_depth=6 for fake_hash. everywhere else, it is left at 30.
> Make ledger_depth compile-time configuration

- src/lib/kademlia/membership.ml
Prior to this commit they only worked from src
Tested by running tests from project root and `src`. Both work.
Checklist:
> Fix running Kademlia tests from project root

- src/app/website/static/css/blog.css
Tested by looking at the output after tweaking changes.
> Fix blog styling because pandoc changed css classes

- .circleci/config.yml
- .circleci/config.yml.jinja
- scripts/macos-setup.sh
Combines cache saves and restores full option if it's there.
> improve caching for mac build

- .circleci/config.yml
- .circleci/config.yml.jinja
split caches to isolate by pathing
> indpendent caches

- .circleci/config.yml
- .circleci/config.yml.jinja
- .circleci/render.py
- src/config/test_postake.mlh
> Full-test with stake on CI

- src/config/testnet_postake_snarkless_fake_hash.mlh
slows down fakehash to 1s slot intervals
> simple: 1s slot

- src/app/kademlia-haskell/app/Main.hs
- src/app/kademlia-haskell/packages.nix
- src/app/kademlia-haskell/stack.yaml
See commit messages. Ran the Kademlia tests with old OCaml code and new OCaml code, both work.
Checklist:
> Haskell kad fixes

- src/lib/coda_base/coinbase.ml
Use the newfangled module versioning for `Coda_base.Coinbase`.
Closes #0000
Closes #0000
> Version the Coinbase module

- src/lib/coda_numbers/dune
- src/lib/coda_numbers/nat.ml
- src/lib/coda_numbers/nat.mli
Version modules in `Nat`.
Checklist:
> Version Nat modules

- src/lib/merkle_address/dune
- src/lib/merkle_address/merkle_address.ml
Versioning of `Merkle_address` module.
Checklist:
> Version Merkle_address module

- src/lib/coda_base/user_command_payload.ml
Use versioning of modules in `User_command_payload`.
Checklist:
> Version User_command_payload modules

- src/lib/coda_base/payment_payload.ml
Versioning for `Payment_payload` module.
Checklist:
> Version Payment_payload module

- src/lib/coda_base/signature.ml
Version module in `coda_base/signature`
Checklist:
> Version signature module

- .mergify.yml
> add mergify configuration

- src/lib/merkle_ledger/dune
- src/lib/merkle_ledger/ledger.ml
Use versioning for `Ledger` in `Merkle_ledger`.
Checklist:
> Version Ledger module

- src/lib/network_peer/dune
- src/lib/network_peer/peer.ml
Wrapped the module in `Peer` inside a `Stable`, added versioning boilerplate.
Checklist:
> Version Peer module

- src/app/cli/src/verifier.ml
> proof_level=check verifier was broken

- src/app/cli/src/client.ml
- src/app/cli/src/coda.ml
- src/lib/cli_lib/fee.ml
Setup fee defaults for CLI, use Currency.fee type instead of int.
> simple: set default fees

- src/app/cli/src/coda.ml
- src/lib/lite_params/gen/gen.ml
- src/lib/snark_params/snark_params.ml
Updates the snarky version and remove all references to gadgets (which were no longer in use anyway)
> Bump snarky version, remove mention of gadgets

- src/config/test_posig_snarkless.mlh
- src/lib/kademlia/membership.ml
This test has failed a few times on my PRs and I'm noticing it failing on several PRs that didn't touch code related to this. I'm disabling this test for now.
See #1725
> Temporarily disable flaky test

- src/lib/consensus/proof_of_signature.ml
There was a module being passed to functor that wasn't used.
Checklist:
> Remove unused module

- .circleci/config.yml
- .circleci/config.yml.jinja
- scripts/artifacts.sh
Adds a step to copy artifacts to GC.
(faster performance, central location)
> simple: copy to gc step

- src/app/website/src/careers.ml
> Swap product manage / eng manager

- src/app/cli/src/client.ml
- src/app/cli/src/coda.ml
- src/lib/daemon_rpcs/daemon_rpcs.ml
minor cosmetic changes in strings used in CLI help
> SIMPLE: cosmetic changes

- src/lib/ledger_catchup/ledger_catchup.ml
- src/lib/non_empty_list/non_empty_list.ml
- src/lib/non_empty_list/non_empty_list.mli
- src/lib/sync_handler/sync_handler.ml
- src/lib/transition_frontier/transition_frontier.ml
- src/lib/transition_frontier_controller_tests/stubs.ml
- src/lib/transition_frontier_controller_tests/test_ledger_catchup.ml
- src/lib/transition_frontier_controller_tests/test_transition_frontier.ml
- src/protocols/coda_transition_frontier.ml
> Added Root_history into transition_frontier

- src/lib/consensus/proof_of_stake.ml
zero pads epoch and slot for easier sorting
> simple: 0 pad

- src/lib/consensus/intf.ml
- src/lib/consensus/proof_of_stake.ml
- src/lib/proposer/proposer.ml
- src/protocols/coda_pow.ml
> know how to propose for the current slot

- src/lib/transition_frontier/transition_frontier.ml
I think maybe whatever I was seeing was spurious, because I can't reproduce it right now. Put the mask code back, with the assertion that we used to fail. Just in case.
> put the mask code back

- src/lib/transition_frontier/transition_frontier.ml
Reverts CodaProtocol/coda#1770
> Revert " put the mask code back"

- .circleci/config.yml
- .circleci/render.py
> simple: skip failing test

- src/lib/coda_base/user_command.ml
Skip user-command check on fake_hash
Fake-hash profile builds
> Skip user-command check on fake_hash

- src/app/cli/src/coda.ml
- src/app/cli/src/coda_five_nodes_test.ml
- src/config/test_postake_five_even_snarkless.mlh
- src/lib/genesis_ledger/genesis_ledger.ml
- src/lib/genesis_ledger/test_five_even_stakes.ml
Purposefully, not adding this test to CI yet. Still needs to be tuned.
This genesis ledger may be useful to others besides me, so I thought I'd try to check this in sooner rather than later.
> Test ledger and integration test for 5 even stakes

- src/app/website/src/main.ml
Make sure to generate the community manager page. I verified it exists and doesn't 404 now.
> Make sure to generate community manager page

- src/lib/transition_frontier_controller/transition_frontier_controller.ml
In this PR, I let the transition_frontier_controller clone the proposer_transition_reader pipe, so that there won't be multi-reads attempt to it. And the copy would be cleaned up after the transition_frontier_controller finishes its job.
> Transition_frontier_controller pipe multi-reads error

- src/lib/transaction_pool/transaction_pool.ml
In this PR, I add an if statement to the second of the branch of `Deferred.any_unit`, so that if the first of branch executed successfully before the second one, then the second one (which contains the error message and `assert false`) won't be executed.
> Transaction_pool assertion false error

- .circleci/config.yml
- .circleci/config.yml.jinja
Wrap all commands that should be skipped for frontend-only changes. This PR should still execute all tests. I'll do another frontend-only one after this lands to make sure it works properly (hard to do before it lands)
> Frontend changes skip tests

- scripts/skip_if_only_frontend.sh
> simple:run builds in master

- .circleci/config.yml
- Makefile
- scripts/artifacts.sh
- scripts/test.py
Nathan had changed CI Job names, needed to adjust this logic too.
> SIMPLE:CIRCLE_JOB naming fix

- src/app/website/jobs/community-manager.markdown
- src/app/website/jobs/developer-advocate.markdown
- src/app/website/jobs/director-of-business-development.markdown
- src/app/website/src/careers.ml
- src/app/website/src/main.ml
- Fixed a broken link on the careers page
- Added Community Manager to repo
yet.
Checklist:
Closes #0000
Closes #0000
> Added Developer Advocate and Director of Business

- src/lib/snarky_taylor/floating_point.ml
- src/lib/snarky_taylor/floating_point.mli
- src/lib/snarky_taylor/integer.ml
Just bumps the snarky version and makes code work against it
> bump snarky version

- frontend/website/package-lock.json
- frontend/website/package.json
- frontend/website/src/Code.re
- frontend/website/src/Render.re
- frontend/website/src/Style.re
Pages are rendered declaratively, the entire site directory is wiped and recreated each build.
The beginnings of a code page are started.
> Render pages declaratively, begin code page

- .circleci/config.yml
- .circleci/config.yml.jinja
- .mergify.yml
- scripts/test.py
- src/app/cli/src/coda_block_production_test.ml
- src/app/cli/src/coda_bootstrap_test.ml
- src/app/cli/src/coda_five_nodes_test.ml
- src/app/cli/src/coda_peers_test.ml
- src/app/cli/src/coda_process.ml
- src/app/cli/src/coda_receipt_chain_test.ml
- src/app/cli/src/coda_restart_node_test.ml
- src/app/cli/src/coda_restarts_and_txns_holy_grail.ml
- src/app/cli/src/coda_shared_prefix_multiproposer_test.ml
- src/app/cli/src/coda_shared_prefix_test.ml
- src/app/cli/src/coda_shared_state_test.ml
- src/app/cli/src/coda_transitive_peers_test.ml
- src/app/cli/src/coda_worker_testnet.ml
maybe this will stop the socket reuse errors by explicitly waiting for our workers to die.
> tear down workers after tests

- frontend/website/src/LegacyPage.re
- frontend/website/src/Render.re
We'll make a new Page for the pages that aren't legacy
> Page -> LegacyPage

- frontend/website/src/Home.re
- frontend/website/src/Nav.re
- frontend/website/src/Page.re
- frontend/website/src/Render.re
- frontend/website/src/Style.re
* Scaffolding for home page
* New page container, wraps at size to spec
* Nav elements are duplicated for now, we can fix later
> New page container

- frontend/website/src/Blog.re
- frontend/website/src/BlogPost.re
- frontend/website/src/CareerPost.re
- frontend/website/src/Markdown.re
- frontend/website/src/Render.re
Shows most recent blog post and has a section at the bottom with links to previous posts in order.
> Add blog index page

- frontend/website/src/CodaNav.re
- frontend/website/src/LegacyPage.re
- frontend/website/src/Nav.re
- frontend/website/src/Page.re
- frontend/website/src/Style.re
It feels right to me to inline the top-level flex-logic in the jsx.
Honestly, the only reason I didn't inline everything is because I needed
to use that crazy checkbox hack and refer to another class. Let me know
what you think re: when we should be inlining styles.
Responsive reflowing shown here:
> Nav closer to spec

- .circleci/config.yml
- .circleci/config.yml.jinja
- scripts/test.py
capture logs from test run so they can be viewed.
> SIMPLE: store test artifacts in CI

- .circleci/config.yml
- .circleci/config.yml.jinja
- .gitignore
- frontend/website/.firebaserc
- frontend/website/firebase.json
- frontend/website/package-lock.json
- frontend/website/package.json
I added FIREBASE_TOKEN to the circle env.
Tested with the following commands:
```bash
▿ staging-on-ci-master│..22 ⇣
𝝺 bash -c 'cd frontend/website && (if [ "$CIRCLE_BRANCH" == "master" ]; then npm run deploy-ci; fi)'
▿ staging-on-ci-master│..22 ⇣
𝝺 CIRCLE_BRANCH="master" bash -c 'cd frontend/website && (if [ "$CIRCLE_BRANCH" == "master" ]; then npm run deploy-ci; fi)'
```
> On CI master, push website to staging

- frontend/website/package-lock.json
- frontend/website/package.json
- frontend/website/src/LegacyPage.re
This is a testing release of bsb, but seems to work for us and will likely solve the problem of opam and bs-platform refmt versions being out of sync (mostly just annoying for editor tooling)
Note: The package.lock change isn't that big, it's just not displayed on github by default.
> Update website bs-platform version

- frontend/website/src/HeroSection.re
- frontend/website/src/Nav.re
My gif is too large, and I'm struggling to get it to a small enough size. So you'll either have to use your imagination or build it locally to see. (Or wait until it's on master and staging does it)
> Better hero section

- src/config/test_postake_split.mlh
yet.
Checklist:
Closes #0000
Closes #0000
> Fixed Postake config by adding curve_size config

- frontend/website/src/Home.re
- frontend/website/src/InvestorsSection.re
- frontend/website/src/Page.re
- frontend/website/src/Render.re
- frontend/website/src/Style.re
Also fixed up the H3.wide (the one with the wings) so that it doesn't have weird margins and doesn't wrap
> Add investors section to website

- frontend/website/src/Grid.re
- frontend/website/src/Page.re
> Grid that's close enough to zeplin's version

- frontend/website/src/Grid.re
- frontend/website/src/Nav.re
- frontend/website/src/Page.re
Things are aligned a bit better, grid is a bit better:
> Somewhat better nav (more to spec)

- .circleci/config.yml
- .circleci/config.yml.jinja
Cannot run this test without source code.
> TRIVIAL: update-branch-protection needs source

- .circleci/config.yml
- .circleci/config.yml.jinja
> TRIVIAL:needs jinja2

- frontend/website/src/AnnouncementBar.re
- frontend/website/src/Code.re
- frontend/website/src/Home.re
- frontend/website/src/InvestorsSection.re
- frontend/website/src/Style.re
- frontend/website/src/TeamSection.re
I'll follow up with adding the expand/contract and the "Built By O(1) Labs" header.
> Add team to website

- src/app/logproc/dune
- src/app/logproc/filter.ml
- src/app/logproc/logproc.ml
Added a test for the broken filter as well.
> Fix logproc filter bugs

- frontend/website/src/CryptoAppsSection.re
- frontend/website/src/HeroSection.re
- frontend/website/src/Home.re
- frontend/website/src/InclusiveSection.re
- frontend/website/src/Size.re
- frontend/website/src/Style.re
- frontend/website/src/Svg.re
- frontend/website/src/TeamSection.re
- frontend/website/src/Title.re
- frontend/website/static/img/coda-figure.svg
- frontend/website/static/img/other-blockchains-figure.svg
Not quite to spec yet, but decent.
Made a few useful things:
* Size: A pair of pixel-values width/height that you can ask for rems
* Svg: The boilerplate for loading svgs from files
* Title: The thing that goes at the top of the 2nd, 3rd, 4th sections
> Inclusive section is passable

- frontend/website/src/Home.re
- frontend/website/src/Style.re
- frontend/website/src/TeamSection.re
Still need to fix up the fonts.
> Add Built By header and fix margins

- .circleci/config.yml
- .mergify.yml
- scripts/test.py
- src/lib/merkle_ledger_tests/test_stubs.ml
Now we won't have build failures in master. :)
Checklist:
> Test dev profile in CI

- frontend/website/src/CryptoAppsSection.re
- frontend/website/src/Home.re
- frontend/website/src/InclusiveSection.re
- frontend/website/src/Style.re
- frontend/website/src/SustainableSection.re
- frontend/website/src/Title.re
- frontend/website/static/img/chart-blockchain-energy.svg
- frontend/website/static/img/chart-blockchain-size.svg
- frontend/website/static/img/leaf.svg
> Section looks passable

- frontend/website/src/Code.re
- frontend/website/src/Render.re
- frontend/website/src/Style.re
It's not perfect but better than an empty page. It's a bit annoying to deal with both kinds of style in the same file but didn't want to take the time to convert everything just yet.
> Add rough code page

- frontend/website/src/AnnouncementBar.re
- frontend/website/src/CodaNav.re
- frontend/website/src/HeroSection.re
- frontend/website/src/Nav.re
- frontend/website/static/img/hero-illustration.svg
* Hover states on nav buttons
* Better hero section
* New svg for hero
> Website cleanups

- frontend/website/src/Code.re
- frontend/website/src/Render.re
- frontend/website/src/Testnet.re
- frontend/website/static/main.bc.js
- frontend/website/static/verifier_main.bc.js
> Add testnet page

- frontend/website/src/CryptoAppsSection.re
- frontend/website/src/InclusiveSection.re
- frontend/website/src/SustainableSection.re
Definitely not perfect, but the text on the right stays aligned vertically and everything is centered when it gets small.
> Experiment with homepage centering

- .gitattributes
- frontend/website/src/Blog.re
- frontend/website/src/RunScript.re
- frontend/website/src/Style.re
- src/app/website/posts/snarky.markdown
- Fix the pandoc error
- Add missing lfs to gitattributes
- Fix some compilation warnings
> Small website fixes

- frontend/website/src/GetInvolvedSection.re
- frontend/website/src/Home.re
Smashed out a shell of a section, it's mediocre, but you can tell it's getting closer to the thing.
> Get involved section mediocre

- frontend/website/src/CodaNav.re
- frontend/website/src/Nav.re
- frontend/website/src/Style.re
> Signup button to-spec

- src/lib/coda_base/ledger.mli
- src/lib/coda_base/transaction_logic.ml
Version `User_command_undo` and its contained modules `Body` and `Common`.
> Version User_command_undo

- frontend/website/src/HeroSection.re
- frontend/website/src/Page.re
- frontend/website/src/Style.re
- frontend/website/src/Svg.re
Hero aligned to baseline.
Since this was very pixel-pushingy I used pixels -- it seems to be fine if you scale with zoom
> Pixel push alignment + thinner fonts

- src/lib/transition_frontier/transition_frontier.ml
The new shared prefix test with 2 proposers will catch bugs caused by this (with two proposers, you'll ~always fork after k blocks)
> consult consensus to change the best tip

- frontend/website/src/Careers.re
- frontend/website/src/CodaNav.re
- frontend/website/src/HeroSection.re
- frontend/website/src/InvestorsSection.re
- frontend/website/src/Nav.re
- frontend/website/src/TeamSection.re
- Bigger buttons on dropdown nav
- Fix media query jumping on investors
- Fix wrapping on careers page
- Tweak size of team members
- Fix typo in hero section
> Small padding fixes for website

- frontend/website/src/GetInvolvedSection.re
- frontend/website/src/Style.re
- frontend/website/static/font/IBMPlexSerif-Medium-Latin1.woff
- frontend/website/static/font/IBMPlexSerif-Medium-Latin1.woff2
> Improve Get Involved section

- src/lib/coda_base/staged_ledger_hash.ml
- src/lib/random_oracle/dune
- src/lib/random_oracle/random_oracle.ml
Instead, encode the blob with base64.
> don't include binary data in json

- src/lib/syncable_ledger/test.ml
Removed it when deleting the in-memory ledger code. Oops!
> Put back syncable ledger test with db ledger

- frontend/website/src/GetInvolvedSection.re
- frontend/website/src/Style.re
- frontend/website/src/Svg.re
Embedded svgs now seem to be loading on firefox/safari
> Fix svgs and Get Involved

- frontend/website/src/HeroSection.re
> Hero section better top margin and crunches

- frontend/website/src/InclusiveSection.re
> Legend is better (inclusive section)

- frontend/website/src/CryptoAppsSection.re
- frontend/website/src/HeroSection.re
- frontend/website/src/Nav.re
- frontend/website/src/Style.re
- frontend/website/static/img/coda-icon.png
- frontend/website/static/img/coda-icon@2x.png
- frontend/website/static/img/coda-icon@3x.png
- frontend/website/static/img/coda-logo.png
- frontend/website/static/img/coda-logo@2x.png
- frontend/website/static/img/coda-logo@3x.png
- frontend/website/static/img/coda.png
- frontend/website/static/img/coda@2x.png
- frontend/website/static/img/coda@3x.png
- frontend/website/static/img/icon.svg
- frontend/website/static/img/montage.png
- frontend/website/static/img/montage@2x.png
- frontend/website/static/img/montage@3x.png
> Better assets, better lines

- frontend/website/src/HeroSection.re
- frontend/website/src/Home.re
- frontend/website/src/Nav.re
- frontend/website/src/Page.re
- frontend/website/src/Style.re
- frontend/website/src/TeamSection.re
> Nav and hero baseline and beautiful announce

- frontend/website/src/CryptoAppsSection.re
- frontend/website/src/InclusiveSection.re
- frontend/website/src/SideText.re
- frontend/website/src/SustainableSection.re
- frontend/website/src/Title.re
> The crisp vertical line on mobile size

- frontend/website/src/CryptoAppsSection.re
- frontend/website/src/GetInvolvedSection.re
- frontend/website/src/Style.re
- Try to fix fonts
- Make crypto apps section selectable and links clickable
- Make code block monospaced
- Fix some chrome/safari compatibility issues in the Get Involved section
> Try to fix fonts, monospace, safari compat

- src/lib/gossip_net/dune
- src/lib/gossip_net/gossip_net.ml
This helped me understand some timeouts I was seeing.
> gossip_net: more logging around errors

- frontend/website/src/GetInvolvedSection.re
- frontend/website/src/Testnet.re
> Fix testnet centering and font

- frontend/website/src/CodaNav.re
- frontend/website/src/CryptoAppsSection.re
- frontend/website/src/Grid.re
- frontend/website/src/HeroSection.re
- frontend/website/src/Home.re
- frontend/website/src/Nav.re
- frontend/website/src/Page.re
The grid says everything:
(fixed, see below)
> Polish the top alot

- frontend/website/src/CryptoAppsSection.re
- frontend/website/src/GetInvolvedSection.re
- frontend/website/src/HeroSection.re
- frontend/website/src/Image.re
- frontend/website/src/InclusiveSection.re
- frontend/website/src/InvestorsSection.re
- frontend/website/src/Nav.re
- frontend/website/src/Page.re
- frontend/website/src/SustainableSection.re
- frontend/website/src/Svg.re
- frontend/website/src/TeamSection.re
First pass at trying to improve the accessiblity of the homepage. Used a few different auditing tools and the voiceover tool in safari.
This one might warrant actual review as it includes alt text copy that I made up.
One thing that could be improved according to the auditing tools is the contrast on some of the text, like the blue on blue of the announcements bar, but I thought it must have already been encountered/resolved in the design phase so I left it for now.
> First pass at website front page accessibility

- frontend/website/src/CodaNav.re
- frontend/website/src/Nav.re
- frontend/website/src/Page.re
- frontend/website/src/Render.re
* Fixed the 1px off on signup button text
* Only show announce bar on home page
> Announce only on homepage

- frontend/website/src/Testnet.re
The explanations are currently disabled on mobile. I can reenable them if someone wants.
> Restyle Testnet page

- frontend/website/src/CryptoAppsSection.re
> Terminal is better now

- frontend/website/src/Blog.re
- frontend/website/src/CryptoAppsSection.re
- frontend/website/src/GetInvolvedSection.re
- frontend/website/src/Home.re
- frontend/website/src/InclusiveSection.re
- frontend/website/src/Links.re
- frontend/website/src/Nav.re
- frontend/website/src/Render.re
- frontend/website/src/SideText.re
- frontend/website/src/SustainableSection.re
- frontend/website/src/Testnet.re
TODO: Brad to updated form link to make a different one for compress the
blockchain and participate in consensus
> Lots of links in place

- src/lib/ppx_coda/versioned.ml
For versioned types, generate
```
let version = n
```
when the type is declared within the `Vn` module path.
I've verified that the let-binding appears in the preprocessed output.
Checklist:
> Generate version number declaration

- frontend/website/src/HeroSection.re
- frontend/website/src/Nav.re
- frontend/website/src/Wrapped.re
> Cols to-spec for hero and nav

- frontend/website/src/CryptoAppsSection.re
- frontend/website/src/Style.re
Re-align the cryptoapps section with the grid (and the next section).
TODO: The dreaded sustainable section
> Realign cryptoapps section

- frontend/website/src/SustainableSection.re
The text is aligned vertically with the other sections, but the chart is
not centered entirely properly. Hopefully this looks decent still.
> Acceptable sustainable section

- frontend/website/src/Nav.re
> Slightly push signup button

- frontend/website/src/Head.re
> Point to staging social image for now

- frontend/website/static/favicon-16x16.png
- frontend/website/static/favicon-32x32.png
> Get those favicons in

- frontend/website/src/GetInvolvedSection.re
- frontend/website/src/SustainableSection.re
- frontend/website/src/Svg.re
- frontend/website/static/img/chart-blockchain-energy.svg
I needed to adjust a few styles to get it to look good with the inline svg, unfortunately we lost the ability to scale the charts when it gets to mobile, but I think it looks good at the fixed size anyway.
> Tooltip on sustainable

- frontend/website/src/Blog.re
- frontend/website/src/BlogPost.re
- frontend/website/src/GetInvolvedSection.re
- frontend/website/src/Style.re
Also
- Fix knowledge base
- CSS reset border padding stuff
- Center blog
- Use IBM Plex on blog posts
> Revamp blog index

- frontend/website/package-lock.json
- frontend/website/package.json
- frontend/website/src/Blog.re
- frontend/website/src/Careers.re
- frontend/website/src/Head.re
- frontend/website/src/Home.re
- frontend/website/src/Image.re
- frontend/website/src/InvestorsSection.re
- frontend/website/src/Links.re
- frontend/website/src/Markdown.re
- frontend/website/src/Render.re
- frontend/website/src/Svg.re
- frontend/website/src/TeamSection.re
- frontend/website/src/filter.js
When you render with prod, we try to load assets from the CDN:
I did an exhaustivity search by visiting the pages and making sure the assets didn't load anywhere. I'll go ahead and upload the CDN assets for real after this lands.
> Links optionally CDN

- frontend/website/src/SustainableSection.re
- frontend/website/static/img/chart-blockchain-energy.svg
- frontend/website/static/img/chart-blockchain-size.svg
Copy taken from below:
```
(1)
Calculations assume 1M accounts and growing with an increasing rate of transactions 
(2)
Calculations use typical transaction costs for consensus and adding transactions to the protocol databse
For Coda: energy use required by Coda for consensus plus snarking transactions for a year at 100tps
For PoW: energy use required for mining by a successful PoW cryptocurrency for a year (numbers taken from bitcoin)
```
> Update tooltip copy to newest

- frontend/website/src/CryptoAppsSection.re
- frontend/website/src/GetInvolvedSection.re
- frontend/website/src/HeroSection.re
- frontend/website/src/InclusiveSection.re
- frontend/website/src/SideText.re
- frontend/website/src/Style.re
- frontend/website/src/SustainableSection.re
I made a little DSL for specifying boldness in the sidetext thing also.
> New copy everywhere

- frontend/website/src/Render.re
> Added the rest of the positions

- frontend/website/src/Nav.re
- frontend/website/src/Page.re
- frontend/website/src/Style.re
> Don't shift nav up until status-lift crosses

- frontend/website/src/Blog.re
- frontend/website/src/GetInvolvedSection.re
- frontend/website/src/Grid.re
- frontend/website/src/Markdown.re
- frontend/website/src/Nav.re
Also:
- Remove some unneeded unsafe rules
> Fix menu zindex

- frontend/website/src/GetInvolvedSection.re
- frontend/website/src/SideText.re
> Fix regressions with the `p` reset

- frontend/website/src/Blog.re
- frontend/website/src/Careers.re
- frontend/website/src/Code.re
- frontend/website/src/GetInvolvedSection.re
- frontend/website/src/HeroSection.re
- frontend/website/src/Home.re
- frontend/website/src/Page.re
- frontend/website/src/Testnet.re
Crazy vertical whitespace clean spree.
> Cleanup the vertical whitespace everywhere

- frontend/website/src/Blog.re
- frontend/website/src/GetInvolvedSection.re
- frontend/website/src/Nav.re
Also:
- Improve menu (below)
- Fix some Get Involved alignment issues
- Fix blog index gradient on safari
Also improved menu:
> Add collapse to knowledgebase

- src/lib/coda_base/staged_ledger_hash.ml
> Pending coinbase aux to and from base64 

- frontend/website/src/Careers.re
- frontend/website/src/InclusiveSection.re
- frontend/website/src/Page.re
- frontend/website/src/Testnet.re
- frontend/website/static/img/chart-blockchain-size.svg
1. Careers page whitespace after images
2. Careers page link color
3. Testnet status font
4. Chart being wrong size on mobile
5. Inclusive figure not centering on mobile
6. Nav being too high up on mobile
> Knockout the small things

- frontend/website/src/CryptoAppsSection.re
- frontend/website/src/HeroSection.re
- frontend/website/src/InclusiveSection.re
- frontend/website/src/SustainableSection.re
> Many copy changes

- frontend/website/src/GetInvolvedSection.re
- frontend/website/src/InvestorsSection.re
- frontend/website/src/Render.re
- frontend/website/src/Style.re
- frontend/website/src/TeamSection.re
> Add view-all buttons to team section

- Makefile
Previous attempt was invalid Makefile.
> trivial: proper syntax for or in makefile

- .gitattributes
- frontend/website/src/Blog.re
- frontend/website/src/CryptoAppsSection.re
- frontend/website/src/HeroSection.re
- frontend/website/src/Page.re
- frontend/website/src/Testnet.re
- frontend/website/static/img/chart-blockchain-energy.svg
- frontend/website/static/img/chart-blockchain-size.svg
- frontend/website/static/presskit.zip
1. "enabling ..." bold in hero
2. "Build apps and games" copy changes
3.  Fade-out half as tall on blog index page
4.  HIDE THE ORANGE CRAP
5.  Nix the corporation on the O(1) labs
6.  Re-export charts
7.  Press kit link in the footer
> The easy pass through the last todos

- frontend/website/.gitignore
- frontend/website/src/Blog.re
- frontend/website/src/Code.re
- frontend/website/src/InvestorsSection.re
- frontend/website/src/Style.re
- frontend/website/src/TeamSection.re
- frontend/website/static/font/PragmataPro.zip
also
- default margin for <p>
- add woff pragmata font
> Many IE and Edge fixes

- src/lib/genesis_ledger/testnet_postake_ledger_many_proposers.ml
make 50 high balance accounts for many_proposer profile
> trivial:let many=50

- scripts/test.py
> Typo successfull -> successful

- frontend/website/src/BlogPost.re
- frontend/website/src/CareerPost.re
Plus better job pages
Not enough internet at airport to post screenshots, but rest assured that it's nice.
> Better margin on blog post mobile / desktop

- frontend/website/package.json
> Decrypt-ci shortcircuits if no creds

- frontend/website/firebase.json
Tested on staging https://coda-staging-84430.firebaseapp.com/snarks
> Redirect codaprotocol.com/snarks for izzy's talk

- frontend/website/firebase.json
Tested on staging. (already deployed)
> Update snark link form

- src/app/cli/src/client.ml
This is a minor refactor that makes use of the `Args` module in `src/app/cli/client.ml` and cleans up the code a little bit.
Checklist:
> Simplify applicative expressions

- src/app/cli/src/prover.ml
- src/lib/coda_base/pending_coinbase_witness.ml
> Versioned pending coinbase witness

- src/lib/coda_base/snark_transition.ml
- src/lib/consensus/dune
- src/lib/consensus/intf.ml
- src/lib/consensus/proof_of_signature.ml
- src/lib/consensus/proof_of_stake.ml
- src/lib/transition_frontier_persistence/diff_mutant.ml
- src/lib/with_hash/dune
- src/lib/with_hash/with_hash.ml
- src/protocols/coda_pow.ml
yet.
Checklist:
Closes #0000
Closes #0000
> Versioning Proof of Stake/ Proof Of Signature

- frontend/wallet/src/Footer.re
- frontend/wallet/src/Page.re
- frontend/wallet/src/StyleGuide.re
- frontend/wallet/src/Tc.re
- frontend/wallet/src/bindings.re
Footer reads data and does most of the logic, needs styling
> Stick footer in place, no style

- frontend/wallet/.gitignore
- frontend/wallet/package-lock.json
- frontend/wallet/package.json
Scaffolding in place for distribution builds. MacOS app/dmg files are
successfully created with `npm run dist`, but the app crashes on
startup.
When this fully works, we'll add it to CI
> Scaffold dist builds

- src/lib/coda_numbers/nat.ml
- src/lib/coda_numbers/nat.mli
- src/lib/consensus/proof_of_stake.ml
This adds the min-epoch length tracking and consensus rule
> Min epoch length consensus rule

- src/lib/daemon_rpcs/daemon_rpcs.ml
- src/lib/snark_worker_lib/worker.ml
- keep snark worker silent when there's no work to be done
- add a return and tab before Total line in text histograms
> TRIVIAL: two simple cosmetic changes (snark worker and histograms)

- scripts/getkeys.sh
don't require json params for PV keys
> TRIVIAL: check for json params

- frontend/wallet/src/Body.re
- frontend/wallet/src/Page.re
- frontend/wallet/src/SettingsRenderer.re
- frontend/wallet/src/StyleGuide.re
- frontend/wallet/src/WalletItem.re
Reducer component for the wallet item as the state complexity was starting to build up. Logic for updating wallet names is real now:
> Settings pane uses real settings

- src/app/website/jobs/engineering-manager.markdown
yet.
Checklist:
Closes #0000
Closes #0000
> Removed functional programming requirement for Engineering Manager

- src/lib/gossip_net/gossip_net.ml
Fix for the failure caused because of entries not found in the `connections` hashtbl in `Gossip_net`
Another possible race condition: when an address is looked up after it gets removed due to a ban
Checklist:
> fix gossip_net failure

- src/app/cli/src/graphql.ml
- src/lib/transition_frontier/transition_frontier.ml
- src/protocols/coda_transition_frontier.ml
> We can now subscribe on payments

- src/app/cli/src/prover.ml
- src/app/cli/src/verifier.ml
- src/lib/coda_base/block_time.mli
- src/lib/coda_networking/coda_networking.ml
- src/lib/consensus/constants.mli
- src/lib/consensus/proof_of_stake.mli
- src/lib/transaction_snark/transaction_snark.ml
- src/protocols/coda_pow.ml
> Remove unused config.mlh imports

- .mergify.yml
- scripts/test.py
adjust mergify rules to not require catchup
> trivial:no catchup

- src/lib/secrets/keypair.ml
> Put a newline in public key files

- src/lib/coda_networking/coda_networking.ml
Move `Made_request` trust system actions to where the node receives a request.
> Move Made_request actions to locus of receipt

- src/lib/blockchain_snark/blockchain.ml
- src/lib/blockchain_snark/blockchain.mli
- src/lib/consensus/intf.ml
- src/lib/prover/prover.ml
This PR has the prover process print out the input which caused it to fail when it does fail. It also will remain running rather than crashing as before.
> Prover prints on error

- frontend/wallet/__tests__/wallet_test.re
- frontend/wallet/package-lock.json
- frontend/wallet/package.json
- frontend/wallet/src/common/Messages.re
- frontend/wallet/src/common/Route.re
- frontend/wallet/src/common/Settings.re
- frontend/wallet/src/common/Settings.rei
- frontend/wallet/src/common/Single.re
- frontend/wallet/src/common/Tc.re
- frontend/wallet/src/main/App.re
- frontend/wallet/src/main/AppTray.re
- frontend/wallet/src/main/AppWindow.re
- frontend/wallet/src/main/Application.re
- frontend/wallet/src/main/ProjectRoot.re
- frontend/wallet/src/main/SettingsMain.re
- frontend/wallet/src/main/SettingsMain.rei
- frontend/wallet/src/render/Body.re
- frontend/wallet/src/render/Footer.re
- frontend/wallet/src/render/MainCommunication.re
- frontend/wallet/src/render/MainCommunication.rei
- frontend/wallet/src/render/Modal.re
- frontend/wallet/src/render/Page.re
- frontend/wallet/src/render/Preload.re
- frontend/wallet/src/render/SettingsRenderer.re
- frontend/wallet/src/render/WalletItem.re
Tested by making sure the application still runs and uses settings
properly.
> Settings coming from render process

- src/lib/gossip_net/gossip_net.ml
- src/lib/trust_system/trust_system.ml
Invoke trust system in TCP server handshake error handler.
> Incoming handshake error invokes trust system

- frontend/website/src/AnnouncementBar.re
- src/app/website/posts/snark-challenge.markdown
Adding the SNARK challenge blog post to our website
> add snark challenge post

- frontend/wallet/src/render/Theme.re
- frontend/wallet/src/render/components/Button.re
- frontend/wallet/src/render/components/Footer.re
- frontend/wallet/src/render/components/Pill.re
- frontend/wallet/src/render/components/TransactionCell.re
- frontend/wallet/src/render/components/WalletItem.re
Adds all the different button styles as a `Button` component.
> Wallet: Better button styles

- frontend/wallet/src/render/Theme.re
- frontend/wallet/src/render/components/Button.re
- frontend/wallet/src/render/components/Footer.re
- frontend/wallet/src/render/components/TransactionCell.re
- frontend/wallet/src/render/components/TransactionsView.re
- frontend/wallet/src/render/components/WalletItem.re
When we deal with the scroll bar properly, everything will be aligned
and look like the spec.
According to the design system document we have different variants of
Body text (regular, small, etc). Thus, Body is an inner module of Text
now.
I used padding2 and marginLeft instead of custom paddingLeft and
paddingRight as padding should always be symetric for better composition
and refactoring. See https://pinterest.github.io/gestalt/#/Box (padding)
and https://basscss.com/v7/docs/white-space/ for more.
> Beautiful time in the transaction cells.

- frontend/wallet/src/render/Theme.re
- frontend/wallet/src/render/components/AddWalletModal.re
- frontend/wallet/src/render/components/Modal.re
- frontend/wallet/src/render/components/SideBar.re
- frontend/wallet/src/render/components/Window.re
- Add title to modal
- Use new buttons in add-wallet modal, make text editable
- Make add-wallet its own component
> Improve add-wallet modal

- src/lib/transaction_pool/indexed_pool.ml
> txpool: better error message on assertion failure

- frontend/wallet/schema.graphql
- frontend/wallet/src/main/App.re
- frontend/wallet/src/render/components/Footer.re
- frontend/wallet/src/render/components/SideBar.re
extensively integration tested using eyes
> Better transaction design in graphql schema

- frontend/website/src/Head.re
- frontend/website/src/Render.re
- frontend/website/src/Style.re
> Website: Remove fonts hack to improve performance

- CODEOWNERS
Pranay on docs,
.circleci covered by Joel and I
> Carey owns frontend stuff + tweaks

- src/lib/trust_system/peer_trust.ml
- src/lib/trust_system/peer_trust.mli
Added a pipe of recorded trust actions for testing purposes, also cleaned up the signatures and fixed a comment.
> Trust action pipe

- .circleci/config.yml
- .circleci/config.yml.jinja
This alters the unittest runs to support capturing coredumps and storing as a build artifact.
> capturing and storing coredumps

- frontend/wallet/package.json
- frontend/wallet/src/main/App.re
- frontend/wallet/src/render/Apollo.re
- frontend/wallet/src/render/components/Header.re
- frontend/wallet/yarn.lock
Also adds some ability to auto-repeat requests that failed due to network error (i.e. server not running yet). This resulted in some rethinking of how we're working with subscriptions.
>  Wallet: Fix faker in dist build

- src/app/cli/src/coda_commands.ml
- src/app/cli/src/coda_delegation_test.ml
- src/app/cli/src/coda_inputs.ml
- src/app/cli/src/coda_worker.ml
- src/app/cli/src/coda_worker_testnet.ml
- src/app/cli/src/graphql.ml
- src/lib/auxiliary_database/external_transition_database.ml
- src/lib/auxiliary_database/external_transition_database.mli
- src/lib/auxiliary_database/filtered_external_transition.ml
- src/lib/auxiliary_database/intf.ml
- src/lib/coda_base/user_command.ml
- src/lib/coda_base/user_command_intf.ml
- src/lib/coda_incremental/coda_incremental.ml
- src/lib/coda_lib/coda_lib.ml
- src/lib/coda_lib/coda_subscriptions.ml
- src/lib/coda_lib/intf.ml
- src/lib/pipe_lib/strict_pipe.ml
- src/lib/pipe_lib/strict_pipe.mli
- src/lib/proposer/proposer.ml
- Changed coda_worker_testnet api to use block subscription service
Refactored code to use new service and it works!
Checklist:
Closes #0000
Closes #0000
> Created block subscription service

- frontend/wallet/src/render/components/Toggle.re
- frontend/wallet/src/render/components/TransactionsView.re
PTAL @figitaki @Schmavery 
Adds the alert box for no txns
> [Wallet] Wallet with no txns view

- src/lib/staged_ledger/dune
Remove `flags` clause with `warn-error` for `Staged_ledger`.
> Staged_ledger, remove warn-error

- .circleci/config.yml
- scripts/test.py
- src/app/cli/src/transaction_snark_profiler.ml
This fixes a bug in the transaction SNARK profiler. It was not providing the correct coinbase state.
> Fix transaction snark profiler

- frontend/website/package.json
- frontend/website/src/InvestorsSection.re
- frontend/website/src/Links.re
- frontend/website/src/Render.re
- frontend/website/src/Style.re
- frontend/website/src/TeamSection.re
- frontend/website/src/Testnet.re
Staging: https://coda-staging-84430.firebaseapp.com/testnet.html
> Website: Fix broken testnet page

- src/app/cli/src/graphql.ml
- src/lib/network_pool/transaction_pool.ml
- src/lib/transition_frontier/diff.ml
Violated invariants fixed in transaction pool tests, reorg calculated
properly, and fixed documentation in GraphQL.
Fixes #2674
> Reorg bool computed properly, and other minutia

- src/app/cli/src/graphql.ml
Add GraphQL entry point for `reset-trust-status`.
If this is OK, I'll add entry points for `get-trust-status` and `get-trust-status-all`.
> Reset trust status via GraphQL

- src/app/cli/src/graphql.ml
Exposes GraphQL endpoints for getting trust status for a particular IP address, and for all peers known to the trust system.
Note: there's no round and filtering of zero-score values here, as we have in the CLI `get-trust-status-all`.
> Get trust status via GraphQL

- frontend/wallet/package.json
- frontend/wallet/schema.graphql
- frontend/wallet/src/render/CodaProcess.re
- frontend/wallet/src/render/ReactApp.re
- frontend/wallet/src/render/Router.re
- frontend/wallet/src/render/components/SideBar.re
- frontend/wallet/src/render/components/TextField.re
- frontend/wallet/src/render/views/settings/NetworkDropdown.re
- frontend/wallet/src/render/views/settings/WalletSettings.re
- frontend/wallet/src/render/views/walletlist/WalletList.re
- src/app/cli/src/graphql.ml
- Fix wallet query (mostly)
- Simplify top-level reducer (greatly)
- Make the `yarn dev` script kick off faker by default and add a `dev-real` script
- Hook up secret key path
- Fix bug in network selector
- Move getWallets into walletList
> Wallet: Fix wallet query and others

- .circleci/config.yml
- .circleci/config.yml.jinja
- scripts/macos-setup.sh
> [CI] re-added macos build job, releases to artifactory every build

- src/app/cli/src/coda_run.ml
Closes #2656
Co-authored-by: @psteckler
> Shutdown daemon on Ctrl-c

- src/app/cli/src/client.ml
Pretty similar to send-payment, adds a `coda client` command to change current delegate
> Change delegate in cli

- frontend/website/jobs/senior-designer.markdown
- frontend/website/src/Render.re
> Add senior designer position

- src/lib/transition_handler/validator.ml
- src/lib/transition_router/initial_validator.ml
> Invoke trust system in transition gossip and improve logging

- frontend/website/jobs/senior-designer.markdown
- frontend/website/src/CareerPost.re
Making the fixes that were approved on discord. Putting this out for approval before deployment.
Also contains a small markup fix to make the left side of the bullets align with the rest of the text.
> Fixes to designer description

- src/app/cli/src/coda.ml
- src/app/cli/src/coda_run.ml
- src/app/cli/src/coda_worker.ml
Fixed a dep cycle with a ref (you were right @cmr ), and made a decent message.
TODO Later: Clean up copy + make an issue template
> Handle crashes first pass

- src/lib/lite_params/gen/gen.ml
> Don't encode/decode pedersen_params

- .circleci/config.yml
- .circleci/config.yml.jinja
This seems to be failing in all the CI builds until we resolve the artifactory situation.
> Temporarily disable artifactory publish step

- frontend/website/jobs/engineering-manager.markdown
- frontend/website/src/Render.re
> Add back the Engineering Manager job

- frontend/website/jobs/frontend-engineer.markdown
- frontend/website/jobs/senior-frontend-engineer.markdown
Some small changes to product engineering job descriptions to make it more readable/approachable.
Lmk if you have any objections
> Website: Update product eng job description

- .circleci/config.yml
- .circleci/config.yml.jinja
- Makefile
- scripts/publish-macos.sh
Consolidated the MacOS publish commands into a script
> [FIX] Added publish script for the MacOS Build #2827

- src/app/cli/src/coda_worker_testnet.ml
- src/lib/pipe_lib/strict_pipe.ml
- src/lib/transition_handler/processor.ml
Minor cleanup/clarification of log message for three files. Checked the corresponding boxes in #2873.
> Some log message cleanup

- src/lib/bootstrap_controller/bootstrap_controller.ml
- src/lib/prover/prover.ml
minor changes in `bootstrap_controller.ml` and `prover.ml`
> log message cleanup

- src/config/testnet_postake_medium_curves.mlh
Testing future genesis, this commit corresponds with a mock pre-release.
> Medium Curves Future Genesis Time: 2019-07-16 00:00:00-08:00

- src/config/testnet_postake_medium_curves.mlh
> testnet_postake_medium_curves future genesis 2019-07-17 12:00:00-07:00

- src/app/cli/src/coda.ml
- src/app/cli/src/coda_commands.ml
- src/app/cli/src/coda_run.ml
- src/app/cli/src/coda_worker.ml
- src/lib/cached/cached.ml
- src/lib/coda_networking/coda_networking.ml
- src/lib/consensus/proof_of_stake.ml
- src/lib/kademlia/membership.ml
- src/lib/ledger_catchup/ledger_catchup.ml
- src/lib/network_pool/network_pool_base.ml
- src/lib/proposer/proposer.ml
- src/lib/root_prover/root_prover.ml
- src/lib/snark_worker/functor.ml
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/syncable_ledger/syncable_ledger.ml
- src/lib/transition_frontier/transition_frontier.ml
- src/lib/transition_handler/catchup_scheduler.ml
Moved some to debug/trace, the ones that remained ensured they were nice
and consistent
> Info logging auditted

- src/lib/coda_lib/coda_lib.ml
Checks off another box in #2873
> Clean up log when a block is received out of its window

- src/app/cli/src/coda.ml
Default log level set to INFO+
> Default log level INFO+

- scripts/publish-deb.sh
- scripts/rebuild-deb.sh
fix bug where 2 debs had colliding metadata
> fix 2 deb collision

- src/app/cli/src/client.ml
Checklist:
Closes #0000
Closes #0000
> Quick Fix: add get txn status cli

- src/app/cli/src/web_pipe.ml
- src/lib/blockchain_snark/blockchain_transition.ml
- src/lib/cache_dir/cache_dir.ml
- src/lib/cache_dir/dune
- src/lib/cached/cached.ml
- src/lib/cached/cached.mli
- src/lib/transaction_snark/transaction_snark.ml
> add homebrew install directory for proving key

- src/app/cli/src/coda.ml
- src/app/cli/src/coda_delegation_test.ml
- src/lib/coda_intf/tmp_test_stub_hack.ml
- src/lib/kademlia/membership.ml
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/transition_router/initial_validator.ml
Audited the log messages in some more files.
The remit is to do that for `error` and `warn`, but it proved too tempting to also clean up some other log messages.
> Audit some more logs

- src/config/testnet_postake_medium_curves.mlh
> future genesis 2019-07-19 10:30:00-07:00

- src/lib/cache_lib/cache_lib.ml
- src/lib/coda_base/transition_system.ml
- src/lib/secrets/wallets.ml
Three more files with improved -- I hope -- logger messages.
> Audit some more logger messages

- src/lib/logger/impl.ml
- src/lib/logger/test.ml
> Change log locations

- src/app/cli/src/web_pipe.ml
- src/lib/transition_frontier_persistence/transition_frontier_persistence.ml
- src/lib/transition_handler/breadcrumb_builder.ml
More log message auditing, should be my last batch.
> Another batch log message audits

- src/lib/gossip_net/gossip_net.ml
- src/lib/transition_frontier_controller_tests/test_transition_frontier_persistence.ml
- src/lib/web_client_pipe/web_client_pipe.ml
Logger message cleanup for three files.
> Yet more log message auditing

- src/lib/coda_base/gen/gen.ml
- src/lib/consensus/proof_of_stake.ml
- src/lib/genesis_ledger/functor.ml
- src/lib/genesis_ledger/testnet_postake_ledger.ml
Ask @jkrauska or myself if you need private keys.
> Update testnet_postake_ledger to have real keys

- src/app/cli/src/client.ml
- src/app/cli/src/coda.ml
- src/lib/coda_lib/coda_lib.ml
Co-authored-by: Pranay <o1pranay@users.noreply.github.com>
> Improved logging low hanging fruits

- src/lib/transition_frontier/transition_frontier.ml
> Commit transactions to SNARKed ledger in a batch when moving root

- .circleci/config.yml
- scripts/test.py
- src/app/cli/src/coda.ml
- src/app/cli/src/coda_archive_node_test.ml
- src/app/cli/src/coda_process.ml
- src/app/cli/src/coda_processes.ml
- src/app/cli/src/coda_transitive_peers_test.ml
- src/app/cli/src/coda_worker.ml
- src/app/cli/src/coda_worker_testnet.ml
- src/lib/auxiliary_database/filtered_external_transition.ml
- src/lib/coda_lib/coda_lib.ml
- src/lib/coda_lib/coda_subscriptions.ml
- src/lib/coda_lib/config.ml
Added Archive Node and made it an option to become an archive node on the cli daemon.
Created the integration test coda-archive-node-test to test this feature and it works :)
Checklist:
> Created Archive Node

- src/app/cli/src/client.ml
- src/lib/cli_lib/fee.ml
- src/lib/daemon_rpcs/daemon_rpcs.ml
Default to 5 so snark workers can be 2
Some logging nits
> Logging nits + defaults change

- src/app/cli/src/coda.ml
- src/lib/coda_metrics/coda_metrics.ml
- src/lib/consensus/proof_of_stake.ml
- src/lib/daemon_rpcs/daemon_rpcs.ml
- src/lib/o1trace/o1trace.ml
- src/lib/proposer/proposer.ml
- src/lib/transition_frontier_controller/transition_frontier_controller.ml
- src/lib/transition_router/initial_validator.ml
Also trace_task name is bundled up in here...
> Block producer not proposer

- src/app/cli/src/coda.ml
I'm actually not convinced we should ever be wiping the whole conf dir. At the very least the config files should probably remain.
> do not wipe the config dir quite as eagerly

- src/config/testnet_postake_medium_curves.mlh
In preparation for the testnet
> Future genesis 7/23

- src/lib/coda_lib/coda_lib.ml
In the future we can re-enable with debouncing
> Logs should be pushed to trace

- frontend/website/docs/getting-started.md
- frontend/website/docs/index.md
- frontend/website/docs/my-first-transaction.md
- frontend/website/src/Careers.re
Plus note about echo service swallowing funds
> Link to leaderboard and more on testnet points

- frontend/website/src/CryptoAppsSection.re
- frontend/website/src/Style.re
Realized we weren't loading this font properly. Not sure when that started happening.
Before/after pictures:
> Website: fix pragmatapro font loading

- src/lib/snark_worker/functor.ml
- src/lib/snark_worker/prod.ml
Audit log messages for a couple of files in `lib/snark_worker`.
> Audit log msgs for SNARK workers

- src/lib/coda_lib/coda_lib.ml
This log seems like it needs to be debounced as well.
Closes #2968
> Fix overly-eager bootstrap log message

- src/config/testnet_postake_medium_curves.mlh
- src/lib/trust_system/peer_trust.ml
- src/lib/trust_system/record.ml
- src/lib/trust_system/record.mli
> [DO NOT MERGE]: Trick CI into building release/0.0.1 beta.2

- frontend/website/docs/architecture/lifecycle-payment.md
- frontend/website/docs/getting-started.md
add docs for transaction failure modes
> Add txn failure docs

- frontend/website/src/Docs.re
- frontend/website/src/TeamSection.re
- frontend/website/static/img/janecka.jpg
- frontend/website/static/img/swann.jpg
- frontend/website/static/img/tekişalp.jpg
Adds bios for Carey, Pranay, Connor, and Emre. Also has a few fixes for styles on Firefox.
> Website: add new bios

- src/app/kademlia-haskell/app/Main.hs
On startup, Kademlia looped over the given initial peers, but stopped trying to connect when it successsfully connected to one of them, or the Kademlia instance reported it had at least one peer.
In order to maximize connectivity, it seems better to connect to as many peers as possible. In this PR, there's an attempt to connect to all the given peers. The check for the peer set is done after looping over those peers. 
Mundane change: use `null` to check for empty list, instead of `length`.
> Try to connect to all given peers on Kademlia startup

- scripts/skip_if_only_frontend.sh
Co-authored-by: Pranay o1pranay@users.noreply.github.com
> Skip-if-only-frontend should base off of develop

- .circleci/config.yml
- .circleci/config.yml.jinja
- frontend/website/posts/testnet-beta.markdown
- frontend/website/posts/testnet-retro-1.markdown
Moves over the following posts from medium:
* https://medium.com/codaprotocol/o-1-labs-releases-testnet-beta-for-coda-protocol-the-first-succinct-blockchain-b937eada81a9
* https://medium.com/codaprotocol/coda-protocol-testnet-beta-retrospective-week-1-e8b3ab2de46f
> Website: Copy blog posts from Medium

- src/config/test_postake_medium_curves.mlh
- src/lib/coda_lib/coda_lib.ml
- src/lib/work_selector/intf.ml
- src/lib/work_selector/random.ml
- src/lib/work_selector/sequence.ml
- src/lib/work_selector/test.ml
- src/lib/work_selector/work_lib.ml
Log when snark works are not received within `work-reassignment-wait`
> log snark-work reassignment

- frontend/website/src/Careers.re
Adds a "Relocation package" benefit.
> Website: Add relocation benefit

- src/lib/coda_base/ledger_transfer.ml
- src/lib/coda_lib/coda_lib.ml
- src/lib/transition_frontier_controller_tests/stubs.ml
A brute-force workaround to close #2991
> If ledger transfer fails, delete DB and try again

- src/app/cli/src/coda.ml
Extra daemon boot-time log message, asking users to be patient.
> Boot wait log message

- frontend/website/docs/troubleshooting.md
> update docs copy / formatting

- src/config/testnet_postake_medium_curves.mlh
- src/lib/genesis_ledger/genesis_ledger.ml
- src/lib/genesis_ledger/testnet_medium_rare_ledger.ml
- Added genesis ledger for Testnet `medium-rare`
- Genesis Timestamp: `"2019-08-12 21:00:00-07:00"`
> [Testnet] Genesis Ledger for Testnet medium-rare

- src/config/testnet_postake_medium_curves.mlh
> [Update] updated genesis timestamp testnet_postake_medium_curves

- frontend/website/jobs/cryptography-engineer.markdown
- frontend/website/src/Render.re
> Add cryptography engineer jd

- .circleci/config.yml
- .mergify.yml
- scripts/publish-deb.sh
- scripts/rebuild-deb.sh
- scripts/test.py
- improved bash quotes (shellcheck)
- using release develop for develop builds
> shellcheck and develop repo

- src/app/cli/src/coda.ml
Every 10 minutes, log an `info` message with some OCaml memory statistics.
This may tell us whether the memory leak is in OCaml or in C++.
> Dump OCaml memory stats

- frontend/wallet/.gitignore
- frontend/wallet/README.md
- frontend/wallet/generate-schema.js
- frontend/wallet/package.json
- frontend/wallet/src/main/DaemonProcess.re
Was accidentally printing junk into the schema file. Also needed to make sure it gets generated.
Also updated the daemon to use the globally-installed coda daemon so that we don't need to keep that macos binary up-to-date.
> Fix wallet with faker

- frontend/bot/Dockerfile
- frontend/bot/README.md
- frontend/bot/src/Constants.re
- frontend/bot/src/Graphql.re
Minor edits to the bot, added some environment variables. 
Added a README
CC @Schmavery
> [Bot] added README, minor edits

- src/lib/coda_graphql/coda_graphql.ml
Closes #3304 
Trivial documentation change based on discussion in #3304
> Update GraphQL docs for pooledUserCommands

- frontend/website/docs/coda-testnet.md
- frontend/website/docs/getting-started.md
- frontend/website/docs/my-first-transaction.md
- frontend/website/docs/node-operator.md
- frontend/website/src/Testnet.re
yet.
Checklist:
Closes #0000
Closes #0000
> update leaderboard and docs for week 6

- Makefile
- dockerfiles/Dockerfile-toolchain-libp2p
- src/app/libp2p_helper/build/DEBIAN/control
Builds a libp2p deb in a docker container using nix.
> libp2p deb build flow similar to kademlia

- .circleci/config.yml
- .circleci/config.yml.jinja
- scripts/macos-setup-brew.sh
Snarky needs newer bash
macos doesn't have bash > 3, use brew.
> TRIVIAL: add bash to brew install, confirm versions

- frontend/website/docs/coda-testnet.md
- frontend/website/docs/my-first-transaction.md
- frontend/website/src/Testnet.re
On staging if you'd like to check it out.
Title says all! The copy taken directly from our latest blog post.
> Modify docs for week7 testnet

- src/config/testnet_postake_medium_curves.mlh
> genesis 9/5

- frontend/wallet/src/render/Apollo.re
- frontend/wallet/src/render/CodaProcess.re
Current fix to allow port forwarding to run wallet locally
> Allow manual port forwarding to local daemon

- src/app/cli/src/coda.ml
- src/lib/trust_system/record.ml
> change expiration date to 9/14

- frontend/website/docs/coda-testnet.md
- frontend/website/docs/getting-started.md
- frontend/website/docs/my-first-transaction.md
- frontend/website/docs/node-operator.md
Update docs for new testnet week
> Update for new testnet week

- .mergify.yml
- scripts/test.py
Temporarily as it's looping forever
> Disable wallet build job

- frontend/website/package.json
- frontend/website/serve.json
yet.
Checklist:
Closes #0000
Closes #0000
> add serve.json

- frontend/website/src/Blog.re
- frontend/website/src/Markdown.re
Truncates HTML loaded to Blog page to improve loading speed
> Truncates html in Blog page for faster loading

- README-spacetime.md
HOWTO use spacetime for memory profiling.
> Spacetime doc

- src/app/cli/src/coda.ml
- src/lib/trust_system/peer_trust.ml
- src/lib/trust_system/peer_trust.mli
- src/lib/trust_system/record.ml
- src/lib/trust_system/record.mli
Per discussion in #3395, I think it's fine for this to come out.
> Remove -no-bans

- src/lib/network_pool/dune
- src/lib/network_pool/intf.ml
- src/lib/network_pool/snark_pool.ml
- src/lib/network_pool/snark_pool_diff.ml
- src/lib/one_or_two/one_or_two.ml
- src/lib/one_or_two/one_or_two.mli
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/transaction_snark_work/transaction_snark_work.ml
- src/lib/transaction_snark_work/transaction_snark_work.mli
- src/lib/transition_frontier_controller_tests/stubs.ml
- src/lib/verifier/dummy.ml
> Check snarks before adding it to snark pool

- src/lib/pipe_lib/broadcast_pipe.ml
Hopefully this would solve #3466
> updating the Broadcast_pipe's cache as soon as possible

- src/app/display_public_key/display_public_key.ml
- src/app/display_public_key/dune
- src/display_public_key.opam
This is a utility which prints out the public key corresponding to a given private key.
> utility for displaying public keys

- src/lib/genesis_ledger/testnet_postake_ledger.ml
Converted old priv keys to use new format publics.
Prior work had generated new priv keys -- this uses same old priv keys, but gets new pub representations.
> Trivial: old privs, new pubs

- frontend/bot/package.json
- frontend/bot/src/Coda.re
- frontend/bot/src/Echo.re
- frontend/bot/src/Faucet.re
- frontend/bot/src/Graphql.re
- frontend/bot/src/Repeater.re
- frontend/bot/src/SubscriptionsTransportWS.re
- frontend/bot/yarn.lock
Trying to make sure that bot error messages are 💯for testnet 2.2
> Bot: Update reason-urql version (improve error msgs)

- frontend/bot/src/App.re
- frontend/bot/src/Messages.re
- frontend/bot/src/Status.re
~~Currently written on top of bot/update-reason-urql, will rebase when that PR lands on develop.~~
Adds a $status command to the bot in the style of https://github.com/CodaProtocol/coda-automation/blob/master/services/faucet/tiny.py#L88-L97
cc @yourbuddyconner
> Bot: Add $status command

- frontend/wallet/package.json
- frontend/wallet/src/main/App.re
- frontend/wallet/yarn.lock
For some reason this is disabled by default so we have to do this.
Corresponding bs-electron commit: https://github.com/Schmavery/bs-electron/commit/0cf39124417bc3157b7a675154f591bf6e4b79ba
> Wallet: Enable copy/paste

- frontend/wallet/src/render/AddressBook.re
- frontend/wallet/src/render/contexts/AddressBookProvider.re
Add echo and faucet addresses to the default addressbook (new pubkeys)
> Wallet: Default addressbook

- frontend/website/posts/testnet-press-release.markdown
- frontend/website/posts/testnet-retro-phase-1.markdown
- frontend/website/static/blog/testnet-press-release/testnet-advisors.jpg
- frontend/website/static/blog/testnet-retro-phase-1/block-count.png
- frontend/website/static/blog/testnet-retro-phase-1/twitter-card.jpg
yet.
Checklist:
Closes #0000
Closes #0000
> Add new blogposts

- frontend/website/docs/gui-wallet.md
> Website: Fix Wallet Download Link

- src/lib/kademlia/membership.ml
If two restarts of the helper are run in very close succession, the second one could try to kill the process before the first one's pid has been written to the lock file, causing the daemon to crash with an exception. This change makes sure we write the lock file before returning a `Membership.t`
> Hotfix for race with kademlia lock file

- frontend/website/package.json
- frontend/website/src/Testnet.re
- frontend/website/static/js/leaderboard.js
- frontend/website/yarn.lock
various fixes:
- bumped serve version to get rid of warning
> fix leaderboard stuff

- frontend/website/docs/gui-wallet.md
- frontend/website/static/img/coda-wallet.png
> Website: Update GUI Screenshot

- src/lib/kademlia/membership.ml
We shouldn't crash when restarting the Kademlia helper anymore.
> More robust handling of kademlia helper termination

- src/lib/coda_state/ancestor.ml
Use `[%%versioned` ppx for Ancestor.
> versioned ppx for Ancestor

- src/lib/ppx_coda/versioned_module.ml
> Guard against unused desereialize_binary_opt

- src/lib/kademlia/membership.ml
Should improve robustness a little more.
> Fix race when killing kademlia helper

- src/lib/coda_metrics/coda_metrics.ml
- src/lib/network_pool/snark_pool.ml
> metrics for snark fee

- graphql_schema.json
- src/app/archive/lib/processor.ml
- src/app/cli/src/init/client.ml
- src/app/cli/src/init/graphql_client.ml
- src/app/cli/src/init/graphql_queries.ml
- src/lib/graphql_client_lib/graphql_client_lib.ml
Send the following user command:
```
src/_build/default/app/cli/src/coda.exe client send-payment \        
-amount 10 \
-privkey-path ~/Desktop/develop/priv_key \
-receiver 8Sujg4gUPP7492eU1xvNssEYocSyrRsvEraT5zmWF2GNvZAD7f6EMfjpUEi59rF4qW
```
Then ran the following command:
```
src/_build/default/app/cli/src/coda.exe advanced pooled-user-commands
```
Returned the following:
```
[{"id":"Bf2dBf2D4xJ9h8Fp8MwSXjb3uaByRFi61xv4DXAYPGnTovvHh1u7Rp2fmdKbht9PhfBnKQbS2VqjT2XBLTVnYWbzwNLKxJ68SABdMkj7jVt5QUeS48A92cy5haGgwFxMxXkJeCT46BCW8Yc6kGQxAKr5WAURbpSQ9EuvSr9LDjvpCV6K3YZiLVxpLJbWKNXNrTZd5F2xR4KuQCFjV9kHBMcNwUMdACLFEoNTJpfsF26iTP33z8za5uCJAunJAqcqv3QjcUYbaB4KYvTkgCtwjPfxEThxnVPMPwtGF4y34rBkYHX","isDelegation":false,"nonce":2,"from":"8Sujk2UD4faWu98TzK6zaeMdo3qngi1G8CRrByULiBgEytSb3sAJudxaUPv45thdBg …
```
> Created pooledUserCommands cli command

- frontend/wallet/src/render/components/Button.re
- frontend/wallet/src/render/views/footer/SendModal.re
- frontend/wallet/src/render/views/sidebar/UnlockModal.re
Support keyboard events on forms
> Wallet: Add ability to unlock wallet and send form upon enter key

- src/lib/auxiliary_database/external_transition_database.ml
- src/lib/auxiliary_database/filtered_external_transition.ml
`%%versioned` ppx in `Auxiliary_database`.
> Version ppx in aux db

- frontend/wallet/src/render/views/sidebar/UnlockModal.re
Deletes extra line from previous PR
> whoops! needed to delete extra loading line

- src/lib/staged_ledger_diff/staged_ledger_diff.ml
`%%versioned` for `Staged_ledger_diff`.
> Versioned ppx for Staged_ledger_diff

- src/lib/coda_transition/internal_transition.ml
`%%versioned` for `Internal_transition`.
> Versioned ppx in Internal_transition

- src/lib/transaction_snark/transaction_snark.ml
`%%versioned` for `Transaction_snark`
> Versioned ppx for Transaction_snark

- src/lib/signature_lib/keypair.ml
- src/lib/snark_work_lib/work.ml
`%%versioned` in `Signature_lib.Keypair`, `Snark_work_lib.Work`
> versioned ppx Keypair, Work

- Makefile
Hopefully this stops making dune presume a profile and fixes the CI error.
/cc @jkrauska
> Fix CI error

- frontend/website/src/Testnet.re
Quick fix to update the "Full Dashboard" link to something that has more info.
> Website: Fix testnet stats url

- frontend/website/src/AnnouncementBar.re
> Website: Change Read here to Join Now

- frontend/wallet/src/render/components/Header.re
- graphql_schema.json
- src/app/cli/src/init/graphql_queries.ml
- src/lib/coda_graphql/coda_graphql.ml
- src/lib/coda_lib/coda_lib.ml
- src/lib/snark_worker/functor.ml
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/staged_ledger/staged_ledger.mli
See the code comment for some notes.
> TESTNET HOTFIX: variety of fixes

- frontend/website/docs/getting-started.md
- `TCP` port `8302` and `8303`
yet.
Checklist:
Closes #0000
Closes #0000
> Update Set up port forwarding and any firewalls

- frontend/wallet/src/render/views/onboarding/AccountCreationStep.re
- frontend/wallet/src/render/views/onboarding/CompletionStep.re
- frontend/wallet/src/render/views/onboarding/SetupNodeStep.re
- frontend/wallet/src/render/views/onboarding/WelcomeStep.re
Screenshot of error message prior: 
https://media.discordapp.net/attachments/618907625316417539/637376362918969355/unknown.png
> Fixes warning

- frontend/website/posts/testnet-retro-8.markdown
- frontend/website/src/BlogPost.re
> fix blog post bug

- .mergify.yml
- scripts/test.py
> make holy grail required for CI

- frontend/website/docs/my-first-transaction.md
New seed peers for van helsing risen again
> New seed peers in docs

- src/lib/snark_worker/functor.ml
In `Snark_worker.Functor.main`, there's a loop `go` that requests snark work via an RPC call. If it successfully performs the work, it submits the snark work back via RPC.
If the work submission failed, the code retried the whole sequence. Redoing the snark work is expensive. In this PR, a work submission failure results in a retry of just that RPC. That's achieved by passing a continuation to `log_and_retry`. If the original work request fails, the continuation is `go`. If the work submission fails, the continuation is a new function `submit_work`, which performs the RPC call.
@jkrauska was of the opinion that the 30 seconds in the retry was too long. So now we pass a time to `log_and_retry`. It's 10 seconds in all cases, but we can adjust those times individually if needed.
> Retry submit work

- src/config/testnet_postake_medium_curves.mlh
trivial change for develop networks.
> trivial: bump up daemon_expiry date

- src/lib/gossip_net/gossip_net.ml
> Don't crash if there is no connection limit set

- frontend/wallet/src/render/views/onboarding/AccountCreationStep.re
- frontend/wallet/src/render/views/onboarding/CompletionStep.re
- frontend/wallet/src/render/views/onboarding/SetupNodeStep.re
- frontend/wallet/src/render/views/onboarding/WelcomeStep.re
> Change button colors, add arrow to Discord link

- frontend/website/docs/gui-wallet.md
Made the changes I recall us asking for on this page.
* Beta heading
* tips on port forwarding
* download steps for mac and linux builds
* Pushing folks to #frontend channel for help
> Update docs for Coda Wallet 0.1.1

- src/lib/bootstrap_controller/bootstrap_controller.ml
- src/lib/bootstrap_controller/bootstrap_controller.mli
- src/lib/coda_intf/transition_frontier_components_intf.ml
- src/lib/transition_handler/validator.ml
- src/lib/transition_router/initial_validator.ml
- src/lib/transition_router/transition_router.ml
Delete `Time_received` for transitions passed initial validator
> delete time_received info for transitions passed initial valiator

- graphql_schema.json
- src/lib/coda_graphql/coda_graphql.ml
Simple change
Checklist:
Closes #0000
Closes #0000
> Added reorg subscription

- .circleci/config.yml
- .circleci/config.yml.jinja
- src/config/testnet_postake_medium_curves.mlh
> [DO NOT MERGE] Hotfix/newness

- dockerfiles/Dockerfile-coda-daemon
> [Fix] added tzdata to Dockerfile

- frontend/website/docs/faq.md
- frontend/website/docs/node-operator.md
yet.
Checklist:
Closes #0000
Closes #0000
>  add block explorer to docs

- src/app/cli/src/init/client.ml
- src/app/cli/src/init/coda_run.ml
- src/lib/daemon_rpcs/daemon_rpcs.ml
Ideas for automated tests for this? We could try the bind-a-weird-localhost-IP trick.
> RPCs and cli for modifying the client whitelist

- src/lib/transition_frontier/full_frontier/full_frontier.ml
- src/lib/transition_frontier/full_frontier/full_frontier.mli
- src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
- src/lib/transition_frontier/tests/full_frontier_tests.ml
- src/lib/transition_frontier/transition_frontier.ml
>  Turn off consensus local state check temporarily while loading frontier from persistence

- src/lib/transition_frontier/full_frontier/full_frontier.ml
The new implementation of transition frontier has 1 place which is different from the old implementation. This PR changed it so that the new implementation agrees with the old one:
Notify consensus (which means calling the `frontier_root_transition` hook) before making changes to snarked_ledger.
> switch the order of operations in full_frontier.move_root

- src/config/testnet_postake_medium_curves.mlh
> TRIVIAL:revert to testnet ledger

- src/lib/cli_lib/flag.ml
Set the correct default rest port
Checklist:
Closes #4064
> Set default rest port

- frontend/website/jobs/protocol-reliability-engineer.markdown
- frontend/website/src/Render.re
Looks like it's added properly
> Add job post for PRE

- src/lib/coda_base/account.ml
Use conditional compilation in `Account` to support nonconsensus nodes.
> Account, conditional compilation for nonconsensus

- src/lib/verifier/prod.ml
The nonconsensus RFC says we'll do verification in nonconsensus nodes.
So do conditional compilation for `Verifier`.
> Verifier, conditional compile

- src/external/ocaml-rocksdb/rocks_linker_flags_gen.ml
Thanks @psteckler and @cmr's, we fixed RocksDB build on Mac! Now we could run unit test for RocksDB on Mac.
> fixed rocksdb build for mac

- frontend/website2/next.config.js
- frontend/website2/package.json
- frontend/website2/yarn.lock
- netlify.toml
Add a netlify config file and some small website2 changes necessary to start deploying.
This should only run a deploy when the frontend/website2 directory changes.
> Website2: add netlify

- frontend/website2/package.json
- frontend/website2/pages/_app.js
- frontend/website2/yarn.lock
Adds a Google Tag Manager to enable Google Analytics.
> Website2: Add Analytics Tag

- .gitmodules
Testing netlify deploy with https submodules
> Use https links in git submodules

- .circleci/config.yml
- .circleci/config.yml.jinja
- Makefile
> generate 10k ledger

- src/lib/staged_ledger/staged_ledger.ml
yet.
Checklist:
Closes #0000
Closes #0000
> log txn count before diff creation

- frontend/website2/pages/docs/architecture/consensus.mdx
- frontend/website2/pages/docs/architecture/index.mdx
- frontend/website2/pages/docs/architecture/lifecycle-payment-technical.mdx
- frontend/website2/pages/docs/architecture/lifecycle-payment.mdx
- frontend/website2/pages/docs/architecture/proof-of-stake.mdx
- frontend/website2/pages/docs/cli-reference.mdx
- frontend/website2/pages/docs/contributing.mdx
- frontend/website2/pages/docs/developers/code-reviews.mdx
- frontend/website2/pages/docs/developers/codebase-overview.mdx
- frontend/website2/pages/docs/developers/directory-structure.mdx
- frontend/website2/pages/docs/developers/graphql-api.mdx
- frontend/website2/pages/docs/developers/style-guide.mdx
- frontend/website2/pages/docs/faq.mdx
- frontend/website2/pages/docs/glossary.mdx
- frontend/website2/pages/docs/gui-wallet.mdx
- frontend/website2/pages/docs/snarks/constructions.mdx
- frontend/website2/pages/docs/snarks/index.mdx
- frontend/website2/pages/docs/snarks/snarky-universe.mdx
- frontend/website2/pages/docs/snarks/snarky.mdx
- frontend/website2/pages/docs/snarks/snarkyjs-crypto.mdx
- frontend/website2/pages/docs/troubleshooting.mdx
Changes made include TODO is missing logic to make youtube player go to certain timestamps. Also, found missing styles for this section about SNARKs:
> Add docs files

- frontend/website2/pages/_app.js
- frontend/website2/src/components/AnnouncementBar.re
- frontend/website2/src/components/GetInvolvedSection.re
- frontend/website2/src/components/Nav.re
- frontend/website2/src/components/TeamSection.re
- frontend/website2/src/components/Terminal.re
- frontend/website2/src/pages/Careers.re
- frontend/website2/src/pages/Docs.re
- frontend/website2/src/pages/Testnet.re
- Add the edit button
- Fix all warnings
- Fix google tag manager id
- Small amount of code cleanup (moving a couple styles from being inline to the Style module)
> Website2: Add docs edit link, fix warnings

- frontend/website2/bsconfig.json
- frontend/website2/next.config.js
- frontend/website2/package.json
- frontend/website2/pages/about.js
- frontend/website2/src/components/NewsletterWidget.re
- frontend/website2/src/pages/About.re
> Add subscribe widget

- src/config/txpool_size.mlh
Increase txn pool from 300 to 3000
> trivial: txn_pool 300->3000

- frontend/website2/next.config.js
- frontend/website2/package.json
- frontend/website2/src/components/DocsComponents.re
- frontend/website2/yarn.lock
Slightly scary direct manipulation of children to inject a styled header link but it seems to work out.
Second commit removes the requirement of the Wrap functor to be passed a classname, not sure why I had that.
> Website2: Add header links to docs

- frontend/website/static/img/genesisHero@2x.png
- frontend/website/static/img/genesisHero@3x.png
- frontend/website/static/img/genesishero.png
- frontend/website2/src/components/Page.re
- frontend/website2/src/pages/Genesis.re
- frontend/website2/src/pages/Index.re
- Hero image swap 
- Social preview copy (TO GET: image) 
- Mobile homepage disable horizontal scroll (for now, the image is a bit cut off and hard to fix because the three images have different maxWidth percentages and those will need to be adjusted individually. if we can get the image to be flattened to one image, should be an easy fix)
> Website nits

- frontend/website2/src/components/AnnouncementBar.re
- frontend/website2/src/components/Nav.re
> change announcement bar to genesis page

- frontend/website2/pages/docs/getting-started.mdx
yet.
Checklist:
Closes #0000
Closes #0000
> reduce memory reqs

- frontend/website2/pages/docs/getting-started.mdx
yet.
Fixed typo: changed tempporarily to temporarily.
N/A
Checklist:
Closes #0000
Closes #0000
> Fix typos: tempporarily -> temporarily & cantidate -> candidate

- frontend/website2/package.json
- frontend/website2/pages/docs/getting-started.mdx
- frontend/website2/src/Theme.re
- frontend/website2/src/components/Alert.re
yet.
Checklist:
Closes #0000
Closes #0000
> update docs for genesis program applicants

- README.md
yet.
Checklist:
Closes #0000
Closes #0000
> Coda logo in README 

- frontend/website/src/components/StepButton.re
- frontend/website/src/pages/Genesis.re
> Bold the step number

- src/lib/base58_check/base58_check.ml
There's a pair of nested loops in the `coda_base58` library, such that encoding and decoding run in time `O(n^2)`.
In this PR, attempting to base58-encode a string longer than 8k results in failure.
AFAIK, the strings we encode are of fixed-length, so we shouldn't see this failure unexpectedly.
Closes #4236.
> Limit length of base58check inputs

- frontend/website/src/components/Challenges.re
yet.
Checklist:
Closes #0000
Closes #0000
> remove "no active testnet" header

- src/app/cli/src/coda.ml
- src/app/cli/src/init/client.ml
Cherrypick 780434d (containing client2->client changes) to 11-beta5-redux
> [Cherrypick] CLI: promote client2 to client (#4151)

- frontend/website/src/components/Page.re
Changes press kit link in footer to zip file uploaded to AWS
> Add press kit from aws

- frontend/website/pages/docs/getting-started.mdx
- frontend/website/pages/docs/my-first-transaction.mdx
- frontend/website/pages/docs/node-operator.mdx
This is a first attempt at cleaning up the docs for the redux release. Feel free to commit directly to this branch with any changes.
> Modifies docs for the phase3 redux release

- README-dev.md
- frontend/website/pages/docs/getting-started.mdx
- frontend/website/pages/docs/my-first-transaction.mdx
- frontend/website/pages/docs/node-operator.mdx
- frontend/website/pages/docs/troubleshooting.mdx
yet.
Checklist:
Closes #0000
Closes #0000
> E2E docs audit

- frontend/website/pages/docs/getting-started.mdx
Update intro to getting-started page.
> Add Feb 14th info to docs

- frontend/website/pages/docs/my-first-transaction.mdx
- frontend/website/src/components/Alert.re
yet.
Checklist:
Closes #0000
Closes #0000
> Add status page to docs

- src/lib/coda_metrics/coda_metrics.ml
- src/lib/transition_router/initial_validator.ml
- src/lib/transition_router/transition_router.ml
The code that update `max_blocklength_observed` was accidentally got deleted. And this PR fixed that.
> fix max_blocklength_observed

- frontend/website/src/components/Challenges.re
- frontend/website/src/pages/Testnet.re
Updates for latest announcement
> Updates for testnet page

- frontend/website/lambdas/sendgrid-subscription/handler.js
Updates the newsletter widget lambdas to use the new Sendgrid API's.
> Website: Update Newsletter Widget

- frontend/website/src/pages/BlogPost.re
Still need to work on centering the text, but this is what I have so far! 
Before: 
After:
> img captions, add grey and font size

- frontend/website/README.md
yet.
I updated the readme in the website directory for more clarity.
I did not need to test anything, was just text.
Checklist:
> Added git-lfs instructions to README.md

- src/lib/coda_base/gen/gen.ml
`Coda_base.Gen` had its own code to generate private keys. In #4458, I noted that there can be duplicates.
Here, use the existing `Private_key.gen`, which should not easily create duplicates. The generated keypairs are still deterministic.
Closes #4509.
> Private_key.gen for sample keypairs

- frontend/website/src/components/StepButton.re
- frontend/website/src/pages/Genesis.re
Pretty self-explanatory
Helps people stay on the site after following the cta, makes sure analytics events get fired without any delay logic
> Website: Genesis links open new tab

- src/lib/ppx_coda/lint_version_syntax.ml
- src/lib/ppx_coda/versioned_type.ml
Add functors `Of_binableN`, for N in {1,2,3} to linter.
> Add Of_binableN functors to linter

- frontend/wallet/src/render/components/HelpButton.re
Got left over from previous PR, from March 6
> Fix the onboarding heading buttons- Chris approved 

- frontend/website/pages/docs/index.mdx
Adds technical and economic whitepaper to docs 
Closes #4600
> Add how does coda work to docs

- frontend/bot/src/CurrencyFormatter.re
This file was missing in #4636
> Add missing file to Coda bots

- frontend/bot/src/Constants.re
Correction to #4636
(That moment when the PR doesn't fix the thing it's supposed to fix)
> Bot: fix second trim issue

- src/app/cli/src/dune.flags.inc
> Remove symlink to nowhere

- src/app/cli/src/tests/coda_receipt_chain_test.ml
- src/app/cli/src/tests/coda_worker_testnet.ml
- src/coda_compile_config_nonconsensus.opam
- src/config/amount_defaults/realistic.mlh
- src/config/amount_defaults/standard.mlh
- src/lib/cli_lib/flag.ml
- src/lib/coda_base/user_command.ml
- src/lib/coda_base/user_command_intf.ml
- src/lib/coda_compile_config/coda_compile_config.ml
- src/lib/coda_graphql/coda_graphql.ml
- src/nonconsensus/coda_base/dune
- src/nonconsensus/coda_compile_config/coda_compile_config.ml
- src/nonconsensus/coda_compile_config/dune
> Minimum fees don't use hardcoded billions

- scripts/run-demo.sh
Thanks to @garethtdavies for flagging this on discord (and testing the fix)! 😄 
@nholland94 @bkase Can we remove the -demo-container flag now?
Co-authored-by: garethtdavies <hello@garethtdavies.com>
> Add -seed flag to demo container

- src/app/cli/src/coda.ml
- src/app/cli/src/init/client.ml
- src/app/cli/src/init/coda_run.ml
- src/lib/cli_lib/arg_type.ml
- src/lib/daemon_rpcs/daemon_rpcs.ml
Enables reasonable SNARK coordination in k8s.
> replace trustlist IPs with cidrs

- docs/daemon.md
- src/app/cli/src/coda.ml
#4676 requested an environment variable for this, here it is
> add and document CODA_CLIENT_TRUSTLIST env var

- dockerfiles/Dockerfile-coda-demo
Sets demo container to 66,000 tokens.
Will confirm it works, by running the container that CI builds
> Uses more tokens in demo

- frontend/website/pages/docs/developers/sandbox-container.mdx
- frontend/website/pages/docs/getting-started.mdx
- frontend/website/pages/docs/gui-wallet.mdx
- frontend/website/src/components/DocsSideNav.re
Makes some changes to the docs in preparation for the 3.2 release.
* Add some more instructions to the installation section for the GUI Wallet
* Add Getting Started instructions for the demo container
* Add notes specific for the Phase 3.2 launch
* *TODO* Update the demo.md readme with up to date information
> Docs: Update GUI Wallet Docs for 3.2

- frontend/website/pages/docs/node-operator.mdx
Adds a note re coinbase elsewhere inside docs
> Adds coinbase elsewhere docs

- frontend/website/src/pages/Testnet.re
a quick link change here to link to the forums 3.2 challenges
> Updates link on Testnet page to testnet challenges for 3.2

- .circleci/config.yml
- .circleci/config.yml.jinja
- scripts/archive/build-release-archives.sh
- scripts/macos-portable.sh
* build-macos job referred to apple signing env vars
* build-archive job tried to push to dockerhub
Testing by running through CI now
> Fixes builds from forks

- CODEOWNERS
It many cases it was obvious which group to use for which folder
> Rewrites CODEOWNERS for #4743

- scripts/pin-external-packages.sh
> Replace typo package -> submodule

- frontend/points-hack-april20/lib.js
Adds public key to subscription to grab creator of the block
> Leaderboard: Add public key in subscription

- src/lib/perf_histograms/rpc.ml
In `Decorate_bin_io`, disambiguate the names for reading and writing responses.
Not sure if anything in Prometheus needs to accommodate this change.
Fix a typo.
> Disambiguate read/write response in metrics

- frontend/points-hack-april20/lib.js
Namespaces points hack so we can distinguish between releases.
> Namespaces points hack

- frontend/points-hack-april20/lib.js
Dynamic programming languages, poor testability :(
> Fixes bad reference to variable in points-hack

- frontend/leaderboard/src/Challenges.re
- frontend/leaderboard/src/Main.re
- frontend/leaderboard/src/Types.re
Added implementations for the following challenges:
- Blocks Created
- Transactions Sent
- Snark Work Created 
Additionally added functionality to merge all metric results together. The resulting merge takes the form of a map, with the key being a public key and the value is an array of tuples that represent a metric name and metric value.
> Added code for assigned challenges and merging functionality

- src/lib/ppx_coda/lint_version_syntax.ml
Linter disallows packaged modules, like `(module Foo)` to be specific module versions. Exception: allow inside `%%versioned...`, because there we may want uses related to the types being defined.
Linting was already disabled for `let%test_module`; now also in individual inline tests with `let%test` and `let%test_unit`.
> Packaged modules may not have specific versions

- rfcs/taskforce/0002-network-utility.md
Outlines the rough ideas for a network utility tool that would improve the iteration speed of spinning up networks.
> RFC: Network Utility Tool

- rfcs/taskforce/0002-network-utility.md
I merged this PR into the wrong place: #4817.
This is the same changes from that PR into develop.
> RFC: Network Utility Tool (#4817)

- frontend/leaderboard/src/Challenges.re
- frontend/leaderboard/src/Main.re
This PR adds two functions:
- award points for top n (i.e. top 10 block producers) 
- award points for a specific place (i.e. 1st place in block producers)
> Add functions to Leaderboard challenges: award top n points and 1st, 2nd.. place

- src/lib/blake2/intf.ml
- src/lib/coda_graphql/coda_graphql.ml
- src/lib/network_peer/peer.ml
- src/lib/sparse_ledger_lib/sparse_ledger.ml
Fix some misplaced versioned types.
> Remove some more misplaced versioned types

- src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
This PR
* uses the `top_hash` instead of the `protocol_state_hash` when comparing to see if we can use the genesis proof
* extracts *only* the genesis proof from the precomputed values, keeping the other values passed from the user intact
* writes the compiled genesis proof to a file on first use, so that it can still be used with binaries compiled against a different config
Checklist:
> Fix Genesis_ledger_helper interaction with Precomputed_values

- frontend/website/pages/docs/my-first-transaction.mdx
yet.
Checklist:
Closes #0000
Closes #0000
> Website: Testnet users dont need to create account

- frontend/website/pages/docs/faq.mdx
yet.
Checklist:
Closes #0000
Closes #0000
> Website: update tech docs FAQ

- frontend/website/src/pages/Testnet.re
Updates testnet view-full-leaderboard link to the latest
> Updates leaderboard link

- src/lib/pickles/dune
- src/lib/pickles/one_hot_vector/dune
- src/lib/pickles/one_hot_vector/one_hot_vector.ml
- src/pickles.opam
This PR implements an in-snark "one hot vector". I.e., a boolean vector exactly one element of which is true.
> Pickles: one hot vector

- src/lib/pickles/common.ml
- src/lib/pickles/marlin_checks/domain.ml
- src/lib/pickles/timer.ml
- src/lib/pickles/timer.mli
This PR adds a simple "timer" module to help with profiling.
> Pickles: timer

- src/lib/pickles/common.ml
- src/lib/pickles/wrap.ml
This implements the 'wrap prover' for wrapping a step proof
> Pickles: wrap prover

- frontend/website/src/pages/Testnet.re
> Website: Update Testnet Challnges Link for 3.2b

- frontend/website/pages/docs/architecture/snark-workers.mdx
> fix link in snark workers docs

- .mergify.yml
- scripts/test.py
- src/lib/transaction_snark_scan_state/transaction_snark_scan_state.mli
Use `%%versioned:` instead of writing out equalities in signature.
> %%versioned: for sig in scan state

- .mergify.yml
- scripts/test.py
> Remove build-wallet blacklisting

- src/lib/staged_ledger/staged_ledger.mli
- src/lib/transaction_snark_scan_state/transaction_snark_scan_state.mli
Use `%%versioned:` in sig for scan state in `Staged_ledger`.
> Staged ledger use %%versioned in sig

- frontend/website/src/Theme.re
- frontend/website/src/bindings/Sheets.re
- frontend/website/src/components/Leaderboard.re
- frontend/website/src/components/Summary.re
- frontend/website/src/components/ToggleButton.re
- frontend/website/src/pages/LeaderboardPage.re
Updates the data structures and styles for the new leaderboard page. 
This closes: #4984 and #4973
> Leaderboard: Update Data Structures

- frontend/website/src/components/TeamSection.re
small change for sherry's title!
> fix sherry's title

- buildkite/scripts/unit-test.sh
- buildkite/src/Command/Base.dhall
- buildkite/src/Command/Size.dhall
- buildkite/src/Jobs/Unit.dhall
[WIP] Buildkite agent machine type performance testing
Checklist:
> add experimental sizing for agent benchmarking

- .circleci/config.yml
- .circleci/config.yml.jinja
- frontend/client_sdk/package.json
- frontend/client_sdk/src/CodaSDK.re
- frontend/client_sdk/test/Test.ts
- frontend/client_sdk/yarn.lock
Client sdk fixes for testnet + CI catches this sort of failure for us
> Fixes client-sdk for testnet

- frontend/website/src/components/Leaderboard.re
This removes the Top 10 functionality since it's not ready for release and removes the links to the member profiles pages until we're ready to release.
> Fix: Remove unreleased Leaderboard features

- scripts/macos-setup-brew.sh
> Force python3 reinstall for Mac CI

- src/app/rosetta/README.md
- src/app/rosetta/create_schema.sql
- src/app/rosetta/make-db.sh
- src/app/rosetta/make-runtime-genesis.sh
- src/app/rosetta/rosetta.ml
- src/app/rosetta/run-demo.sh
- src/app/rosetta/start.sh
- src/lib/block_producer/block_producer.ml
- src/lib/coda_lib/coda_lib.ml
Adds working dev env for rosetta.
Changes are tested by successfully hitting the rosetta server and getting a response. And (at least for a bit), the archive node and coda daemon don't crash.
Usage is documented in README.md under `src/app/rosetta/`.
Fixes #5300
> Adds working dev env for rosetta

- src/app/rosetta/errors.ml
- src/app/rosetta/graphql.ml
- src/app/rosetta/network.ml
- src/app/rosetta/rosetta.ml
- src/app/rosetta/start.sh
- src/app/rosetta/test/README.md
- src/app/rosetta/test/lib.sh
- src/app/rosetta/test/network_list.sh
- src/app/rosetta/test/network_status.sh
Specifically, list + status are behaving to spec.
Introduced a simple `test/` system for checking changes.
Tested by running the two new test bash scripts against the debug network.
#5307
> Partially fixes and verifies network routes

- src/lib/coda_graphql/coda_graphql.ml
> Add genesis block command to GraphQL

- frontend/bot/src/Echo.re
- frontend/bot/src/Faucet.re
- frontend/bot/src/Repeater.re
- frontend/wallet/src/render/views/settings/AccountSettings.re
- frontend/wallet/src/render/views/transactions/Transactions.re
- graphql_schema.json
- src/app/cli/src/init/client.ml
- src/app/cli/src/init/graphql_client.ml
- src/app/cli/src/init/graphql_queries.ml
- src/app/rosetta/network.ml
- src/lib/coda_graphql/coda_graphql.ml
Refreshes schema + gets code compiling
Tested by compiling + running rosetta ./network_status.sh
> Switches rosetta genesis block to graphql

- scripts/compare_pr_diff_items.py
- src/lib/coda_base/account.ml
Versioned type and binable functor comparisons were not detecting changes.
Fixed by @mrmr1993.
> Fix PR comparisons

- frontend/website/src/components/ChallengePointsTable.re
- frontend/website/src/components/Leaderboard.re
- frontend/website/src/components/ProfileHero.re
Reverts CodaProtocol/coda#5438
- revert's @MartinMinkov's PR from last week, a few changes to be added before merging
> Revert "Website Leaderboard - Style fixes and added last manually updated to sheets and frontend"

- src/lib/coda_networking/coda_networking.ml
Checklist:
Closes #0000
Closes #0000
> fix broadcast log

- src/app/rosetta/lib/block.ml
- src/app/rosetta/lib/errors.ml
- src/app/rosetta/lib/mempool.ml
- src/app/rosetta/lib/operation_statuses.ml
With this PR, the full Data API for Rosetta is implemented modulo
necessary protocol changes denoted in TODOs scattered across the
codebase.
Much testing is still needed after protocol changes come through.
These changes were tested by running the (currently commented-out) unit test in mempool and visually inspecting the output.
> Completes mempool transaction API

- frontend/website/public/static/img/star.svg
- frontend/website/src/components/Leaderboard.re
Adds the Top 10 and Top 50 indicators to the Leaderboard page.
Closes #5382
> Website: Leaderboard Top 10/50

- frontend/website/src/components/Leaderboard.re
- frontend/website/src/pages/Testnet.re
Makes the Leaderboard links work on the Testnet page.
Closes #5446
> Website: Testnet Leaderboard Links

- graphql_schema.json
- src/app/archive/archive_lib/processor.ml
- src/app/archive/create_schema.sql
- src/app/rosetta/drop_tables.sql
- src/app/rosetta/lib/account.ml
- src/app/rosetta/lib/amount_of.ml
- src/app/rosetta/lib/block.ml
- src/app/rosetta/lib/errors.ml
- src/app/rosetta/lib/mempool.ml
- src/app/rosetta/lib/network.ml
- src/app/rosetta/lib/operation_statuses.ml
- src/app/rosetta/lib/operation_types.ml
- src/app/rosetta/lib/rosetta.ml
- src/app/rosetta/lib/these.ml
- src/lib/coda_base/token_id.mli
* Shuffled some code around to reuse model gen
* Fleshed out operations for each transaction
* Finished Block API
* Finished Mempool API
With this PR, the full Data API for Rosetta is implemented modulo
necessary protocol changes denoted in TODOs scattered across the
codebase.
Much testing is still needed after protocol changes come through.
Still TODO:
* Hit the DB for real
> Rosetta Block API

- frontend/website/pages/docs/snapps.mdx
Fixes typo on Snapps docs page
> Website: Fix typo in snapps docs page 

- src/app/rosetta/lib/account.ml
- src/app/rosetta/lib/block.ml
- src/app/rosetta/lib/mempool.ml
- src/app/rosetta/test-agent/agent.ml
- src/app/rosetta/test-agent/dune
- src/app/rosetta/test-agent/peek.ml
- src/app/rosetta/test-agent/poke.ml
Runs coda, creates a payment, then queries the mempool via Rosetta and makes sure the operations are sensical.
Fixes #5524 
Ran the test and it passes.
> Implements initial check payment test via mempool

- src/lib/coda_intf/transition_frontier_components_intf.ml
- src/lib/coda_lib/coda_lib.ml
- src/lib/transition_router/transition_router.ml
This PR makes demo mode sync instantly by not waiting 60s for high connectivity.
> demo mode bypass initialization

- src/lib/zexe_backend/zexe_backend_common/r1cs_constraint_system.ml
> Bump snarky

- frontend/website/src/pages/Genesis.re
Hello, this copy change is to be pushed out asap (request was asap) and so we are doing a "hot fix" to master since we are not ready to merge in the other changes in develop for 3.3
> Update Genesis page copy (hot fix to master) 

- src/app/rosetta/test-agent/agent.ml
All the way from keypair generation down to the transaction created
being transmitted and witnessed in mempool and a block.
(For a payment; a follow-up PR can be created once delegation works)
Fixes #5680
> Construction works end-to-end in test agent

- graphql_schema.json
- src/app/cli/src/init/client.ml
- src/app/cli/src/init/graphql_queries.ml
- src/lib/coda_graphql/coda_graphql.ml
This is #5813 rebased onto the release branch. 
Checklist:
> [Release] Add nextAvailableToken to the GraphQL API and CLI

- frontend/website/src/pages/Genesis.re
Changed the text on the genesis page. 
Closes https://github.com/CodaProtocol/coda/issues/5822
> [Website] Changed copy text on Genesis page

- src/app/rosetta/lib/construction.ml
- src/app/rosetta/test-agent/offline.ml
- src/lib/rosetta_models/enums.ml
> Changes signature scheme to match rosetta-spec name

- frontend/website/pages/docs/developers/sandbox-node.mdx
- frontend/website/pages/docs/tokens.mdx
- frontend/website/public/static/img/LeaderboardAwardCommunityMVP.png
- frontend/website/public/static/img/LeaderboardAwardDoubleMVP.png
- frontend/website/public/static/img/LeaderboardAwardGenesisMember.png
- frontend/website/public/static/img/LeaderboardAwardTechnicalMVP.png
- frontend/website/public/static/img/LeaderboardEmpty.png
- frontend/website/public/static/img/star.svg
- frontend/website/src/components/Badge.re
- frontend/website/src/components/ChallengePointsTable.re
- frontend/website/src/components/DocsSideNav.re
- frontend/website/src/components/Dropdown.re
- frontend/website/src/components/Leaderboard.re
- frontend/website/src/components/ProfileHero.re
- frontend/website/src/components/Summary.re
- frontend/website/src/components/Wrapped.re
- frontend/website/src/components/svg/Icons.re
- frontend/website/src/pages/Genesis.re
- frontend/website/src/pages/LeaderboardPage.re
- frontend/website/src/pages/MemberProfilePage.re
- frontend/website/src/pages/Testnet.re
- frontend/website/yarn.lock
To be merged into master (as master is the source of truth for codaprotocol.com now)
> Patch of web changes via develop for sandbox

- netlify.toml
> Hotfix: Update Netlify to deploy off master

- frontend/website/pages/docs/faq.mdx
Remove a space to force a deploy off master.
> Force master deploy

- frontend/website/.babelrc
- frontend/website/bsconfig.json
- frontend/website/next.config.js
- frontend/website/package.json
- frontend/website/yarn.lock
Updated next and fiddled with the babel and bsconfigs until I got the build working locally.
> Hotfix: Webpack Black Magic

- src/app/rosetta/README.md
- src/app/rosetta/lib/network.ml
Plus a minor tweak to pass unit tests
See docs for details
> Documentation for the v1 Rosetta release

- frontend/website/pages/docs/getting-started.mdx
Updates the recommended hardware requirements for 3.3.
> Website: Update hardware requirements for 3.3

- src/lib/child_processes/termination.ml
- src/lib/memory_stats/memory_stats.ml
- src/lib/verifier/dune
- src/lib/verifier/prod.ml
This PR kills the verifier every 15 minutes +/- 2.5 minutes (with the delta being uniformly random to avoid everything dying at once).
> kill the verifier periodically

- src/app/rosetta/README.md
* Supports 1.4.4 spec
* Handles multiple blocks with same best height
* Supports "failed transactions"
> Updates Rosetta README

- src/app/rosetta/README.md
> Updates docker vers in one place missed

- genesis_ledgers/phase_three/genesis_ledger.json
Updates the genesis ledger to include the keys for phase 3.3.
> Phase 3.3 Genesis Ledger

- frontend/website-redesign/public/static/img/MinaBlockchain.png
- frontend/website-redesign/public/static/img/OtherBlockchains.png
- frontend/website-redesign/src/components/BlockchainComparison.re
- frontend/website-redesign/src/pages/Index.re
This PR implements the `Blockchain Comparison` component. 
Please note that the image assets have not been finalized. 
Desktop:
Tablet:
Mobile:
> Website Redesign: Blockchain Comparison

- frontend/leaderboard/src/Metrics.re
- frontend/website-redesign/pages/docs/my-first-transaction.mdx
- frontend/website/pages/docs/my-first-transaction.mdx
Replaces the old echo bot public key with the new one that will be used.
> Leaderboard: Add references to new echo bot

- genesis_ledgers/phase_three/config.json
Checklist:
Closes #0000
Closes #0000
> bump genesis timestamp

- frontend/leaderboard/Dockerfile
Updates the spreadsheet id in the dockerfile to use the correct spreadsheet. The one that is being used currently is a spreadsheet that I used for testing purposes but didn't update.
> Leaderboard: Update spreadsheet ID in dockerfile

- frontend/website/pages/docs/tokens.mdx
This PR adds the changes done from https://github.com/CodaProtocol/coda/pull/5789 and adds them to the master branch so it can be deployed.
> Website: Merge develop tokens into master

- frontend/website/pages/testworld.js
- frontend/website/src/pages/Testworld.re
Adding an empty test world page so that we can approve the link (unable to do so if it 404s).
> Website: added empty testworld page

- frontend/website/pages/adversarial.js
- frontend/website/src/pages/Adversarial.re
Adds empty page for codaprotocol.com/advesarial
> Website: add empty page

- frontend/website/src/pages/LeadGen.re
> Hotfix: Leadgen Email capture

- frontend/website/src/pages/LeadGen.re
> Hotfix: Switchback to Sendgrid

- frontend/website/src/pages/LeadGen.re
Updates the copy on the LeadGen page to match designs.
> Hotfix: Leadgen copy

- frontend/website/src/pages/LeadGen.re
Copy fix and redirect to genesis
> Leadgen: Fix copy and redirect to genesis

- frontend/website-redesign/public/static/img/headshots/HelenaLi.jpg
- frontend/website-redesign/src/components/EmailInput.re
- frontend/website-redesign/src/components/FeaturedSingleRow.re
- frontend/website-redesign/src/components/Hero.re
- frontend/website-redesign/src/components/Icon.re
- frontend/website-redesign/src/components/TeamGrid.re
- frontend/website-redesign/src/pages/About.re
Small fixes including: 
- updating team photos for several members (checked with what's available in google drive) 
- extract about hero into a reusable component 
- fix footer email input height
> Website/small fixes to footer and team section photos 

- frontend/website-redesign/public/static/img/EasilyAccessible.png
- frontend/website-redesign/public/static/img/LightChainHighSpeed.png
- frontend/website-redesign/public/static/img/PrivateAndPowerful.png
- frontend/website-redesign/public/static/img/ProgrammableMoney.png
- frontend/website-redesign/public/static/img/TrulyDecentralized.png
- frontend/website-redesign/public/static/img/door.png
- frontend/website-redesign/public/static/img/hands.png
- frontend/website-redesign/public/static/img/parts.png
- frontend/website-redesign/public/static/img/shooting_star.png
- frontend/website-redesign/public/static/img/spread.png
- frontend/website-redesign/src/components/AlternatingSections.re
- frontend/website-redesign/src/components/BlockchainComparison.re
- frontend/website-redesign/src/components/HomepageHero.re
- frontend/website-redesign/src/pages/Index.re
This PR implements the functionality to pass in a custom background image for the `HomepageHero` component. Additionally, updates the images used on the homepage and fixes some slight CSS layout unpleasantries.
> Website: Parameter for background image in hero and updated images

- frontend/website-redesign/src/Theme.re
- frontend/website-redesign/src/components/Alert.re
- frontend/website-redesign/src/components/DocsComponents.re
- frontend/website-redesign/src/components/DocsSideNav.re
- frontend/website-redesign/src/components/Hero.re
- frontend/website-redesign/src/components/SideNav.re
- frontend/website-redesign/src/pages/Docs.re
* Fixes a few bugs with side nav
* Janky, poor spacing, some poor colors, but starting to get there
* Many more fixes to come
> Starts docs pages

- frontend/website-redesign/pages/blog/all.js
- frontend/website-redesign/public/static/img/AboutTechCta.png
- frontend/website-redesign/public/static/img/ArticleImageSmall.png
- frontend/website-redesign/public/static/img/BlogLandingHero.png
- frontend/website-redesign/public/static/img/GetStartedCta.png
- frontend/website-redesign/src/components/Alert.re
- frontend/website-redesign/src/components/BlogModule.re
- frontend/website-redesign/src/components/ButtonBar.re
- frontend/website-redesign/src/components/DocsComponents.re
- frontend/website-redesign/src/components/InternalCtaSection.re
- frontend/website-redesign/src/components/LabelEyebrow.re
- frontend/website-redesign/src/components/ListModule.re
- frontend/website-redesign/src/pages/Blog.re
- frontend/website-redesign/src/pages/BlogAll.re
- frontend/website-redesign/src/pages/Docs.re
**Incomplete**
* Featured row rendering is wonky
* Lorem ipsum on InternalCtaSection (as designed)
* Rendering at sizes under 1200px
* Stop-gap by taking "More posts" component on all posts
> Initial pass at blog {landing, all-posts} pages

- frontend/website-redesign/src/components/ButtonBar.re
- frontend/website-redesign/src/pages/Blog.re
- frontend/website-redesign/src/pages/BlogAll.re
- frontend/website-redesign/src/pages/BlogPost.re
Fixes responsive issues with landing + all blogs
> More-posts component properly responsive

- frontend/website-redesign/src/components/AnnouncementBanner.re
- frontend/website-redesign/src/components/Footer.re
- frontend/website-redesign/src/components/Page.re
> Website: Last minute copy changes

- frontend/website-redesign/pages/community.js
- frontend/website-redesign/public/static/img/community-page/09_Community_1_1536x1504_tablet.jpg
- frontend/website-redesign/public/static/img/community-page/09_Community_1_2880x1504.jpg
- frontend/website-redesign/public/static/img/community-page/09_Community_1_750x1056_mobile.jpg
- frontend/website-redesign/public/static/img/community-page/09_Community_2_1504x1040.jpg
- frontend/website-redesign/public/static/img/community-page/09_Community_3_1504x1040.jpg
- frontend/website-redesign/public/static/img/community-page/09_Community_4_1504x1040.jpg
- frontend/website-redesign/public/static/img/community-page/CommunityBackground.png
- frontend/website-redesign/public/static/img/community-page/SectionCulture&Values.png
- frontend/website-redesign/src/components/Constants.re
- frontend/website-redesign/src/components/FeaturedSingleRow.re
- frontend/website-redesign/src/components/Footer.re
- frontend/website-redesign/src/components/MemberProfile.re
- frontend/website-redesign/src/components/Nav.re
- frontend/website-redesign/src/pages/Community.re
- frontend/website-redesign/src/pages/Genesis.re
> Website/ Community page 

- frontend/website/public/_redirects
Will ensure it works on staging link of course
> Redirects codaprotocol.com/* to minaprotocol.com/

- frontend/website/public/_redirects
> Website: Forces redirect

- frontend/website-redesign/src/components/AlternatingSections.re
- frontend/website-redesign/src/components/ButtonBar.re
- frontend/website-redesign/src/pages/GetStarted.re
Fixes buttons on the getting started page / footer
> Buttons work on getting started pages

- frontend/website-redesign/public/static/img/logos/LogoTestWorld.svg
- frontend/website-redesign/src/components/FeaturedSingleRow.re
- frontend/website-redesign/src/pages/Genesis.re
- frontend/website-redesign/src/pages/LeadGen.re
Fixes the main CTA button on the Genesis page.
> Fix Genesis CTA

- frontend/website-redesign/public/static/img/tech-access.png
- frontend/website-redesign/public/static/img/tech-access.svg
- frontend/website-redesign/public/static/img/tech-audit.png
- frontend/website-redesign/public/static/img/tech-audit.svg
- frontend/website-redesign/public/static/img/tech-build-snapps.png
- frontend/website-redesign/public/static/img/tech-build-snapps.svg
- frontend/website-redesign/public/static/img/tech-power-fair.png
- frontend/website-redesign/public/static/img/tech-power-fair.svg
- frontend/website-redesign/public/static/img/tech-power-interop.png
- frontend/website-redesign/public/static/img/tech-power-interop.svg
- frontend/website-redesign/public/static/img/tech-txn-fees.png
- frontend/website-redesign/public/static/img/tech-txn-fees.svg
- frontend/website-redesign/src/components/FeaturedSingleRow.re
- frontend/website-redesign/src/components/Footer.re
- frontend/website-redesign/src/components/HomepageHero.re
- frontend/website-redesign/src/pages/Tech.re
Small fixes for tech page incl. fixing CTA images, updating SVG and fixing Footer and Homepage Hero bug.
> Website: Tech Page and Misc Fixes

- src/lib/network_pool/indexed_pool.ml
- src/lib/network_pool/indexed_pool.mli
- src/lib/network_pool/transaction_pool.ml
Refactor to log indexed pool error when handling transactions as a result of best tip change
Checklist:
> log indexed_pool errors when handling best tip diff

- buildkite/scripts/generate-diff.sh
`sudo` is note installed in docker-toolchain:base image
Checklist:
> remove sudo from jq curl install in gen diff

- .mergify.yml
- scripts/test.py
> Fix mergify config

- buildkite/scripts/helm-ci.sh
> fix Chart.yaml dirname logic if empty diff

- scripts/rebuild-deb.sh
Genesis ledger and/or proof can either be downloaded or generated. So check each of these directories before trying to copy 
Checklist:
Closes #0000
Closes #0000
> copy if directory exists

- frontend/ci-build-me/src/index.js
Fixes for #6230 so that it works
* Flips a bool conditional
* Updates the buildkite token to support read_builds privilege (not shown in code)
* Uses GET not POST
* Pretty-printed
> Fixes for ci-build-me no waste

- src/app/replayer/replayer.ml
In preparation for a CI test of the replayer, add a field `target_ledger_hash` to the transaction replayer app.
After all transactions have been replayed, that hash is compared against the actual ledger Merkle root. If they differ, an `error` log is generated, and the tool exits with code 1.
> Add target ledger hash in replayer

- README.md
- frontend/website-redesign/public/static/Mina_Wordmark_Github.png
> Moves readme to Mina

- src/lib/ppx_dhall_type/deriving.ml
Allow `deriving dhall_type` for polymorphic types, by generating functions that accept dhall types for the type parameters.
For example, for the type declarations:
```ocaml
type ('a, 'b) t0 = {x: 'a; y: 'b} [@@deriving dhall_type]
type 'a t1 = ('a, string) t0 [@@deriving dhall_type]
type t2 = int t1 [@@deriving dhall_type]
```
we generate:
```ocaml
let t0_dhall_type a b = Dhall_type.Record [("x", a); ("y", b)]
let t1_dhall_type a = t0_dhall_type a Dhall_type.Text
let t2_dhall_type = t1_dhall_type Dhall_type.Integer
```
> Add dhall_type deriver for polymorphic types

- src/lib/ledger_catchup/ledger_catchup.ml
For catchup, we were downloading state hashes from a random set of peers, which may not have the hashes available.
Instead, first try the peers in the blocks contained in the Rose trees sent over the catchup job reader pipe. Those Rose trees contain blocks and their senders. We know that such blocks are in the senders' transition frontiers, so they should have the needed hashes.
If downloading the hashes from those peers fails, try the random peers, as has been our wont.
Closes #6265.
> Download state hashes from subtree peers first

- src/lib/bootstrap_controller/bootstrap_controller.ml
> Trivial: Make logged time intervals in bootstrap controller positive

- src/lib/integration_test_cloud_engine/coda_automation.ml
Checklist:
Closes #0000
Closes #0000
> add a few default configs

- frontend/website-redesign/src/components/Constants.re
- frontend/website-redesign/src/components/FooterLinks.re
- frontend/website-redesign/src/pages/Genesis.re
- frontend/website-redesign/src/pages/Grants.re
This PR updates the link for the `Genesis Token Grant Application` application on our website.
> Website: Update Genesis Application form link

- frontend/website-redesign/src/components/GenesisMemberProfile.re
- frontend/website-redesign/src/components/WorldMapSection.re
- frontend/website-redesign/src/pages/Genesis.re
This PR implements the requested QA fixes for the Genesis page.
> Website: Genesis QA Fixes

- frontend/website-redesign/src/Theme.re
- frontend/website-redesign/src/components/Constants.re
- frontend/website-redesign/src/components/CultureGrid.re
- frontend/website-redesign/src/pages/Grants.re
This PR changes the copy on the grants page to use Mina. Also fixes some minor layout issues that weren't matching the figma.
> Website: Grants Copy Change

- src/lib/pickles/plonk_curve_ops.ml
- src/lib/pickles/scalar_challenge.ml
This fixes a bug @ltvvlz caught in how endo-scaling and scalar mul were implemented. Basically, we need to make sure the accumulator variables are connected with each other across rows.
> fix handling of accumulator in curve loops

- buildkite/src/Jobs/Lint/Fast.dhall
- buildkite/src/Jobs/Lint/HelmChart.dhall
- buildkite/src/Jobs/Release/ArchiveNodeArtifact.dhall
- buildkite/src/Jobs/Release/HelmRelease.dhall
- buildkite/src/Jobs/Release/MinaArtifact.dhall
- buildkite/src/Jobs/Test/ClientSdk.dhall
- buildkite/src/Jobs/Test/CompareSignatures.dhall
- buildkite/src/Jobs/Test/ReasonScripts.dhall
- buildkite/src/Jobs/Test/UnitTest.dhall
This change should be in effect while coda-automation submodules issues are investigated and resolved.
**Checklist:**
> soft-fail helm lint + release steps

- frontend/website-redesign/public/static/img/logos/Investor Logos_YBB Foundation 1.png
- frontend/website-redesign/public/static/img/logos/SNZ.png
- frontend/website-redesign/public/static/img/logos/YBB Foundation 1.png
- frontend/website-redesign/src/components/AboutpageRows.re
- frontend/website-redesign/src/components/Investors.re
- frontend/website-redesign/src/components/SecuredBySection.re
> Adds SNZ as investor 

- src/lib/trust_system/peer_trust.ml
Fixes https://github.com/MinaProtocol/mina/issues/6476
> Fix NaN assertion failure

- src/lib/runtime_config/runtime_config.ml
Increases k past 1 to avoid forkiness
Still fails sometimes, but so far for other reasons, not the forkiness one
> reduce (some) delegation test flakiness

- scripts/run_local_network.sh
Fixes a bug in the script and some bugs with linux and debian 9
> run local network script fixes for linux

- src/app/cli/src/coda.ml
- src/app/cli/src/init/client.ml
- src/app/cli/src/init/coda_tracing.ml
2. clean up trace files (TODO: implement rotate logic for tracefiles  #6556)
3. "genesis" dir for genesis ledger and proof
TODO: #6555
Checklist:
Closes #6246
> don't wipe out config directory

- src/app/archive/archive_lib/processor.ml
- src/app/archive/create_schema.sql
- src/lib/consensus/intf.ml
- src/lib/consensus/proof_of_stake.ml
> adding epoch_data to archive database

- src/lib/zexe_backend/zexe_backend_common/curve.ml
When we switched to the new curves, we forgot to include a check that deserialized curve points were on the curve (it was present previously). I added a unit test that checks invalid curve points are correctly rejected.
> check that deserialized points are on curve

- src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
There was a mismatch between the filename generated when searching for it vs when creating.
This was causing the daemon to look for a different file than what was packaged/generated already
Checklist:
Closes #0000
Closes #0000
> generate genesis ledger filename consistently

- src/app/cli/src/coda.ml
A workaround for some libp2p network initialization issues we're seeing recently:
We should instead start our nodes with a handful of initial peers (8 or 10) rather than 1 or 2. With peer-exchange on, on the libp2p side, these peers won't get overwhelmed and we won't have to worry about being weakly connected to the network. In the long run on the infrastructure side, I think we should change seed.testnet-name.o1test.net to point to a simple file with these peers in it and we can call this an "initial peers set" and encourage other folks on the network to maintain other initial peers sets to avoid centralization risk.
With this PR, you'd be able to consume this initial peer set, you could manually download the file and examine it to make sure you're happy and pass it as a parameter or …
> Supports loading peers from a list file

- frontend/website-redesign/public/static/img/ModalButtonHover.jpg
- frontend/website-redesign/src/ContentType.re
- frontend/website-redesign/src/components/AnnouncementBanner.re
- frontend/website-redesign/src/components/ButtonBar.re
- frontend/website-redesign/src/components/Constants.re
- frontend/website-redesign/src/components/Contributors.re
- frontend/website-redesign/src/components/Footer.re
- frontend/website-redesign/src/components/FooterLinks.re
- frontend/website-redesign/src/components/GenesisMemberProfile.re
- frontend/website-redesign/src/components/GenesisMembersGrid.re
- frontend/website-redesign/src/components/Investors.re
- frontend/website-redesign/src/components/MemberProfile.re
- frontend/website-redesign/src/components/ModalButton.re
- frontend/website-redesign/src/components/Page.re
- frontend/website-redesign/src/components/ProfileCard.re
- frontend/website-redesign/src/components/ProfileHero.re
- frontend/website-redesign/src/components/SmallCard.re
- frontend/website-redesign/src/components/StatusBadge.re
- frontend/website-redesign/src/components/Summary.re
- frontend/website-redesign/src/components/TeamGrid.re
- frontend/website-redesign/src/components/TeamMember.re
- frontend/website-redesign/src/components/TeamMemberProfile.re
- frontend/website-redesign/src/pages/About.re
- frontend/website-redesign/src/pages/Community.re
- frontend/website-redesign/src/pages/Developers.re
- frontend/website-redesign/src/pages/Docs.re
- frontend/website-redesign/src/pages/Genesis.re
- frontend/website-redesign/src/pages/Grants.re
- frontend/website-redesign/src/pages/Media.re
- frontend/website-redesign/src/pages/Testnet.re
This PR is tracking the progress on the About Team Bios section. 
**NOTE**
Also included a refactor to most URLs used on the website. I added entries to the `Constants.re` file as a reference for all references of URLs that link to external sources.
> Website: Team Bios

- frontend/leaderboard/src/Challenges.re
- frontend/leaderboard/src/Main.re
- frontend/leaderboard/src/Postgres.re
This PR makes a fix to the queries being made to the archive DB. 
**NOTE**: These changes were hotfixed and deployed as a container already. This is the currently running version of the `leaderboard-cron`
> Leaderboard: Postgres Query Fixes

- src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
> Merge back develop

- .mergify.yml
- .mergify.yml.jinja
> Merge into develop-until-4.1-hardfork without merging back first

- src/lib/blake2/blake2.ml
- src/lib/snarky_blake2/test/test.ml
Checklist:
Closes #0000
Closes #0000
> change Blake2 from BLAKE2s to BLAKE2b

- src/lib/coda_net2/coda_net2.ml
It's hard to tell exactly if this would fix the error until we clean up
the validation noise (see #6792 )
The crash was an Ivar fill of full, so adding fill_if_empty in the right place wouldn't cause a regression and only could possibly improve our code.
Closes #6772
> Be conservative with fill-if-empty, fixes #6772

- src/lib/coda_net2/coda_net2.ml
- src/lib/coda_net2/coda_net2.mli
- src/lib/gossip_net/libp2p.ml
This PR kills the libp2p helper every 11 +/- 2.5 minutes.
> kill the libp2p helper periodically

- src/lib/allocation_functor/table.ml
- src/lib/coda_networking/coda_networking.ml
- src/lib/gossip_net/libp2p.ml
- src/lib/ledger_catchup/ledger_catchup.ml
- src/lib/network_pool/snark_pool.ml
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/sync_handler/dune
- src/lib/sync_handler/sync_handler.ml
- src/lib/transition_frontier/transition_frontier.ml
- src/lib/transition_frontier/transition_frontier.mli
- src/lib/transition_router/transition_router.ml
This cherry picks the changes from
https://github.com/MinaProtocol/mina/pull/6822
https://github.com/MinaProtocol/mina/pull/6810
onto 4.1-turbo-pickles
> Fixes cherry pick

- src/lib/coda_lib/coda_lib.ml
> Return some telemetry data even when there is no frontier available

- src/app/libp2p_helper/src/codanet.go
Checklist:
Closes #0000
Closes #0000
> fix/libp2p-disabe-decaying-tags Stop supporting the Decayer interface

- buildkite/scripts/connect-to-testnet-on-develop.sh
> Trivial: Use a bash for loop in connect-to-testnet script

- src/app/libp2p_helper/src/libp2p_helper/main.go
- src/lib/network_pool/network_pool_base.ml
- src/lib/network_pool/transaction_pool.ml
This PR was merged without review or passing CI. Accordingly, it seems to have broken CI.
Checklist:
> Revert "Merge pull request #6876 from MinaProtocol/4.1-turbo-pickles"

- src/lib/network_pool/network_pool_base.ml
- src/lib/network_pool/transaction_pool.ml
This PR is part of #6876.
Checklist:
> Ignore repeated messages (from 4.1-turbo-pickles failed merge)

- buildkite/scripts/connect-to-testnet-on-develop.sh
- buildkite/src/Command/Base.dhall
- buildkite/src/Jobs/Release/MinaArtifact.dhall
Checklist:
Closes #0000
Closes #0000
> Updating submodule coda-automation to branch master

- src/app/libp2p_helper/src/libp2p_helper/main.go
- src/lib/coda_net2/coda_net2.ml
- src/lib/coda_net2/coda_net2.mli
- src/lib/gossip_net/libp2p.ml
This PR is part of #6876.
Checklist:
> Hotfix/libp2p async (from 4.1-turbo-pickles failed merge)

- src/lib/transition_frontier/transition_frontier.ml
This PR attempts to clear the persistent frontier and re-initialise the transition frontier when `load_from_persistence_and_start` fails. Users have been seeing failures here and are having to manually clear out their cache directories, but the error messages are not detailed enough for us to be able to debug what's actually happened and fix the underlying issue.
Checklist:
Closes #6920 
Closes #6908 
Fixes the follow-up issue in #6871
Closes #6868
Closes #6859
Closes #5069
> Retry transition frontier init if load_from_persistence_and_start fails

- src/lib/consensus/proof_of_stake.ml
Addresses an issue we began seeing on the public testnet once the network's best tip no longer shared any checkpoints with the genesis block.
> [HOTFIX] Fix long fork selection rule when min_window_density of chains are equal

- dockerfiles/Dockerfile-coda-daemon
Update default docker entrypoint to more closely match bake.sh behaviour
Checklist:
Closes #0000
Closes #0000
> clean-up-lock-k8s 

- src/lib/consensus/proof_of_stake.ml
Checklist:
Closes #0000
Closes #0000
> Fix long fork selection rule when min_window_density of chains are equal

- .github/PULL_REQUEST_TEMPLATE.md
Mention `Mina` in PR template, which seems a safe change.
> Mention Mina in PR template

- src/app/cli/src/coda.ml
This prevents errors reading from the external transition db from being fatal, allowing startup to continue. This fixes #6745 and #6623.
Checklist:
> Clear out the external transition db and retry if it can't be created

- helm/archive-node/Chart.yaml
- helm/archive-node/README.md
- helm/archive-node/templates/archive.yaml
- helm/archive-node/values.yaml
- helm/block-producer/Chart.yaml
- helm/block-producer/README.md
- helm/block-producer/templates/block-producer.yaml
- helm/block-producer/values.yaml
- helm/seed-node/Chart.yaml
- helm/seed-node/templates/seed-node.yaml
- helm/snark-worker/Chart.yaml
- helm/snark-worker/templates/snark-coordinator.yaml
as a result of this [PR](https://github.com/MinaProtocol/mina/pull/6973)
> rm -log-received-blocks from mina repo helm config

- src/lib/block_producer/block_producer.ml
- src/lib/blockchain_snark/blockchain_snark_state.ml
- src/lib/coda_transition/external_transition.ml
- src/lib/consensus/intf.ml
- src/lib/consensus/proof_of_stake.ml
- src/lib/filtered_external_transition/filtered_external_transition.ml
- src/lib/staged_ledger/pre_diff_info.ml
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/staged_ledger/staged_ledger.mli
- src/lib/staged_ledger_diff/staged_ledger_diff.ml
- src/lib/staged_ledger_diff/staged_ledger_diff.mli
- src/lib/transition_frontier/frontier_base/breadcrumb.ml
> move supercharge_coinbase to protocol state

- src/lib/integration_test_cloud_engine/coda_automation.ml
- src/lib/integration_test_cloud_engine/kubernetes_network.ml
mixing up the graphql ports so they don't conflict
> change graphql ports

- scripts/zexe-standardize.sh
This should fix [this error](https://buildkite.com/o-1-labs-2/mina/builds/7390#0bc339eb-139e-4ea9-bc96-ac2936b1be44)
Checklist:
> Update standardize script

- dockerfiles/Dockerfile-rosetta
Checklist:
Closes #0000
Closes #0000
> fix-rosetta-zexe-standardize Fix rosetta CI

- src/lib/consensus/proof_of_stake.ml
This enables the min window rule
> Min window enable

- src/lib/coda_lib/conf_dir.ml
Export logs to a `tar.gz` file, instead of `.tgz`. That enables uploading the archive to Github.
Also added output of `cat /etc/os-release` to the hardware info file, which might be useful.
> Export logs to tar.gz

- dockerfiles/scripts/healthcheck-utilities.sh
Ensure proper result comparison for heallthchecks.
Checklist:
> healthcheck fixes

- dockerfiles/scripts/healthcheck-utilities.sh
Checklist:
Closes #0000
Closes #0000
> more healthcheck fixes

- dockerfiles/scripts/healthcheck-utilities.sh
Update healthchecks with a special case for prior to genesis timestamp
Checklist:
Closes #0000
Closes #0000
> healthcheck-special-case-genesis-timestamp

- src/lib/integration_test_cloud_engine/coda_automation.ml
make work with https://github.com/MinaProtocol/coda-automation/pull/501/files
> fix k8 context

- buildkite/src/Jobs/Release/MinaArtifact.dhall
- dockerfiles/scripts/healthcheck-utilities.sh
Ensure quotes are included in status comparison. Also fix local daemon owned wallets and total balance check.
Checklist:
> fix sync status "SYNCED" comparison for check

- helm/archive-node/Chart.yaml
- helm/archive-node/templates/_healthchecks.tpl
- scripts/archive/Dockerfile
> add tooling for archive node postgres communication and update archive-postgres healthcheck

- src/lib/logger/impl.ml
Log the dupes in a special key
> Fixes dedupe exception when dupe metadata

- src/app/libp2p_helper/src/libp2p_helper/main.go
Whenever we discover them
Tested by talking to @noot
> Explicitly connect to the found peers

- src/config/testnet_postake_medium_curves.mlh
- src/lib/marlin_plonk_bindings/pasta_fp_plonk_verifier_index/marlin_plonk_bindings_pasta_fp_verifier_index.ml
- src/lib/marlin_plonk_bindings/pasta_fp_urs/marlin_plonk_bindings_pasta_fp_urs.ml
- src/lib/marlin_plonk_bindings/pasta_fq_plonk_verifier_index/marlin_plonk_bindings_pasta_fq_verifier_index.ml
- src/lib/marlin_plonk_bindings/pasta_fq_urs/marlin_plonk_bindings_pasta_fq_urs.ml
- src/lib/pickles/composition_types/composition_types.ml
- src/lib/pickles/dlog_main.ml
- src/lib/pickles/pairing_main.ml
- src/lib/pickles/per_proof_witness.ml
- src/lib/pickles/plonk_checks/plonk_checks.ml
- src/lib/pickles/proof.ml
- src/lib/pickles/requests.ml
- src/lib/pickles/step.ml
- src/lib/pickles/step_main.ml
- src/lib/pickles/unfinalized.ml
- src/lib/pickles/verify.ml
- src/lib/pickles/wrap.ml
- src/lib/pickles/wrap_main.ml
This moves https://github.com/MinaProtocol/mina/pull/7097/ to the pasta curves
> Verifier fixes pasta

- scripts/Brewfile.lock.json
- updates brew lock file
Checklist:
> updated brew lock file

- src/app/cli/src/coda.ml
- src/app/cli/src/tests/coda_worker.ml
- src/app/cli/src/tests/full_test.ml
- src/lib/mina_lib/coda_subscriptions.ml
- src/lib/mina_lib/config.ml
- src/lib/mina_lib/mina_lib.ml
This is #7157 rebased onto `develop-until-4.1-hardfork`
Checklist:
> Add block uploading

- src/config/testnet_postake_medium_curves.mlh
This increases the ledger depth to 20.
> Bump ledger depth

- src/app/libp2p_helper/src/codanet.go
Filter out private ips from the advertise list -- we only need to advertise ips that folks will be able to dial. mDNS uses a different path for discovery.
> Filter out private ips

- frontend/bot/Dockerfile
- helm/block-producer/Chart.yaml
- helm/block-producer/templates/_healthchecks.tpl
> Add health utilities to bots image and refactor bots' probes

- src/lib/codable/BUILD.bazel
- src/lib/command_line_tests/BUILD.bazel
- src/lib/consensus/BUILD.bazel
- src/lib/crs/BUILD.bazel
- src/lib/cstubs_applicative/BUILD.bazel
- src/lib/currency/BUILD.bazel
- src/lib/daemon_rpcs/BUILD.bazel
- src/lib/data_hash_lib/BUILD.bazel
- src/lib/debug_assert/BUILD.bazel
- src/lib/direction/BUILD.bazel
- src/lib/distributed_dsl/BUILD.bazel
> [Bazel] batch 3, of 11 files (c - d)

- src/lib/base58_check/BUILD.bazel
- src/lib/bash_colors/BUILD.bazel
- src/lib/best_tip_prover/BUILD.bazel
- src/lib/block_producer/BUILD.bazel
- src/lib/block_time/BUILD.bazel
- src/lib/blockchain_snark/BUILD.bazel
- src/lib/bootstrap_controller/BUILD.bazel
- src/lib/cache_lib/BUILD.bazel
- src/lib/child_processes/BUILD.bazel
- src/lib/cli_lib/BUILD.bazel
Files starting with 'b', plus a few 'c' ones
> [Bazel] batch 1, of 10 files

- src/lib/bignum_bigint/BUILD.bazel
- src/lib/blake2/BUILD.bazel
- src/lib/bowe_gabizon_hash/BUILD.bazel
- src/lib/cache_dir/BUILD.bazel
- src/lib/crypto_params/BUILD.bazel
- src/lib/crypto_params/gen/BUILD.bazel
- src/lib/hash_prefixes/BUILD.bazel
- src/lib/o1trace/BUILD.bazel
- src/lib/random_oracle_input/BUILD.bazel
- src/lib/snark_keys_header/BUILD.bazel
- src/lib/snarky_group_map/BUILD.bazel
- src/lib/snarky_log/BUILD.bazel
This PR adds Bazel build files for `src/lilb/crypto_params` and its dependencies.
> [Bazel] add crypto-params and its deps

- src/lib/dummy_values/BUILD.bazel
- src/lib/dummy_values/gen_values/BUILD.bazel
- src/lib/random_oracle/BUILD.bazel
generates and compiles a file, using genrule
> [Bazel] src/lib/dummy_values & deps, includes gen_values with genrule

- src/lib/coda_commands/BUILD.bazel
- src/lib/coda_compile_config/BUILD.bazel
- src/lib/coda_debug/BUILD.bazel
- src/lib/coda_incremental/BUILD.bazel
- src/lib/coda_intf/BUILD.bazel
- src/lib/coda_net2/BUILD.bazel
- src/lib/coda_numbers/BUILD.bazel
- src/lib/coda_plugins/BUILD.bazel
- src/lib/coda_state/BUILD.bazel
- src/lib/coda_transition/BUILD.bazel
> [Bazel] batch 2, of 10 files (coda_*)

- src/lib/hash_prefix_states/BUILD.bazel
- src/lib/immutable_array/BUILD.bazel
- src/lib/inline_test_quiet_logs/BUILD.bazel
- src/lib/integration_test_cloud_engine/BUILD.bazel
- src/lib/integration_test_lib/BUILD.bazel
- src/lib/interruptible/BUILD.bazel
- src/lib/key_value_database/BUILD.bazel
- src/lib/ledger_catchup/BUILD.bazel
- src/lib/ledger_proof/BUILD.bazel
- src/lib/linked_tree/BUILD.bazel
Ten files starting with letters h - l
> [Bazel] batch 5, of 10 files (h - l)

- src/lib/mina_base/BUILD.bazel
- src/lib/mina_base/gen/BUILD.bazel
Only two files, but one is large since this pkg contains over 100 files, and this pkg generates and compiles a file, using genrule.
Maybe this should be broken up into smaller packages?
> [Bazel] mina_base and mina_base/gen

- src/lib/rosetta_models/BUILD.bazel
One one build file, but the package contains over 70 source files.
> [Bazel] rosetta_models. one build file for dozens of src files

- src/lib/quickcheck_lib/BUILD.bazel
- src/lib/rc_pool/BUILD.bazel
- src/lib/rose_tree/BUILD.bazel
- src/lib/rosetta_coding/BUILD.bazel
- src/lib/rosetta_lib/BUILD.bazel
- src/lib/rosetta_lib/test/BUILD.bazel
- src/lib/runtime_config/BUILD.bazel
A smaller batch, letters q -r, excluding rosetta_models, which is submitted separately since it contains over 70 files.
> [Bazel] batch 8, of 7 files (q-r, excluding rosetta_models)

- src/lib/secrets/BUILD.bazel
- src/lib/sgn/BUILD.bazel
- src/lib/sha256_lib/BUILD.bazel
- src/lib/signature_lib/BUILD.bazel
- src/lib/sparse_ledger_lib/BUILD.bazel
- src/lib/staged_ledger/BUILD.bazel
- src/lib/staged_ledger_diff/BUILD.bazel
- src/lib/state_or_error/BUILD.bazel
- src/lib/storage/BUILD.bazel
- src/lib/sync_handler/BUILD.bazel
- src/lib/sync_status/BUILD.bazel
- src/lib/syncable_ledger/BUILD.bazel
Files starting with s, except for those starting with 'snark' and a few others, which have already been PRed.
> [Bazel] batch 9, of 12 files (s)

- src/lib/telemetry/BUILD.bazel
- src/lib/test_genesis_ledger/BUILD.bazel
- src/lib/test_util/BUILD.bazel
- src/lib/time_simulator/BUILD.bazel
- src/lib/transaction_protocol_state/BUILD.bazel
- src/lib/transaction_status/BUILD.bazel
- src/lib/transaction_witness/BUILD.bazel
- src/lib/transition_chain_prover/BUILD.bazel
- src/lib/transition_chain_verifier/BUILD.bazel
- src/lib/transition_handler/BUILD.bazel
- src/lib/transition_router/BUILD.bazel
- src/lib/trust_system/BUILD.bazel
- src/lib/truth/BUILD.bazel
Letter t, except for transition_frontier, which will be submitted separately since it has a bunch of subpackages.
> [Bazel] batch 10, of 13 files, t (except transition_frontier)

- src/lib/network_peer/BUILD.bazel
- src/lib/network_pool/BUILD.bazel
- src/lib/node_addrs_and_ports/BUILD.bazel
- src/lib/non_empty_list/BUILD.bazel
- src/lib/non_zero_curve_point/BUILD.bazel
- src/lib/one_or_two/BUILD.bazel
- src/lib/otp_lib/BUILD.bazel
- src/lib/outside_hash_image/BUILD.bazel
- src/lib/parallel/BUILD.bazel
- src/lib/parallel_scan/BUILD.bazel
- src/lib/participating_state/BUILD.bazel
- src/lib/pedersen_lib/BUILD.bazel
- src/lib/perf_histograms/BUILD.bazel
- src/lib/pipe_lib/BUILD.bazel
- src/lib/pokolog/BUILD.bazel
- src/lib/proof_carrying_data/BUILD.bazel
- src/lib/protocol_version/BUILD.bazel
- src/lib/prover/BUILD.bazel
A slightly larger batch.  pickles and ppxes have already been PRed.
> [Bazel] batch 7, of 18 files (n - p)

- src/lib/empty_hashes/BUILD.bazel
- src/lib/exit_handlers/BUILD.bazel
- src/lib/fake_network/BUILD.bazel
- src/lib/file_system/BUILD.bazel
- src/lib/filtered_external_transition/BUILD.bazel
- src/lib/gadt_lib/BUILD.bazel
- src/lib/genesis_constants/BUILD.bazel
- src/lib/genesis_ledger/BUILD.bazel
- src/lib/genesis_ledger_helper/BUILD.bazel
- src/lib/genesis_proof/BUILD.bazel
- src/lib/global_signer_private_key/BUILD.bazel
- src/lib/gossip_net/BUILD.bazel
- src/lib/graphql_lib/BUILD.bazel
Files beginning with e through g
> [Bazel] batch 4, of 13 files, (e - g)

- src/nonconsensus/coda_compile_config/BUILD.bazel
- src/nonconsensus/coda_numbers/BUILD.bazel
- src/nonconsensus/currency/BUILD.bazel
- src/nonconsensus/data_hash_lib/BUILD.bazel
- src/nonconsensus/hash_prefix_states/BUILD.bazel
- src/nonconsensus/hex/BUILD.bazel
- src/nonconsensus/mina_base/BUILD.bazel
- src/nonconsensus/non_zero_curve_point/BUILD.bazel
- src/nonconsensus/outside_hash_image/BUILD.bazel
- src/nonconsensus/quickcheck_lib/BUILD.bazel
- src/nonconsensus/random_oracle/BUILD.bazel
- src/nonconsensus/rosetta_coding/BUILD.bazel
- src/nonconsensus/rosetta_lib/BUILD.bazel
- src/nonconsensus/rosetta_lib/test/BUILD.bazel
- src/nonconsensus/sgn/BUILD.bazel
- src/nonconsensus/signature_lib/BUILD.bazel
- src/nonconsensus/snark_bits/BUILD.bazel
- src/nonconsensus/snark_params/BUILD.bazel
- src/nonconsensus/unsigned_extended/BUILD.bazel
All BUILD.bazel files under `src/nonconsensus`.
> [Bazel] nonconsensus, 19 files

- src/lib/unix_timestamp/BUILD.bazel
- src/lib/unsigned_extended/BUILD.bazel
- src/lib/user_command_input/BUILD.bazel
- src/lib/verifier/BUILD.bazel
- src/lib/visualization/BUILD.bazel
- src/lib/web_client_pipe/BUILD.bazel
- src/lib/web_request/BUILD.bazel
- src/lib/with_hash/BUILD.bazel
- src/lib/work_selector/BUILD.bazel
Last batch from `src/lib`.  zexe_backend has already been PRed.
> [Bazel] batch 11, with 9 files, (u-z)

- src/lib/transition_frontier/BUILD.bazel
- src/lib/transition_frontier/extensions/BUILD.bazel
- src/lib/transition_frontier/frontier_base/BUILD.bazel
- src/lib/transition_frontier/full_frontier/BUILD.bazel
- src/lib/transition_frontier/persistent_frontier/BUILD.bazel
- src/lib/transition_frontier/persistent_root/BUILD.bazel
- src/lib/transition_frontier/tests/BUILD.bazel
One package and six subpackages.
> [Bazel] transition_frontier and subpackages

- src/lib/precomputed_values/BUILD.bazel
- src/lib/precomputed_values/gen_values/BUILD.bazel
Only two files, but involving genrule to generate a file and then compile it.
> [Bazel] precomputed_values, precomputed_values/gen_values

- src/lib/memory_stats/BUILD.bazel
- src/lib/merkle_address/BUILD.bazel
- src/lib/merkle_ledger/BUILD.bazel
- src/lib/merkle_ledger_tests/BUILD.bazel
- src/lib/merkle_list_prover/BUILD.bazel
- src/lib/merkle_list_verifier/BUILD.bazel
- src/lib/merkle_mask/BUILD.bazel
- src/lib/mina_graphql/BUILD.bazel
- src/lib/mina_lib/BUILD.bazel
- src/lib/mina_networking/BUILD.bazel
- src/lib/mina_user_error/BUILD.bazel
Batch of 11 files starting with m, except for mina_base, which will be submitted separately, and mina_metrics, which has already been submitted.
> [Bazel] batch 6, of 11 files (m, except for mina_base)

- src/app/archive/BUILD.bazel
- src/app/archive/archive_lib/BUILD.bazel
- src/app/archive/archive_lib/graphql_query/BUILD.bazel
Three build files for archive app and subpkgs.
> [Bazel]  src/app/archive build files

- src/app/best_tip_merger/BUILD.bazel
- src/app/best_tip_merger/best_tip_merger.ml
CAVEAT: includes one small change to a source file, without which the build fails under Bazel.
> [Bazel] app: best_tip_merger. includes src code change

- src/app/cli/src/BUILD.bazel
- src/app/cli/src/init/BUILD.bazel
- src/app/cli/src/tests/BUILD.bazel
> [Bazel] app: cli

- src/app/client_sdk/BUILD.bazel
- src/app/client_sdk/tests/BUILD.bazel
> [Bazel] app: client_sdk
