MinaProtocol/mina

- src/app/rosetta/lib/account.ml
- src/app/rosetta/lib/block.ml
Changes the `/block` and `/account` endpoints of Rosetta according to the recent archive schema changes. Closes #11846 and #10729.
List of changes:
- `/account` endpoint:
- Simplified the queries and removed fallback queries, since now you can always retrieve the nonce from the `accounts_accessed` table.
- `/block` endpoint:
- Fixed some typos in the queries.
- Account creation fees are now retrieved from the new `accounts_created` table.
- Common:
- Fixed the joins with the `public_keys` table that should go through the `account_identifiers` table first.
This was tested by comparing the API responses with the expected output based on an archive dump from testnet and also with the expected output from a sandbox with operations emitted by us. It was also tested to some extent using the …
> Rosetta: endpoint changes to support legacy tx support.

- graphql_schema.json
- src/lib/mina_graphql/mina_graphql.ml
Enables retrieving the `provedState` flag from an account via graphql. This is needed to support the currently unimplemented `isProved` precondition in snarkyjs.
note: this is stacked on top of https://github.com/MinaProtocol/mina/pull/12166 (bringing `rampup` up to date with `develop`)
> Add provedState field to graphQL account

- src/lib/transaction_snark/transaction_snark.ml
This PR reduces the domain size of the 'trivial zkApp'.
This is useful for speeding up testing in unit tests, as well as improving performance of the zkApp integration tests. The speed-up is approximately 4x on my machine.
Checklist:
> Reduce cost of trivial zkApp for tests

- flake.lock
- nix/README.md
- nix/ocaml.nix
- Update opam-nix to support `withFakeOpam = false`
- Add instructions for VSCode, Vim and Emacs to the Nix README
- Add a note about shell inits to the Troubleshooting section
> Update opam-nix, add per-editor instructions to Nix readme

- src/lib/mina_base/account_update.ml
- src/lib/mina_base/zkapp_command.ml
Fixes #12122
Still needs a test
> Uses vks from earlier account updates if present

- src/app/cli/src/init/transaction_snark_profiler.ml
- src/lib/mina_base/user_command.ml
- src/lib/mina_base/zkapp_command.ml
- src/lib/mina_generators/user_command_generators.ml
- src/lib/network_pool/transaction_pool.ml
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/verifier/common.ml
This PR replaces the non-descriptive `option` type with an `Or_error.t`, containing information about the specific error that has occurred.
This makes debugging easier, and gives better feedback to users that attempt to send invalid transactions.
Checklist:
> Improve error messages around invalid zkApp commands

- src/app/archive/lib/test.ml
- src/lib/mina_base/fee_transfer.ml
- src/lib/mina_base/fee_transfer_intf.ml
- src/lib/mina_base/payment_payload.ml
- src/lib/mina_base/payment_payload.mli
- src/lib/mina_base/signed_command_payload.ml
Fix remaining warnings 16.
This is done by making the last non-optional labeled argument into a non-labeled one, instead of adding an extra `()`  argument.
There shouldn't be any warnings generated by compiling `dune build src/app/cli/src/mina.exe --profile=dev`
> Fix warnings 16

- src/app/archive/create_schema.sql
Add a `UNIQUE` constraint for the `epoch_data` table of the archive database.
This is similar to the PR against `compatible`, #12292, except that the table now has more columns. @nholland94 indicates that there may be rare cases where the epoch length may be different, with other columns otherwise identical. For simplicity, the constraint is against all the columns in the table, except the id.
> epoch_data UNIQUE constraint

- src/app/extract_blocks/sql.ml
Add missing `min_window_density` and `total_currency` fields to `blocks` queries for the `extract_blocks` app.
While that fixes the issue reported in #12127, the app does not succeed with dumps from the `berkeley` testnet, because the `authorization_kind` column does not exist in the `account_update_body` table in the dumps, while it does exist in the current schema. Also, the `command_type` columns for user and internal commands are still named `typ` in the dumps.
Closes #12127.
> Extract blocks, add missing fields to block queries

- src/app/rosetta/ocaml-signer/dune
- src/app/rosetta/ocaml-signer/signer_cli.ml
This PR provides a way to read a private key from a file and display it as hexadecimal suitable for rosetta (using the `Rosetta_coding.Coding.of_scalar` function).
I did not find an entry point to this function so I added one to the `ocaml-signer` binary (as it already does related things).
This is needed in order to use the `prefunded_accounts` feature of `rosetta-cli` and have it automatically use funds from a pre-existing account.
This was tested by running the `rosetta-cli` construction tests with the produced hex private key.
> Display key from private-key file as hexadecimal 

- src/lib/mina_base/account_update.ml
This is to ease compatibility of the hash inputs in JS, without having to add mechanisms to have special annotations for high-level types
Slack thread: https://o1-labs.slack.com/archives/C02ASV6BZCY/p1667999296834509
Snarkyjs companion: https://github.com/o1-labs/snarkyjs/pull/622
> Change permissions hash input

- src/lib/crypto/kimchi_backend/common/plonk_dlog_proof.ml
- src/lib/crypto/kimchi_bindings/js/bindings.js
- src/lib/crypto/kimchi_bindings/stubs/kimchi_types.ml
- src/lib/crypto/kimchi_bindings/stubs/src/main.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_proof.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_proof.rs
- src/lib/crypto/kimchi_bindings/wasm/Cargo.lock
- src/lib/crypto/kimchi_bindings/wasm/Cargo.toml
- src/lib/crypto/kimchi_bindings/wasm/src/lib.rs
- src/lib/crypto/kimchi_bindings/wasm/src/plonk_proof.rs
- src/lib/crypto/kimchi_bindings/wasm/src/wasm_flat_vector.rs
- src/lib/crypto/kimchi_bindings/wasm/src/wasm_ocaml_serde/de.rs
- src/lib/crypto/kimchi_bindings/wasm/src/wasm_ocaml_serde/mod.rs
- src/lib/crypto/kimchi_bindings/wasm/src/wasm_ocaml_serde/ser.rs
This PR
* updates the proof-systems submodule to include https://github.com/o1-labs/proof-systems/pull/833, which switches to using a `PointEvaluations` wrapper for evaluations.
- it would be nice to propagate this change upwards into pickles at some point; this PR does not seek to do that
* updates the bindings.
The most notable part of this PR is the partial new approach to converting rust values in WASM to js_of_ocaml-compatible values in javascript: for the `ProofEvaluations` struct, we now use a special serde `Serializer` / `Deserializer` pair instead of performing the manual conversions. This comes with some caveats; to quote commit 25dad1ee2e6f0e718f03d6e225fcb5b54f901950:
>    This commit copies the strategy of serde_wasm_bindgen, using serde to
>    emit JS values that match the …
> Update proof-systems for `PointEvaluations`

- src/lib/crypto/kimchi_bindings/wasm/src/wasm_ocaml_serde/ser.rs
fix this error:
```
error[E0015]: cannot call non-const fn `serde_wasm_bindgen::Serializer::new` in constant
--> src/wasm_ocaml_serde/ser.rs:129:14
|
129 |         Self(serde_wasm_bindgen::Serializer::new())
|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: calls in constant functions are limited to constant functions, tuple structs
For more information about this error, try `rustc --explain E0015`.
warning: `plonk_wasm` (lib) generated 12 warnings
error: could not compile `plonk_wasm` due to previous error; 12 warnings emitted
Error: Compiling your crate to WebAssembly failed
```
> [crypto] fix rust bug

- src/lib/snarky_js_bindings/lib/dune
- src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
This exposes an additional option to snarkyjs in `sign_field_element`, to enable signing with both "testnet" and "mainnet" network ids. In support of https://github.com/o1-labs/snarkyjs/pull/612
> SnarkyJS: expose mainnet signatures

- src/nonconsensus/snark_params/tick.ml
Remove the `Tests` module from a nonconsensus source file. That module will trip an error in the version linter, which is expecting only `Vn` modules. The module is a hangover from the days of `%%versioned_asserted` (replaced by assertions on individual types within versioned types).
This particular error is what led to the earlier "skip list" effort.
> Remove Tests module

- buildkite/scripts/rosetta-integration-tests.sh
- src/app/rosetta/rosetta-cli-config/config.json
- src/app/rosetta/rosetta-cli-config/mina.ros
This PR:
- Updates the `rosetta-cli` configuration files to add tests for the construction API.
- Updates the `rosetta-integration-tests.sh` script to run these tests in the CI.
Changes:
- The `mina.ros` file describe the construction api tests and is updated to create accounts and generate payment transactions.
- The `rosetta-cli` configuration files now contain some placeholder that must be replaced after the sandbox is generated.
- Tests are run against `mina-dev` because `rosetta-cli` assumes we are using a `testnet` (See [here](https://github.com/coinbase/rosetta-sdk-go/blob/master/keys/signer_pallas.go#L22)).
Tests:
- The CI job may still fails at a later step (it is left optional) but we can see that the construction tests are successful …
> Rosetta construction tests

- src/lib/genesis_ledger_helper/lib/genesis_ledger_helper_lib.ml
- src/lib/mina_base/zkapp_account.ml
Limit length of zkapp URIs to 255 characters, using the same mechanism used for symbol tokens. That is, introduce a length check for `Bin_prot`, sexp, and yojson deserializations, and a check when reading runtime configurations.
Version linter error is expected, and benign.
Closes #12296.
> Limit length of zkapp URIs

- flake.lock
- flake.nix
- nix/javascript.nix
- nix/misc.nix
This PR adds  a `zkapp-impure` devShell, which contains `nmp` and other dependencies needed to compile snarkyjs 
as well as compile and deploy zkapps.
I needed to update the `nixpkgs` version because `binaryen` did not compile with the previous one (I also updated the whole `flake.lock`  as IIUC it should be done from time to time).
It seems that in the recent `nixpkgs`  there is a security issue with `erlangR22` (see [here](https://buildkite.com/tweag-mina-demo/mina/builds/4105#0185072f-35fa-4e0c-b249-28cf8b2daea2/101-104)) so I switched it to `erlangR23` in `misc.nix`.
Closes #12218
> Add dependencies for developing zkapps to nix shell

- README-sandbox.md
Fix some confusing phrasings in the README and make it clearer.
> Docs: Clarify the documentation on the sandbox network.

- flake.lock
- flake.nix
- nix/docker.nix
- nix/ocaml.nix
- src/lib/crypto/kimchi_bindings/stubs/Cargo.lock
Currently, Nix-build docker images have Unix epoch as their creation date. This
is done for reproducibility, but it's not convenient. Set the commit date as the
image creation date instead.
> Nix: mark docker image creation time

- graphql_schema.json
- src/app/rosetta/lib/account.ml
- src/app/rosetta/lib/block.ml
- src/app/rosetta/rosetta-cli-config/README.md
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_lib/mina_lib.mli
This PR fixes two bugs, which caused balance reconciliation failures in `rosetta-cli` tests:
* `/account/balance` when asked for a balance at a block before any transaction involving the queried account was performed, Rosetta reported the most recent balance;
* `/block` only reported internal operations when there had been an account creation fee associated with it.
In order to fix the first bug, `genesis_balance` for each account can now be obtained from GraphQL. `genesis_balance` describes the initial shape of an account it it was present in the genesis ledger or is `null` otherwise.
Manually testing changes:
Set up Rosetta server (this is the easiest to do in sandbox mode), generate some transactions and run `rosetta-cli check:data` against the blockchain. Instructions on how to do it …
> Fix problems with balance reconciliation in rosetta-cli tests

- src/app/rosetta/lib/block.ml
Add support for zkApps balance changing operations to the Rosetta Data API. With this, these operations are now included in the `/block` endpoint response.
Each zkApp command is encoded as a transaction, with the respective fee payment and balance updates encoded as operations part of that transaction.
This was tested in a local sandbox node by deploying several zkApps, interacting with them, and emitting payment operations from within those zkApps. The responses to some calls to the API were manually compared to the expected response. The `rosetta-cli` tool was also used, and all tests in the `check:data` test suite passed successfully.
The CI will be updated on a different PR to include this test suite.
Closes #11847.
> Add support for zkapps balance changing operations to Rosetta Data API

- nix/README.md
Bug discovered by and debugged with @bkase . There doesn't seem to be a good
fix, since the stack limit size is hard-limited in the kernel on macOS.
> Nix README: Add a troubleshooting note about Argument list too long

- buildkite/src/Command/TestExecutive.dhall
* This PR changes the build container that is used by the SnarkyJS integration test. Currently, it is using a standard build container that has old dependencies (and not the updated `integration` container). 
* This change has been tested using the following manual CI pass: 
https://buildkite.com/o-1-labs-2/mina/builds/26363#_
Checklist:
- [NA] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [NA] Serialized types are in stable-versioned modules
* Closes #12400
> initial branch push

- README-sandbox.md
While onboarding some new tem members, we discovered that the README on running a sandboxed Mina daemon was missing some important information. This PR expands the README to give that information and explain why it's important.
> Expand the README on running a sandbox node.

- buildkite/src/Constants/ContainerImages.dhall
- opam.export
- src/app/archive/lib/dune
- src/app/archive/lib/processor.ml
- src/app/archive/zkapp_tables.sql
In the archive db schema, allow the verification key in zkApp accounts to be NULLable; it's an option in the OCaml code.
When adding the tokens used in a block to the db, topologically sort them, so that if token B's owner is an account id with token A, add token A first.
There were related issues with the Berkeley testnet that these changes attempt to fix.
> Verification key NULLable; topo sort tokens

- src/lib/pickles/step_verifier.ml
- src/lib/pickles/verify.ml
This PR
* fixes an off-by-1 error, where we were not accounting for the largest step domain size in side-loaded proofs
* adds a check for the (alleged) step domain size in the `Pickles.verify` function, to ensure that we don't accept proofs with a larger domain size than the maximum that we support.
Tests elided, TODO later.
Checklist:
- Nope!
> Fix off-by-1 error in pickles, check domain size in verify

- src/lib/mina_base/signed_command_payload.mli
- src/lib/snarky_js_bindings/lib/dune
- src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
- src/lib/snarky_js_bindings/snarky_js_constants.ml
- src/lib/transaction/transaction_hash.mli
Companion of https://github.com/o1-labs/snarkyjs/pull/666
This exposes a new module called `Test` from OCaml, which currently only contains function related to transaction hashing. These are used in https://github.com/o1-labs/snarkyjs/pull/666 to check correctness of the JS implementation of tx hashes. Two small interface changes in the main Mina code base had to be made.
> Mina-signer: Transaction hash

- src/lib/crypto/snarky_tests/snarky_tests.ml
Complement of https://github.com/o1-labs/snarky/pull/730
This doesn't really exercise ALL paths, we had a bug where due to the global state and the `is_running` bool we could produce impure computations (create constraints) in out-of-circuit functions: the `out_of_circuit_constraint` function in this PR would not raise an exception if ran after a circuit was run.
Perhaps we should run the out-of-circuit tests twice, once before all other tests, and once after all of the other tests. But this presumes that tests are never ran in parallel, which might change in the future with the new ocaml version?
> [crypto][snarky] implement outside of circuit tests

- buildkite/src/Command/CheckGraphQLSchema.dhall
- buildkite/src/Command/TestExecutive.dhall
- buildkite/src/Jobs/Test/CheckGraphQLSchema.dhall
- buildkite/src/Jobs/Test/TestnetIntegrationTests.dhall
* This PR makes changes to the dhal configurations for the `GraphQL Schema` and `Snarky Integration` tests. Currently in certain PRs these tests stick in a permanent pending state because they are waiting on older "stretch" debian builds that are no longer part of the pipeline. These tests have been updated to use newer "bullseye" Debian versions which are included and supported.
* This changed has been tested using a manual run of the Buildkite CI pipeline. The two tests correctly show updated dependencies and pass as expected.
Checklist:
- [ NA ] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [ NA ] Tests were …
> Buidlkite test deps fix for GraphQL Schema and Snarky Integration tests

- src/app/cli/src/init/transaction_snark_profiler.ml
- src/lib/mina_base/transaction_status.ml
- src/lib/mina_ledger/dune
- src/lib/mina_ledger/ledger.ml
- src/lib/mina_wire_types/mina_base/mina_base_transaction_status.ml
- src/lib/transaction_logic/mina_transaction_logic.ml
- src/lib/transaction_logic/zkapp_command_logic.ml
- src/lib/transaction_snark/test/multisig_account/multisig_account.ml
- src/lib/transaction_snark/test/zkapps_examples/actions/actions.ml
- src/lib/transaction_snark/test/zkapps_examples/add_events/add_events.ml
- src/lib/transaction_snark/test/zkapps_examples/calls/calls.ml
- src/lib/transaction_snark/test/zkapps_examples/empty_update/empty_update.ml
- src/lib/transaction_snark/test/zkapps_examples/initialize_state/initialize_state.ml
- src/lib/transaction_snark/transaction_snark.ml
- src/lib/zkapps_examples/dune
- src/lib/zkapps_examples/zkapps_examples.ml
When calling `Zkapp_command_logic.apply`, for each account update, check its verification key hash against the hash in the account in the local state.
For the `Zkapps_examples` tests, each account update is given a 0 verification key hash. We patch those account updates with the hash from the corresponding account in the test ledger, if that ledger is given, and with any hashes from keys that are `Set` in preceding account updates.
Closes #12392.
> Check verification key hash in `apply`

- src/lib/snarky_js_bindings/dune
This PR builds upon #12513, adding inline source maps for the OCaml code.
They probably shouldn't be inline, but I probably also shouldn't have had to suggest and do this :man_shrugging: 
Checklist:
> Generate OCaml source maps

- buildkite/scripts/test-snarkyjs-bindings.sh
- scripts/build-snarkyjs-node.sh
- scripts/update-snarkyjs-bindings.sh
- src/lib/snarky_js_bindings/dune
This follows up on https://github.com/MinaProtocol/mina/pull/12514:
* makes the source maps not inline, but a separate file
* ship source maps in the release build, not only for development
* add `--enable-source-maps` to the snarkyjs `run` script: https://github.com/o1-labs/snarkyjs/pull/697
TODOs not addressed here:
* have an easily discoverable way of running TS files in zk-CLI projects that uses `--enable-source-maps`, so that most developers benefit from this
* source maps in the web build
> Non-inline source map for snarkyjs node build

- CODEOWNERS
* Transfer responsibility for Rosetta project from O(1) to Mina Foundation.
> Rosetta: MF takes responsibility for the project.

- src/lib/cli_lib/render.ml
Don't manually pad input with strings, use built-in specifiers in format string.
> Pad with format strings

- src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
companion of https://github.com/o1-labs/snarkyjs/pull/681
> snarkyjs assertion long forms

- src/lib/block_storage/block_storage.ml
- src/lib/mina_net2/mina_net2.ml
- src/libp2p_ipc/libp2p_ipc.ml
- src/libp2p_ipc/libp2p_ipc.mli
Add an extra unit () parameter to function create_libp2p_config to avoid the emission of warning 16.
> Libp2p_ipc: remove warning 16

- src/app/rosetta/lib/construction.ml
- src/lib/rosetta_lib/transaction.ml
closes #8084 Add checkfee method to ensure that when request is sent to Rosetta Parse endpoint that an error will be thrown (for both signed and unsigned transactions) if the minimum fee is too small.
> #8084 - Add Check Fee functionality for Parse Endpoint in Rosetta Construction API 

- buildkite/scripts/export-git-env-vars.sh
The introduction of a `test-rosetta` tag has broken CI. This PR attempts to work around it without modifying the existing git tags.
Checklist:
> Fix: Skip over tags with a non-numeric prefix

- src/app/cli/src/init/mina_run.ml
- src/app/test_executive/zkapps.ml
- src/lib/integration_test_lib/event_type.ml
- src/lib/integration_test_lib/event_type.mli
- src/lib/mina_base/sparse_ledger_base.mli
- src/lib/snark_work_lib/work.ml
- src/lib/snark_worker/dune
- src/lib/snark_worker/functor.ml
- src/lib/snark_worker/intf.ml
- src/lib/snark_worker/rpcs.ml
- src/lib/snark_worker/snark_worker.ml
- src/lib/snark_worker/snark_worker.mli
- src/lib/transaction_witness/transaction_witness.ml
- src/lib/transaction_witness/transaction_witness.mli
This PR breaks out a commit from #12342, as part of the effort to home in on the CI failure there.
This tweaks the test executive to give more details about the actual error and the snark work statement when we see a prover failure.
Checklist:
> Test executive: log the actual error, work spec from snark work failures

- src/app/test_executive/zkapps.ml
- src/lib/integration_test_lib/event_type.ml
This PR fixes a bug where outgoing snark work was logged as incoming snark work in the test executive.
Checklist:
> Trivial: fix snark work logging in test_executive

- src/app/libp2p_helper/src/libp2p_helper/main.go
This removes the following error messages at Mina startup:
```
libp2p_helper: failed to set log level debug for mplex: error: No such logger
libp2p_helper: failed to set log level debug for stream-upgrader: error: No such logger
libp2p_helper: failed to set log level debug for discovery: error: No such logger
libp2p_helper: failed to set log level info for addrutil: error: No such logger
```
> Trivial: Remove `setLogLevel` for subsystems that no longer exist in libp2p_helper

- src/app/cli/src/init/mina_run.ml
- src/lib/integration_test_lib/event_type.ml
- src/lib/integration_test_lib/event_type.mli
- src/lib/snark_worker/snark_worker.ml
- src/lib/snark_worker/snark_worker.mli
This PR stops logging the txn snark statement on failure. This ensures that the log messages are sufficiently small to be ingested by stackdriver, allowing them to be consumed as structured logs and thus raised to the test executive.
You can see this working in practice [here](https://buildkite.com/o-1-labs-2/mina/builds/26922#0185f445-ab06-4c8a-ab9f-f1d5f2cd793d).
Checklist:
> Trivial: fix snark work failure logging in test executive

- src/lib/mina_base/zkapp_command.ml
- src/lib/transaction_snark/transaction_snark.ml
#12554 does the first pass to second pass ledger transition (in the local state) within the zkapp application logic and so fee payers can be combined with another update when generating snarks 
Checklist:
* Closes #0000
> Revert to having fee payer possibly bundled with another update

- src/lib/mina_generators/zkapp_command_generators.ml
- src/lib/mina_generators/zkapp_command_generators.mli
- src/lib/transaction_snark/test/zkapp_fuzzy/zkapp_fuzzy.ml
There's 2 fixes in this PR
1. The` generation of failed zkapps would always include `proof` authorization, so we should always use zkapp for that.
2. added an optional `global_slot` argument for the zkapp_command_generator, which is meant to be the global_slot that we apply the transactions.
With those fixes the fuzzy zkapp tests pass on my machine.
Checklist:
* Closes #12590
> fix the fuzzy zkapp test

- src/app/archive/drop_tables.sql
- src/app/archive/lib/load_data.ml
- src/app/archive/lib/processor.ml
- src/app/archive/zkapp_tables.sql
In the archive database schema, rename:
- `zkapp_state_data` to `zkapp_field`
- `zkapp_state_data_array` to `zkapp_field_array`
`zkapp_field` contains data not only for app states, but also for events and actions.
Fixed some formatting, deleted some out-of-date comments.
> Rename state_data in table names to field

- src/app/cli/src/init/transaction_snark_profiler.ml
- src/lib/crypto/kimchi_bindings/stubs/kimchi_types.ml
- src/lib/mina_base/zkapp_command.ml
- src/lib/mina_ledger/ledger.ml
- src/lib/mina_ledger/ledger.mli
- src/lib/mina_ledger/sparse_ledger.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/snark_worker/prod.ml
- src/lib/staged_ledger/diff_creation_log.ml
- src/lib/staged_ledger/pre_diff_info.ml
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/transaction/transaction.ml
- src/lib/transaction_logic/dune
- src/lib/transaction_logic/mina_transaction_logic.ml
- src/lib/transaction_logic/zkapp_command_logic.ml
- src/lib/transaction_snark/test/util.ml
- src/lib/transaction_snark/transaction_snark.ml
- src/lib/transaction_snark/transaction_validator.ml
- src/lib/transaction_snark/transaction_validator.mli
- src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
- src/lib/transaction_witness/transaction_witness.ml
- src/lib/transaction_witness/transaction_witness.mli
- src/lib/transition_frontier/full_frontier/full_frontier.ml
Apply zkapp transactions in two phases. Apply all the simple commands and fee payer part of zkapp transactions and in the second phase apply the zkapp account updates
There's a couple of stubs in non-staged-ledger code, and a few small TODOs to fill in (many of which aren't actually important for testing)
> Support 2-phase transaction apply in staged ledger

- flake.lock
- nix/ocaml.nix
This PR bumps `ocaml-lsp-server` to the latest version. It fixes some issues I was personally having while running `dune build` in watch mode.
I tested it in my VSCode setup, and all is okay. It shouldn't break anyone's setup, but I'll request someone else to test it using (at least) emacs and vim.
> Bump ocaml-lsp-server version

- src/lib/transaction_snark/test/access_permission/transaction_snark_test_access_permission.ml
- src/lib/transaction_snark/test/account_timing/account_timing.ml
- src/lib/transaction_snark/test/app_state/app_state.ml
- src/lib/transaction_snark/test/delegate/delegate.ml
- src/lib/transaction_snark/test/party_preconditions/party_preconditions.ml
- src/lib/transaction_snark/test/permissions/permissions.ml
- src/lib/transaction_snark/test/test_zkapp_update.ml
- src/lib/transaction_snark/test/token_symbol/token_symbol.ml
- src/lib/transaction_snark/test/util.ml
- src/lib/transaction_snark/test/util.mli
- src/lib/transaction_snark/test/verification_key/verification_key.ml
- src/lib/transaction_snark/test/voting_for/voting_for.ml
- src/lib/transaction_snark/test/zkapp_deploy/zkapp_deploy.ml
- src/lib/transaction_snark/test/zkapp_fuzzy/zkapp_fuzzy.ml
- src/lib/transaction_snark/test/zkapp_payments/zkapp_payments.ml
- src/lib/transaction_snark/test/zkapp_uri/zkapp_uri.ml
- src/lib/transaction_snark/test/zkapps_examples/initialize_state/initialize_state.ml
The timed account test in the zkApp fuzzy tests was failing in nightly tests, because the expected `Source_min_balance_violation` failure occurred during the first pass for zkApp application, which wasn't detected.
Add the expected failure test for the first pass. If the expected failure occurs, return without running the second pass, because we don't have all the statements to do so.
The `expected_failure` now includes the pass where the failure is expected to occur.
Other than the new failure check, most of the diff is from the re-formatting occasioned by the `with_return` that wraps existing code.
Tested locally by running the timed account test.
> Check for expected failure on first pass

- src/lib/crypto/kimchi_backend/common/plonk_constraint_system.ml
This adds a `Raw` snarky constraint to let us manually construct kimchi gates for tests.
Checklist:
> Add Raw gate constructor to Plonk_constraint_system

- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
- src/lib/ppx_version/runtime/shapes.ml
- src/lib/ppx_version/tools/print_binable_functors.ml
- src/lib/ppx_version/versioned_module.ml
- src/lib/ppx_version/versioned_type.ml
- src/lib/ppx_version/versioned_util.ml
Add a string representation of types to the output of `dump-type-shapes`, which the version linter can use when reporting errors.
Sample line of output: 
```
src/lib/pickles_base/proofs_verified.ml:Pickles_base__Proofs_verified.Stable.V1.t, 9d312ca152cee7839dbdfc6bef04ae56, (Exp(Variant((N0())(N1())(N2())))), | N0  | N1  | N2 
```
> Add types to shape dump

- src/app/libp2p_helper/src/libp2p_helper/app.go
Bumped the stream response chunk size from 4kb -> 128kb, and bumped the internal IPC message queue from 64 -> 4096.
> Tune parameters for libp2p ipc

- graphql_schema.json
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/mina_lib/mina_lib.ml
Fixes #12622. Also includes a fix for a separate bug that was discovered in the same query where we always included the root block into the best chain.
> Fix bestChain graphql query

- src/lib/consensus/proof_of_stake.ml
- src/lib/currency/currency.ml
- src/lib/data_hash_lib/state_hash.ml
- src/lib/mina_base/ledger_hash0.ml
- src/lib/mina_base/pending_coinbase.ml
- src/lib/mina_base/receipt.ml
- src/lib/mina_base/signature.ml
- src/lib/mina_base/signed_command.ml
- src/lib/mina_base/state_body_hash.ml
- src/lib/mina_base/zkapp_state.ml
- src/lib/mina_ledger/ledger.ml
- src/lib/network_pool/transaction_pool.ml
- src/lib/pickles/composition_types/digest.ml
- src/lib/pickles/proof.ml
- src/lib/pickles/reduced_messages_for_next_proof_over_same_field.ml
- src/lib/pickles_types/vector.ml
- src/lib/transaction_snark_work/transaction_snark_work.ml
- src/nonconsensus/snark_params/tick.ml
In the code, type equalities were asserted in two ways:
- via an `_unused` type declaration with a `constraint`
- via a value defined with `Type_equal.T`, sometimes wrapped in a function
On grounds that "neatness counts" (even if it doesn't), make all those assertions uniform, either:
- `let (_ : (t1,t2) Type_equal.t) = Type_equal.T`, or
- `let _type_equal : type a. (a t1,a t2) Type_equal.t = Type_equal.T` for types with a parameter
The second form requires a name for some reason, a single underscore gives a syntax error.
> Housekeeping: Uniform type equality assertions

- src/app/test_executive/zkapps_nonce_test.ml
In zkApps nonce integration test, bump soft timeout to produce a block from default 3 slots to 5 slots. That timeout was being triggered often in CI.
Also, a little code reorganization so that the existing `with_timeout` is restricted in scope, so it can't be confused with the new one introduced here.
> Bump block production timeout in zkApps nonce test

- src/lib/crypto/kimchi_backend/gadgets/runner/dune
- src/lib/crypto/kimchi_backend/gadgets/runner/example/dune
- src/lib/crypto/kimchi_backend/gadgets/runner/example/example.ml
- src/lib/crypto/kimchi_backend/gadgets/runner/runner.ml
This PR creates a small test runner for gadgets.
This explicitly doesn't use pickles, so that we can still test the new kimchi custom gates before their implementation in pickles is finished.
See the example in `example.ml` for a small test circuit. This example can be run with `dune exec src/lib/crypto/kimchi_backend/gadgets/runner/example/example.exe`.
Checklist:
> Add a test runner for small gadget circuits.

- graphql_schema.json
- src/app/cli/src/init/client.ml
- src/app/cli/src/init/graphql_queries.ml
- src/lib/mina_graphql/mina_graphql.ml
The `tokenOwner` query returns a full account, rather than just an account id. Add the field `tokenId` to accounts, so the result is compatible with existing queries. Deprecate the `token` field in accounts in favor of this new field.
This change makes it easy to find token symbols for custom tokens, as requested in #12425.
> tokenOwner returns full account

- src/lib/transaction_logic/mina_transaction_logic.ml
- src/lib/transaction_logic/zkapp_command_logic.ml
- src/lib/transaction_snark/test/app_state/app_state.ml
- src/lib/transaction_snark/test/delegate/delegate.ml
- src/lib/transaction_snark/test/dune
- src/lib/transaction_snark/test/fee_payer/dune
- src/lib/transaction_snark/test/fee_payer/fee_payer.ml
- src/lib/transaction_snark/test/permissions/permissions.ml
- src/lib/transaction_snark/test/test_zkapp_update.ml
- src/lib/transaction_snark/test/token_symbol/token_symbol.ml
- src/lib/transaction_snark/test/verification_key/verification_key.ml
- src/lib/transaction_snark/test/voting_for/voting_for.ml
- src/lib/transaction_snark/test/zkapp_uri/zkapp_uri.ml
`unmake_zkapp` sets the zkapp part of an account to `None` if it's the same as the default zkapp account.
In `Zkapp_transaction_logic`, the call to `unmake_zkapp` preceded the code that can update the zkApp URI. That made sense when the zkApp URI was not in the zkapp part of accounts.
Now that the zkApp URI is in the zkapp part of accounts, call `unmake_zkapp` after that URI is set.
> Move unmake_zkapp after zkApp URI is set

- src/lib/transaction_logic/mina_transaction_logic.ml
- src/lib/transaction_logic/zkapp_command_logic.ml
- src/lib/transaction_snark/test/app_state/app_state.ml
- src/lib/transaction_snark/test/delegate/delegate.ml
- src/lib/transaction_snark/test/dune
- src/lib/transaction_snark/test/fee_payer/dune
- src/lib/transaction_snark/test/fee_payer/fee_payer.ml
- src/lib/transaction_snark/test/permissions/permissions.ml
- src/lib/transaction_snark/test/test_zkapp_update.ml
- src/lib/transaction_snark/test/token_symbol/token_symbol.ml
- src/lib/transaction_snark/test/verification_key/verification_key.ml
- src/lib/transaction_snark/test/voting_for/voting_for.ml
- src/lib/transaction_snark/test/zkapp_uri/zkapp_uri.ml
https://github.com/MinaProtocol/mina/pull/12697 for rampup
Checklist:
* Closes #0000
> Move unmake_zkapp after zkApp URI is set (rampup)

- buildkite/scripts/helm-ci.sh
- buildkite/src/Jobs/Test/ArchiveNodeUnitTest.dhall
- buildkite/src/Lib/Cmds.dhall
Decided to use the environment variable for the checkout path to make the job commands more agnostic to different buildkite agent configurations.
> Change checkout path to corresponding environment variable

- src/app/archive/create_schema.sql
- src/app/archive/lib/extensional.ml
- src/app/archive/lib/load_data.ml
- src/app/archive/lib/processor.ml
- src/app/archive/zkapp_tables.sql
- src/app/extract_blocks/extract_blocks.ml
- src/app/replayer/replayer.ml
In archive db schema, revert uses of account identifiers where the token is implicitly the default; use just the public key. Using account identifiers introduces the possibility of error, and increases friction between the OCaml code and the archive database -- the default token has to be manually added.
Leave account identifiers where there is the possibility of a custom token, such as in the `accounts_accessed` table.
> Public keys only when default token implicit

- genesis_ledgers/berkeley.json
- nix/rust.nix
- src/lib/crypto/kimchi_bindings/stubs/Cargo.lock
- src/lib/crypto/kimchi_bindings/wasm/Cargo.lock
This is PR https://github.com/MinaProtocol/mina/pull/12739 merged into develop.
> This PR updates the proof-systems submodule to include https://github.com/o1-labs/proof-systems/pull/1013.
> 
> The combined_inner_product functionality that that PR updates is used internally by Pickles.verify, but was unvalidated on the kimchi side due to a duplicate version used in the tests. That PR combines the two implementations, ensuring that the version of the logic implemented by pickles matches the logic implemented by kimchi exactly.
Checklist:
> [Develop] Bump proof-systems for combined_inner_product fix to pickles

- src/app/archive/create_schema.sql
- src/app/archive/lib/dune
- src/app/archive/lib/extensional.ml
- src/app/archive/lib/processor.ml
- src/app/archive/lib/test.ml
- src/app/extract_blocks/extract_blocks.ml
- src/lib/consensus/intf.ml
- src/lib/consensus/proof_of_stake.ml
- src/lib/mina_caqti/mina_caqti.ml
These fields will be useful for chain selection by the archive API . See #12690.
> Add last VRF output and subwindow densities to blocks in archive

- src/lib/staged_ledger/staged_ledger.ml
- src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
Nodes failing to boostrap to the testnet with `Failed to find scan state for the transition...` error
Fix: Remove non-zkapp transactions when applying incomplete transactions to snarked ledger during bootstrap. This was interfering with the logic in `apply_ordered_txns_stepwise`
Explain how you tested your changes: Added a unit test that includes both payments and zkapp transactions
Checklist:
* Closes #0000
> Fix bootstrap failure (rampup)

- src/lib/transaction_logic/mina_transaction_logic.ml
- src/lib/transaction_snark/test/fee_payer/fee_payer.ml
This PR fixes the bug that has currently paused the Berkeley rampup testnet. It should be possible to resume the network by deploying one or more snark workers running this version of the daemon.
Checklist:
> [rampup] Fix fee payer local state ledger hack edge case

- src/lib/transaction_logic/test/dune
- src/lib/transaction_logic/test/supply_increase.ml
A property-based test has been added for the `supply_increase` function in `mina_transaction_logic.ml`. Due to the inability to create some of the private types the function takes, only the Command data type was modelled for the input.
* Closes #12573
> Test for supply_increase in mina_transaction_logic

- src/app/cli/src/init/client.ml
- src/lib/currency/currency.ml
- src/lib/currency/intf.ml
- src/lib/transaction_logic/mina_transaction_logic.ml
- src/lib/transaction_logic/zkapp_command_logic.ml
- src/lib/transaction_snark/transaction_snark.ml
In `Mina_transaction_logic` there's an extension of `Currency.Amount.Signed` which defines functions `is_pos` and `is_neg`. For 0 `is_pos` erroneously returns `true`. Moreover, the same functionality is already implemented correctly in the base currency library, so it should be imported from there. In the future we should probably remove these synonyms in favour of original function names.
* Refactor `Amount` out of `Mina_transaction_logic.Make` functor so that it can be tested.
* Replaced the definition with functions already defined in `Currency.Amount.Signed`.
* Wrote unit tests which fail before this change and pass afterwards.
Checklist: …
> [transaction_logic] Fix sign check bug in currency amount.

- src/lib/mina_base/account_update.ml
This PR makes `Account_update.Account_precondition.equal` treats equivalence as equality. 
I added 2 unit tests that would fail without my changes.
Checklist:
* Closes #0000
> Account precondition equality fix

- scripts/release-docker.sh
Fixes an issue in the logic to push images to docker hub, changing from "only publish stable builds" to "don't publish unstable builds", which now means alpha and beta and rampup and whatever other tagged releases will end up on docker hub like they always have.
> lk86/push-daemon-images Print debian releases

- src/lib/mina_base/test/zkapp_command/fee_related.ml
- src/lib/mina_base/zkapp_command.ml
Branched off another non-develop branch, so ignore all files other than `fee_related.ml` The other branch will be merged first.
* Property based tests for the following functions in `src/lib/mina_base/zkapp_command`:
1. `fee`
2. `fee_payer_pk`
3.  `fee_payer_account_update`
4. `fee_excess`
* Closes #12625
> Tests for fee related functions in Zk App Commands

- buildkite/src/Command/ConnectToTestnet.dhall
* This PR makes the "connect to Berkeley" CI test optional. This allows the test to fail without blockchain PRs.
* Documentation of the softfail behavior ca be found here: https://buildkite.com/docs/pipelines/command-step#soft-fail-attributes
* This change is being test by running within Buildkite CI.
Checklist:
- [NA] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [NA] Tests were added for the new behavior
- [NA] Serialized types are in stable-versioned modules
* Closes #12896
> add softfail to berkeley testnet test

- src/lib/mina_graphql/dune
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/signature_lib/unix/graphql_scalars.ml
Add mutations `schedulePayments` and `stopPayments` to ITN GraphQL server.
Example call to `schedulePayments`:
```
schedulePayments(input: {durationInMinutes: 10, transactionsPerSecond: 1.5, memo: "hello world", feeMax: "0.1", feeMin: "0.05", amount: "33", receiver: "B62qoRRDP58UWbfzQQP5jnePeyGQLdy57FHNYX5cHNzcLixHMUaa89R", senders: ["EKEz9oRCUiHPuRT3uSewV9rjMWSYKYVAgceam4F2mkb1x5oqA6yq"]})
```
The returned value is a "handle", which is a uuid, and can be provide as input to `stopPayments`.
Tested with a local network (had to temporarily disable the auth checking for that).
Closes #12819.
> Payments scheduler for ITN GraphQL server

- src/lib/logger/impl.ml
- src/lib/logger/impl.mli
This small PR simplifies a number of elements within Logger.Impl
- Use built-in format directives to print 2-digits number
- Define a pp function and use it in `Processor.Pretty.process`
- Remove some list iterations and some string allocations in `Processor.Pretty.process`
> Simpler Logger outputs

- src/lib/network_pool/batcher.ml
As requested by @lk86, this PR demotes the noisy network pool batcher logs from `info` to `debug`, to help clean up the daemon log output.
Checklist:
> Demote network pool batch size logs to debug

- buildkite/src/Jobs/Lint/Merge.dhall
* This edit adds a softfail status to the test "merges cleanup into compatible" for the Berkeley test branch
* This change has been tested within Buildkite CI to confirm the test change behaves as expected.
Checklist:
- NA Modified the current draft of release notes with details on what is completed or incomplete within this project
- NA Document code purpose, how to use it
- NA Serialized types are in stable-versioned modules
- NA Does this close issues? List them
> add softfail to "merges into compatible" test for Berkeley branch

- src/lib/currency/currency.ml
- src/lib/currency/intf.ml
- src/lib/mina_base/account.ml
- src/lib/mina_base/account_timing.ml
- src/lib/mina_base/test/account/account.ml
- src/lib/mina_base/test/account/dune
- src/lib/transaction_logic/test/account_timing.ml
* Add unit test for account logic
* Run in CI.
Checklist:
* Closes #12803
> Test accounts logic in mina_base.

- src/app/archive/archive.ml
- src/app/archive/dune
- src/app/archive/lib/processor.ml
- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
- src/lib/mina_caqti/mina_caqti.ml
We had added columns `last_vrf_output, `protocol_version_id`, and `proposed_protocol_version_id` to the `blocks` table in the archive schema.
There's a subchain query on that table that's used to update the chain status (canonical, etc.). Unlike the main query to insert blocks, that query was not derived automatically from the OCaml type associated with the table.  This PR updates the query to include all fields, automatically derived from the OCaml type.
I was able to reproduce the problem using a db from Gareth, and a precomputed block. After the changes made here, I was able to archive the block to his db.
Also added a `version` flag to `archive.exe`, like the one for `mina.exe`. Removed some not-so-helpful code for `mina.exe` (not too useful to run `mina version -help`, the `version` …
> All columns for block subchain query

- buildkite/src/Jobs/Test/TestnetIntegrationTests.dhall
The `snark` integration test only tests features tested in other integration tests. Removing it to lower cloud resource usage.
> Remove snark-test from CI

- src/app/delegation_backend/src/constants.go
- src/app/delegation_backend/src/data.go
- src/app/delegation_backend/src/submit.go
Update uptime service backend with graphql control port.
* Update `constants.go` with new test bucket
* Support non-mainnet network (via setting a `NETWORK` environment variable)
* Support graphql control port in JSON payload and save it to bucket
* Manual testing of a Mina node from #12828 together with the uptime service
Checklist:
* Closes #12825
> Support graphql control port in uptime backend

- src/app/cli/src/init/dune
- src/app/cli/src/init/graphql_internal.ml
- src/app/cli/src/init/mina_run.ml
- src/app/itn_orchestrator/genqlient.graphql
- src/app/itn_orchestrator/genqlient.yaml
- src/app/itn_orchestrator/json_types/types.go
- src/app/itn_orchestrator/schema.graphql
- src/app/itn_orchestrator/src/discovery.go
- src/app/itn_orchestrator/src/go.mod
- src/app/itn_orchestrator/src/go.sum
- src/app/itn_orchestrator/src/graphql.go
- src/app/itn_orchestrator/src/itn_orchestrator/main.go
- src/lib/graphql_basic_scalars/graphql_basic_scalars.ml
- src/lib/mina_graphql/dune
- src/lib/mina_graphql/mina_graphql.ml
Added replay check code to the ITN GraphQL server.  When loading the daemon, the ITN GraphQL server gets assigned a fresh Uuid.
The `Authorization` header now looks like:
```
Signature pubkey signature ; Sequencing uuid sequence-no
```
The `uuid` is checked for syntactic validity (i.e., it decodes to the relevant OCaml type). If that check fails, or the uuid and sequence number are not as expected, return `Precondition_failed` (HTTP code 412). Otherwise, check the signature as before. If the sequence check passes, the sequence number is incremented, regardless of what happens with the signature check and the actual GraphQL query.
The `auth` query now returns the Uuid of the GraphQL server. That query can omit the `Sequencing` part of the header.
Removed the code that checks for …
> ITN GraphQL, check sequence number in Authorization

- src/lib/transaction_logic/zkapp_command_logic.ml
For new accounts created by zkApps, set the delegate to be the public key, if the account token is the default. That matches the strategy used when creating new accounts out-of-SNARK.
We were seeing SNARK failures for new accounts with delegate preconditions, because the delegate had not been set.
> Set delegate in new accounts

- src/app/archive/archive_lib/dune
- src/app/archive/archive_lib/processor.ml
- src/app/replayer/replayer.ml
- src/app/replayer/sql.ml
There was some scaffolding in the replayer for checkpointing, but starting from a checkpoint file didn't really work.
Added flag `--checkpoint-interval` to dump a checkpoint file periodically, useful if there's a failure and we want to restart the replayer.
This change enables #12993, which will give assurance that the hard fork migration uses valid data.
We'll want to make comparable changes for the replayer in `berkeley`, and the modified replayer that fills in the `accounts_accessed` table (not yet written).
> Make replayer checkpointing work (mainnet)

- src/lib/transaction_logic/zkapp_command_logic.ml
- src/lib/transaction_snark/test/zkapp_preconditions/dune
- src/lib/transaction_snark/test/zkapp_preconditions/zkapp_preconditions.ml
The fix in #13043 for SNARK failures seen when new accounts have a `delegate` precondition wasn't quite right. In-SNARK, the account has an empty public key, so setting the delegate to that key is incorrect. The fix is to set the delegate to the account update's public key.
Remove the redundant code that conditionally sets the `base_delegate` based on whether the account is new, and the token is the default. The fix has already set the account delegate using the same criteria.
Add two tests using the `delegate` account precondition, one with the default token (the zkApp succeeds), another with a custom token (the zkApp gets the expected failure). Neither should trigger a SNARK failure.
Rename `party_preconditions` to `zkapp_preconditions` (while `account_update_preconditions` is more …
> Delegate precondition, fix SNARK failure, tests

- src/lib/mina_base/fee_excess.ml
- src/lib/mina_base/test/fee_excess/dune
- src/lib/mina_base/test/fee_excess/fee_excess.ml
* Inline tests written with Jane Street's PPX have a couple of problems. They're intermingled with production code and on top of that they produce no output if all the tests pass, which makes it difficult to sort out if certain tests were or were not actually run in the CI for instance.
* In order to properly separate tests from the production code and also to make it clear which tests are being run when, I migrated the tests in `mina_base/fee_excess.ml` module to Alcotest testing framework, which always displays a summary of the tests it has run. 
* This is an experimental change to demonstrate the viability of of this approach to unit testing and to see how will the results appear in the CI. If it is accepted, we can migrate other unit tests that we have to …
> Migrate Fee excess tests to alcotest.

- src/lib/mina_base/account.ml
- src/lib/mina_base/zkapp_account.ml
- src/lib/monad_lib/monad_lib.ml
- src/lib/monad_lib/monad_lib.mli
- src/lib/transaction_logic/test/dune
- src/lib/transaction_logic/test/helpers.ml
- src/lib/transaction_logic/test/predicates.ml
- src/lib/transaction_logic/test/test_account.ml
- src/lib/transaction_logic/test/transaction_logic.ml
- src/lib/transaction_logic/test/zkapp_cmd_builder.ml
* Add more unit tests to zkapp command logic.
* These tests exercise the function, which applies zkApp commands to a ledger. They verify important properties, like the order in which updates are applied, in what ways they change the accounts in the ledger and what are failure conditions for different types of updates.
* The CI runs these tests.
Checklist:
* Closes #12530
> Add more tests for zkApp command logic.

- src/app/itn_orchestrator/schema.graphql
- src/app/itn_orchestrator/src/discovery.go
- src/app/itn_orchestrator/src/go.mod
- src/app/itn_orchestrator/src/go.sum
- src/app/itn_orchestrator/src/zkapp.go
- src/lib/mina_graphql/mina_graphql.ml
This PR adds a recently used accounts cache to the zkapp scheduler. When generating new zkapp commands, we would try to avoid using recently used accounts to avoid dependency between zkapp commands.
```
mutation ($input: ZkappCommandsInput!) {
scheduleZkappCommands(input: $input){
handle
}
}
```
where input is of type
```
type input =
{ fee_payers : Signature_lib.Private_key.t list
; num_zkapps_to_deploy : int
; num_new_accounts : int
; transactions_per_second : float
; duration_in_minutes : int
; memo_prefix : string
; no_precondition : bool
; account_queue_size : int
; min_balance_change : string
; max_balance_change : string
; init_balance : string
; min_fee : string
; max_fee : string
; deployment_fee : string
}
```
* …
> Zkapp scheduler: avoid recently used accounts

- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
- src/lib/cli_lib/default.ml
- src/lib/cli_lib/flag.ml
- src/lib/cli_lib/flag.mli
Make file log rotations configurable via CLI.
* Ran `--help` command
Checklist:
> Implement `--file-log-rotations` flag

- scripts/mina-local-network/mina-local-network.sh
Small improvement for local network script, which i found useful. Then -reset and -archive parameter is set database schema is recreated
By running script with mentioned parameters and ensured that there is fresh schema 
Checklist:
> Recreate schema in local network script when archive and reset parameter (develop)

- flake.nix
merges rampup -> berkeley as a side effect of bringing the wasm fix https://github.com/MinaProtocol/mina/pull/13341 to berkeley
> Fix Wasm build BERKELEY

- src/app/cli/src/init/coda_run.ml
- src/app/replayer/replayer.ml
- src/lib/merkle_ledger/any_ledger.ml
- src/lib/merkle_ledger/base_ledger_intf.ml
- src/lib/merkle_ledger/database.ml
- src/lib/merkle_ledger/null_ledger.ml
- src/lib/merkle_ledger_tests/dune
- src/lib/merkle_ledger_tests/test_database.ml
- src/lib/merkle_ledger_tests/test_mask.ml
- src/lib/merkle_mask/masking_merkle_tree.ml
- src/lib/mina_base/ledger.ml
- src/lib/mina_commands/mina_commands.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_lib/mina_lib.mli
Speed up ledger export by running `Deferred.List.init` with the `Parallel` flag, and calling `get_at_index_exn` to get each account. That approach replaces code that got locations, then looked up the accounts from the locations, and sorted on addresses.
This approach relies on the fact that the accounts are stored densely in the ledger leaves, that is, all indexes from 0 to the number of accounts - 1 have an associated account.
`to_list` now returns a `Deferred.t`, which infected some other code, which needed to change in response.
Added `to_list_sequential`, which is slower, and doesn't bring in `Deferred.t`, which can be used in tests, where speed isn't essential.
The time to run `ledger export staged-ledger` on mainnet is reduced from ~16 minutes to ~24 seconds. A staking ledger export …
> Faster ledger export

- src/config/features/dev.mlh
- src/config/features/mainnet.mlh
- src/config/features/public_testnet.mlh
- src/lib/mina_base/account.ml
- src/lib/mina_base/signed_command_payload.ml
- src/lib/mina_base/snapp_command.ml
- src/lib/mina_base/token_id.ml
- src/lib/staged_ledger/staged_ledger.ml
Remove `feature_tokens` and `feature_snapps` config items, and code that depended on them.
`Account.check` always looks for a nondefault token and an instantiated `snapp` field. It can now report both errors, where before it would fail for at most one error; in the `dev` profile, it wasn't reporting either error.
`Token_id.gen` always returns the default token. There are existing generators that can generate an invalid or nondefault token, if those are needed.
The unit tests in `merkle_ledger_tests` pass using the `devnet` profile, which they did not before.
Closes #13344.
> rm feature_snapps, feature_tokens

- src/app/heap_usage/values.ml
- src/lib/crypto/snarky_tests/snarky_tests.ml
- src/lib/mina_block/sample_precomputed_block.ml
- src/lib/mina_state/local_state.ml
- src/lib/mina_state/snarked_ledger_state_intf.ml
- src/lib/mina_wire_types/mina_transaction_logic/zkapp_command_logic.ml
- src/lib/mina_wire_types/test/type_equalities.ml
- src/lib/mina_wire_types/utils.ml
- src/lib/transaction_logic/mina_transaction_logic.ml
- src/lib/transaction_logic/zkapp_command_logic.ml
- src/lib/transaction_snark/transaction_snark.ml
- src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
- src/lib/transaction_witness/transaction_witness.ml
- src/lib/transaction_witness/transaction_witness.mli
The `token_id` field of local state was always the default token, and never updated to a different token in the zkApps transaction logic.  Remove that field.
Software engineering: rename the inner `is_start'` in the zkApp transaction logic to `is_empty_call_forest`, to avoid confusion with the outer one.
> Remove token_id from local state

- src/lib/mina_numbers/global_slot_since_genesis.ml
- src/lib/mina_numbers/global_slot_since_hard_fork.ml
- src/lib/mina_numbers/global_slot_span.ml
- src/lib/mina_wire_types/mina_numbers.ml
- src/lib/ppx_version/versioned_module.ml
Unbox the types `Global_slot_since_genesis.t`, `Global_slot_since_hard_fork.t`, and `Global_slot_span.t`. Those types have a single constructor, so the variant tag conveys no information, hence the run-time representation of the type can be the same as the constructor argument. This change saves some space, because the type tag is elided, and some time, boxing and unboxing values is not needed.
For generality, `ppx_version` is changed so that if a type is unboxed, a generated `With_top_tag` or `With_version_tags` module will also have an unboxed type. That part of this PR was tested when the slot types had such modules, though they do not now.
> Unbox slot types

- automation/terraform/modules/kubernetes/testnet/locals.tf
- automation/terraform/modules/kubernetes/testnet/outputs.tf
- automation/terraform/modules/o1-integration/graphql_ingress.tf
- buildkite/scripts/run-test-executive.sh
- graphql_schema.json
- helm/archive-node/templates/archive.yaml
- src/app/test_executive/payments_test.ml
- src/lib/integration_test_cloud_engine/dune
- src/lib/integration_test_cloud_engine/graphql_polling_log_engine.ml
- src/lib/integration_test_cloud_engine/graphql_polling_log_engine.mli
- src/lib/integration_test_cloud_engine/integration_test_cloud_engine.ml
- src/lib/integration_test_cloud_engine/kubernetes_network.ml
- src/lib/integration_test_lib/intf.ml
- src/lib/logger/impl.ml
- src/lib/logger/impl.mli
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_lib/mina_lib.mli
- src/lib/structured_log_events/structured_log_events.ml
- src/lib/structured_log_events/structured_log_events.mli
https://app.zenhub.com/workspaces/velocity-62264fddc441a100183f7f86/issues/gh/minaprotocol/mina/13259
> replace stack driver log engine in Lucy with a log engine based on graphql polling

- src/app/archive/archive_lib/processor.ml
- src/app/replayer/dune
- src/app/replayer/replayer.ml
When processing transactions in a block, the archive processor would update the initial nonce map, instead of cumulatively updating the nonce map passed through the fold accumulator. That meant if a fee payer was involved in more than one transaction in a block, the nonce would be wrong. If a transaction involved a public key not in the initial nonce map, the nonce would be missing.
In the replayer, instead of looking for `slot % interval = 0`, which often fails because not all slots have blocks, set a target slot. Issue a checkpoint file if the target is exceeded, and reset the target. Tested that feature by running the replayer on the mainnet db.
Also, remove warning flags from dune which hid some unused types and variables. Remove those unused items.
Closes #13401.
> Cumulative nonce map in archive processor

- buildkite/scripts/connect-to-mainnet-on-compatible.sh
- buildkite/src/Jobs/Test/ConnectToMainnet.dhall
Add or maintain connect to mainnet test on compatible branch
Running CI and observing results
Checklist:
* Closes #13366
> allow to run connect to mainnet on release branches

- Makefile
- buildkite/scripts/test-snarkyjs-bindings-minimal.sh
- buildkite/src/Jobs/Test/SnarkyJSTest.dhall
snarkyjs: https://github.com/o1-labs/snarkyjs/pull/997
bindings: https://github.com/o1-labs/snarkyjs-bindings/pull/50
closes https://github.com/o1-labs/snarkyjs/issues/971
closes https://github.com/o1-labs/snarkyjs/issues/972
RFC: https://github.com/o1-labs/rfcs/pull/5
* Adds a new make target `snarkyjs_no_types` which builds snarkyjs from source without also compiling TS to JS
* Adds a new, required buildkite job which runs a minimal snarkyjs test without type checking
* The TS code base is bundled to JS on the fly with `esbuild`, which doesn't do type-checking and is very fast
> Blocking SnarkyJS CI tests

- src/lib/crypto/kimchi_backend/gadgets/foreign_field.ml
- src/lib/crypto/kimchi_backend/gadgets/foreign_field.mli
- src/lib/crypto/kimchi_backend/gadgets/keccak.ml
- src/lib/crypto/kimchi_backend/gadgets/keccak.mli
This PR adds 3 functionalities discussed in the RFC for Keccak in SnarkyJS (https://github.com/o1-labs/rfcs/pull/9)
1. Add support for different output lengths corresponding to pre-NIST's variant. SnarkyJS can decide if they implement them or not, but at least they have access to them now.
2. Enables customization in the endianness of both the input and the output of the hash (now both are lists)
3. Adds a flag to enable byte checks (default is `false`, assuming users could use `UInt8` most times)
> Add functionalities to Keccak interface after discussion of RFC

- src/app/replayer/replayer.ml
The replayer was generating a checkpoint file when it finished, if no target epoch ledger hash was provided.
But the last commands replayed may not be all the commands in a block, so the checkpoint file is not a valid state. So don't generate that file.
The checkpoint files generated with `--checkpoint-interval` do represent valid states.
> Replayer, no checkpoint file when finished

- src/lib/crypto/kimchi_backend/gadgets/common.ml
This fixes a couple of bugs in the sqrt implementation used to create the "initial aggregator" point for EC scaling
> Fix modular square root implementation

- src/lib/pickles/step.ml
- src/lib/pickles_types/vector.ml
- src/lib/pickles_types/vector.mli
Avoid calling `Vector.to_list` followed by `List.nth_exn` and directly use `Vector.nth_exn`
> Modest simplification by introducting `Vector.nth_exn`

- src/lib/merkle_ledger_tests/test_stubs.ml
- src/lib/merkle_mask/masking_merkle_tree.ml
- src/lib/network_pool/priced_proof.ml
- src/lib/network_pool/snark_pool.ml
Fix some small issues found during hash table audit:
- remove dead code
- replace `to_alist`, `of_alist` composition with simpler `Table.copy`
- replace `compare` with `equal` for snark pool test
> Fix hash table nits

- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_lib/tests/tests.ml
- src/lib/network_pool/mocks.ml
- src/lib/network_pool/snark_pool.ml
- src/lib/network_pool/snark_pool.mli
- src/lib/transaction_snark_work/transaction_snark_work.ml
- src/lib/transaction_snark_work/transaction_snark_work.mli
- src/lib/transition_frontier/extensions/snark_pool_refcount.ml
- src/lib/transition_frontier/extensions/snark_pool_refcount.mli
- src/lib/transition_frontier/frontier_base/diff.ml
- src/lib/transition_frontier/frontier_base/diff.mli
- src/lib/transition_frontier/full_frontier/full_frontier.ml
Merges https://github.com/MinaProtocol/mina/pull/13409 into berkeley.
> Fix snark pool long async cycles (merge into berkeley)

- src/lib/transition_handler/dune
- src/lib/transition_handler/validator.ml
Problem: when a node is in early catchup and creates a block, it might be considered worse than root and the node to be banned for gossiping it.
This is especially easy to reproduce in a network with a few large-stake BPs, but may happen in network like mainnet too, with a lower probability.
Discussion of the problem: https://www.notion.so/minaprotocol/Banning-of-recently-bootstrapped-block-producer-dd98f2268c9e4a6eb4cbd7730d3a2865
Solution: if parent of the transition is in root history, do not ban.
Additionally, if we've seen gossip with the parent of transition and its ancestor was in root history, do not ban. This one is implemented heuristically via an LRU cache.
* Tested on a private cluster
Checklist:
- Notify Velocity team if dependencies must …
> Don't ban nodes for block created in early catchup

- src/lib/block_producer/block_producer.ml
- src/lib/block_producer/dune
- src/lib/mina_lib/mina_lib.ml
- src/lib/transition_handler/processor.ml
This PR addresses two conditions related to block processing/production.
First problem is that after block is produced, it is scheduled for broadcast only in next cycle (or even in the cycle after next). If some long async job appears in between (and this is what happens in Berkeley now), broadcast will be delayed, potentially causing block to appear later-than-needed on other nodes (especially on clusters using block window below 1 minute).
Second problem appears when node goes to bootstrap while a block is being processed in `add_and_finalize`. It happens very infrequently, but shuts the node down when happens.
Solution: broadcast produced transition immediately after it's added to frontier and check for pipe not being closed before writing to it.
* …
> Broadcast produced transition immediately

- src/lib/network_pool/intf.ml
- src/lib/network_pool/network_pool_base.ml
- src/lib/network_pool/pool_sink.ml
- src/lib/network_pool/snark_pool.ml
- src/lib/network_pool/snark_pool_diff.ml
- src/lib/network_pool/test.ml
- src/lib/network_pool/transaction_pool.ml
Problem: in certain conditions processing of a pool item may stall block processing. This happens because transition frontier extension event is written to a synchronous pipe which is read from the merged reader of a few items:
```
Strict_pipe.Reader.Merge.iter_sync
[ Strict_pipe.Reader.map tf_diffs ~f:(fun diff ->
Transition_frontier_extension diff )
; remote_r
; local_r
]
```
Despite remote and local pool items being given a lower priority, processing of them may block transition frontier extension handling. It leads to a significant (multiple seconds) delay on one block, but also leads to accumulation of unprocessed blocks. If the delay repeats a few times (which is probabilistic), block delay may start growing as an avalanche, leading to hundreds of seconds of delays in block …
> Do not block pool processing on rebroadcast

- src/lib/gossip_net/any.ml
- src/lib/gossip_net/dune
- src/lib/gossip_net/fake.ml
- src/lib/gossip_net/intf.ml
- src/lib/gossip_net/libp2p.ml
- src/lib/gossip_net/message.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_networking/mina_networking.ml
- src/lib/mina_networking/mina_networking.mli
- src/lib/network_pool/intf.ml
- src/lib/network_pool/network_pool_base.ml
- src/lib/network_pool/snark_pool.ml
- src/lib/network_pool/test.ml
- src/lib/network_pool/with_nonce.ml
- src/lib/transaction_inclusion_status/transaction_inclusion_status.ml
Problem: with hash-based message ids rebroadcast mechanism became invalid.
Solution: add integer nonce to snark/tx gossip messages in the old topic.
* Tested on a private cluster, rebroadcast seems to work
* Requires additional testing to confirm rebroadcast works not worse than on mainnet 
Checklist:
* Closes #13451
> Use nonce for snark work and tx gossips

- src/lib/crypto/kimchi_backend/gadgets/ec_group.ml
- src/lib/crypto/kimchi_backend/gadgets/ecdsa.ml
- src/lib/crypto/kimchi_backend/gadgets/foreign_field.ml
- src/lib/crypto/kimchi_backend/gadgets/foreign_field.mli
This PR partially addresses a concern that @mitschabaude pointed out regarding the amount of multi range checks that were being performed automatically by the foreign field gadgets. Until further optimizations are carried out, this PR adds a MRC for the initial value, before it is "augmented" to obtain the bound term. 
Pending tasks arising from this issue are:
- Find out if we could safely avoid this costly step (with this PR, ECDSA takes many more rows)
- This only adds range checks for permutable terms, but what about the quotient of FFMul? We might have to modify the layout to place it somewhere else and add another range check for this one.
Related to https://github.com/MinaProtocol/mina/issues/13478
> Extra safety in foreign field arithmetics

- frontend/leaderboard/helm/templates/leaderboard-cron-job.yaml
Fix for Helm chart lints observed in berkeley based PRs. It manifests with below error:
```
  | Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "leaderboard-cron" namespace: "" from "": no matches for kind "CronJob" in version "batch/v1beta1"
  | ensure CRDs are installed first
```
The hint is in some line above:
```
==> Linting ./frontend/leaderboard/helm
--
  | [WARNING] templates/leaderboard-cron-job.yaml: batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
```
This PR updates apiVersion
run CI
Checklist:
- …
> CI fix: change apiVersion for leaderboard-cron-job.yaml [DEV]

- Makefile
- buildkite/src/Jobs/Lint/Fast.dhall
- scripts/check-proof-systems-submodule.sh
Added new job to CI for checking if current commit in `src/lib/crypto/proof-system` submodule is ancestor of particular branch. As already discussed, we need that kind of verification for all major mina branches (compatible/berkeley/develop/izmir). Due to the problems with merging back changes between mentioned branches ,@mrmr1993 have this idea that it's better to commit the same script everywhere and control it by base branch variable from buildkite. Thanks to than we don't need to have painful merging back changes between develop/berkeley/compatible.
By running CI
Checklist: …
> Lints for system proofs commit ancestor

- buildkite/src/Jobs/Test/FuzzyZkappTest.dhall
We were seeing timeouts in the nightly tests, reproducible locally. Raising the per-test timeout from 120 to 150 avoided the timeouts locally.
> Bump per-test timeout for zkapp_fuzzy [Develop]

- buildkite/src/Jobs/Release/MinaArtifactBionic.dhall
- buildkite/src/Jobs/Release/MinaArtifactStretch.dhall
- dockerfiles/Dockerfile-mina-archive
- dockerfiles/Dockerfile-mina-daemon
- dockerfiles/Dockerfile-mina-test-executive
Removes support for bionic and stretch dockers alike to berkeley and develop
Running CI
Checklist:
> Remove support for bionic and stretch [compatible]

- buildkite/scripts/connect-to-mainnet-on-compatible.sh
- buildkite/src/Jobs/Release/MinaToolchainArtifact.dhall
Another portion of fixes for compatible nightly. Reverse condition on connect to testnet, so actually connection attempt will be executed on compatible. Remove leftover docker for stretch
> reverse condition in mainnet check and remove toolchain stretch docker

- src/lib/crypto/kimchi_bindings/stubs/kimchi_bindings.ml
- src/lib/crypto/kimchi_bindings/stubs/src/main.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_proof.rs
This PR updates the example in `pasta_fp_plonk_proof.rs` that was disabled in [this PR](https://github.com/MinaProtocol/mina/pull/13630/). It uses the updated functions of proof-systems for the new FFMul layout after the [revised RFC](https://github.com/o1-labs/rfcs/blob/main/0006-ffmul-revised.md)
Merge after the base branch, so that more files are not added to the diff of that PR.
Checklist:
> Updates the example using foreign field mul

- helm/cron_jobs/mainnet-replayer-cronjob.yaml
- src/app/replayer/replayer.ml
- src/app/replayer/sql.ml
After loading the blocks it's going to replay, the replayer builds a table from global slots to ledger and state hashes. If the start slot did not contain a block, it would search backwards and never find the most recent hashes, because only the blocks to be replayed are loaded, no blocks before the start slot. So don't look for the ledger hash at the start slot -- we haven't yet replayed anything. We didn't see this issue until we started using checkpoint files.
Also, restore the checkpoint file dumped at the finish, but only write a checkpoint file if the block at a slot is canonical.
Updated the cron job to use image from this PR.
> Don't check ledger hash at start; restore final checkpoint

- helm/cron_jobs/devnet-replayer-cronjob.yaml
- helm/cron_jobs/mainnet-replayer-cronjob.yaml
The checkpoint and error files in buckets `devnet-replayer-checkpoints` and `mainnet-replayer-checkpoints` did not have a prefix indicating the network they were from. If such files were downloaded, it would not be apparent which network they were associated with.
I've already renamed the files in the buckets.
Update the cron scripts so they use and produce files with the network prefix.
> Add network prefix to replayer checkpoint files in cron scripts

- buildkite/src/Command/TestExecutive.dhall
This PR stops that CI job from being blocked by integration test runner availability.
Checklist:
> [berkeley] Fix size of "Build JS integration tests" CI job

- src/app/test_executive/medium_bootstrap.ml
- src/lib/integration_test_lib/wait_condition.ml
This PR converts the `section` calls in the medium bootstrap test to `section_hard`. This ensures that the test will end if any step fails, rather than attempting to continue in a failed state.
This should also stop the test earlier when we hit the hard timeouts, which should reduce the runtime of the test when it's failing.
Checklist:
> [berkeley] Make medium bootstrap sections hard fail

- buildkite/scripts/run-snark-transaction-profiler.sh
- buildkite/src/Command/TestExecutive.dhall
- buildkite/src/Jobs/Test/RunSnarkProfiler.dhall
- helm/cron_jobs/berkeley-dump-archive-cronjob.yml
- scripts/snark_transaction_profiler.py
- src/lib/consensus/proof_of_stake.ml
- src/lib/crypto/kimchi_bindings/stubs/Cargo.lock
- src/lib/crypto/kimchi_bindings/stubs/Cargo.toml
- src/lib/monad_lib/monad_lib.ml
- src/lib/monad_lib/monad_lib.mli
- src/lib/monad_lib/state.ml
- src/lib/monad_lib/state.mli
- src/lib/network_pool/command_error.ml
- src/lib/network_pool/indexed_pool.ml
- src/lib/network_pool/indexed_pool.mli
- src/lib/network_pool/test/dune
- src/lib/network_pool/test/indexed_pool_tests.ml
- src/lib/network_pool/test/main.ml
- src/lib/network_pool/test/transaction_gen.ml
- src/lib/network_pool/transaction_pool.ml
- src/lib/snark_profiler_lib/snark_profiler_lib.ml
I included https://github.com/MinaProtocol/mina/pull/13739
* Bump up ocaml-gen to 0.1.5. Required for https://github.com/o1-labs/proof-systems/pull/1112, see related MR in proof-systems https://github.com/o1-labs/proof-systems/pull/1113.
* ocaml-gen 0.1.5 includes some fixes including bindings with more than 5 parameters, a bug related to array conversions and implement OCamlDesc for i32
Built on top of https://github.com/MinaProtocol/mina/pull/13532
* from dannywillems/lookup branch, CI, and in https://github.com/o1-labs/proof-systems/pull/1112.
Checklist:
- Test names …
> Bump up ocaml-gen to 0.1.5

- src/lib/crypto/kimchi_backend/gadgets/bitwise.ml
This PR inverts the order of some constraints that insert generic gates, and the `Zero` row that needs to follow the chain of `Xor16` rows. Otherwise Snarky could insert generic gates in between, breaking the linkability between Xor inputs and outputs.
Related to a subsequent PR to detect these situations automatically.
* Closes https://github.com/MinaProtocol/mina/issues/13757
> Invert order of constraints in Xor Snarky gadget

- helm/cron_jobs/devnet-replayer-cronjob.yaml
- helm/cron_jobs/mainnet-replayer-cronjob.yaml
- src/app/replayer/sql.ml
When replaying from a checkpoint file, the start slot may not be occupied by a slot. In that case, find the next slot occupied by the slot.
The replayer was choosing that next slot to replay from, regardless of its chain status. Make sure the status is not `orphaned`, otherwise we won't find the block in the chain chosen by the replayer.
The berkeley replayer cron job failed because it tried to replay from an orphaned slot. The fix was made for the berkeley replayer in #13715.
Update the `devnet` and `mainnet` cron jobs to use an image from this PR.
> Replayer, next slot not orphaned

- Makefile
- helm/cron_jobs/berkeley-replayer-cronjob.yaml
- src/app/replayer/dune
- src/app/replayer/replayer.ml
- src/app/replayer/sql.ml
- src/lib/mina_ledger/sparse_ledger.ml
- src/lib/staged_ledger/staged_ledger.ml
Add snarked ledger check to replayer: each snarked ledger is the ledger hash from some first-pass application of a transaction.
There's a hole, though. If replaying from a checkpoint, the transaction that created the ledger hash may have occurred before the checkpoint. We can close that hole by saving pending ledger hashes to the checkpoint file, if desired, but I'd prefer to defer that to a subsequent PR.
Add the YAML file to run a replayer cron job on berkeley.
Tested the cron job by manually running it.
Made some monad uses a little more concise, because I could.
Closes #13463.
Closes #13700.
> Replayer, check snarked ledger hash, berkeley cron job

- helm/cron_jobs/berkeley-replayer-cronjob.yaml
- src/app/replayer/dune
- src/app/replayer/replayer.ml
- src/app/replayer/sql.ml
- src/lib/mina_ledger/sparse_ledger.ml
- src/lib/staged_ledger/staged_ledger.ml
Check the SNARKed ledger hashes in the replayer for `berkeley`. That was done for `rampup` in #13715; cherry-pick the commits there, apply them to `berkeley`.
The other changes from that PR include the YAML for the replayer cron job. I will update the cron job image to use a container created from this PR.
> Replayer, check snarked ledger hash [berkeley]

- src/lib/crypto/kimchi_backend/common/plonk_dlog_proof.ml
- src/lib/crypto/kimchi_backend/gadgets/runner/runner.ml
- src/lib/crypto/kimchi_backend/pasta/pallas_based_plonk.ml
- src/lib/crypto/kimchi_backend/pasta/vesta_based_plonk.ml
- src/lib/crypto/kimchi_bindings/stubs/kimchi_bindings.ml
- src/lib/crypto/kimchi_bindings/stubs/kimchi_types.ml
- src/lib/crypto/kimchi_bindings/stubs/src/main.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_proof.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_proof.rs
- src/lib/pickles/pickles.ml
- src/lib/pickles/step.ml
- src/lib/pickles/wrap.ml
* This PR, with their counterparts in https://github.com/o1-labs/snarkyjs/pull/1031 and https://github.com/o1-labs/snarkyjs-bindings/pull/85 add the parameter "runtime_tables" to the proof creation. For the moment, an empty array is given.
* See PR train : https://github.com/MinaProtocol/mina/issues/13086#issuecomment-1630930227
It will be followed by a PR adding runtime tables to the proof inputs. A WIP is already available in [this branch](https://github.com/MinaProtocol/mina/commits/dannywillems/track-runtime-table-cfg) and [here](https://github.com/o1-labs/snarky/pull/828). Please do not have a look now.
* locally running `./run-ci-tests` and relying on the CI in snarkyjs. The current expectation is to have the current tests …
> [develop] Bindings - pass runtime table parameter to proof creation

- buildkite/src/Jobs/Lint/Fast.dhall
- buildkite/src/Jobs/Lint/Merge.dhall
- scripts/merged-to-proof-systems.sh
Added new job to CI for checking if current commit in `src/lib/crypto/proof-system` submodule is ancestor of particular branch. As already discussed, we need that kind of verification for all major mina branches (compatible/berkeley/develop/izmir). Due to the problems with merging back changes between mentioned branches ,@mrmr1993 have this idea that it's better to commit the same script everywhere and control it by base branch variable from buildkite. Thanks to than we don't need to have painful merging back changes between develop/berkeley/compatible.
By running CI
Checklist: …
> Lints for system proofs commit ancestor DEVELOP

- buildkite/src/Jobs/Test/RosettaIntegrationTests.dhall
Expanded dirty when attribute for rosetta integration tests as per request. Now, tests are run on archive an node changes.
Run CI
Checklist:
* Closes #13656
> [CI] Expanded RosettaIntegrationTests dirtyWhen attribute [DEV]

- nix/go.nix
- nix/libp2p_helper.json
*  Bump versions so that libp2p can build within Nin env again.
* CI
Checklist:
* Closes #0000
> Fix Nix environment by bumping libp2p versions.

- src/app/cli/src/init/itn.ml
For `itn-create-accounts`, use `Get_balance` to check whether accounts have been added, instead of downloading the ledger. That's faster.
Tested by @georgeee.
Closes #13874.
> Use Get_balance to check ledger

- CODEOWNERS
I noticed the CODEOWNERS file doesn't behave as intended for the snarkyjs submodule. The intention is that changing the submodule requires product-eng review, but for example on this PR: https://github.com/MinaProtocol/mina/pull/13899, it seems to require protocol-eng instead.
This tiny change is an attempt to make it work.
> Tweak codeowners file to require product-eng for SnarkyJS changes

- src/lib/crypto/kimchi_backend/common/tests/test_lookup_table_constraint_kind.ml
Small PR changing the tests. Nothing was actually defined in the lookup tables before. It is better to show how to use the constraint kind.
*
*
Checklist:
* Closes #0000
> Define standard lookup tables for testing

- src/lib/mina_generators/zkapp_command_generators.ml
- src/lib/mina_generators/zkapp_command_generators.mli
- src/lib/mina_graphql/mina_graphql.ml
When testing zkapp generator on a cluster, it was found that the tool wasn't working as expected. First, it wasn't going beyond deploying of zkapp accounts. Later it was discovered that even if it deployed all the zkapps, generation produced long async jobs of roughly `75 s`. duration.
* Remove unnecessary log line which was causing the first issue
* Rewrite zkapp generator to make no use of ledger when being called from ITN Graphql code
* Tested on a cluster launched with 140k ledger
* Confirmed that zkapp txs are sent even after deployment of zkapps
Checklist:
- Test names …
> [ITN] optimize zkapp generator for large ledgers

- src/app/itn_orchestrator/genqlient.graphql
- src/app/itn_orchestrator/schema.graphql
- src/app/itn_orchestrator/src/data.go
- src/app/itn_orchestrator/src/fund.go
- src/app/itn_orchestrator/src/generator/main.go
- src/app/itn_orchestrator/src/graphql.go
- src/app/itn_orchestrator/src/itn_orchestrator/main.go
- src/app/itn_orchestrator/src/stop.go
- src/app/itn_orchestrator/src/zkapp.go
This PR delivers a number of improvements to orchestrator/generator.
* Add support for `stop-daemon` command to orchestrator and generator
* Add support for parallel execution of funding commands
* Significantly speeds up start of an experiment (from 2 hours to ~20 minutes)
* Add support for use of multiple daemons in funding step
* Increases reliability of funding step
* Add support for `max-cost` transactions to generator
* Fix a bug in zkapp command handling on orchestrator
* Tested by repeatedly running the tool on a cluster
Checklist: …
> Improvements for ITN orchestrator

- Makefile
- nix/go.nix
- nix/libp2p_helper.json
* Because of the revert of the libp2p update, Nix configuration is broken again. This fixes the issue by reverting the Go compiler version back to 1.18
* Built Nix env.
Checklist:
> [Nix] revert update of the go compiler version.

- src/lib/mina_lib/mina_lib.ml
- src/lib/node_status_service/node_status_service.ml
Add `chain_id` to the `node_status_data` record used by the node status service. The `chain_id` is obtained from the `Mina_lib.Config.t` instance.
Closes #13967.
> Add chain id to node status service

- src/lib/crypto/kimchi_backend/common/kimchi_backend_common.mli
- src/lib/crypto/kimchi_backend/common/plonk_constraint_system.ml
- src/lib/crypto/kimchi_backend/pasta/constraint_system/intf.ml
- src/lib/pickles/fix_domains.ml
- src/lib/pickles/fix_domains.mli
- src/lib/pickles/step_branch_data.ml
Compute the size of the concatenated fixed and runtime lookup table.
Includes a change in snarky, see https://github.com/o1-labs/snarky/pull/831
* Fix https://github.com/MinaProtocol/mina/issues/13977
*
Checklist:
* Closes #0000
> [develop] Compute the size of the concatenation of all fixed and runtime lookup tables

- src/lib/pickles/common.mli
- src/lib/pickles/compile.ml
- src/lib/pickles/composition_types/composition_types.ml
- src/lib/pickles/composition_types/composition_types.mli
- src/lib/pickles/impls.ml
- src/lib/pickles/impls.mli
- src/lib/pickles/per_proof_witness.mli
- src/lib/pickles/pickles.ml
- src/lib/pickles/plonk_checks/plonk_checks.ml
- src/lib/pickles/side_loaded_verification_key.ml
- src/lib/pickles/step.mli
- src/lib/pickles/step_branch_data.ml
- src/lib/pickles/step_branch_data.mli
- src/lib/pickles/step_main.ml
- src/lib/pickles/types_map.ml
- src/lib/pickles/types_map.mli
- src/lib/pickles/verification_key.ml
- src/lib/pickles/verify.ml
- src/lib/pickles/wrap.ml
- src/lib/pickles/wrap.mli
- src/lib/pickles/wrap_domains.mli
- src/lib/pickles/wrap_main.mli
- src/lib/pickles/wrap_proof.ml
- src/lib/pickles_types/dune
- src/lib/pickles_types/plonk_types.ml
- src/lib/pickles_types/plonk_types.mli
This PR tidies up the various different implementations of 'generating derived features from true features'. This is now captured in a (private) record `Features.Full.t`, which everything can use, and which can only be constructed via 1 codepath.
This ensure that we do not have inconsistencies that will break pickles if/when features about the custom gates change, and that the circuits generated are as optimised as possible.
Checklist:
> [develop] Use full features everywhere in pickles

- graphql_schema.json
- src/lib/mina_graphql/mina_graphql.ml
Add additional field `genesisTimestamp` to `genesisConstants` GraphQL query.
Tested by running a local daemon, running GraphQL query. Saw:
```
"genesisConstants": {
"accountCreationFee": "1000000000",
"coinbase": "720000000000",
"genesisTimestamp": "2020-09-16T02:15:00.000000-08:00"
}
```
(Note: should we still be using UTC-8 as the timezone?)
Closes #12728.
> Add genesis timestamp to genesis constants in GraphQL

- src/lib/pickles/opt_sponge.ml
- src/lib/pickles/opt_sponge.mli
- src/lib/pickles/test/optional_custom_gates/pickles_test_optional_custom_gates.ml
- src/lib/pickles/wrap_verifier.ml
- src/lib/pickles_types/plonk_types.ml
This PR continues the work to enable custom gates, using the TDD style. The test added here triggers the condition where the lookup table has differing widths between the 2 different inductive rules.
In this case, we need 2 'branches' of the sponge, one where it is 'squeezed' to generate the `joint_combiner`, and the other where it is not. In order to facilitate this, the `Opt_sponge` now exposes some additional methods to allow for the forking, re-alignment, and re-combining of the sponges that execute the branches.
This PR also fixes an issue in `choose_key`, where combining a `Some` or `None` from one branch with a `Maybe` from another would not correctly set the boolean in the resulting `Maybe`. Embedded in this change is also a change to the default value for `None` commitments, from …
> Add optional logic for computing the joint_combiner

- src/lib/pickles/test/optional_custom_gates/pickles_test_optional_custom_gates.ml
- src/lib/pickles/wrap_verifier.ml
- src/lib/pickles_types/plonk_types.ml
This PR completes the missing logic in the pickles verifier, adding support for combinations of circuit rules where some use the lookup argument and others do not.
In addition to that new code, this includes a bugfix around the handling of `Maybe` for the dummy values in the `Lookup` structure.
This PR completes the changes required to use the optional custom gates in pickles.
Checklist:
> Add optional logic for lookups

- buildkite/src/Monorepo.dhall
- buildkite/src/Prepare.dhall
- src/app/batch_txn_tool/batch_txn_tool.ml
Small maintenance for CI logic. Currently after #13802 pipeline on PullRequest runs also Jobs designed to run only on Nightly. This pr is fixing this problem
Run CI
Checklist:
> Fixing condition not to run nightly on PR

- src/lib/mina_stdlib/list.mli
The `unequal` function was not exposed while its infix counterpart was - this was the lone example of such an instance.
This also adds links to the generated doc, using `{!val:foo}` instead of `[foo]`.
> Expose `unequal` in module `Mina_stdlib.List`

- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
- src/app/test_executive/verification_key_update.ml
- src/app/test_executive/zkapps.ml
- src/lib/block_producer/block_producer.ml
- src/lib/mina_base/signed_command.ml
- src/lib/mina_base/signed_command_intf.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_lib/tests/tests.ml
- src/lib/network_pool/intf.ml
- src/lib/network_pool/network_pool_base.ml
- src/lib/network_pool/pool_sink.ml
- src/lib/network_pool/snark_pool.ml
- src/lib/network_pool/snark_pool_diff.ml
- src/lib/network_pool/transaction_pool.ml
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/transaction/transaction.ml
- src/lib/transaction_snark_work/transaction_snark_work.ml
- src/lib/transition_handler/block_sink.ml
- src/lib/transition_handler/block_sink.mli
Add internal logs to allow to track lifecycle of a transaction or snark work from its receival through validation down to inclusion into a block.
* Add internal logs to track transaction and snark work lifecycle
* Tested on a private cluster
Checklist:
* Closes #0000
> Add internal logging to track pool items

- src/app/test_executive/hard_fork.ml
- src/app/test_executive/payments_test.ml
- src/app/test_executive/test_common.ml
- src/lib/integration_test_lib/graphql_requests.ml
Add vesting accounts to hard fork integration test.
- timed1 fully vests before the hard fork
- timed2 has cliff before the hard fork
- timed3 has cliff at hard fork
Check that total, locked, liquid balances all comport with the vesting schedule.
The hard fork test is not part of PR CI, it's in the nightly CI. Here's a successful run from an earlier draft PR: https://buildkite.com/o-1-labs-2/mina-o-1-labs/builds/30221#018a6660-58c9-440c-9638-6b89876c96ce
Closes #13811.
> Add vesting accounts to hard fork test

- src/lib/pickles/common.ml
- src/lib/pickles/composition_types/spec.ml
- src/lib/pickles/pickles.ml
- src/lib/pickles/step_verifier.ml
- src/lib/pickles/wrap_main.ml
- src/lib/pickles/wrap_verifier.ml
- src/lib/pickles_types/opt.ml
- src/lib/pickles_types/opt.mli
- src/lib/pickles_types/plonk_types.ml
To avoid confusion with the pre-existiong Option.Some and Option.None variants, use Just and Nothing (borrowed from Haskell's Maybe type) instead.
Fixes #13948
> Pickles: change Opt.t variant names

- src/lib/pickles/test/optional_custom_gates/pickles_test_optional_custom_gates.ml
The table ID is for RangeCheck, but the table is not used
* Adding tests in Pickles for lookup tables. It is the first PR introducing tests related to lookup tables in Pickles.
*
Checklist:
* Closes #0000
> Pickles: add a test with fixed lookup tables and fixed and small table ID

- src/app/itn_orchestrator/src/discovery.go
- src/app/itn_orchestrator/src/stop.go
Problem: Orchestrator gets stopped if it can't reach a node for executing stop-daemon command or if it can't find any participants.
Solution: don't treat no-reply on stop-daemon as an error and repeat discovery in the loop to prevent stopping an experiment because of glitches.
* Orchestrator/generator were tested as part of a cluster experiment
* To be tested on cluster by repeatedly running experiments and seeing Orchestrator is not stopped prematurely (over the following weeks, condition that caused the issue #13957 was infrequent)
Checklist:
* Closes …
> Fix premature stops of Orchestrator

- src/app/itn_orchestrator/src/fund.go
- src/app/itn_orchestrator/src/generator/main.go
- src/app/itn_orchestrator/src/itn_orchestrator/main.go
- src/app/itn_orchestrator/src/keyloader.go
- src/app/itn_orchestrator/src/keyloader_test.go
- src/app/itn_orchestrator/src/misc.go
- src/app/itn_orchestrator/src/misc_test.go
- src/app/itn_orchestrator/src/rotate.go
* Implement stake rotations (to ensure each epoch >33% of stake changes hands)
* Transactions are randomly generated between BP keys and are executed on each round
* Design of stake rotations is unusual in that it requires a list of BP public keys and a list of rest servers (which have the corresponding secret keys preloaded) to be specified for experiment generation
* Design above was chosen in order to make this change isolated to Orchestrator/Generator, without any modification of Mina Daemon code
* (NIT) Add a simple test for keyloader
* Allow funding keys to be generated from initial "seed" secret key
* This finalizes workflow of funding, making it easy to use (because only one secret key needs to be provided to start the process) and super-efficient (by …
> ITN: rotate stake and pre-generate funding keys

- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
- src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
- src/lib/runtime_config/runtime_config.ml
Problem: when running Mina node against large ledgers defined in runtime config (say of 100k accounts), nodes struggle to start because of an extra-large logging that prints the entire ledger as part of a runtime config (an async job + RAM usage spike are guaranteed).
* When printing runtime config, omit accounts section and print `accounts_omitted` metadata item
Example output (for a ledger with 200 accounts):
```json
{
"timestamp": "2023-09-10 16:16:41.325213Z",
"level": "Info",
"source": {
"module": "Genesis_ledger_helper",
"location": "..."
},
"message": "Initializing with runtime configuration. Ledger name: $name",
"metadata": {
"accounts_omitted": 200,
"config": {
"genesis": {
"k": 12,
"slots_per_epoch": 288,
"genesis_state_timestamp": …
```
> Do not print accounts from runtime config

- src/lib/transaction_snark/transaction_snark.ml
This PR stops us from printing the log message for `Transaction_snark.system` compilation time on stdout. This gives us a more consistent output format for the unit tests.
Checklist:
> Remove Transaction_snark.system compilation message

- src/lib/mina_net2/libp2p_stream.ml
- src/lib/mina_net2/libp2p_stream.mli
- src/lib/mina_net2/mina_net2.mli
- src/lib/mina_net2/tests/tests.ml
Split larger messages on IPC to support larger ledger sizes.
* When a large message is sent over a stream, split it to a few smaller
* Existing test is modified to support large messages
* After test on cluster, issue #13965 was gone
Checklist:
* Closes #13965
> Support larger ledgers in IPC communication

- nix/go.nix
- nix/libp2p_helper.json
Bump the Go version used to build libp2p in nix to 1.19 due to the changes made in #14085. The beforementioned PR also changes libp2p, and the nix package hash of it must be updated as well.
> Bump Go version in nix build

- src/app/libp2p_helper/src/bitswap_storage.go
- src/app/libp2p_helper/src/libp2p_helper/bitswap.go
- src/app/libp2p_helper/src/libp2p_helper/bitswap_downloader.go
- src/app/libp2p_helper/src/libp2p_helper/bitswap_msg.go
- src/app/libp2p_helper/src/libp2p_helper/incoming_msg.go
- src/app/libp2p_helper/src/libp2p_helper/main.go
- src/app/libp2p_helper/src/libp2p_helper/peer_msg.go
- src/app/libp2p_helper/src/libp2p_helper/pubsub_msg.go
- src/lib/mina_net2/libp2p_helper.ml
- src/libp2p_ipc/libp2p_ipc.ml
- src/libp2p_ipc/libp2p_ipc.mli
* Replace `%w` with `%s` for errors logged in Libp2p helper (`%w` was the wrong descriptor in the first place)
* Add trace-level logging for every outgoing IPC message on Daemon
* Tested on cluster, helped in tracing an issue
Checklist:
> Fix error logging in libp2p

- src/app/itn_orchestrator/schema.graphql
- src/app/itn_orchestrator/src/generator/main.go
- src/app/itn_orchestrator/src/itn_orchestrator/main.go
- src/app/itn_orchestrator/src/params.go
- src/app/itn_orchestrator/src/zkapp.go
- src/lib/mina_generators/zkapp_command_generators.ml
- src/lib/mina_generators/zkapp_command_generators.mli
- src/lib/mina_graphql/itn_zkapps.ml
- src/lib/mina_graphql/types.ml
* Add two new parameters to zkapp scheduler (part of ITN graphql) to control balance to be deployed onto new accounts
* Implement formulas in Generator and Orchestrator to support new account-generating experiments (and most importantly ensure tx generators' balances never fall below zero
* Override number of zkapps deployed for max-cost transaction generation
* Max-cost tx generator doesn't need nearly as many zkapps to be deployed as the regular tx generator
* Improvements to logging in Orchestrator and generator
* Tested by launching experiments on the "small" cluster
Checklist: …
> ITN tooling: fix new accounts and max cost

- buildkite/scripts/finish-coverage-data-upload.sh
Fixing issue with lack of script which pushed notification to coveralls that coverage gathering is finished
Have a pipeline in nightly to check if coverage is correctly pushed: 
https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/481
Checklist:
* Closes #0000
> [Compatible] nightly tear down fix

- src/lib/mina_lib/tests/tests.ml
Add some debug logs to `Mina_lib_tests`.
The `Sync current, next staking ledgers to empty ledgers` test frequently times out. The greatest uses of time:
- starting verifier (locally, ~8 to ~24 secs)
- starting transition router (locally, ~61 secs)
- syncing ledgers (locally, ~12 secs)
Not increasing the timeout, so if the test continues to fail, we can compare the times in CI to these local  times.
Update: the time sink appeared to have been creating the first verifier. Fix: create the verifier in the test module, use that for all tests. Allow the first test to use the default timeout, which should be fine now.
> Add debug logs for Mina_lib_tests

- src/lib/block_producer/block_producer.ml
- src/lib/ledger_catchup/super_catchup.ml
- src/lib/mina_block/validation.ml
- src/lib/mina_block/validation.mli
- src/lib/mina_intf/dune
- src/lib/mina_intf/transition_frontier_components_intf.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_lib/tests/tests.ml
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/staged_ledger/staged_ledger.mli
- src/lib/transition_frontier/frontier_base/breadcrumb.ml
- src/lib/transition_frontier/frontier_base/breadcrumb.mli
- src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
- src/lib/transition_frontier_controller/transition_frontier_controller.ml
- src/lib/transition_handler/breadcrumb_builder.ml
- src/lib/transition_handler/processor.ml
- src/lib/transition_router/transition_router.ml
The patch submitted here was originally made and tested against the `release/2.0.0` branch (connected to berkeleynet and in a private cluster) when investigating where the node spends time when processing a block.
Submitted as `Draft` for now because there are probably some tests need to be added for this change (in particular, making sure that only completed work that exactly matches the one in the block is considered as valid for skipping the verification).
The core logic is in the changes to the `src/lib/staged_ledger/staged_ledger.ml` file. The rest of the files had to be changed to make the `get_completed_work` function available to the block processing code that verifies the work included in the block. If there is a better way that doesn't require passing this around please let me …
> Optimization: Avoid redundant work when checking completed works

- buildkite/scripts/merges-cleanly.sh
@nholland94 this fixes the annoying merge-check failures we discussed.
Checklist:
> Let `git merge` determine whether we can merge

- buildkite/scripts/generate-diff.sh
- buildkite/src/Monorepo.dhall
This PR fixes the `dirtyWhen` logic, and simplifies the script.
Checklist:
> Fix buildkite diff generation, so that dirtyWhen rules work correctly

- buildkite/scripts/fuzzy-zkapp-test.sh
We run zkapp fuzzy tests twice in nightlies within each job, but there is no reason to do this.
> Fix: run fuzzy zkapp test once

- buildkite/src/Command/TestExecutive.dhall
Remove condition in dhall files not to run test executive tests on compatible and develop branch
Unfortunately it's only possible to merge it and check if on develop tests are executed
Checklist:
* Closes #0000
> [Develop] removing if statement for running tests on develop and compatible

- buildkite/src/Command/TestExecutive.dhall
Remove condition in dhall files not to run test executive tests on compatible and develop branch
Unfortunately it's only possible to merge it and check if on develop tests are executed
Checklist:
* Closes #0000
> [Berkeley] port run lucy on compatible and develop branches

- src/lib/rocksdb/key_intf.ml
- src/lib/rocksdb/serializable.ml
- src/lib/transition_frontier/persistent_frontier/database.ml
- src/lib/transition_frontier/persistent_frontier/database.mli
- src/lib/transition_frontier/persistent_frontier/dune
- src/lib/transition_frontier/persistent_frontier/worker.ml
Problem: during testing on a private cluster, persistent frontier writes caused a series of consequent long async cycles of length 8s and 9 x 13s (total of > 100s). Long async cycles of more than 10s is a bad sign on its own, but even more so when combined in consequent groups. 
Cycles are caused by a job in persistent frontier that dumps 10 blocks into RocksDB.
* Submit changes to RocksDB in a single batch for all 10 blocks
* Tested on a private cluster
Checklist:
* Closes #0000
> Batch transactions on persistent frontier writing

- src/lib/block_producer/block_producer.ml
- src/lib/integration_test_lib/dune
- src/lib/integration_test_lib/event_type.ml
- src/lib/integration_test_lib/event_type.mli
- src/lib/integration_test_lib/intf.ml
- src/lib/integration_test_lib/json_parsing.ml
- src/lib/integration_test_lib/network_state.ml
- src/lib/integration_test_lib/wait_condition.ml
- src/lib/mina_base/user_command.ml
- src/lib/mina_commands/mina_commands.ml
- src/lib/mina_graphql/itn_zkapps.ml
- src/lib/mina_lib/mina_subscriptions.ml
- src/lib/mina_networking/mina_networking.ml
- src/lib/mina_networking/mina_networking.mli
- src/lib/network_pool/intf.ml
- src/lib/network_pool/network_pool_base.ml
- src/lib/network_pool/pool_sink.ml
- src/lib/network_pool/snark_pool.ml
- src/lib/network_pool/snark_pool_diff.ml
- src/lib/network_pool/transaction_pool.ml
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/transition_frontier/dune
- src/lib/transition_frontier/transition_frontier.ml
- src/lib/transition_handler/block_sink.ml
- src/lib/uptime_service/uptime_service.ml
There are many logs emitted by Mina which are unnecessarily large and in some case become oversized.
This PR aims to fix many of such logs, reducing the amount of data printed.
* Rewrite all of the logs that print directly or indirectly snark work, transaction or state transition data (as these pieces are potentially unbound in size)
* Before the change, cluster's logs were polluted by extra-large logs in `.mina-config/mina.log*` and oversized logs in `.mina-config/mina-oversized-logs.log*`
* After the change, extra large and oversized logs went away
Checklist:
- Test names …
> Remove some oversized logs

- nix/README.md
This merely updates the `nix/README.md` doc with a few extra comments on emacs integration that I'd find quite helpful.
> Update README.md: A comment on emacs integration

- src/lib/pickles_types/plonk_types.mli
* Removed accessors, instead now there's `[@@derive field]`
* CI will test
Checklist:
* Closes #0000
> [#13901] Implement accessors via derive_ppx

- src/lib/pickles/plonk_checks/plonk_checks.ml
- src/lib/pickles/plonk_checks/plonk_checks.mli
Minor change removing an unused type definition and using another one to simplify a function type.
Fix #14209
> Plonk checks cleanup

- src/lib/pickles/commitment_lengths.ml
- src/lib/pickles/commitment_lengths.mli
- src/lib/pickles/dummy.ml
- src/lib/pickles/evaluation_lengths.ml
- src/lib/pickles/evaluation_lengths.mli
- src/lib/pickles/proof.ml
- src/lib/pickles/wrap_main.ml
- src/lib/pickles/wrap_proof.ml
`Evaluation_lengths.create` and `Commitment_lengths.create`'s `of_int` parameters were only ever instantiated with `Fn.id`.  
This PR removes the unnecessary parameter and renames the `create` functions to a more apt `default` since they're not functions anymore.
#
> Pickles: remove `of_int` parameters in `create`, rename to `default`

- src/lib/pickles/common.mli
It makes the signature more readable
*
*
Checklist:
* Closes #0000
> Pickles: use 'comm and 'scalar instead of 'a and 'b and 'c

- src/lib/mina_ledger/sync_ledger.ml
* Update `account_subtree_height` parameter to speed up sync ledger algorithm
* Previous value of `3` was causing the algorithm to make far too many tiny RPC requests
* Tested on a small cluster: deployed with small (200 accounts) genesis ledger, grew the ledger to ~200k accounts, repeatedly deleted a pod and allowed it to bootstrap
* Tested various values for the constant (see [gist](https://gist.github.com/georgeee/9290d2ab3ff24e51c1dfa3d2b4ebc6dd)), chose the best
Checklist:
* Closes #14202
> Update account_subtree_height to 6

- automation/terraform/monitoring/o1-testnet-alerts.tf
- graphql_schema.json
- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
- src/app/itn_orchestrator/schema.graphql
- src/app/itn_orchestrator/src/generate.go
- src/app/itn_orchestrator/src/generate_test.go
- src/app/itn_orchestrator/src/generator/main.go
- src/app/itn_orchestrator/src/payments.go
- src/app/itn_orchestrator/src/zkapp.go
- src/lib/crypto/kimchi_backend/common/gen_version.sh
- src/lib/daemon_rpcs/types.ml
- src/lib/mina_commands/mina_commands.ml
- src/lib/mina_generators/zkapp_command_generators.ml
- src/lib/mina_generators/zkapp_command_generators.mli
- src/lib/mina_graphql/itn_zkapps.ml
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/mina_graphql/types.ml
- src/lib/mina_ledger/sync_ledger.ml
- src/lib/mina_version/normal/gen.sh
- src/lib/network_pool/transaction_pool.ml
- src/lib/transaction/transaction.ml
- src/libp2p_ipc/dune
Fixes some of the scripts called by dune to use different absolute paths if we are building mina in the context of the o1js as mina being a submodule.
The issue occurs when we build o1js from the root directory with mina as a submodule. Dune will try to resolve some absolute paths from build scripts that will fail and not build o1js properly. To fix this, we conditionally check for submodule locations and change the paths if we have a mina submodule present, otherwise, we use the same build process. This lets us build mina the same way but also build o1js dependencies properly.
Built mina from the root directory to test normal building and built o1js using mina as a submodule successfully.
Addresses …
> [develop] feat: fix scripts to use different paths if mina is a submodule of o1js

- buildkite/scripts/rosetta-integration-tests.sh
- src/app/rosetta/lib/account.ml
This PR tweaks the rosetta test to run faster in CI. This is achieved by
* increasing the throughput of transactions, to better match the 20s slot time
* rebalancing the ledger to increase block outut, so that the staking nodes (the block producer and snark worker) have a majority of the stake.
These two changes save roughly 45 mins of integration test runtime.
> [berkeley] Speed up rosetta test in CI

- src/lib/pickles/proof_cache.ml
- src/lib/pickles/wrap.ml
This PR tweaks the logic in `Proof_cache` to handle ignore the new fields added for custom gates/chunking. This allows for the same unit test speed-up as we get in compatible.
Checklist:
> Speed up unit tests in develop

- src/app/itn_orchestrator/src/discovery.go
* Support remote_addr without port in Orchestrator
* This is needed after recent update of uptime backend and use of `X-Forwarded-For`
* Note tested yet
Checklist:
> Support remote_addr without port in Orchestrator

- src/lib/pickles/compile.ml
- src/lib/pickles/compile.mli
- src/lib/pickles/pickles.ml
- src/lib/pickles/pickles_intf.mli
Fix https://github.com/MinaProtocol/mina/issues/14409
*
*
Checklist:
* Closes #0000
> Remove return_early_digest_exception param and related exception

- src/app/archive/lib/processor.ml
In the archive db, receipt chain hashes in account preconditions were being written using the string representation of field elements. The replayer tries to read them as Base58Check for the `Receipt.Chain_hash.t` type (by calling `Load_data.get_account_update_body` from `zkapp_command_to_transaction`). That mismatch causes the replayer to fail.
The solution is to write the hashes as Base58Check. We already do so for receipt chain hashes in `accounts_accessed`.
Part of #14417.
> Base58Check for receipt chain hashes in account preconditions

- buildkite/src/Command/DockerImage.dhall
- buildkite/src/Command/MinaArtifact.dhall
- buildkite/src/Constants/Profiles.dhall
- dockerfiles/Dockerfile-mina-archive
- scripts/release-docker.sh
Build separate dockers for lightnet and standard profile. Do not build test-executive/batch-txn/rosetta for non-devnet profiles
> [Berkeley] Distinguish lightnet and standard dockers

- buildkite/scripts/merges-cleanly.sh
- buildkite/scripts/run-snark-transaction-profiler.sh
- buildkite/src/Constants/DebianVersions.dhall
> Fix CI on o1js-main branch

- src/lib/pickles/cache.ml
- src/lib/pickles/cache.mli
- src/lib/pickles/compile.ml
- src/lib/pickles/pickles.ml
Changes what `Pickles.Cache` returns in `read_or_generate`, from a keypair (prover and verifier key, `Impl.Keypair.t`) to a prover key (`Impl.Prover_key.t`, which is just a Rust prover index).
The verifier key on the `Keypair.t` structure was never used, but still expensively recomputed when reading prover keys from cache.
> [Pickles] Avoid recomputation of cached verification keys

- automation/terraform/monitoring/o1-testnet-alerts.tf
- graphql_schema.json
- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
- src/app/itn_orchestrator/schema.graphql
- src/app/itn_orchestrator/src/generate.go
- src/app/itn_orchestrator/src/generate_test.go
- src/app/itn_orchestrator/src/generator/main.go
- src/app/itn_orchestrator/src/payments.go
- src/app/itn_orchestrator/src/zkapp.go
- src/lib/crypto/kimchi_backend/common/gen_version.sh
- src/lib/daemon_rpcs/types.ml
- src/lib/mina_commands/mina_commands.ml
- src/lib/mina_generators/zkapp_command_generators.ml
- src/lib/mina_generators/zkapp_command_generators.mli
- src/lib/mina_graphql/itn_zkapps.ml
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/mina_graphql/types.ml
- src/lib/mina_ledger/sync_ledger.ml
- src/lib/mina_version/normal/gen.sh
- src/lib/network_pool/transaction_pool.ml
- src/lib/transaction/transaction.ml
- src/libp2p_ipc/dune
Fixes some of the scripts called by dune to use different absolute paths if we are building mina in the context of the o1js as mina being a submodule.
The issue occurs when we build o1js from the root directory with mina as a submodule. Dune will try to resolve some absolute paths from build scripts that will fail and not build o1js properly. To fix this, we conditionally check for submodule locations and change the paths if we have a mina submodule present, otherwise, we use the same build process. This lets us build mina the same way but also build o1js dependencies properly.
Built mina from the root directory to test normal building and built o1js using mina as a submodule successfully.
> [o1js-main] feat: fix scripts to use different paths if mina is a submodule of o1js 

- src/app/itn_orchestrator/src/discovery.go
- src/app/itn_orchestrator/src/graphql.go
Problem: if many nodes are non-responsive, discovery step takes many minutes because some connections time out after 30 seconds.
Solution: try connecting in parallel.
* Tested on ITN
* discovery completed in 1m23s instead of 45 minutes before the fix
* only unique participants were in output
* experiment was executed successfully
Checklist:
* Closes #14394
> Let discovery step try connections in parallel

- src/app/test_executive/zkapps.ml
Fix flakiness of the zkapps test, the timeout is added to avoid a race condition between ledger update and transaction pool update. A more detailed analysis of this can be find in #13854
*
Checklist:
* Closes #13854
> Fix flakiness insufficient replace fee

- nix/rust.nix
This is mostly an update to the nix subsystems, together with updates to submodules
- [o1js bindings](https://github.com/o1-labs/o1js-bindings/pull/193)
- [o1js](https://github.com/o1-labs/o1js/pull/1199)
- [proof-systems](https://github.com/o1-labs/proof-systems/pull/1302)
> Update wasm-bindgen to 0.2.87

- src/lib/pickles/common.ml
- src/lib/pickles/compile.ml
- src/lib/pickles/pickles.ml
- src/lib/pickles/step.ml
- src/lib/pickles_base/proofs_verified.ml
- src/lib/pickles_base/proofs_verified.mli
* Both `of_int` and `of_nat` are now raising `Invalid_argument` instead of `failwithf`
* They are also renamed to `of_int_exn` and `of_nat_exn`
* Closes #14206, #14205
> [#14206,#14205] Cosmetics for of_int, of_nat

- src/lib/mina_base/test/dune
- src/lib/mina_base/test/main.ml
- src/lib/mina_base/test/zero_vesting_period.ml
The zero vesting period tests in `Mina_base.Test` were bit-rotted, and not being run.
Fixed:
- the JSON for the zkApp was updated with the current syntax for account preconditions
- the tests were converted from `ppx_test` inline tests to Alcotest format, added to `main.ml`
Tested by running:
```
dune exec src/lib/mina_base/test/main.exe -- test '^zero vesting period$'
```
Output:
```
...
[OK]                zero vesting period          0   Zero vesting period is error.
[OK]                zero vesting period          1   Nonzero vesting period is OK.
...
```
Also, I temporarily changed the successful branches in the test to run `assert false`, and Alcotest reported the failures.
> Fix zero vesting period test

- src/app/archive/lib/dune
- src/app/archive/lib/extensional.ml
- src/app/archive/lib/processor.ml
- src/app/extract_blocks/dune
- src/app/extract_blocks/extract_blocks.ml
- src/app/replayer/replayer.ml
- src/app/replayer/sql.ml
- src/lib/consensus/vrf/consensus_vrf.ml
- src/lib/consensus/vrf/dune
The same change was made in the migration app in #12906, which is against `berkeley`. This is consistent with the formatting in precomputed blocks.
This PR is against `rampup`, in order to get this change for the next ITN deployment.
I will add the hex-to-Base64 change to #14419, so the migration script will take care of this column.
Also: in the replayer, fixed a comment and removed an unused module.
> Format last_vrf_output as Base64

- src/app/archive/lib/load_data.ml
- src/lib/currency/currency.ml
- src/lib/currency/intf.ml
Add `Amount.Sign.create_preserve_zero_sign`, to allow replayer to load negative zero from database.
This approach allowed replayer to succeed on ITN database.
Closes #14452.
> Function to preserve sign for 0

- src/config/protocol_version/current.mlh
- src/lib/protocol_version/protocol_version.ml
After getting clarification from the protocol team, set the berkeley hard fork protocol version to `transaction = 2, network = 0, patch = 0`.
Update `Protocol_version.is_valid` to accept 0 as the network version.
> Hard fork protocol version is 2.0

- graphql_schema.json
- src/app/cli/src/init/client.ml
- src/app/cli/src/init/graphql_queries.ml
- src/lib/cli_lib/graphql_types.ml
- src/lib/mina_base/pending_coinbase.ml
- src/lib/mina_base/pending_coinbase_intf.ml
- src/lib/mina_base/stack_frame.ml
- src/lib/mina_graphql/types.ml
Added relevant commits from #14220 to allow merge-to-develop to succeed in CI there.
Had to make some other small changes (in 8692d18) because `develop` had other changes.
> [develop] add ledger proof statement to blockchain state in GraphQL 

- helm/cron_jobs/mainnet-replayer-cronjob.yaml
The image that had been used, `mina-rosetta:1.4.0beta2-alerts-readme-ea8d0f2-bullseye`, seems unavailable. That's different than the one in the `compatible` branch.
This PR updates the image. The replayer cron job ran successfully with the new image.
> Update mainnet replayer cron image

- src/lib/parallel_scan/parallel_scan.ml
- src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
* Hashing of the scan state and  staged ledger performs a lot of unnecessary intermediary allocations by appending strings together before feeding them to the hashing context. This version avoids such concatenation and instead feeds strings directly to the hashing context while retaining the same ordering. Avoiding such unnecessary allocations relieves the garbage collector from all that pressure and also solves some >1GB allocation spikes.
* Patched nodes were launched in a mixed environment (patched and unpatched nodes) in a private cluster. Also a bunch of randomly generated scan states were hashed with both new and old versions to ensure that the result is the same.
Checklist:
- Notify Velocity team if dependencies must change …
> Optimization: More memory-efficient scan state and staged ledger hashing

- src/lib/pickles/fix_domains.ml
https://github.com/MinaProtocol/mina/pull/14405#issuecomment-1814476787 for o1js
> Deduplicate lookup tables

- src/lib/pickles/fix_domains.ml
Revert #14566 which was prematurely merged without working in o1js
Dependency for https://github.com/o1-labs/o1js/pull/1223
> Revert 14566

- buildkite/scripts/export-git-env-vars.sh
- buildkite/scripts/generate-diff.sh
- buildkite/scripts/handle-fork.sh
- buildkite/scripts/merges-cleanly.sh
- buildkite/scripts/refresh_code.sh
- buildkite/scripts/run-snark-transaction-profiler.sh
- buildkite/scripts/version-linter.sh
- buildkite/src/Command/DockerImage.dhall
- buildkite/src/Jobs/Test/VersionLint.dhall
- buildkite/src/Monorepo.dhall
- scripts/release-docker.sh
Currently our CI build system is not prepared to handle change from fork repo to mina. There are various problems like:
many jobs checkout origin branches as reference to some comparison and they will checkout branch from fork repo rather than mina (for example merges cleanly)
we should not allow to publish dockers to docker hub from forked repositories
we need to tag dockers properly not to override main repo based dockers
This PR addresses above problems. It adds yet another remote (mina) which always point to mina protocol repository. If CI is run against forked repository it uses branches from mina remote for comparison instead of origin which point to forked repositories. It also changes behavior when running export env variables script. It does not allow to publish dockers and …
> support ci on forks

- buildkite/scripts/build-artifact.sh
- scripts/archive/build-release-archives.sh
Archive Migration tooling consist of two applications:
- berkeley_migration (#12906)
- berkeley_account_tables (#14339)
We need to incorporate deployment of above apps into actual process. Basically the idea is to add above apps to build step in CI and pack them together with mina archive debian package as well as docker,
Closes #14551
> Deploy migration apps

- buildkite/scripts/build-artifact.sh
- buildkite/scripts/single-node-tests.sh
- buildkite/src/Jobs/Test/SingleNodeTest.dhall
- scripts/rebuild-deb.sh
- src/test/command_line_tests/command_line_tests.ml
- src/test/command_line_tests/config.ml
- src/test/command_line_tests/dune
- src/test/command_line_tests/mina_bootstrapper.ml
- src/test/command_line_tests/runner.ml
Skip building mina on single node tests. Instead, use already built mina lightnet packages. Command line tests evolved from being a test with dev profile (kind of unit test but on already built mina ) to became component test for release version of mina. Execution time is similar (~14 min) but we are testing on higher level and more production alike mina.
Run CI and observe green single node tests
Checklist:
* Closes #0000
> Do not build mina on single-node-tests job

- src/lib/pickles/fix_domains.ml
This brings back #14566 after it was reverted in #14591.
The issue I had with #14566 on my machine turned out to be caused by locally cached prover keys 😥 When forcing a recompilation, the issue is gone.
Bumps o1js to https://github.com/o1-labs/o1js/pull/1266
> Unrevert 14566

- buildkite/scripts/test-nix.sh
- buildkite/scripts/version-linter.sh
- buildkite/src/Constants/DebianVersions.dhall
- buildkite/src/Jobs/Test/VersionLint.dhall
Fixes version linter script. Currently we are suffering from read version linter job as it download sexpdata 1.0.1 . It introduce issue similar to :
https://stackoverflow.com/questions/77523055/missingdynamic-license-defined-outside-of-pyproject-toml-is-ignored
Reverting sexpdata to 1.0.0 should solve our problem
> fix version linter failure

- src/lib/verifier/prod.ml
* When a batch of transactions are verified using the verifier helper subprocess, they are serialized and sent to the verifier subprocess. The verifier subprocess will then write the transactions as `Valid.t` back to the node, which in will decode them from a stream creating duplicates of the already existing transactions. This is an issue for zkApp transactions because those contain proofs which are quite memory-heavy.
This patch removes the duplicates from the response, and converts the `Verifiable.t` values to their `Valid.t` counterparts through the unsafe `User_command.to_valid_unsafe` function.
* Running patched nodes in a mixed-enviroment (patched and unpatched nodes) in a private cluster.
From our testing, we noted this …
> Optimization: Avoid duplicating proofs during txn verification

- automation/terraform/modules/o1-testnet/files.tf
- automation/terraform/modules/o1-testnet/scripts.tf
- automation/terraform/modules/o1-testnet/testnet.tf
- automation/terraform/testnets/berkeley/main.tf
- automation/terraform/testnets/ci-net/main.tf
**Explain your changes:**
This PR applies update to terraform modules related to testnet deployments. These changes have the following effect:
* Removes support for using a `genesis_ledger.json` file from the local machine. This is due to the current ledger sizes exceeding the 4mb that can be handled by Terraform. Note that this change is only applying to production testnet deployments that use the `o1-testnet` terraform module. This change does not apply to integration tests which use a separate `o1-integration` module. Integration tests will still be able to generate an use ledgers within tests (because they are under 4mb). 
* The `main.tf` files within the `berkeley` and `ci-net` testnets have been updated. This is to make them compatible with the latest terraform module changes (a few …
> Merging berkeley testnet config into develop

- buildkite/scripts/connect-to-mainnet-on-compatible.sh
* This pr is to repair CI test "connect to testnet" by increasing the test timeout. The original test was limited to 4 minutes, but was not consistently boot and connecting to nodes in this time. 
* This change has been tested by re-running the existing CI test which happens in the nightly pipeline. At a 5th attempt, the test completed. 
* Within the test log outputs, the initial 4 attempts shows the test was reaching it's self-imposed retry limit which is implemented using a while loop and incrementing counter.  
Checklist:
- [NA] Modified the current draft of release notes with details on what is completed or incomplete within this project
- [NA] Document code purpose, how …
> comment fix, ci test fix for "connect to mainnet"

- src/lib/crypto/kimchi_backend/common/dune
- src/lib/crypto/kimchi_backend/common/field.ml
- src/lib/crypto/kimchi_backend/kimchi_backend.mli
- src/lib/crypto/kimchi_bindings/stubs/src/arkworks/pasta_fp.rs
- src/lib/crypto/kimchi_bindings/stubs/src/arkworks/pasta_fq.rs
As discussed [here](https://github.com/MinaProtocol/mina/pull/14595#discussion_r1401055806), this is a more efficient conversion into `Bignum_bigint.t` values that avoids processing the input and output bit by bit.
It feels kind of dirty having to go through bin_prot for this, but `Bignum_bigint` doesn't expose any other way to interpret raw bytes to produce a bigint (which should be more efficient than the alternatives). A pro of this approach is that it didn't require any new function to be exposed (other than the `compare` added in the other field), but assumes that all implementations of `to_bytes` will produce the same output.
*
Checklist: …
> Field: More efficient conversion into Bignum_bigint.t

- src/lib/merkle_ledger/location.ml
- src/lib/merkle_mask/masking_merkle_tree.ml
- src/lib/mina_ledger/sparse_ledger.ml
This PR builds upon #14520. This adds batching for the location lookups in the sparse ledger conversion function.
Checklist:
> Batch account location lookups for sparse ledger

- src/lib/merkle_ledger/any_ledger.ml
- src/lib/merkle_ledger/base_ledger_intf.ml
- src/lib/merkle_ledger/database.ml
- src/lib/merkle_ledger/null_ledger.ml
- src/lib/merkle_mask/masking_merkle_tree.ml
- src/lib/mina_ledger/sparse_ledger.ml
> Batch merkle_path lookups in Sparse_ledger

- src/lib/merkle_address/merkle_address.ml
- src/lib/merkle_address/merkle_address.mli
- src/lib/merkle_ledger_tests/test_mask.ml
- src/lib/merkle_mask/inputs_intf.ml
- src/lib/merkle_mask/masking_merkle_tree.ml
- src/lib/mina_ledger/ledger.ml
This PR builds on #14594.
In this PR, the hash tables used in merkle masks are replaced with maps in order to avoid hashing data at every single mask traversal when evaluating ledger reads. This showed ~7.5x speedup in applying transactions to a chain of `k=290` masks.
> Replace tables with maps in merkle masks

- src/lib/merkle_address/merkle_address.ml
- src/lib/merkle_address/merkle_address.mli
- src/lib/merkle_ledger/any_ledger.ml
- src/lib/merkle_ledger/base_ledger_intf.ml
- src/lib/merkle_ledger/database.ml
- src/lib/merkle_ledger/null_ledger.ml
- src/lib/merkle_ledger_tests/test_mask.ml
- src/lib/merkle_mask/dune
- src/lib/merkle_mask/maskable_merkle_tree.ml
- src/lib/merkle_mask/maskable_merkle_tree_intf.ml
- src/lib/merkle_mask/masking_merkle_tree.ml
- src/lib/merkle_mask/masking_merkle_tree_intf.ml
- src/lib/mina_ledger/dune
- src/lib/mina_ledger/ledger.ml
- src/lib/mina_ledger/ledger.mli
- src/lib/mina_ledger/sparse_ledger.ml
- src/lib/staged_ledger/staged_ledger.ml
This PR builds upon #14586, removing the `Ledger.copy` and `Ledger.create_empty_exn` calls from `Sparse_ledger.of_ledger_subset_exn`. This function takes a significant amount of time in staged ledger diff application, and so this PR should further improve performance there.
Checklist:
> Avoid ledger copy and mutation in `Sparse_ledger.of_ledger_subset_exn`

- src/lib/merkle_ledger/any_ledger.ml
- src/lib/merkle_ledger/base_ledger_intf.ml
- src/lib/merkle_ledger/database.ml
- src/lib/merkle_ledger/null_ledger.ml
- src/lib/merkle_ledger/syncable_intf.ml
- src/lib/merkle_ledger_tests/test_database.ml
- src/lib/merkle_ledger_tests/test_mask.ml
- src/lib/merkle_mask/dune
- src/lib/merkle_mask/maskable_merkle_tree.ml
- src/lib/merkle_mask/maskable_merkle_tree_intf.ml
- src/lib/merkle_mask/masking_merkle_tree.ml
- src/lib/merkle_mask/masking_merkle_tree_intf.ml
- src/lib/mina_base/ledger_hash.ml
- src/lib/mina_base/ledger_intf.ml
- src/lib/mina_base/pending_coinbase.ml
- src/lib/mina_base/sparse_ledger_base.ml
- src/lib/mina_ledger/ledger.ml
- src/lib/mina_ledger/ledger.mli
- src/lib/syncable_ledger/syncable_ledger.ml
Problem: testing with `test-apply` tool revealed that using multiple masks leads to 7x-8x slowdown of block application (for 128 txs). This happens because instead of a single logarithmic lookup 290 of such lookups are performed instead.
Solution: merge maps state from masks and keep it in the topmost mask. Use them for lookups, reducing 290 map lookups to a single one.
* Measured performance with `test-apply` tool
* Deployed the change on `whale-1-1`, confirmed performance improvement and normal operation _and_ block production
Checklist:
* Closes #13249
> Avoid slowdown when using multiple masks

- helm/archive-node/templates/_healthchecks.tpl
* This PR is to repair a behavior where archive nodes are reported as offline, due to the existing healthcheck script being run with an incorrect username and password (which cannot auth to the archive database).
* Before Error: `Readiness probe failed: Archive[] is out of sync with local daemon[82] psql: error: FATAL: password authentication failed for user "postgres"`
* [Related Slack Thread ](https://o1-labs.slack.com/archives/C02BK3SK89F/p1701977003530609)
* Changes in this PR are limited to a single line which sets the valid username and password for the health check at the time of the archive deployment. This change was tested by manually applying the Archive node helm chart and verifying the values that the healthcheck …
> Steven healthcheck fix - compatible

- dockerfiles/scripts/healthcheck-utilities.sh
- helm/archive-node/templates/_healthchecks.tpl
* This PR is to repair a behavior where archive nodes are reported as offline, due to the existing healthcheck script being run with an incorrect username and password (which cannot auth to the archive database).
* Before Error: `Readiness probe failed: Archive[] is out of sync with local daemon[82] psql: error: FATAL: password authentication failed for user "postgres"`
* [Related Slack Thread ](https://o1-labs.slack.com/archives/C02BK3SK89F/p1701977003530609)
* Changes in this PR are limited to a single line which sets the valid username and password for the health check at the time of the archive deployment. This change was tested by manually applying the Archive node helm chart and verifying the values that the healthcheck …
> Steven healthcheck fix - develop

- buildkite/scripts/replayer-test.sh
- buildkite/src/Command/Base.dhall
- buildkite/src/Command/ReplayerTest.dhall
- buildkite/src/Command/Size.dhall
- buildkite/src/Jobs/Test/ReplayerTest.dhall
- scripts/replayer-test.sh
- src/app/replayer/test/archive_db.sql
- src/app/replayer/test/input.json
Enable Replayer tests for berkeley 
Job is enabled and green
Checklist:
* Closes #13596
> [CI] Revive replayer test

- src/app/berkeley_migration/berkeley_migration.ml
- src/app/berkeley_migration/precomputed_block.ml
Archive Migration tooling consist of two applications:
- berkeley_migration (#12906)
- berkeley_account_tables (#14339)
During testing I found a couple of improvements/ small fixes which are necessary for testing and correct run:
- extract parameters from berkeley_migration:
a) bucket location
b) number of batches for precomputed block fetch
c) corner case when there are no precomputed blocks to fetch 
Closes #14551
> Berkeley migration test imprv

- src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
Genesis ledger tar was being extracted to a random sub dir inside the genesis dir, resulting in each subsequent node run with persistence producing a new dir with the contents of the tar file, making the genesis grow indefinitely in size (issue #14548).
This PR fixes this issue, by making the tar extraction into a dir with the same name as the tar file. Subsequent runs of the node will check for the presence of that dir before extracting, delete it if it exists, and extract the tar. This results in a constant size of the genesis dir, assuming the node is rerun with the same genesis ledger config.
Some small improvements to the overall tar-loading logic were also made.
This was tested by doing node runs with different genesis ledger configurations (accounts, hash, name) and checking if the …
> Fix genesis ledger directory growing in size

- src/lib/crypto/kimchi_backend/common/plonk_constraint_system.ml
- src/lib/pickles/test/optional_custom_gates/pickles_test_optional_custom_gates.ml
Fixes #14746 by adding a test setup step which makes sure no colliding keys with different values exist between runtime and fixed tables if their table ids collide.
> Fix flaky runtime fixed id collision test 

- src/lib/crypto/kimchi_backend/common/gen_version.sh
- src/lib/mina_version/normal/gen.sh
- src/libp2p_ipc/dune
Fixes some of the scripts called by dune to use different absolute paths if we are building mina in the context of the o1js as mina being a submodule.
The issue occurs when we build o1js from the root directory with mina as a submodule. Dune will try to resolve some absolute paths from build scripts that will fail and not build o1js properly. To fix this, we conditionally check for submodule locations and change the paths if we have a mina submodule present, otherwise, we use the same build process. This lets us build mina the same way but also build o1js dependencies properly.
Built mina from the root directory to test normal building and built o1js using mina as a submodule successfully.
Addresses …
> [berkeley] feat: fix scripts to use different paths if mina is a submodule of o1js

- scripts/archive/zkapp_duplicated_precondition/add_constraint.sql
- scripts/archive/zkapp_duplicated_precondition/remove_duplicated_zkapp_account_precondition_rows.sh
- src/app/archive/zkapp_tables.sql
- src/app/rosetta/download-missing-blocks.sh
Added shell script which generated two sql scripts for patching database:
- zkapp_precondition_script.sql - Removes duplicated rows in zkapp_account_precondition
- zkapp_update_body_script.sql - Updates zkapp_account_update_body table which has foreign key to zkapp_account_precondition table
Moreover i've updated zkapp_tables.sql script and added unique constraint so that whenever we bypass Ocaml code and manipulate data directly db constraint will complain
Lastly added update script which adds constraint if we want to patch existing database.
In order to fix current schemas in ITN we need to follow below steps:
- run `zkapp_duplicated_precondition/remove_duplicated_zkapp_account_precondition_rows.sh {schema}`
- run produced scripts in correct order: zkapp_precondition_script.sql, …
> Fix duplicated rows in zkapp_account_precondition table

- buildkite/src/Jobs/Test/ConnectToTestworld-2-0.dhall
Soft fail for testworld 2.0 connectivity test since berkeley is not compatible with itn right now
> [CI] soft fail for testworld 2 0 connectivity

- scripts/archive/zkapp_duplicated_precondition/remove_duplicated_zkapp_account_precondition_rows.sh
Fixed arguments count checks and conditional printing  in remove duplicated zkapp precondition row
> Zkapp duplicated rows script ux improvment 

- buildkite/scripts/export-git-env-vars.sh
With this change, we now support all of the likely URLs, including
```
https://foo:bar@github.com/ORG/REPO.git
https://github.com/ORG/REPO.git
git://github.com/ORG/REPO.git
git@github.com:ORG/REPO.git
```
See [this slack thread](https://o1-labs.slack.com/archives/C02BFPS6BA4/p1704773737899079) for original issue.
> Fix parsing of URLs

- src/app/archive/dune-project
- src/app/archive/lib/dune-project
- src/app/benchmarks/dune-project
- src/app/cli/src/dune-project
- src/app/dump_blocks/dune-project
- src/app/logproc/dune-project
- src/app/reformat/dune-project
- src/app/rosetta/dune-project
- src/app/runtime_genesis_ledger/dune-project
- src/app/zkapp_test_transaction/dune-project
- src/dune-project
- src/lib/transition_frontier/dune-project
- src/nonconsensus/dune-project
This was a mistake, and we have now learned from it :)
**Context:**
We had hoped that this option would get dune to warn us when we were underspecifying our dependencies. In particular, since dune is able to infer the transitive dependencies, it has all the information that we need. However, in practice this is implemented in a way that's very inconvenient to use:
* dune doesn't emit any warnings;
* dune doesn't resolve upstream transitive dependencies (e.g. `core -> core_kernel -> base -> base.caml`), which makes our external dependencies unnecessarily and unhelpfully verbose;
* the OCaml compiler is the only thing 'checking' the dependencies, and missing types are treated as 'abstract'
- this causes unpleasant and confusing error messages,
- the OCaml compiler uses head-normalising type …
> End the suffering, turn back on `implicit_transitive_deps`

- src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
Port of PR Fix genesis ledger directory growing in size #1473 that is in `berkeley`, but evaded `rampup` sadly.
* Not tested
Checklist:
> Rampup port: Fix genesis ledger directory growing in size

- src/app/itn_orchestrator/genqlient.graphql
- src/app/itn_orchestrator/schema.graphql
- src/app/itn_orchestrator/src/graphql.go
- src/app/itn_orchestrator/src/itn_orchestrator/main.go
- src/app/itn_orchestrator/src/params.go
- src/app/itn_orchestrator/src/set_zkapp_soft_limit.go
- src/app/itn_orchestrator/src/slots_won.go
- src/lib/mina_graphql/mina_graphql.ml
Bonus: ability to check that X% of stake were updated.
* Adds a command to Orchestrator to allow setting zkapp limit on nodes in the test environment
* Adds a command that (combined with existing `slots-won` command) allows to check that at least `X%` of stake were affected by the soft limit upgrade
* Tested on the large cluster:
* set limit to 23 zkapp txs/min
```
{"action":"discovery","params":{"offsetMin":15}}
{"action":"set-zkapp-soft-limit","params":{"limit":23,"nodes":{"type":"output","step":-1,"name":"participant"}}}
{"action":"slots-won","params":{"nodes":{"type":"output","step":-1,"name":"participant"}}}
{"action":"slots-covered-check","params":{"threshold":0.6,"slotsWon":{"type":"output","step":-1,"name":"slotsWon"}}} …
```
> Support setting zkapp limit in orchestrator

- graphql_schema.json
- src/lib/mina_graphql/types.ml
This PR is https://github.com/MinaProtocol/mina/pull/4654, updated for the latest code.
> Removing extra `epoch` in `lastEpochDelegators` docs

- CODEOWNERS
Because the SDK team is much less involved with this code than the protocol team
> Make protocol-eng the codeowners for archive node

- scripts/archive/split_precomputed_log.sh
- scripts/mina-local-network/mina-local-network.sh
- src/app/ledger_export_bench/README.md
- src/app/ledger_export_bench/dune
- src/app/ledger_export_bench/ledger_export_benchmark.ml
- src/lib/genesis_ledger_helper/lib/genesis_ledger_helper_lib.ml
- src/lib/mina_graphql/dune
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/runtime_config/dune
- src/lib/runtime_config/runtime_config.ml
This recreates the merge from https://github.com/MinaProtocol/mina/pull/14864 and one other merge conflict against rampup.
> Merge back to rampup

- nix/go.nix
- src/app/rosetta/lib/block.ml
There was an issue with Rosetta API when querying operations from accounts with multiple tokens where the operations would show multiplicated. This PR fixes it by constraining the queries to the default token.
Another issue was found where the API would present the same zkapp account update multiplicated when the same zkapp account updates existed in different blocks. This is fixed by constraining the zkapp account updates queries by block.
This was tested by running `rosetta-cli check:data` against ITN and verifying that the previously observed issue was fixed.
This PR also updates `rosetta-cli` in our nix flake to our fork that has the necessary signature modules.
> Fix issues with the Rosetta API block queries

- src/app/test_executive/hard_fork.ml
Two cases that weren't covered: cliff after the hard fork, and finish vesting on the hard fork block.
Closes #14853
> more exhaustive timing tests

- scripts/prepare-test-ledger.sh
Adds a script that downloads staking ledger for the current epoch in mainnet and updates keys in it to delegate to a defined set of delegates.
Usage:
```
KEY_BALANCE=100 NUM_GHOST_KEYS=2 ./scripts/prepare-test-ledger.sh B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg B62qmqMrgPshhHKLJ7DqWn1KeizEgga5MuGmWb2bXajUnyivfeMW6JE B62qmVHmj3mNhouDf1hyQFCSt3ATuttrxozMunxYMLctMvnk5y7nas1 > /tmp/new_ledger.json
```
Command above generates a ledger with three keys specified as arguments being delegates, each holding balance of `100 MINA`. Parameter `NUM_GHOST_KEYS` controls how many keys are not re-delegated. With three delegate keys and `NUM_GHOST_KEYS=2`, `2/5` keys in ledger are unaltered.
Defaults:
* `NUM_GHOST_KEYS = 0`
* `KEY_BALANCE = 100000`
* Ran …
> Add prepare test ledger script

- src/app/delegation_backend/src/delegation_backend/submit.go
Prior the change there was a check in `S3Save` if particular item (submission or block) already exists on S3, however whether it existed or not, the item was overwritten anyway. The change only checks whether block exists, and if it does, it skips writing it to S3. I believe that the same check for the submission is not needed as it has a timestamp in the 'filename' so it will be always different.
This change seem to significantly improve response times and memory usage of the application.
Load test has been performed prior and after applying the fix. Results gathered in the report: https://github.com/MinaFoundation/mina-delegation-program-tech/wiki/Load-Test-Report-2024%E2%80%9001%E2%80%9018
Checklist:
- Notify Velocity team if …
> Check if block exists on S3Save - delegation backend performance improvement.

- src/lib/consensus/intf.ml
- src/lib/consensus/proof_of_stake.ml
- src/lib/ledger_proof/ledger_proof.ml
- src/lib/ledger_proof/ledger_proof_intf.ml
- src/lib/mina_block/validation.ml
- src/lib/mina_state/blockchain_state.ml
- src/lib/mina_state/protocol_state.ml
- src/lib/mina_state/protocol_state_intf.ml
- src/lib/mina_state/snarked_ledger_state.ml
- src/lib/mina_state/snarked_ledger_state_intf.ml
- src/lib/transition_frontier/frontier_base/breadcrumb.ml
* Block validation to use first pass ledger for snarked ledger
* Lift snarked ledger hash to the protocol state/blockchain state lib and refactored the code a bit to make it clearer
* Fixed a bug in breadcrumb generation for tests
* Existing unit tests covered the changes
Checklist:
* Closes #0000
> Use first pass ledger for snarked ledger everywhere

- buildkite/scripts/check-compatibility.sh
This PR tweaks the logging script, using a background `docker container logs --follow` instead of manually repeating the last 10 lines of logs every 5 seconds.
> Stop repeating logs in compatibility test

- src/app/rosetta/docker-start.sh
- src/app/rosetta/init-db.sh
---
* This changes add te possibility to pull the SQL Dump, Genesis ledger and precomputed blocks from custom URLs
* As a consequence, it allows Rosetta to connect to custom network other that Mainnet, Berkeley or DevNet.
* There are no breaking changes
* I have built the images an managed to connect Rosetta to Testworld 2-0 minafoundation/mina-rosetta:2.0.0rampup8-56fa1db-focal
Checklist:
* Closes #14931
> Enable Rosetta to connect to custom networks

- buildkite/scripts/version-linter.sh
This PR fixes a bug where the current `berkeley` attempts to run the `mina` binary, even though it is not installed.
> Install mina binary before calling it in the version linter

- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
- src/lib/mina_lib/tests/tests.ml
- src/lib/trust_system/peer_trust.ml
- src/lib/trust_system/peer_trust.mli
This PR handles a corrupt or outdated trust system DB, by checking at startup that the values are parseable, and resetting to a new DB if not.
This is also required for starting a node running `berkeley` with a config directory from a `compatible` node.
> Remove the trust system DB if it is corrupted

- src/app/test_executive/hard_fork.ml
This PR fixes the flakiness of hard fork integration. The flakiness is that when getting the liquid balance, we are actually using the global slot from the consensus state: https://github.com/MinaProtocol/mina/blob/605b8c874ff5b4957e602972a4c97ed15b68c21f/src/lib/mina_graphql/types.ml#L934
My fix is also use the consensus slot instead of the most recent slot.
This fix would resolve the flakiness of the test.
*
Checklist:
* Closes #0000
> use consensus slot to compute the balance

- src/lib/node_status_service/dune
- src/lib/node_status_service/node_status_service.ml
Add information on resource usage to node status:
* uptime
* load
* total RAM
* free RAM
* total swap
* free swap
* number of running processes.
* Run an ITN node, connecting to a testing status service instance.
* CI
Checklist:
> Add system / resource usage to status reports.

- scripts/prepare-test-ledger.sh
Simple merge of `compatible` to `rampup`, no conflicts happened when merging.
Checklist:
> Merge compatible to rampup (30 jan 2024)

- src/app/rosetta/lib/account.ml
- src/app/rosetta/lib/block.ml
- src/app/rosetta/rosetta-cli-config/config.json
A change was missing from #14529. This PR fixes it, by adding the missing ids in Rosetta SQL queries.
Another issue was found in retrieving the balance from an account with multiple tokens, when the last relevant command of the account was related to a custom token. This is fixed here by constraining the queries to retrieve the balance to the default token id.
Rosetta integration test was very flaky, requiring many retries to succeed. This is improved by ignoring broadcast errors in `rosetta-cli` configuration. These errors happen because other parallel transactions are being sent to the network and they invalidate things like the nonce used by the Rosetta Construction API.
> Fix Rosetta SQL queries and improve Rosetta integration test reliance

- buildkite/scripts/export-git-env-vars.sh
Added new case when commit is tagged by berkeley related name.
As a result package build from commit which tag contains "berkeley" will be pushed to "berkeley" channel
> [CI] Berkeley channel in Debian Repository

- buildkite/scripts/export-git-env-vars.sh
- flake.nix
- nix/ocaml.nix
Clone of #15026 against `develop`.
To build mainnet node, use `nix build mina#mainnet`
For devnet node: `nix build mina#devnet`
* Ran a node, checked that `mainnet` profile was used when compiling
* Compared output of `mina advanced constraint-system-digests` between nix version and mainnet binary built by CI
Checklist:
> Introduce mainnet/devnet build profiles in nix (develop)

- buildkite/scripts/test-nix.sh
- buildkite/src/Jobs/Test/NixBuildTest.dhall
There's an issue with the nix test in CI where it fails due to ownership of a directory not belonging to the current user (example [here](https://buildkite.com/o-1-labs-2/mina-o-1-labs/builds/32540#018d6a24-84eb-458a-a634-006347c68a5e)). This PR fixes it by changing recursively the ownership of that directory (`/workdir`) to the current user.
This PR also makes CI run the test when the test script or any nix-related file is changed.
> [berkeley] Fix nix CI test issue with directory ownership

- buildkite/scripts/rosetta-integration-tests.sh
- buildkite/src/Constants/DebianVersions.dhall
- src/app/rosetta/rosetta-cli-config/config.json
This PR adds time-vesting accounts to the `rosetta-cli` integration test genesis ledger so that the behaviour of such accounts can be tested. These accounts are also added to the interesting accounts configuration of the tool so that they are verified at each block height, even when they are not involved in any transaction. This adds little overhead to the overall test and it's a nice check to have. It also serves as a sanity check for the changes in #14944.
> Test Rosetta with time-vesting accounts

- src/app/berkeley_migration/berkeley_migration.ml
- src/app/berkeley_migration/precomputed_block.ml
Introduced `--network` parameter which control prefix used when downloading precomputed blocks. This new parameter can be used when dealling with differenet network than mainnet.
> Allow berkeley_migration app migrate other networks than mainnet

- src/lib/crypto/kimchi_backend/common/plonk_dlog_proof.ml
Instead of the typical change which would have added a unit () argument to the function (to make the optional argument erasable), making the function look like
```
let extract_challenges_and_commitments ?message ()
```
, I chose to make the argument a labeled option type (which thus cannot be omitted), since it looks like the context in which this function is called never actually needs to omit this labeled parameter.
> Kimchi_backend: fix unerasable-optional-argument warning

- src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
fixes an issue in the migration cronjob where it (very sensibly) thinks errors are important. this one isn't, it'll get logged even when an account list is provided (due to the way it falls back to the account list only after failing to download it...)
> demote error to warn

- src/app/archive/lib/processor.ml
- src/app/archive/lib/test.ml
- src/app/berkeley_migration/berkeley_migration.ml
- src/app/berkeley_migration/sql.ml
- src/app/replayer/replayer.ml
- src/app/replayer/test/input.json
This PR contains 4 different fixes against our migration tools. Those 4 different fixes corresponding to 4 different commits.
[use v1_transaction_hash for find user_commands](https://github.com/MinaProtocol/mina/pull/15069/commits/231ac86d415dc20444cd18c81e38c20398fe0694) This commits fixes the processor so that when searching for the user command we would use `v1_state_hash`
[always create a checkpoint with migration mode](https://github.com/MinaProtocol/mina/pull/15069/commits/5e60c261de9a2ea2c2771c6d4a3761bdd5e61097) This commits makes the replayer always create a checkpoint when we are in the migration-mode
[mark all the blocks to be canonical in berkeley_migration app](https://github.com/MinaProtocol/mina/pull/15069/commits/77ebba65c91415353e35c5b35a4cfc6b2bf184a …
> Fixes for migration tools

- src/config/devnet.mlh
- src/config/mainnet.mlh
Sets these compile-time values correctly to 24
> zkapp_cmd_limit devnet/mainnet

- src/lib/crypto/snarky_tests/snarky_tests.ml
- src/lib/mina_base/protocol_constants_checked.ml
> Fix `to_input` for protocol constants so that all fields are included

- buildkite/src/Jobs/Lint/Merge.dhall
- src/config/fork.mlh
- src/config/fork_at_3757.mlh
- src/lib/blockchain_snark/blockchain_snark_state.ml
- src/lib/consensus/constants.ml
- src/lib/consensus/proof_of_stake.ml
- src/lib/genesis_constants/genesis_constants.ml
- src/lib/genesis_ledger_helper/lib/genesis_ledger_helper_lib.ml
- src/lib/mina_state/genesis_protocol_state.ml
- src/lib/network_pool/indexed_pool.ml
- src/lib/runtime_config/runtime_config.ml
- src/lib/snark_keys_header/snark_keys_header.ml
Closes #15070
Berkeley: https://github.com/MinaProtocol/mina/pull/15079
(the berkeley version is compatible with develop, unlike this one)
> Fork_config loses previous_ label

- buildkite/src/Command/Base.dhall
This PR fixes an issue where a flake / infra error may lead to a job being triggered, even though its dependencies aren't actually ready. See e.g. [this run](https://buildkite.com/o-1-labs-2/mina-o-1-labs/builds/32661#018da6ac-5fc9-4cd9-adc9-e4dfa11c17fd) trigger by the completion of the failed run [here](https://buildkite.com/o-1-labs-2/mina-o-1-labs/builds/32661#018da6ac-582e-40a5-837c-1d53e2ec20c2).
> Make buildkite dependencies depend on success

- buildkite/src/Command/Base.dhall
This PR builds upon #15113, adding a retry for `SIGTERM` (exit code 143) that we can see when buildkite kills the running command. See e.g. [this run](https://buildkite.com/o-1-labs-2/mina-o-1-labs/builds/32659#018da690-e63f-4023-8f44-4b0e63be3955) (on PR #15113) for an example.
> Retry jobs after sigterm

- src/app/rosetta/lib/block.ml
- src/app/rosetta/lib/network.ml
Due to the increased size of the genesis ledger post-hard fork, GraphQL queries for genesis info are significantly taking more time to be responded to. This affects Rosetta API requests that rely on these queries, to the point that concurrent Rosetta requests make the GraphQL endpoint unresponsive.
To mitigate this, this PR implements the preexisting memoization mechanism in all Rosetta API GraphQL queries that retrieve genesis info. After caching the GraphQL requests, subsequent Rosetta requests are responded to in a similar time as compared to when the genesis ledger is smaller.
This has been tested by running an updated Rosetta node connected to the post-hard fork test network and validating it with `rosetta-cli`.
> Memoize Rosetta API GraphQL requests for genesis info

- buildkite/src/Command/Base.dhall
For example: docker failed
[here](https://buildkite.com/o-1-labs-2/mina-o-1-labs/builds/32674#018da711-083c-4d2c-8e0a-1db265335889).
> Restart jobs on exit code 125

- scripts/hardfork/create_runtime_config.sh
This PR updates the hardfork package generation to compute a global slot implicitly from the genesis timestamp. In particular, this ensures that we have continuity of time between the old and new networks, so that timed accounts etc. do not experience time travel and continue according to the existing schedule.
Notice that the time per slot is hard-coded in the script. We should choose a place to extract it from in future instead.
Closes #15097
> Hardfork package generation: compute the global slot for the fork from the genesis timestamp

- scripts/prepare-test-ledger-hf-dryrun.sh
- scripts/prepare-test-ledger.sh
- scripts/run-hf-localnet.sh
1. Update prepare-test-ledger.sh to allow generating a ledger with normal distribution, delegatee balance cutoff and a nicer CLi interface
2. Introduce a new script that generates a mainnet-like ledger with all stake delegated to a key and start a network of two nodes operating off this ledger
To learn about usage of both scripts, run them with `-h` flag.
Script `scripts/run-hf-localnet.sh` can be used without change with both `compatible` and `berkeley`. In latter case `-b` flag should be provided.
Script `scripts/run-hf-localnet.sh` generates a configuration based on mainnet ledger and launches two local nodes.
It also sends transactions on interval to simulate networking activity and ledger mutation.
Usage as simple as (launches a local node with the given mina executable, if not …
> Add script to run a local network for HF testing

- src/app/delegation_verify/submission.ml
The fs option was looking for a submitted_at field in the submission and not a created_at
> Update Stateless Verifier Input Type

- src/lib/mina_compile_config/dune
- src/lib/mina_compile_config/mina_compile_config.ml
- src/lib/runtime_config/runtime_config.ml
#14516 introduced a dependency on `mina_numbers` for `mina_compile_config`. This broke the build of `src/nonconsensus` (see https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/1273#018d686f-508b-4630-b49e-3dddd6ee9e7d).
This PR removes that dependency by making the parameters `int` and delegation to `runtime_config` the conversion to `Global_slot.t`, as it happens already in other branches.
> Remove dependency from mina_numbers from compile config

- src/lib/mina_graphql/mina_graphql.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_lib/mina_lib.mli
This PR fixes https://github.com/MinaProtocol/mina/issues/15149, by adapting the Mina_lib.next_epoch_ledger to ignore the finalisation check when a flag is passed, and then passing that flag in the fork_config GraphQL endpoint.
Berkeley counterpart in https://github.com/MinaProtocol/mina/pull/15186.
> [compatible] Update fork_config export to expose unfinalized next_epoch_ledgers

- buildkite/scripts/export-git-env-vars.sh
Branch names  can now have the `#` character in their name, e.g., to refer to  the issue they are resolving.
> Allow `#` in branch names

- src/lib/mina_graphql/mina_graphql.ml
Port of Ensure fork slot precedes stop slot #15189 to `berkeley`.
Problem: when there is a block created exactly at `stop-txn-slot`, it will be chosen as the block to donor height, slot and state hash for fork config. This is an unnecessary corner case.
Solution: make sure that fork config always refers a block happening strictly before the `stop-txn-slot`.
* TBD
Checklist:
> Ensure fork slot precedes stop slot (berkeley)

- flake.nix
- nix/ocaml.nix
To build mainnet node, use `nix build mina#mainnet`
For devnet node: `nix build mina#devnet`
* Ran a node, checked that `mainnet` profile was used when compiling
* Compared output of `mina advanced constraint-system-digests` between nix version and mainnet binary built by CI
Related PRs:
* https://github.com/MinaProtocol/mina/pull/15026
* https://github.com/MinaProtocol/mina/pull/15028
* https://github.com/MinaProtocol/mina/pull/15181
Checklist:
> Introduce mainnet/devnet build profiles in nix

- src/lib/runtime_config/runtime_config.ml
This PR let permissions in runtime_config to use the default value from `Permissions.user_default`
*
Checklist:
* Closes #0000
> let default permissions to be the same as user_default

- src/lib/mina_graphql/mina_graphql.ml
Problem: when there is a block created exactly at `stop-txn-slot`, it will be chosen as the block to donor height, slot and state hash for fork config. This is an unnecessary corner case.
Solution: make sure that fork config always refers a block happening strictly before the `stop-txn-slot`.
* TBD
Checklist:
> Ensure fork slot precedes stop slot

- src/lib/cli_lib/commands.ml
Actually really disable the deprecation alerts, or the story of an extra hyphen.
The actual better fix would be https://github.com/MinaProtocol/mina/pull/12768 but we might want to have this one low-hanging fix-fruit in nonetheless
> Cli_lib: correctly mark alert as deprecated

- buildkite/scripts/build-hardfork-package.sh
- src/lib/cache_dir/native/cache_dir.ml
- src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
MINA_LEDGER_S3_BUCKET env var now allows overriding the URL where we check for ledger tars.
Hardfork package uploads its ledgers during build, while being careful not to clobber existing tarballs.
> hf package upload ledgers

- automation/terraform/modules/kubernetes/testnet/locals.tf
- automation/terraform/modules/kubernetes/testnet/variables.tf
- automation/terraform/modules/o1-integration/inputs.tf
- automation/terraform/modules/o1-integration/testnet.tf
- automation/terraform/modules/o1-testnet/inputs.tf
- automation/terraform/modules/o1-testnet/testnet.tf
- helm/block-producer/templates/block-producer.yaml
- helm/block-producer/values.yaml
- helm/plain-node/templates/plain-node.yaml
- helm/plain-node/values.yaml
- helm/seed-node/templates/seed-node.yaml
- helm/seed-node/values.yaml
- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
- src/lib/integration_test_cloud_engine/mina_automation.ml
- src/lib/integration_test_lib/test_config.ml
- src/lib/integration_test_local_engine/mina_docker.ml
- src/lib/mina_lib/config.ml
- src/lib/mina_lib/mina_lib.ml
This PR adds a new CLI flag `--start-filtered-logs`, which can be passed multiple times with a filter to each argument.
This PR also includes my attempt at updating the terraform to propagate this change.
Currently, integration tests are broken against develop, because now the seed nodes start up 'too quickly' (i.e. sleeping for 60s at startup). The hope is that this PR will solve that problem without us needing to make them slow again.
> [develop] Fix integration tests for fast seed startup

- flake.lock
- flake.nix
* Add another signing key for nix substituter (generated by @georgeee)
* Bump `opam-repository` (package `ocamlgraph` had broken URL in the previous version)
* Built with `#devnet` profile, observed cache is used successfully
Checklist:
> [compatible] Tiny updates to nix 

- src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml
- src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
The value in the JSON is encoded using the wrong check byte. It isn't used anywhere else though.
> Ledger_hash and State_hash are different

- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
- src/lib/mina_lib/config.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/node_status_service/node_status_service.ml
This pull request adds support for simplified data reporting in the node status service. It includes changes to the CLI and configuration to enable the reporting of simplified node stats by providing `--simplified-node-stats`.
This was tested by running a node with `mina daemon --node-status-url https://nodestats-itn.minaprotocol.tools/submit/stats --simplified-node-stats ...` and checking if payloads are received and processed correctly by OpenSearch.
PRs for other branches:
- #15241 
- #15242
> Support simplified data reporting in node status service

- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
This PR attends a late request for #15231 that was left out: setting `--simplified-node-stats` to default to true.
> Set simplified node stats reporting to be default

- src/app/replayer/replayer.ml
This PR modifies the replayer so that it also records the ledger hash in the `genesis_ledger` field for each checkpoint.
*
Checklist:
* Closes #0000
> record the ledger in the replayer

- buildkite/src/Jobs/Release/MinaArtifactHardforkBuster.dhall
- buildkite/src/Jobs/Release/MinaArtifactHardforkFocal.dhall
This pulls in the missing builds, grabbed from [here](https://github.com/MinaProtocol/mina/pull/15251/commits/85e7e38abf46152d6279d88cf176d8b639d02080) on #15251.
> Add buster + focal HF builds

- src/lib/mina_base/coinbase.ml
- src/lib/mina_ledger/ledger.mli
- src/lib/mina_ledger/test/helpers/ledger_helpers.ml
- src/lib/transaction_logic/test/transaction_logic/main.ml
- src/lib/transaction_logic/test/transaction_logic/transaction_logic.ml
This PR cherry-picks https://github.com/MinaProtocol/mina/pull/13860 onto `berkeley`, and adds a test that passes only when the fix is applied. All credit goes to @sebastiencs.
Checklist:
> Fix order of accounts in ledger coinbase witness

- automation/terraform/modules/testnet-alerts/templates/testnet-alert-rules.yml.tpl
This PR builds on #15281, demoting the `CriticallyLowMinWindowDensity` alert to a warning. This alert has been firing for some time, but we can't act to fix it until after berkeley. Accordingly, we have no need to use it as an alert until berkeley is released.
> Convert `CriticallyLowMinWindowDensity` to a warning (until berkeley)

- src/lib/crypto/kimchi_backend/common/plonk_constraint_system.ml
When checking constraints, snarky will call the `eval` function of the constraint to determine if it failed:
https://github.com/o1-labs/snarky/blob/b539752a5c075f2d822703a7d5bf00f19f805d63/src/base/checked_runner.ml#L214
If `eval` returns `false`, an error is thrown which describes the failure.
The `eval` function for `Plonk_constraint.Basic` was behaving a little unusual: Instead of just returning `false`, it also logged information about the constraint to the console.
None of the other `eval` functions do this, and it's not the right thing to do: in tests, you often _want_ to confirm that a certain constraint is failing, and don't want your console spammed by such a test. This PR fixes the behavior, which was hurting the DX of using custom generic gates in o1js.
> Do not log constraint failures to the console

- dockerfiles/stages/3-toolchain
Removing unnecessary use of `wget`, replacing with `curl`.
`compatible` PR: https://github.com/MinaProtocol/mina/pull/15304
> Resolving conflicts with develop from #15304

- src/app/replayer/replayer.ml
Added ability for replayer to dump repair nonces script which then can be applied to target db. Usage:
```
mina-replayer  --archive-uri postgres://....  --dump-repair-script repair.sql --repair-nonces --set-nonces
```
:warning: `--dump-repair-script` works only when repair-nonces or set-nonces are applied.
After successful run one can applied repair.sql script like below:
```
(echo "BEGIN;"; cat repair.sql; echo "COMMIT;") | psql -U postgres -d archive_balances_migrated
```
> Replayer can dump sql script after fixing nonces

- src/app/replayer/replayer.ml
Changed global_slots_to_avoid to state_hashed_to_avoid array in order to support other networks, like denvet. Before the change, it was not possible to add slots from other network as global slot to avoid on mainnet not necessarily should be skipped in devnet and vice versa
> Replayer: convert global slots to avoid to hashes in order to support devnet

- flake.nix
- nix/ocaml.nix
_PR against develop: https://github.com/MinaProtocol/mina/pull/15340_
Problem: berkeley archive migration app is not specified in the nix build.
Solution: add berkeley archive migration app into flakes.
Note: building the archive migration app requires DUNE_PROFILE to be set to a specialized value.
Checklist:
* Closes #0000
> Add berkeley archive migration app to nix

- nix/ocaml.nix
Problem: mina-berkeley-migration-verifier, mina-migration-replayer are not included in the migration build offered by nix.
Solution: build the two additional apps.
* Build the tools, run `--help`
Checklist:
> [Nix] Build verifier and replayer for berkeley migration

- dockerfiles/stages/1-build-deps
This reverts commit fe5d9eb55070f7c07a07533773366fad7c5d0b34.
That patch is no longer needed (upstream should be fine, flakiness was seemingly temporary)
Checklist:
> Revert parsetree patch

- dockerfiles/Dockerfile-mina-test-executive
- dockerfiles/stages/3-toolchain
This avoids a 60s wait when building these docker images caused by the deprecated version warning.
Checklist:
> Upgrade nodesource install to supported nodejs version

- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
- src/lib/cli_lib/arg_type.ml
- src/lib/mina_lib/config.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/node_status_service/node_status_service.ml
This pull request replaces the `--simplified-node-stats` flag with the optional node status type flag (`--node-status-type`). This flag allows three values: `simple` enables simple status reporting, `full` enables full status reporting, and `none` disables status reporting. The default value is `simple` and a hard coded node status URL is used. This URL can be overridden at runtime by using the `--node-status-url` flag.
It also adds the block producer public key to the full node status payload.
Tested by running the daemon with the different combinations of flags and the observed behaviour matches the expected one.
> Node status type flag

- src/app/berkeley_migration_verifier/sql.ml
This PR fixes berkeley_migration_verifier so that it ignores genesis accounts in genesis block
*
Checklist:
* Closes #0000
> ignore genesis accounts in berkeley_migration_verifier

- src/app/rosetta/lib/block.ml
This pull request fixes an issue where user commands were not being retrieved correctly when the receiving account does not exist in the database. The SQL query has been updated to handle this scenario properly.
This has been tested against the migrated devnet DB, which had a scenario where this issue was present.
> Fix issue retrieving user commands when receiving account doesn't exist in the DB

- nix/ocaml.nix
- scripts/rebuild-deb.sh
- src/app/runtime_genesis_ledger/dune
- src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml
* Port changes from `berkeley` to allow for `runtime_genesis_ledger` tool to generate hashes json file with ledger hashes of config file being used as an input
* Generate a new debian package with `runtime_genesis_ledger` corresponding to mainnet's version (hence names as create "legacy" ledger)
* Part of HF unit test, tested there
Checklist:
* Closes #0000
> Port runtime_genesis_ledger from Berkeley (without SHA3 hash)

- buildkite/scripts/caqti-upgrade-plus-archive-init-speedup.patch
- buildkite/scripts/caqti-upgrade.patch
- flake.nix
- nix/ocaml.nix
Apply `caqti-upgrade-plus-archive-init-speedup.patch` to sources before building the packages.
* Built `berkeley` package with `nix build .?submodules=1#mainnet-caqti-patched.berkeley_migration`
* Ran incremental migration pass with `mina-berkeley-migration-script incremental -g mainnet.json -b mina_network_block_data -bs 50 -n mainnet -s postgres://mina@localhost:5440/archive_feb19 -t postgres://mina@localhost:5440/migrated -r migration-checkpoint-497736.json`
Checklist:
> Update nix files to build berkeley migration tools

- scripts/archive/migration/README.md
- scripts/archive/migration/mina-berkeley-migration-script
- src/app/berkeley_migration_verifier/Readme.md
- src/app/berkeley_migration_verifier/berkeley_migration_verifier.ml
* Remove redundant parameter `--fork-state-hash` from `final` step
* Use `grep '"level":"Error"'` instead of `grep Error` for checking errors in logs
* Rename `--fork-config` and `--fork-config-file` parameters in migration script/verifier to `--fork-genesis-config`
Checklist:
> Fixes to migration script

- src/lib/mina_graphql/mina_graphql.ml
renaming to avoid confusion
*
Checklist:
* Closes #0000
> [berkeley] target_height -> txn_stop_slot

- buildkite/scripts/caqti-upgrade-plus-archive-init-speedup.patch
- buildkite/scripts/caqti-upgrade.patch
- src/app/archive/lib/processor.ml
- src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml
Currently the archive node breaks when adding genesis accounts if there isn't a protocol version that matches the transaction version used by those accounts. This seems wholly unnecessary, and leads to nasty hacks like #15471 (where we add a fake `X.4611686018427387903.4611686018427387903` version).
This PR deletes the unnecessary check.
> Don't check the transaction version when adding accounts

- buildkite/scripts/caqti-upgrade-plus-archive-init-speedup.patch
- buildkite/scripts/caqti-upgrade.patch
- src/app/berkeley_migration_verifier/berkeley_migration_verifier.ml
- src/app/berkeley_migration_verifier/sql.ml
This PR modifies the verifier so that it directly does the comparison in ocaml instead of dump the result and then run `diff` on it. This change would make the verifier a little bit slower (not too bad). For mainnet, it increased about 30 secs.
I've run the verifier against the devnet data using this dump: gs://mina-archive-dumps/devnet-archive-migrated-2024-03-22_2050.sql.tar.gz and everything is good
I've also run the verifier against the mainnet using the following 2 dumps: 
1. gs://mina-archive-dumps/mainnet-migrated-archive-dump-2024-04-04_0200.sql.tar.gz This is failing for the 3rd check
```
jiawei@bench-30vcpu-120gb-c2-cl:~/mina$ time _build/default/src/app/berkeley_migration_verifier/berkeley_migration_verifier.exe …
```
> Do comparison in ocaml instead of dump the result and then run diff on it

- buildkite/src/Jobs/Test/SingleNodeTest.dhall
This PR fixes flakes in the `single-node` integration test in CI, where it can trigger before all of its dependencies are ready.
> [berkeley] Wait for all dependencies in the single-node integration test

- buildkite/scripts/build-hardfork-package.sh
- scripts/mina-verify-packaged-fork-config
Which is fixed by PR #15462
*
Checklist:
* Closes #0000
> [Draft] Patch build-hardfork-package.sh against a bug in 1.4

- src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/runtime_config/runtime_config.ml
* Use the correct value of staged ledger hash in the `.ledger.hash` field
* Do not inherit fields of genesis ledger (`name`, `balances`, `num_accounts`, `hash`)
* Make `runtime_genesis_ledger` more strict in accepting fork configs
PR group:
* _compatible_: https://github.com/MinaProtocol/mina/pull/15462
* _berkeley_: https://github.com/MinaProtocol/mina/pull/15464
* _develop_: https://github.com/MinaProtocol/mina/pull/15465
Checklist:
> Fix fork config export

- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
- src/lib/gossip_net/libp2p.ml
- src/lib/mina_graphql/types.ml
- src/lib/mina_lib/tests/tests.ml
This PR makes the `--libp2p-keypair` CLI argument optional, to avoid the irritating setup steps when first running a Mina node.
This option was added to ensure persistence will interact correctly with bitswap: if a node restarts, the network's knowledge of its persisted data will be preserved, and it doesn't need to re-advertise the contents of its store. However,
* bitswap is currently enabled, so this annoyance is for nothing, and
* if persistence *isn't* enabled for the node, re-using the libp2p keypair will mislead the network into believing that it has data that it doesn't.
After some discussion, it appears that
* converting the flag back to optional immediately does no harm and improves UX considerably, and
* we can solve the issues properly by persisting the libp2p keypair …
> [berkeley] Make libp2p_keypair CLI argument optional again

- buildkite/scripts/build-hardfork-package.sh
- scripts/mina-verify-packaged-fork-config
Problem: when ledgers for the fork where uploaded, wrong sha3 hashes of archives are going to be used in the config that is put into a .deb file.
Solution: replace quotes in bash.
Checklist:
> Fix incorrect ledger archive hashes

- dockerfiles/scripts/daemon-entrypoint.sh
This PR removes a pattern that would handle (hidden) scripts which start with `.`, ensuring that all scripts are easily visible with `ls`. This logic also includes the directories `.` and `..`, giving us the annoying message
```
[ERROR] Entrypoint script /entrypoint.d/.. is not a regular file, ignoring
```
at every docker startup.
> [berkeley] Fix entrypoint.d warning on startup: don't allow hidden scripts, and don't include `.` and `..` as scripts

- buildkite/scripts/export-git-env-vars.sh
- scripts/release-docker.sh
In order to prevent unintentional releases from personal branches or nightly I removed logic which decides where to push artifacts. Now it will push debian into unstable channel and dockers to gcr. We will then rely on promotion pipeline to promote packages to other channels in a fully controlled way.
On the horizon there is one possible fork of logic when we will introduce different channel and tag for nightly releases
> [CI] Disable logic which decides where to push artifacts

- buildkite/src/Constants/ContainerImages.dhall
- flake.lock
- flake.nix
- nix/go.nix
- nix/impure-shell.nix
- nix/misc.nix
- nix/ocaml.nix
- nix/rust.nix
- nix/update-libp2p-hashes.sh
- nix/vend/default.nix
- opam.export
- src/external/ocaml-rocksdb/rocks_options.ml
Problem: some old unstable nixpkgs is used in flake.nix, which is potentially insecure.
Solution: bump the version of nixpkgs, and a few more flakes.
Checklist:
> Use stable nixpkgs version (23.11)

- buildkite/scripts/caqti-upgrade-plus-archive-init-speedup.patch
- buildkite/scripts/caqti-upgrade.patch
- src/app/archive/lib/processor.ml
This PR moves the update to parent_id to the very end. The reason is that if berkeley_migration app crashed before migration finished. Then blocks with null parent_id would be considered as garbage and would be removed once migration being restarted.
I've tested this change with umt data. Without this change, if we crash just after the parent_id being set, then the block would not be removed and those block would be considered valid and the corresponding `blocks_user_commands` table would not be populated after restart migration
Checklist: …
> update parent_id at the very last

- docs/specs/types_and_structures/serialized_key.md
- src/lib/blockchain_snark/blockchain_snark_state.ml
- src/lib/pickles/compile.ml
- src/lib/pickles/compile.mli
- src/lib/pickles/pickles.ml
- src/lib/pickles/pickles_intf.mli
- src/lib/snark_keys_header/snark_keys_header.ml
- src/lib/transaction_snark/transaction_snark.ml
Use only git commit
Checklist:
> Omit verbose git info in snark keys header

- src/app/delegation_verify/dune
- src/app/disk_caching_stats/dune
- src/app/snark_work_debugger/dune
- src/lib/integration_test_cloud_engine/dune
- src/lib/integration_test_local_engine/dune
- src/lib/merkle_ledger_tests/dune
- src/lib/o1js_stub/dune
- src/lib/transaction_logic/test/dune
- src/lib/transaction_logic/test/transaction_logic/dune
For libraries `fields_derivers.zkapps` and `mina_base.import` always use public name in other libraries' dependencies.
This change doesn't affect dune compilation, but allows to always distinguish nonconsensus libraries from their consensus "originals", even if the profile check is not performed.
This in turn reduces number of concerns involved in dependency analysis.
* It compiles
Checklist:
> Use public names for `fields_derivers.zkapps` and `mina_base.import`

- buildkite/scripts/run_promote_build_job.sh
Do not exit when PROFILE or NETWORK is not defined but use defaults
> Correctly handle defaults on run_promote_build_job.sh

- src/lib/pickles/wrap_main.ml
This PR fixes https://github.com/o1-labs/o1js/issues/1336 (using https://github.com/o1-labs/o1js/pull/1335 as the repro case).
The underlying issue was that we were using the feature flags for the step circuit when reasoning about the contents of the wrap proofs. In particular,
* when the circuit uses a feature
* and it uses recursion
* then it expects that feature to be used by the wrap proof that it recurses over (even though wrap never uses any custom gates).
This PR fixes that by hard-coding `Features.Full.none`.
> Fix: don't use step feature_flags for wrap evaluations

- src/lib/node_error_service/node_error_service.ml
- src/lib/node_status_service/node_status_service.ml
Use only git commit
Checklist:
> Omit git branch in node status/error reports

- src/lib/integration_test_lib/dsl.ml
- src/lib/integration_test_lib/dune
- src/lib/merkle_ledger/dune
- src/lib/merkle_ledger_tests/dune
- src/lib/transition_frontier/persistent_frontier/diff_buffer.ml
- src/lib/transition_frontier/persistent_frontier/dune
- src/lib/transition_frontier/persistent_frontier/sync.ml
This fixes #1471. We only depended on `extlib` for `DynArray`, and none of the uses actually required a `DynArray`.
Checklist:
> Remove dependency on extlib

- src/app/dump_blocks/dump_blocks.ml
Fix the warning
* App compiles
Checklist:
> Fix warnings in dump_blocks

- src/lib/network_pool/test/indexed_pool_tests.ml
- src/lib/transaction_logic/test/transaction_logic/transaction_logic.ml
This PR builds upon #15648.
This PR reduces the runtime of some slow quickcheck unit tests by reducing the number of trials from 10,000 to 1000, with the goal of reducing the runtime of unit tests in CI.
> Reduce quickcheck trials from 10,000 to 1000 for some slow tests

- genesis_ledgers/mainnet.json
Soft fork update to set stop-slots in mainnet config file for the upcoming berkeley upgrade.
Slot set as per the announced date **June 4, 2024**.
Setting stop-slots such that the timings match all the dry-runs and devnet upgrade schedule and as a result- 
* stop-transaction slot is **564180** (June 4th 9am UTC). This translates to 120th slot of 79th epoch. Upgraded nodes won't accept blocks with transactions at/after this slot
* stop-network slot is **564280** which is 100 slots/5hours after the stop-transaction slot (June 4th 14:00 UTC). This translates to 220th slot of 79th epoch. Upgraded nodes won't accept any blocks at or after this slot 
These calculations are based on mainnet genesis timestamp `2021-03-17 00:00:00 UTC`
Reviewer- please perform the calculation once more for sanity …
> Stop slots for mainnet upgrade

- scripts/archive/migration/mina-berkeley-migration-script
Exposing checkpoint-prefix parameter in berkeley migration script. It might be helpful when we have more that one migration on single machine (devnet and mainnet) and for some reason we would like to keep both checkpoints. This is the case for our cron job which is used for more than one network and it need to be aware of checkpoint prefixes
> Introduce checkpoint prefix argument to migration script

- .gitmodules
- buildkite/scripts/build-hardfork-package.sh
- src/lib/crypto/dune
- src/lib/crypto/kimchi_bindings/stubs/.cargo/config
- src/lib/crypto/kimchi_bindings/stubs/dune
We were exposed to supply chain attacks because our Rust dependencies were not pinned. This PR fixes that by pinning the kimchi stubs dependencies and also incorporating all vendored dependencies available in proof-systems.
* Vendored all Kimchi stubs dependencies to a separate repository (i.e., [`kimchi-stubs-vendors`](https://github.com/MinaProtocol/kimchi-stubs-vendors)).
* Incorporated the `kimchi-stubs-vendors` repository as a dependency through git submodules.
* Updated the Kimchi stubs dune script with proper instructions to use the vendored dependencies.
* Pulled in all the vendored dependencies available in `proof-systems:berkeley`.
* Verified that our build scripts no longer downloads crates from remote sources, both on …
> Vendored dependencies 

- buildkite/src/Constants/ContainerImages.dhall
- opam.export
- src/lib/cli_lib/commands.ml
- src/lib/cli_lib/dune
This PR removes the deprecation warning yielded by the use of `Caml.Stream` by depending on package `camlp-streams`. 
This needed https://github.com/MinaProtocol/mina/pull/15683 to work correctly.
> Fix Stream deprecation warning

- buildkite/scripts/rosetta-integration-tests.sh
- src/lib/genesis_ledger_helper/lib/genesis_ledger_helper_lib.ml
- src/lib/integration_test_cloud_engine/mina_automation.ml
- src/lib/integration_test_lib/test_config.ml
- src/lib/integration_test_local_engine/mina_docker.ml
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/runtime_config/runtime_config.ml
This is a pr that adds the network id field to the daemon. It's purpose is to ensure the correct output result from a fork config, such that the networkId graphql endpoint is correct.
> adding network id field to the daemon

- docs/upgrading-to-berkeley.md
Updating package verification documentation to include some additional environment configuration steps and mina-legacy-create-genesis instructions after stable name change.
> Berkley Package Verification Documentation Upgrade

- automation/terraform/modules/testnet-alerts/templates/testnet-alert-rules.yml.tpl
Set the hard coded genesis timestamp in mainnet alerts to `1717545600`, which is `2024 June 05 00:00 UTC`.
> Update hardcoded genesis timestamp in alerts to 3.0.0 genesis timestamp

- src/lib/mina_net2/multiaddr.ml
* maps `String.strip` over the lines of the peerlist file
* ~~I haven't been able to get a locally compiled node to run, but I've confirmed that adding spaces to the peer list without this change does change the error message and with this change no longer changes the error message.~~
* I've used this branch to run a node using a peerlist with trailing spaces
Checklist:
* Closes #15696
> ignore any leading/trailing whitespace in the peerlist

- buildkite/scripts/export-git-env-vars.sh
Currently `MINA_BUILD_MAINNET` flag is set in export_git_env_vars.sh. However it's not exported and thus mainnet package is not built. This is due to lack of exporting MINA_BUILD_MAINNET flag which causes that build-artifact.sh script is not building mina_mainnet_signatures.exe which then is missing when trying to build debian. I think this was an effect of not complete merge to master since develop already has this change. I tested mix fix in nightly:
https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/2132
Jobs failing:
`Build Mina for *` - so basically all mina build jobs. For example:
https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/2130#01902914-0abe-470b-919e-5d67ac2004c0
> Properly use MINA_BUILD_MAINNET flag

- scripts/release-docker.sh
We are not distinguishing instrumented docker in CI. This PR is adding `-instrumented` suffix to a daemon and archive docker
> Add suffix to docker version if we are building instrumented dockers

- src/lib/merkle_ledger_tests/dune
- src/lib/merkle_ledger_tests/main.ml
- src/lib/merkle_ledger_tests/test.ml
- src/lib/merkle_ledger_tests/test_database.ml
- src/lib/merkle_ledger_tests/test_mask.ml
- src/lib/merkle_ledger_tests/test_stubs.ml
Use `alcotest` to express tests for Merkle ledger(s).
Sneaked in a small update in one the test Modules.
> Move Merkle ledger tests to Alcotest

- buildkite/src/Jobs/Lint/Merge.dhall
Since we are not using actively berkeley branch and we are fallback to having develop,compatible,master branches, we need to also convert merges cleanly check from berkeley to master
> Move merges cleanly check from berkeley do master

- scripts/deb-builder-helpers.sh
Another fix for master CI, looks like after update to newest master and fix for mainnet signature there was another issue lurking in the shadows. If we are using mainnet signatures then we are also building devnet package, but for this we are using non-existing method. This PR fixes it
> [CI/Master] Rename copy_control_file -> create_control_file

- buildkite/scripts/debian/install.sh
- src/app/test_executive/verification_key_update.ml
Fix nightly for verification key update in nightly for develop. After last commit nightly is happy:
https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/2144
Fix was to partially revert incorrect merge from o1js-main: 
https://github.com/MinaProtocol/mina/pull/15594/commits/adf934d28f491d850c9d8e83e35a5857a74f59f6
> Fix verification key update in develop

- src/lib/mina_generators/user_command_generators.ml
This PR brings some optimisations for the zkapp generators used by tests and the batch transaction tool. In particular:
* we don't use an on-disk ledger, avoiding disk IO entirely
* we batch the writes for ledger initialisation, dramatically speeding up that part of the code.
On my machine, this brings the runtime of the test in `src/lib/staged_ledger/tests` down from 528s to 247s, a roughly 115% speed-up.
> Speed up zkapp generators

- src/lib/mina_base/test/zkapp_command_test.ml
- src/lib/mina_base/user_command.ml
- src/lib/mina_base/zkapp_command.ml
Problem: this check is the only one we perform in this layer, seemingly for no good reason.
Solution: move the check to where all of the other zkapp command checks reside.
P.S. this refactoring makes analysis of the code easier, because all tx-related checks are now located in a single place.
* Tested on mainnet via custom build
Checklist:
> Move wire check to the tx validation logic

- Makefile
The script that the target  is supposed to launch does not exist anymore.
> Makefile: rm check-proof-systems-submodule target

- src/lib/fields_derivers_zkapps/fields_derivers_zkapps.ml
companion of https://github.com/o1-labs/o1js/pull/1749
Note: this PR doesn't change the format of the `balanceChange` field, but adds a hint to that type that we need to change some of the automatically derived defaults on the JS type (that will be autogenerated using this deriver).
In this case, we want to modify the defining constraints of the  `balanceChange` type such that it can never be `{ magnitude: 0, sgn: Negative }`. We want to prevent this case because it implies a non-unique representation of 0, which can lead to unexpected vulnerabilities.
With the existing deriver, the balance change type would just be composed from its parts, a `UInt64` and a `Bool`. By adding the `needs_custom_js` annotation, the generated TS code allows us to provide customization of the composed type.
> [o1js] Custom deriver type for Int64 / BalanceChange

- src/lib/rocksdb/database.ml
I'm not certain how often this happens, but at least in some reproducible cases `foldi` and `fold_until` behave as if the database were empty. Seemingly because `Iterator.create` does not always return an iterator at the first entry. Adding this `seek_first` call seems to fix this. Computing the size of the database with a fold agrees with the length of the list returned by `to_alist` in the case where it previously consistently did not.
> Fix bug with rocksdb fold methods

- src/lib/crypto/kimchi_bindings/stubs/dune
Compilation of the library as a standalone unit fails without this flag.
* Library compiles as part of granular nix approach
Checklist:
> Add (no_dynlink) to kimchi_bindings stubs

- graphql_schema.json
- src/lib/mina_graphql/mina_graphql.ml
This PR adds a new GraphQL query `protocolState` to retrieve the current protocol state. The query allows clients to fetch the protocol state in either JSON or Base64 encoded format.
Addressing the request for https://github.com/MinaProtocol/mina/issues/15825
1. Added a new field protocolState to the GraphQL schema
1. Implemented resolver for the protocolState query
1. Added option to return the protocol state as JSON or Base64 encoded
The new query provides the following functionality:
- Retrieves the current protocol state from the best tip of the blockchain
- Allows clients to specify the desired encoding format (JSON or Base64)
- Returns the full Mina_state.Protocol_state.Value.Stable.V2.t type
This addition enables clients to:
- Extract consensus data for consensus rules checking
- …
> Add `protocolState` GraphQL query for JSON and Base64 encoded protocol state

- automation/terraform/modules/o1-testnet/files.tf
- automation/terraform/modules/o1-testnet/inputs.tf
- automation/terraform/testnets/ci-net/main.tf
- buildkite/scripts/terraform-test.sh
This PR creates the required `peerid` key files in order to make the `terraform plan` command succeed.
As the Terraform file is not applied, this fix makes the job succeed and still tells us the Terraform files are ok in terms of syntax and functionality.
> Fix Terraform tests by synthetically creating required seed peerid files

- buildkite/src/Jobs/Test/HFTest.dhall
- buildkite/src/Jobs/Test/TestnetIntegrationTests.dhall
- buildkite/src/Jobs/Test/TestnetIntegrationTestsLong.dhall
Introduced two changes which should make develop nightly green again:
- soft fail to hf test (while fixing is in progress)
- moving all integration tests to docker
> [Develop][Nightly][CI] Making nightly tests green

- src/lib/blockchain_snark/blockchain_snark_state.ml
- src/lib/blockchain_snark/dune
- src/lib/pickles/compile.ml
- src/lib/pickles/compile.mli
- src/lib/pickles/pickles.ml
- src/lib/pickles/pickles_intf.mli
- src/lib/snark_keys_header/snark_keys_header.ml
- src/lib/transaction_snark/dune
- src/lib/transaction_snark/transaction_snark.ml
Commit id was only used for snark header files. This could be safely removed.
* Pickles code compiles
Checklist:
> Remove commit field for Pickles

- src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
- src/lib/mina_compile_config/mina_compile_config.ml
- src/lib/mina_compile_config/mina_compile_config.mli
- src/lib/mina_lib/tests/tests.ml
- src/lib/node_config/node_config.ml
- src/lib/node_config/node_config.mli
- src/lib/test_genesis_ledger/test_genesis_ledger.ml
This PR raises an error if no configuration file has set the `ledger` field for the network, instead of falling back to a test ledger.
This removes one of the compile-time configuration variables.
> Make "ledger" field required in runtime config

- src/lib/mina_intf/transition_frontier_components_intf.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_lib/tests/tests.ml
- src/lib/transition_router/initial_validator.ml
- src/lib/transition_router/transition_router.ml
This PR performs a small refactor on the `Initial_validator` library, turning it into a helper function `Initial_validator.validate` called directly from the pipe in `Transition_validator`, instead of running it as a sub-process.
> Pipeless initial validator

- buildkite/src/Jobs/Test/RosettaIntegrationTests.dhall
Making rosetta integration tests soft fail until fixed
> add soft fail to RosettaIntegrationTests

- src/app/rosetta/lib/graphql.ml
This pull request replaces new line characters with spaces instead of empty strings in Rosetta's GraphQL client. This change ensures that the resulting string does not contain any newline characters and that words are separated by a space, thus fixing an existing issue where some words were wrongfully joined.
> [Rosetta] Replace new line with space instead of empty string in GraphQL

- buildkite/src/Command/HardforkPackageGeneration.dhall
- scripts/create_hardfork_deb.sh
> build rosetta for hardfork

- src/lib/mina_graphql/types.ml
This PR fixes `epochDelegateAccount` so that its behaviour matches the description, returning the account from the staking ledger to which this account has delegated. It has been broken since its inception in https://github.com/MinaProtocol/mina/pull/3904, where its behaviour has been to always return the same account from the current staking ledger.
> Fix `epochDelegateAccount` GraphQL command to match its description

- genesis_ledgers/devnet.json
- genesis_ledgers/mainnet.json
This PR adds the relevant fields to the config files to set the response of the `networkID` GraphQL endpoint.
Tested by running the mainnet and devnet 3.0.0 containers, and comparing the responses to those from this branch using the config files.
> [release/3.0.1] Add network_id to the devnet and mainnet config files

- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
Fix the log by removing the now-removed `branch` metadata item.
Tested by launching the Mina node.
Checklist:
> Fix 'Mina daemon is booting up' log

- .gitignore
- Makefile
- dune
- scripts/update-opam-switch.sh
**Problem:** when different branches contain different opam.export files, managing corresponding switches when jumping between branches becomes burdensome.
**Solution:** use local switch functionality of opam to maintain _opam as a symlink to a switch that exactly matches opam.export. Update it autmatically when running `make build` and other commands.
**Explain how you tested your changes:**
1. Took a fresh Ubuntu (where mina wasn't ever built before)
2. Executed `apt install opam libgmp-dev liblmdb-dev libpq-dev pkg-config liblmdb0 liblmdb-dev libssl-dev libffi-dev` from root user
3. Checked out mina repository at branch `georgeee/makefile-opam-switch`, synchronized submodules
4. `opam init --bare`
5. `make ocaml_checks` (takes a while to build the switch)
6. `git apply test.patch`
7. …
> Maintain concurrent switches locally

- src/lib/merkle_ledger/any_ledger.ml
- src/lib/merkle_ledger/intf.ml
- src/lib/merkle_ledger/null_ledger.ml
- src/lib/merkle_ledger/util.ml
- src/lib/merkle_ledger/util.mli
- src/lib/merkle_mask/maskable_merkle_tree.ml
- src/lib/merkle_mask/masking_merkle_tree.ml
Problem: recomputation of hashes is costly and is absolutely nonsensical when we commit child ledger to parent.
Solution: provide hashes map from child to parent to be used in operation of hash recomputation for the accounts being added.
This change improved performance of transaction application for 9-account-update transactions by ~20% (as measured by #14582).
* Measured performance with #14582
Checklist:
> Do not recompute hashes on ledger commit

- src/lib/merkle_ledger_tests/test_mask.ml
- src/lib/merkle_mask/masking_merkle_tree.ml
Problem: account preloading is not able to preserve information about some accounts not existing in ledger, which invites future repetitive lookups to DB during staged ledger application.
Solution: keep a set of non-existent accounts for masks populated on preload.
Impact: after preload underlying ledger is guaranteed not to be queried.
Checklist:
> Handle non-existent accounts in preload

- nix/ocaml.nix
Small fix to nix wrapping (affects executables built with `nix build mina`/`nix build mina#devnet`/`nix build mina#mainnet`)
> Fix MINA_LIBP2P_HELPER_PATH in nix

- src/lib/mina_base/account_update.ml
This PR makes the types between account updates and zkApp accounts more consistent, in preparation for the work to move `bin_prot` into the `Mina_wire_types` layer.
This also gives us the option to make `Zkapp_uri` opaque/private in future if needed. This is a no-op.
> [Trivial] Re-use `Zkapp_account.Zkapp_uri` in `Account_update` for consistency

- buildkite/scripts/check-compatibility.sh
This PR removes the use of the `--no-merges` flag for the compatibility test, since it's essentially never what we want.
> Remove mistaken use of `--no-merges` in compatibility test

- docs/README.md
- flake.lock
- flake.nix
- frontend/ci-build-me/src/index.js
- nix/README.md
- nix/ocaml.nix
- src/lib/crypto_params/gen/dune
- src/lib/dummy_values/gen_values/dune
_This PR is ought to be rebased after the following PRs are merged: #15510_ 
This PR updates `flake.nix`, `nix/ocaml.nix` to integrate [o1-labs/dune-nix](https://github.com/o1-labs/dune-nix) library into the repository.
This adds a family of derivations that allow:
1. Building any Mina library/executable in isolation from rest of the code
2. Running unit tests
3. Extract useful information about internal dependencies of Mina's Ocaml packages
Crucially, it allows Mina to be built package-by-package, caching build/test results for code that didn't change. This brings CI run (similar to `buildkite/scripts/unit-test.sh`) to be shortened from ~40 minutes to something between 2 minutes and 17 minutes (depending on how deep the changes are).
Dune files are analyzed by the …
> Granular nix

- src/lib/logger/fake/logger.ml
- src/lib/logger/logger.mli
- src/lib/logger/native/logger.ml
- src/lib/prover/prover.ml
- src/lib/uptime_service/uptime_snark_worker.ml
- src/lib/verifier/prod.ml
- src/lib/vrf_evaluator/vrf_evaluator.ml
These seem to have been introduced for serialization of logger for RPC parallel, however versionining is not needed in that context.
Checklist:
> Remove %%versioned from Logger.t

- Makefile
Remove duplicate `replayer` rule.
Same rule is written twice in `Makefile` which obviously makes no sense.
Likely it was introduced over another merge.
Checklist:
> [Easy] Remove duplicate `replayer` rule from `Makefile`

- buildkite/scripts/generate-genesis-config.sh
- scripts/hardfork/create_runtime_config.sh
* [Fix genesis config creation for berkeley-to-berkeley HF](https://github.com/MinaProtocol/mina/commit/f49d0c2949b1a307c23a71285ede9b0b55fc6c00)
* [Use local script in generate-genesis-config.sh](https://github.com/MinaProtocol/mina/commit/7cfb6388d0fb38d7ac7cb406c6685c8aee37aa0c)
* Successul emergency HF dry-run with these changes
Checklist:
> Fix emergency hf pipeline

- src/lib/transition_frontier/frontier_base/diff.ml
- src/lib/transition_frontier/frontier_base/diff.mli
- src/lib/transition_frontier/frontier_base/root_data.ml
- src/lib/transition_frontier/frontier_base/root_data.mli
This PR removes some dead code depending on `bin_io` from the `Transition_frontier` libraries.
> Remove some unused `bin_io` derivations from `Transition_frontier`

- src/app/cli/src/init/client.ml
- src/lib/cli_lib/commands.ml
- src/lib/cli_lib/dune
To test cluster on large ledgers it's useful to have a tool to randomly generate ledger accounts for testing.
Usage: `mina ledger test-generate-accounts -n 200000 > ledger.json` to generate 200'000 accounts.
Bonus: to wire the accounts generated to file `ledger.json` into a `daemon.stub.json` stub, use the following command (also sets genesis timestamp to a new value):
```bash
jq --arg timestamp $( d=$(date +%s); date -u -d @$((d - d % 180 + 180)) +%FT%H:%M:%S+00:00 ) --slurpfile accounts ledger.json '.ledger.accounts |= . + $accounts[0] | .genesis.genesis_state_timestamp |= $timestamp'  < daemon.stub.json > daemon.json
```
Unlike `scripts/prepare-test-ledger.sh`, this tool generates ledger using uniform distribution of account balances, doesn't try to follow the shape of mainnet ledger. …
> Add tool to generate ledger accounts for testing

- src/lib/crypto/kimchi_bindings/stubs/Cargo.lock
- src/lib/crypto/kimchi_bindings/stubs/Cargo.toml
- src/lib/crypto/kimchi_bindings/stubs/src/arkworks/bigint_256.rs
- src/lib/crypto/kimchi_bindings/stubs/src/arkworks/group_affine.rs
- src/lib/crypto/kimchi_bindings/stubs/src/arkworks/pasta_fp.rs
- src/lib/crypto/kimchi_bindings/stubs/src/arkworks/pasta_fq.rs
- src/lib/crypto/kimchi_bindings/stubs/src/lagrange_basis.rs
- src/lib/crypto/kimchi_bindings/stubs/src/linearization.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_proof.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_verifier_index.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_proof.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_verifier_index.rs
- src/lib/crypto/kimchi_bindings/stubs/src/plonk_verifier_index.rs
- src/lib/crypto/kimchi_bindings/stubs/src/projective.rs
- src/lib/crypto/kimchi_bindings/stubs/src/srs.rs
- src/lib/crypto/kimchi_bindings/stubs/src/urs_utils.rs
- src/lib/crypto/kimchi_bindings/wasm/Cargo.lock
- src/lib/crypto/kimchi_bindings/wasm/Cargo.toml
- src/lib/crypto/kimchi_bindings/wasm/src/arkworks/bigint_256.rs
- src/lib/crypto/kimchi_bindings/wasm/src/arkworks/group_affine.rs
- src/lib/crypto/kimchi_bindings/wasm/src/arkworks/pasta_fp.rs
- src/lib/crypto/kimchi_bindings/wasm/src/arkworks/pasta_fq.rs
- src/lib/crypto/kimchi_bindings/wasm/src/plonk_proof.rs
- src/lib/crypto/kimchi_bindings/wasm/src/plonk_verifier_index.rs
- src/lib/crypto/kimchi_bindings/wasm/src/projective.rs
- src/lib/crypto/kimchi_bindings/wasm/src/rayon.rs
- src/lib/crypto/kimchi_bindings/wasm/src/srs.rs
- src/lib/crypto/kimchi_bindings/wasm/src/urs_utils.rs
- src/lib/pickles/wrap_verifier.ml
* Proof-systems: https://github.com/o1-labs/proof-systems/pull/2474
* Kimchi-stubs vendors: https://github.com/MinaProtocol/kimchi-stubs-vendors/pull/1
> Update arkworks to 0.4.2 (compatible)

- buildkite/scripts/build-release.sh
- buildkite/scripts/export-git-env-vars.sh
- scripts/debian/build.sh
- scripts/export-git-env-vars.sh
In some cases when building debian packages on buildkite agent below command return HEAD instead of actual branch name (like develop etc):
```
export GITBRANCH=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD |  sed 's!/!-!g; s!_!-!g; s!#!-!g' )
```
It is still under investigation why since at first look it depends on agent state (we couldn't reproduce it locally nor on agent after failure detection)
Another observation is that it could be unstable almost from long time ago, since in buildkite/scripts/export-git-env-vars.sh file we set GITBRANCH to be equal to BUILDKITE_BRANCH (if exists) after we calculate GITBRANCH.
> Pass BUILDKITE_BRANCH env variable to ensure correct debian version

- src/lib/mina_compile_config/dune
Very simple change to fix nix CI (`!ci-nix-me`).
Checklist:
> Use public name of mina_node_config.for_unit_tests

- scripts/debian/build.sh
Another slight adjustment for HEAD issue which is hard to track but easy to patch post mortem
> pass BRANCH_NAME to export-git-env-vars script properly

- src/lib/crypto/kimchi_backend/pasta/basic/kimchi_pasta_basic.ml
- src/lib/mina_wire_types/dune
- src/lib/mina_wire_types/mina_base/mina_base_zkapp_state.ml
- src/lib/mina_wire_types/pickles/pickles.ml
- src/lib/mina_wire_types/pickles/pickles.mli
- src/lib/mina_wire_types/pickles/pickles_composition_types.ml
- src/lib/mina_wire_types/pickles/pickles_composition_types.mli
- src/lib/mina_wire_types/pickles/pickles_limb_vector.ml
- src/lib/mina_wire_types/pickles/pickles_reduced_messages_for_next_proof_over_same_field.ml
- src/lib/mina_wire_types/pickles_base.ml
- src/lib/mina_wire_types/pickles_types.ml
- src/lib/mina_wire_types/snark_params.ml
- src/lib/pickles_types/dune
- src/lib/pickles_types/nat.ml
- src/lib/pickles_types/nat.mli
- src/lib/pickles_types/plonk_types.ml
- src/lib/pickles_types/plonk_types.mli
- src/lib/pickles_types/plonk_verification_key_evals.ml
- src/lib/pickles_types/plonk_verification_key_evals.mli
- src/lib/pickles_types/shifted_value.ml
- src/lib/pickles_types/shifted_value.mli
- src/lib/pickles_types/vector.ml
- src/lib/pickles_types/vector.mli
This PR moves the `Pickles_types` type definitions into the `Mina_wire_types` library.
This unblocks a dependency cycle, which in turn allows us to use concrete instances for `Typ.t`s etc. when we're communicating across the FFI boundary with rust.
> Push `Pickles_types` down into `Mina_wire_types`

- scripts/docker/helper.sh
- src/app/archive/lib/processor.ml
During stable run we experienced issue in archive node during some integration tests run:
```
2024-09-18 20:48:55 UTC [Info] Starting archive process; built with commit "b40ca1562f2f448ae20ecdb299c8b9da14090c28"
2024-09-18 20:48:55 UTC [Info] Initializing with runtime configuration. Ledger name: null
2024-09-18 20:48:55 UTC [Info] Using the constraint constants from the configuration file
2024-09-18 20:48:55 UTC [Fatal] Proof level "full" is not 
compatible with compile-time proof level "none"
(monitor.ml.Error
(Failure
"Could not get precomputed values, error: Proof level full is not compatible with compile-time proof level none")
("Raised at Stdlib.failwith in file \"stdlib.ml\", line 29, characters 17-33"
"Called from Async_kernel__Deferred1.M.map.(fun) in file \"src/deferred1.ml\", …
```
> Port lightnet suffix fix to release 3.0.2

- src/lib/crypto/kimchi_bindings/stubs/Cargo.lock
- src/lib/crypto/kimchi_bindings/stubs/Cargo.toml
- src/lib/crypto/kimchi_bindings/wasm/Cargo.lock
- src/lib/crypto/kimchi_bindings/wasm/Cargo.toml
* Unified packages/version lower bounds with `proof-systems`
* As a result, `Cargo.toml` uses more same-version dependencies. `serde_with` is now `3.6.0` (which it was in `proof-systems`) only, and `2.3.3` is not used anymore. Same or `serde_with_macros`. `rmp-serde` is `1.1.2` now, and the `0.15.5` version is not used anymore.
* Added `asm` flag to `ark-ff`
See:
- https://github.com/o1-labs/proof-systems/pull/2574
- https://github.com/MinaProtocol/kimchi-stubs-vendors/pull/3
> Unify versions between bindings and proof-systems + add asm flags

- buildkite/scripts/check-compatibility.sh
This PR fixes the 'compatiblity test' so that it doesn't hang in an infinite loop if starting the container fails.
See e.g. [this hung test](https://buildkite.com/o-1-labs-2/mina-o-1-labs/builds/35269#01920a82-e1d3-46b3-ac23-e7136824ee86).
> Fail the compatibility test if the docker execution fails

- buildkite/scripts/build-release.sh
- buildkite/scripts/export-git-env-vars.sh
- scripts/debian/build.sh
- scripts/export-git-env-vars.sh
Use BUILDKITE_BRANCH when calculating debian name as git rev-name can return random tag/branch
> Port BRANCH_NAME fix from compatible

- src/lib/crypto/kimchi_bindings/stubs/kimchi_bindings.ml
- src/lib/pickles/compile.ml
- src/lib/pickles/pickles.ml
- src/lib/pickles/plonk_checks/plonk_checks.ml
- src/lib/pickles/plonk_checks/plonk_checks.mli
- src/lib/pickles/proof.ml
- src/lib/pickles/side_loaded_verification_key.ml
- src/lib/pickles/step.ml
- src/lib/pickles/step_branch_data.ml
- src/lib/pickles/step_main.ml
- src/lib/pickles/unfinalized.ml
- src/lib/pickles/verification_key.ml
- src/lib/pickles/verify.ml
- src/lib/pickles/wrap_domains.ml
- src/lib/pickles/wrap_proof.ml
- src/lib/pickles/wrap_verifier.ml
This is part of the investigation of the chunking bug in Pickles and o1js (RFCs [here](https://github.com/o1-labs/rfcs/blob/main/0002-chunking.md) and [here](https://github.com/o1-labs/rfcs/pull/45/)).
Partially addresses https://github.com/o1-labs/o1js/issues/1806
* Substitute hardcoded values of `3` for `zk_rows` for a variables called `zk_rows_by_default`, and likewise for `1` and `num_chunks`. 
* This is to facilitate debugging and reduce error proneness. 
* It only contains cosmetic changes.
* There must still be a few places in our codebase, because the chunking tests in `o1js` still read `3` always. 
Checklist:
- …
> Remove hardcoded values for `zk_rows` and `num_chunks` in Pickles code

- src/app/reformat/reformat.ml
* opam-switches has been added to handle different switches. It is created by the Makefile. However, `make reformat` will try to reformat the files in the directory.
* N/A
cc @querolita who was stuck because of this.
Checklist:
* Closes #0000
> reformat: ignore opam-switches

- src/lib/mina_wire_types/pickles_types.ml
- src/lib/pickles_types/plonk_types.ml
- src/lib/pickles_types/plonk_types.mli
This PR expands the number of serialised types tracked in `Mina_wire_types` to cover proofs from `Pickles_types`.
> Add more of `Pickles_types` to `Mina_wire_types`

- src/app/reformat/reformat.ml
Counterpart of https://github.com/MinaProtocol/mina/pull/16115/. It will be to build the develop version of https://github.com/MinaProtocol/mina/pull/16117
*
*
Checklist:
* Closes #0000
> reformat: ignore opam-switches [develop]

- buildkite/src/Command/Libp2pHelperBuild.dhall
- buildkite/src/Jobs/Lint/Dhall.dhall
This PR builds on https://github.com/MinaProtocol/mina/pull/16132. This enables the `generic-multi` agents for dhall lint and libp2p_helper build jobs in CI.
> [master] Use generic-multi CI for dhall lint and libp2p_helper build

- src/app/reformat/reformat.ml
Reapply https://github.com/MinaProtocol/mina/pull/16115/
*
*
Checklist:
* Closes #0000
> [compatible] reformat: ignore opam-switches - reapply 16115

- scripts/debian/aptly.sh
- scripts/debian/build.sh
- scripts/debian/builder-helpers.sh
- scripts/debian/publish.sh
- scripts/debian/reversion.sh
- scripts/debian/verify.sh
I use [shellcheck](https://www.shellcheck.net/) on my machine and my code editor warns me when `shellcheck` encounters an error/warning.
I would like to suggest to add shellcheck later in the CI.
Check the commit message for the errors we are still getting.
* I mostly run shellcheck on the files, and fix the error messages. I didn't do on all of them, only a few I explored.
[compatible version](https://github.com/MinaProtocol/mina/pull/16119)
Checklist:
* Closes #0000
> [easy/develop] Make shellcheck happier on scripts/debian/*.sh

- src/lib/mina_net2/validation_callback.ml
This PR fixes the behaviour of `Mina_net2.Validation_callback.fire_if_not_already_fired`, making it match its name.
This bug was re-introduced [here](https://github.com/MinaProtocol/mina/pull/7483) after originally appearing as [a typo](https://github.com/MinaProtocol/mina/pull/6924/files#diff-2844302d4a5657da64729bc73c995310d1bdc1159acdbb6e6b9e38a30aa37719R60) in PR #6924.
We've seen this bug crash a node on devnet recently (Ivar log message [here](https://console.cloud.google.com/logs/query;aroundTime=2024-09-26T14:15:20.272Z;cursorTimestamp=2024-09-26T14:28:18.513122331Z;duration=PT1H;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22o1labs-192920%22%0Aresource.labels.location%3D%22us-central1-a%22%0Aresource.labels.cluster_name%3D%22mina-devnet-infra-2%22%0Are …
>  Change semantics of `fire_if_not_already_fired` to match its name

- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_proof.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_proof.rs
- src/lib/crypto/kimchi_bindings/wasm/src/plonk_proof.rs
https://github.com/o1-labs/proof-systems/pull/2598 introduces serialization tests into `proof-systems`. For that it was necessary to make kimchi prover take `rng` explicitly (Instead of taking `&mut rand::rngs::OsRng` internally), this is merely a semantic change.
This PR propagates this semantics to `mina` and updates to the new version of proof-systems.
> Update proof-systems: external prover randomness & regression tests

- src/lib/bootstrap_controller/bootstrap_controller.ml
- src/lib/bootstrap_controller/bootstrap_controller.mli
- src/lib/bootstrap_controller/transition_cache.ml
- src/lib/bootstrap_controller/transition_cache.mli
- src/lib/mina_block/header.ml
- src/lib/mina_block/header_intf.ml
- src/lib/mina_block/mina_block.ml
- src/lib/mina_block/validation.ml
- src/lib/mina_block/validation.mli
- src/lib/mina_block/validation_types.ml
- src/lib/transition_frontier_controller/dune
- src/lib/transition_frontier_controller/transition_frontier_controller.ml
- src/lib/transition_router/transition_router.ml
This PR rebases the following commit of [this PR](https://github.com/MinaProtocol/mina/pull/12534) :
[Refactor Transition_router](https://github.com/MinaProtocol/mina/pull/12534/commits/fbc8bf0ff093b07283d08ab64ddba0598d0b394d)
1. Simplify transition_router: remove unnecessary reader refs
2. Do not ignore validation_callbacks for transition gossips received
during bootstrap
3. Add support for header gossip collection during boostrap
> Refactor transition router

- src/app/archive/lib/test.ml
- src/lib/blockchain_snark/blockchain_snark_state.ml
- src/lib/genesis_constants/genesis_constants.ml
- src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
- src/lib/genesis_ledger_helper/lib/genesis_ledger_helper_lib.ml
- src/lib/mina_lib/tests/tests.ml
- src/lib/prover/prover.ml
- src/lib/runtime_config/runtime_config.ml
- src/lib/snark_worker/debug.ml
- src/lib/snark_worker/prod.ml
- src/lib/snark_worker/standalone/run_snark_worker.ml
- src/lib/verifier/dummy.ml
- src/lib/verifier/prod.ml
Using widely used `None `for name of constructor lead to an issue when `~proof_level` parameter changed its type and compiler left it unnoticed.
* Code compiles
Resurrection of #16105
Checklist:
> Rename constructor Proof_level.{None -> No_check}

- scripts/snark_transaction_profiler.py
- src/lib/snark_profiler_lib/snark_profiler_lib.ml
- src/lib/transaction_snark/test/util.ml
Applied fix from https://github.com/MinaProtocol/mina/pull/16170 + fixed snark profiler test to detect any errors occurence in log and fail the build. This change goes with porting to master as all CI fixes should be applied to master as well
> Fail the build on error match in output

- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
- src/lib/integration_test_cloud_engine/mina_automation.ml
- src/lib/integration_test_local_engine/mina_docker.ml
- src/lib/runtime_config/dune
- src/lib/runtime_config/runtime_config.ml
We allow certain values to be picked up during `mina` daemon  configuration loading that are not explicitly part of the runtime config type.  This means that `Runtime_config.t` is not the proper type to describe the values that are allowed. 
- Add all the config fields that are implicitly allowed
- Modify the functions `maybe_from_config` and `or_from_config` in `Mina_cli_entrypoint` to make use of the proper types.
- Remove the unused `Quickcheck` generator instances in `Runtime_config` (rather than extending these for the new fields, we should just delete them since no one will miss them)
> Explicitly declare missing daemon runtime configuration

- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
- src/app/cli/src/init/client.ml
- src/app/delegation_verify/delegation_verify.ml
- src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml
- src/app/zkapp_test_transaction/lib/commands.ml
- src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
- src/lib/runtime_config/dune
- src/lib/runtime_config/runtime_config.ml
This PR stacks on #16163
There should only be one way to load json files to construct a value of type `Runtime_config.t`, we have several:
- `Mina_cli_entrypoint` checks system directories for an installed config file, other places do not
- `Mina_cli_entrypoint` logs verbosely where it finds certain values that belong the `daemon` object. This requires special handling to load these values only to gain a `debug` log -- we don't do this for any other fields or in any other CLI context, and would require more complicated handling. The fact that the `~keyname` arguments for the logger are not derived from the value means they can drift.
- `Mina_cli_entrypoint` will also attempt to _write_ configuration as it is reading it. This addition was made something like 4 years ago. Rather than …
> unify json config loading

- src/lib/pickles/test/main.ml
- src/lib/pickles/test/test_ro.ml
- src/lib/pickles/tests/dune
For some reasons there were two directories for
the pickles test and tests. We remove tests and move it's unique file.
Note that we also need to modify a bit the tests, because we use base instead of the standard lib
> Pickles/test : moved content from tests to test

- buildkite/src/Command/MinaArtifact.dhall
- buildkite/src/Jobs/Test/RosettaIntegrationTests.dhall
- buildkite/src/Jobs/Test/RosettaIntegrationTestsLong.dhall
- scripts/debian/build.sh
Builds two versions of rosetta docker for mainnet and devnet networks (previously was build only for berkeley network)
> Build rosetta mainnet/devnet docker

- src/lib/best_tip_prover/best_tip_prover.ml
- src/lib/block_producer/block_producer.ml
- src/lib/bootstrap_controller/bootstrap_controller.ml
- src/lib/bootstrap_controller/bootstrap_controller.mli
- src/lib/gossip_net/fake.ml
- src/lib/gossip_net/intf.ml
- src/lib/gossip_net/libp2p.ml
- src/lib/gossip_net/message.ml
- src/lib/ledger_catchup/normal_catchup.ml
- src/lib/ledger_catchup/super_catchup.ml
- src/lib/mina_block/mina_block.ml
- src/lib/mina_block/validation.ml
- src/lib/mina_block/validation.mli
- src/lib/mina_block/validation_types.ml
- src/lib/mina_commands/mina_commands.ml
- src/lib/mina_intf/transition_frontier_components_intf.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_lib/mina_lib.mli
- src/lib/mina_lib/tests/tests.ml
- src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
- src/lib/transition_frontier_controller/dune
- src/lib/transition_frontier_controller/transition_frontier_controller.ml
- src/lib/transition_handler/block_sink.ml
- src/lib/transition_handler/block_sink.mli
- src/lib/transition_handler/catchup_scheduler.ml
- src/lib/transition_handler/processor.ml
- src/lib/transition_handler/validator.ml
- src/lib/transition_router/initial_validator.ml
- src/lib/transition_router/transition_router.ml
This PR rebases the following commit of https://github.com/MinaProtocol/mina/pull/12534 :
[Use headers for v1 pubsub block topic](https://github.com/MinaProtocol/mina/pull/12534/commits/c9416b3dc82999047d081718e6d57d4c47a4cc01)
Receive headers on a new pubsub topic and propagate them all the way
through to catchup, as alternative to block.
Existing synchronization code relies heavily on full blocks becoming
available, hence a hack was made: when a valid and relevant header
enters catchup system, download of a block will be requested and only
when the full block is available, processing will continue.
---
I did my best to split in several commits but I didn't manage to make them all compile.
> Use headers for v1 pubsub block topic

- buildkite/scripts/rosetta-integration-tests.sh
This PR increases the relative proportion of stake that the block producer has in the rosetta integration tests. This should speed up progress of the test, similar in principle to #14376.
> Rosetta integration test: make block producer produce more blocks

- src/app/test_executive/zkapps.ml
This wait is the likely cause of flakiness with the message
```
ZkApp transaction failed: "Couldn't send zkApp commands: [\"Invalid_nonce\"] (in [\"internalSendZkapp\"])", but expected "Insufficient_replace_fee"
```
In particular, this delay plus an additional delay from block production, validation, and propagation, means that the transaction to be 'replaced' may have already been included in a block.
> Remove the arbitrary 30s wait in the zkapps integration test

- automation/services/mina-bp-stats/sidecar/build.sh
- scripts/publish-deb.sh
Debian Buster is EOL. We are using apt-get update when verifying pushed packages to debian repo. We are relying purely on deb-s3 in order to verify package is located in out repo so we can remove apt-get call from process. 
For mina-side car issue, looks like there is a name mismatch between package name in control file with debian package name. Adjusting package name in control file will solve the issue
> Fix Debian Buster EOL issue when publishing debian

- src/app/libp2p_helper/src/libp2p_helper/bitswap.go
- src/app/libp2p_helper/src/libp2p_helper/bitswap_delete.go
- src/app/libp2p_helper/src/libp2p_helper/bitswap_downloader.go
- src/app/libp2p_helper/src/libp2p_helper/bitswap_downloader_test.go
- src/app/libp2p_helper/src/libp2p_helper/bitswap_msg.go
- src/app/libp2p_helper/src/libp2p_helper/bitswap_test.go
- src/app/libp2p_helper/src/libp2p_helper/error.go
- src/app/libp2p_helper/src/libp2p_helper/incoming_msg.go
- src/app/libp2p_helper/src/libp2p_helper/msg.go
- src/lib/mina_net2/libp2p_helper.ml
- src/libp2p_ipc/libp2p_ipc.capnp
- src/libp2p_ipc/libp2p_ipc.ml
- src/libp2p_ipc/libp2p_ipc.mli
This PR renames a number of methods with names `deleteXX` to `removeXX`.
It also adds a functions `create_download_resource_push_message` and `create_remove_resource_push_message` that will later be used for organization of IPC between Ocaml's bit-catchup algrotihm code and Libp2p's functions exposing Biytswap functionality.
> Bitswap: rename `deleteXX` to `removeXX`, add tag to IPC

- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
- src/app/cli/src/init/client.ml
- src/lib/gossip_net/libp2p.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_lib/tests/tests.ml
- src/lib/mina_net2/mina_net2.ml
- src/lib/mina_net2/mina_net2.mli
- src/lib/mina_net2/subscription.ml
- src/lib/mina_net2/subscription.mli
- src/lib/mina_net2/tests/all_ipc.ml
- src/lib/mina_net2/tests/tests.ml
- src/lib/mina_net2/validation_callback.ml
- src/lib/mina_net2/validation_callback.mli
- src/lib/network_pool/network_pool_base.ml
- src/lib/network_pool/pool_sink.ml
- src/lib/transition_handler/block_sink.ml
- src/lib/transition_handler/block_sink.mli
- src/lib/transition_handler/catchup_scheduler.ml
- src/lib/transition_handler/processor.ml
_part 2 of #16173_ 
Argument `block_window_duration` was unnecessarily introduced in one of recent refactorings, by accident.
This PR essentially removes `~block_window_duration:_ (*TODO remove*)` in `validation_callback.ml` and propagates the change up the function calls.
> Remove unused block window duration arguments

- src/app/libp2p_helper/src/libp2p_helper/bitswap_test.go
Existing test is really long to execute. On some machines it exceeds the limit of 60 minutes.
With the reduced number of repetitions, testing is still performed, but it's ensured that libp2p unit tests take less than 30m even on slower machines.
In future we may look deeper in the test and instead of making lesser amount of repetitions either optimize the software or restructure the test.
Tests concerns only bitswap, i.e. functionality that is not activated in mainnet's Mina build.
Checklist:
> Reduce repetitions in TestBitswapSmall

- src/lib/blockchain_snark/blockchain_snark_state.ml
- src/lib/blockchain_snark/blockchain_snark_state.mli
- src/lib/mina_state/snarked_ledger_state.ml
- src/lib/mina_state/snarked_ledger_state_intf.ml
- src/lib/transaction_snark/transaction_snark.ml
- src/lib/transaction_snark/transaction_snark_intf.ml
Removes some code which was unused:
* Function `Transaction_state.verify`
* Function `Blockchain_state.verify`
* Function `to_input` and module `Checked` from  `Snarked_ledger_state.Statement.With_sok`
Code was written but never used. More importantly, implementation of `Snarked_ledger_state.Statement.With_sok.to_input` (and transitively `Transaction_state.verify`) didn't agree with `verify` function exposed by `Proof` module (which used `to_field_elements` derived from `typ` instead of `to_input`).
PR removes a function that was unused before #16201, where it was used and the new code become unexpectedly incorrect.
Checklist:
- Document test …
> Remove some unused code in snark-related modules

- src/lib/crypto/kimchi_backend/pasta/pallas_based_plonk.ml
- src/lib/crypto/kimchi_backend/pasta/vesta_based_plonk.ml
- src/lib/crypto/kimchi_bindings/stubs/kimchi_bindings.ml
- src/lib/crypto/kimchi_bindings/stubs/src/lagrange_basis.rs
- src/lib/crypto/kimchi_bindings/stubs/src/main.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_index.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_proof.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_verifier_index.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_index.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_proof.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_verifier_index.rs
- src/lib/crypto/kimchi_bindings/stubs/src/srs.rs
1. This creates a binding function `_lagrange_commitments_whole_domain` that is to be used instead of calling `_lagrange_commitment` (that retrieves a single base) `domain_size` times. 
* The optimisation saves up about 100ms on every prove call on my local machine if I remember correctly, or less -- in the end it cuts about 0.5m or 6% time on the cluster:
* Benchmark improvement (on a fast-ish cluster) for `_build/default/src/app/cli/src/mina.exe transaction-snark-profiler --zkapps --k 1 --max-num-updates 4 --min-num-updates 2`:
```
- NEW
- 6.231m
- 6.378m
- 6.381m
- OLD:
- 6.843m
- 6.753m
- 6.743m
```
2. Additionally I removed some `unsafe`s that are not anymore necessary since SRS is now wrapped in a `Mutex` (which should be `RWLock` really).
~Caveat: this change plus some amount of …
> Improve lagrange retrieval performance & remove unsafes

- buildkite/scripts/fuzzy-zkapp-test.sh
- buildkite/scripts/unit-test.sh
This PR removes the explicit parallelism argument passed to dune in CI. Allowing dune to automatically detect how many cores are available is likely to have better performance.
> [master] Remove hard-coded assumption that test runners have 16 cores

- src/lib/network_pool/batcher.ml
- src/lib/network_pool/batcher.mli
- src/lib/network_pool/snark_pool.ml
- src/lib/network_pool/test.ml
- src/lib/network_pool/transaction_pool.ml
- src/lib/signature_lib/schnorr.ml
This PR disables `Inline_test_quiet_logs` in the `Network_pool` tests, after making some tweaks to ensure that the tests don't have any auxiliary output.
Re-enabling the output also reveals the runtime of the unit tests, which was previously suppressed by the quiet logs. These tests include some long-running ones that were previously overlooked, for example `max size is maintained` in the `Transaction_pool` tests.
> Stop using `Inline_test_quiet_logs` for `Network_pool` tests

- src/lib/mina_graphql/mina_graphql.ml
Problem: value from compile time config was always used, although such a field existed in runtime config as well and was expected to be used.
Solution: use value from runtime config when present.
Checklist:
- Release 3.0.2 has `networkID` returning `mina:testnet` on a mainnet build
> Use network_id from runtime config in Graphql

- src/lib/mina_ledger/sparse_ledger.ml
- src/lib/snark_profiler_lib/snark_profiler_lib.ml
- src/lib/staged_ledger/pre_diff_info.ml
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/staged_ledger/staged_ledger.mli
- src/lib/transaction_logic/mina_transaction_logic.ml
- src/lib/transaction_logic/test/helpers.ml
- src/lib/transaction_logic/test/predicates.ml
- src/lib/transaction_logic/test/zkapp_logic.ml
- src/lib/transaction_snark/test/account_timing/account_timing.ml
- src/lib/transaction_snark/test/transaction_union/transaction_union.ml
- src/lib/transaction_snark/test/util.ml
- src/lib/transaction_snark/transaction_validator.ml
- src/lib/transaction_snark/transaction_validator.mli
- src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
- src/lib/transaction_snark_scan_state/transaction_snark_scan_state.mli
Transaction_applied is exposed in both the top-level module and a `Make` functor. It's cleaner to just expose it once.
Checklist:
> Do not over-expose Transaction_applied

- buildkite/Makefile
- buildkite/scripts/dhall/checker.py
- buildkite/src/Jobs/Lint/Dhall.dhall
Added two more dhall checks to buildkite/Makefile, which I found handy when making changes to dhall framework:
- make check_dups
Looks for duplicate names of any steps defined
- make check_names
Validates that all defined jobs respect naming constraints
Running above checks before pushing to CI helped me to find out issues without spamming (!ci-build-me) command too much
> new dhall jobs for detecting duplicated steps and invalid jobs names

- src/lib/mina_base/zkapp_account.ml
- src/lib/mina_base/zkapp_call_forest.ml
- src/lib/mina_ledger/ledger.ml
When no zkapp uri is specified, use a precomputed hash of a dummy stub.
Previous behavior involved hashing the dummy stub each time no zkapp uri was specified which is wasteful.
PR also removes some dead code, which just happened to be discovered dead during work on the PR.
* Saw improvement with `mina ledger test apply` benchmark
Checklist:
> Optimize the non-present zkapp uri hashing

- buildkite/scripts/promote-docker.sh
Fixes promotion job logic.
PUBLISH flag controls whether we push docker image to gcr or docker.io. We were testing existance of PUBLISH variable only, which looks like and issue as  if we don't want to publish to docker.io we set PUBLISH=0. However, code check only if variable is set not its value. Therefore we promote it to docker.io even if our target was gcr.io. This pr fixes is by comparing PUBLISH value
> Fix promotion job PUBLISH misuse

- buildkite/src/Command/PatchArchiveTest.dhall
- buildkite/src/Command/ReplayerTest.dhall
- buildkite/src/Constants/DebianVersions.dhall
- buildkite/src/Jobs/Test/ReplayerTest.dhall
Added sub steps for patch archive and replayer tests which sends coverage data to coveralls
> add coverage gather for archive related tests

- src/config/dev.mlh
- src/config/devnet.mlh
- src/config/lightnet.mlh
- src/config/mainnet.mlh
- src/lib/mina_compile_config/mina_compile_config.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_lib/tests/tests.ml
- src/lib/network_pool/snark_pool.ml
- src/lib/network_pool/test.ml
- src/lib/network_pool/transaction_pool.ml
- src/lib/node_config/for_unit_tests/node_config_for_unit_tests.ml
- src/lib/node_config/intf/node_config_intf.mli
- src/lib/node_config/node_config.ml
- src/lib/runtime_config/runtime_config.ml
- src/lib/transaction_inclusion_status/transaction_inclusion_status.ml
- src/lib/transition_handler/processor.ml
- The field `curve_size` isn't being used anywhere in the codebase, so remove the field and definitions in `mlh` files
- Fixes #16108
> Remove redundant fields from compile config type

- src/lib/mina_base/zkapp_command.ml
- src/lib/mina_generators/zkapp_command_generators.ml
- src/lib/mina_generators/zkapp_command_generators.mli
- src/lib/network_pool/transaction_pool.ml
**Problem**: previous generator was modifying zkapp commands after computing call forest hashes, which essentially rendered transactions incorrect, though didn't fail the test immediately.
**Solution**: rearrange modifications so that call forest hashes are computed after modifications to account updates take place.
While the issue didn't cause any test to fail, after some unrelated change some tests of transaction_pool started failing. Another branch will also contain a "regression" unit tests that fails before the fix and succeeds after. That regression tests will essentially recompute call forest hashes and compare them to original hashes.
Checklist:
- Mention expected invariants, implicit …
> Fix generator for transaction_pool tests

- scripts/debian/builder-helpers.sh
PR https://github.com/MinaProtocol/mina/pull/15899 added an out-of-sync, broken copy of `buildkite/scripts/export-git-env-vars.sh` at `scripts/export-git-env-vars.sh` that we use for debian builds. As a result, all of the debian descriptions have stopped containing the host URL, instead now taking the form
```
Built from 012abcf by local build from '0123456789ab' host
```
This PR uses `BUILDKITE_BUILD_URL` as the primary fallback for `BUILD_URL`, to mitigate the harm caused by this error while it's being fixed.
> Default to `BUILDKITE_BUILD_URL` for package info when available

- src/lib/pickles/composition_types/composition_types.ml
- src/lib/pickles/composition_types/spec.ml
- src/lib/pickles/composition_types/spec.mli
- src/lib/pickles/impls.ml
This PR converts the generalized helpers in `Pickles.Composition_types.Spec` to functors, instantiating them by default with the step and wrap snarky instances for pickles.
This allows for more straightfoward manipulation of the `Typ.t`s for each instance, which in turn allows for integration with the rust snarky backend.
> Rework `Pickles.Composition_types.Spec` to handle distinct snarky instances

- src/lib/crypto/kimchi_backend/common/kimchi_backend_common.mli
- src/lib/crypto/kimchi_backend/common/scalar_challenge.ml
- src/lib/crypto/kimchi_backend/common/scalar_challenge.mli
- src/lib/pickles/composition_types/bulletproof_challenge.ml
- src/lib/pickles/composition_types/bulletproof_challenge.mli
- src/lib/pickles/composition_types/spec.ml
- src/lib/pickles/scalar_challenge.ml
This PR builds upon #16353, allowing us to extend the efforts from PR #16352 for the `Bulletproof_challenge.typ`.
> Specialize more `Typ.t`s in `Pickles.Composition_types`

- src/lib/pickles/composition_types/composition_types.ml
- src/lib/pickles/composition_types/composition_types.mli
- src/lib/pickles/composition_types/spec.ml
- src/lib/pickles/composition_types/spec.mli
- src/lib/pickles/per_proof_witness.ml
- src/lib/pickles/step_main.ml
- src/lib/pickles/test/test_wrap.ml
- src/lib/pickles/wrap_main.ml
- src/lib/pickles/wrap_proof.ml
- src/lib/pickles/wrap_verifier.mli
- src/lib/pickles_types/dune
- src/lib/pickles_types/hlist.ml
- src/lib/pickles_types/hlist.mli
- src/lib/pickles_types/opt.ml
- src/lib/pickles_types/opt.mli
- src/lib/pickles_types/plonk_types.ml
- src/lib/pickles_types/plonk_types.mli
- src/lib/pickles_types/plonk_verification_key_evals.ml
- src/lib/pickles_types/plonk_verification_key_evals.mli
This PR specializes many of the `Typ.t`s from `Pickles_types`. This builds upon #16354, moving closer towards the goal of entirely separated instances of `Typ.t` for the different snarky instances (specifically those for step and wrap in pickles).
> Specialize `Typ.t`s in `Pickles_types`

- src/lib/pickles/composition_types/composition_types.ml
- src/lib/pickles/composition_types/spec.ml
- src/lib/pickles/test/test_wrap_hack.ml
- src/lib/pickles/wrap_main.ml
- src/lib/pickles_base/one_hot_vector/one_hot_vector.ml
- src/lib/pickles_base/proofs_verified.ml
- src/lib/pickles_types/plonk_types.ml
- src/lib/pickles_types/vector.ml
- src/lib/pickles_types/vector.mli
This PR builds upon https://github.com/MinaProtocol/mina/pull/16355, continuing its work by removing the dependency on `Snarky_backendless.Typ` from `Vector.typ` and its downstream `Typ.t`s.
> Use concrete snarky implementations for `Vector.typ` and friends

- src/lib/pickles/composition_types/branch_data.ml
- src/lib/pickles/composition_types/branch_data_intf.ml
- src/lib/pickles/composition_types/spec.ml
- src/lib/pickles/per_proof_witness.ml
- src/lib/pickles/side_loaded_verification_key.ml
- src/lib/pickles/test/test_wrap.ml
- src/lib/pickles_base/proofs_verified.ml
- src/lib/pickles_base/proofs_verified.mli
This PR builds upon https://github.com/MinaProtocol/mina/pull/16357, using the concretized versions of `Typ.t`s to give concrete types to `Pickles.Composition_types.Branch_data`, and remove their dependency on the generalized `Typ.t` from snarky.
> Specialize `Pickles.Composition_types.Branch_data`

- src/lib/mina_base/protocol_constants_checked.ml
- src/lib/mina_base/test/account_test.ml
- src/lib/pickles/impls.ml
- src/lib/pickles/intf.mli
- src/lib/pickles/step_verifier.mli
- src/lib/pickles/wrap_main.ml
- src/lib/pickles_types/shifted_value.ml
- src/lib/pickles_types/shifted_value.mli
- src/lib/transaction_snark/test/account_timing/account_timing.ml
This PR extends https://github.com/MinaProtocol/mina/pull/16359, removing all remaining references to `As_prover0` and `Snarky.Types.Typ` everywhere. This finally allows us to make these types opaque so that they can be forwarded from rust.
> [Trivial] Stop using `Snarky.As_prover0` and `Snarky.Types.Typ` everywhere

- src/app/rosetta/scripts/docker-start.sh
Porting fix only from PR: https://github.com/MinaProtocol/mina/pull/16346, while waiting for test stabilization
How i tested it:
```
docker run -d --env MINA_NETWORK=mainnet gcr.io/o1labs-192920/mina-rosetta:${ROSETTA_DOCKER_TAG}-mainnet
```
> [Rosetta] use mina missing block guardian script instead of download missing blocks

- src/lib/mina_commands/mina_commands.ml
We update to sync status 5 blocks before the best tip block number. In the spirit of getting rid of magic numbers, I've named it. I would also like to reference it in a later PR.
> naming sync lag variable

- src/lib/staged_ledger/staged_ledger.ml
- src/lib/staged_ledger/staged_ledger.mli
- src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
- src/lib/transaction_snark_scan_state/transaction_snark_scan_state.mli
This use of deriving is not used, so no point in having it.
Checklist:
> Do not derive sexp for the scan state

- scripts/snark_work_strategy.py
- src/lib/snark_worker/standalone/run_snark_worker.ml
This MR adds a script & change a bit some existant code in `run_snark_worker.ml`.
The script fetch a range of work (size of the range is given by user), spawn a process and runs `run_snark_worker.ml` (perform & submit work) for each fetched work in parallel.
This script is provided as an example for users who want to customize their work production process and have more refined strategy than current selection methods.
This MR starts with commit `Scripts: add a script for fetching, performing and submitting snark work` (https://github.com/MinaProtocol/mina/commit/74241548e4957223954bf6e9e53087dbd5eb06ac)
Run a mina node. Once the pending snark work list is filled with some works, you can run the script and see the new work being added to the snark pool.
> Scripts: add a script to customize snark work production

- buildkite/scripts/build-artifact.sh
- scripts/debian/builder-helpers.sh
Publish "src/lib/snark_worker/standalone/run_snark_worker.exe" in mina-daemon debian package. App will be built using two profiles (mainnet,devnet) and  placed in mina-devnet and mina-mainnet debian packages. 
App will be automatically added to dockers (daemon and rosetta) as we are installing debian while building docker
> publish standalone snark worker

- src/dune-project
This package must have been removed without deleting the declaration in the `dune-project`. It currently produces a build error, this PR will fix it.
> Remove inline_test_quiet_logs package declaration

- src/lib/transaction_snark/transaction_snark.mli
It seems the file hasn't been modified since '22. I guess it is a leftover.
*
*
Checklist:
* Closes #0000
> [trivial] Transaction_snark: remove old comment reg. type constraints

- src/app/zkapps_examples/tokens/zkapps_tokens.ml
- src/app/zkapps_examples/zkapps_examples.ml
- src/dune-project
- src/lib/blockchain_snark/blockchain_snark_state.ml
- src/lib/mina_base/account.ml
- src/lib/mina_base/account_update.ml
- src/lib/mina_base/data_as_hash.ml
- src/lib/mina_base/data_as_hash.mli
- src/lib/mina_base/prover_value.ml
- src/lib/pickles/compile.ml
- src/lib/pickles/inductive_rule.ml
- src/lib/pickles/inductive_rule.mli
- src/lib/pickles/pickles.ml
- src/lib/pickles/pickles_intf.mli
- src/lib/pickles/scalar_challenge.ml
- src/lib/pickles/scalar_challenge.mli
- src/lib/pickles/step_main.ml
- src/lib/pickles/test/chunked_circuits/chunks2.ml
- src/lib/transaction_snark/test/multisig_account/multisig_account.ml
- src/lib/transaction_snark/test/util.ml
- src/lib/transaction_snark/transaction_snark.ml
- src/lib/transaction_snark/transaction_snark.mli
* `git checkout develop && git fetch && git reset --hard origin/develop && git checkout compatible && git reset --hard origin/compatible && git checkout develop && git checkout -b dw/merge-compatible-20241217 && git merge compatible`
* N/A
Checklist:
* Closes #0000
> [20241217] merge compatible into develop

- src/lib/network_pool/indexed_pool.ml
- src/lib/network_pool/indexed_pool.mli
- src/lib/network_pool/test/indexed_pool_tests.ml
This parameter is not used.
Checklist:
> Remove constraint_constants from currency_consumed

- src/lib/pickles/step_verifier.ml
- src/lib/pickles/wrap_verifier.ml
This PR builds on https://github.com/o1-labs/snarky/pull/856, updating the snarky submodule to pull in the simplifications there.
This also adapts the aliasing in a couple of functors, so that the OCaml typechecker can harmonise the type aliases in strengthened module types that snarky generates. This was caused by a corresponding signature tweak in snarky's `Snark_intf` to better respect the order of strengthening.
> Simplify snarky `Typ.t`, removing unnecessary type parameters

- src/app/disk_caching_stats/disk_caching_stats.ml
Small change to print out proofs and keys to console while running disk_caching_stats app
> Print key sizes in disk_caching_stats

- src/lib/crypto/kimchi_backend/kimchi_backend.mli
- src/lib/crypto/kimchi_backend/pasta/kimchi_pasta.ml
- src/lib/crypto/kimchi_backend/pasta/kimchi_pasta.mli
- src/lib/crypto/kimchi_backend/pasta/pallas_based_plonk.ml
- src/lib/crypto/kimchi_backend/pasta/vesta_based_plonk.ml
- src/lib/crypto/kimchi_pasta_snarky_backend/kimchi_pasta_snarky_backend.ml
- src/lib/pickles/composition_types/spec.ml
- src/lib/pickles/step_verifier.ml
- src/lib/pickles/wrap_verifier.ml
This PR updates snarky to https://github.com/o1-labs/snarky/pull/858, allowing us to pass a `Run_state` implementation from rust.
> Update snarky for generalized `Run_state`

- src/lib/crypto/kimchi_backend/pasta/constraint_system/intf.ml
- src/lib/crypto/kimchi_backend/pasta/constraint_system/pallas_constraint_system.mli
- src/lib/crypto/kimchi_backend/pasta/constraint_system/vesta_constraint_system.mli
- src/lib/pickles/impls.ml
- src/lib/pickles/impls.mli
- src/lib/pickles/scalar_challenge.mli
- src/lib/pickles/side_loaded_verification_key.mli
- src/lib/pickles/step_main_inputs.mli
- src/lib/pickles/step_verifier.mli
- src/lib/pickles/types_map.ml
- src/lib/pickles/types_map.mli
- src/lib/pickles/wrap.mli
- src/lib/pickles/wrap_main_inputs.mli
- src/lib/pickles/wrap_verifier.mli
This PR builds upon https://github.com/MinaProtocol/mina/pull/16449, tidying up some pickles interfaces to remove spurious references to `Snarky_backendless.Cvar.t`.
> Tidy up some pickles interfaces

- src/test/command_line_tests/command_line_tests.ml
- src/test/command_line_tests/mina_bootstrapper.ml
- src/test/command_line_tests/mina_cli.ml
Increase test coverage for `mina advanced` and `mina ledger` commands
> add e2e tests for mina cli (unexpected log output)

- src/lib/network_pool/indexed_pool.ml
1. Fix two similar issues originating from confusion between previous variable names `t` and `t'` (`Account no longer has permission to send` and `Current account nonce precedes first nonce in queue`)
2. Fix the issue #16397 by ensuring removal from `applicable_by_fee` is
done only for the previous head of queue.
* Closes #16397
> Fix a few bugs in `revalidate` (mini)

- src/lib/network_pool/transaction_pool.ml
This PR builds upon https://github.com/MinaProtocol/mina/pull/16415. The commits in this PR apply a series of transformations to make the code more readable and maintainable. Most notably:
* the pervasive use of the overloaded word 'spec' is removed
* `Account_spec` is renamed to `Simple_account`
* the `Account_spec.t array` pattern is encapsulated as a new `Simple_ledger` module
* `Command_spec` is renamed to `Simple_command`
* single-letter and non-descriptive variables names have been updated
* functions and generators that cause side-effects on ledgers are named to record that
* the edge-case generators are split into their own helper functions
* transactions now carry a `sender_info` struct instead of a full account
* yojson is used in place of s-expression strings masquerading as …
> Opinionated refactoring of #16415

- src/app/dump_blocks/.ocamlformat
- src/app/dump_blocks/dump_blocks.ml
- src/app/dump_blocks/encoding.ml
A trivial PR that adds a missing `.ocamlformat` file and runs the formatter.
Checklist:
> Reformat src/app/dump_blocks

- src/app/test_executive/zkapps.ml
This PR is intended to reduce the number of flakes that we see e.g. [here](https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/3191#01948957-9ec5-4e88-ace9-86c63fcbc7ab), moving the command earlier in the sequence so that it is more likely to trigger the condition. This particular flake occurs when the first transaction is accepted into a block before the node processes the second transaction, causing an 'invalid nonce' error instead of hitting the replace-fee logic.
This PR also adds an unrelated change to help, attempting to schedule the transaction broadcasts to fall within the same slot, in the hopes that this further reduces flakiness.
> Send command with insufficient replace fee earlier to reduce flakiness

- src/lib/staged_ledger/staged_ledger.ml
- src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
- src/lib/transaction_snark_scan_state/transaction_snark_scan_state.mli
Remove `[%sexp]` from `Available_job.t`.
This eases integration with `Proof_cache_tag.t`, as we don't need to implement `sexp` for it.
Checklist:
> Remove [%sexp] from Available_job.t

- src/lib/mina_block/block.ml
- src/lib/mina_block/block.mli
- src/lib/mina_block/validated_block.ml
- src/lib/mina_block/validated_block.mli
- src/lib/transition_frontier/frontier_base/root_data.ml
- src/lib/transition_frontier/frontier_base/root_data.mli
Move `to_yojson` outside of `Stable` in `Mina_block.t`.
Implementation is not really stable and is only used for logging.
Checklist:
> Move to_yojson outside of Stable in Mina_block.t

- src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
Persistent_frontier: use `get_root_hash` instead of `get_root`.
Checklist:
> Persistent_frontier: use get_root_hash instead of get_root

- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_networking/rpcs.ml
- src/lib/staged_ledger/diff_creation_log.ml
- src/lib/staged_ledger/pre_diff_info.ml
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/transaction_snark_work/transaction_snark_work.ml
- src/lib/transaction_snark_work/transaction_snark_work.mli
- src/lib/transition_frontier/frontier_base/breadcrumb.ml
- src/lib/work_selector/inputs.ml
- src/lib/work_selector/intf.ml
- src/lib/work_selector/work_lib.ml
- src/lib/work_selector/work_selector.mli
Make `Transaction_snark_work.{Checked.t != t}`. Having the two types equal defeats the purpose of type separation.
It also confuses future refactoring of use of the two types.
Checklist:
> Make Transaction_snark_work.{Checked.t != t}

- src/lib/staged_ledger/pre_diff_info.ml
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/staged_ledger_diff/diff.ml
- src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
- src/lib/transaction_snark_work/transaction_snark_work.ml
- src/lib/transaction_snark_work/transaction_snark_work.mli
- src/lib/transition_frontier/frontier_base/breadcrumb.ml
Having them exposed means that `Transaction_snark_work.Checked.t` can be trivially constructed anywhere, without doing any checks.
Checklist:
> Hide fields of `Transaction_snark_work.Checked.t`

- src/lib/mina_block/block.ml
- src/lib/mina_block/block.mli
Remove equal from `Mina_block.t`. This eases integration with `Proof_cache_tag.t`.
Checklist:
> Remove equal from Mina_block.t

- src/lib/crypto/kimchi_bindings/stubs/Cargo.toml
- src/lib/crypto/kimchi_bindings/wasm/Cargo.toml
Part of https://github.com/MinaProtocol/mina/pull/16464/
In future PR, dependencies will be moved to a top-level "Cargo.toml". This intermediate PR will ease the review and check that the versions have the same constraints.
> [Trivial] Reorg Rust dependencies alphabetically in Cargo.toml files

- src/lib/crypto/kimchi_bindings/stubs/src/caml/caml_pointer.rs
- src/lib/crypto/kimchi_bindings/stubs/src/lagrange_basis.rs
- src/lib/crypto/kimchi_bindings/stubs/src/linearization.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_proof.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_proof.rs
- src/lib/crypto/kimchi_bindings/stubs/src/projective.rs
Would be nice to enforce it everywhere in a CI job. It is easier to read on a small screen or when splitting a Vim/Emacs window in different buffers.
> [Trivial] kimchi-bindings/stubs: enforce 80 characters limit

- buildkite/src/Monorepo.dhall
- buildkite/src/Prepare.dhall
The `generic` agents also handle some longer-running jobs, so many CI runs are blocked at the first stage until some long-lived job has finally finished. `generic-multi` is both less congested and more appropriate for this job.
> Move 'Prepare Monorepo Triage' to generic-multi buildkite agents

- src/dune-project
- src/lib/proof_cache_tag/dune
- src/lib/proof_cache_tag/identity/dune
- src/lib/proof_cache_tag/identity/proof_cache_tag.ml
- src/lib/proof_cache_tag/proof_cache_tag.mli
Add basic `proof_cache_tag`.
No cache implementation, just "identity".
Checklist:
> Add basic proof_cache_tag

- scripts/debian/builder-helpers.sh
- src/app/rosetta/scripts/docker-start.sh
fix missing-blocks-guardian location in rosetta docker
cherry-picked from: https://github.com/MinaProtocol/mina/pull/16375
resolves: https://github.com/MinaProtocol/mina/issues/16503
> [Rosetta][3.0.3.1] use mina missing block guardian script instead of download missing blocks

- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
- src/app/cli/src/init/client.ml
- src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
- src/lib/runtime_config/runtime_config.ml
Previous implementation was leading to logs about loading config files appearing twice.
Also contains some cosmetic changes based on re-review of #16186.
Checklist:
> Do not load config twice in mina_cli_entrypoint.ml

- src/lib/crypto/kimchi_backend/common/dune
- src/lib/crypto/kimchi_backend/dune
- src/lib/crypto/kimchi_backend/gadgets/dune
- src/lib/crypto/kimchi_backend/gadgets/runner/dune
- src/lib/crypto/kimchi_backend/gadgets/runner/example/dune
- src/lib/crypto/kimchi_backend/pasta/basic/dune
- src/lib/crypto/kimchi_backend/pasta/constraint_system/caml/dune
- src/lib/crypto/kimchi_backend/pasta/constraint_system/dune
- src/lib/crypto/kimchi_backend/pasta/dune
- src/lib/crypto/kimchi_bindings/js/test/dune
- src/lib/crypto/kimchi_bindings/pasta_fp_poseidon/dune
- src/lib/crypto/kimchi_bindings/pasta_fq_poseidon/dune
- src/lib/crypto/kimchi_bindings/stubs/dune
- src/lib/crypto/kimchi_bindings/stubs/pasta_bindings_backend/dune
- src/lib/crypto/kimchi_bindings/stubs/pasta_bindings_backend/none/dune
- src/lib/crypto/plonkish_prelude/dune
- src/lib/crypto/plonkish_prelude/test/dune
Cherry-picked from https://github.com/MinaProtocol/mina/pull/16464/
Following an old work trying to replace the reformat script. In some next PRs, the dune files in stubs and wasm will be changed.
Can be replicated using:
```
cd src/lib/crypto && dune fmt --auto-promote
```
It is because I modify later in [16464](https://github.com/MinaProtocol/mina/pull/16464/) the dune files, and I pretty-print it. It is to have minimal (and separated) changes in the [16464](https://github.com/MinaProtocol/mina/pull/16464/)
> [Trivial] lib/crypto: run dune fmt --auto-promote

- src/lib/mina_lmdb_storage/block.ml
- src/lib/mina_lmdb_storage/dune
Before merging PR #16361 into `compatible`, latest `compatible` wasn't merged into the feature branch. Because of that CI run didn't catch a compilation error.
This PR fixes compilation by removing usage of `Inline_test_quiet_logs`.
Checklist:
> Fix src/lib/mina_lmdb_storage

- src/lib/crypto/kimchi_bindings/wasm/src/srs.rs
companion
https://github.com/o1-labs/o1js-bindings/pull/327
https://github.com/o1-labs/o1js/pull/1984
> Handle whole domain commitment by pointer

- src/lib/ledger_catchup/best_tip_lru.ml
- src/lib/ledger_catchup/best_tip_lru.mli
- src/lib/ledger_catchup/super_catchup.ml
- src/lib/transition_router/transition_router.ml
Currently we store too much of data in the LRU cache.
This eases integration with `Proof_cache_tag.t`.
Checklist:
> Change type of Best_tip_lru

- src/lib/transition_frontier/persistent_frontier/database.ml
- src/lib/transition_frontier/persistent_frontier/database.mli
- src/lib/transition_frontier/persistent_frontier/worker.ml
Accept/return state hash instead of `Root_data.Mimimal.t` in `Database.{move_root, find_arcs}`.
This eases integration with `Proof_cache_tag.t`.
Checklist:
> Simplify types of Database.{move_root, find_arcs}

- src/lib/staged_ledger/staged_ledger.ml
- src/lib/transaction_snark_work/transaction_snark_work.mli
The `Transaction_snark_work.Checked.Stable` module is not used (for a good reason), and shouldn't be exposed.
Plus removing an unnecessary type annotation in `staged_ledger.ml`.
Based on review comments from PR:
- #16485
Checklist:
> Remove Stable from Transaction_snark_work.Checked

- src/lib/mina_wire_types/proof_carrying_data.ml
- src/lib/proof_carrying_data/dune
- src/lib/proof_carrying_data/proof_carrying_data.ml
Mirror `Proof_carrying_data` in `Mina_wire_types`.
Checklist:
> Mirror Proof_carrying_data in Mina_wire_types

- src/lib/runtime_config/runtime_config.ml
This PR removes log messages of the form
```
Reading configuration files []
```
> Remove useless log messages

- scripts/mina-local-network/mina-local-network.sh
This PR adds an option to override the slot time for a 'lightnet' network. When the flag is passed, the config file will have an entry added that modifies the `block_window_duration_ms` field accordingly.
This lets us run networks more quickly for testing, for example with
```
./scripts/mina-local-network/mina-local-network.sh --override-slot-time 3000 --proof-level none --update-genesis-timestamp --seed-start-port 3100 --whales 1 --fish 0 --nodes 0
```
> Allow override of slot times for lightnet

- buildkite/scripts/bench/run.sh
- buildkite/src/Constants/DebianVersions.dhall
- scripts/benchmarks/lib/bench.py
Two small issues fix for benchmarks.
- check if there is enough data for calculating moving average. If not, skip comparison
- add missing category tag for jane street related benchmarks
> [Benchmarks] fix for moving average. Add category for jane benchmarks

- src/lib/disk_cache/lmdb/disk_cache.ml
- src/lib/disk_cache/lmdb/dune
- src/lib/lmdb_storage/conv.ml
Another implementation of disk cache, baked by lmdb. Added two new functions for Disk_cache module (iteri, count).
Implemented sanity test for read - write operations on cache. 
Also some fix for converter for all structs implementing Binable interface
> [Proof cache] Disk cache: LMDB implementation

- src/app/archive/cli/dune
- src/app/archive/dune
- src/app/archive/lib/dune
Add flag to support sigterm command from bisect ppx. This is required to generate coverage on sigterm command when using instrumented archive. See details here: 
https://github.com/aantron/bisect_ppx/blob/master/doc/advanced.md#sigterm-handling
Main problem is that we need to fetch instrumentation artifacts from running archive node. Usually when we stop archive process it won't generate coverage files unless process support 'coverage' sigterm
> allow instrumentation sigterm in archive node

- src/lib/proof_cache_tag/dune
- src/lib/proof_cache_tag/identity/proof_cache_tag.ml
- src/lib/proof_cache_tag/lmdb/dune
- src/lib/proof_cache_tag/lmdb/proof_cache_tag.ml
- src/lib/proof_cache_tag/proof_cache_tag.mli
Added real implementation for proof caching apart from `identity` one. Lmdb implementation uses `disk_cache.lmdb` as proof cache db lib. 
This PR is continuation of proof_cache_tag lib started in: https://github.com/MinaProtocol/mina/pull/16478
> [Proof cache] lmdb implementation

- src/lib/bootstrap_controller/bootstrap_controller.ml
- src/lib/genesis_proof/genesis_proof.ml
- src/lib/mina_block/validated_block.ml
- src/lib/mina_block/validated_block.mli
- src/lib/sync_handler/sync_handler.ml
- src/lib/transition_frontier/frontier_base/breadcrumb.ml
- src/lib/transition_frontier/frontier_base/breadcrumb.mli
- src/lib/transition_frontier/frontier_base/root_data.ml
- src/lib/transition_frontier/full_frontier/full_frontier.ml
- src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
Problem: RPC get_staged_ledger_aux_and_pending_coinbases_at_hash computes staged ledger hash on every call, which is unnecessary expensive.
Solution: use staged ledger hash from breadcrumb on each invocation of RPC.
Checklist:
> Don't compute staged ledger hash on every RPC call

- src/lib/ledger_catchup/normal_catchup.ml
- src/lib/ledger_catchup/super_catchup.ml
- src/lib/mina_block/validated_block.ml
- src/lib/mina_block/validated_block.mli
- src/lib/transition_frontier/catchup_hash_tree.ml
- src/lib/transition_frontier/extensions/root_history.ml
- src/lib/transition_frontier/frontier_base/diff.ml
- src/lib/transition_frontier/frontier_base/diff.mli
- src/lib/transition_frontier/frontier_base/root_data.ml
- src/lib/transition_frontier/frontier_base/root_data.mli
- src/lib/transition_frontier/full_catchup_tree.ml
- src/lib/transition_frontier/full_frontier/full_frontier.ml
- src/lib/transition_frontier/persistent_frontier/database.ml
- src/lib/transition_frontier/persistent_frontier/database.mli
- src/lib/transition_frontier/persistent_frontier/worker.ml
Remove `Stable.Latest.t = t` from interfaces. This is a preparation step for removing the equality in the implementation as well.
A step towards _Use Proof_cache_tag.t in scan state #16571._
Checklist:
> Decouple Mina_block.Validated.{Stable.Latest.t, t}

- README.md
This PR replaces a broken link in the README. This fixes https://github.com/MinaProtocol/mina/issues/15735.
> Fixup broken link in README

- src/lib/mina_base/signed_command_memo.ml
This PR fixes https://github.com/MinaProtocol/mina/issues/16155. Memos sent in JSON format to the GraphQL endpoint may have an invalid length, and can cause nodes to crash when printing memos that are too short.
This PR fixes this by adding validity checks around the code involved in printing.
> Check validity of memos from GraphQL before printing them

- src/app/cli/src/init/client.ml
Yojson's pretty printing creates a huge call stack using the built-in OCaml list iterators. Since we're only printing an array of objects, we can easily implement a tail-recursive version.
This fixes https://github.com/MinaProtocol/mina/issues/16579.
> Manually implement JSON array printing to avoid stack overflow

- src/lib/mina_net2/libp2p_stream.ml
Without this, we will attempt to send more enqueued messages, but if the stream has already failed then we've already decided to close it. This prevents a cascade of error messages like
```
2025-02-08 15:09:17 UTC [Error] error sending message on stream "20": $error
error: {
"string": "only wrote 0 out of 15 bytes error: libp2p error: stream reset"
}
2025-02-08 15:09:17 UTC [Warn] RPC call error for "get_best_tip"
2025-02-08 15:09:17 UTC [Error] error sending message on stream "20": $error
error: { "string": "internal RPC error: unknown stream_idx" }
2025-02-08 15:09:17 UTC [Error] error sending message on stream "20": $error
error: { "string": "internal RPC error: unknown stream_idx" }
2025-02-08 15:09:17 UTC [Error] error sending message on stream "20": $error
error: { "string": …
```
> Stop sending data on libp2p streams after the first error

- src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
- src/lib/transition_frontier/persistent_frontier/sync.ml
- src/lib/transition_frontier/persistent_frontier/sync.mli
- src/lib/transition_frontier/persistent_frontier/worker.ml
- src/lib/transition_frontier/persistent_frontier/worker.mli
Use `dequeue_snarked_ledger` instead of persistent root instance when creating the worker.
This simplifies the future unit testing effort.
Checklist:
> Simplify interface of persistent frontier worker

- src/lib/mina_compile_config/dune
Dune file of mina_compile_config package was referring to a library from another package by its internal name.
* `nix build '.?submodules=1#pkgs.mina_compile_config'` succeeds
Checklist:
> Use public package names in compile config's dune

- buildkite/scripts/check-compatibility.sh
This PR ensures that this test is actually checking what it purports to be checking: that `CURR_BRANCH` is compatible with `MAINLINE_BRANCH`. Since https://github.com/MinaProtocol/mina/pull/14181 first landed, the order of operations in https://github.com/MinaProtocol/mina/blob/914218e94d5880cacf45b9bbf31aebb381792f46/buildkite/scripts/check-compatibility.sh#L143-L162 ensures that `CURR_BRANCH` is always incorrectly set to `MAINLINE_BRANCH`, and so the test will never have given us useful information.
It is likely that we don't want this test for now anyway. However, it feels pragmatic to fix the test so that we can use it for subsequent hard forks.
> Fix the compatibility-with-develop test

- buildkite/scripts/debian/install.sh
- buildkite/scripts/run-test-executive-local.sh
- buildkite/src/Constants/ContainerImages.dhall
- dockerfiles/stages/3-toolchain
This PR tweaks the uses of `apt-get update` in CI to avoid re-fetching all sources unnecessarily. In particular,
* we hoist the installation of `aptly` into the toolchain file, and
* we limit `apt-get update` to update only the local Mina repository that `aptly` generates.
This PR should improve the stability of CI, where a mirror sync can cause flakiness outside of our control.
> Remove `apt-get update` from aptly script

- flake.nix
- nix/ocaml.nix
- src/lib/disk_cache/dune
- src/lib/proof_cache_tag/dune
There were a number of changes to codebase that required an update to nix code related to _Granular nix_:
* `command_line_tests` relied on home directory to exist, which wasn't the case for the environment provided by nix testing
* `block_storage` was removed and `mina_lmdb_storage` was created as a replacement
Furthermore, two dune libraries were introduced that were not specifying `(name)` stanza in dune file. Dune's specification mentions it as an obligatory, however in presence of `public_name` dune handles this case well. While we could extend nix code to support that case in a similar way, this time it seemed easier to simply make the two new libraries to conform to what other dune libraries are doing.
Checklist:
- Notify Velocity team if …
> Fix granular nix compilation

- buildkite/scripts/debian/promote.sh
- buildkite/scripts/run_promote_build_job.sh
- buildkite/scripts/run_verify_promoted_build_job.sh
- buildkite/src/Command/Promotion/PromotePackages.dhall
- buildkite/src/Command/Promotion/VerifyDebian.dhall
- buildkite/src/Command/Promotion/VerifyPackages.dhall
- buildkite/src/Entrypoints/PromotePackage.dhall
- scripts/debian/reversion.sh
- scripts/debian/verify.sh
Fixing promotion job after introducing multiple debian repo.  
Promotion job which is used rarely was lacking adjustment after code change for supporting signing debian packages. Main goal was not to change UX of promotion pipeline, so still PackagesO1Test is default debian repository for both source and target. 
Issue was caused by lack of repo-key propagation to promote.sh script. `Packages.o1test.net` debian repository is not signed therefore such key does not exist for it. 
There were two fixes possible:
- either completely remove repo-key and derived settings like sign etc, since currently used packages.o1test.net repository is not signed
- support signed repositories, which requires import correctly debian key locally (+ some gpg options) and expose setting for allowing cross debian …
> Fix promotion job : introduce from/to repo with accompanying key

- buildkite/scripts/debian/promote.sh
Issue spotted while testing https://github.com/MinaProtocol/mina/pull/16633. If the source and target version are the same previously we were using deb-s3 copy. However this introduce small issues as it not updates SUITE attribute which we are trying to kepp in track when manually doing reversion (by downloading packages locally unwrapping it modifying Package file and uploading it again).
The ultimate solution would be to patch our forked version of deb-s3, but till now we will use our working version
> [CI] do not use deb-s3 for when the version is the same

- buildkite/src/Jobs/TearDown/PublishDebians.dhall
Disabling jobs which runs in nightly for publishing debians. Now, only manual publishing is allowed
> [CI] Disable publishing debians to debian repo

- src/test/command_line_tests/command_line_tests.ml
Single node test was flaky due to relying on string comparision on ledger currency test like here: 
https://buildkite.com/o-1-labs-2/mina-o-1-labs/builds/36424#019493cb-40be-4294-bb92-d0826c56786f
Now comparision is relying on float representation.
> [single node tests] use float comparision instead of flaky string comparision

- src/app/test_executive/block_production_priority.ml
- src/app/test_executive/block_reward_test.ml
- src/app/test_executive/chain_reliability_test.ml
- src/app/test_executive/gossip_consistency.ml
- src/app/test_executive/hard_fork.ml
- src/app/test_executive/medium_bootstrap.ml
- src/app/test_executive/payments_test.ml
- src/app/test_executive/slot_end_test.ml
- src/app/test_executive/verification_key_update.ml
- src/app/test_executive/zkapps.ml
- src/app/test_executive/zkapps_nonce_test.ml
- src/lib/integration_test_lib/intf.ml
- src/lib/integration_test_local_engine/docker_network.ml
During integration tests debugging i found it handy to squash boilerplate code for fetching node or keypair from 3 lines to a single one. 
No behavior was changed, purely cosmetic PR
> [Int tests] remove boilerplate code for fetching node and genesis keypair

- src/lib/transition_frontier/frontier_base/root_data.ml
- src/lib/transition_frontier/frontier_base/root_data.mli
- src/lib/transition_frontier/persistent_frontier/database.ml
- src/lib/transition_frontier/persistent_frontier/database.mli
This is the same PR as #16650 , just from a branch in upstream so CI is happy. 
--------------
This is a follow up for https://github.com/MinaProtocol/mina/pull/16624 
This PR only contains patch to be merged into compatible. It's compatible because we try to replace `Root` with `(Root_hash, Root_common)` when:
1. initializing a new DB;
2. trying to moving the root;
3. trying to query `root` or `root_hash` 
That means attempting to perform transactions on old persistence database, the bottleneck will occur once and not after.  
Here's the PR for the [testcase](https://github.com/MinaProtocol/mina/pull/16655).
> replace Root with Root_(hash, common) in persistent database

- buildkite/scripts/version-linter-patch-missing-type-shapes.sh
- buildkite/src/Constants/DebianVersions.dhall
- buildkite/src/Jobs/Test/VersionLint.dhall
There is a subtle error in check for missing ref files in version-linter script. There was missing * at the end which made that we always try to regenerate ref files. I noticed that when we merged caqti update which broke compatibilitiy with old toolchain so checking out old code from e.g master always errored out since it tried to build old code with new caqti version. Fixing asterix should partially solve issue. I also regenerated locally ref files and uploaded to mina-type-shapes bucket which solves the issue
> Version linter missing ref files check

- src/dune-project
- src/lib/zkapp_vk_cache_tag/dune
- src/lib/zkapp_vk_cache_tag/zkapp_vk_cache_tag.ml
- src/lib/zkapp_vk_cache_tag/zkapp_vk_cache_tag.mli
Introducing zkapp_vk_cache_tag dune module for cache implementation for Zkapp Verification key. In further PRs this project will be use in places we want to cache verification keys, for example transaction pool. I created yet another database exclusively for zkapp vk (we won't mix it with proofs in cache db)
Caching is not enabled yet, so there should not be any change of behaviour
This Pr enables merging further work under `dkijania/experiment_with_wires branch` which goal is to implement caching in tranasaction_pool module for `Vk_refcount_table` struct 
Basically module mimic how proof_cache_tag looks like. As a result we will have two cache db one for proofs and one for verification keys
Enables https://github.com/MinaProtocol/mina/pull/16674
> [Zkapp VK Caching] Cache Tag Project

- scripts/debian/reversion-helper.sh
- scripts/debian/reversion.sh
Refactoring needed for https://github.com/MinaProtocol/mina/pull/16661 under https://github.com/MinaProtocol/mina/issues/16640 investment. New code will use reversion-helper.sh without it's scripting interface, which is now in reversion.sh . However we want to make it compatible with previous version. In order to allow reversion-helper.sh usage from different script I introduced --path parameter which can detect caller pwd
> [Promotion] Split reversion script

- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_lib/tests/tests.ml
- src/lib/network_pool/dune
- src/lib/network_pool/intf.ml
- src/lib/network_pool/transaction_pool.ml
- src/lib/transaction_inclusion_status/transaction_inclusion_status.ml
PR on top of https://github.com/MinaProtocol/mina/pull/16671. It uses newly create module zkapp_vk_cache_tag. Then using similar approach as proof_cache_tag module it is used in place of Verification_key_wire.
> [Caching] use zkapp_vk_cache_tag project for caching zkapp verification keys

- src/lib/crypto/kimchi_bindings/stubs/src/caml/caml_pointer.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_proof.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_proof.rs
Coming from 2ec9256db104760f3538c086a56cc385f1347f7c
If we don't have this update, Rust complains when updating to 1.74.
To convince yourself, update rust-toolchain.toml in kimchi_bindings/stubs to 1.74, and see the error when building.
This is a first step to update Rust in Mina to newer versions.
Doing it gradually.
> Kimchi-bindings: use UnsafeCell

- src/lib/transition_frontier/persistent_frontier/database.ml
* As requested by @georgeee , we now delete the key `Root` when we try to query root, and when we try to move the root
* https://github.com/MinaProtocol/mina/pull/16655
Checklist:
* None
> remove root key on split of the root -> root_(hash, common)

- scripts/tests/rosetta-connectivity.sh
- scripts/tests/rosetta-sanity.sh
Expanding test suite for rosetta by adding more checks to connectivity test. After rosetta is synced with given network we are sending some requests with hardcoded yet valid inputs. Addional 6 tests should be good e2e sanity. I also modified connectivity tests so now it won't wait for adding blocks but directly querying rosetta api and check status (waits for Synced).
I'm not super confident that hardcoded values are good final form of this test. Maybe we could fetch it from explorers at minascan or read it directly from database ? However, maybe for hot fix release test it would be enough
> Added new sanity tests for rosetta

- buildkite/src/Command/DockerImage.dhall
- buildkite/src/Command/MinaArtifact.dhall
- buildkite/src/Constants/DockerPublish.dhall
- buildkite/src/Jobs/Release/MinaToolchainArtifactBullseye.dhall
- buildkite/src/Jobs/Release/MinaToolchainArtifactFocal.dhall
- buildkite/src/Pipeline/Mode.dhall
In order to preserve cost of our gcr.io, but also avoid lengthy docker push operation, this PR avoid pushing non essential dockers to gcr.io. What is essential or not can be configured, as well as hard switches Enabled all or Disabled all. 
As a result only daemon,archive,rosetta and functional_test_suite (until https://github.com/MinaProtocol/mina/pull/16608 is not merged) dockers will be pushed to gcr.io all others can be build using `!ci-docker-me` pipeline.
> Skip publishing dockers on PR 

- src/lib/gossip_net/message.ml
- src/lib/mina_block/block.ml
- src/lib/mina_block/block.mli
- src/lib/mina_block/validated_block.ml
- src/lib/transition_handler/block_sink.ml
- src/lib/transition_handler/catchup_scheduler.ml
_Step toward #16582_
* Replace `Mina_block.to_yojson` with `Mina_block.to_logging_yojson`
* the new functions operates on headers, but pretends to dump the block-like json
* Small refactoring of `block_sink.ml` (just syntax)
Checklist:
> Small refactoring of `mina_block.ml` and `block_sink.ml`

- automation/services/watchdog/Dockerfile
Buster is EOL let's use bullseye
> [Sync] Bump watchdog docker from version

- scripts/debian/publish.sh
While running debian publish pipeline for  cache reorg i stumbled into excessive duration for verifying **unstable** channel. 
Example: https://buildkite.com/o-1-labs-2/mina-build-debian/builds/17
This PR skips verification on unstable channel as it takes 40 minutes. We have plans to clean unstable channel and/or shrink it. However, before that let's unblock publishing job.  
INFO:
Even without this fix publishing is fully functional as this is last additional check.
> [CI][Publish] skip debian channel check for unstable channel

- src/lib/network_pool/indexed_pool.ml
- src/lib/network_pool/test/indexed_pool_tests.ml
- src/lib/network_pool/transaction_pool.ml
- src/lib/transaction/transaction_hash.ml
- src/lib/transaction/transaction_hash.mli
Refactoring is executed in two steps:
- **Rename function hash -> transaction_hash**
- Simple renaming of a function with changes across codebase
- **Remove unused Stable module in Transaction_hash**
- Remove unstable module completely
- Add `hash` function back to `User_command_with_valid_signature` module so that it can be used for hash tables
* This refactoring doesn't change any functionality
Checklist:
> Remove Stable from Transaction_hash.User_command_with_valid_signature

- buildkite/scripts/setup-database-for-archive-node.sh
Make `shellcheck` happy on `buildkite/scripts/setup-database-for-archive-node.sh`.
Previous output was:
```
In buildkite/scripts/setup-database-for-archive-node.sh line 15:
sudo -u postgres createdb -O $user $db
^---^ SC2086 (info): Double quote to prevent globbing and word splitting.
^-^ SC2086 (info): Double quote to prevent globbing and word splitting.
Did you mean: 
sudo -u postgres createdb -O "$user" "$db"
In buildkite/scripts/setup-database-for-archive-node.sh line 16:
PGPASSWORD=$password psql -h localhost -p $port -U $user -d $db -a -f src/app/archive/create_schema.sql
^---^ SC2086 (info): Double quote to prevent globbing and word splitting.
^---^ SC2086 (info): Double quote to prevent globbing and word splitting.
^-^ SC2086 (info): Double quote to prevent globbing and word …
```
> Buildkite: fix shellcheck on setup-db-archive-node

- src/lib/pickles/pickles_intf.mli
- src/lib/pickles/side_loaded_verification_key.ml
- src/lib/pickles/side_loaded_verification_key.mli
- src/lib/transaction_snark/transaction_snark.ml
Pass dummy vk when no vk is present in account for proved account update
Twin against `compatible` for PR #16699.
Checklist:
> [compatible] fix work vk tracking issue

- src/lib/mina_base/user_command.ml
- src/lib/mina_wire_types/test/type_equalities.ml
* Remove type that wasn't used in any sensible way
* Simple refactoring, no changes to functionality
Checklist:
> Remove User_command.Valid.Stable

- src/lib/mina_base/zkapp_command.ml
- src/lib/mina_wire_types/test/type_equalities.ml
* Remove type that wasn't used in any sensible way
* Simple refactoring, no changes to functionality
Checklist:
> Remove Zkapp_command.Valid.Stable

- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
Fixing native logger setup which was another victim for revert after introducing runtime config.
This commit changed logger behavior in regards to itn_features flag:
https://github.com/MinaProtocol/mina/commit/2c858d7309499da50e23ac480b5af3bff6e777a6#diff-e8bcb44f0f9c363945c8e5adcea9ea47904f79f44e362eef7ec6c484e61aa1a1L413
However it was reverted incompletely. As a result Mina_compile_config usage was removed but not reinstated on mina setup code. 
I tested above fix with internal log fetcher app and by manually validating that all the logger with internal level are derived from the one setup with ~itn_features
> Fix internal logs for itn 

- scripts/docker/build.sh
After Luis introduced persistent storage for docker images, out situation improved a bit (agents are not crashing due to OOM). However, on our target is a new issue: docker storage growth in alarming time. This simple fix will prune old images (older than 24 hours) before building any. Since docker build is a major contributor to a space issue it will bring a bit of space relief when prunning before building
> [CI] Prune dockers before build

- scripts/tests/rosetta-sanity.sh
FIxed message on successful version check for rosetta:
```
✅  Rosetta is synced
🔗  Testing Rosetta sanity functionality for network: devnet
🧪  1/6 Testing network/status endpoint
✅  Rosetta is synced
🧪  2/6 Testing network/options endpoint
✅  Rosetta Version is **not** correct <--- removed not
🧪  3/6 Testing network/list endpoint
✅  Block hash correct
🧪  4/6 Testing account/balance endpoint for account
✅  Account: Balance for ok
🧪  5/6 Testing search/transactions endpoint for payment transaction
✅  Payment transaction found
🧪  6/6 Testing search/transactions endpoint for zkapp transaction
✅  Zkapp transaction found
🎉  All tests passed successfully!
```
> Fix rosetta sanity success message

- flake.lock
Support dune files without `name` stanza.
PR bumps versions of `dune-nix` and `describe-dune` to support libraries and executables with only `public_name` defined.
Previous version assumed `name` stannza to be always present.
This fixes granular nix building.
Checklist:
> Granular nix: support dune files with only `public_name`

- nix/rust.nix
Follow-up on https://github.com/MinaProtocol/mina/pull/16731 and https://github.com/MinaProtocol/mina/pull/16652
> Nix: remove old Rust version (1.72 and nightly-2023-09-01)

- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
- src/app/cli/src/init/mina_run.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_lib/mina_lib.mli
- src/lib/snark_worker/functor.ml
- src/lib/snark_worker/intf.ml
- src/lib/snark_worker/prod.ml
- src/lib/snark_worker/rpcs.ml
- src/lib/snark_worker/standalone/run_snark_worker.ml
- src/lib/transaction/transaction.ml
- src/lib/transaction_witness/transaction_witness.ml
- src/lib/transaction_witness/transaction_witness.mli
- src/lib/uptime_service/uptime_service.ml
- src/lib/work_selector/intf.ml
- src/lib/work_selector/work_lib.ml
- src/lib/work_selector/work_selector.mli
* Decouples `Transaction.Stable.Latest.t` and `Transaction.t`
* Decoupling unblocks changing the structure of regular type to use on-disk cache
* This is a simple refactoring, no behavior change
Checklist:
> Prepare for Transaction.{Stable.Latest.t != t}

- changes/16803.md
- src/lib/pickles/pickles.ml
This PR removes some `[@warning "-45"]` from pickles. Nothing is affected.
> Remove warning -45 from 'pickles/pickles.ml'

- src/lib/pickles/pickles_intf.mli
This is a simple PR documenting more about `pickles.compile_promise`. No changelog should be needed.
> Document the args for Pickles.compile_promise

- src/lib/pickles/README.md
This PR added a link to zkpmooc on recusive-SNARKs, no changelog should be added.
> Add a link to explainer for recursive-SNARKs

- src/lib/merkle_ledger/any_ledger.ml
- src/lib/merkle_ledger/database.ml
- src/lib/merkle_ledger/intf.ml
- src/lib/merkle_ledger/null_ledger.ml
- src/lib/merkle_ledger_tests/test_database.ml
- src/lib/merkle_ledger_tests/test_mask.ml
- src/lib/merkle_mask/masking_merkle_tree.ml
This PR is a no-op, removing an unused ledger function. The tests corresponding to this function have been deleted.
This function is problematic -- or actually unimplementable -- for automated ledger upgrades where the calculated hash is different. Since it's unused, it makes more sense to delete it entirely.
> Remove unused ledger function `set_inner_hash_at_addr_exn`

- dockerfiles/Dockerfile-mina-rosetta
Change to the `dockerfiles/Dockerfile-mina-rosetta` to update the installation process for the Rosetta CLI with a new dependency.
Updates to Rosetta CLI installation:
* [`dockerfiles/Dockerfile-mina-rosetta`](diffhunk://#diff-54b335cf3a3b99ca2072224ae14abfecab9f753647cf3daaaf18086559edc271L68-R70): Changed the URL and references from `rosetta-cli` to `mesh-cli` to reflect the new dependency and ensure compatibility with the updated rosetta-sdk-go.
> [Master] correct path to rosetta-cli archive

- dockerfiles/Dockerfile-mina-rosetta
porting https://github.com/MinaProtocol/mina/pull/16835 to compatible
> [Comp] correct path to rosetta-cli archive

- changes/16812.md
This reintroduces the feature reverted here https://github.com/MinaProtocol/mina/pull/16782, with a bugfix.
`proof-systems` PR:
- https://github.com/o1-labs/proof-systems/pull/3121
> Update proof-systems: reintroduce perm_aggreg parallelization + bugfix

- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
- src/app/cli/src/init/mina_run.ml
- src/config/devnet.mlh
- src/config/mainnet.mlh
- src/lib/mina_compile_config/mina_compile_config.ml
- src/lib/mina_lib/config.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/node_config/for_unit_tests/node_config_for_unit_tests.ml
- src/lib/node_config/intf/node_config_intf.mli
- src/lib/node_config/node_config.ml
This PR is successor of https://github.com/MinaProtocol/mina/pull/16754 where we fixed itn features setup for logger. 
Here we want to remove itn_features flag from compile config completely and  read it from env var. I used this approach as i wanted to preserve conditional appearance of itn_* related cli argument. If there is a better way to control when those argument are available, then I'm happy to change it. 
Usage: 
```
ITN_FEATURES=1 DUNE_PROFILE=devnet dune exec src/app/cli/src/mina.exe -- daemon  -insecure-rest-server --itn-graphql-port 8080 --itn-keys ....  
```
> move itn_feature from compile config to env var

- src/lib/pickles/pickles.ml
- src/lib/pickles/step.ml
- src/lib/pickles/test/test_wrap_hack.ml
- src/lib/pickles/verify.ml
- src/lib/pickles/wrap.ml
- src/lib/pickles/wrap_hack.ml
- src/lib/pickles/wrap_hack.mli
This PR removes an unused argument from `hash_messages_for_next_wrap_proof`. This is a no-op, and the only validation needed is that this compiles.
> Pickles: Remove unused function argument

- src/lib/mina_base/user_command.ml
- src/lib/mina_stdlib/dune
- src/lib/mina_stdlib/list.ml
- src/lib/mina_stdlib/list.mli
- src/lib/staged_ledger/check_commands.ml
A simple noop refactor, should be no behavioral change. No change log should be needed.
> Refactor `User_command.Make_to_all_verifiable.to_all_verifiable` with `process_separately`

- src/lib/filtered_external_transition/filtered_external_transition.ml
- src/lib/mina_graphql/types.ml
Instead of having it defing by Stable module.
Preparation step to break `Stable.Latest.t = t` equality in one of
future commits.
* Trivially simple refactoring
Checklist:
> Define Filtered_external_transition.t explicitly

- scripts/archive/emergency_hf/test/runner.sh
This pull request includes a small change to the `scripts/archive/emergency_hf/test/runner.sh` file. The change ensures that if the `replayer-postgres` container already exists, it will be killed and removed before starting a new one.
> Stabilize emergency hf test

- changes/16660.md
- src/lib/mina_block/block.ml
- src/lib/mina_block/block.mli
- src/lib/staged_ledger/pre_diff_info.ml
- src/lib/staged_ledger_diff/diff.ml
- src/lib/staged_ledger_diff/diff_intf.ml
Introduce `transactions` function for `Mina_block`'s stable type.
Implementation doesn't rely on `Stable.Latest.t = t`, which is useful to utilize the new `transactions` function after we break the equality in #16496.
_Step toward #16582_
Checklist:
> Add `Mina_block.Stable.Latest.transactions`

- src/lib/network_pool/transaction_pool.ml
Prettify code a little bit, move some code around.
This refactoring is useful for a much large effort in #16556.
Checklist:
> Small refactroing of `transaction_pool.ml`

- buildkite/scripts/test-nix.sh
- changes/16857.md
- flake.nix
- nix/README.md
- nix/ocaml.nix
- nix/rust.nix
- src/lib/crypto/kimchi_bindings/stubs/dune
hotfix / followup to #16820
- fix `o1js_stubs` build
- enforce `dune build src` in nix ci
- rename `MARLIN_PLONK_*` env vars to `KIMCHI_*`
> hotfix / follow-up  to Move kimchi-stubs into proof-systems

- src/app/test_executive/verification_key_update.ml
- src/app/zkapps_examples/test/actions/actions.ml
- src/app/zkapps_examples/test/add_events/add_events.ml
- src/app/zkapps_examples/test/big_circuit/big_circuit.ml
- src/app/zkapps_examples/test/calls/calls.ml
- src/app/zkapps_examples/test/empty_update/empty_update.ml
- src/app/zkapps_examples/test/initialize_state/initialize_state.ml
- src/app/zkapps_examples/test/optional_custom_gates/zkapp_optional_custom_gates_tests.ml
- src/app/zkapps_examples/tokens/zkapps_tokens.ml
- src/app/zkapps_examples/zkapps_examples.ml
- src/lib/blockchain_snark/blockchain_snark_state.ml
- src/lib/crypto/plonkish_prelude/hlist.ml
- src/lib/crypto/plonkish_prelude/hlist.mli
- src/lib/pickles/compile.ml
- src/lib/pickles/compile.mli
- src/lib/pickles/pickles.ml
- src/lib/pickles/pickles_intf.mli
- src/lib/pickles/test/chunked_circuits/chunks2.ml
- src/lib/pickles/test/chunked_circuits/chunks4.ml
- src/lib/pickles/test/chunked_circuits/chunks8.ml
- src/lib/pickles/test/optional_custom_gates/lookup_range_check.ml
- src/lib/pickles/test/optional_custom_gates/pickles_test_optional_custom_gates.ml
- src/lib/transaction_snark/test/access_permission/transaction_snark_test_access_permission.ml
- src/lib/transaction_snark/test/multisig_account/multisig_account.ml
- src/lib/transaction_snark/test/ring_sig.ml
- src/lib/transaction_snark/transaction_snark.ml
This PR is a no-op, but simplifies the pickles interface.
Pickles previously required the user to manually provide the number of inductive rule branches in its `~choices` argument separately as the `~branches` argument, and then asserted that it equals the true number at runtime. This is both annoying and unnecessary.
This PR modifies the hlist type used for the `choices` to encode its length as a type-level nat by construction. Since this type can now always be inferred from the hlist itself, there is no longer any need to pass a separate type witness for the number of branches.
> Pickles: remove `~branching` argument

- src/lib/pickles/compile.ml
- src/lib/pickles/pickles.ml
- src/lib/pickles/step_branch_data.ml
- src/lib/pickles/step_branch_data.mli
- src/lib/pickles/step_main.ml
- src/lib/pickles/step_verifier.ml
- src/lib/pickles/step_verifier.mli
- src/lib/pickles/types_map.ml
- src/lib/pickles/types_map.mli
This PR builds upon #16849. This removes `proof_verifieds` as a function argument where it was unused, and then removes the corresponding tracking that is no longer used.
This PR is a no-op, but simplifies some of the internals of pickles to make it easier to understand. As long as this compiles, this PR is safe, given the lack of functional changes.
> Pickles: stop tracking unused value `proof_verifieds`

- buildkite/scripts/debian/install.sh
- buildkite/scripts/debian/start_local_repo.sh
- scripts/debian/aptly.sh
Performance tests are failing occasionally due to too early access to aptly in order to fetch packages. As a consequence they cannot find them and error out. This PR solves this race conditions and make all scripts to wait (optional flag to preserve compatibility),
> [CI] wait for aptly service

- src/lib/mina_block/dune
Removed unnecessary dependencies from mina_block dune file:
- core_kernel
- async_kernel
- bin_prot.shape  
- base.caml
- sexplib0
- result
- base
> Dune: remove unused dependencies in mina_block

- src/lib/staged_ledger/dune
Removed unnecessary dependencies from staged_ledger dune file:
- async_kernel
- base.caml
- base
- sexplib0
- core_kernel  
- mina_base.import
> Dune: remove unused dependencies in staged_ledger

- src/lib/mina_state/dune
Removed unnecessary dependencies from mina_state dune file:
- base.caml
- bin_prot.shape
- base
- sexplib0
- core_kernel
> Dune: remove unused dependencies in mina_state

- src/lib/genesis_ledger/dune
Removed unnecessary dependencies from coda_genesis_ledger (genesis_ledger) dune file:
- core_kernel
- base
- mina_base.import
> Dune: remove unused dependencies in coda_genesis_ledger

- src/lib/network_pool/dune
Removed unnecessary dependencies from network_pool dune file:
- result
- base
- async_kernel
- core_kernel
- sexplib0
- base.caml
- bin_prot.shape
- mina_base.import
> Dune: remove unused dependencies in network_pool

- src/lib/file_system/dune
- core_kernel
- async_kernel
- base.caml
> Clean up unused library dependencies in file_system

- src/lib/direction/dune
Remove the following unused dependency:
- sexplib0
> Clean up unused library dependencies in direction

- src/lib/exit_handlers/dune
> Clean up unused library dependencies in exit_handlers

- src/lib/fake_network/dune
- core_kernel.uuid
- core_kernel
- base.caml
- async_kernel
- sexplib0
> Clean up unused library dependencies in fake_network

- src/lib/fields_derivers/dune
> Clean up unused library dependencies in fields_derivers

- src/lib/data_hash_lib/dune
- result
- bin_prot.shape
- sexplib0
- base.caml
> Clean up unused library dependencies in data_hash_lib

- src/lib/mina_generators/dune
> Clean up unused library dependencies in mina_generators

- src/lib/interruptible/dune
> Clean up unused library dependencies in interruptible

- src/lib/hex/dune
> Clean up unused library dependencies in hex

- changes/16809.md
Title is self-descriptive. We want more concise changelog entry for it to be able to be read by end-user. 
No changelog entry should be added.
> fix changelog entry 16809 to be more concise

- src/lib/hex/dune
- src/lib/internal_tracing/dune
> Clean up unused library dependencies in internal_tracing

- src/lib/itn_crypto/dune
> Clean up unused library dependencies in itn_crypto

- src/lib/key_gen/dune
> Clean up unused library dependencies in key_gen

- src/lib/key_value_database/dune
> Clean up unused library dependencies in key_value_database

- src/app/zkapp_test_transaction/lib/commands.ml
- src/lib/snark_worker/prod.ml
- src/lib/transaction_witness/transaction_witness.ml
- src/lib/transaction_witness/transaction_witness.mli
This is a **mostly no-op** modification that is required for future switch of zkapp_command types.
Checklist:
> Separate transaction_witness stable/regular types

- src/app/zkapp_test_transaction/lib/commands.ml
- src/lib/graphql_lib/transaction/graphql_scalars.ml
- src/lib/mina_graphql/itn_zkapps.ml
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/mina_graphql/types.ml
- src/lib/transaction/transaction_id.ml
This is a no-op change which prepares codebase for future switch of zkapp_command types.
Checklist:
> Update graphql code to use stable zkapp_command

- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_lib/mina_lib.mli
- src/lib/network_pool/indexed_pool.ml
- src/lib/network_pool/intf.ml
- src/lib/network_pool/transaction_pool.ml
This commit is a **mostly** no-op change, but prepares for the future switch of types.
Contains a minor change to the logging format.
Checklist:
> Use Zkapp_command.Stable.Latest in network_pool

- src/app/cli/src/init/client.ml
- src/app/cli/src/init/itn.ml
- src/lib/filtered_external_transition/filtered_external_transition.ml
- src/lib/integration_test_lib/graphql_requests.ml
- src/lib/integration_test_lib/wait_condition.ml
- src/lib/mina_base/test/zkapp_command_test.ml
- src/lib/mina_commands/mina_commands.ml
- src/lib/snark_worker/prod.ml
A batch of unrelated changes in preparation of removing hashes from Zkapp_command.Stable.Latest.t.
Checklist:
> Prepare for switch of zkapp_command types

- src/lib/staged_ledger/pre_diff_info.ml
- src/lib/transaction/transaction.ml
Relax types in two modules to make existing functions more polymorphic.
- Relax user command types in `Pre_diff_info`
- Relax types in `Transaction`
* Simple refactoring, no change to behavior or code structure
Checklist:
> Relax zkapp types in Transaction and Pre_diff_info

- src/lib/verifier/common.ml
- src/lib/verifier/dummy.ml
- src/lib/verifier/prod.ml
Simplify the verifier's logic (don't use integer tags), relax types in
Common.check.
Previous logic was unnecessarily complex, with returned types later ignored, complex logic of sorting instead of `map2_exn` etc.
* A refactoring, no behavior changes.
Checklist:
> Simplify code of verifier

- src/lib/mina_stdlib/dune
- src/lib/mina_stdlib/generic_set.mli
- src/lib/with_hash/dune
- src/lib/with_hash/with_hash.ml
- src/lib/with_hash/with_hash.mli
A new module With_hash.Set provides a set that uses `(_, _) With_hash.t`
as elements, using hash for operating the set (and ignoring the value).
A new module is added to Mina_stdlib.
The module provides an interface for general-purpose set (which may
not necessary be implemented via Comparable's Make).
* Only some new code is added in this PR, it'll be used in follow-up PRs
* The new code is a trivial re-package of Map interface, so tests are not necessary, provided a review is performed
Checklist:
> Add With_hash.Set module

- src/lib/network_pool/locally_generated.ml
- src/lib/network_pool/locally_generated.mli
- src/lib/network_pool/transaction_pool.ml
Introduce a separate type to manage `locally_generated_{un,}committed` fields of the transaction pool.
New module enforces types in a more strict and safer way.
Additionally, remove usage of hashtable based on transaction. Use a tree map built on `Transaction_hash.t` as a key.
This approach is more straightforward.
* This is a refactoring, no changes to behavior have been made
Checklist:
> Don't use hashmaps for Locally_generated maps

- src/app/test_executive/zkapps.ml
- src/app/zkapps_examples/test/big_circuit/big_circuit.ml
- src/app/zkapps_examples/test/empty_update/empty_update.ml
- src/app/zkapps_examples/test/tokens/tokens.ml
- src/app/zkapps_examples/tokens/zkapps_tokens.ml
- src/lib/mina_base/account_update.ml
- src/lib/mina_base/control.ml
- src/lib/mina_base/test/helpers/zkapp_cmd_builder.ml
- src/lib/mina_base/zkapp_command.ml
- src/lib/mina_generators/zkapp_command_generators.ml
- src/lib/mina_wire_types/mina_base/mina_base_control.ml
- src/lib/transaction/transaction_hash.ml
- src/lib/transaction_logic/mina_transaction_logic.ml
- src/lib/transaction_snark/test/access_permission/transaction_snark_test_access_permission.ml
- src/lib/transaction_snark/test/zkapp_preconditions/zkapp_preconditions.ml
- src/lib/transaction_snark/transaction_snark.ml
- src/lib/verifier/common.ml
- src/lib/zkapp_command_builder/zkapp_command_builder.ml
Introduce `Mina_base.Control.Poly` type.
Thijs will later allow us to have one control type that stores the proof, and another one that stores disk cache tag refering to the proof.
* A refactoring, no behavior changes.
Checklist:
> Introduce polymorphic type for Mina_base.Control

- src/app/cli/src/init/mina_run.ml
- src/app/heap_usage/values.ml
- src/app/test_executive/verification_key_update.ml
- src/app/test_executive/zkapps.ml
- src/app/zkapps_examples/test/actions/actions.ml
- src/app/zkapps_examples/test/add_events/add_events.ml
- src/app/zkapps_examples/test/calls/calls.ml
- src/app/zkapps_examples/test/initialize_state/initialize_state.ml
- src/app/zkapps_examples/test/tokens/tokens.ml
- src/app/zkapps_examples/tokens/zkapps_tokens.ml
- src/app/zkapps_examples/zkapps_examples.ml
- src/lib/mina_base/account_update.ml
- src/lib/mina_base/test/helpers/zkapp_cmd_builder.ml
- src/lib/mina_base/zkapp_call_forest.ml
- src/lib/mina_base/zkapp_command.ml
- src/lib/mina_generators/zkapp_command_generators.ml
- src/lib/mina_wire_types/mina_base/mina_base_account_update.ml
- src/lib/network_pool/indexed_pool.ml
- src/lib/network_pool/test/indexed_pool_tests.ml
- src/lib/snark_worker/functor.ml
- src/lib/transaction/transaction.ml
- src/lib/transaction_snark/transaction_snark.ml
- src/lib/verifier/common.ml
- src/lib/zkapp_command_builder/zkapp_command_builder.ml
Introduce `Mina_base.Account_update.Poly` type.
This will later allow us to have one account update type that stores the proof, and another one that stores disk cache tag refering to the proof.
* A refactoring, no behavior changes.
Checklist:
> Polymorphize Account_update

- src/lib/snark_worker/prod.ml
- src/lib/staged_ledger/check_commands.ml
- src/lib/staged_ledger_diff/diff.ml
PR introduces three changes which are very minor, and are needed to enable removal of intermediate hashes from definition of `Zkapp_command.Stable` types.
- Fully prepare for type decoupling in `Staged_ledger_diff`
- Change was introduced as a by-product of managing work in parallel branches, which are now merged to `compatible`
- Add missing `read_all_proofs_from_disk` in `Check_commands`
- Revert an unnecessary change from #16788
- Change was introduced as a by-product of managing work in parallel branches, which are now merged to `compatible`
* A small refactoring, no changes to behavior.
Checklist:
- Document test …
> Some changes required for hash removal from Zkapp_command.Stable

- src/lib/pickles/pickles_intf.mli
This is a noop change, aims to fix the inccorectly documented arg `override_wrap_domain`
> Fix `override_wrap_domain` document

- src/lib/crypto/kimchi_bindings/stubs/Cargo.lock
- src/lib/crypto/kimchi_bindings/stubs/Cargo.toml
Bumping up ocaml-gen to 1.0.0 and bumping up mina-signer/mina-poseidon to a no-std version.
- https://github.com/MinaProtocol/kimchi-stubs-vendors/pull/8
- https://github.com/MinaProtocol/mina/pull/16944
> Use no-std mina-poseidon and mina-signer

- src/app/archive/lib/processor.ml
- src/app/archive/lib/test.ml
- src/app/cli/src/init/itn.ml
- src/lib/staged_ledger/check_commands.ml
- src/lib/transaction/transaction_hash.ml
- src/lib/transaction/transaction_hash.mli
- src/lib/transition_frontier/transition_frontier.ml
Don't read proofs to compute transaction hashes.
It is achieved by relaxing signatures in implementation of `Transaction_hash`.
Also some functions names are updated to follow the latest naming convention.
- **Make hash_command and its variants polymorphic in proof**
- **Restrict types for hash_command and variants**
* Simple and straightforward refactoring of types
Checklist:
> Don't read proofs when computing transaction hash

- src/lib/mina_base/account_update.ml
- src/lib/mina_base/user_command.ml
- src/lib/mina_base/zkapp_command.ml
- src/lib/network_pool/batcher.ml
- src/lib/network_pool/batcher.mli
- src/lib/verifier/prod.ml
After switch to using proof cache tags in zkapp commands, it's useful to have two verifiable types: one without tags (which is serializable) and another that has proof tags, one that is easily convertable to `Zkapp_command.Valid.t`.
This commit introduces `User_command.Verifiable.Serializable.t` which contains proofs, and has `bin_io` derivation. At the same time `bin_io` is removed from the `User_command.Verifiable.t`, which later will start containing proof cache tags.
Full PR contents:
- **Introduce Account_update.map_proofs**
- **Remove of_sexp from Batcher.Transaction_pool**
- **Introduce User_command.Verifiable.Serializable.t**
* This is a refactoring, no behavior is changed.
Checklist:
- …
> Add User_command.Verifiable.Seriliazable

- src/lib/mina_base/user_command.ml
- src/lib/mina_base/zkapp_command.ml
- src/lib/network_pool/batcher.ml
- src/lib/network_pool/batcher.mli
- src/lib/network_pool/indexed_pool.ml
- src/lib/network_pool/indexed_pool.mli
- src/lib/network_pool/test/indexed_pool_tests.ml
- src/lib/network_pool/transaction_pool.ml
- src/lib/transaction/transaction.ml
- src/lib/transaction/transaction_hash.ml
- src/lib/transaction/transaction_hash.mli
This PR is a series of the following changes:
- **Remove User_command_with_valid_signature.t_of_sexp**
- **Remove Transaction_hash.User_command_with_valid_signature.compare**
- **Remove Transaction_hash.User_command_with_valid_signature.hash**
- **Remove User_command.Valid.hash**
- **Remove User_command.Valid.compare**
- **Remove User_command.Valid.equal**
- **Remove t_of_sexp, of_yojson from User_command.Valid**
- **Remove unnecessary derivations from Zkapp_command.Valid**
All of the derivations are no longer necessary. The only usages that remained were in test and were not crucial to test implementation.
Checklist:
- Test names …
> Remove unnecessary derivations from valid command types

- src/lib/proof_cache_tag/dune
- src/lib/proof_cache_tag/proof_cache_tag.ml
- src/lib/proof_cache_tag/proof_cache_tag.mli
We need these derivations for debug output and logging for transactions.
For these purposes it would be a lot of changes to perform explicit conversions that replace proofs with `(unit)`.
And there will be little actual benefit.
The main usage of this will be debug printout of entire `Index_pool.t`. Because of layers of derivations, removing it would be a huge amount of work.
This change is introduced after it was established that it'll be used only for logging.
Checklist:
> Implement opaque sexp_of, to_yojson for proof_cache_tag

- buildkite/src/Command/DockerImage.dhall
- buildkite/src/Jobs/Release/MinaToolchainArtifactBullseye.dhall
- buildkite/src/Jobs/Release/MinaToolchainArtifactFocal.dhall
Small improvement for toolchain build. Do not start aptly in case of toolchain as they are not operating on debians
> [CI] do not start aptly if not needed

- buildkite/scripts/bench/run.sh
- buildkite/src/Command/Bench/Base.dhall
- scripts/benchmarks/lib/bench.py
- scripts/tests/ledger_test_apply.sh
Fixes corner case for benchmarks for which moving average has different than anticipated format. In some cases result is actual table which has correct length but there are few examples which has always 1. Safest is to always count records
As a result some benchmark did not performed requested comparision against reference data.
I also added switch to always use BUILDKITE_BRANCH when running in nightly and BUILDKITE_PULL_REQUEST_BASE_BRANCH on prs.
> [Benchmarks] Corner case fix for handling different  result from MA

- src/app/cli/src/init/mina_run.ml
- src/lib/cli_lib/render.ml
- src/lib/mina_base/test/zero_vesting_period.ml
- src/lib/mina_base/user_command.ml
- src/lib/mina_base/zkapp_command.ml
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/network_pool/indexed_pool.ml
- src/lib/network_pool/indexed_pool.mli
- src/lib/network_pool/intf.ml
- src/lib/network_pool/transaction_pool.ml
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/staged_ledger/staged_ledger.mli
- src/lib/transaction/transaction.ml
- src/lib/transaction_inclusion_status/transaction_inclusion_status.ml
- src/lib/transaction_inclusion_status/transaction_inclusion_status.mli
- src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
- src/lib/transaction_snark_scan_state/transaction_snark_scan_state.mli
- src/lib/transaction_witness/transaction_witness.ml
- src/lib/transaction_witness/transaction_witness.mli
- src/lib/uptime_service/uptime_service.ml
- src/lib/work_selector/inputs.ml
- src/lib/work_selector/intf.ml
- src/lib/work_selector/work_lib.ml
- src/lib/work_selector/work_selector.ml
- src/lib/work_selector/work_selector.mli
This PR removes a bunch of derivations that are not used in any way that matters.
Removing them eases path towards using proof cache tags in the `Zkapp_command.t`.
- **Remove of_sexp, of_yojson from User_command.t**
- **Remove Zkapp_command.hash derivation**
- **Remove Zkapp_command.compare derivation**
- **Remove Zkapp_command.equal derivation**
* Simple refactoring, no change of behavior.
Checklist:
> Remove unnecessary derivations from User_command.t

- src/app/cli/src/init/mina_run.ml
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/mina_graphql/types.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_lib/mina_lib.mli
- src/lib/snark_work_lib/work.ml
- src/lib/staged_ledger/staged_ledger.mli
- src/lib/transaction_inclusion_status/transaction_inclusion_status.ml
- src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
- src/lib/transaction_snark_scan_state/transaction_snark_scan_state.mli
- src/lib/uptime_service/uptime_service.ml
- src/lib/work_selector/inputs.ml
- src/lib/work_selector/intf.ml
- src/lib/work_selector/work_lib.ml
- src/lib/work_selector/work_selector.ml
- src/lib/work_selector/work_selector.mli
This PR changes the types for snark work while we're passing it around. Most importantly, this means that we aren't reading all of the proofs any time we enumerate the available work.
This PR addresses on [this review comment](https://github.com/MinaProtocol/mina/pull/16964#discussion_r2047380211) on PR #16964.
> Keep snark work proofs on disk until we actually need them

- buildkite/scripts/changelog.sh
- buildkite/scripts/generate-diff.sh
- buildkite/scripts/handle-fork.sh
- buildkite/scripts/merges-cleanly.sh
- buildkite/scripts/refresh_code.sh
- buildkite/scripts/version-linter-patch-missing-type-shapes.sh
- buildkite/scripts/version-linter.sh
Some external contributors are suffering from failing CI on their correct PRs, for example: https://github.com/MinaProtocol/mina/pull/16925
Origin of issue was my assumption when writing the code that forked repositories always have all mainline branches synced with ours. As a result we can rely on diffing base branch with head on forked repo alone not touching our repo in such comparision. In above case this assumption was proven wrong. Forked repositories does not have base branch (in this case compatible) , so git cannot find them and is erroring out. In buildkite we have 4 env vars which can help us identify PR from forked repository:
```
BUILDKITE_PULL_REQUEST_REPO="https://github.com/mrmr1993/mina.git"
BUILDKITE_REPO="https://github.com/MinaProtocol/mina.git" …
```
> [CI][FORK]  Revert REMOTE env var

- src/lib/pickles/compile.ml
- src/lib/pickles/compile.mli
- src/lib/pickles/inductive_rule.ml
- src/lib/pickles/inductive_rule.mli
- src/lib/pickles/pickles.ml
- src/lib/pickles/requests.ml
- src/lib/pickles/requests.mli
- src/lib/pickles/step.ml
- src/lib/pickles/step.mli
- src/lib/pickles/step_branch_data.ml
- src/lib/pickles/step_branch_data.mli
- src/lib/pickles/step_main.ml
- src/lib/pickles/step_main.mli
This PR changes `Pickles.Inductive_rule` from a module to the result of functor applied to an argument of signature
```ocaml
module type Proof_intf = sig
type 'width t
end
```
We can recover the existing implementation 
```ocaml
module Kimchi : Intf with type 'width proof = 'width Proof.t
```
We then functorize in as many places as possible to avoid specifying the proof type unless necessary. The result is that modules like `Step_branch_data` and `Step_main` are generic in the proof type (sort of), while e.g. `Compile` and `Pickles` explicitly rely on the concrete `Kimchi` inductive rule.
This PR is a no-op, only changes types. The diff is bad because of formatting (functorizing results in indentation). The only real changes are in
- …
> Functorize Pickles.Inductive_rule with Proof arg

- src/lib/base58_check/dune
Alphabetize library dependencies in src/lib/base58_check/dune file for better readability and maintenance.
> Alphabetize dependencies in base58_check dune file

- src/lib/mina_base/test/zkapp_account_test.ml
- src/lib/mina_base/zkapp_account.ml
- src/lib/mina_base/zkapp_command.ml
- src/lib/mina_generators/zkapp_command_generators.ml
- src/lib/transaction_logic/mina_transaction_logic.ml
This PR refactors definitions of Actions in a way that allows alternative definition of Actions.t type.
This is useul to store some auziliary hash information.
- **Make definition of Zkapp_account.Actions more explicit**
- **Add actions type variable to Account_update_body_components**
- **Change type of Zkapp_account.Actions**
- **Rollback addition of unit to Actions.t**
* Simple refactoring, no behavior changes
Checklist:
> Reorganize Actions in zkapp command

- src/lib/blockchain_snark/dune
Alphabetize library dependencies in src/lib/blockchain_snark/dune file for better readability and maintenance.
> Alphabetize dependencies in blockchain_snark dune file

- src/lib/blake2/dune
Alphabetize library dependencies in src/lib/blake2/dune file for better readability and maintenance.
> Alphabetize dependencies in blake2 dune file

- src/lib/block_producer/dune
Alphabetize library dependencies in src/lib/block_producer/dune file for better readability and maintenance.
> Alphabetize dependencies in block_producer dune file

- src/lib/bounded_types/dune
Alphabetize library dependencies in src/lib/bounded_types/dune file for better readability and maintenance.
> Alphabetize dependencies in bounded_types dune file

- src/lib/bowe_gabizon_hash/dune
Alphabetize library dependencies in src/lib/bowe_gabizon_hash/dune file for better readability and maintenance.
> Alphabetize dependencies in bowe_gabizon_hash dune file

- src/lib/cache_lib/dune
Alphabetize library dependencies in src/lib/cache_lib/dune file for better readability and maintenance.
> Alphabetize dependencies in cache_lib dune file

- src/lib/bootstrap_controller/dune
Alphabetize library dependencies in src/lib/bootstrap_controller/dune file for better readability and maintenance.
> Alphabetize dependencies in bootstrap_controller dune file

- src/lib/child_processes/dune
Alphabetize library dependencies in src/lib/child_processes/dune file for better readability and maintenance.
> Alphabetize dependencies in child_processes dune file

- src/lib/codable/dune
Alphabetize library dependencies in src/lib/codable/dune file for better readability and maintenance.
> Alphabetize dependencies in codable dune file

- src/lib/crypto/kimchi_backend/dune
- src/lib/crypto/plonkish_prelude/dune
Alphabetize library dependencies in the following dune files for better readability and maintenance:
- src/lib/crypto/kimchi_backend/dune
- src/lib/crypto/plonkish_prelude/dune
> Alphabetize dependencies in kimchi_backend dune file

- src/lib/crypto_params/dune
Alphabetize library dependencies in src/lib/crypto_params/dune file for better readability and maintenance.
> Alphabetize dependencies in crypto_params dune file

- src/lib/currency/dune
Alphabetize library dependencies in src/lib/currency/dune file for better readability and maintenance.
> Alphabetize dependencies in currency dune file

- src/lib/daemon_rpcs/dune
Alphabetize library dependencies in src/lib/daemon_rpcs/dune file for better readability and maintenance.
> Alphabetize dependencies in daemon_rpcs dune file

- src/lib/data_hash_lib/dune
Alphabetize library dependencies in src/lib/data_hash_lib/dune file for better readability and maintenance.
> Alphabetize dependencies in data_hash_lib dune file

- src/lib/direction/dune
Alphabetize library dependencies in src/lib/direction/dune file for better readability and maintenance.
> Alphabetize dependencies in direction dune file

- src/lib/downloader/dune
Alphabetize library dependencies in src/lib/downloader/dune file for better readability and maintenance.
> Alphabetize dependencies in downloader dune file

- src/lib/error_json/dune
Alphabetize library dependencies in src/lib/error_json/dune file for better readability and maintenance.
> Alphabetize dependencies in error_json dune file

- src/lib/fields_derivers/dune
Alphabetize library dependencies in src/lib/fields_derivers/dune file for better readability and maintenance.
> Alphabetize dependencies in fields_derivers dune file

- src/lib/pickles/README.md
- src/lib/pickles/snarky_tests/snarky_tests.ml
- src/lib/pickles/test/test_wrap.ml
- src/lib/transition_frontier/README.md
- src/lib/transition_frontier/extensions/extensions.mli
- src/lib/transition_frontier/frontier_base/root_data.mli
- src/lib/transition_frontier/full_frontier/full_frontier.ml
- src/lib/transition_frontier/persistent_frontier/sync.mli
- src/lib/transition_frontier/transition_frontier.ml
Tired of seeing bots.
Close https://github.com/MinaProtocol/mina/pull/16975
> Fix typos with codespell in pickles and transition_frontier

- src/lib/fields_derivers_graphql/dune
Alphabetize library dependencies in src/lib/fields_derivers_graphql/dune file for better readability and maintenance.
> Alphabetize dependencies in fields_derivers_graphql dune file

- src/lib/fields_derivers_json/dune
Alphabetize library dependencies in src/lib/fields_derivers_json/dune file for better readability and maintenance.
> Alphabetize dependencies in fields_derivers_json dune file

- src/lib/fields_derivers_zkapps/dune
Alphabetize library dependencies in src/lib/fields_derivers_zkapps/dune file for better readability and maintenance.
> Alphabetize dependencies in fields_derivers_zkapps dune file

- src/lib/file_system/dune
Alphabetize library dependencies in src/lib/file_system/dune file for better readability and maintenance.
> Alphabetize dependencies in file_system dune file

- src/lib/filtered_external_transition/dune
Alphabetize library dependencies in src/lib/filtered_external_transition/dune file for better readability and maintenance.
> Alphabetize dependencies in filtered_external_transition dune

- src/lib/gadt_lib/dune
Alphabetize library dependencies in src/lib/gadt_lib/dune file for better readability and maintenance.
> Alphabetize dependencies in gadt_lib dune file

- changes/16974.md
- src/lib/mina_lib/conf_dir.ml
The daemon lockfile `.mina-lock` is created in the config directory used by a running daemon. It contains the PID of the running daemon, and a daemon with the same PID as in the lockfile is said to own (have acquired) that lockfile. This file is used to exclude other daemons from starting up in the same config directory; if the lockfile exists and is owned by another process then new daemons will refuse to continue startup once they see it. This file is normally deleted during daemon shutdown. However, if a daemon crashes or is killed, then it may not have a chance to delete this file before it exits.
If a new daemon starts up and finds that a daemon lockfile exists but is not owned by any process (meaning there is no running process with the same PID as is recorded in the lockfile) then …
> Ensure daemon acquires the daemon lockfile after cleaning up a stale lockfile

- scripts/debian/builder-helpers.sh
- scripts/debian/reversion.sh
This is simply copy/pasting the version from compatible, to not have any conflict anymore.
> scripts/debian: use compatible version

- buildkite/scripts/refresh_code.sh
- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
Some guys are experiencing issue when running CI with non mainline branches as base. For example:
https://github.com/MinaProtocol/mina/pull/17040
This PR is fixing above issue by fetching before refering to base branch. 
I've tested my solution here: https://github.com/MinaProtocol/mina/pull/17042
> Fix refresh code on non mainline branch pr

- src/app/cli/src/init/client.ml
- src/app/cli/src/init/graphql_client.ml
- src/lib/graphql_lib/client.ml
- src/lib/integration_test_lib/graphql_requests.ml
- src/lib/snark_worker/standalone/run_snark_worker.ml
This PR removes the `Make` functor from Graphql_lib/Client that was always called with the same argument (aka `Fn.id` and `Map.empty`).
> Defunctorize Graphql client

- scripts/tests/ledger_test_apply.sh
- src/app/cli/src/init/client.ml
- src/app/cli/src/init/test_ledger_application.ml
- src/lib/transaction_snark/transaction_snark.ml
- src/lib/transaction_snark/transaction_snark_intf.ml
The `mina ledger test apply` command and the `scripts/tests/ledger_test_apply.sh` script now recognize the flag `--transfer-parties-get-actions-events`. When set, the commands used in the test are generated so that every account update in those commands has their actions and events filled completely. This is 100 actions and 100 events in each update with the current genesis constants. Otherwise, these fields are left empty. By default, the flag is off (matching the current behaviour).
To support this change, a new `signature_transfers` command generator and associated spec have been added to `Transaction_snarks.For_tests`. These generalize the existing `multiple_transfers` command generator by allowing receivers and the sender to have their actions and events filled with the spec actions …
> Modify mina ledger test apply to allow for filled actions and events in updates

- nix/README.md
openvsix domain is down. Redirecting users to official version only
> Removed broken openvsix link:

- changes/17091.md
- src/lib/mina_intf/transition_frontier_components_intf.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_lib/tests/tests.ml
- src/lib/transition_frontier_controller/dune
- src/lib/transition_frontier_controller/transition_frontier_controller.ml
- src/lib/transition_handler/dune
- src/lib/transition_handler/processor.ml
- src/lib/transition_router/dune
- src/lib/transition_router/transition_router.ml
This PR expose the transaction pool to `Transition_handler.processor`, so when it's building a breadcrumb, it would be able to query the pool for already verified proofs, so to save time on actually verifying the commands.
One refactor that make this possible is we lift `Transaction_pool_proxy` to to level as it's own module, so we could handle the dependency issue rather than wiring everything together.
> Wire transaction pool proxy in txn handler

- nix/README.md
We do want to keep a reference to the opensource package. As it became available again this reverts "Removed broken link:"
This reverts commit 3a44c8d195f190ce3df3c664456022f8bcb8c6cd.
> Restoring openvsix link:

- src/lib/transaction_snark/dune
Initially I wanted to be sure that zkapp_command_builder was unused to be sure that https://github.com/MinaProtocol/mina/pull/16965/files#r2059048486 was confirmed in transaction_snark. Re-ordered alphabetically at the same time.
> Transaction_snark/dune: remove useless dependency used for testing + reorder alphabetically

- src/dune-project
After https://github.com/MinaProtocol/mina/pull/17114, the `dune-project` entry for `snark_work_debugger` stopped referring to any local package. Removing entry resolves this error that would be emitted during `dune build`:
```
Error: The package snark_work_debugger does not have any user defined stanzas
attached to it. If this is intentional, add (allow_empty) to the package
definition in the dune-project file
-> required by _build/default/src/snark_work_debugger.install
-> required by alias src/all
-> required by alias default
```
I ran `dune build` locally and observed that the error disappeared.
> Remove obsolete snark_work_debugger dune project entry

- dockerfiles/Dockerfile-mina-rosetta
Cherry picking 99d307c51c1d50bb1bbd69cfb49ef205f3e11fc0
> Dockerfile/Rosetta: rosetta-sdk-go is now mesh-sdk-go

- opam.export
This dependency is unused anywhere in our code-base. Should be safe to remove them.
> Remove ppx fail

- src/app/cli/src/init/client.ml
- src/lib/hash_prefix_states/hash_prefix_states.ml
- src/lib/hash_prefixes/hash_prefixes.ml
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/signature_kind/compile_config/mina_signature_kind.ml
- src/lib/signature_kind/mainnet/mina_signature_kind.ml
- src/lib/signature_kind/mina_signature_kind.mli
- src/lib/signature_kind/testnet/mina_signature_kind.ml
- src/lib/signature_lib/schnorr.ml
This is the start of a series of PRs that will eventually remove the default compiled config `Mina_signature_kind.t` value from the code base completely, turning it into a completely runtime-configurable value.
This first PR only renames the value `Mina_signature_kind.t` to `Mina_signature_kind.t_DEPRECATED`, to make it clear during this ongoing refactoring that the value should not be used in new code, and to make my life a little easier during this refactor. Subsequent PRs will gradually replace the use of the value in functions with a `~signature_kind` parameter that can be set by the caller. This will push the deprecated value upward in the code base until we reach a point at which the signature kind can be determined by other means (with a runtime config value, or a hard-wired …
> Deprecate the use of compiled signature kind

- src/app/test_executive/zkapps.ml
- src/lib/hash_prefix_states/hash_prefix_states.ml
- src/lib/hash_prefix_states/hash_prefix_states.mli
- src/lib/hash_prefixes/hash_prefixes.ml
- src/lib/mina_base/account_update.ml
- src/lib/mina_base/zkapp_call_forest_base.ml
- src/lib/network_pool/transaction_pool.ml
- src/lib/signature_lib/schnorr.ml
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/transaction_snark/test/account_update_network_id/account_update_network_id.ml
- src/lib/transaction_snark/transaction_snark.ml
- src/lib/transaction_snark/transaction_snark_intf.ml
This PR follows https://github.com/MinaProtocol/mina/pull/17153 in the refactoring of the network/signature kind, making it a runtime-configurable setting. The terminology in the code base has been regularized, so the signature kind parameter is always called `~signature_kind` - certain instances were `~chain` previously - and the use of the deprecated compiled config signature kind has been pushed out of the `hash_prefixes.ml` and `hash_prefix_states.ml` files.
No behaviour has been changed.
> Regularize signature kind terminology, move deprecated value out of hash prefix modules

- scripts/update-opam-switch.sh
Ading a confirmation before deleting `_opam`. The script is called after every commnand in the Makefile.
Instead of changing the default behavior in the Makefile, I prefer to ask for confirmation before any removal.
It happened many times on my machine that I run a target and my local setup was removed.
> scripts/update-opam-switch: add confirmation before nuking _opam

- src/lib/mina_base/account_update.ml
- src/lib/mina_base/zkapp_call_forest_base.ml
- src/lib/transaction_snark/test/multisig_account/multisig_account.ml
- src/lib/transaction_snark/test/ring_sig.ml
This PR follows https://github.com/MinaProtocol/mina/pull/17171 in the refactoring of the network/signature kind, making it a runtime-configurable setting. This refactoring has been applied to `mina_base/account_update.ml`, removing the use of that deprecated compiled-config value from the modules in that file.
This PR only changes the interface of certain modules and does not change runtime behaviour.
> Move deprecated value out of account update

- src/lib/snark_work_lib/dune
- src/lib/snark_work_lib/result_without_metrics.ml
- src/lib/snark_work_lib/result_without_metrics.mli
- src/lib/snark_work_lib/snark_work_lib.ml
- src/lib/snark_work_lib/work.ml
This is a noop. I'm reorganizing Snark Work Lib, so it's cleaner when I'm introducing new types.
> Move Result_without_metrics to a separate file

- src/lib/mina_state/snarked_ledger_state.ml
- src/lib/mina_state/snarked_ledger_state_intf.ml
This function is needed for Subzkapp level snark works to be cachable. As in a snark worker the caching uses Statement rather than Statement with an Sok for keys.
> Snarked Ledger State: implement Full.Poly.drop_sok

- src/lib/ledger_proof/ledger_proof.ml
- src/lib/ledger_proof/ledger_proof.mli
- src/lib/snark_worker/prod.ml
- src/lib/verifier/dummy.ml
- src/lib/verifier/prod.ml
- src/lib/verifier/prod.mli
This PR removed `Ledger_proof.Prod` and lift it to top level. `Ledger_proof.t` and `Ledger_proof.Prod.t` are the exact same thing and there's no reason leaving them as 2 types.
> Lift `Ledger Proof Prod` to to level to avoid module alias

- src/lib/mina_stdlib/tests/dune
- src/lib/mina_stdlib/tests/main.ml
- src/lib/mina_stdlib/tests/time_test.ml
- src/lib/mina_stdlib/time.ml
This generic time span type is needed, as new snark worker would include a `span_since_unix_epoch` in the work spec. It represents the instant a snark work is issued. 
`Core_kernel.Time.Span` doesn't have a yojson implementation and `Core_kernel.Time` is not serializable(also we need to deal with timezone hassle if we use it). Hence I think this solution is simpler & better.
For tests, I think we're fine without test for this PR, but tell me if we should add tests. I think if we want any, it would be specifically on lossless round-tripping.
> Mina Stdlib: Add Time.Span

- dockerfiles/Dockerfile-mina-rosetta
Original issue was: 
```
github.com/coinbase/rosetta-sdk-go/types@v1.0.0: git init --bare in /root/go/pkg/mod/cache/vcs/b533490f0e0edb9a52f10692f73836419bd8db7ac5bda88f3c45fc77ca71fdd7: exec: "git": executable file not found in $PATH
```
Which was fixed by changing lib name from rosetta-sdk-go -> mesh-sdk-go. This unblocked rosetta docker build but caused another problem which is visible on 3 mainline branches at integration tests:
```
Command Failed: unable to create transaction: unable to sign payloads: unable to to sign payload: failed to parse signing payload: payment not found in signingPayload
🚨 Error: The command exited with status 1
```
(https://buildkite.com/o-1-labs-2/mina-mainline-branches-nightlies/builds/183#0196d740-fd12-40d1-9090-75205e843a5f)
Above fix is unfortunately …
> [Rosetta fix] Install git & revert rosetta -> mesh change

- src/lib/snark_work_lib/sub_zkapp_spec.ml
- src/lib/snark_work_lib/sub_zkapp_spec.mli
- src/lib/transaction_witness/transaction_witness.ml
- src/lib/transaction_witness/transaction_witness.mli
This PR is part of the project Snark Worker Rework.
This PR implements subzkapp spec, which is either a Merge or a Segment. Later Snark Coordinator could distribute such spec as an option.
> Snark Work Lib: Implement Subzkapp Spec

- src/lib/snark_work_lib/id.ml
- src/lib/snark_work_lib/id.mli
This PR is part project of Snark Worker Rework.
This PR defines 2 kinds of ID, `Single` and `Sub_zkapp`; The first identifies a single spec; while the later identifies a subzkapp spec. 
The conversion between them is needed because we need to correspond a single zkapp command and the set of the subzkapp specs generated from that command.
> Snark Work Lib: define ID to be assigend to partitioned work

- flake.lock
- flake.nix
- nix/go.nix
- nix/misc.nix
- nix/ocaml.nix
- nix/rust.nix
Same changes as in #17192, against `develop`.
- **Pin rocksdb to 5.11.3 via old nixpkgs**
- **Use old nixpkgs to import Go 1.19**
- **Reformat rust.nix**
- **Use nixos-24.11-small**
- **Fix warning in ocaml.nix**
- **Fix warning in rust.nix**
> [Develop] Use nixos-24.11-small

- flake.lock
- flake.nix
- nix/go.nix
- nix/misc.nix
- nix/ocaml.nix
- nix/rust.nix
Use 24.11 channel instead of 23.11.
o1js is already on a newer channel, so it makes sense to update both.
Checklist:
> Use nixos-24.11-small

- src/lib/work_partitioner/id_generator.ml
- src/lib/work_partitioner/id_generator.mli
This PR is part of the project Snark Worker Rework.
ID generator is used so Work Partitioner could identify a spec, so it could know which job in the pool SNARK worker is submitting a result for. 
No interface is here because this is considered an internal detail of a work Partitioner.
> Work Partitioner: implement ID generator

- scripts/debian/builder-helpers.sh
Fix for focal debian package. 
Error at runtime when running mina from installed package
```
mina: error while loading shared libraries: liblmdb.so.0: cannot open shared object file: No such file or directory
```
This error is only observed at runtime. Reason is that we didn't add liblmdb-dev dependency to mina-daemon package. Unfortunately we didn't catch this earlier as focal debian is not used in tests (PR,Nightly). Also docker are not affected since we are installing 'dnsutils' which loads liblmdb-dev. 
Still this is a bit of mystery for me why bullseye debian is not affected
Reproduction path and test:
`docker run -it ubuntu:focal bash`
and then 
```
export DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC
apt-get update
apt-get install -y lsb-release ca-certificates
echo "deb [trusted=yes] …
```
> add liblmdb-dev to focal and bullseye dependency

- src/app/cli/src/init/mina_run.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_lib/mina_lib.mli
- src/lib/snark_work_lib/selector.ml
- src/lib/snark_work_lib/single_spec.ml
- src/lib/snark_work_lib/single_spec.mli
- src/lib/snark_worker/functor.ml
- src/lib/snark_worker/intf.ml
- src/lib/snark_worker/prod.ml
- src/lib/snark_worker/snark_worker.ml
After the snark worker rework, this function will likely to depend on more functions defined in Prod, specifically parts related to zkapp segments and merges.
Hence it make sense to put `perform` in `Prod` where there's related functions available.
> Snark Worker: move `perform` from {Functor -> Prod}

- src/lib/snark_worker/rpc_get_work.ml
- src/lib/snark_worker/rpcs.ml
- src/lib/snark_worker/snark_worker.ml
This PR lifted Rpc_get_work to its own self contained module, so when we're actually modifying the RPC, it can be all done in one file.
> Snark Worker: lift Rpc_get_work

- src/lib/snark_work_lib/single_result.ml
- src/lib/snark_work_lib/single_result.mli
This is the result for a One work distributed by the Work Selector. The reason for redefining this type(and the combined result type in next PR in train) is to eliminate some invalid value, e.g. for previous result we could have One metric with Two proofs, which doesn't make sense. 
Next in train https://github.com/MinaProtocol/mina/pull/17265
> Snark Work Lib: define single result

- changes/16722.md
- nix/rust.nix
- src/lib/crypto/kimchi_backend/common/dlog_plonk_based_keypair.ml
- src/lib/crypto/kimchi_bindings/js/bindings/prover-index.js
- src/lib/crypto/kimchi_bindings/js/test/bindings_js_test.ml
- src/lib/crypto/kimchi_bindings/stubs/Cargo.lock
- src/lib/crypto/kimchi_bindings/stubs/kimchi_bindings.ml
- src/lib/pickles/cache.ml
- src/lib/pickles/cache.mli
- src/lib/pickles/compile.ml
- src/lib/pickles/compile.mli
- src/lib/pickles/impls.ml
- src/lib/pickles/impls.mli
- src/lib/pickles/pickles.ml
- src/lib/pickles/pickles_intf.mli
- src/lib/pickles/test/test_wrap.ml
* Updated bindings (wasm, stubs, js) to include the `lazy_mode` flag at setup and prover index creation. 
* There's a [playground](https://github.com/MinaProtocol/mina/pull/17199/files) where we measured the memory impact of this flag, showing some savings at setup time.
Closes #[2006](https://github.com/o1-labs/o1js/issues/2006) (mina side https://github.com/o1-labs/o1js/issues/2073)
> WASM Memory boosting mode with lazy cache

- src/lib/bootstrap_controller/bootstrap_controller.ml
- src/lib/mina_metrics/mina_metrics.mli
- src/lib/mina_metrics/no_metrics/mina_metrics.ml
- src/lib/mina_metrics/prometheus_metrics/mina_metrics.ml
Problem: buffered pipe for bootstrap had no semantical value. It's built
on top of an already-existing buffered pipe in the router.
Solution: use synchronous pipe.The only behavior change is that some
transitions that would otherwise be dropped when boostrap would've
finished will be transfered instead to the succeeding transition
frontier pipe.
* Relying on existing tests
* Semantics didn't change a lot, so no surprises are expected
Checklist:
> Make sync ledger pipe synchronous

- src/lib/bootstrap_controller/bootstrap_controller.ml
Move the main cycle of bootstrap out of `run` function.
Conflicts with PR #15921, taking a more conservative approach to refactoring. This is a first step to split out parts of bootstrap to incrementally smaller pieces, and then adopting some ideas from #15923 to make code's semantics clearer.
This is a no-op code refactoring.
Checklist:
> Small refactoring for bootstrap controller

- src/lib/snark_work_lib/snark_work_lib.ml
- src/lib/snark_worker/prod.ml
- src/lib/uptime_service/uptime_snark_worker.ml
This would conflict with https://github.com/MinaProtocol/mina/pull/17275, but conflicts are not terribly hard to resolve.
This type is just `Snark_work_lib.Spec.Single`(or `Snark_work_lib.Selector.Single.Spec`). Redundant.
A general question: Is there any point supporting both yojson & sexp as debugging dump format? Could we get rid of sexp?
> Snark Worker: Remove Prod.single_spec

- dockerfiles/Dockerfile-mina-archive
- dockerfiles/Dockerfile-mina-daemon
- dockerfiles/Dockerfile-mina-rosetta
- dockerfiles/Dockerfile-mina-test-suite
- dockerfiles/Dockerfile-txn-burst
- dockerfiles/Dockerfile-zkapp-test-transaction
This PR works around an issue where Ubuntu Focal repositories do not respond to HTTP requests. It does it by switching to `https` all apt sources used to fetch dependencies.
> Focal https

- src/lib/snark_work_lib/partitioned_result.ml
- src/lib/snark_work_lib/partitioned_result.mli
- src/lib/snark_work_lib/partitioned_spec.ml
- src/lib/snark_work_lib/partitioned_spec.mli
This is the only type that would be passed across the network when snark worker returns. So I'll only remove spec in this. for other result it would be needed to still have spec in them so we can send them to network pool to further process.
Indeed stable types in those results need to go, will follow up in next PRs.
> Snark Work Lib: Drop spec in partitioned result

- src/app/archive/lib/processor.ml
- src/app/cli/src/init/client.ml
- src/app/replayer/replayer.ml
- src/app/zkapps_examples/calls/zkapps_calls.ml
- src/app/zkapps_examples/tokens/zkapps_tokens.ml
- src/app/zkapps_examples/zkapps_examples.ml
- src/lib/mina_base/test/helpers/zkapp_cmd_builder.ml
- src/lib/mina_base/test/verification_key_permission_test.ml
- src/lib/mina_base/test/zkapp_command_test.ml
- src/lib/mina_base/user_command.ml
- src/lib/mina_base/zkapp_call_forest.ml
- src/lib/mina_base/zkapp_command.ml
- src/lib/mina_generators/zkapp_command_generators.ml
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/network_pool/test/indexed_pool_tests.ml
- src/lib/network_pool/transaction_pool.ml
- src/lib/snark_profiler_lib/snark_profiler_lib.ml
- src/lib/snark_worker/prod.ml
- src/lib/staged_ledger_diff/diff.ml
- src/lib/transaction/transaction.ml
- src/lib/transaction_logic/mina_transaction_logic.ml
- src/lib/transaction_logic/transaction_applied.ml
- src/lib/transaction_logic/zkapp_command_logic.ml
- src/lib/transaction_snark/test/multisig_account/multisig_account.ml
- src/lib/transaction_snark/test/ring_sig.ml
- src/lib/transaction_snark/test/zkapp_payments/zkapp_payments.ml
- src/lib/transaction_snark/test/zkapp_preconditions/zkapp_preconditions.ml
- src/lib/transaction_snark/transaction_snark.ml
- src/lib/transaction_witness/transaction_witness.ml
- src/lib/zkapp_command_builder/zkapp_command_builder.ml
This PR follows https://github.com/MinaProtocol/mina/pull/17299 in the refactoring of the network/signature kind, making it a runtime-configurable setting. This refactoring has been applied to the final few files in `mina_base` still referencing the deprecated compiled-config value for the signature kind.
This PR only changes the interface of certain modules and does not change runtime behaviour, other than the slight difference that certain tests now always use the `Mina_signature_kind.Testnet` signature kind.
> Move deprecated value out of mina base

- changes/16853.md
- src/lib/merkle_ledger/converting_merkle_tree.ml
- src/lib/merkle_ledger/converting_merkle_tree.mli
- src/lib/merkle_ledger_tests/test.ml
- src/lib/merkle_ledger_tests/test/main.ml
- src/lib/merkle_ledger_tests/test_converting.ml
- src/lib/merkle_ledger_tests/test_database.ml
- src/lib/merkle_ledger_tests/test_mask.ml
- src/lib/merkle_ledger_tests/test_stubs.ml
- src/lib/mina_base/account.ml
- src/lib/syncable_ledger/test/test.ml
This PR introduces a converting merkle tree implementation. From the doc-comment:
```
(** Create a merkle tree implementation that proxies through to
[Primary_ledger] for all reads and writes, but also updates the
[Converting_ledger] on every mutation.
The goal of this is to make it easy to upgrade ledgers for breaking changes
to the merkle tree. A running daemon can use this to keep track of ledgers
as normal, but can also retrieve the [Converting_ledger] so that it may be
used for an automated switch-over at upgrade time.
*)
```
This mechanism forms the core of our automated ledger upgrades for hard-forks. I have tested this manually with
* the same `Converting_ledger` implementation as the `Primary_ledger` implementation, and confirming that the resulting hashes are identical
* a …
> Add an implementation of a `Converting_merkle_tree`

- dockerfiles/stages/1-build-deps
- dockerfiles/stages/2-opam-deps
We are experiencing issues with unvailable location for ocamlfind1.9.3 sources:
https://buildkite.com/o-1-labs-2/mina-toolchains-build/builds/168#019734d1-e310-4849-86b4-08555fb281e1
Quickest solution is to pin ocamlfind1.9.3 to alternative location advised on similar issue: 
https://github.com/ocaml/ocamlfind/issues/98#issuecomment-2678150397
> pin ocamlfind.1.9.3 to alt path until connectivity solved

- flake.lock
Now `nix develop mina#with-lsp` is failing due to we bumped OPAM repo but didn't update Flake lock. 
This PR regenerates `flake.lock` so we can use nix.
> update flake.lock for update in OPAM repo

- src/lib/mina_base/account_timing.ml
- src/lib/mina_base/test/main.ml
- src/lib/mina_base/test/slot_reduction_vesting_test.ml
Tests have been added to ensure that the vesting parameter update equations in the slot reduction MIP preserve the guarantees included in the MIP, namely that the minimum balance at the hardfork slot itself is unchanged, and funds unlock at the same system times as they would have had the hardfork not occurred.
I ran the tests manually and confirmed that they all passed.
(not applicable, I think)
> Add tests for the vesting update procedure

- src/lib/integers_stubs_js/test/dune
This test is somehow not enabled. renaming dune rule `executable -> test` will fix that.
> Enable integers_stubs_js test

- src/lib/merkle_ledger/converting_merkle_tree.ml
- src/lib/merkle_ledger/converting_merkle_tree.mli
- src/lib/merkle_ledger_tests/test_converting.ml
The new `create_with_migration` method for a `Converting_ledger` takes an empty secondary ledger and migrates the primary ledger's data to it before constructing the full `Converting_ledger`. This migration is necessary if an already-synced secondary ledger does not already exist for the primary ledger.
I've made it the caller's responsibility to provide an empty secondary ledger because we will want to use this to migrate a few different ledgers; I think it would be better to handle at the call site the task of detecting if a migrated already exists and/or providing database config.
I've added another very simple test in `merkle_ledger_tests/test_converting.ml`.
> Add create with migration for converting ledger

- src/lib/child_processes/child_processes.ml
The Async.Writer.save function uses with_file_atomic to ensure that a given string is always written to a file completely or not at all. However, if the ?fsync parameter for that function is set to false - the default, and what it was before these changes - the temp file that with_file_atomic creates may not be flushed to disk before being moved to the target location. Thus, a well-timed interruption might cause the PID file to be created but be entirely empty. An empty PID file will cause this line to throw an exception:
https://github.com/MinaProtocol/mina/blob/2a9d6219863c13ddea4185aec9aa6378140ef0ca/src/lib/child_processes/child_processes.ml#L117
because the empty string cannot be parsed as an `Int`. This crash was discussed in a [slack thread on the …
> Ensure PID lock files are synced to disk

- src/lib/concurrency/pipe_lib/swappable_strict_pipe.ml
- src/lib/concurrency/pipe_lib/swappable_strict_pipe.mli
- src/lib/transition_router/transition_router.ml
Previously introduced swappable pipe used o1trace, and the name is subsequently used for prometheus to generate metrics. 
We ensure names doesn't contain `-` or ` `, so prometheus are happy.
> Make prometheus happy with the metrics name

- src/app/replayer/replayer.ml
- src/app/zkapp_test_transaction/lib/commands.ml
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/mina_ledger/ledger.ml
- src/lib/mina_ledger/sparse_ledger.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/network_pool/test/indexed_pool_tests.ml
- src/lib/network_pool/transaction_pool.ml
- src/lib/snark_profiler_lib/snark_profiler_lib.ml
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/transaction_logic/mina_transaction_logic.ml
- src/lib/transaction_logic/test/protocol_config_examples.ml
- src/lib/transaction_logic/test/transaction_logic/transaction_logic.ml
- src/lib/transaction_logic/test/zkapp_logic.ml
- src/lib/transaction_logic/transaction_applied.ml
- src/lib/transaction_logic/zkapp_command_logic.ml
- src/lib/transaction_snark/test/account_timing/account_timing.ml
- src/lib/transaction_snark/test/fee_payer/fee_payer.ml
- src/lib/transaction_snark/test/util.ml
- src/lib/transaction_snark/test/zkapp_preconditions/zkapp_preconditions.ml
- src/lib/transaction_snark/transaction_snark.ml
- src/lib/transaction_snark/transaction_validator.ml
- src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
- src/lib/transition_frontier/full_frontier/full_frontier.ml
This PR follows https://github.com/MinaProtocol/mina/pull/17316 in the refactoring of the network/signature kind, making it a runtime-configurable setting. This refactoring has been applied to the `transaction_logic` package, removing the use of that deprecated compiled-config value from the modules in that package.
This PR only changes the interface of certain modules and does not change runtime behaviour, other than the slight difference that certain tests now always use the `Mina_signature_kind.Testnet` signature kind.
> Move deprecated value out of transaction logic

- buildkite/src/Jobs/Test/NixBuildTest.dhall
Previous bump on OPAM.export skipped nix build test completely. We should include that file so CI is ranned.
> Set Nix Dirty When to include `opam.export`

- dockerfiles/stages/1-build-deps
This should be inoffensive. This is mostly to get the latest features of OPAM, in case we need it.
> Docker: bump up OPAM version to 2.3.0

- dockerfiles/stages/1-build-deps-jammy
- scripts/docker/build.sh
Can be tested using `make CODENAME=jammy docker-build-toolchain`.
> Dockerfiles/scripts: adding jammy toolchain

- src/app/test_executive/block_production_priority.ml
- src/app/test_executive/block_reward_test.ml
- src/app/test_executive/chain_reliability_test.ml
- src/app/test_executive/dune
- src/app/test_executive/epoch_ledger.ml
- src/app/test_executive/gossip_consistency.ml
- src/app/test_executive/hard_fork.ml
- src/app/test_executive/medium_bootstrap.ml
- src/app/test_executive/mina_test_executive.opam
- src/app/test_executive/payments_test.ml
- src/app/test_executive/peers_reliability_test.ml
- src/app/test_executive/slot_end_test.ml
- src/app/test_executive/test_common.ml
- src/app/test_executive/test_executive.ml
- src/app/test_executive/zkapps.ml
- src/app/test_executive/zkapps_nonce_test.ml
- src/dune-project
This allows to have in the PATH the binary mina-test-executive when using `make
install`/`dune install`. The CI copies the binary `_build/default/src/app/test_executive/test_executive.exe` to
`mina-test-executive`, and this patch will help sharing the same configuration, locally and in the CI.
> Make mina test executive public

- src/lib/blockchain_snark/tests/dune
- src/lib/blockchain_snark/tests/test_blockchain_snark.ml
Simply regtest, and show how to use the `blockchain_snark` library.
> Blockchain_snark: add regtest for digest

- src/lib/disk_cache/test/README.md
- src/lib/disk_cache/test/dune
- src/lib/disk_cache/test/test_cache_deadlock.ml
- src/lib/disk_cache/test/test_cache_deadlock.mli
- src/lib/disk_cache/test/test_filesystem_deadlock.ml
- src/lib/disk_cache/test/test_lmdb_deadlock.ml
(This reproduction is complete, but I'm not sure this is the exact form a permanent test of this deadlock should take. I'm putting it up for people to take a look at it.)
We have been observing a problem in devnet where mina nodes occasionally become completely unresponsive, no longer emitting logs or responding to rpc calls like `mina client status`. We have gotten a couple of reproductions by connecting to devnet locally, which allowed us to collect this backtrace with gdb at the point the freeze occurred:
```
#0  0x00007ffff6e9bad0 in __pthread_mutex_lock_full () from /nix/store/p9kdj55g5l39nbrxpjyz5wc1m0s7rzsx-glibc-2.40-66/lib/libc.so.6
#1  0x00007ffff7f1f492 in mdb_txn_renew0 () from /nix/store/096qj8qh7f03lwlw2ha9d3p73dirdzi2-lmdb-0.9.33/lib/liblmdb.so
#2  0x00007ffff7f205bb in …
```
> Add tests reproducing a deadlock related to lmdb observed in devnet

- buildkite/scripts/run-test-executive-local.sh
And inline and gather `apt-get install` commands
> Buildkite/test-executive: remove reference to hashicorp

- src/lib/snark_worker/entry.ml
As title. 
I run into this sometimes when running snark coordinator
```
Error parsing command line:
unknown flag --log_json
For usage information, run
mina internal snark-worker -help
```
Here's the output of `mina internal snark-worker --help`
```
Snark worker
mina.exe internal snark-worker 
=== flags ===
--daemon-address HOST-AND-PORT         address daemon is listening on
(alias: -daemon-address)
[--config-directory DIR]               Configuration directory
(alias: -config-directory)
[--file-log-level LEVEL]               Set log level for the log file
(Internal|Spam|Trace|Debug|Info|Warn|Error|Faulty_peer|Fatal,
default: Trace)
(alias: -file-log-level)
[--log-json]                           Print log output as JSON (default:
plain text)
(alias: -log-json)
[--log-level LEVEL] …
```
> Snark Worker: fix incorrect CLI arg after hardfork localnet patch

- src/lib/logger/test/dune
- src/lib/logger/test/logger_test.ml
- Convert inline test to Alcotest format
- Update dune file to use test stanza instead of inline_tests
- Replace ppx_inline_test with alcotest library
- Maintain existing test functionality for log rotation
> logger: migrate inline tests to Alcotest

- src/lib/consensus/vrf/tests/test_consensus_vrf.ml
- Move at the top of the method declaration multiple local open statements
- Remove local open of Snark_params.Tick to be more explicit, and be consistent
in using full path or local open (full path used).
- Remove local open of Consensus_vrf and use full path
> Consensus_vrf/test: aesthetic changes

- buildkite/src/Command/DockerImage.dhall
Fixing CI issue in DockerImage.dhall. Old Standard variant was used instead of Devnet one
> [CI] convert standard to devnet handler

- src/libp2p_ipc/Makefile
Remove the polluting logs:
```
mkdir -p _codegen                            
capnp compile -oocaml:_codegen -I/home/fok/.gopath/pkg/mod/capnproto.org/go/capnp/v3@v3.0.0-alpha.5/std libp2p_ipc.capnp
kj/filesystem-disk-unix.c++:1690: warning: PWD environment variable doesn't match current directory; pwd = /home/fok/codes/o1-labs/mina
libp2p_ipc.capnp --> libp2p_ipc.mli libp2p_ipc.ml
for ext in ml mli; do mv _codegen/libp2p_ipc.$ext libp2p_ipc_capnp.$ext; done
rm -rf _codegen
make: 'libp2p_ipc_capnp.mli' is up to date.
```
> Makefile/libp2p: silent executed commands to clean stdout

- src/lib/disk_cache/lmdb/disk_cache.ml
This is a revamp of https://github.com/MinaProtocol/mina/pull/17469. 
With some rounds of review & misunderstanding. I realized the choose of DS and the name of that DS is not optimal. 
Hence a redesign, aiming at clarify the intention. 
------------
In our previous implementation, to avoid deadlock, all keys that are supposed to be removed from underlying LMDB cache is put in a hashset instead. On invoke of a `put`, if there's too many such keys, we'll call a round of clean up of all of those keys. 
For the keys returned by `put`, it was just a monotonically increasing integer.
----------
In this PR, we try to retrive keys from the hashset(replaced by a queue), so we can skip the cycle wasted to clean up any specific keys reused this way when we try to invoke a clean up. 
---------- …
> LMDB Cache: partially reuse GCed IDs so to save cycles on cleaning LMDB V2

- buildkite/scripts/release/manager.sh
- scripts/debian/builder-helpers.sh
- scripts/debian/reversion.sh
Fixing publishing debian package in mainline nightly. Two errors were found:
After we merged https://github.com/MinaProtocol/mina/pull/17513 it modifyes reversion.sh script, This change was not updated in my PR which was introducing  publishing post-job. This PR is fixing this situation. 
More sever issue, and this is a sweet information that we found this issue here. Publishing is generally disabled on nightly so we would find out this problem when releasing probably. 
Fix is to add lliblmdb0 to every debian
> Fix for publishing debian packages in nightly

- buildkite/src/Jobs/Lint/Bash.dhall
It does use an old version (0.7.1 - see [1]) in the CI as the Debian package is old. 0.7.1 is from 2021.
Running `make check-bash` for https://github.com/MinaProtocol/mina/pull/17525) is fine on my machine with `>= 0.8.0` but it seems to fail in the CI (see [this build](https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/3801/steps/canvas?sid=019809c8-bda9-451b-a8c3-82b7ba8cb30d))
[1]
```
Preparing to unpack .../shellcheck_0.7.1-1+deb11u1_amd64.deb ...
Unpacking shellcheck (0.7.1-1+deb11u1) ...
Setting up shellcheck (0.7.1-1+deb11u1) ...
```
> CI: use shellcheck 0.10.0

- buildkite/src/Command/Rosetta/Connectivity.dhall
- buildkite/src/Jobs/Release/MinaArtifactBookwormMainnetLegacyMainnet.dhall
- buildkite/src/Jobs/Release/MinaArtifactBookwormMainnetMainnet.dhall
- buildkite/src/Jobs/Release/MinaArtifactBullseyeMainnetLegacyMainnet.dhall
- buildkite/src/Jobs/Release/MinaArtifactBullseyeMainnetMainnet.dhall
- buildkite/src/Jobs/Release/MinaArtifactFocalMainnetLegacyMainnet.dhall
- buildkite/src/Jobs/Release/MinaArtifactFocalMainnetMainnet.dhall
- buildkite/src/Jobs/Release/MinaArtifactNobleMainnetLegacyMainnet.dhall
- buildkite/src/Jobs/Release/MinaArtifactNobleMainnetMainnet.dhall
- buildkite/src/Jobs/Test/ConnectToMainnet.dhall
- buildkite/src/Jobs/Test/RosettaMainnetConnect.dhall
Last PR for replayer profile fix on mainnet. Here, we are fixing profiles for mina artifacts jobs in a way, that profile matches network.
| Network | Profile |
|--------|--------|
| Mainnet | Mainnet |
| Devnet | Devnet |
| Berkeley | devnet | 
As a result archive docker will receive suffix similar to daemon
> Use Profile.Type.Mainnet in mainnet alike jobs

- buildkite/scripts/build-artifact.sh
- buildkite/src/Command/ArchiveNodeTest.dhall
- buildkite/src/Command/RunWithPostgres.dhall
- buildkite/src/Jobs/Test/ArchiveNodeTest.dhall
- changes/16329.md
- scripts/debian/builder-helpers.sh
- scripts/tests/archive-node-test.sh
- src/test/archive/archive_node_tests/archive_node_tests.ml
- src/test/archive/archive_node_tests/dune
- src/test/mina_automation/daemon.ml
- src/test/mina_automation/executor.ml
- src/test/mina_automation/fixture/archive.ml
- src/test/mina_automation/fixture/archive.mli
- src/test/mina_automation/network_data.ml
- src/test/mina_automation/psql.ml
- src/test/mina_automation/replayer.ml
- src/test/mina_automation/utils.ml
Introducing quick component test for archive node with mocked daemon which simulates sending precomputed blocks. Test scenario is easy:
- start archive node with runtime config (so genesis block will be included at startup)
- use mina advanced archive-blocks to send precomputed blocks to archive node
- validate all blocks are archived
- run replayer for consistency check
While developing thte test i introduced new mini framework for defining test case with setup i and tear down)
Test operates on new tiny framework for running tests with common setup and tear down linked in (https://github.com/MinaProtocol/mina/pull/16329)
> [Archive single node test] Implement archive test with mocked daemon

- src/lib/transaction_snark/test/util.ml
> Transaction Snark Test Util: use Testnet instead of t_DEPRECATED

- src/lib/merkle_ledger/database.ml
- src/lib/merkle_ledger/dune
- src/lib/merkle_ledger/intf.ml
- src/lib/merkle_ledger/location.ml
- src/lib/merkle_ledger/merkle_path.ml
- src/lib/mina_base/account.ml
- src/lib/mina_ledger/dune
- src/lib/mina_ledger/ledger.ml
Continuation of https://github.com/MinaProtocol/mina/pull/17379
Status: waiting for next round of review.
> Add converting ledger with test

- buildkite/scripts/release/manager.sh
- buildkite/src/Command/Packages/Publish.dhall
- buildkite/src/Jobs/Promote/AutoPromoteNightly.dhall
Small patch for CI publisher. When veryfing if debian is pushed correctly we omit suffix which is causing that  debian cannot be found.
I also joined publish and verify commands for debian, since there is no point in separating them like for dockers
> Support suffix for archive in CI publisher

- src/lib/merkle_ledger/converting_merkle_tree.ml
- src/lib/merkle_ledger/converting_merkle_tree.mli
- src/lib/merkle_ledger/test/test_converting.ml
- src/lib/mina_ledger/ledger.ml
The `With_database` functor adds creation and checkpointing operations to the converting merkle tree when the underlying ledgers are databases.
> Add With_database functor to converting merkle tree

- buildkite/src/Jobs/Test/HFTest.dhall
This pull request includes a single change to the `Pipeline.build` configuration in the `buildkite/src/Jobs/Test/HFTest.dhall` file. The `target` parameter has been updated from `Size.Small` to `Size.Integration`, use more powerful agent as test suffer with some instabilities
> use Integration agent size instead of small for hardfork test

- src/lib/block_time/block_time.ml
This is a simple improvement, as I see some logs are spitted to stderr instead of stdout, indicating we're not using logger.
> Block Time: don't use eprintf, use logger instead

- src/lib/bootstrap_controller/bootstrap_controller.ml
- src/lib/consensus/intf.ml
- src/lib/consensus/proof_of_stake.ml
- src/lib/genesis_ledger/genesis_ledger.ml
- src/lib/genesis_ledger/intf.ml
- src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
- src/lib/genesis_proof/genesis_proof.ml
- src/lib/merkle_ledger/test/test_converting.ml
- src/lib/mina_ledger/ledger.ml
- src/lib/mina_ledger/ledger.mli
- src/lib/mina_ledger/root.ml
- src/lib/mina_ledger/root.mli
- src/lib/mina_lib/mina_lib.ml
- src/lib/sync_handler/sync_handler.ml
- src/lib/transition_frontier/full_frontier/full_frontier.ml
- src/lib/transition_frontier/full_frontier/full_frontier.mli
- src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
- src/lib/transition_frontier/persistent_root/persistent_root.ml
- src/lib/transition_frontier/transition_frontier.ml
- src/lib/transition_frontier/transition_frontier.mli
A new Root mina ledger type has been created, to encapsulate the functionality of the snarked root ledger. A Root ledger is an unmasked, fully-committed and database-backed ledger that can be used as the base of a ledger mask tree. It is only possible to create these with a single backing database, for now; in a future update the root definition will be expanded so that they can be backed by a pair of stable and unstable account databases that are kept in sync by a converting merkle tree.
This new root ledger is also used to back non-ephemeral genesis ledgers. This will be important in the full ledger migration implementation (with a root backed by a converting database), as having a pre-migrated genesis available to construct the initial snarked root will greatly speed up snarked root …
> Abstract the snarked root ledger

- buildkite/scripts/tests/archive-node-unit-tests.sh
- buildkite/src/Command/Rosetta/Connectivity.dhall
- dockerfiles/Dockerfile-mina-rosetta
- scripts/tests/ROSETTA_TESTS.md
- scripts/tests/rosetta-connectivity.sh
- scripts/tests/rosetta-helper.sh
- scripts/tests/rosetta-load.sh
- scripts/tests/rosetta-sanity.sh
Extended rosetta sanity tests by adding optional load test for rosetta which takes 10 minutes (but its duration can be configured).
Load tests in order to gain sufficient randomness need quite many blocks/zkapps etc. So my idea was to use already synced rosetta with filled archive database. If we would like to run load test as a separate test we would need to sync it again, loosing CI time. At this moment we don't have assertion yet on memory consumption etc. We might want to add assertion on memory consumption on postgres database
Currently there is no assertion on memory consumption as we have still have memory leak. We can either wait for fix and add assertion, or let test failing. Alternatively we an set a very big threshold (~4 gb)
> [Rosetta] run load test after sanity 

- src/app/test_executive/block_production_priority.ml
- src/app/test_executive/block_reward_test.ml
- src/app/test_executive/chain_reliability_test.ml
- src/app/test_executive/epoch_ledger.ml
- src/app/test_executive/gossip_consistency.ml
- src/app/test_executive/hard_fork.ml
- src/app/test_executive/medium_bootstrap.ml
- src/app/test_executive/payments_test.ml
- src/app/test_executive/peers_reliability_test.ml
- src/app/test_executive/slot_end_test.ml
- src/app/test_executive/test_executive.ml
- src/app/test_executive/verification_key_update.ml
- src/app/test_executive/zkapps.ml
- src/app/test_executive/zkapps_nonce_test.ml
- src/app/test_executive/zkapps_timing.ml
- src/lib/network_pool/test/indexed_pool_tests.ml
- src/lib/signature_kind/dune
- src/lib/signature_kind/mina_signature_kind.mli
- src/lib/signature_kind/type/dune
- src/lib/signature_kind/type/mina_signature_kind_type.ml
- src/lib/testing/integration_test_lib/intf.ml
- src/lib/testing/integration_test_lib/test_config.ml
Along with change on push sig kind, I've also allow integ tests to accept a new `~config` as param, as it's used by various test already anyway.
> Push sig kind out of test executive & network pool test

- buildkite/Makefile
- buildkite/scripts/release/manager.sh
- buildkite/src/Jobs/Promote/AutoPromoteNightly.dhall
- scripts/debian/verify.sh
Added bookworm and noble debians or nightly publishing. 
Also fixed warning when dealing with repo public key: 
```
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
```
> [CI] support bookworm and noble in publishing

- src/app/cli/src/init/mina_run.ml
- src/lib/bootstrap_controller/bootstrap_controller.ml
- src/lib/consensus/intf.ml
- src/lib/consensus/proof_of_stake.ml
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/mina_graphql/types.ml
- src/lib/mina_ledger/root.ml
- src/lib/mina_ledger/root.mli
- src/lib/mina_ledger/sync_ledger.ml
- src/lib/mina_lib/tests/tests.ml
- src/lib/sync_handler/sync_handler.ml
As part of the hard fork automation, the epoch ledger snapshots will need to be available in migrated form when the hard fork config is generated. This is a preliminary change that modifies the epoch ledger snapshot code so they are handled as `Root` ledgers and not `Db` ledgers. When the `Converting_ledger` backing is added to `Root`, the snapshots (which are created by checkpointing the `Root`) will automatically be saved in both unmigrated and migrated form. The initial creation of the epoch snapshots (now done by `Ledger.Root.create_single`) will also need to change when that backing is added, based ultimately on the runtime flag enabling the hard fork automation feature.
The existing code expects to be able to construct a syncable ledger given an epoch snapshot, so the syncable …
> Use Root ledger in epoch snapshots

- src/lib/block_producer/block_producer.ml
The PR https://github.com/MinaProtocol/mina/pull/17605 was opened against `release/3.2.0` to fix https://github.com/MinaProtocol/mina/issues/17595. Those changes need to be ported to `compatible`. This PR does that, by reverting the same two commits:
- 84ffc7ecd420c6948898b858a4dc81624f762523
- 599ebf09d892c1e38a9aae556bcecf2cd0198a7f
that were contained in the PR https://github.com/MinaProtocol/mina/pull/16728.
> Port #17605 (block producer refactor revert) to compatible

- Makefile
- buildkite/scripts/build-artifact.sh
- buildkite/scripts/debian/install.sh
- buildkite/scripts/export-git-env-vars.sh
- buildkite/src/Command/DockerImage.dhall
- scripts/debian/build.sh
- scripts/debian/builder-helpers.sh
- scripts/debian/clear-s3-lockfile.sh
- scripts/docker/build.sh
- scripts/export-git-env-vars.sh
Enabling local dev build for major debians and dockers.
Goal of this PR is to make buildkite and local env build process more alike. Enabling developers to build debians and dockers locally without running CI. 
Refactor CI code a bit too. Removed duplication between setting env vars as well as exposed BUILD_DIR env var which may differ.
Example of usage in local dev (building archive):
```
(export OPAMSWITCH=4.14.2 DUNE_PROFILE=devnet && make build-archive && make build-archive-utils)
make debian-build-archive-devnet 
make docker-build-archive-devnet
```
> Enable local docker build on dev env

- scripts/debian/verify.sh
Remove [trusted=yes] tag when verfying debian repositories.
This will test a real user scenario, where no one is trusting our repository like packages.o1test.net.
Also please take a look at pages i created for each repository with guide how to install debians from stable/unstable/nightly
https://nightly.apt.packages.minaprotocol.com
etc.
> remove trusted tag when fetching debian packages from signed repos

- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
- src/app/cli/src/init/mina_run.ml
- src/app/cli/src/init/test_ledger_application.ml
- src/app/zkapp_test_transaction/lib/commands.ml
- src/lib/consensus/genesis_epoch_data.ml
- src/lib/consensus/intf.ml
- src/lib/consensus/proof_of_stake.ml
- src/lib/fake_network/fake_network.ml
- src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/mina_graphql/types.ml
- src/lib/mina_lib/tests/tests.ml
- src/lib/mina_state/genesis_protocol_state.ml
- src/lib/mina_state/genesis_protocol_state.mli
- src/lib/mina_state/protocol_state.ml
- src/lib/mina_state/protocol_state_intf.ml
- src/lib/network_pool/test/indexed_pool_tests.ml
- src/lib/network_pool/transaction_pool.ml
- src/lib/precomputed_values/precomputed_values.ml
- src/lib/prover/prover.ml
- src/lib/snark_profiler_lib/snark_profiler_lib.ml
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/transaction_snark/test/transaction_union/transaction_union.ml
- src/lib/transaction_snark/test/util.ml
- src/lib/transition_frontier/full_frontier/full_frontier.ml
- src/lib/transition_frontier/transition_frontier.ml
This is the PR for https://www.notion.so/o1labs/Improve-genesis-epoch-ledger-snapshot-creation-23fe79b1f91080299e0edd9bd7a7e21a
I did it slightly different in that: in Genesis_epoch_ledger, store `Genesis_ledger.Packed.t` instead of `Mina_ledger.Ledger.t`
This would allow access to any function in `Genesis_ledger.Packed`, with `populate_root` included. 
Nightly: https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/3852
^ Seems to be passing
> Improve Genesis Ledger Creation

- src/lib/consensus/proof_of_stake.ml
- src/lib/genesis_ledger/genesis_ledger.ml
- src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
- src/lib/mina_ledger/root.ml
- src/lib/mina_ledger/root.mli
- src/lib/mina_lib/tests/tests.ml
- src/lib/transition_frontier/full_frontier/full_frontier.ml
- src/lib/transition_frontier/persistent_root/persistent_root.ml
The Root.Config module defines how a Root ledger can be created. There are two independently varying options:
1. The directory_name to use for the database(s) backing the Root
2. The backing_type for the Root
Some methods have been defined on the abstract Config.t type, to represent common operations on the locations of the databases backing root ledgers. The intent is to support existing patterns in the ledger handling code (deleting the backing of a root ledger, testing if a backing already exists, creating a root ledger based on a particular directory name) while abstracting the filesystem details of the root ledger backing. This is necessary for the future converting merkle tree backing for root ledgers; the migrated database will need to be created, moved, and deleted properly, and …
> Define and use a Config.t type for Root ledgers

- src/dune-project
- src/lib/merkle_ledger/test/dune
Motivation: otherwise there is a circular package-to-package dependency
between merkle_ledger and merkle_mask because the tests in both packages
use libraries from the other.
This prevents building with granular nix (`nix build mina#exes.mina`).
Checklist:
> Make merkle_ledger_tests a separate package

- changes/17646.md
- src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml
- src/lib/runtime_config/runtime_config.ml
With the introduction of hardfork feature (in develop branch) of zkapp
`app_state` containing 32 elements, it's necessary for the
`runtime_genesis_ledger` to support padding the app state to necessary
length.
In future this flag will be replaced by a flag performing all the
necessary ledger transformations required for planned hardfork.
Checklist:
> Add a flag to pad app_state

- scripts/mina-local-network/mina-local-network.sh
Mina-local-network script is use to spawn local network on dev environment. Part of It is also used in lightnet docker ci build:
https://github.com/o1-labs/mina-lightnet-docker/blob/develop/scripts/spinup-testnet.sh
The problem is that  above script is a duplication of mina-local-network-script. Therefore in order to remove such, we are introducing demo mode in actual local-network-script. I've added new parameter --demo which is overriding default network behavior and allow to spin only one node which will play a role of seed/blockproduced and snarkworker in one.
> introduced demo mode for mina-local-network script.

- src/lib/mina_graphql/mina_graphql.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_lib/mina_lib.mli
- src/lib/runtime_config/runtime_config.ml
- src/lib/testing/integration_test_local_engine/mina_docker.ml
The inputs necessary to generate the hard fork daemon config and genesis ledgers will need to be available to other parts of the code base, so I have isolated that logic and moved it into `mina_lib`.
> Prepare fork config inputs in mina_lib

- Makefile
- buildkite/scripts/generate-genesis-config.sh
- scripts/debian/builder-helpers.sh
- scripts/hardfork/build-packages.sh
- scripts/hardfork/mina-verify-packaged-fork-config
Applied newest changes to makefile to allow locally build hardfork package.
How to test:
setup your opam using opam.export file.
```
opam switch create 
opam switch import opam.export
eval $(opam env)
```
then run build with some examples
```
DUNE_PROFILE=devnet OPAMSWITCH=4.14.2 BYPASS_OPAM_SWITCH_UPDATE=y  CONFIG_JSON_GZ_URL=https://storage.googleapis.com/o1labs-gitops-infrastructure/devnet/devnet-state-dump-3NL1tz1m4SY9eh1pGWo6B9ZAB64fz5WKXdyDhLJivZbXCU1P1SsP-9bce84dccd98c83b0e494daa356caee7713ff940db85bf1d6947c2ddc6864b93.json.gz NETWORK_NAME=devnet make hardfork-debian
```
> allow to build hf packages locally using Makefile

- src/lib/cache_dir/native/cache_dir.ml
Problem: On systems where `/tmp` is not provided and
a different `TMPDIR` is set, downloading ledgers will fail.
Solution: consider TMPDIR via using `Filename.temp_dir_name`
instead of explicit `/tmp`.
* Tested on a server with no `/tmp`, ledgers are loading well
Checklist:
> Consider TMPDIR in computing s3_install_path

- src/lib/mina_base/account.ml
- src/lib/mina_base/zkapp_account.ml
- src/lib/mina_base/zkapp_state.ml
A preliminary `Hardfork` variant of account types has now been defined, which can be used while developing the actual hard fork automation feature. I added the proposed zkapp state size increase in its definition to make it different from `Account.Stable.Latest.t`; this will be useful for testing the HF automation feature. This type can be edited as the actual account format/migration changes necessary for planned hard forks become known; it doesn't commit us to any changes.
The existing `Unstable` account type is unchanged, other than having it use `Stable.Latest`. I think it'll be useful to keep that `Unstable` type around for unit tests, and it will be simpler to manage if it's just equal in definition to `Account.Stable.Latest.t` but with an `unstable_field` that duplicates the nonce.
> Add a preliminary Hardfork variant to account types

- src/app/archive/cli/archive_cli.ml
- src/app/archive/lib/processor.ml
- src/app/archive_blocks/archive_blocks.ml
This PR pushed signature kind out of archive/lib/processor. 
This is a no-op PR, no functional change is expected.
> Push sig kind out of Archive.Lib.Processor

- scripts/debian/verify.sh
Small improvement for release manager script.  
If we are using unsigned repo we need to trust it. If repo is signed we are not using [trusted=yes]
> [Release] added trusted part in debian import if repo is unsigned

- src/lib/snark_work_lib/combined_result.mli
- src/lib/work_partitioner/combining_result.ml
This is needed for:
1. logging metrics after Snark Worker RPC protocol is updated
2. Push back completed but invalid snark works back to the work partitioner pool for rescheduling
> Pass back spec on successful result combination in partitioner

- src/lib/consensus/proof_of_stake.ml
- src/lib/merkle_ledger/converting_merkle_tree.ml
- src/lib/merkle_ledger/intf.ml
- src/lib/mina_ledger/root.ml
- src/lib/mina_ledger/root.mli
- src/lib/transition_frontier/persistent_root/persistent_root.ml
This function is only used in debug. It might have some unexpected behavior if we rely on it in our business logics when backing is converting root. Hence, it'd be better to just replace it with a `to_yojson` which is only used for debugging. 
Last in train: https://github.com/MinaProtocol/mina/pull/17669
> Remove Config.primary_directory in Root.Make(_).Config

- src/lib/merkle_ledger/any_ledger.ml
- src/lib/merkle_ledger/converting_merkle_tree.ml
- src/lib/merkle_ledger/database.ml
- src/lib/merkle_ledger/intf.ml
- src/lib/merkle_ledger/null_ledger.ml
- src/lib/merkle_mask/masking_merkle_tree.ml
This is a simpler alternative to https://github.com/MinaProtocol/mina/pull/17626. 
As in `Masking_merkle_tree.Make(_).Attached.commit` (see below) only `accounts` is committed in a `maps_t`, there's no point tracking other data. 
Last in train: https://github.com/MinaProtocol/mina/pull/17674
Next in train: https://github.com/MinaProtocol/mina/pull/17677
> Folding accounts across all ledger masks

- src/lib/genesis_ledger/genesis_ledger.ml
- src/lib/genesis_ledger/intf.ml
- src/lib/mina_ledger/root.ml
- src/lib/mina_ledger/root.mli
- src/lib/transition_frontier/persistent_root/persistent_root.ml
This method was supposed to be implementable in a more efficient way with a converting database backing. However, the most convenient way of doing that involves a different API, where the method is responsible for creating the destination database itself. If avoiding the re-hashing that Ledger_transfer does is found to be desirable then this new API can be implemented and used when populating a Root from genesis or a recovered potential snarked ledger.
> Remove transfer_accounts_with from Root

- buildkite/src/Command/MinaArtifact.dhall
- buildkite/src/Constants/Artifacts.dhall
- buildkite/src/Constants/DockerPublish.dhall
- buildkite/src/Entrypoints/GenerateHardforkPackage.dhall
- buildkite/src/Jobs/Release/MinaArtifactBullseyeMainnetMainnet.dhall
- buildkite/src/Jobs/Release/MinaArtifactFocalDevnetDevnet.dhall
- buildkite/src/Jobs/Release/MinaArtifactFocalMainnetMainnet.dhall
- scripts/docker/build.sh
- scripts/docker/helper.sh
Issue:
NIghtly build for 3 codename/network combination. Job requires env vars which were not provided. Root cause of issue is that we mixed old style hf with new auto hardfork package. 
Example:
https://buildkite.com/o-1-labs-2/mina-mainline-branches-nightlies/builds/529
Fixing nightly by differentiating two hardfork packages (auto and legacy):
- legacy - it's the hf package build using https://buildkite.com/o-1-labs-2/hardfork-package-generation-new
- auto -> we bake docker with two versions (legacy and new) and mina is automatically switching from old to new
Therefore i introduced two hf packages old fashion and new one so env vars for legacy one won't be required when running new on
> [Nightly fix] Introduce two hf packages 

- src/dune-project
- src/lib/block_producer/block_producer.ml
- src/lib/block_producer/dune
- src/lib/debug_assert/debug_assert.ml
- src/lib/debug_assert/debug_assert.mli
- src/lib/debug_assert/dune
- src/lib/merkle_mask/dune
- src/lib/merkle_mask/masking_merkle_tree.ml
- src/lib/mina_base/dune
- src/lib/mina_ledger/dune
- src/lib/mina_ledger/ledger.ml
- src/lib/mina_ledger/sparse_ledger.ml
- src/lib/transaction_logic/dune
- src/lib/transition_frontier/full_frontier/dune
- src/lib/transition_frontier/full_frontier/full_frontier.ml
- src/lib/transition_frontier/persistent_frontier/dune
- src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
I think the initial purpose of that library is introducing a virtual library and swap with unit implementation in release profile so we don't pay the cost on assertion. However using native assert gives us same result with `-noassert`. 
Right now it's just ident imeplementation meaning we always pay the assertion overhead.
The only useful one that could possibly benefit from virt library is `debug_assert_deferred` as assert can't be used along a Deferred.t, however, it seems that function is not invoked by any place.
> Remove debug_assert library and replace all use with native assert

- buildkite/src/Command/Packages/Publish.dhall
- buildkite/src/Constants/DebianChannel.dhall
- buildkite/src/Jobs/Promote/AutoPromoteNightly.dhall
Introduced 3 different publishing job per branch. This is solving issue where compatible branch is used for all three branches (develop,compatible,master) therefore we couldn't find master debian package
> [Nightly CI Fix] introduce one publish job per branch

- buildkite/scripts/bench/install.sh
- buildkite/scripts/connect/connect-to-network.sh
- buildkite/scripts/debian/start_local_repo.sh
- buildkite/scripts/debian/update.sh
- buildkite/scripts/dump-mina-type-shapes.sh
- buildkite/scripts/run-test-executive-local.sh
- buildkite/scripts/single-node-tests.sh
- buildkite/scripts/tests/ledger_test_apply.sh
- buildkite/scripts/version-linter.sh
- buildkite/src/Command/DockerImage.dhall
- buildkite/src/Jobs/Lint/Bash.dhall
- scripts/debian/builder-helpers.sh
- scripts/tests/archive-node-test.sh
Removes apt-get update from CI scripts. Introduced specialized update script which:
a) detect if we need to use sudo or not
b) can blacklist installed repos 
c) has verbose and dry run modes
By default it blacklist helm charts repo which is currently unavailable and causing disruption in CI.
In related PR Luis is removing such repo: https://github.com/MinaProtocol/mina/pull/17721
> replace apt-get update with specialized update script

- src/lib/network_pool/network_pool_base.ml
In this function local sink was named remotes and remote sink was named locals. this PR aims to fix that.
> Network Pool Base: fix misleading var name

- buildkite/src/Command/ArchiveNodeTest.dhall
- buildkite/src/Constants/DebianVersions.dhall
as title says. We experience hard to follow issue where Archive Node: Tests is soft failed and developer may missed the real reason for Performance tests to fail. They depends on successful run of Archive Node: Test job since it produces performance metric dump
> [CI] remove soft fail from archive node tests

- src/lib/snark_worker/prod.ml
- src/lib/work_partitioner/snark_worker_shared.ml
- src/lib/work_partitioner/work_partitioner.ml
- src/lib/work_partitioner/work_partitioner.mli
There is only a single error that may happen for this code path,
and wrapping it into the generic `Error.t` really makes it harder
to analyze the whole code around Snark work production.
So using a stricter type really helps.
* Refactoring, no testing required
Checklist:
> Use stricter error type in Work partitioner

- src/lib/child_processes/child_processes.ml
- src/lib/child_processes/tester.sh
This PR touches on Child process module:
- Simplifies use of Let_syntax with Async in some unit test 
- Fix a bug where output is not produced per line
- Do not repeatedly check for lockfile existence
Here's an example of failing dev unit test:
https://buildkite.com/organizations/o-1-labs-2/pipelines/mina-o-1-labs/builds/38968/jobs/01991f76-95ae-4b8e-851e-d2b686881d15/log
> Fix and prettify child processs unit tests

- src/lib/transition_frontier/persistent_frontier/database.ml
- src/lib/transition_frontier/persistent_frontier/database.mli
These code are there solely to maintain compatibility with old persistent frontier. 
With HF, we expect:
- daemon to restart in an intermediate release pre-HF
- daemon to use post-HF release after HF
That would completely make these migration code uncessary post-HF. Hence it's safe to remove them.
> Remove obselete code in persistent frontier post-HF

- buildkite/src/Constants/ContainerImages.dhall
- buildkite/src/Jobs/Release/MinaToolchainArtifactBookwormArm64.dhall
- buildkite/src/Jobs/Release/MinaToolchainArtifactNobleArm64.dhall
- changes/17709.md
- dockerfiles/Dockerfile-mina-daemon
- dockerfiles/Dockerfile-mina-rosetta
- dockerfiles/stages/1-build-deps
- dockerfiles/stages/1-build-deps-bookworm
- dockerfiles/stages/1-build-deps-jammy
- dockerfiles/stages/1-build-deps-noble
- dockerfiles/stages/3-toolchain
- scripts/docker/build.sh
Removed hardcoded amd64 or x86_64 segment in various paths to toolchain tooling. This enable other architectures as arm64 to be provided instead amd64.
However, there were some issues in consolidation of naming convention (canonical and debian alike) which lead to introduce both cases x86_64/arm64 and x86_64/aarch64 to satisfy every possible case
> [ARM64] unhardcode amd64 architecture in dockerfiles

- scripts/hardfork/run-localnet.sh
- scripts/prepare-test-ledger.sh
We are experiencing issues in hardfork test which were originally not easy to debug. Therefore we are adding exclusive check for them in hardfork integration test.
Mentioned issue is caused by lack of fairly new staking ledger, which is periodically dumped into mina-staking-ledgers bucket. prepare-test-ledger script is fetching staking ledger to current epoch. However if there is something wrong with dump, like new ledger is missing, and old ledger from 31-epoch is taken. This is causing problem when daemon wants to boot with such ledger as it is almost certain that old ledger has old format, therefore it won't be compatible with mina from compatible branch.
Leger is quite large, so the orginal root cause is well hidden in oversized mina log. Example of such error: …
> [HF] Guardian for not accepting too old ledger in prepare ledger script

- buildkite/scripts/release/manager.sh
- scripts/debian/publish.sh
- scripts/debian/verify.sh
addded jammy case when verify debian.
Fix lack of presence of --force-upload-debian. Previously it renders to '' which is wrongly treated as argument. Reverted change and disabled shellcheck 
There is no way to test the solution for anyone except release manager (who uses release/manager.sh script with debian and aws keys).
> [CI][Publishing]  Verify jammy. Fix lack of force parameter

- src/app/archive/archive_mainnet_signatures.ml
- src/app/archive/archive_testnet_signatures.ml
- src/app/archive/dune
This PR removes 2 executables. They are almost identical to what's being built with `archive.ml`(see [here](https://github.com/MinaProtocol/mina/blob/compatible/src/app/archive/archive.ml)). except they don't intercept versions.
> Remove specialized build for mainnet/testnet archives

- src/lib/mina_ledger/ledger.ml
- src/lib/mina_ledger/ledger.mli
- src/lib/mina_ledger/root.ml
- src/lib/mina_ledger/root.mli
We're intending to use the `Account.Hardfork.t` type to represent the upcoming hard fork account changes and migration, so this should be used in `Ledger.Root`.
> Use Hardfork account type in Root ledger

- buildkite/scripts/archive/upgrade-script-check.sh
- buildkite/scripts/changelog.sh
- buildkite/scripts/git/check-bypass.sh
- buildkite/src/Command/Rosetta/Connectivity.dhall
- buildkite/src/Jobs/Lint/ArchiveUpgrade.dhall
- changes/17713.md
- scripts/debian/builder-helpers.sh
- scripts/tests/rosetta-connectivity.sh
Adding test step to rosetta devnet connectivity test. 
We are checking if upgraded database is backward compatible and still can accept blocks from berkeley. We are also doing upgrade rollback couple times to ensure script won't cause irreversible changes
How to test:
Run locally script with some already built docker tag:
```
"scripts/tests/rosetta-connectivity.sh --network devnet--tag ${TAG} --timeout 900  --run-compatibility-test develop"
```
Where TAG can be for example : `3.3.0-alpha1-dkijania-archive-compatibility-test-8795846-bullseye-devnet`
Closes #17745
> [HF] test upgrade script on devnet

- buildkite/scripts/changelog.sh
- buildkite/scripts/git/check-bypass.sh
The script should exit, but moving some code to anther script resulting in it being in a subprocess. exit 0 doesn't work anymore. We need to manual detect that check works.
> fix bypass changelog

- src/app/test_executive/hard_fork.ml
- src/app/test_executive/peers_reliability_test.ml
- src/app/test_executive/verification_key_update.ml
- src/app/test_executive/zkapps.ml
- src/app/test_executive/zkapps_timing.ml
- src/app/zkapp_test_transaction/lib/commands.ml
- src/lib/mina_graphql/itn_zkapps.ml
- src/lib/network_pool/transaction_pool.ml
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/transaction_snark/test/account_timing/account_timing.ml
- src/lib/transaction_snark/test/account_update_network_id/account_update_network_id.ml
- src/lib/transaction_snark/test/fee_payer/fee_payer.ml
- src/lib/transaction_snark/test/zkapp_deploy/zkapp_deploy.ml
- src/lib/transaction_snark/transaction_snark.ml
- src/lib/transaction_snark/transaction_snark_intf.ml
So apparently, some methods in `Transaction_snark.For_test` are used out of unit test, e.g. test executive. 
Hence a push of sig kind out of these methods are need. So we can for example run mainnet artifacts with test executive.
> Fix test executive for mainnet build

- src/dune.linker.inc
* dune-linker target generates two conflicting targets if `DUNE_USE_DEFAULT_LINKER` is `y` and `lld` is available as a `bin` in the environment.
* The change is logic-only, `dune build` will fail otherwise (with an incorrect `dune` config error)
Checklist:
* Closes #0000
> fix: mutually exclusive dune linker clause

- changes/17874.md
- src/app/dump_blocks/dump_blocks.ml
- src/lib/consensus/proof_of_stake.ml
- src/lib/genesis_ledger/genesis_ledger.ml
- src/lib/genesis_ledger/intf.ml
- src/lib/genesis_proof/genesis_proof.ml
- src/lib/mina_lmdb_storage/block.ml
- src/lib/transition_frontier/full_frontier/full_frontier.ml
- src/lib/transition_frontier/full_frontier/full_frontier.mli
- src/lib/transition_frontier/persistent_root/persistent_root.ml
- src/lib/transition_frontier/persistent_root/persistent_root.mli
- src/lib/transition_frontier/tests/full_frontier_tests.ml
- src/lib/transition_frontier/transition_frontier.ml
- src/lib/transition_frontier/transition_frontier.mli
This PR is a revival of https://github.com/MinaProtocol/mina/pull/17659. (I was going to reopen that one, but github won't allow me to do that now that I've force-pushed to rebase the branch onto the latest `compatible` to fix the merge conflicts that have accumulated since I opened that one).
Instead of having a `populate_root` method to populate an existing, empty root ledger from genesis, the genesis ledger now has a `create_root` method. This method assumes the responsibility for creating the root ledger itself. This design allows the `create_root` method to checkpoint the genesis ledger directly when the genesis ledger is backed by a database, which is much faster than using the `transfer_accounts` method from the functor in `ledger_transfer.ml`. This should resolve …
> Rework, speed up root ledger population from genesis

- src/lib/transaction_witness/transaction_witness.ml
- src/lib/transaction_witness/transaction_witness.mli
- src/lib/work_selector/inputs.ml
- src/lib/work_selector/intf.ml
- src/lib/work_selector/random.ml
- src/lib/work_selector/random_offset.ml
- src/lib/work_selector/sequence.ml
- src/lib/work_selector/work_lib.ml
Add internal trace logging for snark work being added to the work selector, and then scheduled.
This would allow measurement of real time required to process SWs during experiments.
* To be tested on cluster
Checklist:
> Add additional SW internal trace logging

- scripts/tests/rosetta-load.sh
The postgres instance in the rosetta tests is exceeding the current default memory limit of 2500MB somewhat regularly; it seems as though it was close to this limit in past tests, and is now finally exceeding it. The limit is now temporarily 3000MB until we either decide that the memory usage is still fine, or we find out why the memory usage is increasing and fix that issue.
Waiting on nightly run: https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/3907
Some components of the nightly build seem to be failing for unrelated reasons (git issues). The connectivity tests did run, however, and the highest transitory memory value I saw was this:
```
2025-09-30 19:24:30 - 🔄 Current TPS: 2.99, 📈 Average TPS: 3.15, 📊 Total Requests: 1730
📊 Memory Usage:
- 🐘 PostgreSQL: 2654.4 MB
- 📦 …
```
> Increase rosetta test postgres memory threshold

- buildkite/src/Command/Rosetta/Connectivity.dhall
Skip running rosetta connectivity tests on develop branch (on any PR which target develop too).
Pr targets compatible as we are always merge up CI changes (i skipped master since it will be updated by compatible anytime soon)
> skip rosetta connectivity tests on develop
