- src/lib/transaction_snark/transaction_snark.ml
This PR
* swallows an overflow error that can't affect user commands, fixing #6028
* handles the other possible overflow location in line with what's done in the transaction logic
* adds a TODO for later reference.
Checklist:
> [Release] Fix overflows in the transaction snark

- buildkite/src/Command/DockerArtifact.dhall
Increased compute resources (4vcp => ~16vcpu) should hopefully reduce the runtime from ~1hr considerably.
Checklist:
> increase agent target sizing for docker artifact build job (medium -> xlarge)

- frontend/website-redesign/src/components/AlternatingRowsButton.re
- frontend/website-redesign/src/components/AlternatingSections.re
- frontend/website-redesign/src/components/BlogModule.re
- frontend/website-redesign/src/components/Button.re
- frontend/website-redesign/src/components/Contributors.re
- frontend/website-redesign/src/components/EmailInput.re
- frontend/website-redesign/src/components/FeaturedSingleRow.re
- frontend/website-redesign/src/components/Footer.re
- frontend/website-redesign/src/components/GenesisMemberProfile.re
- frontend/website-redesign/src/components/HomepageHero.re
- frontend/website-redesign/src/components/Nav.re
- frontend/website-redesign/src/components/ProfileHero.re
- frontend/website-redesign/src/components/SecuredBySection.re
- frontend/website-redesign/src/components/Summary.re
- frontend/website-redesign/src/components/WorkWithMina.re
- frontend/website-redesign/src/pages/Blog.re
- frontend/website-redesign/src/pages/Community.re
- frontend/website-redesign/src/pages/Demo.re
- frontend/website-redesign/src/pages/Genesis.re
- frontend/website-redesign/src/pages/GetStarted.re
- frontend/website-redesign/src/pages/Index.re
- frontend/website-redesign/src/pages/Tech.re
- frontend/website-redesign/src/pages/Testnet.re
And required, so all buttons are now valid on the site
> Button's href is a variant

- buildkite/scripts/generate-diff.sh
Rather than base Buildkite jobs executed against `develop` on `git ls-files` (all tracked files) for all jobs, this change enables basing the diff against the most recent successful Buildkite run if enabled.
_Testing:_ Buildkite CI
Checklist:
> enable incremental builds for buildkite's generate-diff script

- src/lib/ppx_register_event/register_event.ml
This fixes a bug with `ppx_register_event` yojson derivations for typed metadata.
> Fix register event yojson derivations

- frontend/ci-build-me/package.json
- frontend/ci-build-me/src/index.js
This PR updates the `ci-build-me` bot to use the new mina URLs so that it will work again.
Checklist:
> Fix ci-build-me bot

- buildkite/scripts/generate-diff.sh
- buildkite/src/Monorepo.dhall
Transfer Buildkite's BUILDKITE_INCREMENTAL environment variable trigger for incremental Buildkite `develop` builds into the Monorepo triage job container execution environment. Also, temporarily install necessary tooling `curl` and `jq` while a more suitable option w/r/t to the container env is investigated.
Checklist:
> add BUILDKITE_INCREMENTAL envVar to monorepo container runtime env

- Makefile
- src/app/cli/src/init/graphql_queries.ml
- src/lib/coda_base/fee_excess.ml
- src/lib/coda_base/pending_coinbase.ml
- src/lib/coda_base/permissions.ml
- src/lib/integration_test_cloud_engine/kubernetes_network.ml
- src/lib/pickles/dlog_main.ml
- src/lib/pickles/opt_sponge.ml
- src/lib/pickles/pairing_main.ml
- src/lib/pickles/step_main.ml
- src/lib/transaction_snark/transaction_snark.ml
Use the special `Boolean` binops from snarky, namely `&&&` and `|||`, so files can be processed by `bisect_ppx`.
Tested by running `make test-coverage`, and also `BISECT_ENABLE=YES DUNE_PROFILE=testnet_postake_medium_curves make build`.
The `graphql` ppx and `bisect_ppx` interact badly, generating code with type errors. Fortunately, there's a directive `@@@coverage exclude_file` that tells `bisect_ppx` not to instrument a file.
There are a couple of those added in the PR, marked with an explanatory comment.
This is the last bit of #6090, except for adding coverage results to CI.
> Use special Boolean binops

- scripts/compare_pr_diff_items.py
Swap `mina` for `coda` in the compare items script. The name difference caused `lint-opt` to fail in #6141.
> Use mina in compare items script

- buildkite/helm/README.md
- buildkite/scripts/helm-ci.sh
Also remove a few `echo` stmts used for debugging.
**Testing:** Buildkite CI - [positive case](https://buildkite.com/o-1-labs-2/mina/builds/3674#eedf3559-0b79-472d-892b-c98cde3a9399) | [negative-case](https://buildkite.com/o-1-labs-2/mina/builds/3673#f1bac1d0-e8db-4950-b169-8718a8faf16c)
Checklist:
> add || true to Chart.yaml find command since failures are expected and inconsequential

- src/app/replayer/replayer.ml
- src/app/replayer/sql.ml
The ledger hashes in the replayer did not match the staged ledger hashes seen in the daemon, after applying user commands. That was because the user commands were using a dummy memo, which affects the receipt chain hash in accounts in the ledger. Adding the memo when querying the archive db makes the hashes correspond.
Also, given a particular state hash, the set of user and internal command ids can also exist for blocks not in the block chain from that state hash. So query for the valid global slots corresponding to blocks along that chain, and filter out commands with global slots not in that set. Otherwise, the replayer may perform commands not along the desired chain.
Print all ledger hashes after all commands in a slot have been executed. We were printing hashes after each command, …
> Include memos in user commands in replayer

- src/lib/gossip_net/libp2p.ml
This PR explicitly passes the libp2p port as the address to listen on when configuring libp2p in the helper. When we don't do this, it seems to chose its own port arbitrarily.
Testing locally indicates that this fixes the transitive peers test.
Checklist:
> Specify that libp2p should listen on the libp2p_port

- frontend/ci-build-me/src/index.js
Currently the `console.error` call fails, leading to
```
16:57:38.722  Failed to trigger buildkite build for some reason:
16:57:38.723  HTTP 500: data is not defined
```
This was triggered by [this comment](https://github.com/MinaProtocol/mina/pull/6188#issuecomment-703759177), which failed to start CI for that PR.
Checklist:
> Log buildkite errors properly

- src/app/cli/src/coda.ml
- src/lib/block_time/block_time.ml
- src/lib/block_time/block_time.mli
This PR enables mutating the block time so that we can replay blocks through the block producer from a file and step the time accordingly.
Checklist:
> Allow updating time offset in block time

- graphql_schema.json
- src/app/cli/src/init/client.ml
- src/app/cli/src/init/graphql_queries.ml
- src/lib/block_time/block_time.ml
- src/lib/block_time/block_time.mli
- src/lib/coda_graphql/coda_graphql.ml
This PR adds a mechanism for dumping the current time offset and exposes it from GraphQL and CLI. This will be necessary for syncing to a peer that has replayed a chain as if it were producing blocks, since its time offset will be determined by the time it interpreted the last block in the chain.
Sample output:
```
$ _build/default/src/app/cli/src/coda.exe advanced time-offset -help
Get the time offset used by the daemon to convert real time into blockchain time
coda.exe advanced time-offset
=== flags ===
[-rest-server URI/LOCALHOST-PORT]  graphql rest server for daemon interaction
(examples: 3085 or
http://localhost:3085/graphql,
/dns4/peer1-rising-phoenix.o1test.net:3085/graphql)
(default: 3085 or
http://localhost:3085/graphql)
[-help]                            print this help text and …
```
> Add GraphQL, CLI endpoints for dumping the CODA_TIME_OFFSET

- src/lib/block_producer/block_producer.ml
- src/lib/coda_transition/external_transition_intf.ml
- src/lib/transition_frontier/frontier_base/breadcrumb.mli
This PR restructures the `Block_producer.run` function so that the logic is distinct from the error handling. This is a no-op, but makes it much easier to reason about what the actual logic is, and circumvents ocamlformat's aggressive indentation.
Checklist:
> Separate error handling from main logic in the block producer

- scripts/archive/build-release-archives.sh
Docker tags cannot contain the same character set as deb package versions so a DOCKER_TAG variant was created of VERSION.
Testing:  CircleCI
Checklist:
> fix docker tagging in archive build script

- buildkite/src/Command/DockerArtifact.dhall
- buildkite/src/Jobs/Release/CodaArtifact.dhall
- Also refactored the DockerArtifact::ReleaseSpec type's build_rosetta property to more closely match its purpose as a rosetta build override in the absence of a deploy env file or rosetta build envvar.
Checklist:
> update puppeteered docker image build dependency to build of daemon image

- src/lib/transition_router/transition_router.ml
This fixes a 'write to closed pipe' error where we were writing to
`transition_writer_ref`, then mutating it and `kill`ing all of the pipes
that the `Transition_frontier_controller` writes to when it goes to
handle the message.
The underlying error is that we were (correctly) closing the transition
frontier controller and opening a bootstrap controller, but
(incorrectly) sending the message to the writer pipe before updating it
to point to the bootstrap controller. This behaviour matches the
original version from pre-#3974.
*Edit: the diff is inflated by format changes; the [diff without whitespace changes](https://github.com/MinaProtocol/mina/pull/6357/files?diff=split&w=1) is much more indicative of what has changed.*
Checklist:
- …
> Write transition to bootstrap pipe if the transition is for bootstrap

- buildkite/scripts/publish-deb.sh
- scripts/archive/build-release-archives.sh
- scripts/publish-deb.sh
> re-add --lock flag to deb-s3 command

- src/app/cli/src/coda.ml
This PR adds a command `internal replay-blocks` to access the replay functionality in #6327. The command takes the same arguments as `client daemon`, plus an additional `-blocks-filename` argument with a path to the file containing the sexp-encoded blocks.
This PR has a large diff due to whitespace changes; I recommend viewing the diff with [whitespace changes hidden](https://github.com/MinaProtocol/mina/pull/6353/files?diff=split&w=1).
This was tested with blocks generated on a 100k accounts ledger. To run this test:
* modify the `ledger_depth` in `src/config/testnet_postake_medium_curves.mlh` to `17`
* compile a binary using that profile `DUNE_PROFILE=testnet_postake_medium_curves make build`
* create a runtime configuration file `config-100k.json` containing
```json …
```
> Command to replay saved blocks in block producer

- src/lib/coda_net2/coda_net2.ml
This PR stops the daemon from dying if libp2p_helper sends a line which is not valid JSON to stdout or stderr.
This partially mitigates the error seen on the testnet, so that we will hopefully get the full error message. Error there was
```
(monitor.ml.Error\n  (\"Yojson.Json_error(\\\"Line 1, bytes 0-33:\\\\nInvalid token 'panic: runtime error: invalid mem'\\\")\")\n  (\"Raised at file \\\"common.ml\\\", line 5, characters 19-39\"\n    \"Called from file \\\"lib/read.ml\\\" (inlined), line 1025, characters 3-39\"\n    \"Called from file \\\"lib/read.mll\\\", line 1109, characters 8-26\"\n    \"Called from file \\\"lib/read.mll\\\", line 1122, characters 6-26\"\n    \"Called from file \\\"src/lib/coda_net2/coda_net2.ml\\\", line 1396, characters 42-72\"\n    \"Called from file …
```
> Don't die on JSON parse errors from libp2p_helper

- buildkite/src/Command/Base.dhall
According to Buildkite's *agent exit code* documentation, job exit status of `1` is the most common error (which is also observably supported by "flakey" jobs throughout Coda's pipeline which generally fail with exit-code 1 and are resolved by a single retry.)
This change adds a single automatic retry for all jobs failing in this way as a first defense against flakey errors.
**Testing:** Buildkite linting + CI
**Checklist:**
> ensure single retry of all buildkite jobs exiting w/ code 1 (common error)

- src/lib/best_tip_prover/best_tip_prover.ml
Adds a fix for syncing during the first k slots
Existing code only sent over best_tips if it had a best tip with at least k blocks behind it. However this was not true during the first k blocks, despite best_tips at that time having a valid proof. 
This changes the behavior to check whether a best_tip either has k blocks behind it, or the root of the best_tip is the genesis state.
This should fix #6354
> add fix for syncing during first k blocks

- frontend/website-redesign/public/static/img/TestnetCopyBackgroundDesktop.jpg
- frontend/website-redesign/src/components/ButtonBar.re
- frontend/website-redesign/src/components/FeaturedSingleRow.re
- frontend/website-redesign/src/components/Footer.re
- frontend/website-redesign/src/components/ListModule.re
- frontend/website-redesign/src/components/TestnetRetroModule.re
- frontend/website-redesign/src/pages/Testnet.re
This PR implements the QA fixes as according to the UME design document. 
The following was addressed:
1. Testnet challenges: photo is not the correct one
2. Testnet challenges: teal button needs left-aligned type, arrow should center vertically
3. Test retros: headings of each retro, copy looks too heavy weight
4. Sections with large black buttons: Buttons as a unit should align with left and right margins. This would make each one wider which would accommodate text without changing vertical size of buttons.
5. Leaderboard: Too much spacing between leaderboard and the following module
6. Read More links: Orange arrows are too big
> Website: Testnet Fixes

- src/lib/coda_net2/coda_net2.ml
These errors show that there's something going wrong in libp2p_helper, likely an internal error. We should surface these at the 'error' level to ensure that they get picked up so we can fix them. See e.g. #6404.
Checklist:
> Trivial: Log libp2p_helper JSON parse errors at level error

- src/app/cli/src/tests/coda_delegation_test.ml
- src/lib/runtime_config/runtime_config.ml
Changes to f resulted in coda-delegation-test taking ~50 minutes. This speeds that back up by reducing some constants
> speedup delegation test

- src/app/replayer/replayer.ml
In the replayer, check that the chain leading to the target state hash includes the genesis block, which occupies global slot 0.
The replayer starts with a genesis ledger, and if we replay commands from some block other than the genesis block, we'd get an invalid ledger.
Deepthi observed an archive db with gaps in the parent ids, which made it possible to try to replay against an invalid chain. The nonce check prevented the replayer from proceeding, but the new check in this PR makes it evident what the problem is.
Tested against that archive db using a target state hash which started at such a gap, and also with target state hash which led back to the genesis block.
Also added another log to indicate the number of commands being replayed.
> Check for genesis block in replayer

- src/lib/coda_base/transaction_logic.ml
- src/lib/coda_base/transaction_validator.mli
- src/lib/transaction_snark/transaction_snark.ml
The timed account transaction unchecked/checked validators calculate a current minimum balance, in order to decide whether a transaction violates that minimum balance, and whether an account becomes untimed, in the case that min balance is 0.
The existing unit tests for the validators verified that the new timings agreed. This PR also compares the calculated minimum balances.
Many thanks to Matthew Ryan for help with getting the snarky-related code to run without error.
Part of #5993.
> Compare checked, unchecked min balances

- buildkite/scripts/helm-ci.sh
- buildkite/src/Jobs/Lint/HelmChart.dhall
- buildkite/src/Jobs/Release/HelmRelease.dhall
- buildkite/src/Jobs/Test/UnitTest.dhall
Avoids processing Helm charts incorporated into the Mina repo via a *coda-automation* submodule since these charts are not designed/implemented for release.
**Checklist:**
> only lint helm charts defined within mina (skip coda-automation charts to prevent release

- src/lib/integration_test_cloud_engine/cli_inputs.ml
Checklist:
Closes #0000
Closes #0000
> make the flag look at submodule by default

- buildkite/helm/buildkite-exporter/Chart.yaml
- buildkite/scripts/helm-ci.sh
- buildkite/scripts/unit-test.sh
- buildkite/src/Jobs/Release/BotArtifact.dhall
- buildkite/src/Jobs/Release/HelmRelease.dhall
- buildkite/src/Jobs/Release/LeaderboardArtifact.dhall
- frontend/bot/helm/Chart.yaml
- frontend/leaderboard/helm/Chart.yaml
- helm/archive-node/Chart.yaml
- helm/block-producer/Chart.yaml
- helm/seed-node/Chart.yaml
- helm/snark-worker/Chart.yaml
Release latest versions of Helm charts to the GCS hosted *coda-charts* repo.
**Checklist:**
> update helm chart versions

- src/lib/coda_graphql/coda_graphql.ml
We mustn't use the same name for multiple types. This fixes #6474.
Checklist:
> Rename NetworkPeer GraphQL type

- src/app/archive/archive_lib/processor.ml
- src/app/archive/archive_lib/test.ml
- src/app/archive/create_schema.sql
- src/app/cli/src/tests/coda_archive_processor_test.ml
- src/app/rosetta/lib/block.ml
This PR fixed the bug introduced in #6470. In #6470, I made parent_id of blocks table to be NOT NULL and this change caused the failure when trying to add genesis blocks because I didn't provide a way to work around genesis block in previous PR.
In this PR, I decided that genesis block's parent_id should reference itself. And we consider a block to be genesis block if its blockchain_length is 1.
I also commented out 1 unit test for archive node which attempts to delete blocks in archive node.
> Fix genesis block's parent_id in archive node

- scripts/rebuild-deb.sh
Delete keys instead of trying to use them in deb package. This can be removed to make a final build on master for 4.1 but at the moment the keys are getting in the way.
Checklist:
Closes #6498
> remove-keys-from-deb to remove CI lock contention

- src/lib/network_pool/dune
- src/lib/network_pool/transaction_pool.ml
Use a structured log for commands that are rejected from the transaction pool. That will make it easier to write integration tests that look for rejected commands with a particular failure.
> Transaction pool rejected command, structured log

- src/lib/network_pool/indexed_pool.ml
- src/lib/network_pool/indexed_pool.mli
- src/lib/network_pool/transaction_pool.ml
This PR uses the timed balance instead of the maximum balance when considering whether transactions are valid to include in the pool.
This likely would have prevented the issue that stalled the current testnet.
Checklist:
> Consider timed balance in the transaction pool

- src/lib/coda_net2/coda_net2.ml
This fixes a mismatch between the ocaml and go sides of the libp2p helper which was causing message validation to not work.
> libp2p fix

- src/lib/consensus/proof_of_stake.ml
Hoping will fix the following bug on q/a nets:
```
!!! (monitor.ml.Error Not_found
("Raised at file \"src/list.ml\" (inlined), line 838, characters 14-34"
"Called from file \"src/lib/sparse_ledger_lib/sparse_ledger.ml\", line 199, characters 4-61"
"Called from file \"src/lib/coda_base/sparse_ledger.ml\", line 613, characters 12-39"
"Called from file \"src/lib/staged_ledger/staged_ledger.ml\", line 1666, characters 4-133"
"Called from file \"src/lib/block_producer/block_producer.ml\", line 131, characters 8-112"
"Called from file \"src/lib/block_producer/block_producer.ml\", line 400, characters 14-354"
"Called from file \"src/lib/interruptible/interruptible.ml\", line 24, characters 23-26"```
Trying on a Q/A net now, hopefully will fix the error
Update: confirmed this is a fix on a q/a …
> Attempt to fix a bug in block production

- src/lib/staged_ledger/staged_ledger.ml
- src/lib/staged_ledger/staged_ledger.mli
- src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
- src/lib/transaction_snark_scan_state/transaction_snark_scan_state.mli
- src/lib/transition_frontier/frontier_base/breadcrumb.ml
- src/lib/transition_router/initial_validator.ml
We currently exit if we can't contact the verifier. This PR makes it so we log the failure but do not exit.
> remove exit on verifier failure

- src/config/test_postake_full_epoch.mlh
- src/config/testnet_postake_medium_curves.mlh
- src/lib/runtime_config/runtime_config.ml
The new snark lowers the snark production time on q/a nets from ~120-150 seconds to 55 seconds. This PR lowers the slot time given that. We may be able to lower even further once we know the block gossip time for our network.
> lower default slot time to 2 minutes

- src/lib/transition_frontier/transition_frontier.ml
- src/lib/transition_router/transition_router.ml
Currently on pickles-public nodes are taking a very long time after starting to resume normal operation. 
I believe the ultimate cause of this is before starting normal operation, we wait for both the loading of the on-disk frontier, and getting the "best tip" from 8 of our peers.
I have been observing a node for the past 45min or so after restarting. We log when both of the above have finished and we also log when a request errors out. From the observed logging behavior we can deduce
- It is not the case that both the on-disk frontier is loaded and all requests have finished
- 1 out of 8 requests errored out (so far) because no heartbeats were received on the rpc connection for 30s 
It does not seem possible to know (from logs at least) whether finishing is blocked on the on-disk …
> Let "best tip" rpc timeout when starting up

- src/config/test_archive_processor.mlh
The archive unit test  failure that we saw recently on circleci and buildkite is because the block_window_duration is too short.
The block_window_duration was 600 ms, which means 1 min = 100 slots. And initialization takes about 1 min, so the first block produced  by the block producer would definitely pass the first epoch.
> turn up block-window-duration for test-archive-processor profile

- src/lib/coda_net2/coda_net2.ml
- src/lib/coda_net2/coda_net2.mli
- src/lib/coda_networking/coda_networking.ml
- src/lib/gossip_net/libp2p.ml
Probably fixes our broken metric too
Tested locally using `scripts/run_local_network.sh`
```
{"timestamp":"2020-10-29 00:03:17.141612Z","level":"Info","source":{"module":"Coda_networking","location":"File \"src/lib/coda_networking/coda_networking.ml\", line 1076, characters 14-25"},"message":"Got extra $peers","metadata":{"host":"213.149.61.129","peer_id":"12D3KooWRUFRrozfqgXmiRkxE12GcQNWPiJFh9ewtFBFVgrkcNCc","peers":[{"host":"192.168.1.6","peer_id":"12D3KooWPNXP6VeajCXsCuyUZTXSzKQbw7r2j2BLJGLzanwnGWoU","libp2p_port":5007},{"host":"192.168.1.6","peer_id":"12D3KooWAoB9tp8qVvRce2uTQQRfhU3EG9twk9TmLD9ZE2KX9gqK","libp2p_port":6007},{"host":"127.0.0.1","peer_id":"12D3KooWRUFRrozfqgXmiRkxE12GcQNWPiJFh9ewtFBFVgrkcNCc","libp2p_port":4007}],"pid":8770,"port":4007}}
```
> Fix for get some extra peers

- dockerfiles/Dockerfile-coda-daemon
- dockerfiles/coda_daemon_puppeteer.py
- src/app/cli/src/coda.ml
- src/lib/logger/impl.ml
- src/lib/logger/impl.mli
- src/lib/ppx_coda/log.ml
- src/lib/transition_frontier/extensions/best_tip_diff.ml
Writing best tip logs to a different file `mina-best-tip.log`. This is to make it easier to collect the required logs from nodes  to determine the state to fork off of
Added a new log level `best_tip_diff` that is of  `Spam` level and  doesn't have source or module
Checklist:
Closes #0000
Closes #0000
> Best tip logs in a different file

- src/app/test_executive/block_production_test.ml
- src/app/test_executive/block_production_test_timed_accounts.ml
- src/app/test_executive/bootstrap_test.ml
- src/app/test_executive/mina_peers_test.ml
- src/app/test_executive/payments_timed_accounts.ml
- src/app/test_executive/send_payment_test.ml
- src/app/test_executive/test_executive.ml
- src/lib/integration_test_cloud_engine/kubernetes_network.ml
- src/lib/integration_test_cloud_engine/stack_driver_log_engine.ml
- src/lib/integration_test_lib/integration_test_lib.ml
- src/lib/integration_test_lib/test_error.ml
Add an integration test using timed accounts:
- send a payment that succeeds
- send a payment that fails because of a minimum balance violation
The sender and receiver are the same in both cases. The first payment should deplete the sender's balance to the point where the second payment fails.
The failing payment should trigger an error log from the transaction pool. We update integration test error reporting so that the presence of this log does not cause a test failure, but its absence does. Each integration test contains a list of structured logs `repr`s indicating expected test failures.
Originally, the plan was to add these payments to `Block_producer_timed_accounts`. Because of the size of the scan state with `testnet_postake_medium_curves`, producing a SNARKed ledger for that test …
> Timed account payment integration test

- frontend/website-redesign/src/components/AlternatingSections.re
reduces image sizes in the home page via changing the maxWidth and desktop size in the component
> Website improvements: reduce size of home page images 

- dockerfiles/Dockerfile-coda-daemon-puppeteered
Ensure coda branch arg is correctly exposed for usage. As indicated in Docker docs, "An ARG declared before the FROM instruction can’t be used after the FROM"
Checklist:
> fix daemon puppeteered image

- src/lib/block_producer/block_producer.ml
- src/lib/coda_transition/external_transition.ml
- src/lib/coda_transition/external_transition_intf.ml
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/staged_ledger/staged_ledger.mli
- src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
- src/lib/transition_frontier/frontier_base/breadcrumb.ml
- src/lib/transition_frontier/frontier_base/breadcrumb.mli
- src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
- src/lib/transition_handler/breadcrumb_builder.ml
- src/lib/transition_handler/processor.ml
This attempts to speed up the loading of the persistent frontier by skipping validation of the staged ledger after applying on disk transitions.
> do not verify scan statement while loading persistent frontier

- scripts/telemetry-crawl.py
Add a script to get the telemetries from all nodes reachable from a local Mina daemon.
```
usage: telemetry-crawl.py [-h] [--daemon-port DAEMON_PORT] [--executable EXECUTABLE]
Get telemetry data from all Mina nodes reachable from localhost daemon
optional arguments:
-h, --help            show this help message and exit
--daemon-port DAEMON_PORT
daemon port on localhost (default: 8301)
--executable EXECUTABLE
Mina program on localhost (default: coda)
```
Example output (piped through `jq`):
```json
{
"peer_ids_queried": 4,
"telemetries": [
{
"node_ip_addr": "136.25.135.80",
"node_peer_id": "12D3KooWAFFq2yEQFFzhU5dt64AWqawRuomG9hL8rSmm5vxhAsgr",
"peers": [
{
"host": "127.0.0.1",
"peer_id": "12D3KooWAsU3WkEh64zBwsVchhcDCUHJCEaxSyerVBgdHdzGycTr",
"libp2p_port": 6007
},
{
"host": …
```
> Telemetry crawler

- src/lib/consensus/proof_of_stake.ml
- src/lib/merkle_mask/maskable_merkle_tree.ml
Only accounts with a balance in the default token may stake. At two places in the code, the total currency was computed by summing all balances in a ledger, regardless of the token id.
After a hard fork, even the genesis ledger may contain accounts using a non-default token.
Change those computations to only include balances for accounts with the default token.
Reviewer: Do the "supply increase" amounts used to increase total currency elsewhere in the code always represent the default token?
> Default token contributes to total currency

- helm/archive-node/Chart.yaml
- helm/archive-node/templates/archive.yaml
- helm/block-producer/Chart.yaml
- helm/block-producer/templates/block-producer.yaml
- helm/seed-node/Chart.yaml
- helm/seed-node/templates/seed-node.yaml
- helm/snark-worker/Chart.yaml
- helm/snark-worker/templates/snark-coordinator.yaml
- scripts/archive/Dockerfile
Remove the command definition redundancy and instead rely on the default ENTRYPOINT set by an image.
Also this change enables `coda_daemon_puppeteered` images to be substituted in place of the generic daemon image within Helm daemon specs as the puppeteered image's custom ENTRYPOINT will be respected and not overridden.
**Checklist:**
> remove command overrides for Helm daemon container specs

- src/app/cli/src/coda.ml
- src/app/cli/src/tests/coda_worker.ml
- src/app/cli/src/tests/full_test.ml
- src/lib/consensus/intf.ml
- src/lib/consensus/proof_of_stake.ml
- src/lib/fake_network/fake_network.ml
- src/lib/file_system/file_system.ml
- src/lib/transition_frontier/tests/full_frontier_tests.ml
- src/lib/transition_frontier/transition_frontier.ml
Added genesis_state_hash to the uuid file
If the genesis state hash the daemon is running on doesn't match the one in the uuid file then remove the epoch ledgers corresponding to the uuids
Checklist:
Closes #0000
Closes #0000
> destroy persisted epoch ledgers when genesis state changes

- src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
Currently this is being run before any information is collected, so it's logging no information. This PR moves it so that the log will contain the actual information that we record.
Checklist:
> Trivial: Run Timer.log after aggregating timing information

- src/app/archive/archive_lib/processor.ml
- src/app/rosetta/lib/block.ml
In Rosetta, the SQL queries for blocks were missing the new epoch data columns. Added those in this PR.
Also, the recursive query for block height adds a recursion-stopper, because the genesis block's parent id is the block id.
> Rosetta, add epoch data columns to SQL

- src/lib/runtime_config/runtime_config.ml
This adds `slots_per_epoch` to the delegation test config file. This was missed as part of #6455, causing the ~1hr40 test runtimes that we've been seeing. Runtime should now be ~20 mins.
Checklist:
> Make delegation test fast again

- src/app/libp2p_helper/src/libp2p_helper/main.go
This PR modifies the log level of some logging subsystems in go to reduce the level of logspam.
* The active logging subsystems are now listed in the log at startup
* The currently active logging subsystems are enumerated and set an appropriate log level by this PR
- Any log level modified from the default is given a justification comment
- I have looked at the code for each subsystem to work out whether the log level can/should be changed
- Some of these decisions are subjective; I have erred on the side of minimising spam without losing information, but a few comments note where the level could be raised further.
This fixes #6517.
Checklist:
> Stop libp2p_helper logspam

- src/lib/parallel_scan/parallel_scan.ml
A unit test in `Parallel_scan` calls `bin_read` and `bin_write`. It was getting those from a `Stable.V1` module. 
Change those calls to use `Stable.Latest`, so the test will be kept up-to-date in the event of version changes.
Tested by running the unit tests.
> Parallel scan, use Latest module for bin_io

- src/lib/consensus/proof_of_stake.ml
replacing it with new uuids instead
Checklist:
Closes #6631
> don't fail on epoch_ledger.json read error

- src/lib/coda_net2/coda_net2.ml
This PR fixes #6425. It
* updates the go log message parser to accept fields in any order
* accepts additional fields that aren't in the OCaml type, storing them in a `metadata` object
- previously these fields would cause an error
- this object is passed to our logger, so the information is not lost
- the `error` property is special-cased to alias to `go_error`, to keep consistency with prior logs
* gives cleaner, more descriptive error messages than the generated ones when parsing errors occur
Checklist:
> More flexible, more detailed go log parsing

- src/lib/signature_lib/schnorr.ml
This PR modifies our schnorr signature to use the full output of the hash function as a challenge in the sigma protocol.
> use full field element for challenge in signature

- src/app/replayer/replayer.ml
- src/app/replayer/sql.ml
Use the slot number of the parent block for transaction application
Checklist:
Closes #0000
Closes #0000
> fix txn_global_slot in the replayer

- src/lib/network_pool/batcher.ml
This PR
* adds logging for the number of proofs in each batch when verifying
* adds an environment variable `MAX_VERIFIER_BATCH_SIZE` to set a maximum number of proofs to include in a batch
- this is deliberately undocumented while we collect data to work out whether this is necessary and/or what a good default would be
Checklist:
> Add logging for proof batch sizes, add MAX_VERIFIER_BATCH_SIZE envvar

- src/app/libp2p_helper/src/codanet.go
- src/app/libp2p_helper/src/libp2p_helper/main.go
- src/lib/coda_net2/coda_net2.ml
Tries triggering RPC for real with foundPeer on connect and disconnect
EDIT: Tested on `peering` network (which partially deployed). Confirmed that (1) the network peers metric increases (this means the callback is called properly). (2) the get some initial peers call is happening (3) it is successfully sending peers back to those that join on first connect and (4) there are no errors when trying to add those peers.
> Fix libp2p initial peers RPC is triggered now

- src/app/cli/src/coda.ml
- src/app/cli/src/init/client.ml
- src/lib/cli_lib/flag.ml
Change CLI docstrings to use `PUBLICKEY` uniformly. There had been a mix of that and `KEY`.
Fixed wording in `config-file` docstring.
> CLI docstring fixes

- src/lib/coda_base/account.ml
For timed accounts, there was a check that the balance was at least as great as the account's initial minimum balance.
That check is unneeded. The initial minimum balance is a floor on spending, but the account is not required to maintain that minimum balance.
> Timed accounts, don't check balance against minimum balance

- src/lib/blockchain_snark/blockchain.ml
- src/lib/blockchain_snark/blockchain.mli
- src/lib/transaction_snark/transaction_snark.ml
- src/lib/transaction_snark/transaction_snark.mli
This PR adds `of_yojson` derivers for the inputs to the transaction and blockchain snarks, so that we can reconstruct the input from logs.
Checklist:
> Trivial: add of_yojson derivers for snark inputs

- src/app/cli/src/coda.ml
- src/lib/ledger_proof/ledger_proof.ml
- src/lib/ledger_proof/ledger_proof_intf.ml
This PR allows us to run a standalone verifier against the given input. The input can be taken from the log metadata [here](https://github.com/MinaProtocol/mina/blob/6369885e2f84998106a4d43636ddb69cd27768ef/src/lib/network_pool/network_pool_base.ml#L112) from the snark pool.
Checklist:
> Add internal run-verifier command

- src/lib/logger/impl.ml
We escape `\` and `"` in our log messages even though Yojson already does it for us.
Before:
```ocaml
utop # Logger.info (Logger.create ()) "\"This is a test\\ This is also a test\"" ~module_:"" ~location:"";;
{"timestamp":"2020-11-16 23:56:29.508455Z","level":"Info","source":{"module":"","location":""},"message":"\\\"This is a test\\\\ This is also a test\\\"","metadata":{"pid":25491}}
- : unit = ()
```
The message string parses into `\"This is a test\\ This is also a test\"`.
After:
```ocaml
utop # Logger.info (Logger.create ()) "\"This is a test\\ This is also a test\"" ~module_:"" ~location:"";;
{"timestamp":"2020-11-17 00:03:43.969678Z","level":"Info","source":{"module":"","location":""},"message":"\"This is a test\\ This is also a test\"","metadata":{"pid":30766}}
- : unit = ()
``` …
> Trivial: Stop unnecessarily double-escaping log messages

- graphql_schema.json
- src/app/cli/src/coda.ml
- src/app/cli/src/init/client.ml
- src/app/cli/src/init/graphql_queries.ml
- src/lib/coda_graphql/coda_graphql.ml
- src/lib/coda_graphql/dune
- src/lib/coda_lib/coda_lib.ml
- src/lib/coda_lib/coda_lib.mli
- src/lib/coda_lib/conf_dir.ml
Add a new subcommand `export-logs` to `coda client`, which takes a `-tarfile` optional flag. The command creates a compressed tar archive in the `exported_logs` subdirectory of the config dir, which is created if it doesn't exist.
The `-tarfile` is a basename for the archive. If omitted, the current date and time to create the basename.
The logs are the `*.log` files at the root of the config dir. (I see other .log files in subdirectories, those could be added, if desired.)
Example:
```
$ coda client export-logs -tarfile my-logs -rest-server 8080 
Exported logs to /home/steck/.coda-config/exported_logs/my-logs.tgz
```
The implementation uses a GraphQL mutation, which returns the created tarfile. The mutation:
```graphql
exportLogs {
exportLogs {
tarfile
}
}
}
```
returns
```graphql …
```
> Export logs via CLI and GraphQL

- src/app/cli/src/coda.ml
- src/app/cli/src/init/coda_run.ml
- src/app/cli/src/tests/coda_worker.ml
Intended to address #6686.
I opted to only kill the child processes for now. Other solutions require changes of a higher surface area, and this *should* release enough memory in most situations. Some extra consideration I thought about, but have not yet convinced myself are necessary:
- graceful shutdown chains some deferred's after the children are killed, and children are non-gracefully SIGKILL'd; perhaps this whole routine should be made synchronous to avoid worries of other async jobs crashing prematurely
- not sure if it's necessary to sleep after sending the signals, to give the OS some time to free up process memory
I can't really test this since I have not reproduced the new out of memory crash condition.
> Kill child processes on shutdown

- src/allocation_functor.opam
- src/app/cli/src/init/client.ml
- src/app/cli/src/init/coda_run.ml
- src/lib/allocation_functor/dune
- src/lib/allocation_functor/functor.ml
- src/lib/allocation_functor/intf.ml
- src/lib/allocation_functor/table.ml
- src/lib/allocation_functor/table.mli
- src/lib/coda_metrics/coda_metrics.ml
- src/lib/coda_transition/dune
- src/lib/daemon_rpcs/daemon_rpcs.ml
- src/lib/transition_frontier/frontier_base/breadcrumb.ml
- src/lib/transition_frontier/frontier_base/breadcrumb.mli
- src/lib/transition_frontier/full_frontier/full_frontier.ml
- src/lib/transition_frontier/transition_frontier.ml
Initial implementation of the allocation functor, which (in the long term) aims to address #6719 and #3367. This PR only contains object counting and not lifetimes or any deeper memory statistics about objects. This PR also only wires this functor up for `Breadcrumb.t`, as that was an easy first target. Once this lands, I will expand the functionality of this pattern further and wrap more types with this functor.
The statistics computed by this pattern are available via the cli through `coda advanced object-lifetime-statistics` and prometheus metrics.
> Implement allocation functor, wire up cli command and metrics

- src/lib/transition_handler/breadcrumb_builder.ml
> Fix dangling_mask during catchup

- src/lib/allocation_functor/dune
- src/lib/allocation_functor/table.ml
- src/lib/allocation_functor/table.mli
- src/lib/coda_metrics/coda_metrics.ml
Implements the active lifetime quartiles for #6719.
Added unit tests and for sanity locally using the local network script.
> Compute object lifetime quartiles in allocation functor

- src/lib/marlin_plonk_bindings/stubs/src/index_serialization.rs
- src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_plonk_index.rs
- src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_plonk_oracles.rs
- src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_plonk_verifier_index.rs
- src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_urs.rs
- src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_plonk_index.rs
- src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_plonk_oracles.rs
- src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_plonk_verifier_index.rs
- src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_urs.rs
- src/lib/marlin_plonk_bindings/tweedle_fp_index/marlin_plonk_bindings_tweedle_fp_index.ml
- src/lib/marlin_plonk_bindings/tweedle_fp_plonk_verifier_index/marlin_plonk_bindings_tweedle_fp_verifier_index.ml
- src/lib/marlin_plonk_bindings/tweedle_fp_urs/marlin_plonk_bindings_tweedle_fp_urs.ml
- src/lib/marlin_plonk_bindings/tweedle_fq_index/marlin_plonk_bindings_tweedle_fq_index.ml
- src/lib/marlin_plonk_bindings/tweedle_fq_plonk_verifier_index/marlin_plonk_bindings_tweedle_fq_verifier_index.ml
- src/lib/marlin_plonk_bindings/tweedle_fq_urs/marlin_plonk_bindings_tweedle_fq_urs.ml
- src/lib/zexe_backend/zexe_backend_common/dlog_plonk_based_keypair.ml
This PR adds an `offset` optional argument to the rust `read` functions, to allow us to place a header before the data (see #6661 for header format, #6769 for header parsing).
Checklist:
> Allow keys, urs to be read after an offset, to allow for a header

- src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
I suspect this is the root-cause for #6762, although I can't open the crash report in that issue to confirm. This behaviour is preferable anyway.
Checklist:
> Regenerate the genesis proof if there is an error when reading it

- src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_plonk_index.rs
- src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_plonk_verifier_index.rs
- src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_urs.rs
- src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_plonk_index.rs
- src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_plonk_verifier_index.rs
- src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_urs.rs
- src/lib/marlin_plonk_bindings/tweedle_fp_index/marlin_plonk_bindings_tweedle_fp_index.ml
- src/lib/marlin_plonk_bindings/tweedle_fp_plonk_verifier_index/marlin_plonk_bindings_tweedle_fp_verifier_index.ml
- src/lib/marlin_plonk_bindings/tweedle_fp_urs/marlin_plonk_bindings_tweedle_fp_urs.ml
- src/lib/marlin_plonk_bindings/tweedle_fq_index/marlin_plonk_bindings_tweedle_fq_index.ml
- src/lib/marlin_plonk_bindings/tweedle_fq_plonk_verifier_index/marlin_plonk_bindings_tweedle_fq_verifier_index.ml
- src/lib/marlin_plonk_bindings/tweedle_fq_urs/marlin_plonk_bindings_tweedle_fq_urs.ml
- src/lib/zexe_backend/zexe_backend_common/dlog_plonk_based_keypair.ml
This PR adds an optional `append` argument to the rust `write` functions, to allow us to place a header before the actual data in the file. This is the counterpart to #6771, which adjusts the `read` functions.
Checklist:
> Allow keys, urs to be appended to a file instead of overwriting

- .mergify.yml
- .mergify.yml.jinja
> Add ready-to-merge-into-develop support for develop-until-4.1-hardfork branch

- src/app/cli/src/coda.ml
- src/lib/coda_lib/conf_dir.ml
Create a lockfile `.mina-lock` in the config dir on daemon startup. If that file already exists, raise an error. On shutdown, remove the file, if it exists.
Boot log:
```
2020-11-20 19:29:19 UTC [Info] Coda daemon is booting up; built with commit "2b6a7ecefbd8fa04cfc081d59dbb3d00e38cfbd4" on branch "feature/mina-lockfile"
2020-11-20 19:29:19 UTC [Info] Created lockfile "/home/steck/.coda-config/.mina-lock"
2020-11-20 19:29:19 UTC [Info] Registering async shutdown handler: "Remove daemon lockfile"
```
Shutdown log:
```
2020-11-20 19:27:19 UTC [Info] Running async shutdown handler: "Remove daemon lockfile"
```
If the lockfile exists:
```
2020-11-20 19:30:34 UTC [Info] Coda daemon is booting up; built with commit "2b6a7ecefbd8fa04cfc081d59dbb3d00e38cfbd4" on branch "feature/mina-lockfile" …
```
> Mina lockfile

- src/app/cli/src/coda.ml
- src/lib/coda_version/coda_version.mli
- src/lib/coda_version/gen.sh
This PR adds more information to `Coda_version`, so that it can be used to fill the header in the `Snark_keys_header`.
This also adds some of this information to the version log at startup, since it's cheap to add (only logged once) and may make it easier to track down snark problems caused by changes to marlin and zexe.
Output at this PR:
```ocaml
let commit_id = "e523a4a68cf9371bf2e3e57ef10f993a52db4086"
let commit_id_short = "e523a4a6"
let branch = "feature/more-info-in-coda_version"
let commit_date = "2020-11-20T19:31:56+01:00"
let marlin_commit_id = "49f81edc9c86e5907d26ea791fa083640ad0ef3e"
let marlin_commit_id_short = "49f81edc"
let marlin_commit_date = "2020-11-18T02:16:47+00:00"
let zexe_commit_id = "e6eef92d6ce67908f787872883190a5d41be4228"
let zexe_commit_id_short = "e6eef92d" …
```
> Expose commit_date and marlin, zexe commit information from Coda_version

- scripts/run_local_network.sh
- src/app/cli/src/coda.ml
- src/app/cli/src/tests/coda_worker.ml
- src/app/cli/src/tests/full_test.ml
- src/app/libp2p_helper/src/go.mod
- src/app/libp2p_helper/src/go.sum
- src/app/libp2p_helper/src/libp2p_helper/main.go
- src/lib/coda_net2/coda_net2.ml
- src/lib/coda_net2/coda_net2.mli
- src/lib/gossip_net/libp2p.ml
Only default go metrics are registered for now. I updated the `run_local_network.sh` script to expose both ocaml and go prometheus servers, and checked to make sure that everything works properly. There is a new flag `-libp2p-metrics-port` which runs the prometheus server in libp2p_helper when set.
> Add libp2p_helper prometheus server and -libp2p-metrics-port flag

- src/app/cli/src/coda.ml
- src/lib/cli_lib/flag.ml
- src/lib/cli_lib/flag.mli
Adds a flag to control log level for coda.log. Default to trace+ (Spam can go away)
> File log level for `coda.log`

- src/app/cli/src/coda.ml
- src/lib/coda_lib/conf_dir.ml
This PR is the same code as in #6796, already merged to `develop-until-4.1-hardfork`.
This PR is to get the change to develop for the next testnet.
> Daemon lockfile for develop

- src/lib/staged_ledger/staged_ledger.ml
We weren't skipping verification of proofs when loading a persisted state. That caused the daemon to take a very long time to restart from a persisted state. This should fix that. On my machine, the daemon now seems to take around 1.3s per block whereas before it took more like 6s per block.
> properly skip verification

- src/lib/network_pool/snark_pool.ml
Right now we waste a lot of time fully verifying SNARKs only to reject them with a quick test later.
> check if snarks are referenced before verifying them

- scripts/compare_binables.py
- scripts/compare_ci_diff_binables.sh
- scripts/compare_ci_diff_types.sh
- scripts/compare_versioned_types.py
In `ppx_version`, the versioned type printer was printing internal attributes in type declarations, which don't affect serialization. That was causing a spurious failure in the CI linter.
Bumped to latest commit, which includes Bazel changes.
> Bump ppx_version to filter attributes when printing versioned types

- src/app/cli/src/tests/coda_worker_testnet.ml
This should make CI less red, making it easier to spot actual failures/regressions.
Checklist:
> Fix test_postake_three_producers integration test

- src/app/cli/src/tests/coda_archive_node_test.ml
- src/app/cli/src/tests/dune
This PR
* fixes the test, by not checking for blocks that could never have been seen
* uses `[%test_eq]` instead of `assert` to check equality, so that the results of a failure are printed.
Checklist:
> Fix test--dev--coda-archive-node-test

- src/inline_test_quiet_logs.opam
- src/lib/bootstrap_controller/bootstrap_controller.ml
- src/lib/consensus/dune
- src/lib/consensus/proof_of_stake.ml
- src/lib/inline_test_quiet_logs/dune
- src/lib/inline_test_quiet_logs/inline_test_quiet_logs.ml
- src/lib/ledger_catchup/ledger_catchup.ml
- src/lib/network_pool/batcher.ml
- src/lib/staged_ledger/dune
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/transition_frontier/tests/full_frontier_tests.ml
- src/lib/transition_frontier/tests/transition_frontier_tests.ml
- src/lib/transition_handler/catchup_scheduler.ml
- src/lib/transition_handler/processor.ml
This PR
* creates the `Inline_test_quiet_logs` library, to silence logs for passing unit tests
- this uses a hack with overwriting the unix file descriptor underlying the `stdout` `out_channel`
- this can be `open`ed at the top of any module containing unit tests to silence the output on stdout from any passing test
- failing tests have their stdout dumped at the end of the test
* removes the verification batch size log
- this never gave useful output -- our batch size is always 1 (although maybe we should look into why we never batch?)
- this single log line accounted for `130428/145594 = ~90%` lines in the log file [here](https://buildkite.com/o-1-labs-2/mina/builds/6377#0b7ec790-c83e-48fc-985e-864a88c048f9) (80% of the file by size)
* silences logs from some unit test (percentages are …
> Quieter logs in unit tests (145,594 lines -> 2,134 lines)

- src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_plonk_proof.rs
- src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_vector.rs
- src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_plonk_proof.rs
- src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_vector.rs
This PR fixes the segmentation fault reported in #6824.
The 'header' (ie. data pointer + length) of the input vectors were stored in the OCaml heap. This was fine when they were run synchronously, but the async version allows the OCaml GC to run while the function is also running. A badly timed GC can move the header and leave rust's reference pointing at arbitrary data, and dereferencing the vector's data pointer may then result in a segfault.
This PR changes the behaviour to store only a (rust heap) pointer in the OCaml heap. As long as we capture the pointer before yielding to OCaml, we know that we hold a reference to the intended data.
Checklist: …
> Fix segfault: capture rust heap references before yeilding to OCaml

- src/lib/coda_lib/conf_dir.ml
Write the daemon's process ID to the Mina lockfile. On startup, if the process in the lockfile exists, raise an error. Otherwise, remove the lockfile, log that fact, and continue.
Raise errors if the lockfile is empty or doesn't contain a pid.
> Process id in lockfileFeature/pid in lockfile

- .circleci/config.yml
- .circleci/config.yml.jinja
This PR removes a lint step for `frontend/website`, which now lives in a separate repo. This fixes an unnecessary failure in CI.
Checklist:
> Trivial: Stop attempting to lint frontend/website in CI

- src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
This PR removes the `$config` variable from the configuration log line, so that the configuration will appear in the logs, but will not be printed in the pretty output to stdout.
Checklist:
> Trivial: Don't print the runtime configuration/full genesis ledger during startup

- src/lib/allocation_functor/table.ml
- src/lib/coda_networking/coda_networking.ml
- src/lib/gossip_net/libp2p.ml
- src/lib/ledger_catchup/ledger_catchup.ml
- src/lib/network_pool/indexed_pool.ml
- src/lib/network_pool/mocks.ml
- src/lib/network_pool/snark_pool.ml
- src/lib/network_pool/test.ml
- src/lib/sync_handler/dune
- src/lib/sync_handler/sync_handler.ml
- src/lib/transition_frontier/transition_frontier.ml
- src/lib/transition_frontier/transition_frontier.mli
- src/lib/transition_router/transition_router.ml
This PR includes a number of fixes for the current test network. It should improve catchup in that it changes the way that blocks are downloaded to be more efficient/effective. It does not fully fix all the issues but it should get us a lot closer.
> Fixes for turbo pickles (should improve catchup)

- src/lib/gossip_net/libp2p.ml
periodically restarts the helper if env variable `MINA_LIBP2P_HELPER_RESTART_INTERVAL_BASE` is set
Checklist:
> libp2p restarts if env variable is set

- frontend/leaderboard/src/Challenges.re
This PR changes the value received for challenge #1. Originally, it was 500 but it should actually be 1000.
> Leaderboard: Fix Challenge #1 to be 1000 points.

- src/app/libp2p_helper/src/libp2p_helper/main.go
This version of the libp2p hotfix makes libp2p handle all rpc messages asynchronously. This has not been well vetted, and could introduce new race conditions.
This may be risky and we should test this well before we decide to release this.
> [HOTFIX] Libp2p async rpc handling

- genesis_ledgers/phase_three/config.json
`config.json` needs the newly added field `cliff_amount`
Checklist:
Closes #0000
Closes #0000
> fix deb build in develop-until-4.1-harfork

- buildkite/scripts/connect-to-testnet-on-develop.sh
The failure logic for `connect-to-testnet-on-develop.sh` is still wonky. This fixes it.
Checklist:
> Don't capture `coda client status` output in status_exit_code

- buildkite/scripts/connect-to-testnet-on-develop.sh
> Don't exit connect-to-testnet script if coda client status isn't ready yet

- dockerfiles/Dockerfile-coda-daemon
Currently used by testnet component healthchecks for processing graphql JSON responses.
**Checklist:**
> install jq (json processor) tool into daemon dockerfile

- src/lib/consensus/constants.ml
- src/lib/consensus/dune
- src/lib/consensus/epoch.ml
- src/lib/consensus/global_slot.ml
- src/lib/consensus/global_slot.mli
- src/lib/consensus/global_sub_window.mli
- src/lib/consensus/proof_of_stake.ml
- src/lib/consensus/slot.ml
removed `-w -37`flag from src/lib/consensus/dune and fixed all the errors (caught a bug too!)
Checklist:
> enable unused variable warning in src/lib/consensus

- src/lib/network_pool/transaction_pool.ml
I think this is the root cause for the following error in turbo-pickles:
```
backtrace: [
0: "Raised at file "src/lib/merkle_mask/masking_merkle_tree.ml", line 101, characters 10-50"      
1: "Called from file "src/lib/merkle_mask/masking_merkle_tree.ml", line 513, characters 6-26"      
2: "Called from file "src/lib/network_pool/transaction_pool.ml", line 877, characters 24-75"      
3: "Called from file "src/lib/network_pool/transaction_pool.ml", line 880, characters 26-68"      
4: "Called from file "src/lib/network_pool/transaction_pool.ml", line 1117, characters 18-30"      
5: "Called from file "src/lib/network_pool/network_pool_base.ml", line 93, characters 15-67"      
6: "Called from file "src/lib/pipe_lib/strict_pipe.ml", line 152, characters 28-37"      
7: "Called from file …
```
> fix dangling_parent_reference in transaction pool

- src/lib/coda_networking/coda_networking.ml
- src/lib/network_pool/intf.ml
- src/lib/network_pool/network_pool_base.ml
- src/lib/network_pool/snark_pool.ml
- src/lib/network_pool/snark_pool.mli
- src/lib/network_pool/snark_pool_diff.ml
- src/lib/network_pool/test.ml
- src/lib/network_pool/transaction_pool.ml
- src/lib/pipe_lib/strict_pipe.ml
- src/lib/pipe_lib/strict_pipe.mli
This aims to address #6764, though I haven't reproduced the issue there. This PR adds a new overflow behavior to `Strict_pipe.t` to call a function when a message is dropped due to overflow. Network pool will now fire all diff callbacks, even if the message is dropped from the pipe.
Not very proud of the addition of empty snark pool diffs, but I didn't see any easy way around that (suggestions requested).
> Trigger network pool callbacks when pipe is full

- src/lib/interruptible/interruptible.ml
- src/lib/interruptible/interruptible.mli
This PR rewrites the interruptible monad to behave correctly. In particular, this changes the semantics around binding so that
```ocaml
let%bind x = (* this gets the interrupt *) in
let%bind y = (* while running this *) in
let%bind z = f y in
(* ... *)
```
has the same behaviour as
```ocaml
let%bind x = (* this gets the interrupt *) in
let%bind z =
let%bind y = (* while running this *) in
f y
in
(* ... *)
```
This was not the case in either the original version or the tweaked implementation in #6880. Presumably this was causing issues in `Integration_test_cloud_engine.Stack_driver_log_engine.pull_subscription_in_background`, which calls itself infinitely in this nested-bind style.
This also adds unit tests for these cases, and fixes the existing unit test (which was equivalent to …
> Rework Interruptible monad

- README-dev.md
Very minor fix. Link didn't work because header for that section changed.
> Fix link in dev README

- src/lib/coda_lib/conf_dir.ml
On Linux, include a hardware information file in the tar file created by `export-logs` and `export-local-logs`.
The file is created by running `uname -a`, `lscpu`, `lsgpu`, `lsmem`, and `lsblk`, and writing that to a single file `hardware.info` in the config dir. (It's not removed, could add that if desired). 
Example output:
```
Linux tabouleh 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
*** Output from 'lscpu' ***
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          16
On-line CPU(s) list:             0-15
Thread(s) per core:              2
Core(s) per socket: …
```
> Dump hardware details for Linux

- src/app/cli/src/coda.ml
- src/lib/bootstrap_controller/bootstrap_controller.ml
- src/lib/consensus/proof_of_stake.ml
- src/lib/transition_router/transition_router.ml
Epoch ledger sync is failing because nodes were requesting genesis ledger.
This happens when transition frontier controller starts and the node tries to sync its local state using the frontier root which could point to an older epoch ledger (in this case genesis ledger) as compared to what the best tip points to. However, the epoch ledgers persisted by the node would already be updated for the best-tip. So essentially the node was trying to revert the epoch ledgers to an older state. 
Syncing the local state with the best tip ensures that the frontier and local state are in sync (given the epoch finalization condition in the code)
Also, removed an assertion that was failing for me locally. Described the issue here: #6956. This should be added back when the issue is fixed
fixes #6955
fixes …
> Hot fix epoch ledger sync failure

- src/app/cli/src/coda.ml
- src/lib/block_producer/block_producer.ml
- src/lib/coda_lib/coda_lib.ml
- src/lib/coda_networking/coda_networking.ml
Log the following at info level
1. "Received a block from"
2. "Broadcasting new state over gossip net"
3. "Rebroadcasting $state_hash"
4. "Producing new block with parent $breadcrumb"
5. "Successfully produced a new block"
Also removed the daemon flag `-log-received-blocks`. The daemon will always log blocks received
The reason for this PR is to have enough information about block production and gossip in the log files to calculate block latencies as implemented here https://github.com/MinaProtocol/coda-automation/pull/509
> Block production/gossip logs at info level

- src/lib/interruptible/interruptible.ml
- src/lib/interruptible/interruptible.mli
- src/lib/merkle_ledger/any_ledger.ml
- src/lib/merkle_ledger/base_ledger_intf.ml
- src/lib/merkle_ledger/database.ml
- src/lib/merkle_ledger/null_ledger.ml
- src/lib/merkle_mask/maskable_merkle_tree.ml
- src/lib/merkle_mask/masking_merkle_tree.ml
- src/lib/merkle_mask/masking_merkle_tree_intf.ml
- src/lib/network_pool/transaction_pool.ml
This PR
* adds a `detach_signal` method to ledgers triggered when
- the ledger is closed
- the ledger is a mask, and its parent is removed without the intention to replace it
* adds `Interruptible.Deferred_let_syntax`
- this exposes a `Let_syntax` module that works with ppx_let to consume `Async.Deferred.t`s and return `Interruptible.t`s
- this allows us to make an async function interruptible without having to modify any of the code
- this also supports `let%map_open`/`let%bind_open`, where the rhs of the binding can use the `Deferred.t` monad as normal.
* converts `Transaction_pool.apply` to interrupt when its ledger emits a detach signal
- this combines `detach_signal` and the `Interruptible.Deferred_let_syntax` to trigger the interrupt with minimal code changes
Open question: should …
> Interrupt Transaction_pool.apply when the ledger is detached

- src/app/rosetta/lib/block.ml
- src/app/rosetta/test-agent/agent.ml
- Fix broken query_height query in Rosetta block.ml
- Fix Rosetta handling of coinbase fees
Rosetta was incorrectly using a constant for all coinbase fees. Some
fees are "supercharged" so they're actually variable. The specific fee
was already available so this switches to using that and removes the
code that was pulling the base coinbase fee constant from GraphQL.
Tested using Rosetta `./start.sh` and Coinbase's `rosetta-cli`.
Checklist:
> Fix Rosetta handling of coinbase fees (plus miscellaneous related fixes)

- rfcs/0040-rosetta-timelocking.md
This is a proposal for supporting time-locked account tracking in Rosetta. Though, really, it boils down to supporting historical balance lookups for accounts through the archive node (some of which may have time locks on them). We are still considering adding support for time-locked account creation after the genesis block, this proposal aims to describe what changes we could make to the design and implementation in the scenario that we do wish to support this feature.
This PR deprecates #6931
> RFC: Time locked accounts in Rosetta

- Makefile
- src/app/missing_blocks_auditor/dune
- src/app/missing_blocks_auditor/missing_blocks_auditor.ml
- src/app/missing_blocks_auditor/sql.ml
- src/missing_blocks_auditor.opam
App to report missing blocks in archive db. A block is missing if the `parent_id` field of `blocks` is `NULL`.
There's a Makefile target to build it with `postake_medium_curves`.
Tested against archive db created by Rosetta.
Sample output:
```
{"timestamp":"2020-12-09 23:33:59.960871Z","level":"Info","source":{"module":"Dune__exe__Missing_blocks_auditor","location":"File \"src/app/missing_blocks_auditor/missing_blocks_auditor.ml\", line 30, characters 10-21"},"message":"Block has no parent in archive db","metadata":{"block_id":1,"parent_hash":"3NK9z26joBvSDZswiLVjHp3Y3c9t4vq7P8H5JCk4QpSLL9sXMPMb","pid":94199,"state_hash":"3NL52BwYWhu6oHPY5YAWsUmFtcuCJJ7BCifUxgq2Wo9CwNdgiedA"}}
```
We'd use the reported `parent_hash`es as the ends of missing subchains.
Closes #6912.
> Report missing blocks in archive db

- src/lib/ledger_catchup/ledger_catchup.ml
- src/lib/transition_frontier/catchup_hash_tree.ml
- src/lib/transition_frontier/full_frontier/full_frontier.ml
- src/lib/transition_frontier/full_frontier/full_frontier.mli
- src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
- src/lib/transition_frontier/tests/full_frontier_tests.ml
- src/lib/transition_frontier/transition_frontier.ml
- src/lib/transition_frontier/transition_frontier.mli
This PR creates a module `catchup_hash_tree.ml` which is contained in a transition frontier. This type is a tree with
- Nodes: State hashes which are either in the full frontier or in some set of catchup jobs
- Edges: There are edges from children to their parents.
For each node, we record whether or not it is in the full frontier, and if not we write down which active catchup jobs it is involved with.
The point of this is to let us write a function `val max_catchup_chain_length : Catchup_hash_tree.t -> int` which computes the length of the longest directed path from a leaf of the tree to a node which is in the full frontier. This allows us to know whether a "long" (defined as > 5) catchup job is in progress, in which case we allow a particular assertion about local state to fail. …
> Remove assertion when catchup is long

- src/app/cli/src/coda.ml
- src/app/cli/src/init/client.ml
- src/app/cli/src/tests/coda_worker.ml
- src/app/cli/src/tests/full_test.ml
- src/lib/block_producer/block_producer.ml
- src/lib/coda_lib/coda_lib.ml
- src/lib/coda_lib/config.ml
- src/lib/coda_lib/dune
- src/lib/coda_networking/coda_networking.ml
- src/lib/coda_networking/coda_networking.mli
- src/lib/coda_networking/dune
- src/lib/ledger_catchup/ledger_catchup.ml
- src/lib/network_peer/envelope.ml
- src/lib/network_peer/envelope.mli
- src/lib/network_pool/snark_pool.ml
- src/lib/network_pool/snark_pool_diff.ml
- src/lib/transition_frontier/frontier_base/breadcrumb.ml
- src/lib/transition_frontier/frontier_base/breadcrumb.mli
- src/lib/transition_frontier/full_frontier/full_frontier.ml
- src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
- src/lib/transition_frontier/transition_frontier.ml
- src/lib/transition_handler/breadcrumb_builder.ml
- src/lib/transition_handler/processor.ml
Add more fields to the telemetry response.
These are the same changes as in #7002, except based on `develop-until-4.1-hardfork`.
See that PR for comments and commits leading to the current design.
> Add more telemetry data (against until-4.1-hardfork)

- src/lib/trust_system/peer_trust.ml
- src/lib/trust_system/peer_trust.mli
This fixes a crash by renaming the `peer` field to `sender_id`, so that it matches `ban_message` . See e.g. https://buildkite.com/o-1-labs-2/mina/builds/7332#b2ac1ae0-5e43-4b0f-8df9-b0fecfcdd27d
We should might have been able to catch this in `ppx_register_event`, which is far preferable to a crash a runtime. @psteckler any ideas?
Checklist:
> Fix Peer_banned structured log message

- src/app/libp2p_helper/src/libp2p_helper/main.go
- src/lib/coda_networking/coda_networking.ml
We were seeing crashes from prometheus `MustRegister` in our QA-nets. Replaced all calls to MustRegister with Register instead and handled the error.
Additionally, we no longer will need the extra initial peers because we properly query the DHT for extra peers.
It builds -- will test on a qa net as these errors don't show up in run-local-network
> Prometheus double-register fails, no extra peers

- src/app/libp2p_helper/src/libp2p_helper/main.go
We think this could be causing some of the issues we're running into on qa nets, so disabling for now
> Go metrics disabled for now

- src/lib/integration_test_cloud_engine/coda_automation.ml
tried to put too much information in the integration test namespace string, was causing problems because it made it too long and ran up against character length limits with some tests with longer names.
removing some of the info, now that integration tests are in their own cluster anyways it shouldn't be as necessary
> shorten namespace

- src/lib/transition_frontier/catchup_hash_tree.ml
This logs the hash tree structure when the invariant is broken to aid in debugging.
> log hash tree structure when invariant is broken

- src/lib/transition_frontier/catchup_hash_tree.ml
This moves the "hash tree invariant broken" log to debug instead of warn.
> move hash tree invariant log to debug

- helm/snark-worker/Chart.yaml
- helm/snark-worker/templates/coordinator-service.yaml
Add client port to `snark-coordinator`'s ClusterIP service object for inter-communication with SNARK workers.
Checklist:
> expose snark coordinator's client port for worker inter-communication

- helm/archive-node/Chart.yaml
- helm/archive-node/templates/archive.yaml
- helm/block-producer/Chart.yaml
- helm/block-producer/templates/block-producer.yaml
- helm/seed-node/Chart.yaml
- helm/seed-node/templates/seed-node.yaml
- helm/snark-worker/Chart.yaml
- helm/snark-worker/templates/snark-coordinator.yaml
The port annotations should reference the recently added port variables rather than rely on static values within the charts.
Checklist:
> update prometheus scrape/listening port annotation with metrics port var

- src/lib/block_producer/block_producer.ml
- src/lib/coda_base/ledger.mli
- src/lib/coda_base/transaction_logic.ml
- src/lib/coda_base/user_command_status.ml
- src/lib/coda_transition/external_transition.ml
- src/lib/consensus/intf.ml
- src/lib/consensus/proof_of_stake.ml
- src/lib/staged_ledger/pre_diff_info.ml
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/staged_ledger/staged_ledger.mli
- src/lib/staged_ledger_diff/staged_ledger_diff.ml
- src/lib/staged_ledger_diff/staged_ledger_diff.mli
- src/lib/transition_frontier/frontier_base/breadcrumb.ml
This PR
* updates the staged ledger pre-diffs to include the balances involved in each internal command (fee payment or coinbase)
* adds validation for the user command statuses and balance information stored in the diffs
- previously, we had been relying on the statuses being accurate for the archive node, but we never checked them
- now their correctness is enforced by a trust score
This is more invasive than some of the other ways we could have exposed this data for #6940. However, doing it this way allows partial ledgers and transactions to be reliably reconstructed from a block without needing to use or reimplement a full archive node, which was one of the stated goals of #7074.
Checklist: …
> Add balances to internal commands in blocks, validate statuses

- helm/archive-node/Chart.yaml
- helm/archive-node/templates/archive.yaml
- helm/block-producer/Chart.yaml
- helm/block-producer/templates/block-producer.yaml
- helm/seed-node/Chart.yaml
- helm/seed-node/templates/seed-node.yaml
- helm/snark-worker/Chart.yaml
- helm/snark-worker/templates/snark-coordinator.yaml
- helm/snark-worker/templates/snark-worker.yaml
Trimming trailing "-" is a [common practice](https://github.com/MinaProtocol/mina/blob/develop/helm/archive-node/templates/_helpers.tpl#L6) across our charts and should help avoid future encounters of the following error:
```
Error: Deployment.apps "seed-node" is invalid: spec.template.labels: Invalid value: "0.1.0-": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character
on ../../modules/kubernetes/testnet/helm.tf line 161, in resource "helm_release" "seed":
161: resource "helm_release" "seed" {
```
**note:** "must start and end with an alphanumeric character"
Checklist:
- …
> ensure trailing "-" are removed from version labels (based on docker image tags)

- src/lib/transition_frontier/persistent_frontier/database.ml
- src/lib/transition_frontier/persistent_frontier/database.mli
This catches database corruption errors where the data written is itself corrupted. This allows us to clear the corrupted database and try again.
Checklist:
Closes  #7112
> Catch errors raised when checking the persistent frontier db

- .mergify.yml
- .mergify.yml.jinja
This makes `ready-for-merge-into-develop` work for the `develop-until-adversarial` branch.
Checklist:
> Update mergify for develop-until-adversarial

- .circleci/config.yml
- .circleci/config.yml.jinja
The wallet is deprecated, but we're still paying to run a wallet build for every CI run. It has been failing for a while, so we're gaining nothing by running it.
Checklist:
> Remove wallet build from CI

- src/lib/mina_lib/coda_subscriptions.ml
- src/lib/mina_metrics/mina_metrics.ml
The gcloud block dump backup writing uses an asynchronous process instead. Also introduced a prometheus metric so we can track how far we get backed up.
> Writes to gcloud asynchronously

- .circleci/config.yml
- .circleci/config.yml.jinja
Our CircleCI plan currently doesn't seem to support the large resource class for Mac builds. Builds can't finish with the lower resource class, so there's no point running the job at all unless we change that.
Checklist:
> Disable Mac builds on CI

- src/lib/coda_version/BUILD.bazel
- src/lib/coda_version/coda_version.ml.template
- src/lib/pickles/BUILD.bazel
- src/lib/pickles/backend/BUILD.bazel
- src/lib/pickles/composition_types/BUILD.bazel
- src/lib/pickles/limb_vector/BUILD.bazel
- src/lib/pickles/one_hot_vector/BUILD.bazel
- src/lib/pickles/plonk_checks/BUILD.bazel
- src/lib/pickles/precomputed/BUILD.bazel
- src/lib/pickles/pseudo/BUILD.bazel
- src/lib/pickles_base/BUILD.bazel
- src/lib/random_oracle_input/BUILD.bazel
- src/lib/snark_keys_header/BUILD.bazel
- src/lib/snarky_group_map/BUILD.bazel
- src/lib/snarky_log/BUILD.bazel
- src/lib/webkit_trace_event/BUILD.bazel
This PR adds Bazel support for `src/lib/pickles` and its dependencies.  The targets in this PR will not build until the following PRs are merged:  #7146 #7149 #7150
> Bazel: src/lib/pickles support

- src/lib/allocation_functor/dune
- src/lib/allocation_functor/intf.ml
- src/lib/allocation_functor/make.ml
#7185 for the bazel branch
Checklist:
> [Bazel] Use ppx_compare instead of ppx_deriving.std

- src/lib/allocation_functor/dune
- src/lib/allocation_functor/intf.ml
- src/lib/allocation_functor/make.ml
This fixes an inconsistency in the behaviour of `ppx_version` between dune and bazel when building; see #7177.
Checklist:
> Use ppx_compare instead of ppx_deriving.std

- src/lib/mina_lib/conf_dir.ml
Copy the logs before running tar, to avoid file-changed-when-reading errors. The copies are in a /tmp directory, which is deleted after the archive is created.
Closes #7113.
> Copy logs before tarring

- src/lib/snark_keys/BUILD.bazel
- src/lib/snark_keys/gen_keys/BUILD.bazel
- src/lib/snark_keys/remove_snark_keys_trigger/BUILD.bazel
- src/lib/snark_keys/remove_snark_keys_trigger/clear_keys/BUILD.bazel
Contains subdir gen_keys which uses genrule to generate a file for compilation.
> [Bazel] add src/lib/snark_keys and subdirs, incl. gen_keys

- src/app/benchmarks/BUILD.bazel
CAVEAT: does not build, due to dependence on vrf_lib_tests, which depend on @snarky//src:snarky
> [Bazel] app: benchmarks

- src/lib/snark_bits/BUILD.bazel
- src/lib/snark_params/BUILD.bazel
- src/lib/snark_work_lib/BUILD.bazel
- src/lib/snark_worker/BUILD.bazel
- src/lib/snark_worker/standalone/BUILD.bazel
- src/lib/snarky_blake2/BUILD.bazel
- src/lib/snarky_curves/BUILD.bazel
- src/lib/snarky_field_extensions/BUILD.bazel
- src/lib/snarky_pairing/BUILD.bazel
- src/lib/snarky_taylor/BUILD.bazel
- src/lib/snarky_verifier/BUILD.bazel
Except for snark_keys, which contains a genrule (to follow)
> [Bazel] add src/lib/snark* packages

- dockerfiles/scripts/healthcheck-utilities.sh
`curl` download progress is currently displayed in health probe output (like the following) making the probe message more noisy and more difficult to identify/parse. This change silences this progress output only showing errors.
```
Readiness  probe failed: Archive[] is out of sync with local daemon[3847]   % Total    % Received % Xferd  Average Speed   Time    Time     Time   Current                                  Dload  Upload   Total   Spent    Left   Speed    0     0    0     0    0     0      0      0 --:--:-- --:--:--  --:--:--     0 100    68    0    32  100    36   6400   7200 --:--:--  --:--:-- --:--:-- 13600   % Total    % Received % Xferd  Average Speed   Time    Time     Time   Current                                  Dload  Upload   Total   Spent    Left   Speed    0     0 …
```
> silence curl requests in k8s health probes for less noisy event output

- .bazelignore
- bzl/tools/qbuild.sh
- bzl/tools/qdeps.sh
- bzl/tools/qppxmodule.sh
- bzl/tools/qrdeps.sh
- src/BUILD.bazel
- src/config/BUILD.bazel
- src/lib/coda_version/coda_version_defaults.ml
- src/lib/coda_version/dune
* the modifications in .bazelignore are for the transition period to full bazel
support. we need to bazelignore stuff that is pinned to old versions
until the transition is complete. otherwise some queries fail.
* src/BUILD.bazel contains config rules that need to be fleshed out
and updated once the transition is complete. they're not used currently, but they screw up queries.
* the profile fixes in src/config/BUILD.bazel are not temporary
* add some query scripts. they're generally useful, and they help in making PRs
> [Bazel] temporary fixes to baseline; add query scripts

- src/lib/allocation_functor/BUILD.bazel
- src/lib/allocation_functor/make.ml
I don't know if this is a good fix, but the Bazel build fails without it, throwing:
```
File "src/lib/allocation_functor/make.ml", line 193, characters 8-719:
Error: Signature mismatch:
...
The value `equal' is required but not provided
File "bazel-out/darwin-fastbuild/bin/src/lib/allocation_functor/_obazl_/Allocation_functor__Intf.ml", line 368, characters 16-63:
Expected declaration
```
> [Bazel] fix missing code in allocation_functor/make.ml

- .mergify.yml
- .mergify.yml.jinja
This allows mergify to take advantage of the new settings on develop; without this it still attempts to bring each branch up-to-date before merging it.
Checklist:
> Use fasttrack merging: merge.strict=false instead of smart for mergify

- graphql_schema.json
- src/app/archive/archive_lib/processor.ml
- src/app/archive/archive_lib/rpc.ml
- src/app/cli/src/init/client.ml
- src/app/cli/src/init/graphql_queries.ml
- src/lib/coda_transition/external_transition.ml
- src/lib/coda_transition/external_transition_intf.ml
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/mina_lib/archive_client.ml
- src/lib/mina_lib/archive_client.mli
- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_lib/mina_lib.mli
This PR
* adds a `Send_precomputed_block` RPC to the archive process
* exposes an `archivePrecomputedBlock` command to GraphQL
- the argument type takes the precomputed block in JSON format, but its particular structure is not exposed to the GraphQL schema
- the return type is `{applied: bool}`. Using a more restricted return type (e.g. an empty object or a scalar) causes the CLI to silently swallow any errors
- this pipes the data to the archive node associated with the daemon, failing if there is no such process
* adds a `advanced archive-precomputed-blocks` command to the CLI
- this provides the option of sending blocks to the archive node via a running daemon, or to the daemon directly using the given port/address
- the anonymous arguments are filenames, where we expect 1 JSON-encoded …
> Add archive-precomputed-blocks command to CLI and GraphQL

- src/lib/daemon_rpcs/client.ml
Errors raised by `Tcp.with_connection` may be uncaught without this, causing tcp 'connection attempt timeout' etc. to be fatal (e.g. #7108).
Checklist:
Fixes #7108
> Fix archive node timeout crash: Catch errors raised by Tcp.with_connection

- src/lib/verifier/prod.ml
This log message is misleading, caused some confusion.
Checklist:
> [Trivial] Correct 'prover successfully stopped' log message from verifier

- helm/archive-node/Chart.yaml
- helm/archive-node/templates/archive.yaml
Based on https://github.com/MinaProtocol/coda-automation/pull/544, a new flag `-config-file` is being introduced in https://github.com/MinaProtocol/mina/pull/7125
**Checklist:**
> pass daemon.json to the archive process

- .circleci/config.yml
The CircleCI template was changed but the actual config hasn't been re-rendered.
Landing this without review; config changes have been reviewed.
Checklist:
> Re-render circleci

- src/app/archive/archive_lib/processor.ml
- src/app/rosetta/lib/block.ml
In `Archive_lib.Processor.User_command.t`, the types for tokens, amount, and fee were given as an OCaml `int`, which is a 63-bit signed value. Those types are used to populate the archive db.
The values are derived from `Token_id.t`, `Amount.t`, and `Fee.t` which are unsigned 64-bit values, so there's a potential data loss (or exception raised) when converting to `int`.
We can squeeze out one more bit by using the `int64` type, which is a signed type. The columns in Postgresql have type `bigint`, which is a 64-bit signed type. So once we have an `int64` value, there's no data loss when saving to the database.
If we wanted to guarantee no data loss for very big numbers, we'd have to change the Postgresql type.
The change here is a strict improvement, though.
Tested by using the Rosetta …
> Change some archive lib user command types to int64

- src/app/archive/archive_lib/processor.ml
- src/app/rosetta/lib/block.ml
The type `Processor.User_command.Signed_command.t` was missing some fields that occur in the archive db. The SQL for the `load` command mentioned those fields, but the data was not captured in the returned value.
Add those fields here. As a by-product, there is some simplification in the Rosetta code.
Tested by generating an archive db from Rosetta.
> Add missing fields to user commands

- src/lib/coda_numbers/account_nonce.ml
Use `int` Yojson coding for nonces, instead of `string`, which is slower.
> int yojson coding for nonces

- frontend/leaderboard/__tests__/leaderboard_test.re
- frontend/leaderboard/src/Challenges.re
- frontend/leaderboard/src/Main.re
- frontend/leaderboard/src/Metrics.re
- frontend/leaderboard/src/Points.re
- frontend/leaderboard/src/Sheets.re
- frontend/leaderboard/src/Types.re
- frontend/leaderboard/src/UploadLeaderboardData.re
This PR implements the functionality needed to reward all the points gathered from the pre and post-fork dumps. Additionally adds functionality to give points for the SNARK challenge. 
To get the SNARK challenge working, we had to add parsing for a coinbase receiver in a block. The coinbase receiver property is initialized to `None` as we need to inspect the formed block data instead of the query. To find the coinbase receiver, we look for internal commands that have a type of `Coinbase`. Once we find the PK associated with that receiver, we update the block data and include it.
To give points for SNARK fees, the snark fees in a block must not belong to the coinbase receiver. As long as this requirement is met, we can add snark fees for each public key. 
To view the current results from …
> Leaderboard: Merged pre and postfork data + SNARK challenge [DO NOT MERGE]

- src/lib/error_json/error_json.ml
This distinguishes errors encountered while constructing an `Error.t` (encoded as `Could_not_construct`) from other sexp-encoded errors.
Checklist:
> Distinguish Could_not_construct from Sexp in Error.t

- src/lib/block_producer/block_producer.ml
- src/lib/mina_transition/external_transition.ml
- src/lib/mina_transition/external_transition_intf.ml
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/staged_ledger/staged_ledger.mli
- src/lib/transition_frontier/frontier_base/breadcrumb.ml
- src/lib/transition_frontier/frontier_base/breadcrumb.mli
- src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
- src/lib/transition_handler/processor.ml
This PR
1. Adds a more specific argument for skipping parts of staged ledger verification
2. When snapps are not enabled, does not call the verifier process to check user commands.
> add finer grained argument for skipping staged ledger verification

- helm/archive-node/Chart.yaml
- helm/archive-node/templates/archive.yaml
- helm/block-producer/Chart.yaml
- helm/block-producer/templates/block-producer.yaml
- helm/seed-node/Chart.yaml
- helm/seed-node/templates/seed-node.yaml
- helm/snark-worker/Chart.yaml
- helm/snark-worker/templates/snark-coordinator.yaml
Ensure `CONNECT_PRIVATE_IPS` is set to true for all daemon containers within Helm testnet component pods to enable cluster-local peer discovery.
Checklist:
> set testnet component envvar CONNECT_PRIVATE_IPS=true

- frontend/bot/helm/Chart.yaml
- frontend/leaderboard/helm/Chart.yaml
- helm/archive-node/Chart.yaml
- helm/block-producer/Chart.yaml
- helm/common/Chart.yaml
- helm/seed-node/Chart.yaml
- helm/snark-worker/Chart.yaml
Update Helm chart logos from non-existent repo image file to official Mina logo and make it publicly accessible from the GCS `coda/mina-charts` repo.
Checklist:
> update helm chart Mina logo/icon metadata

- src/app/archive/archive_lib/extensional.ml
- src/app/archive/archive_lib/processor.ml
- src/app/missing_subchain/block.ml
- src/app/missing_subchain/dune
- src/app/missing_subchain/missing_subchain.ml
- src/app/missing_subchain/sql.ml
- src/app/rosetta/lib/block.ml
Add transactions to output of missing subchains tool. The output is now in JSON format; each line of output is a JSON object representing a block.
The output is meant to be the same as the block logging format, eliding the data not available in an archive db. Two additional fields are added, a state hash and a ledger hash, because those are needed to put in the archive database. The idea is to have a single ingestor program that can take this output, or the logged blocks, and update an archive db.
For internal commands, the balances are dummy values for now, until that data becomes available in the archive db. There are TODOs in the code for this task, and I'll add an issue.
Tested by running on an archive db created with Rosetta and examining the output JSON.
Closes #7239.
> Transactions in missing subchains; compatible JSON output

- Makefile
- src/app/missing_subchain/block.ml
Move ledger hash from top-level of emitted blocks to blockchain state.
Tested with a Rosetta archive db.
Added a Makefile target.
> Move ledger hash to blockchain state

- src/lib/mina_lib/archive_client.ml
- src/lib/mina_lib/archive_client.mli
In the current testnet, we have been seeing lots of RPC failures, primarily handshake errors, in the RPC that sends data to the archive process.
Most of the time, the RPC succeeds, so maybe it's worth retrying the RPC when it fails. Not including blocks in the archive db is bad, because we have to patch the archive db from other sources, in case we need to do a hard fork.
Here, put the RPC calls in a loop, subject to a max number of tries. If it fails after that number of tries, return a tagged error, where the tag is built from all the errors seen.
> Retry archive RPCs

- src/app/cli/src/init/client.ml
> Don't exit on failed GraphQL requests in archive-precomputed-blocks

- .circleci/config.yml.jinja
> Disable update-branch-protection CI job while we transition to the new branch world

- .circleci/config.yml
- .circleci/config.yml.jinja
> Disable update-branch-protection CI job while we transition to the new branch world 

- automation/services/coda-network-services/make_report.py
Add uptime buckets to network health report.
Possible future improvement: add synced statuses to the buckets.
Tested on `testworld`.
Closes #7238.
> Uptime buckets in network health report

- src/app/archive/archive_lib/extensional.ml
- src/app/missing_subchain/missing_subchain.ml
#7393 was closed, because it's too hard to accurately reproduce the structure of an `External_transition`.
Here, instead, the output of the missing subchains tool are `Archive_lib.Extensional_block.t`s in JSON format. Each block is in a file `<state-hash>.json`.
An extensional block contains the same information as a block in the archive db, except that there are no intensional references to foreign keys. That will make it easy to repopulate the archive db from these blocks.
The plan is add a CLI command, `advanced archive-extensional-blocks` in the manner of `archive-precomputed-blocks`.
Sample output:
```json
{
"state_hash": "3NK32K4iUga1jEjySzhFQvtzQsYqCHHyommWj1g2yG6xjA5VPjU6",
"parent_hash": "3NKkKzY9CLEKDjGSiNLd9aDZKPDLo8GFVeSggLa31Br4rVX6TLap",
"creator": …
```
> Extensional blocks output for missing subchains

- automation/services/coda-network-services/Dockerfile
`master` branch reference was from Dockerfile usage in `coda-automation` repo and missed during merge into `mina`.
Checklist:
> update coda-network-service's Dockerfile random_restart script ADD directive

- buildkite/scripts/connect-to-testnet-on-develop.sh
- scripts/compare_ci_diff_types_develop.sh
> Set compatibility checks to run on compatible, not on develop

- src/lib/daemon_rpcs/types.ml
In `client status`, print only the number of peers, not the actual peers.
Tested by running a local network.
Output:
```
Peers:                                         3
```
Closes #7422.
> Peer count in client status

- src/lib/pickles/limb_vector/constant.ml
This PR fixes the parsing of some precomputed blocks that were received over GraphQL. Tested on 
[this block](https://github.com/MinaProtocol/mina/files/5805732/testworld-3NK3C6F5KtYC7Z7tbsEXr6iJXt3CMKp8LnCsHtGMeMdrs2ALS9Wm.txt), which fails without this change.
Checklist:
> Fix archive-precomputed-blocks

- src/lib/daemon_rpcs/types.ml
Change wording for maximum observed block height. The new wording is consistent with `block height` used elsewhere in `client status`.
Closes #7440.
> Max observed block height

- src/app/archive/archive_lib/processor.ml
This stops the archive process from failing if it hasn't seen the block that snarked the particular ledger hash.
Checklist:
Closes #7455
> Always add snarked_ledger_hash to archive db if it doesn't exist

- src/app/cli/src/init/coda_run.ml
- src/lib/error_json/error_json.ml
This PR adds improved error printing. This allows us to avoid unwrapping the `Monitor.Error` exception, which may contain a more useful backtrace than the one we can infer otherwise.
Printing for the error is slightly worse than when we have a JSON encoding, but this backtrace information is more valuable than the pretty printing. This is an alternative to #6904, designed to address the weird stack traces seen in #6901 and [this comment](https://github.com/MinaProtocol/mina/issues/7108#issuecomment-752658625).
Checklist:
> Improve error printing

- src/app/cli/src/init/client.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/network_pool/indexed_pool.ml
- src/lib/network_pool/transaction_pool.ml
- src/lib/user_command_input/user_command_input.ml
- src/lib/user_command_input/user_command_input.mli
This PR
* prevents transaction replacement from evicting transactions other than the one with the matching nonce
- if the replacement increases costs by more than is left in the account, some later transactions will be dropped
- if it is less profitable to include the new transaction because of later transactions that would be dropped, it is rejected
* sets a constant replacement fee at `0.5` mina
* allows the nonces of `User_command_input.t`s to take any value in the range `ledger_nonce+1...txn_pool_nonce+1`
Checklist:
Closes #6605
> Fix transaction replacements

- src/app/cli/src/init/coda_run.ml
- src/lib/network_pool/network_pool_base.ml
- src/lib/transition_frontier/transition_frontier.ml
- src/lib/transition_handler/catchup_scheduler.ml
I think error logs that we don't want users to be bothered about should be `debug` (Trace logs are a lil too noisy)
> changed some trace logs to debug/warn

- src/lib/block_producer/block_producer.ml
- src/lib/cache_lib/impl.ml
- src/lib/child_processes/child_processes.ml
- src/lib/consensus/proof_of_stake.ml
- src/lib/distributed_dsl/distributed_dsl.ml
- src/lib/integration_test_cloud_engine/stack_driver_log_engine.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_net2/mina_net2.ml
- src/lib/network_pool/batcher.ml
- src/lib/pipe_lib/broadcast_pipe.ml
- src/lib/syncable_ledger/syncable_ledger.ml
- src/lib/timeout_lib/timeout_lib.ml
- src/lib/transition_frontier/extensions/transition_registry.ml
- src/lib/transition_frontier_controller/dune
- src/lib/transition_frontier_controller/transition_frontier_controller.ml
- src/lib/transition_handler/processor.ml
This PR changes all Ivar.fill to Ivar.fill_if_empty in our codebase (not include tests).
There's also warning for places where we are trying to fill in a non-empty ivar (except for timeout_lib.ml and broadcast_pipe.ml)
I did an analysis of all those use of Ivar.fill in #7463.
Once this PR is landed, we can also monitor our logs to see where does that exception comes from.
> change all Ivar.fill to Ivar.fill_if_empty

- src/lib/block_producer/block_producer.ml
- src/lib/cache_lib/impl.ml
- src/lib/child_processes/child_processes.ml
- src/lib/consensus/proof_of_stake.ml
- src/lib/distributed_dsl/distributed_dsl.ml
- src/lib/integration_test_cloud_engine/stack_driver_log_engine.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_net2/mina_net2.ml
- src/lib/network_pool/batcher.ml
- src/lib/pipe_lib/broadcast_pipe.ml
- src/lib/syncable_ledger/syncable_ledger.ml
- src/lib/timeout_lib/dune
- src/lib/timeout_lib/timeout_lib.ml
- src/lib/transition_frontier/extensions/transition_registry.ml
- src/lib/transition_frontier_controller/transition_frontier_controller.ml
- src/lib/transition_handler/processor.ml
This reverts the `Ivar.fill` to `Ivar.fill_if_empty` change, and adds a couple of missing logs.
We still want to crash, since the `fill` is likely to be a logic error; the logs will tell us where this crash came from so we can fix it.
Checklist:
> Ivar.fill_if_empty -> Ivar.fill

- src/lib/mina_lib/mina_lib.ml
> Fix: Don't use successor when calculating the ledger nonce

- .circleci/config.yml
- .circleci/config.yml.jinja
> Fix CI: Bump opam cache version number

- graphql_schema.json
- scripts/run_local_network.sh
- src/app/archive/archive_lib/extensional.ml
- src/app/archive/archive_lib/graphql_query/base_types.ml
- src/app/archive/archive_lib/processor.ml
- src/app/archive/archive_lib/rpc.ml
- src/app/cli/src/init/client.ml
- src/app/cli/src/init/graphql_queries.ml
- src/app/missing_subchain/missing_subchain.ml
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/mina_lib/archive_client.ml
- src/lib/mina_lib/archive_client.mli
Add ability to archive the extensional blocks produced by the missing subchains app.
Change: `advanced archive-precomputed-blocks` becomes `advanced archive-blocks`, which takes either `-precomputed` or `-extensional` as an additional flag.
There's an attempt here to share code for the two kinds of blocks, as much as possible.
Tested by deleting data in an archive db, and re-adding that data, and verifying result was as before (modulo intensional data like table ids). Tested using the GraphQL and direct-to-archive-process routes. The testing wasn't exhaustive, that might be part of the acceptance tests.
Fixed a bug in the missing subchains app, there was a mixup between staking, next epoch data.
In the archive lib, changed the processor SQL queries to use OCaml multiline strings using …
> Archive extensional blocks

- src/app/generate_keypair/generate_keypair.ml
- src/lib/cli_lib/commands.ml
The `generate_keypair` app was silently using a password from `CODA_PRIVKEY_PASS`, without informing the user. (I got bitten by this cur today.)
Print a message when the environment variable is used.
Also, add a newline when the pubkey is printed.
> Inform user when CODA_PRIVKEY_PASS used

- src/app/cli/src/coda.ml
- src/lib/secrets/keypair_common.ml
For client commands that require a private key password, print a message when the password is obtained from an environment variable.
For daemon commands, issue an `info` log in the same circumstance.
Changed a "secret key" to "private-key", to conform to other usage.
Note: we're using the same environment variable for all private keys. Is that acceptable?
> Print or log when private-key password from env var

- src/app/cli/src/coda.ml
- src/lib/mina_net2/mina_net2.ml
- src/lib/mina_net2/mina_net2.mli
Create a user error for `peer` arguments to the daemon. The check does not guarantee a valid multiaddress, only that it can be turned into a `Peer.t`, which just does some simple string-splitting. The check should catch gross errors, like using a peer list file.
Example failure:
```
FATAL ERROR
☠  Coda Daemon encountered a configuration error decoding peer as a multiaddress.
The given peer "foobar" is not a valid multiaddress (ex: /ip4/IPADDR/tcp/PORT/p2p/PEERID)
```
Q: Why does our `to_peer` function for multiaddresses insist on IPv4?
Closes #7267.
> User error for some faulty peer multiaddresses

- src/lib/memory_stats/memory_stats.ml
Add `fragments` to the OCaml memory stats. Mention `bytes` explicitly for relevant statistics (wasn't obvious).
> OCaml memory stats, add fragments, mention bytes

- src/lib/mina_lib/coda_subscriptions.ml
Don't put precomputed block in log message; do put its state hash. Keep the precomputed block in the `metadata`.
Closes #7395.
> Don't interpolate precomputed block

- src/lib/mina_metrics/mina_metrics.ml
Add OCaml heap fragments to the GC statistics in `Mina_metrics`.
> OCaml heap fragments in metrics

- src/lib/transition_handler/processor.ml
This PR fixes a bug in processor.ml, where we invalidate cached transitions twice if validation fails.
We are using Cached.sequence_result which would automatically invalided the cached item if failed, so do not need to invalidate it by hand.
This would make the crash in #7560 goes away.
> do not invalidate cached item twice

- src/lib/mina_net2/mina_net2.ml
This PR removes the `Ivar.t`s from `outstanding_requests` in `Mina_net2` when a shutdown is detected.
This avoids a double-fill when
* we perform a scheduled restart of libp2p_helper (or it crashes and we restart it) in `Gossip_net.Libp2p.create`
* there is some message read from stdout of libp2p_helper, and the scheduler yields before handling it
* the termination handler in `Mina_net2` fills all unfilled `Ivar.t`s with an error state
* the scheduler resumes the message handling, which attempts to fill the now-filled `Ivar.t`.
A backtrace indicating this logic (or, at least, the final step) was posted on discord in the `development` channel.
Checklist: …
> Ivar.fill crash fix: Remove outstanding_requests ivars during libp2p_helper shutdown/restart

- automation/terraform/modules/kubernetes/testnet/helm.tf
- automation/terraform/modules/kubernetes/testnet/testnet-artifacts.tf
- automation/terraform/modules/kubernetes/testnet/variables.tf
- src/app/libp2p_helper/src/codanet.go
- src/app/libp2p_helper/src/libp2p_helper/main.go
- src/app/test_executive/peers_test.ml
- src/lib/integration_test_cloud_engine/coda_automation.ml
- src/lib/key_cache/key_cache.ml
- Made changes to automation configuration to support integration test framework again (will need to discuss with infra before landing).
- moved back to `runtime_config` var instead of `genesis_ledger.json`; requires change to existing testnet configs
- Made changes to libp2p_helper to address connectivity issues.
- half tested, seems promising, but requires some more iteration to confirm
- probably needs chainsafe review
> Update and fix integration test framework

- src/app/archive/archive_lib/processor.ml
- src/app/rosetta/bootstrap_balances.json
- src/app/rosetta/lib/account.ml
- src/app/rosetta/lib/block.ml
- src/app/rosetta/test-agent/agent.ml
- src/app/rosetta/test-agent/poke.ml
- src/lib/bootstrap_controller/bootstrap_controller.ml
- src/lib/mina_base/account.ml
- src/lib/user_command_input/user_command_input.ml
Miscellaneous small fixes and additions to support adding historical balance lookups to Rosetta (https://github.com/MinaProtocol/mina/pull/7114).
Ran Rosetta test suite successfully.
Checklist:
- [ x Tests were added for the new behavior
> Misc. intermediate commits for support for historical balance lookups in Rosetta

- graphql_schema.json
- src/lib/mina_graphql/mina_graphql.ml
Add a query `block` in GraphQL that takes a `stateHash` string, and returns a block with that state hash, using the same format as the blocks returned by `bestChain`.
Closes #7404. Well, maybe, it doesn't support querying by height. Should we provide that as a separate query? I think we'd need to linear search through all breadcrumbs to support that, or add additional indexing to support such a query.
> Block query in GraphQL

- src/app/cli/src/coda.ml
- src/app/generate_keypair/dune
- src/app/generate_keypair/generate_keypair.ml
- src/lib/mina_version/dune
- src/lib/mina_version/gen.sh
- src/lib/mina_version/mina_version.mli
Allow `-version` and `version` as arguments to `generate_keypair.exe`, and print the version.
Moved `print_version_info` from `coda.ml` to `Mina_version.print_version`, so that any executable can print a version in the same way.
As in `coda.ml`, we have to intercept `Sys.argv` to handle these flags, because the Jane St version relies on a script we're not using.
Example output:
```
Commit 3ea902875ddfbf1d06f5138045f91fd63dd4bfe0 on branch feature/version-for-generate-keypair
```
> Print version in generate-keypair

- graphql_schema.json
- src/app/rosetta/lib/account.ml
- src/lib/graphql_lib/decoders.ml
- src/lib/mina_graphql/mina_graphql.ml
- Adds new `liquid` and `locked` fields to `AnnotatedBalance` that are set whenever we have sufficient bootstrapping information to compute them.
- Updates Rosetta business logic to use the liquid balance for `/accounts/balance` requests instead of total balance, as required by the Rosetta spec. (Also makes it so `/accounts/balance` requests error out when no liquid balance is available, which would have happened anyway for other reasons.)
To test I ran Rosetta with a genesis ledger including time-locked accounts and confirmed that pre-cliff, cliff, and vesting periods all worked by `curl`ing for balances over time.
Checklist:
> Add liquid and locked balances to GraphQL, use liquid in Rosetta

- src/lib/mina_graphql/mina_graphql.ml
Allow `height` argument to QraphQL `block` query.
With this change, the query requires exactly one of `height` or `stateHash` (allowing both would not be sensible, I think).
Tested against a local network.
> Height input to block query

- automation/terraform/modules/kubernetes/buildkite-agent/google_cloud.tf
- automation/terraform/modules/kubernetes/buildkite-agent/helm.tf
- automation/terraform/modules/kubernetes/buildkite-agent/secrets.tf
- automation/terraform/modules/kubernetes/buildkite-agent/variables.tf
* add var for and set default agent testnet k8s ctx
* add agent entrypoint for terraform install 
* add kube config to shared DIR between agent and dind containers
* update agent service account roles for terraform testnet provisioning
Redirects changes from https://github.com/MinaProtocol/mina/pull/7457 (targeting `develop`)
Checklist:
> update default CI k8s ctx and tooling

- src/app/cli/src/coda.ml
- src/lib/block_producer/block_producer.ml
- src/lib/logger/impl.ml
- src/lib/logger/impl.mli
- src/lib/logger/logger.ml
- src/lib/transition_frontier/extensions/best_tip_diff.ml
- src/lib/transition_router/initial_validator.ml
A separate log file `mina-rejected-blocks.log` for rejected blocks. This is to understand the impact of blocks being missed/not broadcasted fast enough
(tracked here https://github.com/MinaProtocol/mina/issues/7338)
> log file for rejected blocks

- src/lib/child_processes/child_processes.ml
- src/lib/child_processes/child_processes.mli
- src/lib/child_processes/dune
- src/lib/mina_net2/mina_net2.ml
- src/lib/verifier/prod.ml
This PR catches and handles WNOHANG errors that the libp2p_helper and verifier subprocess monitors may cause via `Process.wait`.
I suspect most of these were caused by races between creating/stopping the processes and the calls to wait. Subtly different behaviour in OS X's process creation and/or waiting syscalls may explain the higher prevalence of these errors on Macs.
**Open question: Should we retry before failing? If so, under what conditions, with what time delay, etc.?**
It's worth noting that we could leak started processes if the OS starts the subprocess after both the wait and the attempted kill have already executed.
This is very likely to fix the WNOHANG errors mentioned in #6951, #4480. This may also fix
* #4297 (old, so it's not clear from the stacktrace)
* #3706 (refers to …
> Handle WNOHANG exceptions from verifier and libp2p_helper processes

- buildkite/scripts/build-artifact.sh
- scripts/rebuild-deb.sh
- src/app/cli/src/init/client.ml
- src/app/validate_keypair/dune
- src/app/validate_keypair/validate_keypair.ml
- src/lib/cli_lib/commands.ml
- src/validate_keypair.opam
New `validate_keypair` app, and command `advanced validate-keypair`.
As with `generate-keypair`, the app and command use `CODA_PRIVKEY_PASS`, if set, and prompt for a password otherwise, and both take the `privkey-path` flag.
Validation consists of signing a dummy transaction and verifying the signature.
TODO: add a test of the keys using the VRF machinery (as commented in the code).
Update: won't add VRF bits, see comment below.
Example session:
```
$ coda advanced validate-keypair -privkey-path ~/keys/flimflam
Enter password: 
Again to confirm: 
Verified a transaction using specified keypair
```
> Validate keypair app and command

- scripts/rebuild-deb.sh
Remove keypair validator binary, so it doesn't appear in Mina .deb.
Otherwise, if you install both the keypair-generator and Mina .debs, you'll get an error.
> Remove keypair validator binary

- src/app/archive/archive_lib/processor.ml
- src/app/archive/create_schema.sql
- src/app/missing_subchain/missing_subchain.ml
- src/app/rosetta/lib/block.ml
- src/app/rosetta/lib/dune
- Updates archive DB schema to move columns
- Updates Archive_lib.Processor so the Transaction_status.t object is
passed to Block_and_signed_command insertion instead of to
User_command insertion
- Updates Rosetta Block code to handle the new schema when retrieving
these columns
- Temporarily removes code in missing_subchain.ml that converted
Archive_lib.Processor user commands to Extensional user commands since
they'll now require an additional query
Checklist:
> Move user command status columns to blocks_user_commands

- src/app/archive/archive_lib/processor.ml
- src/app/missing_subchain/missing_subchain.ml
Modify missing subchains tool to use the new archive db schema. In particular, take data from `blocks_user_commands` that had been in `user_commands`, and place it in an `Extensional.User_command.t`.
Tested by generating a fresh archive db from Rosetta, generating JSON files for the entire chain using the missing subchains app, ingesting those blocks using `advanced archive-blocks -extensional`.
> Missing subchains, use new schema

- frontend/client_sdk/src/CodaSDK.d.ts
- frontend/client_sdk/src/CodaSDK.re
- frontend/client_sdk/test/Test.ts
This PR implements the publicKeyOfPrivateKey function which returns a public key corresponding to a private key.
> Client SDK: Added functionality to get public key from private key

- src/lib/cli_lib/flag.ml
```
[-log-level LEVEL]                                 Set log level
(Spam|Trace|Debug|Info|Warn|Error|Faulty_peer|Fatal,
default: Info)
[-file-log-level LEVEL]                            Set log level for the log
file
(Spam|Trace|Debug|Info|Warn|Error|Faulty_peer|Fatal,
default: Trace)
```
Note that this doesn't put the the level next to the flag, since it moves the alignment of the rhs doc comments right significantly, to the point of their being unreadable.
Checklist:
Closes #7630
> Add list of levels to -log-level

- src/lib/network_pool/indexed_pool.ml
This PR fixes a potential error path and changes the exception that is thrown to make it easier to debug in future. Related issues #7668 and #7661.
Checklist:
> Verify cmds before recursively adding to the pool, throw useful errors

- src/app/cli/src/coda.ml
- src/lib/child_processes/termination.ml
For some signals (namely, SIGKILL and SIGINT), log a possible cause when a child process terminates. 
There's an extensible table of signals-to-causes, if more such signals have plausible explanations.
Closes #7620.
> Explain some terminating signals

- Makefile
- buildkite/scripts/ci-archive-release.sh
- scripts/archive/build-release-archives.sh
- src/app/archive/archive_lib/processor.ml
- src/app/archive_blocks/archive_blocks.ml
- src/app/archive_blocks/dune
- src/archive_blocks.opam
Standalone app `archive_blocks` for ingesting precomputed or extensional blocks into an archive database. 
The app works much like the CLI `advanced archive-blocks` command. The benefit of the app is that you don't need to be running a daemon or archive process.
(While the functionality is the same, the slight differences made it seem not worth trying to factor out common code.)
The flags for the app are basically the same as for the CLI command, except that the connection is directly to the Postgresql server, and not the daemon or its GraphQL port.
Usage:
```
Write blocks to an archive database
archive_blocks.exe [FILES ...]
=== flags ===
-archive-uri URI              URI for connecting to the archive database
(e.g.,
postgres://$USER:$USER@localhost:5432/archiver)
[-extensional] …
```
> Archive_blocks app

- src/lib/marlin_plonk_bindings/stubs/src/caml_pointer.rs
This PR changes the behaviour of `CamlPointer` so that it uses a refcounted shared pointer instead of a raw pointer. This fixes a double-free: cloning a `CamlPointer` would result in 2 references to the same pointer, and each would be freed by the finaliser.
Checklist:
> Fix a segfault: Use reference counted pointers for CamlPointer

- frontend/ci-build-me/src/index.js
Adds a new pipeline and soon a status-check for mainnet gating of PRs into the ci-build-me-bot.
I'll use this PR to test the logic of the bot.
> PR mainnet gating for build-me-bot

- src/lib/mina_graphql/mina_graphql.ml
Use `Deferred.List.map` to compute the blocks returned by the `best_chain` GraphQL query. That should allow other `Async` tasks to run when processing each block.
N.B.: the default `~how` for the map is `Sequential`.
Change in behavior: if the chain is unavailable, return an error, rather than `null`.
Closes #7706.
> Async list map for `best_chain` GraphQL query

- src/app/archive/archive_lib/processor.ml
- src/app/archive_blocks/archive_blocks.ml
Added retry logic for database writes to support concurrent database transactions (described [here](https://github.com/MinaProtocol/mina/issues/7567)). This also requires setting transaction isolation level to 'serializable' and can be done in two ways:
1. set it as the default isolation level in postgresql.conf:
`default_transaction_isolation = 'serializable'`
2. set it for a specific database using the following query
`ALTER DATABASE <DATABASE NAME> SET DEFAULT_TRANSACTION_ISOLATION TO SERIALIZABLE ;` 
They need to be done as a separate step before archive node starts writing (and before bringing up the database instance in the case of option 1). I think setting it at the db level makes it explicit and therefore is a better option, but i'm not quite sure where in the codebase this …
> archive node retries

- automation/scripts/generate-keys-and-ledger.sh
- automation/terraform/modules/kubernetes/testnet/helm.tf
- automation/terraform/modules/kubernetes/testnet/testnet-artifacts.tf
- automation/terraform/modules/kubernetes/testnet/variables.tf
- automation/terraform/testnets/ci-net/main.tf
- buildkite/src/Command/DeployTestnet.dhall
- buildkite/src/Jobs/Test/DeployTestnetAndDestroy.dhall
`terraform workspace` basically allows management of multiple related states via a single state file ([see](https://www.terraform.io/docs/language/state/workspaces.html#using-workspaces) for more details).
Also reduce time after *apply* to *destroy* deployment during DeployAndDestroy test and add a variable for the path for testnet artifacts to be stored/processed locally.
Checklist:
Closes #7701
> use terraform workspaces for managing CI deployment states

- src/config/features/dev.mlh
- src/config/features/public_testnet.mlh
- src/config/testnet_postake_medium_curves.mlh
- src/lib/hash_prefix_states/dune
- src/lib/hash_prefix_states/hash_prefix_states.ml
- src/lib/hash_prefixes/hash_prefixes.ml
- src/lib/signature_lib/schnorr.ml
This PR modifies the signature scheme so that signatures on testnets bear no relation to signatures on mainnet.
> Vary signature for mainnet

- src/lib/mina_base/coinbase.ml
- src/lib/mina_base/coinbase.mli
- src/lib/mina_base/fee_transfer.ml
- src/lib/mina_base/fee_transfer.mli
- src/lib/mina_base/fee_with_prover.ml
- src/lib/mina_base/transaction.ml
- src/lib/network_pool/snark_pool.ml
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/staged_ledger/staged_ledger.mli
- src/lib/transition_frontier/frontier_base/breadcrumb.ml
This checks snark work before entering it into the pool, to make sure that it doesn't have an invalid public key attached. This also validates the public keys in fee transfers and coinbases while checking an external transition.
**We should hold off on merging this.** The block containing the fee transfer that triggered this bug may still be passed around the network, and running a node with this change will make it ban any others that share this block with it.
Checklist:
Closes #7656
Closes #7658
> Reject invalid public keys from the snark pool and in snark pool diffs

- src/app/archive/archive_lib/extensional.ml
- src/app/archive/archive_lib/processor.ml
- src/app/missing_subchain/block.ml
- src/app/missing_subchain/dune
- src/app/missing_subchain/missing_subchain.ml
- src/app/missing_subchain/sql.ml
Add balances to user, internal commands in `Processor.Extensional`. Process the balances in the missing subchains tool.
This is the biggest piece of #7344. Will update the replayer to verify the balances after this is merged.
> Add balances to extensional commands

- src/app/client_sdk/client_sdk.ml
In the client SDK, the verification methods for payments and delegation were returning an OCaml bool, which Javascript sees as an int.
Return an explicit Javascript boolean, which matches what we were already doing for verifying signed strings.
#7767, which wraps these methods for the distributed SDK, will use this change.
> Client SDK, return JS bool from verifiers

- frontend/client_sdk/src/CodaSDK.d.ts
- frontend/client_sdk/src/CodaSDK.re
- frontend/client_sdk/test/Test.ts
1. Adds the functionality for `verifyPaymentSignature` and `verifyStakeDelegationSignature` to the Client SDK. 
2. Added tests for the newly implemented features.
> Client SDK: Implement verifyPaymentSignature and verifyStakeDelegationSignature

- src/app/client_sdk/client_sdk.ml
- src/app/client_sdk/js_util.ml
- src/lib/cli_lib/commands.ml
For the key validation in CLI, and the separate executable, check that the on-disk `.pub` file contains the same Base58Check public key as is derived from the on-disk private key. The existing validator synthesized the public key from the private key, without examining the public key file at all. So you could have relied on the validator giving a positive result, given a good private key file, while the public key file could have been missing, or contained anything whatsoever.
Tested using the daemon `advanced validate-keypair` command, with good and bad keypaths.
Similarly, for the client SDK, add a method `validKeypair`, which checks that the contained public key is derivable from the private key. Further, like the CLI command, try to sign a dummy transaction. If the method succeeds, …
> Key validation improvements

- buildkite/src/Command/DeployTestnet.dhall
Set artifact upload dest envvar following pushd to maintain value.
Checklist:
> Fix CI deploy testnet artifact upload logic

- graphql_schema.json
- src/lib/mina_graphql/mina_graphql.ml
This PR exposes the Account_timing information on an account in our GraphQL.
This was tested by using a ledger that had time-locked accounts enabled as well as normal accounts. Manual queries were done to ensure correctness.
Timed Account:
Normal Account:
**Note**
This PR is the same as https://github.com/MinaProtocol/mina/pull/7600 but was made because of the repo changes made recently.
> Feature: Expose Account Timing in GraphQL

- src/app/archive/archive.ml
- src/app/archive_blocks/archive_blocks.ml
- src/app/best_tip_merger/best_tip_merger.ml
- src/app/cli/src/coda.ml
- src/app/cli/src/init/client.ml
- src/app/cli/src/init/transaction_snark_profiler.ml
- src/app/cli/src/tests/coda_long_fork.ml
- src/app/cli/src/tests/coda_restarts_and_txns_holy_grail.ml
- src/app/cli/src/tests/coda_shared_prefix_multiproducer_test.ml
- src/app/cli/src/tests/coda_shared_prefix_test.ml
- src/app/reformat/reformat.ml
- src/app/rosetta/lib/rosetta.ml
- src/app/rosetta/ocaml-signer/signer.ml
- src/app/rosetta/test-agent/agent.ml
- src/lib/cli_lib/flag.ml
- src/lib/snark_worker/functor.ml
This converts all our non-POSIX-compliant flags to POSIX-compliant ones. The original forms are preserved as aliases, so all our scripts etc. should still work.
This also fixes a flag where the default argument was part of the name 🤦‍♂️ 
Checklist:
> Use posix-style flags by default

- src/app/archive/archive.ml
There was a flag the same as an alias in `Archive`. The executable refused to run, complaining of the duplicate.
> Fix duplicate flag in archive

- graphql_schema.json
- src/app/cli/src/init/client.ml
- src/app/cli/src/init/graphql_queries.ml
- src/lib/mina_graphql/mina_graphql.ml
This fixes #7838, which was caused by #7751.
Checklist:
Closes #7838
> Fix addPeers graphql endpoint and command

- src/app/libp2p_helper/src/codanet.go
- add conn direction check, return if not outbound (ie. we didn't initiate the connection)
- fix go func scoping
- only return peers if they have non-empty `AddrInfo`
`go test ./... -run TestGetPeerMessage -v`
Checklist:
Closes #0000
Closes #0000
> libp2p helper: add conn direction check to peer exchange, other fixes

- src/app/libp2p_helper/src/codanet.go
This PR fixes 2 issues in the initial peer exchange
1. It fixes a "for loop" scoping bug which causes a go routine to capture the final iteration value of a loop variable than the value at that iteration.
2. It allows non-seed nodes to provide us with new peers. In a follow up, we should check that we only allow one such inbound stream at a time from peers, and that it should only be from peers that we have ourselves connected to, rather than peers that have connected to us.
> fix peer exchange bugs

- src/app/cli/src/coda.ml
- src/app/cli/src/init/client.ml
- src/lib/cli_lib/flag.ml
- src/lib/cli_lib/flag.mli
Move the `dump-ledger` and `dump-staking-ledger` subcommands from `advanced` to a new `ledger` command.
For both of those, the default output is JSON; using `--plaintext` produces an S-expression.
First baby steps towards #7737.
> Move ledger dumps to ledger subcommand

- src/app/cli/src/init/client.ml
Command description:
```
$ _build/default/src/app/cli/src/coda.exe advanced compute-receipt-chain-hash -help
Compute the next receipt chain hash from the previous hash and transaction ID
coda.exe advanced compute-receipt-chain-hash
=== flags ===
--previous-hash HASH  Previous receipt chain hash, base58check encoded
--transaction-id ID   Transaction ID, base58check encoded
[-help]               print this help text and exit
(alias: -?)
```
As described in the MainNet prio meeting, all this does is surface the function from `Mina_base` to the CLI.
Checklist:
> Add advanced command for computing receipt chain hash

- src/app/rosetta/lib/account.ml
- src/app/rosetta/lib/network.ml
Depends on https://github.com/MinaProtocol/mina/pull/7680
Adds support for historical balance lookups in Rosetta via queries to the balance tables in the archive DB.
Testing:
- Ran `./start.sh` and saw it passes
- Ran Rosetta CLI and saw that it still passes all past conditions and still fails on time-locked accounts
TODO:
- Write additional tests for `./start.sh` suite
- Waiting to hear back from the Rosetta team regarding this edge case https://community.rosetta-api.org/t/historical-balance-requests-with-block-identifiers-from-before-account-was-created/369 (but I think we can merge without it)
Checklist:
> Add support for historical balance lookups in Rosetta

- src/app/rosetta/lib/cli.ml
- src/app/rosetta/lib/rosetta.ml
Refactors the Rosetta server code so the archive URI is optional and only used to instantiate a DB connection/pool when a request is made to a top-level route that may need it (i.e., any route other than `construction/*`).
To test I ran Rosetta's test suite and saw it still passes with the existing parameters; then started Rosetta without the `archive-uri` parameter set (along with Mina running without `archive-address` set) and made sure `construction/*` routes worked but others failed gracefully.
TODO:
- This means the first non-`construction/*` call to any Rosetta server will be slower than normal since it needs to instantiate the DB connection. Is this okay?
- We previously were just returning `Deferred.unit` when failing to connect to the DB (when an archive URI was passed); this now …
> Make it so Rosetta construction routes don't need archive URI/connection/pool

- src/app/cli/src/init/client.ml
- src/lib/cli_lib/flag.ml
Add subcommand `ledger hash`, which prints out the Merkle root of ledgers created via `ledger export`.
Usage:
```
$ coda ledger hash -help
Print the Merkle root of the ledger contained in the specified file
coda.exe ledger hash 
=== flags ===
--ledger-file LEDGER-FILE                 File containing an exported ledger
[--daemon-port HOST:PORT/LOCALHOST-PORT]  Client to local daemon
communication. If HOST is omitted,
then localhost is assumed to be
HOST. (examples: 8301,
154.97.53.97:8301) (default: 8301)
(alias: -daemon-port)
[--plaintext]                             Use plaintext input or output
(default: JSON)
(alias: -plaintext)
```
(For `ledger export`, changed `current-staged-ledger` ledger kind to just `staged-ledger`, since providing a state hash gives you a non-current ledger.) …
> Print ledger hashes

- automation/terraform/modules/o1-integration/inputs.tf
- automation/terraform/modules/o1-integration/locals.tf
- automation/terraform/modules/o1-integration/secrets.tf
- automation/terraform/modules/o1-integration/testnet.tf
- src/app/test_executive/README.md
- src/config/integration_tests.mlh
- src/lib/integration_test_cloud_engine/coda_automation.ml
- src/lib/integration_test_cloud_engine/terraform.ml
Depends on https://github.com/MinaProtocol/mina/pull/7854. Do not merge until that is merged.
This PR contains a new `o1-integration` terraform module, and reworks the `integration_test_cloud_engine` to deploy off of that. Integration tests are passing now against images built off of `develop`. See the new `src/app/test_executive/README.md` for updated details on running integration tests.
> New Integration Terraform Module 

- automation/README.md
> add automation documentation regarding setting terraform kube config path

- buildkite/src/Command/TestExecutive.dhall
Per https://github.com/MinaProtocol/mina/issues/7945, skip and NOOP while failures are investigated.
Checklist:
Closes #0000
Closes #0000
> skip integration test execution while failures are investigated

- src/lib/mina_lib/mina_lib.ml
Remove the code that starts a shutdown timer when a node is `Offline`.
Tested that the sync status still updates with `client status` on a local network.
Closes #7970.
> Remove offline timeout shutdown, log instead

- src/app/genesis_ledger_from_tsv/genesis_ledger_from_tsv.ml
Allow more possible words in the spreadsheet to indicate a pending wallet public key.
Use `pretty_to_string` for the JSON output, so we don't have to use `jq` or other beautifier post-hoc.
Tested with the latest spreadsheet.
> More pending public keys, pretty output

- src/app/rosetta/lib/account.ml
- src/app/rosetta/lib/block.ml
- src/app/rosetta/lib/mempool.ml
- src/app/rosetta/lib/network.ml
- src/app/rosetta/lib/rosetta.ml
This makes the pool acquisition more granular, only acquiring a resource
from the DB pool for `foo/bar` when `foo/bar` actually uses the DB resource
rather than any time `foo` uses it for any `foo/baz`.
Concretely, this means we now only acquire a DB resource for:
- `network/status`
- `account/balance`
- `block` and `block/`
Previously we acquired it for all subroutes except `construction/*`.
(Though we actually could've already removed it trivially for `mempool/*`
without this refactor.)
To test I tried hitting `network/list` with `archive-uri` set and unset and saw it works both times. I also confirmed that before this change if `archive-uri` wasn't set it returned a SQL error. I also ran the Rosetta test suite and `rosetta-cli` tests. 
Checklist:
Closes #7690 
Closes #8001
> Make Rosetta DB acquisition more granular

- src/lib/genesis_proof/genesis_proof.ml
- src/lib/mina_state/blockchain_state.ml
- src/lib/mina_state/blockchain_state.mli
- src/lib/mina_state/genesis_protocol_state.ml
- src/lib/mina_state/protocol_state.ml
- src/lib/mina_state/snark_transition.ml
- src/lib/mina_state/snark_transition.mli
This fixes a bug where the genesis block has a timestamp relative to
genesis state (0) rather than relative to UTC epoch (~50 years). All
other blocks already had correct timestamps relative to UTC epoch.
Tested changes by running Rosetta's `./start.sh` and `rosetta-cli`.
Checklist:
Closes #6700
> Use genesis time instead of UTC epoch for initial Blockchain_state

- automation/terraform/modules/kubernetes/buildkite-agent/helm.tf
In preparation of supporting terraform `optionals` and additional upgrades to the operational terraform tooling used in CI, add custom versions of tools like terraform to the Buildkite agent shared DIR (accessible on agents and in launched docker containers).
Checklist:
> add terraform v0.14.7 to shared buildkite agent DIR

- automation/terraform/infrastructure/testnet-alerts.tf
Update testnet monitoring infra to alert to Pagerduty on *testworld, encore and zenith* testnet alert violations. 
Checklist:
> Add encore + zenith testnets to Pagerduty monitoring and alerting set

- automation/terraform/infrastructure/testnet-alerts.tf
> Applying retroactively - only alert to PagerDuty on zenith testnet check violations.

- src/lib/consensus/intf.ml
- src/lib/consensus/proof_of_stake.ml
- src/lib/transition_frontier/full_frontier/full_frontier.ml
1. Local state sync (at epoch 1 after a hardfork) fails because the node is requesting genesis epoch ledger.
When the epoch snapshot that needs to be synced is genesis epoch ledge, we do `staking snapshot = next snapshot`. However, local state is mutable and when syncing, `next snapshot` gets updated with the new `next snapshot` from a peer before the staking snapshot is updated. Therefore, target `staking snapshot` now (next epoch ledger from genesis) doesn't match `next snapshot` and so the node requests for it from peers.
Fixed this by syncing `staking snapshot` before `next snapshot`.
2. Increased the peers to query from 3 to 5.
3. updated the epoch ledger cleanup logic to check both the epoch ledgers determined by the uuids stored are present
Tested the changes locally by connecting …
> Epoch ledger sync fix

- automation/terraform/infrastructure/us-central1.tf
- automation/terraform/infrastructure/us-east1.tf
- automation/terraform/infrastructure/us-east4.tf
- automation/terraform/infrastructure/us-west1.tf
Adding `<region>` to infra's storage class naming scheme is redundant as storage classes are scoped by region/cluster. Also, relying on regions when specifying defaults can be problematic and generally unnecessary (at least in this case). 
Checklist:
> Remove <region> from infra kubernetes storage class naming scheme

- src/app/rosetta/lib/construction.ml
- src/app/rosetta/lib/rosetta.ml
- src/lib/rosetta_lib/errors.ml
- Make the graphql_uri param optional on a CLI level
- Add a new Graphql_uri_not_set error
- Return the new error for network/*, account/*, mempool/*, block/*,
construction/metadata, construction/parse, and construction/submit
- Currently all network/*, account/*, mempool/*, and block/* routes
require GraphQL but this makes it easy to refactor those to have it
only required for certain subroutes
To test:
- Manually tested `construction/derive` endpoint with and without `graphql_uri` set, saw it still works both with and without it set
- Manually tested `construction/metadata` endpoint without `graphql_uri` set, saw it returns a clear error when it's not set
- Ran Rosetta test suite
- Ran rosetta-cli
Checklist:
- Document test purpose, …
> Make Rosetta graphql_uri param optional

- automation/terraform/buildkite/buildkite-experimental/main.tf
- automation/terraform/infrastructure/main.tf
- automation/terraform/modules/kubernetes/buildkite-agent/helm.tf
- automation/terraform/testnets/bug-net/main.tf
- automation/terraform/testnets/bugspray/main.tf
- automation/terraform/testnets/ci-net/main.tf
- automation/terraform/testnets/multiple-seeds-test/main.tf
- automation/terraform/testnets/nightly/main.tf
- automation/terraform/testnets/static-peers-net/main.tf
- automation/terraform/testnets/testworld/main.tf
- automation/terraform/testnets/watchdog-test/main.tf
- automation/terraform/testnets/zenith/main.tf
`v0.14.7` should be compatible with existing terraform configs (both **testnets** and **buildkite**) so it's safe to loosen *required_versions* across the board. Also the *0.14.x* version family is required for upcoming changes to how multiple instances of testnet components are deployed (see: https://github.com/MinaProtocol/mina/pull/7781 for example).
Checklist:
> set base CI terraform version to 0.14.7 and update infra + testnet minimum supported versions

- src/lib/mina_graphql/mina_graphql.ml
Adds the field `stagedLedgerEmittedProof` to the `protocolState` which allows us to detect when the staged ledger fills up and emits a new proof. This will be used in the Local Test Framework to validate the protocol is working as expected.
> GraphQL: Add field for Staged Ledger proof emission

- src/app/rosetta/lib/block.ml
- src/app/rosetta/make-runtime-genesis.sh
- src/app/rosetta/test-agent/agent.ml
- src/app/rosetta/test-agent/peek.ml
Depends on #7992 (first commit).
- Makes it so we use block genesis `date` instead of `utcDate` in Rosetta
- Adds a time-locked account to the Rosetta test genesis ledger
- Adds code to Rosetta test-agent/agent.ml to check the time-locked
account's balance at each index and confirm it matches what we expect
- Doesn't add the new account to the rosetta-cli bootstrap_balances
because we don't have a way yet to mark the account as balance exempt
(we're still waiting to hear back from Coinbase on that)
- Doesn't yet test a more complex situation with a time-locked accounts
that actually encounters internal and user commands
Checklist:
> Add Rosetta test for historical balance lookup, fix Rosetta date bug

- buildkite/src/Jobs/Lint/TestnetAlerts.dhall
- buildkite/src/Jobs/Release/TestnetAlerts.dhall
Testnet alert jobs in CI are currently failing due to the recent `terraform` version upgrade and their existing state file being based on the 0.12.x tool versions (see for [example](https://buildkite.com/o-1-labs-2/mina/builds/12721#402961df-0746-4e64-bf94-40ad274ce820). A resolution for this issue is pretty straightforward though unblock/only soft-fail on such failures during it is committed.
```
Error: Invalid legacy provider address
This configuration or its associated state refers to the unqualified provider
You must complete the Terraform 0.13 upgrade process before upgrading to later
---
```
Checklist:
> soft-fail testnet alert jobs while terraform state is updated to support 0.14.x terraform wersions

- buildkite/src/Jobs/Release/MinaArtifact.dhall
- src/lib/mina_version/gen.sh
I confirmed that the `coda-daemon` image buildkite built on this branch no longer has the dirty version.
```
root@5180ce164c23:~# mina version
Commit c80d8b8f87ba6243a30f2b26d0b0b7e47b21e566 on branch fix/undirty-buildkite-artifacts
```
> Remove dirty message from buildkite artifact versions

- automation/terraform/modules/o1-integration/testnet.tf
Fixes an integration test error related to the missing variables ([example](https://buildkite.com/o-1-labs-2/mina/builds/12859#57b441b2-5ed1-4462-97bb-f8c65b4d44bd)).
**Checklist:**
> add required archive vars to block-producer and seed-node specs in o1-integration module

- buildkite/src/Jobs/Lint/TestnetAlerts.dhall
- buildkite/src/Jobs/Release/TestnetAlerts.dhall
> update testnet alert terraform -targets based on new location

- src/lib/mina_graphql/mina_graphql.ml
Guard against underflow when computing "liquid" balances for accounts in GraphQL.
Verified that 
- `Unsigned.UInt64.sub` does not check for underflow
- The numbers in the first example in #8083 produce the anomalous result when applying `sub`
- Using `Unsigned.UInt64.compare` as a guard can detect the underflow
The calculation here is only used by GraphQL.
Closes #8083.
> Guard against underflow when computing liquid balance

- graphql_schema.json
- src/lib/filtered_external_transition/filtered_external_transition.ml
- src/lib/mina_graphql/mina_graphql.ml
Added a new string field `type` to the fee transfer in graphql for queries that return blocks. The value of this field is `Fee_transfer` or `Fee_transfer_via_coinbase`.
`Fee_transfer_via_coinbase` is the fee transfer in a coinbase transaction. This corresponds to the snark worker fee deducted from the coinbase amount. 
All other snark worker fees are deducted from transaction fees. These (and the fee transfer paying the remainder transaction fee to the block producer) have the type `Fee_Transfer`
Ran a node and tested the graphql output of the `best_chain` query
Checklist:
Closes #8072
> [hotfix] fee transfer type in graphql blocks query

- src/lib/mina_graphql/mina_graphql.ml
This is the same fix as in #8096, except based on `master`.
> [HOTFIX] Prevent underflow for liquid balance

- src/app/cli/src/init/client.ml
- src/app/cli/src/init/graphql_client.ml
- src/app/cli/src/mina.ml
- src/lib/child_processes/child_processes.ml
- src/lib/cli_lib/background_daemon.ml
- src/lib/daemon_rpcs/types.ml
- src/lib/mina_lib/mina_lib.ml
Change some uses of `Coda` to `Mina` in UX and logs. In particular, change header line in `client status`, logs like `daemon is listening`, and `daemon -help`.
Partially addresses #8087 (which was the name of an Intel math co-processor, way back when).
> [HOTFIX] Change some Coda to Mina for logs, UX

- automation/services/watchdog/node_status_metrics.py
When merging `master` to `compatible`, there was a conflict. In `master`, I noticed the result of a `node-status` called was being discarded (o, Python!) in the watchdog. 
Restore the assignment of the response. This change is already in `compatible`.
> [HOTFIX] Assign node-status response in watchdog

- src/app/rosetta/lib/construction.ml
- src/app/rosetta/lib/dune
* Use compile-time constant rather than hardcoded
This PR fixes an issue with rosetta `construction/metadata` where it returns a hardcoded default transaction fee.
Instead of returning the hardcoded fee we now return the default fee from the compile-time config `Mina_compile_config.minimum_user_command_fee`
The test agent (`test-agent/agent.ml`) does not have any test cases using the default fee so required no updates.
**Testing:**
Prior to these changes `construction/metadata` returns a hardcoded fee of 1 Mina.  After the change it returns the value from the compile-time constant in one of the `.mlh` files.
Rosetta will now return the default fee depending on the build profile used.  For example, for the production build profile, the `default_transaction_fee` from …
> Make rosetta construction/metadata return the correct default fee

- src/lib/transition_frontier/full_frontier/full_frontier.ml
- src/lib/transition_frontier/full_frontier/full_frontier.mli
- src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
- src/lib/transition_frontier/tests/full_frontier_tests.ml
Change to only update the best tip coinbase metric when the new best tip block is recent.
> only update coinbase metric when the new best tip is recent

- src/app/cli/src/init/client.ml
Remaining Coda mention in a `-help` docstring changed to Mina.
Might be last fix for #8087.
> [HOTFIX] Coda to Mina in visualization docstring

- automation/terraform/monitoring/o1-testnet-alerts.tf
**Test:** Buildkite CI + manual
Checklist:
> Omit testnets deployed by CI/integration tests from monitoring and alerting flow

- automation/terraform/modules/testnet-alerts/templates/testnet-alert-rules.yml.tpl
This PR adds a warning alert for when there are 2 or more nodes on a network which hasn't updated its best tip for 8 slots (24 minutes).
> warning for when > 1 node on a network has an old best tip

- automation/terraform/modules/testnet-alerts/templates/testnet-alert-rules.yml.tpl
Add testnet alerts for tracking the following archive/postgres block stats:
* Coda_Archive_unparented_blocks
* Coda_Archive_max_block_height
* Coda_Archive_missing_blocks
Checklist:
Closes #8063
> Add Archive Postgres block metric alerts

- automation/terraform/monitoring/o1-testnet-alerts.tf
Use regex NOT operator `!~` instead of `?!` syntax ([see](https://prometheus.io/docs/prometheus/latest/querying/basics/#instant-vector-selectors) for details) - Fixes the following metric deployment failure:
```
ERRO[0000] unable parse rules file                       error="163:11: group \"Critical Alerts\", rule 0, \"WatchdogClusterCrashes\": could not parse expression: 1:64: parse error: error parsing regexp: invalid or unsupported Perl syntax: `(?!`" file=alert_rules.yml
```
**Test:** Buildkite CI + Prometheus Explorer + online regex checker
Checklist:
> Fix alert rule regex query filter omitting ci/integration testnets

- buildkite/src/Command/TestExecutive.dhall
- buildkite/src/Jobs/Lint/TestnetAlerts.dhall
- buildkite/src/Jobs/Release/TestnetAlerts.dhall
> ensure reset/full sync of testnet alert state during CI and rename integration test jobs

- src/lib/mina_metrics/mina_metrics.ml
This PR initializes the best tip coinbase metric to "1" so that the alert does not fire inaccurately when a node first starts up.
> initialize best tip coinbase metric to 1

- src/lib/mina_graphql/mina_graphql.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_lib/mina_lib.mli
- src/lib/user_command_input/user_command_input.ml
- src/lib/user_command_input/user_command_input.mli
- Thread `get_account`, `logger`, and `constraint_constants` to `User_command_input.to_user_command`
- Have `User_command.to_user_command` log a warning if it encounters a user command where the receiver doesn't have an account yet and the command has an amount smaller than the account creation fee
TODO:
- A few inline code questions
- Testing
Checklist:
Addresses hotfix part of #8213
> Add warning for txns that can't cover account creation fee

- src/app/genesis_ledger_from_tsv/genesis_ledger_from_tsv.ml
Output individual JSON records for the genesis ledger accounts, without wrapping them in a JSON list. This format is what's needed to process the accounts into the runtime genesis ledger.
Also, check that the initial min balance is less than or equal to the balance.
Tested by using the last devnet spreadsheet, examining the JSON output (before I added the validation). About 40 accounts failed the validation.
> Output JSON accounts, not wrapped in list, for genesis ledger; validate init min balance

- genesis_ledgers/mainnet.json
Checklist:
Closes #0000
Closes #0000
> release/mainnet-v1.1.2 Fix mainnet ledger

- src/app/rosetta/lib/construction.ml
This PR adds the minimum tx fee to the rosetta `construction/metadata` response so that clients can prevent users from creating transactions that would fail to be accepted.  The minimum fee is obtained from the compile-time config `Mina_compile_config.minimum_user_command_fee`
For compatibility with the [Rosetta specification](https://www.rosetta-api.org/docs/models/ConstructionMetadataResponse.html) we've added the additional `"minimum_fee"` information to the metadata property like so
```json
{
"metadata": {
"sender": "B62qnzbXmRNo9q32n4SNu2mpB8e7FYYLH8NmaX6oFCBYjjQ8SbD7uzV",
"nonce": "0",
"token_id": "1",
"minimum_fee": [
{
"value": "1000000",
"currency": {
"symbol": "CODA",
"decimals": 9
}
}
]
},
"suggested_fee": [
{
"value": "250000000",
"currency": {
"symbol": "CODA",
"decimals": 9 …
```
> Add minimum tx fee to rosetta construction/metadata

- src/app/archive/archive.ml
- src/lib/mina_graphql/mina_graphql.ml
Change more user-visible uses of Coda to Mina (GraphQL docstrings, archive executable).
Part of #8087.
> Docstrings, Coda to Mina

- buildkite/src/Command/TestExecutive.dhall
- buildkite/src/Jobs/Lint/TestnetAlerts.dhall
- buildkite/src/Jobs/Release/TestnetAlerts.dhall
Also remove `soft-fails` from testnet alert CI jobs since failures should now be blockers.
Checklist:
> Only execute integration tests on developer/non-mainline branch CI runs

- src/lib/mina_graphql/mina_graphql.ml
This allows `pooledUserCommands` to accept transactions encoded with either hashes or ids, to make them more consistent with `transactionStatus`.
This also can be used to get the hash of a transaction from its ID via GraphQL: you can send the transaction as an ID and query its hash in the output.
Checklist:
Closes #8244
> Accept transactions by ID in pooledUserCommands

- automation/terraform/modules/kubernetes/testnet/kubernetes.tf
- automation/terraform/modules/kubernetes/testnet/locals.tf
- automation/terraform/modules/kubernetes/testnet/variables.tf
- automation/terraform/modules/o1-integration/graphql_ingress.tf
- automation/terraform/modules/o1-integration/inputs.tf
- automation/terraform/modules/o1-integration/testnet.tf
- buildkite/src/Jobs/Release/MinaArtifact.dhall
- dockerfiles/coda_daemon_puppeteer.py
- src/app/test_executive/archive_node_test.ml
- src/app/test_executive/archive_node_test.mli
- src/app/test_executive/payments_timed_accounts_test.ml
- src/app/test_executive/peers_test.ml
- src/app/test_executive/send_payment_test.ml
- src/app/test_executive/test_executive.ml
- src/lib/integration_test_cloud_engine/coda_automation.ml
- src/lib/integration_test_cloud_engine/kubernetes_network.ml
- src/lib/integration_test_cloud_engine/stack_driver_log_engine.ml
- src/lib/integration_test_lib/intf.ml
- src/lib/integration_test_lib/test_config.ml
This PR contains a variety of fixes to the integration test framework to address recent issues. Fixes included:
- graphql ingress race condition (nodes failing to initialize, but initialization log is present)
- context deadline timeout on network destructions
- skip deploying graphql ingresses for tests that do not require it
- pod assignment race condition (very rare, but became more frequent with changes introduced in this PR)
- seed node artifact generation race condition (nodes failing to initialize, unable to find initial peers and restart in time)
> Integration Test Fixes

- automation/terraform/modules/testnet-alerts/templates/testnet-alert-rules.yml.tpl
This PR gates the `NoNewSnarks` alert on the existence of unfilled snark work. This alert has already triggered twice on this network when there is a > 6 minute gap between blocks, but the snark work status of the network is completely fine.
See #8301 for more details.
Checklist:
Closes #8301
> Don't trigger NoNewSnarks alert if there is no unfilled snark work

- buildkite/scripts/run-test-executive.sh
- buildkite/src/Jobs/Release/ArchiveNodeArtifact.dhall
- buildkite/src/Jobs/Test/TestnetIntegrationTests.dhall
- src/app/test_executive/test_executive.ml
Pass an archive image to the test executive for integration tests. This change is in preparation for adding the archive node test. While the image is currently required only for that test, it's no harm to pass it for other tests.
In the test executive, change `archiver` to `archive`, a little less awkward.
> Pass archive image for integration tests

- src/app/cli/src/mina.ml
- src/app/cli/src/tests/coda_process.ml
- src/lib/child_processes/child_processes.ml
- src/lib/child_processes/termination.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/verifier/prod.ml
This PR tweaks the handling of `wait` syscalls throughout the codebase. Specifically,
* it seems unlikely, but we may be mishandling the error in ``wait_nohang `Any`` in `mina.ml`
- This adds some additional logging, and a `try ... with exn -> ...; raise exn` to inject that location into the backtrace.
* there is additional handling to force the early evaluation of `Process.wait` for all processes that (I can tell that) we use it on
- This code also catches and logs any errors that it sees, distinguishing errors at 'call time' and 'deferred time' to give us the maximum amount of information
- This code is deliberately duplicated in each location, so that we will have the location information for *that particular error* if it fires. Not having this information has been the primary pain …
> [master-qa] Add much more aggressive handling of waits, with logging upon errors

- src/app/archive/archive_lib/processor.ml
- src/app/cli/src/mina.ml
- src/lib/mina_metrics/mina_metrics.ml
Tested with `_build/default/src/app/cli/src/mina.exe daemon -seed -proof-level none -libp2p-metrics-port 6666 -metrics-port 7777` and observing that the libp2p_helper metrics are included in `http://localhost:7777/metrics`.
Checklist:
> [master-qa] Expose libp2p_helper metrics via daemon

- src/config/debug_level/all.mlh
Fix misspelling of `cache_exceptions` in `debug_level/all.mlh`.
That compile-time flag is used only in `Cache_lib`, the misspelling is not found anywhere else.
Closes #8145.
> Fix misspelling of cache_exceptions

- src/app/archive/archive_lib/extensional.ml
- src/app/missing_subchain/missing_subchain.ml
- src/lib/blake2/blake2.ml
- src/lib/blake2/intf.ml
- src/lib/mina_base/transaction_hash.mli
For #8277, we want to be able to compare the contents of two archive dbs, to check whether they are equivalent. Databases can be equivalent, without being equal. They can differ in the ids of blocks, for example.
We can test whether two dbs are equivalent by using the `missing_subchain` tool to dump extensional blocks for them, then check whether the set of block files is the same, and that the contents of each pair of block files are identical.
Each extensional block contains lists of commands, and there was no guarantee that the lists were in any particular order. This PR sorts those lists, to yield a canonical representation of extensional blocks, so we can compare a pair of blocks with `equal`. Add the deriver for `equal` to `Extensional.Block`.
> Canonicalize extensional blocks

- frontend/client_sdk/src/CodaSDK.re
- src/app/client_sdk/client_sdk.ml
- src/app/client_sdk/tests/run_unit_tests.js
- src/app/client_sdk/tests/test_encodings.js
- src/app/client_sdk/tests/test_signatures.js
Add method to convert a Rosetta signed transaction to a signed command. The input is a JS string, because that's what the existing method `signRosettaTransaction` returns. The output is a JS string representing the JSON conversion of a `Signed_command.t`.
The output of this method is intended to be an input to GraphQL, so a string, rather than a structured object, should be acceptable.
Tested with a Rosetta signed delegation, and a Rosetta signed payment.
Changed the name of the method-containing object from `CodaSDK` to `MinaSDK`. Changed the Reason wrapper to use that new name when importing, but didn't change the wrapper name.
Closes #8282.
> Client SDK, add Rosetta signed txn to signed cmd method

- src/app/cli/src/mina.ml
This removes the `$error` interpolation from a log message where the error is not usually useful for the user. This changes the startup logs from
```
$ _build/default/src/app/cli/src/mina.exe daemon -seed
2021-03-15 23:17:59 UTC [Info] Coda daemon is booting up; built with commit "48401e92d94948c066c03ca76326c065e5cbfc92" on branch "feature/catch-seed-list-url-errors"
2021-03-15 23:17:59 UTC [Info] Created daemon lockfile "/home/matthew/.mina-config/.mina-lock"
2021-03-15 23:17:59 UTC [Info] Registering async shutdown handler: "Remove daemon lockfile"
2021-03-15 23:17:59 UTC [Info] Booting may take several seconds, please wait
2021-03-15 23:17:59 UTC [Info] Reading configuration files [ "/home/matthew/.mina-config/daemon.json" ]
2021-03-15 23:17:59 UTC [Warn] Could not read configuration …
```
> [TRIVIAL] Don't print a large error in the pretty logs for missing config files

- src/lib/genesis_ledger_helper/dune
- src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
This now prints
```
FATAL ERROR
☠  Coda Daemon encountered a configuration error generating a genesis proof.
Hint: pass the flag --generate-genesis-proof true. For example,
mina.exe daemon --generate-genesis-proof true
```
Checklist:
Closes #8093
> [Trivial] Improve error message from missing --generate-genesis-proof

- src/app/cli/src/tests/coda_process.ml
- src/app/cli/src/tests/dune
- src/lib/child_processes/child_processes.ml
- src/lib/child_processes/termination.ml
- src/lib/mina_lib/dune
- src/lib/mina_lib/mina_lib.ml
- src/lib/verifier/prod.ml
Move the code to eagerly/deferredly trap `Process.wait` errors to `Child_processes.Termination`, instead of having duplicated code.
Pass the module and location to the library code, don't use the `log` ppx, so that error logs show where this new function is called from.
Untested, but the wait code is the same as in #8352.
> Move code to wait and log errors to library code

- src/app/libp2p_helper/src/libp2p_helper/main.go
Update connection count metric to use Coda_ prefix, leave others as-is.
Currently this is the only metric we explicitly expose, the rest are default `proccess_` and `go_` metrics (and some meta-metrics for the metrics server). Based on the documentation for the libraries we are using and prometheus it is not recommended to adjust the prefix of these metrics, instead there will be a follow-up PR to forward those prefixes to grafana cloud alongside the ones we already send.
> hotfix/rename-critical-metrics 

- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_networking/mina_networking.ml
- src/lib/mina_networking/mina_networking.mli
Add an optional block height to the node status.
That change required creating `Node_status.V2` (our first version new versioned type!). The node status is an option, so the coercion from `V1` gives `None` for the block height.
The new type version feeds into a new version `V2` for the `Get_node_status` RPC, which requires `response_of_callee_model` and `caller_model_of_response` coercions that are not the identity function.
A perhaps-important observation:
The latter coercion relies on `Node_status.V1.to_latest` function, hence trivial. The other coercion works in the other direction. That means when creating new versions that feed into RPCs, you have to contemplate not only going from an old version to the latest version, but also the reverse. So if your new version elided record …
> Add block height option to node status

- buildkite/src/Jobs/Release/ClientSdk.dhall
The NPM token was not being passed into the running containers and thus the client-sdk-tool.sh script was not firing correctly. The following fix was tested by initiating a buildkite job and then logging into the container to check if the env var was being properly set.
> Added NPM token env variable to running buildkite container

- src/app/cli/src/init/client.ml
- src/app/cli/src/mina.ml
- src/app/cli/src/tests/coda_processes.ml
- src/app/cli/src/tests/coda_worker.ml
- src/app/cli/src/tests/full_test.ml
- src/lib/child_processes/child_processes.ml
- src/lib/child_processes/child_processes.mli
- src/lib/child_processes/termination.ml
- src/lib/gossip_net/libp2p.ml
- src/lib/mina_net2/mina_net2.ml
- src/lib/mina_net2/mina_net2.mli
It seems likely that the remaining WNOHANG crashes are coming from the libp2p_helper process. This PR adds the `child_data` metadata that we need to confirm this for to libp2p_helper processes, and also a log message for the process ID to help us track the process lifetime.
This change is a no-op except for the more detailed logging.
Sample log [here](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22o1labs-192920%22%0Aresource.labels.location%3D%22us-east1%22%0Aresource.labels.cluster_name%3D%22coda-infra-east%22%0Aresource.labels.namespace_name%3D%22mainnet%22%0Aresource.labels.pod_name%3D%22seed-3-77994d66b8-q4px9%22%0Aresource.labels.container_name%3D%22coda%22%0Atimestamp%3D%222021-03-23T06:36:07.433039953Z%22%0Ains …
> [master-qa] Track libp2p_helper process termination in Child_processes.Termination

- src/lib/mina_base/signed_command.ml
- src/lib/mina_base/snapp_command.ml
> [HOTFIX] Check public keys are valid before placing transactions in the pool

- automation/terraform/modules/testnet-alerts/templates/testnet-alert-rules.yml.tpl
This changes the alert level for out of sync nodes to 60%. Right now this alert is of limited utility due to issues with nodes responding. Also, I would argue that the scenarios this would fire on are well covered by FewBlocksPerHour and LongFork
> change out of sync node alert level to 60%

- buildkite/src/Jobs/Release/ArchiveNodeArtifact.dhall
- buildkite/src/Jobs/Release/ArchiveRedundancyTools.dhall
- src/lib/allocation_functor/make.ml
Bump commit of `ppx_version` submodule.
In that library, `deserialize_binary_opt` was renamed to `bin_read_to_latest_opt`. The signature for that function is changed to use a `pos_ref` argument; there was a bug involving buffer offsets, fixed.
Thanks to Gregg Reynolds who contributed patches to the expected test results, and patches to the Bazel code.
> Bump ppx_version

- src/app/archive/archive_lib/processor.ml
- src/app/extract_blocks/extract_blocks.ml
- src/app/extract_blocks/sql.ml
The program to compare a poked-and-patched archive db with an original archive db indicated that the balances in internal commands differed. The bug was that the balance ids instead of the actual balances were placed in the internal commands in extracted blocks.
After making this fix, the program to compare archive dbs succeeded. That will be a separate PR.
There's also a little cleanup in `Archive_lib.Processor` here.
> Receiver balances in internal cmds, not balance ids

- src/lib/mina_graphql/mina_graphql.ml
- src/lib/network_pool/intf.ml
- src/lib/network_pool/transaction_pool.ml
This PR improves the error messages from the `sendRosettaTransaction` GraphQL query. Previously, any error from the pool was a catch-all `Transaction could not be entered into the pool`.
Checklist:
> Improved error messages for rejection in sendRosettaTransaction

- src/lib/mina_graphql/mina_graphql.ml
This PR prevents us from accepting any string that does not roundtrip with (`to_string (of_string s) = s`). This may seem overstrict, but the unsigned parsers do unexpected things (see the code comment) and it's safer to fail explicitly than misinterpret the user.
Checklist:
Closes #8527
> Only accept valid UInt32/64 values in GraphQL

- src/app/archive/archive_lib/processor.ml
For combined fee transfers, where two fee transfers are combined into one, the archive db was receiving balances swapped between the two receivers of the fee transfers.
The code has a list of fee transfers, and a separate record of corresponding balances. The code was adding the fee transfer to the db, and retrieving the db id for them. It did so via a fold that reversed the order of the fee transfers, and so associated balances with the wrong fee transfers.
I'm unable to test this fix with Rosetta, since it doesn't create such combined fee transfers, as far as I see. The real way to test this would be to create a testnet with an archive db, and run the replayer on it.
That said, I believe this fix is correct.
Fixes #8504, as far as I see.
> Swap balances for combined fee transfers

- buildkite/scripts/publish-deb.sh
- buildkite/src/Jobs/Release/TestnetAlerts.dhall
Also pulls in the alerting change from compatible that causes alerts to drift out of date
> hotfix/pre-release-debian-channel Add codename branch for master-qa

- automation/services/watchdog/node_status_metrics.py
- automation/services/watchdog/watchdog.py
As discussed in a meeting earlier today, without knowing how many nodes respond to a status query, it's hard to tell how significant a change in the `synced` or `synced_near_best_tip` metrics actually is. This information can be extracted from the watchdog logs manually, but it's useful to have it exposed directly as a metric.
This PR adds a metric tracking this information.
Checklist:
> Add Coda_watchdog_nodes_queried metric

- src/lib/mina_lib/mina_lib.ml
Previously only the ones passed in daemon command were sent. BP keys can be updated using the `set-staking` command
> include updated block production keys in node status

- src/lib/ledger_proof/dune
- src/lib/ledger_proof/ledger_proof.ml
- src/lib/ledger_proof/ledger_proof.mli
- src/lib/network_pool/mocks.ml
- src/lib/snark_worker/debug.ml
- src/lib/snark_worker/dune
- src/lib/snark_worker/snark_worker.ml
- src/lib/verifier/dummy.ml
- src/lib/verifier/dummy.mli
- src/lib/verifier/dune
- src/lib/verifier/verifier.ml
- src/lib/verifier/verifier.mli
This PR tweaks compilation so no types or important behaviour is determined by the compile-time `proof_level` (except for compile time keys and genesis proof generation). There is still a warning in `Staged_ledger_hash.Non_snark.typ` that is disabled by setting `proof_level < Full`, but this should have no other impact.
This should (hopefully!) make it possible to switch the integration test executive to a lower proof level and avoid downloading keys.
Checklist:
> Use the same code and types for all proof_levels

- src/lib/merkle_mask/masking_merkle_tree.ml
For Merkle masks, `last_filled` was using the polymorphic `max` to compare locations. That might have worked, but hard to know.
Instead, check that the locations are indeed account locations, and use `Addr.compare` to compare the underlying addresses. `Addr.compare` is `Bitstring.compare`, which is essentially `String.compare`. For accounts, the addresses are bitstrings with length equal to the ledger depth. A set bit is greater than an unset bit (verified by testing).
Closes #8474.
> Mask `last_filled`, use Addr.compare

- src/lib/base58_check/README.md
- src/lib/base58_check/base58_check.ml
- src/lib/base58_check/base58_check.mli
- src/lib/base58_check/version_bytes.ml
- src/lib/secrets/hardware_wallets.ml
Add a `README` for `Base58_check` library, update comments in .mli file, add/update comments in `Version_bytes`.
Rename `coda_alphabet` to `mina_alphabet`.
> Docs, minor changes to Base58_check

- CODEOWNERS
- Makefile
- src/app/patch_archive_test/dune
- src/app/patch_archive_test/patch_archive_test.ml
- src/patch_archive_test.opam
`patch_archive_test` takes an archive db, makes a copy, deletes some blocks from the copy, and patches the copy using extensional or precomputed blocks. The app then extracts all blocks from the original and patched copy, and checks whether the sets of blocks are the same, and that their contents are identical. 
The extracted blocks are written to temp directories in `/tmp/`. Those directories are deleted if the test succeeds, but kept if there's an error, to aid debugging.
Usage:
```
patch_archive_test.exe [FILES ...]
== flags ==
--archive-blocks-path PATH  Path to archive_blocks executable
(alias: -archive-blocks-path)
--archive-uri URI           URI for connecting to the archive database (e.g.,
postgres://$USER@localhost:5432/archiver)
--extract-blocks-path PATH  Path to extract_blocks …
```
> App to poke and patch archive database

- src/lib/mina_lib/coda_subscriptions.ml
Makes it easier to look for missing blocks at specific heights
> include the height of a block in the precomputed block filename

- automation/terraform/modules/o1-integration/graphql_ingress.tf
- automation/terraform/modules/o1-integration/locals.tf
- dockerfiles/coda_daemon_puppeteer.py
- helm/block-producer/templates/block-producer.yaml
- helm/seed-node/templates/seed-node.yaml
- helm/snark-worker/templates/coordinator-service.yaml
- src/lib/integration_test_cloud_engine/kubernetes_network.ml
This PR switches the integration test over to use an nginx ingress controller w/ mergeable ingress types. This will provide a serious speed improvement to the integration tests, and replaces the unreliable/flaky gke ingress controller system we had in place previously.
For now, I've manually deployed the nginx ingress controller and master ingress for the integration test cluster. I will create a separate PR that updates the infrastructure terraform module to deploy the nginx ingress (for the future, in case we need to recreate the cluster).
> Integration tests nginx ingress

- src/app/archive/archive.opam
- src/config/integration_tests.mlh
This PR changes the `proof_level` for the test executive, so that it doesn't attempt to generate snark keys or a genesis proof during compilation.
This builds upon #8454, which ensures that the types etc. used by binaries from different proof levels are compatible.
> Use proof_level=none for integration tests

- scripts/archive/find-swapped-balances.awk
- scripts/archive/fix-swapped-balances.sh
Two scripts to help patching swapped fee transfer balances in the archive db.
`find-swapped-balances.awk` is an AWK script that isolates the replayer log entries with the information needed to patch pairs of swapped balances. You run the script on the replayer log, and you get relevant logs with the block state hash and sequence number, plus the logs showing the balance mismatch. (Funny enough, this script revealed that one pair of swapped balances had identical amounts.)
`fix-swapped-balances.sh` patches all swapped balances an archive db through the first canonical block on April 7, 2021. We announced v1.1.5 later that day. Anyone who upgraded soon after the release should have few remaining invalid balances, after running this script.
Tested by:
- dumping the mainnet archive db
- …
> Scripts for patching swapped balances

- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
- src/lib/block_producer/block_producer.ml
- src/lib/mina_lib/config.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_transition/external_transition.ml
- src/lib/staged_ledger_diff/staged_ledger_diff.ml
- src/lib/staged_ledger_diff/staged_ledger_diff.mli
Added a new flag `--minimum-block-reward` to the daemon command.
If the total reward of a block generated by a node is less than the  `minimum-block-reward` configured by the node then it discards the diff (consisting of transactions and snark work) and creates an empty block (no coinbase or transactions) instead.
This is temporary solution to a problem described in #8576. The long term solution is described here #8585
Closes #8576
> minimum block reward

- automation/terraform/modules/testnet-alerts/templates/testnet-alert-rules.yml.tpl
This PR removes the `min_over_time`/`max_over_time` aggregators for several alerts. The effect of these aggregators is to extend the time that an alert fires for by `${alert_timeframe}` (currently `10m`) after it otherwise should have stopped.
For all of the alerts changed in this PR, the issue is known to be resolved as soon as the alert stops firing.
Checklist:
> Remove some *_over_time modifiers for alerts

- graphql_schema.json
- src/lib/mina_graphql/mina_graphql.ml
This PR implements the `stagedLedgerProofEmitted` endpoint in our GraphQL. This endpoint looks for a given state hash and attempts to find a corresponding breadcrumb in the transition frontier. If we find a breadcrumb, we call the `just_emitted_a_proof` method to see if the staged ledger proof has been emitted. If no breadcrumb or block is found, we return null.
GraphQL:
> Feature: Add stagedLedgerProofEmitted to GraphQL

- src/lib/pickles/inductive_rule.ml
- src/lib/pickles/pickles.ml
- src/lib/pickles/step.ml
- src/lib/pickles/step_main.ml
- src/lib/pickles/wrap_domains.ml
- src/lib/pickles_types/higher_kinded_poly.ml
- src/lib/pickles_types/hlist.ml
- src/lib/pickles_types/poly_types.ml
This PR adds the `Pickles_types.Higher_kinded_poly` utility library.
This is a type-level hack that allows manipulating higher-kinded polymorphic types using type variables.
For example, we can constrain packed modules to have a particular higher-kinded type even though we cannot do so in the surface-level type system:
```ocaml
module My_type = struct
type 'a t
end
module type S = sig
type 'a t
module Poly_witness : P1.S with type 'a p = 'a t
end
let f (module M : S with type Poly_witness.witness = P1.W(My_type).t) = ...
let g (type t_poly) (module M : S with type Poly_witness.witness = t_poly) (module N : S with type Poly_witness.witness = t_poly) = ...
```
This also plays nicely with `Hlist`. For our purposes, we can use this to carry proofs from multiple proof systems in the same …
> Add Pickles_types.Higher_kinded_poly

- src/app/cli/src/init/client.ml
- src/app/cli/src/mina.ml
- src/app/cli/src/tests/coda_processes.ml
- src/app/cli/src/tests/coda_worker.ml
- src/app/cli/src/tests/full_test.ml
- src/lib/gossip_net/libp2p.ml
- src/lib/mina_metrics/mina_metrics.ml
- src/lib/mina_net2/dune
- src/lib/mina_net2/mina_net2.ml
- src/lib/mina_net2/mina_net2.mli
This PR adds one of the metrics for the investigation in #8638: when the `--all-peers-seen-metric true` flag is passed, the node will accumulate the set of all peers it ever receives a message from, exposing the size of this set as the `all_peers` metric.
Note that this doesn't use the connection events that we receive from libp2p, because the metrics from the connection manager indicate that it isn't correctly tracking connections (issue #8525). Instead, this is hooked into the `incomingStream` message, so this metric is more accurately tracking every peer that we've ever received an incoming connection from in OCaml.
Tracking of peers is done using the IP address and port only, to ensure that we don't double(or triple, etc.) count peers that restart and generate a new libp2p ID. …
> [master] Metric for all peers ever seen

- graphql_schema.json
- src/app/cli/src/init/client.ml
- src/app/cli/src/init/dune
- src/app/cli/src/init/graphql_queries.ml
- src/lib/cli_lib/flag.ml
- src/lib/cli_lib/flag.mli
- src/lib/mina_graphql/mina_graphql.ml
This PR
* adds support importing keys to a remote daemon via GraphQL
* reports when importing keys occurs locally due to a connection failure
* allows setting of either `-config-directory` for explicit local imports or `-rest-port` for explicit remote imports
* adds support (and fallthrough) for local account listing.
Some sample runs:
* `accounts list`, no running daemon, imported keys 
* `accounts list`, running daemon, no imported key 
* `accounts import`, no running daemon, imported keys
* `accounts import`, running daemon, no imported key 
* `accounts list`, running daemon, imported key 
* `accounts list`, explicit config directory path 
* `accounts list` with incompatible flags 
Checklist: …
> Support local filesystem and rest-server modes for `accounts import`, `accounts list`

- src/lib/block_producer/block_producer.ml
- src/lib/merkle_ledger/any_ledger.ml
- src/lib/merkle_ledger/base_ledger_intf.ml
- src/lib/merkle_ledger/database.ml
- src/lib/merkle_ledger/null_ledger.ml
- src/lib/merkle_ledger_tests/test.ml
- src/lib/merkle_ledger_tests/test_database.ml
- src/lib/merkle_ledger_tests/test_mask.ml
- src/lib/merkle_mask/masking_merkle_tree.ml
- src/lib/mina_base/ledger.ml
- src/lib/mina_base/ledger.mli
- src/lib/mina_base/ledger_transfer.ml
- src/lib/mina_base/sparse_ledger.ml
- src/lib/mina_base/transaction_logic.ml
- src/lib/mina_base/transaction_validator.ml
- src/lib/syncable_ledger/test.ml
- src/lib/transition_frontier/frontier_base/breadcrumb.ml
This PR should address the concerns behind #7255 around our behaviour when the ledger is full and no more accounts can be created. It does this by removing `get_or_create_account_exn` and handling the error cases explicitly.
Overview:
* In order to create an account we need a `Location.t`
- We derive from the current highest location with `Location.next`, which returns `None` when the ledger is full
* The two active codepaths that do this both return an `_ Or_error.t` containing an 'out of leaves' error when they receive this `None` value
* This error is bubbled up through `get_or_create_account` and friends, where it can be handled by the caller
* This PR adds the handling for this, so that transactions which would create a new account in the full ledger will fail without applying, but …
> Catch errors when the ledger is full

- src/app/replayer/replayer.ml
- src/app/replayer/sql.ml
The epoch ledgers were handled incorrectly in the replayer. The existing code computed hashes for the staking and next ledgers once at startup, and when the ledger hash matched those, generated the epoch ledgers, never to be updated again.
The new algorithm maintains a last-block-id, initialized with the genesis block id. Before executing a  command, lookup the staking, next epoch data ids for that block, get the corresponding epoch ledger hashes, and compare against the ledger hash. If they match, generate new epoch ledgers. Even if they don't match, record the seed, which, in the case of the next epoch ledger, gets updated more frequently than the hash. User and internal commands already contained a block id, which is passed as the latest block id.
The existing replayer test still …
> Update epoch ledger handling in replayer

- buildkite/src/Monorepo.dhall
- buildkite/src/Prepare.dhall
The purpose of this PR is to support a new type of buildkite pipeline for stable branch builds which will run all available buildkite jobs whenever stable branches are updated. The new pipeline can be found here https://buildkite.com/o-1-labs-2/mina-stable.
Once this lands, we would be disabling our hourly scheduled builds on stable branches and only use this new pipeline for testing stable branches when they are updated. We will likely keep nightlies around for the time being, but will be thinking of the best way to maintain them soon.
> Add stable pipeline support to buildkite

- buildkite/src/Monorepo.dhall
- buildkite/src/Pipeline/Mode.dhall
- buildkite/src/Prepare.dhall
- buildkite/src/gen/Jobs.dhall
My first PR (#8715) seems to have not fully worked as intended. Attempting to fix that in this version of the PR.
It's rather difficult to pass env vars down through Prepare.dhall and into Monorepo.dhall. I think Prepare.dhall is pretty unnecessary and that we should probably just replace it with an entry shell script, if reasonable. Might do that in a future PR.
> Add stable pipeline support to buildkite (round 2)

- src/app/cli/src/init/client.ml
> Exit with code 1 if there is an error in `ledger export`

- src/app/replayer/replayer.ml
Check to see if the existing epoch ledger has the hash we want before creating a new epoch ledger. This saves creating new epoch ledgers when they're the same as the genesis ledger.
Tested by making the same change in the code for #8735, verifying that the new epoch ledgers were not created.
> Replayer, don't create epoch ledger if exists

- src/app/delegation_compliance/delegation_compliance.ml
- src/app/delegation_compliance/sql.ml
- src/app/replayer/replayer.ml
I had made an "optimization" in the replayer and delegation compliance apps, in #8735 and #8739, by not creating epoch ledgers if the existing ledger had the right hash.
But those tools start with epoch ledgers that are the genesis ledger, not copies of it, and that ledger gets updated. Comparing some results for delegation compliance with Gareth's data, there were incorrect values. Removing the "optimization" resolved the discrepancies; the epoch ledgers get copied (again).
Tested by comparing a delegation total for a particular delegatee, comparing with Gareth's value for the same delegatee.
Also fixes a couple of bugs in the compliance app: 1) use delegator's balance on the staking ledger, rather than the active ledger, to compute stake fraction; 2) only count blocks produced on the …
> Replayer and delegation compliance, undo bad optimization

- scripts/archive/find-swapped-balances.awk
- scripts/archive/fix-all-balances.sh
- scripts/archive/fix-swapped-balances.sh
Checklist:
Closes #0000
Closes #0000
> improve-bad-balance-scripting Add fix-all-balances.sh script

- src/app/delegation_compliance/delegation_compliance.ml
- src/app/delegation_compliance/input.json
- src/app/delegation_compliance/sql.ml
In `delegation_compliance`, log the transactions it's considering, to make its operations auditable. Doing so revealed some duplicated transactions.
When computing payout obligations, move more of the computation to `Currency.Amount` from `Float`.
Log amounts in Mina, not in nanoMina.
Tested with 3 payout addresses from the "scofflaw spreadsheet" and a dump of the archive db from today.
> Audit trail, remove duplicate data in `delegation_compliance`

- automation/terraform/modules/testnet-alerts/templates/testnet-alert-receivers.yml.tpl
The generic webhook receiver config wasn't working for slack integration. Added the slack specific one and specified some details about the alert to be displayed in the notification.
Deployed the receiver config manually
> receiver configuration for warnings

- src/app/delegation_compliance/delegation_compliance.ml
- src/app/delegation_compliance/input.json
- src/app/delegation_compliance/sql.ml
In `delegation_compliance`, check payments in the archive database directly, don't replay transactions. The updated app is able to check all the foundation delegations in about 11 seconds on my desktop. That's compared with 15 minutes for just one delegator with the existing code.
As input, provide a staking ledger, and the corresponding epoch number (0-based). Given the archive db, the app will find the longest canonical chain, and find the relevant transactions along the chain in the given epoch.
Tested with an archive db up to slot ~21000.
> Delegation compliance, simplified

- src/app/libp2p_helper/src/codanet.go
Bump the node status timeout in an attempt to reduce the number of "context deadline exceeded" errors we get back from our watchdog.
> Increase node status timeout

- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
- src/app/cli/src/init/client.ml
- src/app/cli/src/tests/coda_worker.ml
- src/app/cli/src/tests/full_test.ml
- src/app/rosetta/test-agent/agent.ml
- src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml
- src/lib/block_producer/block_producer.ml
- src/lib/consensus/intf.ml
- src/lib/consensus/proof_of_stake.ml
- src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
- src/lib/genesis_proof/genesis_proof.ml
- src/lib/integration_test_cloud_engine/coda_automation.ml
- src/lib/integration_test_lib/event_type.ml
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/mina_transition/external_transition.ml
- src/lib/precomputed_values/gen_values/gen_values.ml
- src/lib/prover/intf.ml
- src/lib/prover/prover.ml
This PR
* removes genesis proof generation from the startup code
* adds support for generating genesis proofs in the prover process
* adds logic to generate a genesis proof when a block producer will need one to be able to produce their block
- if the next block for the producer is `n` slots in the future, the genesis proof will be produced at slot `n-1`, if it is still needed
- if it's needed immediately, the genesis proof will be produced as soon as possible and then used to generate the block
Checklist:
> Don't generate genesis proof at startup

- automation/README.md
- automation/terraform/monitoring/o1-testnet-alerts.tf
Omitting alerts from testnets that start with `test-`. Any private testnet can have the prefix `test-` in its name to omit alerts from it. This is to reduce noise in testnet-warnings channel
Integration tests and ci nets are already being ignored. Retaining alerts from `nightly` since we want to ensure it runs fine in order to make alpha releases
> Omit alerts from private testnets

- automation/services/watchdog/metrics.py
Fix another bug of watchdog. This should fix the SeedListDown alert in devnet2.
> only exec commands on running pods

- src/app/libp2p_helper/src/libp2p_helper/main.go
Part of #8749. There will be a followup PR that fixes the OCaml integration with the libp2p_helper wrt surfacing these metrics.
> Re-enable libp2p metrics; remove per-peer metrics

- src/app/delegation_compliance/delegation_compliance.ml
- src/app/delegation_compliance/sql.ml
In the delegation compliance app, the number of blocks produced for a given block producer was less than the number reported by Gareth. That was due to the change to consider only payments between slots 3500 of the current epoch and slot 3500 of the next epoch, to avoid double-attribution of payments to epochs.
Instead, obtain all block ids for slots between the start of the current epoch and slot 3500 of the following epoch along the canonical chain. To get the number of blocks produced, obtain block ids for produced blocks in current epoch, filtered to the canonical chain. For payments, filter the block ids between slot 3500 of the current epoch and slot 3500 of the following epoch and membership in the canonical chain.
Tested by running with a payout address where the result mismatched …
> Delegation compliance, count all blocks in epoch

- src/app/delegation_compliance/delegation_compliance.ml
New strategy for the `delegation_compliance` app. For a given epoch, generate a preliminary CSV, and take as input, the preliminary CSV from the preceding epoch. That preceding epoch CSV is updated with a `.finalized` CSV, where any satisfied obligation can be paid with payments up to slot 3500 in the current epoch. Those payments are made unavailable for the obligation of the current epoch.
This strategy solves the double-attribution problem in the same way as the older replayer-based app. It's much faster to run, though, since it considers only one epoch at a time, and does not need to apply transactions (it takes a staking ledger as input).
Tested by generating CSVs for epochs 0 - 3, and finalized CSVs for epoch 0 - 2, reviewed by Ben.
> Delegation compliance, CSV stitching

- src/lib/network_pool/transaction_pool.ml
These tests have become far more flaky as of late. This variability seems to be coming from the async scheduler, which may choose to run the test's assertion before committing the updates sent to a broadcast pipe.
This PR fixes this, by yielding to the scheduler and waiting for all jobs to finish before running the checks.
cc @psteckler, this should fix the failures you were seeing in #8898.
Checklist:
> Fix flaky tests: ensure all async jobs have completed before asserting

- src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
This PR stops calling into code for loading genesis proofs from file or S3. This removes a number of unnecessary log messages.
Checklist:
> [Release] Don't look for genesis proof file at startup

- src/lib/ledger_catchup/super_catchup.ml
- src/lib/transition_frontier/full_catchup_tree.ml
Nodes crashed with the dangling merkle mask parent exception when one of them created a fork off of the root of the frontier.
This is an edge case in the catchup code where a cached breadcrumb becomes stale and doesn't get updated before being used. The breadcrumb at the root changes when the root transitions. When a node produces blocks off of the root of the frontier and other nodes try to catchup to the short fork, they’d use the stale breadcrumb which would have a detached mask.
Fixed by not storing any breadcrumbs in the catchup tree
Reproduced it locally and tested the fix
This is a different case from what is reported in #8681 which is the transition frontier and extension desync issue
> devnet catchup failure fix

- src/lib/mina_lib/mina_lib.ml
- src/lib/network_pool/rate_limiter.ml
- src/lib/network_pool/rate_limiter.mli
- src/lib/network_pool/transaction_pool.ml
> Rebroadcast in chunks

- src/app/cli/src/init/client.ml
- src/app/cli/src/init/coda_run.ml
The RPC call to export the staged ledger was timing out, because RPC heartbeats could not be processed.
Wrapping the daemon-side call to `get_ledger` in a system thread seems to allow the heartbeats to continue, and the ledger export succeeds, though it takes time well beyond the RPC heartbeat timeout.
This call is only reading data, so I don't think there's a concern with data shared between threads.
Also cleaned up the flag processing for `ledger export` to make it more maintainable.
Tested by compiling with the `mainnet` profile, running the node locally, exporting the ledger. That failed without the changes in this PR.
Closes #8988.
> `get_ledger` in system thread for export

- buildkite/src/Jobs/Test/DaemonUnitTest.dhall
- frontend/client_sdk/package.json
- scripts/client-sdk-unit-tests.sh
- scripts/compare_test_signatures.sh
- src/lib/signature_lib/private_key.ml
- src/nonconsensus/signature_lib/dune
This PR uses JavaScript's crypto API (working around the different APIs of node and the browser) to provide random bytes for keypair generation for the JS build. It has been tested in Firefox and node.js
> Improve randomness generation for nonconsensus signature lib

- src/lib/network_pool/transaction_pool.ml
This PR changes the handling of locally-generated transactions in the transaction pool, so that
* re-sending a transaction will not fail with `already saw this`
- this allows transactions accidentally sent out-of-order, to accounts that are yet to be created/funded, etc. to be re-issued once the problem has resolved
* re-sending transactions resets their rebroadcast timer
- this ensures that transactions can be recovered from becoming 'stuck' in the pool by sending them again
Checklist:
> Allow local re-sending of txns, reset re-broadcast timer when doing so

- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
The docstring for `--peer-list-file` appeared to suggest that it takes a multiaddress as an argument, rather than a file.
Change the docstring to indicate that it's a path to a file that's needed.
Tested by building mina.exe, examining `daemon -help`.
> Better doc for peer-list-file flag

- src/lib/mina_networking/mina_networking.ml
Add a mention of the chain id when a node can't connect to any initial peers.
That was already mentioned in a comment, would be helpful to surface that to node operators.
> Mention chain id when can't connect to init peers

- README-dev.md
Since the [zexe repository](https://github.com/o1-labs/zexe/tree/21a9eb6948083dcad7aa21c61da6feac05e28319) is a submodule of the [marlin repository](https://github.com/o1-labs/marlin). We need to resolve the git submodules recursively otherwise we cannot build the project because `zexe` will be missing.
> docs: update submodules recursively

- src/external/ocaml-rocksdb/dune
This PR is a no-op for normal compilation.
This tweaks the `dune` file for the rocksdb library so that it can be built in bytecode mode as well as native mode, allowing `mina_base` and other libraries that depend on it to be loaded by utop.
Found as part of testing #9022.
Verified by running `dune utop src/lib/mina_base`.
Checklist:
> Enable `dune utop src/lib/mina_base`

- src/lib/marlin_plonk_bindings/stubs/src/index_serialization.rs
- src/lib/marlin_plonk_bindings/stubs/src/pasta_fp_plonk_index.rs
- src/lib/marlin_plonk_bindings/stubs/src/pasta_fp_plonk_verifier_index.rs
- src/lib/marlin_plonk_bindings/stubs/src/pasta_fq_plonk_index.rs
- src/lib/marlin_plonk_bindings/stubs/src/pasta_fq_plonk_verifier_index.rs
This PR pulls in the latest changes from the marlin repo.
This PR is a no-op; the changes here are only to respect the some rust code that was moved in the marlin repo.
Tested by syncing a daemon to devnet.
Checklist:
> Bump marlin submodule

- src/lib/mina_lib/mina_lib.ml
- src/lib/network_pool/intf.ml
- src/lib/network_pool/mocks.ml
- src/lib/network_pool/network_pool_base.ml
- src/lib/network_pool/snark_pool.ml
- src/lib/network_pool/snark_pool_diff.ml
- src/lib/transition_frontier/extensions/snark_pool_refcount.ml
- src/lib/transition_frontier/extensions/snark_pool_refcount.mli
limit local snark work broadcasts as per the current rate limit to avoid being rejected by peers
> limit local snark work broadcast

- src/lib/marlin_plonk_bindings/stubs/Cargo.toml
- src/lib/marlin_plonk_bindings/stubs/src/bigint_256.rs
- src/lib/marlin_plonk_bindings/stubs/src/bigint_384.rs
- src/lib/marlin_plonk_bindings/stubs/src/bn_382_fp.rs
- src/lib/marlin_plonk_bindings/stubs/src/bn_382_fp_vector.rs
- src/lib/marlin_plonk_bindings/stubs/src/bn_382_fq.rs
- src/lib/marlin_plonk_bindings/stubs/src/bn_382_fq_vector.rs
- src/lib/marlin_plonk_bindings/stubs/src/caml_pointer.rs
- src/lib/marlin_plonk_bindings/stubs/src/pasta_fp.rs
- src/lib/marlin_plonk_bindings/stubs/src/pasta_fp_plonk_index.rs
- src/lib/marlin_plonk_bindings/stubs/src/pasta_fp_plonk_oracles.rs
- src/lib/marlin_plonk_bindings/stubs/src/pasta_fp_plonk_proof.rs
- src/lib/marlin_plonk_bindings/stubs/src/pasta_fq.rs
- src/lib/marlin_plonk_bindings/stubs/src/pasta_fq_plonk_index.rs
- src/lib/marlin_plonk_bindings/stubs/src/pasta_fq_plonk_oracles.rs
- src/lib/marlin_plonk_bindings/stubs/src/pasta_fq_plonk_proof.rs
- src/lib/marlin_plonk_bindings/stubs/src/plonk_gate.rs
- src/lib/marlin_plonk_bindings/stubs/src/plonk_verifier_index.rs
- src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp.rs
- src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_plonk_index.rs
- src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_plonk_oracles.rs
- src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_plonk_proof.rs
- src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq.rs
- src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_plonk_index.rs
- src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_plonk_oracles.rs
- src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_plonk_proof.rs
This PR upgrades the `ocaml-rs` library that we use to convert values between rust and OCaml.
Most notably, the new version has updated code for generating OCaml `_ Option.t` values from rust `Option<_>`s. The new code generates the inner OCaml value before generating the option wrapper, so we should no longer see values in the major heap pointing to values in the minor heap coming from these allocations. Based on the [backtrace](https://github.com/MinaProtocol/mina/issues/8353#issuecomment-856762183) and memory contents from a recent segfault, this is a good candidate for source of memory corruption issues.
Tested by connecting to mainnet; the node successfully synced (from a blank `.mina-config` directory), and was behaving normally.
Checklist:
- Mention expected invariants, implicit …
> Upgrade ocaml-rs, tweak some bindings to be safer

- dockerfiles/scripts/cron_job_dump_ledger.sh
- helm/staking-ledger-cron/mainnet-dump-staking-ledger-cronjob.yaml
Add timestamp to epoch ledgers (and daemon logs) saved to GCloud by cron job.
The existing cron job saved these files at the beginning of epochs, then subsequent runs would fail, because the saved files could not be deleted. That meant, if the first run produced bogus results, we'd never have valid results.
Tested by running the cron job manually, inspecting the results in GCloud.
Clients of these files should be able to select a valid one.
> Add timestamp to epoch ledger files in GCloud

- dockerfiles/Dockerfile-mina-daemon
- src/lib/staged_ledger/staged_ledger.ml
Block production failed with a [diff application error](https://console.cloud.google.com/logs/viewer?interval=CUSTOM&project=o1labs-192920&minLogLevel=0&expandAll=false&timestamp=2021-06-17T06:03:23.367000000Z&customFacets=jsonPayload.metadata.proof_count,jsonPayload.metadata.txn_count,jsonPayload.metadata.error_extra.expected_nonce,jsonPayload.metadata.error_extra.nonce,jsonPayload.metadata.cmd%5B1%5D.signer,jsonPayload.metadata.cmd%5B1%5D.payload.common.nonce,jsonPayload.metadata.rate_limiter.by_peer_id%5B0%5D%5B0%5D,jsonPayload.metadata.rate_limiter.by_peer_id%5B0%5D%5B1%5D.capacity_used,jsonPayload.metadata.work_ids,jsonPayload.metadata.reorg_best_tip,jsonPayload.metadata.added_transitions%5B0%5D.protocol_state.body.consensus_state.curr_global_slot.slot_number,jsonPayload.metadata.adde …
> [hotfix] Revert staged ledger diff changes

- frontend/client_sdk/package.json
- frontend/client_sdk/yarn.lock
This PR upgrades the typescript version to be a minimum of `3.8.2`. Our build client sdk job has been failing due to a `error TS1005: '=' expected.` which indicates that we are using an old version of typescript (checked on a `1.1.6alpha5` build) https://buildkite.com/o-1-labs-2/mina/builds/17865#a511dc97-d28f-42e0-a792-b8bc3532b124/140-164. 
This fix has been tested by creating a PR to trigger the CI and force a build of the client sdk. See here: https://github.com/MinaProtocol/mina/pull/9078/files
The resulting job in our CI passed as seen here:
https://buildkite.com/o-1-labs-2/mina/builds/17908#563cd2a4-e3b7-486d-9df0-d73579cf7400/127-149
> ClientSDK - Upgrade tsc in package.json

- src/lib/daemon_rpcs/types.ml
This disables the unhelpful log message at the top of each `mina client status` output:
```json
{"timestamp":"2000-01-01 00:00:00.000000Z","level":"Debug","source":{"module":"Block_time","location":"File \"src/lib/block_time/block_time.ml\", line 83, characters 18-30"},"message":"Environment variable CODA_TIME_OFFSET not found, using default of 0","metadata":{"pid":1}}
```
A call to format the results of a status request is never the right time to emit this log message, so passing the `Logger.null ()` logger here is strictly an improvement.
Checklist:
Closes #9054
> [TRIVIAL] Disable log message at the start of each `mina client status`

- src/config/dune
In the dependencies list to rebuild `config.mlh`, remove the use of `CODA_DUNE_PROFILE`, which is otherwise unused.
Also, change a polymorphic equality to a string equality. Not required, since this code doesn't use the Jane St libraries, but good practice.
Part of #9041.
> Remove CODA_DUNE_PROFILE

- dockerfiles/Dockerfile-rosetta-hardcoded
- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
- src/app/cli/src/init/client.ml
- src/app/rosetta/run-demo.sh
- src/app/rosetta/test-agent/agent.ml
Use environment variables `MINA_CONFIG_DIR` and `MINA_CONFIG_FILE`.
The first of these is used internally in the Rosetta Dockerfile and demo scripts.
The second is used in the daemon startup, an `advanced` command, and the Rosetta test agent, so we still allow use of `CODA_CONFIG_FILE`. In the cases of the daemon startup and the Rosetta test agent, we print a deprecation message.
Part of #9041.
> MINA_CONFIG... environment variables

- docs/tracing.md
- src/app/cli/src/tests/coda_peers_test.ml
- src/app/cli/src/tests/coda_transitive_peers_test.ml
- src/app/cli/src/tests/coda_worker_testnet.ml
- src/app/cli/src/tests/full_test.ml
Replace `CODA_TRACING` environment variable with `MINA_TRACING`.
As far as I see, we're only using this variable internally, in the CLI tests (which we're not running).
> MINA_TRACING environment variable

- automation/scripts/generate-keys-and-ledger.sh
- automation/scripts/testnet-keys.py
- automation/services/coda-user-agent/agent.py
- automation/services/watchdog/metrics.py
- automation/terraform/modules/services/daemon/templates/container-definition.json.tpl
- automation/terraform/modules/services/faucet/templates/container-definition.json.tpl
- automation/terraform/modules/services/graphql-proxy/templates/container-definition.json.tpl
- dockerfiles/auxiliary_entrypoints/01-run-demo.sh
- docs/docker.md
- helm/block-producer/templates/block-producer.yaml
- helm/seed-node/templates/seed-node.yaml
- scripts/get-wallet-keys.sh
- scripts/run_local_network.sh
- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
- src/app/cli/src/init/client.ml
- src/app/rosetta/docker-demo-start.sh
- src/app/rosetta/docker-start.sh
- src/app/rosetta/docker-test-start.sh
- src/app/rosetta/run-demo.sh
- src/lib/secrets/keypair.ml
- src/lib/secrets/keypair_common.ml
- src/lib/secrets/libp2p_keypair.ml
Allow use of environment variables `MINA_PRIVKEY_PASS` and `MINA_LIBP2P_PASS`, while still allowing use of the `CODA_` equivalents.
When the `CODA_` variables are used, mention that they are deprecated, and suggest use of the corresponding `MINA_` variable.
All uses of the old variables are replaced with the new variables.
Tested by running `advanced dump-keypair`, with both environment variables, and with no variable set.
Part of #9041.
> Allow MINA_PRIVKEY_PASS, MINA_LIBP2P_PASS

- src/app/cli/src/tests/coda_process.ml
- src/lib/child_processes/child_processes.ml
Use `MINA_INTEGRATION_TEST_DIR` for the CLI tests. Those tests are not currently run, and this variable doesn't appear elsewhere, so I think it's not important to use the old name.
For child processes, allow `MINA_prog_PATH`, in addition to `CODA_prog_PATH`.
Part of #9041.
> MINA_INTEGRATION_TEST_DIR, MINA_prog_PATH

- automation/bake/Dockerfile
- dockerfiles/Dockerfile-mina-daemon
- dockerfiles/auxiliary_entrypoints/01-run-demo.sh
- src/app/cli/src/init/client.ml
- src/app/cli/src/tests/coda_process.ml
- src/app/cli/src/tests/full_test.ml
- src/app/rosetta/docker-demo-start.sh
- src/app/rosetta/docker-test-start.sh
- src/app/rosetta/run-demo.sh
- src/lib/block_time/block_time.ml
- src/lib/block_time/block_time.mli
Allow use of `MINA_TIME_OFFSET` as an environment variable, while continuing to allow `CODA_TIME_OFFSET`.
If the old variable is used, a warning log is issued.
All uses of the variable in the codebase are updated.
Part of #9041.
> Allow MINA_TIME_OFFSET

- src/lib/currency/currency.ml
- src/lib/currency/intf.ml
Currently, for signed values we have
```ocaml
{ sgn= Pos; magnitude= 0 } <> { sgn= Neg; magnitude= 0 }
```
This PR corrects this so that those two values are now equal, and adds some helper functions.
> Fix signed equality

- src/lib/base58_check/version_bytes.ml
The base58check representation of `Non_zero_curve_point` always represents the compressed representation of the point. The version byte for the uncompressed point was used in the past, but not used in the current code, so its presence is confusing.
> Remove version byte for uncompressed Non_zero_curve_point

- automation/services/graphql-public-proxy/Dockerfile
- automation/services/graphql-public-proxy/src/index.js
- automation/terraform/modules/services/faucet/templates/container-definition.json.tpl
- automation/terraform/modules/services/graphql-proxy/templates/container-definition.json.tpl
- buildkite/src/Jobs/Release/BotArtifact.dhall
- buildkite/src/Jobs/Release/LeaderboardArtifact.dhall
- frontend/bot/Dockerfile
- frontend/bot/README.md
- frontend/bot/src/Constants.re
- frontend/points-hack-april20/Dockerfile
- frontend/points-hack-april20/lib.js
- helm/block-producer/templates/block-producer.yaml
Use environment variables `MINA_GRAPHQL_HOST` and `MINA_GRAPHQL_PORT` instead of `CODA_...` equivalents.
All uses of the old variables in the codebase are changed here.
> Use MINA_GRAPHQL... environment variables

- src/lib/cache_dir/cache_dir.ml
Add `MINA_KEYS_PATH`, while still allowing use of `CODA_KEYS_PATH`.
Part of #9041.
> MINA_KEYS_PATH

- automation/bake/Dockerfile
> Use catchsegv to dump backtrace on segfaults

- src/lib/file_system/file_system.ml
- src/lib/key_cache/dune
- src/lib/key_cache/key_cache.ml
The `1.2.0` beta still reveals `WNOHANG` crashes. 
In issue #9169, the exception is generated in `Process.collect_output_and_wait`, which is called (indirectly) by `Process.run`.
While the two calls here are unlikely candidates to have generated the exception, it's good practice to wrap them in monitors.
> Wrap a couple of `Process.run`

- src/app/cli/src/init/client.ml
- src/app/cli/src/init/coda_run.ml
Apply the diff for #8996 to the `release/1.2.0` branch.
When running CLI command `ledger export staged-ledger`, run `Mina_lib.get_ledger` in a system thread, so RPC heartbeats can be processed. No other code is affected.
(There's also some cleanup of the flag processing for ledger export.)
> `get_ledger` in sys thread for release

- src/lib/marlin_plonk_bindings/js/bindings.js
- src/lib/marlin_plonk_bindings/js/test/bindings_js_test.ml
This PR implements vectors for the JS OCaml bindings.
These bindings aren't really rust vectors -- instead, we encode them entirely in javascript. This allows us to avoid calling across the FFI and to leverage the existing `Array` vector implementation in JS.
Checklist:
> WASM bindings for vectors

- helm/cron_jobs/mainnet-dump-archive-cronjob.yaml
- helm/cron_jobs/mainnet-dump-staking-ledger-cronjob.yaml
https://github.com/MinaProtocol/mina/issues/9138
the actual cron job task is here: https://console.cloud.google.com/kubernetes/cronjob/us-east1/coda-infra-east/mainnet/mainnet-dump-archive-cronjob/details?authuser=2&project=o1labs-192920
committing the job specs to github is mostly for future reference
Note by @psteckler: output is to `https://console.cloud.google.com/storage/browser/mina-archive-dumps`
> Dump archive daily cron job

- src/lib/mina_lib/mina_lib.ml
- src/lib/verifier/prod.ml
Issue #9163 suggests that there's a FIFO leak in the code. When child processes terminate, the Mina executable should close `stdin`, its end of the pipe shared with those processes.
For `libp2p`, the `start_custom` code already does a close on termination. For the SNARK worker and verifier, this PR introduces explicit closes.
Tested that the code for the verifier is exercised by running a local network, killing the verifier, and printing out the closed status of all 3 file descriptors. Only the `stdin` was open. (Also verified that the closes for libp2p helper are being called. Probably the one for stdout isn't needed.)
(In fact, in one case, all 3 descriptors remained open, but I'm supposing that's a race where the stdout and stderr had not yet been automatically closed.)
> Close stdin for some processes

- src/lib/mina_lib/mina_lib.ml
- src/lib/verifier/prod.ml
Close stdin when verifier or SNARK worker terminate.
Same as #9178, except against `compatible`, and the calls for the `Ok` cases for the SNARK worker are factored out into one call.
> Close stdin for verifier, snark worker (in compatible)

- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
- src/lib/child_processes/child_processes.ml
- src/lib/child_processes/child_processes.mli
- src/lib/child_processes/termination.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_net2/mina_net2.ml
- src/lib/prover/prover.ml
- src/lib/verifier/prod.ml
My understanding of the world: After a process is created, there should be exactly one `wait` on that process:
- if there's no `wait`, after the parent terminates, the child will be a "zombie" process
- the child's exit-or-signal status is reported to the parent upon the first `wait`; any `wait` after the first one will raise `WNOHANG`
The `wait` loop in the daemon violates this principle, because it waits on all child processes. So if it finds a terminated child, any other `wait` on that child will raise a `WNHOHANG`. I added this loop in early days to detect crashed children, but the `wait`s that exist specifically for those children should serve that purpose.
After the removal of this loop, I'm supposing that the monitors around `Process.run` may be unnecessary.
The pid table used by …
> Remove daemon wait loop

- src/lib/child_processes/termination.ml
- src/lib/mina_lib/mina_lib.ml
The SNARK worker process was not being registered as a child process, as is done for the verifier, prover, and libp2p helper.
There was code to remove its pid from the child process table, which was never added, in fact. :-)
> Register snark worker process

- src/app/client_sdk/client_sdk.ml
- src/app/client_sdk/dune
- src/app/client_sdk/poseidon_hash.ml
- src/app/client_sdk/tests/poseidon_test_vectors.json
- src/app/client_sdk/tests/test_hash.js
This commit exports an OCaml poseidon hash implemention to javascript.
It uses the fp_3 parameters (see https://github.com/o1-labs/marlin/blob/master/oracle/src/poseidon.rs#L73).
In particular, the javascript implementation has two methods:
- `hashBytearray` to hash an opaque array of bytes. The type expected is a Uint8Array.
- `hashFieldElems` to hash an array of field elements. The field elements must be represented in little-endian hex encoded form.
Both methods return a digest in hexadecimal form of a little-endian encoded field element.
For more details see https://hackmd.io/ecBTibDpTzGdH9WM30gwQw
> [crypto] poseidon.js

- src/app/archive/create_schema.sql
Add indexes for columns used in JOINs when loading user and internal commands, to speed up the replayer and other code that relies on querying the archive db.
The replayer test in CI had been taking about 30 minutes, this reduces the time to about 20 minutes.
Closes #9177.
> Index JOIN columns in archive db

- src/lib/network_pool/snark_pool.ml
This PR tweaks the behaviour of the snark pool so that looking up the worker in a detached ledger causes the snark work to be rejected instead of crashing the daemon.
Checklist:
Closes #9152
> Protect against detached ledger crashes in snark pool

- src/lib/integration_test_lib/wait_condition.ml
Fixed a race condition that causes node syncs to non-deterministically fail.
CI will not pass on this due to the current marlin build issue fixed in https://github.com/MinaProtocol/mina/pull/9291, but I applied that change locally and was able to successfully build.
> Fix integration test race condition on node syncs

- src/lib/merkle_mask/masking_merkle_tree.ml
For mask ledgers, `num_accounts` built a set of accounts, and returned the cardinality of that set. With a large number of accounts, that's time-consuming.
Instead, use the current `last_filled` field, the same as is done for database ledgers.
Closes #9275.
> Faster num_accounts

- src/app/cli/src/cli_entrypoint/dune
- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
- src/app/client_sdk/client_sdk.ml
- src/app/client_sdk/dune
- src/lib/block_producer/block_producer.ml
- src/lib/cache_lib/impl.ml
- src/lib/child_processes/termination.ml
- src/lib/mina_lib/config.ml
- src/lib/mina_lib/dune
- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_lib/mina_lib.mli
- src/lib/secrets/keypair.ml
- src/lib/secrets/keypair_read_write.ml
- src/lib/secrets/uptime_keypair.ml
- src/lib/secrets/wallets.ml
- src/lib/secrets/wallets.mli
- src/lib/signature_lib/private_key.ml
- src/lib/snark_worker/prod.ml
- src/lib/string_sign/dune
- src/lib/string_sign/string_sign.ml
- src/lib/uptime_service/dune
- src/lib/uptime_service/uptime_service.ml
- src/lib/uptime_service/uptime_snark_worker.ml
- src/nonconsensus/string_sign/dune
- src/nonconsensus/string_sign/string_sign.ml
- src/string_sign.opam
- src/string_sign_nonconsensus.opam
- src/uptime_service.opam
Uptime service for Mina Foundation delegation program.
Every 5 slots (15 minutes), if the node will produce a block within the next 5 slots, send that block to the uptime backend. Else, send a block from the best tip and some transaction SNARK work. The code for this is in a new library `Uptime_service`.
Specifically, the SNARK work is the Base64 encoding of a `Bin_prot`-serialized instance of the type:
```ocaml
type proof_data =
{ proof: Ledger_proof.Stable.Latest.t
; proof_time: Core_kernel.Time.Span.t
; snark_work_fee: Currency.Fee.Stable.Latest.t
```
This type is not versioned, so the verifier will need to be using the exact same type.
The daemon CLI adds two new flags:
```
[--uptime-submitter PUBLICKEY]                      Public key of the
submitter to the uptime
service of the …
```
> Uptime service for delegation program

- src/lib/ledger_catchup/super_catchup.ml
This PR did a small optimization on state_hash downloading during super_catchup.
The current implementation would try to do a `get_transition_chain_proof` rpc call on every peer until it gets one valid answer. This is not very efficient. My change is to compute a set of preferred set and let the node try those preferred peers first before it attempts at other non-preferred peers.
> optimize state_hash downloading during catchup

- src/lib/mina_graphql/mina_graphql.ml
For the GraphQL mutation `setStaking`, if a given key is locked, it's unavailable as a block production key. Despite that, the existing log always indicated that the passed-in keys were the new block production keys.
Instead, indicate which of the passed-in keys are the new block production keys, and issue a warning log if any of the passed-in keys is locked.
> setStaking, log locked block production keys

- src/app/rosetta/make-runtime-genesis.sh
- src/app/rosetta/start.sh
- src/app/rosetta/test-agent/agent.ml
- src/lib/mina_commands/mina_commands.ml
Get the Rosetta test-agent to run again.
Changes:
- comment out tests involving token creation
- increase wait times for block production
- `add_genesis_winner` in generated config file
- increase sleep time before starting Rosetta
- in demo code, always have `Synced` status
The wait times for block production are tuned to the short slots (2 sec) for the `dev` profile. So running the test agent with a daemon on a "real" network, not in demo mode, will fail. Nonetheless, retaining the otherwise-harmless check for sync status, in case the test is updated to allow running with a real network.
Testing: ran `start.sh` twice in a row with a 0 exit status.
This PR is part of updating Rosetta to use current models.
> Update Rosetta test-agent

- src/libp2p_ipc/libp2p_ipc.capnp
We made a decision today (due to lack of async support on the ocaml capnp-rpc library) to move forward with only utilizing the Cap'N Proto serialization format rather than the entire Cap'N Proto RPC protocol. We will continue to look into a full upgrade to the Cap'N Proto RPC protocol, but this scope cut will allow us to still deliver a large benefit in the meantime without risk of extending our deadline on the networking project.
> Redescribe libp2p IPC format without capnp RPC

- src/libp2p_ipc/libp2p_ipc.capnp
Cap'N Proto generics were causing some issue on the OCaml codegen, and Go lacks generics anyway, so we decided to move towards a non-generic approach. Additionally, I did some renaming of some of the struct names and fields so that the names in the generated OCaml code get translated properly from `CamelCase` to `snake_case`.
> Remove generics from libp2p_ipc description; improve OCaml codegen

- scripts/archive/coinbase-account-fees.sh
- src/app/archive/archive_lib/extensional.ml
- src/app/archive/archive_lib/processor.ml
- src/app/archive/create_schema.sql
- src/app/extract_blocks/extract_blocks.ml
- src/app/extract_blocks/sql.ml
Add a new column, `account_creation_fee_paid`, to `blocks_internal_commands`. An internal command can create a new account, and we'd like to be expose the account creation fee. We need that for Rosetta, so the balances will reconcile. The Rosetta changes will be in a subsequent PR.
In the archive db, when there's a coinbase internal command added, if the balance after the command is 1 Mina less the coinbase amount, it must be a new account, and we enter 1000000000 nanoMina in that column.
*THIS IS A TEMPORIZING BUT SAFE HACK*
Eventually, we'll want to have internal commands return a list of `Transaction_status.t`s. Coinbases and fee transfers can consist of multiple commands, so we need a status for each. That's a biggish/riskier change which we can do in a later PR.
Other changes:
- add …
> Account creation fee for coinbases in archive db

- src/app/rosetta/lib/account.ml
- src/app/rosetta/lib/block.ml
- src/app/rosetta/rosetta.conf
- src/lib/rosetta_lib/operation_types.ml
In Rosetta, handle account creation fees for internal commands, as were added in #9356. Add a new operation `Account_creation_fee_via_fee_receiver` for this purpose.
Also, when creating a Rosetta `Transaction_identifier.hash`, prepend the Mina internal command type and `:` to the actual hash, because the archive db schema makes the type, hash unique, so duplicate hashes are possible (and occurred during Rosetta testing).
Other fixes:
- in `rosetta.conf`, change the network name to `dev` from `debug`
- for the query in `Balance_from_last_relevant_command`, take the union of balances from fee payer, source, and receiver in user commands; there had been a `JOIN` over those, which resulted in 0 rows rturned when any of those was `NULL` in `blocks_user_commands`, causing the genesis ledger …
> Rosetta handle internal cmd account creation, dup txn hashes

- scripts/archive/internal-command-account-fees.sh
- src/app/archive/archive_lib/processor.ml
Update and rename archive db patch script to add an account creation fee for all internal commands, not just coinbases, when the receiver balance is the fee less 1 MINA.
The archive processor adds that creation fee for all internal commands when that same 1 Mina difference exists, not just for coinbases.
Tested the script by patching a local copy of the devnet archive db, running `rosettta-cli` with that patched db.
> Patch and create account creation fees for all internal cmds

- src/app/archive/archive_lib/processor.ml
- src/app/rosetta/lib/account.ml
- src/lib/mina_base/signed_command.ml
Two changes:
- The Caqti type for coinbase amounts and fee transfer fees is changed from `int` to `int64`, because the db schema uses `bigint` for internal command amounts 
- for Rosetta, to retrieve the "last relevant command", consider the secondary sequence number in the descending sort, using a dummy 0 for user commands
The Rosetta change did not seem to fix any of the observed errors reported by `rosetta-cli`, but it could avoid errors.
Probably there are no errors fixed by the archive db change, the amounts for fees and coinbases are usually small. It's better to have the types match up, though.
> int64 for internal cmd amounts, secondary seq no in Rosetta last relevant command

- src/lib/mina_lib/mina_lib.ml
- src/lib/network_pool/network_pool_base.ml
Adds additional tracing to the various components of the mina daemon that are spawned from `Mina_lib`, including the network pools.
> More tracing for release/1.2.0

- scripts/replayer-test.sh
- src/app/replayer/replayer.ml
- src/app/replayer/sql.ml
Allow the replayer to start with an arbitrary staged ledger, instead of the genesis ledger. The input file now allows an optional field, `start_slot`, default `0`, corresponding to the staged ledger.
The field `target_epoch_ledgers_state_hash` becomes optional. If not given, the replayer will try to play through the block of greatest height along the canonical chain. Additionally, if that field is omitted, don't produce output, because the output contains staking ledgers, meant for use at a hard fork. The thinking is, if you omitted the field, you meant to validate the data in the archive db.
The cli flag `--ouput-file` becomes optional, so we don't have to specify `/dev/null` in CI tests.
Tested by printing the ledger at an arbitrary slot when running the `replayer-test.sh` script; using …
> Replayer, start with arbitrary staged ledger

- src/lib/cli_lib/commands.ml
This is a small change to move the "Using password from..." message from stdout to stderr. This message complicates automation since it has to filter for it, e.g. automatic restarts, vrf commands, metrics.
> feat: moves "Using password from..." to stderr

- src/lib/rosetta_lib/errors.ml
This makes Rosetta not fail if the daemon (temporarily) times out
> Make the GraphQL error retriable

- src/app/rosetta/lib/account.ml
In Rosetta, the `account/balance` query was returning a nonce in the response metadata, which makes no sense for historical balance lookups, and probably not even for the current balance. That was the only metadata item, so make the metadata `null` (None in OCaml).
Other than the nonce, the results of GraphQL query made on every balance query were only used for current balances, so move the GraphQL call there, and don't call it for historical balances.
Tested by running `view:balance` from rosetta-cli, with and without a block height.
> Rosetta, remove nonce from balance response

- dockerfiles/Dockerfile-mina-daemon
Use 65534 as the safe user ID for the mina home directory. As requested on discord in #qa-task-force by user `KP`.
> lk86/fix-docker-permissions Use a smaller UserID for the mina user in docker

- src/app/replayer/replayer.ml
- src/app/replayer/sql.ml
The archive processor was updated recently to populate a new column `receiver_account_creation_fee_paid` in `blocks_internal_commands`. For existing archive databases, the script `internal-command-account-fees.sh` adds the column and populates it with values.
To make sure that a database has that column with correct values, verify those values in the replayer. That is, make sure it has the correct value when needed, and NULL when not needed.
Tested by running the replayer test locally, the same one that's run in CI.
Closes #9430.
> Replayer, verify account creation fee for internal commands

- src/app/rosetta/docker-start.sh
Otherwise Rosetta breaks before starting when trying to connect to devnet
> Default MINA_CLIENT_TRUSTLIST to empty

- src/app/rosetta/README.md
> Rosetta: Docker uses 16GB ram instructions

- src/lib/mina_base/party.ml
- src/lib/mina_base/transaction_logic.ml
- src/lib/transaction_snark/transaction_snark.ml
This PR builds upon #9354.
This adds a `timing` field to the `changes` record within a party. When a party in a transaction results in the creation of an account, this data is used to set the timing info for that account. If the timing data is invalid (e.g. the initial balance is below the actual balance) or the account already exists then the update fails, and the only effect of the transaction is to charge the fee to the fee payer.
This also fixes a bug where a party receiving funds had their timing calculated as if they were sending them, which would make the snark unsatisfiable for any such transaction.
Checklist:
> Allow accounts to be created with timing info in parties transactions

- graphql_schema.json
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/pickles/composition_types/index.ml
- src/lib/pickles/dune
- src/lib/pickles/limb_vector/constant.ml
- src/lib/pickles/pickles.mli
- src/lib/pickles/proof.ml
Name the fields in the input to a GraphQL Snapps transaction.
Tested by taking an existing transaction used to test the code in #9466, and modifying it to conform to this format, and running against a daemon in demo mode.
Here's that input: https://gist.github.com/psteckler/b3ab4632b55e565dac5f723ef40b07a8
The new input is a bit more verbose than the JSON-derived input. Constructors like `Set`, `Keep`, `Check`, `Ignore` are in fields with names, rather than as unadorned list elements.
> Explicit fields for GraphQL Snapp txns

- frontend/client_sdk/README.md
- frontend/client_sdk/package.json
- frontend/client_sdk/src/MinaSDK.d.ts
- frontend/client_sdk/src/MinaSDK.re
- frontend/client_sdk/src/SDKWrapper.d.ts
- frontend/client_sdk/src/SDKWrapper.ts
- frontend/client_sdk/test/Test.ts
- Renamed all references of `CodaSDK` to `MinaSDK`. The new usage is reflected in `Test.ts`. 
- Bumped major version number
- Code formatting was additionally applied.
Checklist:
Closes  #9468
> fix: Rename CodaSDK -> MinaSDK

- src/app/archive/archive_lib/extensional.ml
- src/app/archive/archive_lib/processor.ml
- src/app/extract_blocks/extract_blocks.ml
- src/app/replayer/replayer.ml
- src/app/replayer/sql.ml
In extensional blocks and the replayer code, changed `global_slot` to `global_slot_since_hard_fork`, to disambiguate from `global_slot_since_genesis`. In the replayer, use `global_slot_since_genesis` uniformly.
Update the input file to use `start_slot_since_genesis`.
Verified that the replayer test still passes locally.
Part of #9502.
> Slot since genesis in replayer, extract blocks

- CHANGES
- src/lib/verifier/prod.ml
Remove the code introduced in #5911 that automatically restarts the verifier every 15 minutes.
The restarts were to avoid problems due to memory leaks, which reportedly no longer exist.
Tested by running a node against mainnet for 21 minutes, the verifier did not restart.
> Remove verifier auto-restart

- src/lib/crypto/kimchi_backend/common/endoscale_round.ml
- src/lib/crypto/kimchi_backend/common/endoscale_scalar_round.ml
- src/lib/crypto/kimchi_backend/common/plonk_constraint_system.ml
Adding backend code for the new endomul scalar custom gate of kimchi, see https://github.com/o1-labs/proof-systems/pull/199
> [kimchi][backend] add backend code for new endoscale scalar gate

- graphql_schema.json
- src/app/archive/snapp_tables.sql
- src/lib/genesis_ledger_helper/lib/genesis_ledger_helper_lib.ml
- src/lib/hash_prefix_states/hash_prefix_states.ml
- src/lib/hash_prefix_states/hash_prefix_states.mli
- src/lib/hash_prefixes/hash_prefixes.ml
- src/lib/mina_base/party.ml
- src/lib/mina_base/permissions.ml
- src/lib/mina_base/permissions.mli
- src/lib/mina_base/snapp_account.ml
- src/lib/mina_base/snapp_generators.ml
- src/lib/mina_base/snapp_predicate.ml
- src/lib/mina_base/transaction_logic.ml
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/runtime_config/runtime_config.ml
- src/lib/transaction_snark/transaction_snark.ml
Rename `rollup_events` to `sequence_events`.
Closes #9688.
Note: this name change will trigger the versioned type linter error. The serialization of the type hasn't changed, so the error can be ignored.
> Rename rollup_events to sequence_events

- graphql_schema.json
- src/app/cli/src/init/client.ml
- src/lib/mina_graphql/mina_graphql.ml
* deprecate setStaking graphql and cli command. 
*tested the cli command and the graphql mutation  by running a node locally
Checklist:
* Closes #0000
> deprecate setStaking command

- dockerfiles/stages/1-build-deps
This should presumably fix CI.
Checklist:
> Checkout opam-repository over https

- dockerfiles/stages/1-build-deps
- src/lib/ledger_catchup/super_catchup.ml
- src/lib/mina_base/signed_command.ml
- src/lib/mina_base/signed_command_intf.ml
- src/lib/network_pool/batcher.ml
- src/lib/network_pool/batcher.mli
- src/lib/network_pool/transaction_pool.ml
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/verifier/common.ml
- src/lib/verifier/dummy.ml
- src/lib/verifier/dune
- src/lib/verifier/prod.ml
- src/lib/verifier/verifier_intf.ml
Verification failures had been captured by a single token `Invalid`. We have more information than that, which we can return.
There are three sources of failure: invalid keys, invalid signatures, and invalid proofs.
The ultimate consumer of the verification result seems to be `Staged_ledger.check_commands`, which is called directly by `Staged_ledger.apply`.
Introduce a new function, `Signed_command.check_only_for_signature`, which omits the key validation in `check`. The new function also returns a `With_valid_signature.t`. With that new function, we can make a separate call to validate the keys, and return an appropriate error.
Part of #9592.
> Distinguish verification failures

- scripts/compare_ci_diff_types.sh
This brings the behaviour into line with the 'binable compatibility changes' PR, and should stop the spurious failures we see for this job in CI.
Checklist:
> Use the correct branch name for 'versions compatibility changes' in CI

- Makefile
- buildkite/scripts/check-graphql-schema.sh
- buildkite/src/Command/CheckGraphQLSchema.dhall
- dune
- graphql_schema.json
- src/app/cli/src/init/dune
- src/app/graphql_schema_dump/dune
- src/app/graphql_schema_dump/graphql_schema_dump.ml
This PR
* adds an ocaml executable `graphql_schema_dump` for generating the schema
* adds a dune rule to generate the schema during build using this executable
- this rule includes a `(mode promote)` stanza, so the file is updated automatically when there are changes
* adds the preprocessor dependency on the `graphql_schema.json` file to ensure that it gets regenerated during build
This removes the need to start a daemon in order to dump the GraphQL schema, and also removes the need to use a python script to generate it. This should also ensure that the schema is never out-of-date, since `make build` and friends will always automatically update it.
Since this uses `Yojson.Safe.pretty_to_string` to output the schema, the formatting is different from the formatting generated by python. …
> Generate graphql_schema.json during build

- src/lib/pickles/commitment_lengths.ml
This error was introduced in df12992198627f0f115a617dd4197ee5322d6d93, where the `generic` version was updated correctly to use `h` everywhere, but the `generic'` version incorrectly used `n` instead of `h`. Since we weren't using side-loaded keys anywhere at the time, this was also missed during testing.
**NOTE: This is deliberately against `develop` rather than `compatible`, because this change will cause snark keys to change!**
Checklist:
> Fix commitment lengths for side-loaded verification keys

- src/lib/uptime_service/uptime_service.ml
If POST to the uptime service returns a code other than 200, retry it. The retries occur in a bounded loop, and there's a uniform pause between them. The number of retries and pause are constants that could be tweaked, if desired.
Tested the code with an unregistered uptime submitter key, and the each retry produced a 401 Unauthorized response, and the loop terminated.
I was unable to test with a registered key, but the submission code is as before, so I have good confidence that it works correctly.
> Uptime service, retry POST

- scripts/archive/add_chain_status.sh
This PR add a script to add a new column `chain_status` to the `blocks` table in the archive database. That column contains either `canonical` or `orphaned`, and is nullable.
The script makes the genesis block, which has global_slot = 0, canonical.
Then, the script makes a recursive query from a block with the maximum height back to the block of greatest height that is marked canonical. The expected length of that subchain is the difference in those heights, plus 1. If the actual length is that expected length, mark blocks along the subchain whose height is leq the maximum height - `k` as canonical. Mark other blocks with the same heights, but not along the chain, as orphaned.
Blocks are marked as canonical in ascending height order. Therefore, if the script is interrupted, it can be …
> Script to add chain_status to blocks table

- src/app/archive/archive_lib/chain_status.ml
- src/app/archive/archive_lib/extensional.ml
- src/app/archive/archive_lib/processor.ml
- src/app/archive/create_schema.sql
- src/app/extract_blocks/extract_blocks.ml
- src/app/extract_blocks/sql.ml
Add a new column to the `blocks` table, `chain_status`, that can be either `canonical` or `orphaned`, and is nullable.
When a new block is added to the table, find a subchain back to the highest block that is canonical. For all blocks along that subchain that are least `k` blocks lower than the new block, mark them as canonical. For blocks that meet the same height criterion, but are not in the subchain, mark them as orphaned. This is the same algorithm used in the script in #9795.
Tested by adding extensional blocks using the `archive_blocks` app, verifying that the new code is called.
> Update chain status in archive db when blocks added

- src/lib/block_producer/block_producer.ml
- src/lib/cli_lib/default.ml
- src/lib/daemon_rpcs/types.ml
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/uptime_service/uptime_service.ml
- src/lib/vrf_evaluator/vrf_evaluator.ml
* update next producing time in the daemon status when there are no more slots won. 
* Added a new status `Evaluating VRF` when there are no slots won and vrf evaluations are still in progress 
For example-
`Evaluating VRF… Last checked global slot 576 (Generated from consensus at slot: 544 slot-since-genesis: 544)`
* Updated daemon stop time to 7 days
* ran a BP node locally and checked `mina client status`
Checklist:
* Closes #0000
> fix next producing time in daemon status (1.2.1)

- src/app/rosetta/docker-start.sh
- src/app/rosetta/download-missing-blocks.sh
Make download-missing-blocks run forever and in the background
---
*
*
Checklist:
* Closes #0000
> lk86/rosetta-bootstrap-forever 

- src/app/rosetta/lib/account.ml
- src/app/rosetta/lib/block.ml
The rosetta side of the equation
* Only use the archive-node path for /account/balance
* Use chain-status for "old" queries of blocks rather than the slower recursive queries
* TODO: Blocked on #9796 and running #9795 on one of the databases
* After it's unblocked, we should sync a node and poke at the endpoint a bit and then try cli check:data
> Rosetta: Fast canonical lookups chain_status

- src/app/archive/archive_lib/processor.ml
Adding blocks, including precomputed blocks via `archive_blocks`, was failing because Postgresql thought the chain status was a string.
Inserting a type annotation for `chain_status_type` allows blocks to be added.
> Add type annotation for chain_status in SQL

- src/app/rosetta/lib/account.ml
- src/app/rosetta/lib/block.ml
* Make sure the recursive query stops before going too far, and fallback
to the historical query in that case with (min_recent_height-1)
* Will want to test live
> Rosetta: Short circuit recursive near tip

- dockerfiles/auxiliary_entrypoints/01-run-demo.sh
Fixes a typo preventing the RUN_DEMO=true logic from working properly. There are more issues with this script remaining in master and release/1.2.0 (to be fixed in a future PR) but this solves the more minor problems in compatible
> lk86/fix-demo-script Fix demo script

- scripts/archive/add_chain_status.sh
- src/app/archive/archive_lib/chain_status.ml
- src/app/archive/archive_lib/extensional.ml
- src/app/archive/archive_lib/processor.ml
- src/app/archive/create_schema.sql
- src/app/extract_blocks/extract_blocks.ml
- src/app/rosetta/lib/account.ml
- src/app/rosetta/lib/block.ml
This PR against `rosetta-1.2.1-safe` contains the changes to use `pending` instead of NULL for chain status, as in #9810.
It also simplifies the Rosetta `account` and `block` queries, because the `chain_status` column is now never NULL.
> Chain status pending, update queries

- scripts/compare_test_signatures.sh
- src/app/archive/archive_lib/processor.ml
- src/app/archive/create_schema.sql
- src/app/client_sdk/client_sdk.ml
- src/app/client_sdk/dune
- src/app/client_sdk/js_util.ml
- src/app/client_sdk/tests/dune
- src/app/client_sdk/tests/test_signatures.js
- src/app/client_sdk/tests/test_signatures.ml
- src/lib/signature_lib/schnorr.ml
- src/lib/string_sign/dune
- src/lib/string_sign/string_sign.ml
- src/nonconsensus/string_sign/dune
In the client SDK, add a required network argument to the methods `signString` and `verifyStringSignature`. The argument must be either "mainnet" or "testnet" (case irrelevant), or an exception will be raised.  If we wish to omit that argument, the typescript wrapper can add a default.
Formerly, `signString` returned just a signature object. In this PR, it returns an object with the signature, the string that was signed, and the signer's public key.  That matches the signing methods for payments and delegations, which return information about what was signed, and who signed it.
Added tests that compare the consensus/nonconsensus code for string signing and verification, which are run by the `compare_test_signatures` script in CI.
Simplified `String_sign` to rely on the signer and verifier …
> Client SDK, signature kind arg to string signer, verifier

- src/app/client_sdk/client_sdk.ml
- src/app/client_sdk/tests/test_signatures.js
- src/app/client_sdk/tests/test_signatures.ml
- src/lib/mina_base/signed_command.ml
- src/lib/mina_base/signed_command_intf.ml
In client SDK, require a network argument when signing and verifying such signatures for payments and stake delegations. The Typescript wrapper can choose a default, if desired. 
#9808 made a similar change for signing strings, and verifying those signatures.
To enable that change, added an optional signature kind argument to `Signed_commands.{sign, sign_payload}`.
In the `compare_test_signatures` script for CI, run the signers and verifiers, including the ones for strings, for both networks. That script passes locally.
> Client SDK, choose network when signing payments, delegations

- scripts/archive/add_chain_status.sh
- src/app/archive/archive_lib/chain_status.ml
- src/app/archive/archive_lib/extensional.ml
- src/app/archive/archive_lib/processor.ml
- src/app/archive/create_schema.sql
- src/app/extract_blocks/extract_blocks.ml
In the archive database, use `pending` for chain status instead of a NULL. Avoiding NULLs lessens the chance for error and simplifies queries.
The migration script is updated accordingly. We'll have to migrate the live databases after merging this.
Tested the migration script on a local database. For an already-migrated database, the column and chain status type need to be DROPped before running the script.
> Chain status 'pending' instead of NULL

- src/lib/mina_base/ledger.mli
- src/lib/mina_base/parties_logic.ml
- src/lib/mina_base/sparse_ledger.mli
- src/lib/mina_base/transaction_logic.ml
- src/lib/mina_base/transaction_status.ml
- src/lib/mina_state/local_state.ml
- src/lib/mina_transition/external_transition_sample_precomputed_block.ml
- src/lib/transaction_snark/transaction_snark.ml
- src/lib/transaction_witness/transaction_witness.ml
- src/lib/transaction_witness/transaction_witness.mli
Propagate failures in `Parties_logic` to errors in `Transaction_logic.apply_transaction`.
The strategy for that is to add a new field `failure_status` in `Parties_logic.Local_state.t`. Outside the transaction SNARK, that's a `Transaction_status.Failure.t option`; inside the SNARK, it's `unit`.
In `apply_parties_unchecked_aux`, if a step returns a local status with a failure, we convert that failure to an error.
Some bits to review carefully: 
- `Mina_state.Local_state.to_input` changes, which relies on `Transaction_status.Failure.option_to_input`
- in the same module, `failure_status_typ`, which relates `failure_status` types in/out the SNARK
- also `gen` in that module, which relies on `Transaction_status.Failure.gen`
Closes #9592
> Propagate Parties.t failures to apply_transaction

- src/app/archive/archive_lib/test.ml
- src/lib/mina_base/snapp_generators.ml
- src/lib/network_pool/transaction_pool.ml
For some reason, it had been necessary to add `~succeed:false` when invoking this generator to make the test succeed, but that's no longer reproducible. That flag is only meant to affect whether the generated Snapp can be applied successfully, so it should have no affect on this test. 
Remove the use of that flag. Also, update all the Snapp generators so the flag is actually optional. If all the arguments to a function are labelled, then arguments with `?` are not optional. Adding a unit argument makes those optional.
Remove a comment that hid some no longer used code.
> Remove ~succeed from Snapp generator in archive unit test

- src/app/archive/create_schema.sql
Add indexes in the archive db schema for all columns mentioned in the `JOIN` predicates used in the queries in `Balance_from_last_relevant_command`.
Tested by importing the schema with `psql`.
> Add indexes to archive db schema for Rosetta account query

- src/app/rosetta/lib/block.ml
* Removes distinct when not needed from a query
* Tested manually by port-forwarding in postgres, still returns results on mainnet for the offending block that it broke on in our testing
> Rosetta: Removes distinct via usercommand query

- src/lib/consensus/proof_of_stake.ml
* Security checked code that indeed genesis epoch seed is derived
with nothing-up-my-sleeve numbers
* Cross-checked with team members
* Closes #9768
> Removed completed non-determinable genesis epoch seed todo comment

- scripts/archive/add_chain_status.sh
The migration script was missing the NOT NULL constraint. 
No NULL values were created because we had the `DEFAULT` value, but without the constraint, the integrity of the database could be compromised by later actions.
> Add NOT NULL constraint when adding chain_status column

- src/app/archive/archive_lib/processor.ml
The code to add extensional blocks in the archive processor had a `TEMP` comment for the account creation fees associated with internal commands, and always passed `None` as the creation fee.
The data is there in the extensional block, so use that value.
> Add account creation fee for internal command when adding extensional blocks

- src/app/archive/archive_lib/processor.ml
- src/app/archive/create_schema.sql
- src/app/extract_blocks/extract_blocks.ml
- src/app/migrate-balances-table/dune
- src/app/migrate-balances-table/migrate_balances_table.ml
- src/app/migrate-balances-table/sql.ml
- src/app/replayer/replayer.ml
- src/app/replayer/sql.ml
- src/migrate_balances_table.opam
Add extra columns to the `balances` table in the archive db schema, to speed up Rosetta queries and make them less resource-intensive.
Update the archive processor to populate those extra columns.
There's a new app, `migrate_balances_table` to convert existing databases to the new format. Tested that app by migrating the replayer test database, then running the replayer, which verifies balances after running each transaction. The replayer found bugs in the migration app. After fixing those bugs, the replayer succeeded.
The migration app add cursor tables to the db, so that if it crashes, the app can be restarted and resuming (approximately) where it left off.  The app does not remove those tables, they can be DROPped manually (or I can add an automatic DROP if desired). Such restart …
> Extend balances table for better Rosetta

- src/app/rosetta/docker-start.sh
- src/app/rosetta/lib/account.ml
Use the new block columns from the `balances` table for Rosetta account balance queries.
The new query eliminates the `relevant_block_balances` subquery.
Tested by running a daemon on mainnet, and the rosetta app connected to a local migrated database, then running `rosetta-cli view_account` on the accounts with lots of dust transactions, at very old heights, and at heights near the max block height in the database. Print statements verified that the old and new queries were both performed.
For a new query, the time was just over a 2 seconds. For an old query, the time average 0.8 seconds.
> Rosetta account balance query using extended balances table

- src/app/rosetta/lib/account.ml
- src/app/rosetta/lib/block.ml
- src/lib/rosetta_lib/errors.ml
- src/lib/vrf_lib/tests/integrated_test.ml
There are two queries for blocks in Rosetta, one for for "old" blocks, another for "recent" blocks. There was a call to dispatch to those two queries, based on the difference between the maximum block height and the height of the query. 
But if we chose the recent query, and the block was already marked as canonical, the query returned no block.
Instead, determine the recency of the block by the chain status of blocks at the requested height. 
If there is a canonical block at that height, the chain status of blocks at that height has been resolved, choose that canonical block.
If there is no canonical block at that height, then find a subchain from the block at maximum height back to a canonical block, and choose the block in the subchain with the requested height.
Also: put the query …
> Use chain status for block recency

- src/app/missing_blocks_auditor/missing_blocks_auditor.ml
- src/app/missing_blocks_auditor/sql.ml
Report gaps in the block chain statuses in the archive db.
There's a gap if there's a `pending` block with a height the same or lower than the highest `canonical` block.
The mainnet `3` `archive_balances_migrated` db had a few of these, since corrected.
The devnet `1` `archive_balances_migrated` db still has many of these, will fix.
> Report chain status gaps in missing blocks auditor

- src/app/missing_blocks_auditor/missing_blocks_auditor.ml
- src/app/missing_blocks_auditor/sql.ml
In `missing_blocks_auditor`, check that all the chain statuses along the canonical chain are, in fact, `canonical`.
Ran on mainnet `archive_balances_migrated`, it had no errors.
Closes #9815.
> Audit canonical chain statuses

- src/lib/ledger_catchup/super_catchup.ml
- src/lib/mina_net2/tests/all_ipc.ml
- src/lib/mina_net2/tests/dune
- src/lib/mina_net2/tests/tests.ml
- src/lib/network_pool/batcher.ml
- src/lib/network_pool/indexed_pool.ml
- src/lib/network_pool/snark_pool.ml
- src/lib/network_pool/test.ml
- src/lib/network_pool/transaction_pool.ml
This PR uses the existing `Inline_test_quiet_logs` library to silence the output of inline tests from `ledger_catchup`, `mina_net2` and `network_pool`. Note that this library only suppresses output for passing tests; failing tests will display their full output.
This significantly reduces the amount of output in the dev unit-tests job in CI (by >3000 lines compared to a recent run), which will make it easier to see and debug actual errors.
Checklist:
> [TRIVIAL] Silence output for passing tests in ledger_catchup, mina_net2, network_pool

- src/app/cli/src/init/client.ml
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/secrets/privkey_error.ml
- src/lib/secrets/secret_file.ml
- src/lib/secrets/wallets.ml
- src/lib/secrets/wallets.mli
*Propagate Privkey_error.t to the account unlock command output
*Added unix error in the error message
* Ran a node locally, deleted imported keys and tried to unlock them. 
Before the change:
```
❌ Error: Wrong password provided (in ["unlockAccount"])
```
After the change
```
❌ Error: Error reading the secret key file: Cannot open file: /.mina-config/wallets/store/B62qjJwgq7kNXYHXQsMeyiMWL7fHsnPeuAiPfYd3yTor3eKpK8VV1gG. Error: No such file or directory (in ["unlockAccount"])
```
Checklist:
* Closes #0000
> show file read errors when unlocking keys

- src/app/rosetta/lib/account.ml
- src/app/rosetta/lib/block.ml
Change query names from `query_old` and `query_recent` to `query_canonical` and `query_pending`, which better reflects the dispatch mechanism to choose these calls. Similarly for `query_height_old` and `query_height_recent`.
Also, remove the extra call to `query_canonical/old` if `query_pending/recent` returns `None`, because that call certainly won't return `Some`.
Tested by running `check:data` on devnet.
> Rosetta, rename queries

- src/app/rosetta/lib/account.ml
- src/app/rosetta/lib/block.ml
- src/app/rosetta/lib/construction.ml
- src/app/rosetta/lib/mempool.ml
- src/app/rosetta/lib/network.ml
- src/app/rosetta/lib/pg_data.ml
- src/app/rosetta/lib/rosetta.ml
Add some logs to Rosetta:
- for account, blocks, and construction endpoints, log the query data
- at some interval, log the Postgresql number of connections and number of locks
The default interval is 30 seconds. That default can be overridden using the environment variable `MINA_ROSETTA_PG_DATA_INTERVAL`, given in seconds.
Tested locally to make sure the Postgresql logs appeared at the given interval.
> Rosetta, log Postgresql connection, locks data

- src/app/missing_blocks_auditor/missing_blocks_auditor.ml
Add an exit code to `missing_blocks_auditor` to indicate errors, to help scripting.
Each possible error is associated with a prime number. When an error occurs, multiply an exit code by that prime number.
A script can check divisibility by a particular prime to see if that error occurred.
If no error occurs, exit with 0.
Tested by running the auditor on an archive db with known errors.
> Exit codes for missing blocks auditor

- src/lib/mina_base/fee_excess.ml
- src/lib/mina_base/parties_logic.ml
- src/lib/transaction_snark/transaction_snark.ml
* Fixed the issue where the fee excess for parties transactions was not in the 'canonical' form i.e., if there is only 1 nonzero excess, it is to the left https://github.com/MinaProtocol/mina/blob/af76cb7980d5e81e704120290a850ea9c6f8522e/src/lib/mina_base/fee_excess.ml#L273
* tested with the following parties transactions that were producing two different fee excess-  
2 parties without a proof
3 parties with a proof
Checklist:
* Closes #0000
> fix fee excess for parties transaction

- src/app/missing_blocks_auditor/missing_blocks_auditor.ml
- src/app/rosetta/lib/account.ml
- src/app/rosetta/lib/network.ml
- src/app/rosetta/rosetta.conf
Fix Rosetta balance queries when the given height is for a pending block.
Strategy:
- Use a `RECURSIVE` query from the block of max height back to a canonical block
- `UNION` all canonical blocks
- `JOIN` that entire chain on the `balances` table
For the network status endpoint, use the latest block in the archive db to the get the "current block" height and state hash.
(Continue to use the GraphQL best tip for the sync status height.)
With these changes, rosetta-cli `check:data` on mainnet succeeds through all block in the archive db. 
Also: Change the `missing_blocks_auditor` to use individual bits for particular errors, rather than prime number factors, which was a crazy idea. Tested the app against the mainnet `3` db.
> Rosetta, fix pending blocks balance query

- src/app/archive/archive_lib/processor.ml
When adding blocks to the archive db, they are marked as pending to start. For blocks `k` or more above the highest canonical block, we can mark additional blocks as canonical.
If there are missing blocks added, they may be below the highest canonical block, and we weren't updating their chain status. In this PR, we add that update.
Algorithm:
- find the closest canonical blocks above and below the new block, and the subchain between them
- mark all blocks in the subchain as canonical, and all other blocks at the same heights as orphaned
Tested by extracting some blocks from the db, deleting the blocks from the db, then re-adding them, verifying that the re-added blocks have the same chain statuses as before. Also tried the same experiment with precomputed blocks, instead of extracted …
> Set chain status when adding intermediate blocks

- src/app/archive/archive_lib/processor.ml
- src/app/archive/snapp_tables.sql
Add `increment_nonce` to the archive db schema as a column with type `boolean` in the table `snapps_party_body`.
Add that field to the type in `Processor.Snapp_party_body`.
N.B.: the type `Party.Fee_payer.t` uses the `unit` type for that field, but `Party.Body.of_fee_payer` converts that unit value to `true`, which will get written to the archive db.
Closes #9886.
> Add increment_nonce to archive db

- graphql_schema.json
- src/app/archive/archive_lib/dune
- src/app/archive/archive_lib/processor.ml
- src/app/archive/archive_lib/test.ml
- src/app/archive/create_schema.sql
- src/app/delegation_compliance/delegation_compliance.ml
- src/app/delegation_compliance/dune
- src/app/delegation_compliance/sql.ml
- src/app/extract_blocks/dune
- src/app/extract_blocks/sql.ml
- src/app/replayer/dune
- src/app/replayer/sql.ml
- src/app/rosetta/lib/block.ml
- src/app/rosetta/lib/dune
- src/lib/mina_caqti/dune
- src/lib/mina_caqti/mina_caqti.ml
- src/mina_caqti.opam
There was a lot of Caqti-related code in `Archive_lib.Processor` of general applicability, that was also used in the `replayer`, `extract_blocks`, and `archive_blocks`.  It seemed awkward to have those apps depends on the processor, so move that code to its own library, `mina_caqti`.
The `vector` Caqti type encoding is removed, because unused.
Also: add mention of a db schema invariant that has been implicit.
This change is preparation for the Snapps-related changes to the replayer and other archive db-related apps (#9260, #9261, #9262).
> Move Caqti code to mina_caqti library

- graphql_schema.json
- src/app/archive/archive_lib/processor.ml
- src/app/archive/snapp_tables.sql
- src/lib/mina_base/parties.ml
- src/lib/mina_base/parties_logic.ml
- src/lib/mina_base/party.ml
- src/lib/mina_base/snapp_generators.ml
- src/lib/mina_base/transaction_logic.ml
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/transaction_snark/transaction_snark.ml
Change `depth` to `call_depth` and `delta` to `balance_change`.
Made that change to OCaml code, in the archive db schema, and in the GraphQL schema.
Note: these changes will trigger the versioned type change linter.  Field name changes, as here, are innocuous, because serializations don't change. So this PR will require manual merge.
Closes #9844.
> Snapps, some renamings

- buildkite/src/Jobs/Test/TestnetIntegrationTests.dhall
- src/app/test_executive/chain_reliability_test.ml
- src/app/test_executive/chain_reliability_test.mli
- src/app/test_executive/peers_reliability_test.ml
- src/app/test_executive/peers_reliability_test.mli
- src/app/test_executive/test_executive.ml
reliability test can be flaky and take a long time, so split it into 2 to make each one shorter and less flaky.
> Split reliability test

- graphql_schema.json
- src/lib/mina_base/ledger.mli
- src/lib/mina_base/parties.ml
- src/lib/mina_base/parties_logic.ml
- src/lib/mina_base/sparse_ledger.ml
- src/lib/mina_base/sparse_ledger.mli
- src/lib/mina_base/transaction.ml
- src/lib/mina_base/transaction_logic.ml
- src/lib/mina_base/transaction_status.ml
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/transaction_snark/transaction_snark.ml
- src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
All balance transfers within a parties transaction should be settled and the fee excess from applying should be equal to the transaction fee 
Checklist:
* Closes #0000
> fail snapp txn when fee excess > txn fee

- graphql_schema.json
- src/lib/mina_base/snapp_generators.ml
In the Snapps generators, we were using incorrect nonces as predicates in two places.
In `gen_party_predicated_signed`, we were generating a nonce.
In `gen_party_predicated_fee_payer`, we were invariantly using the zero nonce.
In both cases, look up the account in the ledger, and use the nonce there.
Closes #9727.
Note that this change does not address the possibility that an account is used more than once in a single Parties.t.
> Snapp generators, nonce from ledger

- src/lib/mina_base/parties.ml
- src/lib/transaction_snark/transaction_snark.ml
The order of accounts when creating sparse ledger was different from the parties application order causing a merkle root mismatch. Fixed by maintaining the order when de-duping
Checklist:
* Closes #0000
> snapps: merkle root mismatch fix

- src/app/archive/archive_lib/processor.ml
- src/app/rosetta/lib/account.ml
This PR is in response to the `check:data` error resulting from trying to lookup a public key that was not in the archive database.
The error apparently results from an account balance query. As part of that, there was a lookup of timing info for a given public key, which was assumed to be in the database.
The fix is to try to lookup the key before any other database queries, and return `Account_not_found` if the key is not present.
The timing info lookup is modified to return `None` if the key is not present, although the fix just mentioned will prevent the timing info lookup from being called.
(I will test on `devnet` before we release this code.)
> Rosetta, return error if no account

- src/lib/fake_network/fake_network.ml
- src/lib/fake_network/fake_network.mli
- src/lib/ledger_catchup/super_catchup.ml
- src/lib/transition_frontier/frontier_base/breadcrumb.ml
- src/lib/transition_frontier/frontier_base/breadcrumb.mli
https://github.com/MinaProtocol/mina/issues/9403
Super catchup failure and recovery unit tests.
If catchup fails, some cleanup needs to be done. Catch-uping with a block consists of the following steps: 1. downloading state hashes; 2. download block; 3. initial validation; 4. verification of transaction snark; 5. build breadcrumb; 6. add those blocks to transition frontier. If any step fails, then we have some clean up jobs to do.  
These following test were originally spec'd, but jiawei and i have decided that they don't actually make sense to test
> catchup failure cases unit tests

- src/app/rosetta/lib/account.ml
- src/app/rosetta/lib/block.ml
- src/app/rosetta/lib/network.ml
In Rosetta, several of the queries for blocks order results by timestamp, but timestamps are not unique.
For those queries, add `state_hash` as an additional field to qualify the ordering. The ordering of state hashes is arbitrary, of course, but makes these queries deterministic.
> Rosetta, making block queries deterministic

- src/app/rosetta/lib/block.ml
- src/app/rosetta/lib/network.ml
In Rosetta, allow use of environment variable `MINA_ROSETTA_MAX_HEIGHT_DELTA` to limit the maximum height of block queries. 
Let `d` be the value of that variable. If the maximum height of blocks is `h` in the archive db, then a query for a block of height greater than `h - d` will return `None`.
This change affects not only direct `block` queries, but also `account/balance` queries, both of which call `Block.run`. In both cases, the `None` becomes the `Block_missing` error.
The environment variable is also used to determine the height of the latest block in the `/network/status/` endpoint.
If the environment variable is absent, a zero value is used for the delta.
The purpose of this change is to disallow queries for blocks near the tip, whose ultimate chain status is uncertain.
> Rosetta, limit max height of block queries

- src/app/archive/archive_lib/extensional.ml
- src/app/archive/archive_lib/processor.ml
- src/app/archive/create_schema.sql
- src/app/archive/snapp_tables.sql
- src/app/extract_blocks/extract_blocks.ml
- src/app/extract_blocks/sql.ml
- src/app/replayer/dune
- src/app/replayer/replayer.ml
- src/app/replayer/sql.ml
- src/app/rosetta/lib/block.ml
- src/lib/consensus/intf.ml
- src/lib/mina_base/epoch_data.ml
- src/lib/mina_base/party.ml
- src/lib/mina_base/snapp_predicate.ml
- src/lib/mina_caqti/mina_caqti.ml
Update the replayer to handle Snapp commands.
As before, the app replays commands ordered by global slot and sequence number. There are now three lists of commands, user commands, internal commands, and Snapp commands, so choosing the next command to run is a little more involved.
The function `run_snapp_command` runs the Snapp commands, by constructing a `state_view` from a parent block, and a `Parties.t`, then running `Ledger.apply_parties_unchecked`. 
To create the fee payer body in a `Parties.t`, we create an ordinary `Party.Body.t`, and substitute the fee and the unit value placeholders. That approach does more work than necessary, but allows reuse of code. Reviewers: too much of a hack?
There are some new db columns in `epoch_data` and `blocks`, needed to construct a state view when …
> Replayer, update for Snapps

- src/app/cli/src/init/transaction_snark_profiler.ml
- src/lib/merkle_ledger/any_ledger.ml
- src/lib/merkle_ledger/base_ledger_intf.ml
- src/lib/merkle_ledger/database.ml
- src/lib/merkle_ledger/null_ledger.ml
- src/lib/merkle_mask/masking_merkle_tree.ml
- src/lib/merkle_mask/masking_merkle_tree_intf.ml
- src/lib/mina_base/dune
- src/lib/mina_base/ledger.mli
- src/lib/mina_base/pending_coinbase.ml
- src/lib/mina_base/sparse_ledger.ml
- src/lib/mina_base/sparse_ledger.mli
- src/lib/mina_base/transaction_logic.ml
- src/lib/sparse_ledger_lib/sparse_ledger.ml
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/staged_ledger/staged_ledger.mli
- src/lib/transaction_snark/transaction_snark.ml
- src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
- src/lib/transaction_snark_scan_state/transaction_snark_scan_state.mli
- src/lib/transition_frontier/full_frontier/full_frontier.ml
- src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
Changes:
* Removed custom sparse ledger implementation of transaction application algorithms in favor of unifying under `Transaction_logic` functor.
* Added support for deriving sparse ledger subsets from existing sparse ledgers.
* This involved giving sparse ledger some notion of the "next index" to allocate new accounts at, though this "next index" does not automatically increment as you interact with the sparse ledger.
* Added new batching operations to standard ledger interface; implemented operations in various ledger modules.
* Batched ledger mask interactions when extracting subsets of ledgers into sparse ledgers.
* Update sparse ledger application logic to pre-load all accounts modified by txns in the staged ledger diff into a sparse ledger upfront (this allows us to batch the …
> Optimize staged ledger diff application

- src/lib/best_tip_prover/best_tip_prover.ml
- src/lib/ledger_catchup/normal_catchup.ml
- src/lib/ledger_catchup/super_catchup.ml
- src/lib/mina_transition/external_transition.ml
- src/lib/mina_transition/external_transition_intf.ml
- src/lib/transition_router/initial_validator.ml
This PR skips the proof verification check for the genesis block when it's sent by another peer. Currently, nodes will send a dummy proof with the genesis block, and will then be banned by the receiving node.
Note that the node(s) that produce the first block will generate a genesis proof, which they will recursively verify in that block. It is never otherwise useful to generate and distribute a genesis proof, so we avoid doing so by removing this check.
This should fix some flakiness that we've been seeing in integration tests due to nodes banning eachother.
Checklist:
> Don't require a valid proof for genesis blocks

- src/app/libp2p_helper/src/libp2p_helper/pubsub_msg.go
Problem: a logging line was accidentally left unremoved after debugging process
Solution: remove the line
Checklist:
> Remove unnecessary verbose logging

- src/lib/mina_base/control.ml
- src/lib/mina_base/party.ml
- src/lib/mina_base/snapp_generators.ml
When generating the `other_parties` field of a `Parties.t`, generate the `Party.t` in pairs.  Choose an authorization, then the first `Party.t` updates the permissions consistent with that authorization, while still using `Signature` as its own authorization. The second `Party.t` then uses the chosen authorization.
This strategy allows testing of all possible authorizations, not just `Signature`, and also tests permissions updating.
The existing staged ledger Snapps unit test passes with this change.
> Split generated other parties in two

- src/app/libp2p_helper/src/codanet.go
- src/app/libp2p_helper/src/libp2p_helper/stream_msg_test.go
- src/lib/best_tip_prover/best_tip_prover.ml
- src/lib/ledger_catchup/normal_catchup.ml
- src/lib/ledger_catchup/super_catchup.ml
- src/lib/mina_transition/external_transition.ml
- src/lib/mina_transition/external_transition_intf.ml
- src/lib/transition_router/initial_validator.ml
Problem: banning behavior is not enacted for
future connections.
Solution: implement a test that makes previous code fail,
set gaiting config properly.
* Added a unit test that tests that no stream can be opened after ban is enacted.
Checklist:
> Fix SetGatingConfig RPC endpoint

- src/app/rosetta/lib/network.ml
- src/app/rosetta/lib/rosetta.ml
As required by
https://www.rosetta-api.org/docs/node_deployment.html#offline-mode-endpoints
* Pass in the thunked graphql URI into the network route (like construction) to support offline endpoints
* Make those two endpoints offline: /options remains relatively similar, /list lists all networks (which it should have done anyway)
* Hit these endpoints with the relevant test-curl scripts and they still work even on a rosetta instance that is in "offline mode"
> Rosetta offline network endpoints

- src/app/libp2p_helper/Makefile
- src/app/libp2p_helper/src/libp2p_helper/config_msg.go
- src/app/libp2p_helper/src/libp2p_helper/message_id_test.go
- src/app/libp2p_helper/src/libp2p_helper/multinode_test.go
- src/app/libp2p_helper/src/libp2p_helper/upcall_test.go
- src/app/libp2p_helper/src/libp2p_helper/util_test.go
Problem: default message id function used for pubsub is
based on public key of the message creator and some nonce.
Hence, it is possible for the same message to appear twice on the same
topic provided it was sent by different creators.
This might be problematic for some types of gossip, especially in the
light of forecoming softfork introducing a versioning mechanism for
pubsub topics.
Solution: use hash-based message id function.
* a new unit test is added, which would be failing without the other changes in the PR
Checklist:
> Use hash-based message id function

- graphql_schema.json
- src/app/archive/archive_lib/processor.ml
- src/app/replayer/replayer.ml
- src/app/snapp_test_transaction/dune
- src/app/snapp_test_transaction/snapp_test_transaction.ml
- src/lib/mina_base/parties.ml
- src/lib/mina_base/party.ml
- src/lib/mina_base/snapp_generators.ml
- src/lib/mina_base/transaction_logic.ml
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/transaction_snark/test/ring_sig.ml
- src/lib/transaction_snark/transaction_snark.ml
- src/lib/verifier/common.ml
For the GraphQL input produced by `snapps_test_transaction`, instead of filling in fields in a string, traverse JSON derived from a `Parties.t` to build a string.
The Snapps GraphQL input is a Javascript object almost isomorphic to JSON; the main difference is that field names are not double-quoted. But the GraphQL schema has some differences  -- `Keep` is encoded as a `null`, for example. Those elements of special-handling are called out in comments.
In `Party.Body.t`, change `pk` to `public_key`, so that the GraphQL name is the more-informative `publicKey`. This change will trigger the version linter, of course.
In the GraphQL schema, camelCase `balance_change` and `use_full_commitment`, to avoid special handling for the underscored names.
Tested by running the app with sample inputs, …
> Snapps GraphQL, derive from JSON

- src/lib/block_time/block_time.ml
- src/lib/block_time/block_time.mli
- src/lib/block_time/dune
- src/lib/consensus/constants.ml
- src/lib/consensus/global_slot.ml
- src/lib/consensus/global_slot.mli
- src/lib/consensus/global_sub_window.ml
- src/lib/consensus/global_sub_window.mli
- src/lib/consensus/intf.ml
- src/lib/consensus/proof_of_stake.ml
- src/lib/consensus/slot.ml
- src/lib/consensus/vrf/consensus_vrf.ml
- src/lib/currency/currency.ml
- src/lib/currency/currency.mli
- src/lib/currency/intf.ml
- src/lib/mina_base/account.ml
- src/lib/mina_base/fee_excess.ml
- src/lib/mina_base/party.ml
- src/lib/mina_base/payment_payload.ml
- src/lib/mina_base/protocol_constants_checked.ml
- src/lib/mina_base/signed_command_payload.ml
- src/lib/mina_base/snapp_command.ml
- src/lib/mina_base/snapp_predicate.ml
- src/lib/mina_base/token_id.ml
- src/lib/mina_base/transaction_union_payload.ml
- src/lib/mina_numbers/intf.ml
- src/lib/mina_numbers/nat.ml
- src/lib/mina_state/blockchain_state.ml
- src/lib/mina_state/blockchain_state.mli
- src/lib/transaction_snark/transaction_snark.ml
This PR uses the efficient range-check that comes from `Scalar_challenge.to_field` to implement arithmetic operations in currencly.ml
> use range check for currency and numbers

- graphql_schema.json
- src/lib/mina_graphql/mina_graphql.ml
Add an endpoint `mockSnapp` to GraphQL. The input and output types are the same as for `sendSnapp`.
Instead of adding a `Parties.t` to the transaction pool, like `sendSnapp` does, the new endpoint applies the `Parties.t` to a copy of the ledger associated with the best tip. The `state_view` is the protocol state associated with the best tip's parent breadcrumb.
Closes #9972.
There is no CLI command added to run mock Snapps here, but there's not yet a CLI command to run Snapps in earnest. If that's added, a similar command could be added to run mock Snapps in the same way as this GraphQL endpoint.
> mockSnapp GraphQL endpoint

- src/lib/staged_ledger/staged_ledger.ml
Add a couple more staged ledger unit tests with Snapp commands, by mimicking existing user command tests.
Create `gen_snapps_below_capacity` by factoring out code common with `gen_snapps_at_capacity`.
Do we need to create more of these tests? Do the remaining existing tests exercise anything where a Snapp vs. a user command might make a difference? It already takes several minutes to run the tests in this module, so we should only add tests if truly warranted.
Closes #9247 (maybe).
> More staged ledger Snapp unit tests

- dockerfiles/Dockerfile-mina-daemon
the integration tests were hitting a "container not found" bug, i found out later that this is because there is no longer python in the mina daemon containers, for mysterious reasons.
it looks like one of our packages that we install in the dockerfile of the mina daemon image used to depend on python but no longer does so python no longer appears in our container.  this is fixed by just manually installing it
> Debug intgtest

- dockerfiles/Dockerfile-mina-daemon
- src/app/snapp_test_transaction/snapp_test_transaction.ml
In `snapp_test_transaction`, we were printing a dummy record for the `Full` predicate.
The code to transform JSON to a string had most of the machinery to handle this case (camelCasing field names, etc.). The only additional mechanism needed was to add an "account" field to the record for this case.
Tested by QC-generating an instance of `Snapp_predicate.Account.t`, using `jsobj_of_json` to convert it to a string, and inspecting the printed result.
Closes #10008.
> Valid output for Full predicate

- src/lib/mina_base/parties_logic.ml
- src/lib/mina_base/transaction_logic.ml
- src/lib/transaction_snark/transaction_snark.ml
This PR replaces the effects for `get_account`, `set_account` and `check_inclusion` with equivalent functions passed to the functor.
This PR is part of the work for #10033.
Checklist:
> Move get_account, set_account, and check_inclusion out of Parties_logic effects

- src/lib/mina_base/parties_logic.ml
- src/lib/mina_base/transaction_logic.ml
- src/lib/transaction_snark/transaction_snark.ml
This PR moves the `Global_slot.t` type and its accessors out of the `Parties_logic.Eff` effects module, accepting it as a functor argument instead.
This is part of the work for #10033.
Checklist:
> Move `Global_slot` type and accessors out of effects

- src/lib/mina_base/parties_logic.ml
- src/lib/mina_base/transaction_logic.ml
- src/lib/transaction_snark/transaction_snark.ml
This PR introduces an `add_check` function, which we can use to verify checks in both the transaction logic and the snark logic using the `Parties_logic` functor. This function is designed so that it can collect the informative `Failure_reason.t` error for the transaction logic, while ensuring that the failure cases are identical between the two versions. This is then used to replace the `Check_fee_excess` effect
This is part of the work for #10033.
Checklist:
> Add `add_check` helper function to Parties_logic, use it for `Check_fee_excess`

- src/lib/mina_base/parties_logic.ml
- src/lib/mina_base/party.ml
- src/lib/mina_base/transaction_logic.ml
- src/lib/transaction_snark/transaction_snark.ml
This PR moves transaction verification from the catch-all `Check_auth_and_update_account` effect into a dedicated function, and calls this function from `Parties_logic`.
This is part of the work for #10033.
Checklist:
> Check transaction verification in Parties_logic

- src/lib/mina_base/parties_logic.ml
- src/lib/mina_base/party.ml
- src/lib/mina_base/transaction_logic.ml
- src/lib/transaction_snark/transaction_snark.ml
This PR deduplicates the logic for the replay checks in the transaction logic / transaction snark, moving them to a single implementation in `Parties_logic`.
This is part of #10033
Checklist:
> Move replay checks into `Parties_logic`

- buildkite/src/Jobs/Test/TestnetIntegrationTests.dhall
- graphql_schema.json
- src/app/test_executive/snapps_test.ml
- src/app/test_executive/test_executive.ml
- src/lib/block_time/block_time.ml
- src/lib/integration_test_cloud_engine/dune
- src/lib/integration_test_cloud_engine/kubernetes_network.ml
- src/lib/integration_test_cloud_engine/mina_automation.ml
- src/lib/integration_test_lib/intf.ml
- src/lib/integration_test_lib/wait_condition.ml
- src/lib/mina_base/account.ml
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/pickles/pickles.ml
- src/lib/snarky_log/snarky_log.ml
Create an integration test for snapps.
Strategy:
- generate a `Parties.t` using QC generators
- integration test ledgers have a `snapp` field
- substitute fee payer key from an account in the integration test ledger
- substitute a dummy signature for the fee payer, so the snapp is expected to fail
Other changes:
- add a new GraphQL endpoint `sendTestSnapp` that accepts a `scalar`, so programatically, we can just send a `Yojson.Basic.t`; the extant `sendSnapp` requires an OCaml object ; the upcoming derivers may make this extra endpoint unnecessary
- the length check on token symbols updated to use nonstrict inequality
- define `snapp_to_be_included_in_frontier` for future tests
- disable `profile_constraints` in `Pickles` due to an exception opening a log file; added a close for that …
> Snapp integration test

- src/lib/mina_transition/external_transition.ml
- src/lib/transition_handler/processor.ml
- src/lib/truth/truth.ml
- src/lib/truth/truth.mli
This PR does a small amount of housekeeping, removing some unreachable branches from the code.
This is done by expanding `Truth.True.t` and `Truth.False.t` to have incompatible type declarations. Previously, the typechecker was unable to determine that `Truth.True.t` and `Truth.False.t` were not equal, because they were abstract.
Indeed, it was correct to do so, because both were aliased to `unit`, and thus the true types of the constructors were:
```ocaml
type (_, _) t =
| True : 'witness -> ('witness, unit) t
| False : ('witness, unit) t
```
Naturally, any code consuming a `_ t` must by construction have type `('witness, unit) Truth.t`, and thus must be matched against both.
By giving the types distinct, non-abstract declarations, the typechecker can infer that the types could never be …
> Make Truth.t cases exhaustive

- src/lib/currency/currency.ml
- src/lib/currency/currency.mli
- src/lib/currency/intf.ml
This PR
* adds some functions to the non-circuit currency interface to allow it to be used interchangeably with the circuit version (for snapps logic unification)
* exposes some new functions that are needed in the unified snapps logic.
Checklist:
> Add non-circuit equivalent functions to Currency, add missing functions

- src/lib/mina_base/parties_logic.ml
- src/lib/mina_base/party.ml
- src/lib/mina_base/transaction_logic.ml
- src/lib/transaction_snark/transaction_snark.ml
This PR replaces the separate implementations of timing updates between the snark logic and the transaction logic with a unified implementation in parties logic.
This is part of the work towards #10033.
Checklist:
> Move timing update into combined transaction logic

- src/lib/mina_graphql/mina_graphql.ml
When importing keys, the user-provided password was clobbered by a step before the actual import.
Fixed by copying the key and using the copy at the import step.
Tested by importing, locking, and unlocking a key. The unlock step had failed before making the changes in this PR.
Closes #9720.
> Copy password when importing key

- src/lib/crypto/kimchi_bindings/stubs/binding_generation/src/main.rs
- src/lib/crypto/kimchi_bindings/stubs/src/lib.rs
- src/lib/crypto/kimchi_bindings/stubs/src/oracles.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_index.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_proof.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_verifier_index.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_index.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_proof.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_verifier_index.rs
- src/lib/crypto/kimchi_bindings/stubs/src/plonk_verifier_index.rs
- src/lib/pickles/side_loaded_verification_key.ml
- src/lib/pickles/verification_key.ml
This is PR #10176 rebased back onto `develop`. Hopefully this (and a re-merge-forward) will fix the weird non-conflict merge conflict in #10163.
> Remove linearization on verification key

- .gitignore
- scripts/generate-local-network-ledger.py
- scripts/run_local_network.sh
This PR revives the `run_local_network.sh` script for local testing purposes. This script stopped working a while ago when we removed some of the old automation genesis ledger generation code. I brought back the subset of that code that is needed for this script while re-implementing the other logic in the shell script itself. I also did some simple quality of life refactoring of the script to make it (hopefully) easier to maintain.
I've tested it locally with some other changes I'm working on to verify that it is working. The `-t` flag is currently broken, but I will try and address that in a followup.
> Revive run local network script

- src/lib/pickles/side_loaded_verification_key.ml
Use base58 format when representing verification key in yojson
Checklist:
* Closes #0000
> fix verification key json format in parties

- src/lib/verifier/prod.ml
My thread timing work showed that the daemon was spending a very large amount of time making 4x calls to collect GC stats every time we submit snark work to the verifier. This PR removes this logging. This change has been tested on mainnet and I've confirmed it has a significant reduction in async scheduler contention.
> Remove verifier memory stats logging

- src/lib/downloader/downloader.ml
In my thread timing work. I found that a particular async loop in the super catchup downloader was starving other jobs in the scheduler. The loop checks for a condition, waits for a signals related to events that may make that condition true, and then restarts. The issue was that the signals it was using to wait before checking again were based on pipes having messages. This is buggy because a pipe having a message is not the same as an event firing on the reader side of the message, which is what the code was assuming.
I added a `Bvar.t` to the module to use as a proper event signaling primitive. This took the CPU usage of catchup down from 90%+ all the time (even when no catchup jobs were queued) to nearly 0% while no catchup jobs are running. Catchup still takes nearly 100% CPU during …
> Fix Super Catchup Async Loop

- src/lib/crypto/kimchi_backend/common/dlog_plonk_based_keypair.ml
- src/lib/crypto/kimchi_backend/common/plonk_constraint_system.ml
- src/lib/pickles/fix_domains.ml
This PR removes an unused type parameter. This is a no-op.
Checklist:
> [Trivial] Remove unused type parameter in kimchi constraint system

- dockerfiles/scripts/daemon-entrypoint.sh
Cherry picks a change from #10243 to fix the daemon entrypoint logic and allow for these environment variables to remain unset and unused.
> lk86/fix-entrypoint Make entrypoint backward compatible

- src/lib/pickles_types/hlist.ml
- src/lib/pickles_types/hlist.mli
- src/lib/pickles_types/hlist0.ml
- src/lib/pickles_types/poly_types.ml
Add considerable documentation to `Hlist` in the `pickles` lib, in a new MLI file.
Also renames `Fst` and `Snd` to `Arg1` and `Arg2`, and removes `Hlist_1`, which is redundant with `Hlist0.H1_1`.
> [pickles] Document Hlist

- src/lib/rosetta_lib/user_command_info.ml
* An empty string within status fields also mean the same as omitting it
* Tried hitting the preprocess endpoint with a `"status": ""`
> Rosetta: Accepts empty string status

- graphql_schema.json
- src/app/snapp_test_transaction/lib/commands.ml
- src/app/snapp_test_transaction/snapp_test_transaction.ml
- src/lib/mina_graphql/mina_graphql.ml
Added permissions, verification key, sequence state
Checklist:
* Closes #0000
> Add more fields to accounts in graphql

- src/lib/crypto/kimchi_backend/common/dlog_plonk_based_keypair.ml
- src/lib/crypto/kimchi_backend/common/plonk_constraint_system.ml
- src/lib/crypto/kimchi_bindings/stubs/Cargo.toml
- src/lib/crypto/kimchi_bindings/stubs/binding_generation/src/main.rs
- src/lib/crypto/kimchi_bindings/stubs/kimchi.ml
- src/lib/crypto/kimchi_bindings/stubs/src/gate_vector.rs
- src/lib/pickles/fix_domains.ml
To obtain a hash for a circuit, we currently hash the intermediate snarky representation (before it gets compiled to the actual gates). I don't think this is a good idea as different IR might lead to the same compiled circuit (gates). Thus, different circuits could have the same hash.
This PR proposes to compute the digest from the compiled circuit directly, which is implemented on the Rust side much more easily using serde's Serialization: https://github.com/o1-labs/proof-systems/pull/321
**Note: this change means that you can't obtain a digest from an unfinalized circuit, which sounds to me like it's a feature. But I need to see if things need fixing because of that.**
> [crypto][kimchi] compute circuit digest via compiled gates (instead of IR)

- src/app/test_executive/chain_reliability_test.ml
This PR increases the 'soft timeout' for the short bootstrap phase of the chain reliability test to 3 slots, up from the default 2 slots.
This test frequently fails due to the soft timeout (anecdotally, it seems to do so far more often than it succeeds), but eventually succeeds with enough retries. However, retrying is manual and wastes both developer time and CI resources. Increasing this timeout should decrease the number of flakes that we see.
Checklist:
> Increase 'short bootstrap' timeout for chain reliability test

- src/lib/integers_stubs_js/runtime.js
* This PR fixes broken uin64 comparison in integer_stubs_js, as documented and explained here: https://github.com/o1-labs/integers_stubs_js/issues/1
* The strategy is to change the uint64 from being the same as int64, to be a wrapper around int64
* Verified manually that this fixes uint64 comparison
Checklist:
* Closes #0000
> Fix uint64 comparing in JS

- src/lib/crypto/kimchi_bindings/stubs/Cargo.toml
This PR fixes `dune utop`, by passing the `no-caml-startup` flag to `ocaml-rs`. This disables the symbol in `ocaml-rs` that previously caused a link error.
Checklist:
> Fix `dune utop` in `mina_base` and friends

- .gitattributes
This is a redux of #10135; this uses `**` to match recursively in directories. Previously it was only matching at the toplevel directory level with `*`, and thus did not work as intended.
Checklist:
> Use ** blob specifier for linguist-vendored

- src/app/test_executive/snapps_constructed.ml
This PR increases the timeouts in the snapps integration test from 2 to 3, to reduce the number of flakes. This is similar to #10286.
Checklist:
> Increase timeout in snapps integration test

- src/lib/ledger_catchup/super_catchup.ml
i think Marlin_plonk_bindings_pasta_fp got changed to State_body_hash but some changes based on what was used before got merged before having a chance to rebase, causing a compile time bug
> replace Marlin_plonk_bindings_pasta_fp with State_body_hash in super catchup

- src/app/test_executive/snapps_constructed.ml
- src/lib/integration_test_lib/wait_condition.ml
- src/lib/ledger_catchup/super_catchup.ml
- src/lib/pickles_base/side_loaded_verification_key.ml
Change the `snapp-constr` integration test to update all fields (save `timing`, which cannot be updated for an existing account).
To perform the update, the permissions need to be changed, so there's a snapp transaction to update the permissions.
Remove the snapp transaction that updated only the application state, since this new test subsumes that one.
Increase the wait soft timeout to 3 slots, and the hard timeout to 6 slots.
Part of #10067.
Closes #10282: The `wrap_bk` field of verification keys, which is an option, is ignored for `Pickles.Side_loaded_verification_key.compare` and `equal`, since that field can be apparently be derived from the `wrap_index` field. If that field is `None`, it can become `Some` after `Bin_prot` deserialization, so an equality check that respects that …
> Snapp integration test, update all possible fields

- src/app/archive/archive_lib/processor.ml
Add a log in `add_block_aux` when a block is added.
That will help to know how long it takes to add a block, or fail to do so.
> Add log when adding block

- src/lib/currency/currency.ml
This PR fixes the inconsistent values returned by the `*_flagged` functions when there is an overflow. In particular, when there is an underflow, the value outside of the snark would wrap around back to `2^64-1`, but the value inside of the snark would wrap around to the smaller value `Field.size-1 % 2^64`.
The code now explicitly adjusts the values before applying the range check, asserting that the adjusted value is in range rather than allowing it to be arbitrarily decided.
Checklist:
> Ensure that `Currency.{add,sub}_flagged` etc. is consistent in and out of snark

- automation/terraform/modules/kubernetes/testnet/locals.tf
- automation/terraform/modules/o1-integration/locals.tf
- helm/snark-worker/templates/snark-coordinator.yaml
- helm/snark-worker/templates/snark-worker.yaml
- src/app/test_executive/README.md
- src/app/test_executive/archive_node_test.ml
- src/app/test_executive/chain_reliability_test.ml
- src/app/test_executive/gossip_consistency.ml
- src/app/test_executive/payments_test.ml
- src/app/test_executive/peers_reliability_test.ml
- src/app/test_executive/test_executive.ml
- src/lib/integration_test_cloud_engine/kubernetes_network.ml
- src/lib/integration_test_cloud_engine/mina_automation.ml
- src/lib/integration_test_cloud_engine/stack_driver_log_engine.ml
- src/lib/integration_test_lib/intf.ml
- src/lib/integration_test_lib/wait_condition.ml
Integration test framework supports snark workers by design. This functionality wasn't used and well-maintained. This PR brings it up-to-date, read to be used.
Checklist:
> Fix snark worker support in integration tests

- src/lib/mina_base/parties_logic.ml
- src/lib/mina_base/party.ml
- src/lib/mina_base/snapp_account.ml
- src/lib/mina_base/snapp_basic.ml
- src/lib/mina_base/transaction_logic.ml
- src/lib/transaction_snark/transaction_snark.ml
This PR loads the `Side_loaded_verification_key.t` contained in the updates of a `Party.t` for transaction snark logic, and uses it to update the sparse ledger. This is intended as a fix for the recent QANet crash.
Checklist:
> Load `Side_loaded_verification_key.t` from `Party.t` in snark logic

- src/lib/integration_test_lib/wait_condition.ml
This PR increases the soft-timeout used when waiting for some number of blocks to be produced. To quote the new comment in the code:
```ocaml
(* We add 1 here to make sure that we see the entirety of at least 2*n
full slots, since slot time may be misaligned with wait times after
non-block-related waits.
This ensures that low numbers of blocks (e.g. 1 or 2) have a
reasonable probability of success, reducing flakiness of the tests.
*)
```
Checklist:
> Bump soft_timeout of `Wait_condition.blocks_to_be_produced` in integration tests

- src/lib/mina_base/parties_logic.ml
- src/lib/mina_base/transaction_logic.ml
- src/lib/transaction_snark/transaction_snark.ml
This PR tweaks the handling of fee-payer failures to return a descriptive error string based on the `Transaction_status.Failure.t`, if available. This allows the fix in #10318 and the (unmerged) follow-up fix in #10329 to work correctly while still making information about the failure available.
Checklist:
> Improve error message printing when there is an available failure_status

- src/lib/mina_base/transaction_logic.ml
This PR removes the erroneous failure handling in `Transaction_logic`. This approach corrects the existing behaviour and the extension in #10323.
Checklist:
> Fixup error/failure handling in Transaction_logic

- src/app/test_executive/snapps_constructed.ml
- src/lib/integration_test_cloud_engine/kubernetes_network.ml
- src/lib/integration_test_lib/intf.ml
- src/lib/transaction_snark/transaction_snark.ml
For the "snapps-constructed" integration test, add steps to verify that
- the changed permissions have taken effect
- the other field updates are visible 
For the permissions, we check that the new permissions equal the requested permissions.
For the other updates, we construct a `Party.Update.t` from the ledger account, as if that update had been applied. We compare that against the update that was applied. For any field where the requested update had `Keep`, we allow any value in the constructed update. (We could do more checking by verifying that such a value is the same as before the applied update, but that's less of a concern.) For any field where the requested update has `Set`, we require the same value in the constructed update.
Part of #10067.
> Verify permissions changes, updates in snapp test

- buildkite/src/Command/Base.dhall
- buildkite/src/Command/DockerLogin/Type.dhall
40 new Buildkite CI nodes have been deployed to Kubernetes. These have better security configurations and eventually will replace the currently running buildkite nodes.
This PR is to test the cutover process and changes the pod assignments used in CI to point to the new nodes (these are the edits in Base.dhall).
An additional edit is made in Type.dhall to change the Dockerhub account used for pushing packages to Dockerhub. It is currently manually assign to point to an old account that does not exist in the new Buildkite nodes.
The new nodes have been assigned into the Buildkite "smokescreen" pipeline to confirm all credentials are valid and authorized.
The new nodes have also been installed into the existing Mina build pipeline …
> Changed CI pod sizing to generic

- buildkite/src/Command/Base.dhall
- buildkite/src/Command/DockerLogin/Type.dhall
This update has already merged into 'compatible' ([original PR link](https://github.com/MinaProtocol/mina/pull/10338)). This PR is requested to apply the update to the 'develop' branch.
40 new Buildkite CI nodes have been deployed to Kubernetes. These have better security configurations and eventually will replace the currently running buildkite nodes.
This PR is to test the cutover process and changes the pod assignments used in CI to point to the new nodes (these are the edits in Base.dhall).
An additional edit is made in Type.dhall to change the Dockerhub account used for pushing packages to Dockerhub. It is currently manually assign to point to an old account that does not exist in the new Buildkite nodes.
The new nodes have …
> This update cuts over from old to new buildk nodes

- src/lib/mina_graphql/dune
- src/lib/node_error_service/dune
The addition of `src/lib/node_error_service` is conflicting with the setting of `(implicit_transitive_deps false)`,
this PR should fix this by adding direct dependencies explicitly to `src/lib/node_error_service/dune`.
> add direct dependencies to src/lib/node_error_service/dune

- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_index.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_index.rs
This PR adds `USED` and `MAX` parameters to the OCaml allocations used for proof indexes. This information allows the OCaml GC to better reason about how many of these allocations should normally co-exist in memory, and to attempt to free accordingly when this limit is reached.
For example, when running the `transaction_snark` unit tests, several proof systems are initialised in order to run the various different tests. Without this PR, the proof index for each remains in memory, as OCaml considers the data used by the allocation to be negligible (a single pointer of size 1 machine word). In practice, this means that the memory usage of the test would otherwise continue to increase as we add more tests.
The `MAX` parameter is chosen to be `12=2*6` to match the 2 (step and wrap) keys for …
> Allow OCaml GC to reason about the size of rust memory held for snark proof indexes

- buildkite/scripts/unit-test.sh
This PR tweaks the unit test runner script, so that it will retry the tests once within the same buildkite run. This allows any flaking test to be re-run without a rebuild, and without running the other tests that have already succeeded.
If the test still fails, either due to a badly configured/misbehaving buildkite node or a genuine error in the PR, then the normal buildkite retry process will still take effect.
Checklist:
> Retry failed unit tests using dune cache

- src/lib/mina_base/party.ml
- src/lib/mina_graphql/mina_graphql.ml
This PR replaces the polymorphic `Party.Update.Poly.t` with monomorphic versions at both of its specialisations. This decreases the amount of code dedicated to type definitions, as well as providing better error messages for type errors.
Checklist:
> Monomorphise `Party.Update.t`

- src/nonconsensus/currency/dune
- src/nonconsensus/data_hash_lib/dune
- src/nonconsensus/dune-project
- src/nonconsensus/fields_derivers_snapps/dune
- src/nonconsensus/hash_prefix_states/dune
- src/nonconsensus/hex/dune
- src/nonconsensus/mina_base/dune
- src/nonconsensus/mina_base/util/dune
- src/nonconsensus/mina_numbers/dune
- src/nonconsensus/non_zero_curve_point/dune
- src/nonconsensus/quickcheck_lib/dune
- src/nonconsensus/random_oracle/dune
- src/nonconsensus/rosetta_coding/dune
- src/nonconsensus/rosetta_lib/dune
- src/nonconsensus/rosetta_lib/test/dune
- src/nonconsensus/sgn/dune
- src/nonconsensus/signature_lib/dune
- src/nonconsensus/snark_bits/dune
- src/nonconsensus/snark_params/dune
- src/nonconsensus/string_sign/dune
- src/nonconsensus/unsigned_extended/dune
This PR sets the `(implicit_transitive_deps false)` option in `src/nonconsensus` and adds the needed direct dependencies to the dune files.
```
- make build
- make client_sdk
- make client_sdk_test_sigs_nonconsensus
- make rosetta_lib_encodings_nonconsensus
- dune build src/nonconsensus --profile=nonconsensus_mainnet
```
- The CI failure seems unrelated
Checklist:
> set (implicit_transitive_dependencies false) in src/nonconsensus

- src/app/client_sdk/poseidon_hash.ml
- src/lib/crypto/kimchi_backend/pasta/pallas_based_plonk.ml
- src/lib/crypto/kimchi_backend/pasta/vesta_based_plonk.ml
- src/lib/crypto/kimchi_bindings/stubs/src/linearization.rs
- src/lib/crypto/kimchi_bindings/stubs/src/oracles.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_index.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_proof.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_verifier_index.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_poseidon.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_index.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_proof.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_verifier_index.rs
- src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_poseidon.rs
- src/lib/pickles/step_main_inputs.ml
- src/lib/pickles/tick_field_sponge.ml
- src/lib/pickles/tock_field_sponge.ml
- src/lib/pickles/wrap_main_inputs.ml
- src/lib/random_oracle/random_oracle.ml
* Update to latest version
* Update names to be more obvious and match proof-systems names
* pasta_{p,q} -> Legacy: pasta_{p,q}_legacy
* pasta_{q,q}_3 -> Kimchi: pasta_{p,q}_kimchi
* Need to update submodules once proof-systems and snarky PRs are approved
* Closes #10446
> Update to new arithmetic sponge params

- src/lib/network_pool/indexed_pool.ml
Remove two unit tests that purported to check the integrity of indexed pool maps from `Fee_rate.t` to sets of user commands.
The tests inserted commands into the indexed pool, then used `Map.data` to pull out the commands, and checked whether they were in fee/weight order. But `Map.data` provides no ordering guarantees, so these tests succeeded by sheer coincidence. The number of commands given is small (4); increasing the number broke the tests, because the insertion step failed.
> Remove bogus fee/weight unit tests

- src/lib/network_pool/indexed_pool.ml
- src/lib/network_pool/transaction_pool.ml
In the `Transaction_pool` unit tests, add another assertion on the pool, that `transactions` provides commands ordered in decreasing fee/weight order, subject to nonce ordering for fee payers.
In `Indexed_pool.get_highest_fee`, use specific `Set` and `Map` modules, rather than the `Stdlib` ones.
Note: `get_highest_fee` seems to use `min_elt_exn` as a tie-breaker, when multiple commands have the same fee/weight. Adding that tie-breaker to the sort breaks the assertion for some tests. Omitting the tie-breaker allows all tests to succeed. I don't understand why adding the tie-breaker breaks tests, but I think omitting it is OK, because the assertion nonetheless establishes that transactions are ordered by decreasing fee/weight.
Part of #10067.
> Assert fee/weight ordering of transactions

- buildkite/src/Jobs/Test/TestnetIntegrationTests.dhall
- src/app/test_executive/delegation_test.ml
- src/app/test_executive/delegation_test.mli
- src/app/test_executive/gossip_consistency.ml
- src/app/test_executive/payments_test.ml
- src/app/test_executive/test_executive.ml
- src/lib/integration_test_cloud_engine/kubernetes_network.ml
- src/lib/integration_test_lib/intf.ml
- src/lib/integration_test_lib/wait_condition.ml
write a new delegation test in support of https://github.com/MinaProtocol/mina/issues/10319
> Delegation test

- src/app/test_executive/snapps.ml
- src/lib/transaction_snark/transaction_snark.ml
In the `snapp` integration test, create a new account with a timing. Verify that the timing appears in the ledger account.
Closes #10359.
> Add snapp with timing to integration test

- src/app/missing_blocks_auditor/missing_blocks_auditor.ml
- src/app/missing_blocks_auditor/sql.ml
In `missing_blocks_auditor`, add an estimate of the gap size when there's a missing block.
The gap estimate is the height of the unparented block, minus the maximum block height less than that height, minus 1.
It's an estimate, because we don't know there's a chain between the unparented block and that block of maximum height.
Tested with a gappy archive db.
> Add gap estimate to missing block log

- graphql_schema.json
- src/lib/currency/dune
- src/lib/currency/signed_poly.ml
- src/lib/fields_derivers/dune
- src/lib/fields_derivers/fields_derivers.ml
- src/lib/fields_derivers_graphql/dune
- src/lib/fields_derivers_graphql/fields_derivers_graphql.ml
- src/lib/fields_derivers_json/dune
- src/lib/fields_derivers_json/fields_derivers_json.ml
- src/lib/fields_derivers_snapps/dune
- src/lib/fields_derivers_snapps/fields_derivers_snapps.ml
- src/lib/mina_base/control.ml
- src/lib/mina_base/dune
- src/lib/mina_base/epoch_data.ml
- src/lib/mina_base/epoch_ledger.ml
- src/lib/mina_base/parties.ml
- src/lib/mina_base/party.ml
- src/lib/mina_base/permissions.ml
- src/lib/mina_base/snapp_predicate.ml
- src/lib/with_hash/dune
- src/lib/with_hash/with_hash.ml
- src/nonconsensus/currency/dune
- src/nonconsensus/fields_derivers_snapps/dune
- src/nonconsensus/mina_base/dune
* Uses `ppx_annot` to pull annotations into derivers
* Looks for `name` and `doc` on both top-level and fields and `depr` (deprecated) and `skip` on fields
* Note: I thought about sticking the relevant derived annots into the "god object" that the rest of the derivers rely on, but it's syntactically awkward to inject it in. The approach taken here to change the DSL seems the least syntactically messy.
* This PR doesn't address: Using `skip` nor actually thoroughly renaming/documenting the structures. These will be addressed in follow-up PRs
* Unit tests in the annots parsers
* Adjust fields_derivers_* tests to use annotations
* Full e2e party derivers tests pass
Closes #10485
> Initial integration of ppx_annot with fields-derivers

- buildkite/src/Jobs/Test/TestnetIntegrationTests.dhall
- src/app/test_executive/test_executive.ml
- src/app/test_executive/zkapps.ml
- src/lib/integration_test_cloud_engine/kubernetes_network.ml
- src/lib/integration_test_lib/intf.ml
Add valid and invalid transfers from a timed account in the `zkapps` (né `snapps`) integration test.
The invalid transfer has a transaction amount that would push the account balance below the minimum ("locked") balance.
Currently, the transaction status does not indicate a failure in this case. Instead, we check that the account balance has been reduced only by the fee, and not the transaction amount. This test should be updated when the transaction status can indicate a failure for this case.
Closes #10362.
> Valid, invalid transfers from timed account

- buildkite/src/Jobs/Test/TestnetIntegrationTests.dhall
- src/app/test_executive/test_common.ml
- src/app/test_executive/test_executive.ml
- src/app/test_executive/zkapps.ml
- src/app/test_executive/zkapps_timing.ml
Send a zkapp that attempts to update the timing of a timed account; verify that the timing has not changed.
Split the zkapps integration tests into ordinary and timed tests.
Closes #10358.
> Invalid timing update

- src/lib/integration_test_cloud_engine/mina_automation.ml
This reverts commit f6359e079965c9cc153ede72d217ae3ff779d84b, which attempts to retrieve the archive schema from a non-extant branch.
> Revert "use this branch for sql schemas in mina_automation.ml"

- src/lib/block_producer/dune
- src/lib/blockchain_snark/dune
- src/lib/bootstrap_controller/dune
- src/lib/consensus/dune
- src/lib/consensus/intf.ml
- src/lib/ledger_proof/dune
- src/lib/mina_base/mina_base.ml
- src/lib/mina_ledger/ledger.mli
- src/lib/mina_state/dune
- src/lib/mina_state/local_state.ml
- src/lib/staged_ledger/dune
- src/lib/transaction_logic/dune
- src/lib/transaction_logic/mina_transaction_logic.ml
- src/lib/transaction_logic/parties_logic.ml
- src/lib/transaction_snark/transaction_snark.ml
- src/lib/transaction_snark/transaction_snark.mli
- src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
- src/lib/transaction_witness/dune
- src/lib/transaction_witness/transaction_witness.ml
- src/lib/transaction_witness/transaction_witness.mli
- src/lib/transition_frontier/frontier_base/dune
- src/lib/transition_frontier/persistent_frontier/dune
This PR moves `Parties_logic` out of `Mina_base` and into `Mina_transaction_logic`.
This is some housekeeping prework to allow https://github.com/MinaProtocol/mina/issues/10520 to be implemented without injecting a large number of new modules into Mina_base.
Checklist:
> Move Parties_logic out of Mina_base

- src/app/archive/archive_lib/extensional.ml
- src/app/archive/archive_lib/test.ml
- src/app/cli/src/init/client.ml
- src/app/client_sdk/client_sdk.ml
- src/app/client_sdk/dune
- src/app/extract_blocks/dune
- src/app/extract_blocks/extract_blocks.ml
- src/app/rosetta/lib/construction.ml
- src/lib/block_producer/block_producer.ml
- src/lib/block_producer/dune
- src/lib/mina_base/mina_base.ml
- src/lib/mina_graphql/dune
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/mina_lib/dune
- src/lib/mina_lib/mina_lib.ml
- src/lib/network_pool/dune
- src/lib/network_pool/indexed_pool.ml
- src/lib/network_pool/indexed_pool.mli
- src/lib/network_pool/intf.ml
- src/lib/network_pool/transaction_pool.ml
- src/lib/transaction/dune
- src/lib/transaction/transaction_hash.ml
- src/lib/transaction/transaction_hash.mli
- src/lib/transaction_inclusion_status/dune
- src/lib/transaction_inclusion_status/transaction_inclusion_status.ml
- src/nonconsensus/mina_base/mina_base_nonconsensus.ml
- src/nonconsensus/mina_base/transaction_hash.ml
- src/nonconsensus/mina_transaction_nonconsensus.opam
- src/nonconsensus/transaction/dune
- src/nonconsensus/transaction/transaction_hash.ml
This PR moves `Transaction_hash` out of `Mina_base` and into `Mina_transaction`.
This is some housekeeping prework to allow https://github.com/MinaProtocol/mina/issues/10520 to be implemented without injecting a large number of new modules into Mina_base.
Checklist:
> Move Transaction_hash out of Mina_base

- buildkite/src/Constants/ContainerImages.dhall
- dockerfiles/stages/3-toolchain
* Use [tweag's](https://github.com/tweag/deb-s3) version of deb-s3, which do not lock during .deb upload. An attempt to avoid long locks during CI builds. The lock is still held during retrieval/update of the package lists, but released before uploading the packages themselves.
* Use the rebuilt debian Docker images for Buildkite
* Tested multiple parallel jobs on a test S3 bucket with firefox .deb.
* See also the CI for this PR
> [deb-s3] Do not lock while uploading (unique) .deb files

- buildkite/scripts/test-snarkyjs-bindings.sh
- buildkite/src/Jobs/Test/SnarkyJSTest.dhall
This PR adds a test harness for the SnarkyJS bindings on CI. This is intended to support the effort to merge the bindings into `develop` via #10267. The script is currently a no-op, whose contents will be filled by @mitschabaude in that PR.
Checklist:
> Add test harness for SnarkyJS bindings

- src/lib/integration_test_cloud_engine/mina_automation.ml
per paul and deepthi's request, have the intg test framework use own branch hash in the raw github url instead of hardcoding to develop
> splice the git hash into the url

- src/lib/pickles/pairing_main.ml
- src/lib/pickles/per_proof_witness.ml
- src/lib/pickles/step_main.ml
This PR breaks out some small refactors to pickles coming from the documentation effort. This
* moves the logic for verifying a proof into a `verify_one` function, out of the nasty multi-hlist map
* removes an unused parameter and the logic for constructing its input
* remove an unused function
The commits are self-contained; it may be easier to review them individually.
Checklist:
> [Easy] Small pickles refactors

- Makefile
Use `:=` instead of `=` to avoid running the command multiple times
> [cleanup] Small Makefile optimization

- buildkite/scripts/run-test-executive.sh
- buildkite/src/Command/Base.dhall
- buildkite/src/Jobs/Test/TestnetIntegrationTests.dhall
- graphql_schema.json
- src/app/test_executive/block_production_priority.ml
- src/app/test_executive/block_production_priority.mli
- src/app/test_executive/chain_reliability_test.ml
- src/app/test_executive/peers_reliability_test.ml
- src/app/test_executive/test_executive.ml
- src/lib/block_producer/block_producer.ml
- src/lib/daemon_rpcs/types.ml
- src/lib/integration_test_cloud_engine/kubernetes_network.ml
- src/lib/integration_test_cloud_engine/mina_automation.ml
- src/lib/integration_test_lib/intf.ml
- src/lib/integration_test_lib/test_config.ml
- src/lib/integration_test_lib/test_error.ml
- src/lib/mina_base/gen/gen.ml
- src/lib/mina_commands/mina_commands.ml
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/mina_metrics/mina_metrics.mli
- src/lib/mina_metrics/no_metrics/mina_metrics.ml
- src/lib/mina_metrics/prometheus_metrics/mina_metrics.ml
- src/lib/network_pool/transaction_pool.ml
On some block producing nodes blocks are created with a significant lag, apparently due to being overwhelmed with transactions.
Problem: there is no good way to reproduce the condition in test environment
Solution: implement an integration test that tests this condition with a high probability.
The test implemented fails on current `develop` with ~25% probability. By default this test is turned off, provide `RUN_OPT_TESTS=1` environment variable via Buildkite custom build to see the test executed.
The test launches:
* 4 transaction producers, each generating a transaction each 2 seconds
* a block producer
* a snark coordinator with 25 snark workers
Result of the test is expected to be:
1. Median of transaction count in blocks is ~125 (first few empty blocks are ignored)
2. All blocks are …
> Test block production under load

- src/lib/integration_test_cloud_engine/kubernetes_network.ml
We currently spend 30s waiting before sending each GraphQL request in integration tests. This PR removes that wait, since it should almost never be necessary.
For tests where we send a lot of transactions, this can add up quickly. For example, in the snapps integration test, we spend at least 6 minutes in these 30s sleeps!
Checklist:
> Integration tests: don't wait 30s before every GraphQL test

- src/lib/pickles/limb_vector/constant.ml
- src/lib/transaction_logic/mina_transaction_logic.ml
This PR fixes two integer overflows that were previously occuring in the JS build. One of them had caused a bug in serializing Pickles proofs to strings in JS.
The problem in both cases was that OCaml's `int` was assumed to hold more than 32 bits, or be equivalent to `int64`. This is not the case in JS, where `int64` is implemented correctly but `int` has only 32 bits.
The solution is to avoid `int` for large integers, and use `int64` instead. For creating large integers, `Int64.of_string` can be used instead of `Int64.of_int`.
> Fix JS integer overflows

- buildkite/src/Command/Base.dhall
- buildkite/src/Command/Size.dhall
- buildkite/src/Command/TestExecutive.dhall
- buildkite/src/Jobs/Test/TestnetIntegrationTests.dhall
* This change is to update the buildkite resources used for integration tests. Buildkite allocates pods based on the tag the job has assigned. In this case there are now 40 pods added that use the tag `integration` which are dedicated to integration tests. This specific allocation is intended to place a cap on the number of integration tests that can run in parallel, and avoid exhausting the cloud resources on the back-end. 
* Because this item is changing a setting within the CI pipeline, the ci-build-me tag is added to this PR. If these tests complete successfully, it would validate that the update does not cause issue. 
Checklist: …
> updated integration test node sizing

- src/lib/fields_derivers_graphql/fields_derivers_graphql.ml
- src/lib/fields_derivers_json/fields_derivers_json.ml
- src/lib/fields_derivers_snapps/fields_derivers_snapps.ml
- src/lib/mina_base/permissions.mli
This PR allows the use of the `skip` fields deriver without an associated `skip` annotation. This fixes the compilation error in #10189.
Checklist:
> Add skip marker to fields_derivers

- src/app/replayer/replayer.ml
- src/app/replayer/sql.ml
Apply changes in #10312 in `develop`, so we can get a clean merge.
We had to make some changes to that PR, based on changes in `develop` not done in `compatible`.
Once this PR is merged, that PR should have a clean merge.
> Filter command ids in SQL (for develop)

- src/app/delegation_backend/README.md
- src/app/delegation_backend/src/constants.go
- src/app/delegation_backend/src/data.go
- src/app/delegation_backend/src/delegation_backend/main.go
- src/app/delegation_backend/src/delegation_backend_migrate/main.go
- src/app/delegation_backend/src/delegation_backend_migrate/main_test.go
- src/app/delegation_backend/src/go.mod
- src/app/delegation_backend/src/go.sum
- src/app/delegation_backend/src/sheets.go
- src/app/delegation_backend/src/submit.go
- src/app/delegation_backend/src/submit_test.go
Upon request from OnTab, a few changes were introduced to Delegation backend. A different directory structure was agreed upon to ease implementation of Ontab's software.
* User submissions are saved by path `<submited_date>/<submitted_time>-<submitter>.json`
* Fields `created_at`, `submitter` and `block_hash` are added to the JSON file
* (Minor) encoding of `submitter` field is fixed to match Mina's standard Pk encoding (prefix was added)
* Migration tool to migrate existing submissions to the new format was implemented
* Existing tests were tested accordingly
Checklist:
> Delegation backend: new storage structure

- src/lib/block_producer/block_producer.ml
- src/lib/bootstrap_controller/bootstrap_controller.ml
- src/lib/bootstrap_controller/bootstrap_controller.mli
- src/lib/mina_intf/transition_frontier_components_intf.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_transition/external_transition.ml
- src/lib/mina_transition/external_transition_intf.ml
- src/lib/transition_frontier/frontier_base/breadcrumb.ml
- src/lib/transition_frontier_controller/transition_frontier_controller.ml
- src/lib/transition_handler/processor.ml
- src/lib/transition_handler/validator.ml
- src/lib/transition_router/initial_validator.ml
- src/lib/transition_router/transition_router.ml
Problem: mutable field validation_callback is misplaced in the external
transition type.
Solution: remove the field out of the block type.
Checklist:
* Closes #0000
> Remove validation_callback out of block type

- src/app/test_executive/delegation_test.ml
- src/app/test_executive/gossip_consistency.ml
- src/app/test_executive/payments_test.ml
- src/app/test_executive/test_executive.ml
- src/lib/integration_test_cloud_engine/kubernetes_network.ml
- src/lib/integration_test_lib/event_type.ml
- src/lib/integration_test_lib/event_type.mli
- src/lib/integration_test_lib/intf.ml
- src/lib/integration_test_lib/network_state.ml
- src/lib/integration_test_lib/wait_condition.ml
- src/lib/transition_frontier/transition_frontier.ml
this PR addresses both #10721 and #10699
after merging, intg tests should be a lot less flaky in general, as well as gossip-consistency itself being less flaky
> breadcrumb wait for not working

- src/app/libp2p_helper/src/libp2p_helper/config_msg_test.go
(Preparation for Nix packaging)
libp2p_helper: allow disabling MDNS test. The Nix Sandbox doesn't
allow MDNS, so the test can't pass. Allow disabling it.
> [nix prep] libp2p: allow disabling MDNS test

- src/lib/mina_ledger/ledger.mli
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/transaction_logic/mina_transaction_logic.ml
Add `previous_empty_accounts` to `Parties_applied.t`.
To get those accounts, in `apply_parties_unchecked_aux`, look at accounts not in ledger, see if they've been added to the ledger after the application.
That list of account ids should be non-empty only if the failure table is empty. There's no assertion for that invariant, but it could be added.
Closes #10734.
> Add `previous_empty_accounts` to `Parties_applied.t`

- buildkite/src/Constants/ContainerImages.dhall
- dockerfiles/stages/3-toolchain
Companion PR for #10719. No difference
> Deb s3 atomic upload compatible

- buildkite/src/Constants/ContainerImages.dhall
- dockerfiles/stages/1-build-deps
- src/dune.flags.inc
- src/external/ocaml-rocksdb/dune
- src/external/ocaml-rocksdb/rocks_linker_flags_gen.ml
Companion PR for #10762, making the same changes on `develop`.
It uses different toolchain images than compatible, regenerated from develop + changes.
Should be merged first.
> Use LLD as a linker / develop

- buildkite/src/Constants/ContainerImages.dhall
- dockerfiles/stages/1-build-deps
- src/dune.flags.inc
- src/external/ocaml-rocksdb/dune
- src/external/ocaml-rocksdb/rocks_linker_flags_gen.ml
Analysis in https://github.com/MinaProtocol/mina/issues/10503 has shown that switching from the GNU linker to LLVM's lld improves build times, especially when building incrementally (where linking is a significant bottleneck).
This PR makes that change by:
- adding `lld` to the toolchain
- passing a global compiler flag for the internal code, to use `lld`
- adapting `ocaml-rocksdb` so that it correctly links with `lld`, which is more strict than the GNU linker with respect to duplicate symbols
Closes #10761
> Use LLD as a linker

- src/dune.flags.inc
- src/external/ocaml-rocksdb/dune
- src/external/ocaml-rocksdb/rocks_linker_flags_gen.ml
https://github.com/MinaProtocol/mina/pull/10768 seems to have broken some local builds where `lld` is not available or badly packaged. This reverts changes in the flags while devising a solution that supports both environments.
> Temporarily revert LLD linking

- src/lib/uptime_service/uptime_service.ml
Try to make the uptime service more reliable and efficient.
Changes:
- Move `Monitor.try_with` inside `run_attempt`, to allow retries upon connection errors, which can be due to transient network conditions
- Don't retry sending a block on certain 4xx HTTP status codes, which can't be recovered from
- Retry pause reduced to 4 seconds (still an eternity in Internet time)
- Always send a block w/ SNARK work at the beginning of each 5-slot widow, even if producing a block in the window
> Uptime service, retry on connection errors when sending block

- src/lib/transition_frontier/full_frontier/full_frontier.ml
Fixes bug reported in #10717.
The transition frontier would crash if a diff was applied to it which adds a breadcrumb that already exists in the frontier. If 2 block producing nodes are running with the same keypair, and generate the same staged ledger diff when producing their block, then this issue can happen. The fix is to just log a message instead of crashing.
> Fix duplicate block bug

- buildkite/src/Command/Docker/Type.dhall
- buildkite/src/Lib/Cmds.dhall
Nix sandboxing, which increases reproducibility and allows more
isolated builds, requires a privileged docker container. Add a way to
pass `--privileged` to docker running on buildkite builders.
> [nix prep] buildkite: allow passing --privileged to docker

- src/app/zkapp_test_transaction/lib/commands.ml
- src/app/zkapp_test_transaction/zkapp_test_transaction.ml
In `zkapp_test_transaction` app, distinguish uses of `zkapp-account-key` flag documentation. All the instances had mentioned a new account, even if the transaction is meant to work on an existing account.
Removed that flag from `Flags`, because unused.
Change many uses of `snapps` to `zkapps`. A few remain, because of requirements in other libraries.
> Distinguish docs in "zkapp-account-key" uses

- README-dev.md
- src/app/test_executive/README.md
- src/app/test_executive/payments_test.ml
- src/lib/integration_test_cloud_engine/mina_automation.ml
- src/lib/integration_test_lib/intf.ml
- src/lib/integration_test_lib/test_config.ml
- src/lib/integration_test_lib/wait_condition.ml
- src/lib/runtime_config/runtime_config.ml
explicitly as many of the runtime_configs, so that they can be tweaked by tests
> Explicit genesis configs

- buildkite/src/Command/Base.dhall
- buildkite/src/Command/DockerLogin/Type.dhall
- buildkite/src/Command/Size.dhall
- buildkite/src/Command/TestExecutive.dhall
- buildkite/src/Jobs/Test/TestnetIntegrationTests.dhall
This PR changes the pod size used for CI tests within buildkite. It is a change that is already active within `Develop` and `Compatible`, but had not yet been ported into Master. CI test in master are currently broken while this update is not in place. This PR is to manually apply the update to Master outside of the normal merges for `Compatible` and `Develop` branches. 
Linked to the original PRs which this is based on: 
Merge into `Compatible`: https://github.com/MinaProtocol/mina/pull/10632 and https://github.com/MinaProtocol/mina/pull/10338
Merge into `Develop`: https://github.com/MinaProtocol/mina/pull/10344
Since this item related directly to CI tests, the `ci-build-me` tag is applied to this PR to run integration tests and …
> hotfix to repair ci tests for PRs into master

- src/app/archive/archive_lib/test.ml
Allow configuring postgres connstring in archive_lib tests. Useful for testing with `pg_tmp` instead of a system-wide postgres.
> archive_lib tests: allow configuring postgres

- src/app/test_executive/payments_test.ml
- src/lib/integration_test_cloud_engine/mina_automation.ml
- src/lib/integration_test_lib/test_config.ml
> make slot time configurable in intg tests

- src/lib/structured_log_events/structured_log_events.ml
When a structured log parser failed, there was a failure raised indicating that the parser was missing for the particular structured log id.
Instead, fail with a message indicating that the parser was found, but failed when applied to particular arguments.
This may help debug the issues we're seeing in CI for the structured log `Snark_work_received`. Constructing that log manually succeeds, so there may be something about the particular arguments fed to the parser.
> Informative structured log error message

- src/app/rosetta/README.md
- src/app/rosetta/lib/account.ml
When a transaction is received in the same block that a transaction is sent, the nonce returned by the account-balance lookup returns an older nonce. There was also another edge case that hasn't occurred yet where nonces could be off-by-one, this is also now fixed.
Ultimately this is caused by the archive processor writing balance entries with a nonce that doesn't take into account new nonces that may have been written _within_ the current block.
* The query-pending SQL is broken apart into separate balance and nonce components. The nonce component takes the latest 255 entries and picks the maximum nonce to workaround this bug. This will cover the case where this block sends many transactions but receives one and breaks the rules.
* Additionally, in certain fallback …
> Hotfix: Fixes nonce edge case with Rosetta

- src/lib/mina_base/signed_command_memo.ml
The recent merge from `master` removed some `to_string` / `of_string` functions that were used by new code introduced in `compatible`. This PR fixes the compilation errors by using the explicit `to_base58_check` and `of_base58_check_exn` versions.
> Fixup compilation after merge from master

- graphql_schema.json
- src/app/archive/archive_lib/processor.ml
- src/app/archive/archive_lib/test.ml
- src/app/archive/zkapp_tables.sql
- src/app/replayer/replayer.ml
- src/lib/mina_base/party.ml
- src/lib/mina_base/zkapp_precondition.ml
- src/lib/mina_generators/parties_generators.ml
- src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
- src/lib/transaction_snark/test/party_preconditions/party_preconditions.ml
- src/lib/zkapps_examples/zkapps_examples.ml
This PR removes the `public_key` field from account precondition.
This field adds no value -- the `public_key` is already explicitly exposed in the `Party.t` -- so we lose nothing by removing it. This also decreases the size of transactions and reduces the amount of hashing that we have to do inside and out of the circuit.
Checklist:
> Remove unnecessary `public_key` field from account precondition

- src/app/archive/archive_lib/.ocamlformat
- src/app/archive/archive_lib/ast.ml
- src/app/archive/archive_lib/chain_status.ml
- src/app/archive/archive_lib/diff.ml
- src/app/archive/archive_lib/extensional.ml
- src/app/archive/archive_lib/graphql_query/base_types.ml
- src/app/archive/archive_lib/metrics.ml
- src/app/archive/archive_lib/processor.ml
- src/app/archive/archive_lib/test.ml
This PR adds an `.ocamlformat` file for the `archive_lib` library.
This already exists in develop, so merging back compatible can cause formatting errors.
Checklist:
> Add .ocamlformat to archive_lib

- src/app/archive/.ocamlformat
- src/app/archive/cli/archive_cli.ml
This PR adds an `.ocamlformat` file for the archive process.
This already exists in develop, so merging back compatible can cause formatting errors.
Checklist:
> [Trivial] Add ocamlformat config for archive

- genesis_ledgers/berkeley.json
bump berkeley genesis timestamp for qa-net redeployment
> bump berkeley genesis timestamp

- src/app/archive/archive_lib/test.ml
- src/lib/transaction_logic/parties_logic.ml
This PR combines several `assert_` checks used to ensure the success of a fee-payer into a single final check.
This makes the circuit more efficient, but will also make the errors far more descriptive once #10812 is merged and its labelled overflow failures are available.
Checklist:
> Move fee-payer success assertions to a single final check

- src/app/archive/archive_lib/processor.ml
- src/app/replayer/replayer.ml
- src/app/replayer/sql.ml
Update replayer to work with recent changes in archive db for zkApps.
Tested by running a local network that generated payments, and submitting zkApps via GraphQL, then running replayer on resulting archive db, which succeeded.
Note: in this experiment, there was a temporary hack in the replayer to populate the `accounts_accessed` for the genesis block. When the archive db is migrated for the hard fork, we'll need to do something similar.
Unlike the previous iterations of the replayer, balances and nonces are checked at block boundaries, instead of after every transaction. That should make the replayer significantly faster. There's also a check that the accounts created are a subset of the accounts accessed in each block.
Closes #10508.
> Replayer working with zkApps

- src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
This is intended to fix https://github.com/o1-labs/snarkyjs/issues/146
Checklist:
> Use `Field.project` instead of `Field.pack` for SnarkyJS `ofBits`

- src/app/archive/archive_lib/processor.ml
- src/app/archive/zkapp_tables.sql
- src/lib/mina_caqti/mina_caqti.ml
Update `select_cols` and `select_insert_into_cols` to generate checks in the `WHERE` clause that allow valid comparisons in the case of NULL values.
In `Block_and_zkapp_command.add_if_doesn't_exist`, add a type annotation for the `status` column. That should fix an error seen on today's QA net.
Use the new mechanism for the default token in `Token.add_if_doesn't_exist`.
Tested by running a local network. The default token was added to an empty archive db, and a zkApp was added to the `blocks_zkapp_commands` table.
> Annotate status field of blocks_zkapp_commands; allow nullable cols

- src/lib/mina_version/normal/gen.sh
- src/lib/zexe_backend/zexe_backend_common/gen_version.sh
Make the version info generation more flexible (by allowing to
override various information with env variables) and reselient (by
allowing `git` to not be present in PATH).
> [nix prep] mina_version/gen.sh: make version info generation more reselient and flexible

- src/lib/integration_test_cloud_engine/mina_automation.ml
A change to the archive node schema on develop has broken the archive node integration tests on compatible. This PR is a reduced version of the fix applied to develop, which uses the github URL for the current commit instead.
Presumably we will require an equivalent fix on `master`.
Checklist:
> [Compatible] Use the archive URL for the current branch when running tests

- src/lib/mina_base/fee_excess.ml
The `Snark_work_received` structured log in `Snark_pool_diff` was causing errors because the `work` field had JSON that could not be parsed. The parse failure was due to a reversal of the fields in the JSON for fee excesses.
I was unable to track down where that reversal occurred, perhaps it's something internal in the Yojson library. `Fee_excess.to_yojson` produces a particular field order, and the only instance I could find where we construct such JSON manually, the fields are in the right order.
The solution here is to allow `of_yojson` to accept either order of the fields, per Postel's Law.
Closes #10849. Verified that the unparseable JSON mentioned in that issue becomes parseable after this change.
> Allow reversed fields in Fee_excess JSON

- src/lib/cli_lib/commands.ml
This PR fixes #10863 by delaying printing of `Using password from environment variable` until the commands that should print it are actually run.
Checklist:
> Remove spurious "Using password from environment variable" logs at startup

- src/app/archive/archive_lib/processor.ml
Annotate the column type for `failure_reasons_ids` when adding to the table `blocks_zkapp_commands`.
This should fix the query failure recently observed in the QA net.
> Annotate column type for failure reasons

- src/app/archive/archive_lib/processor.ml
- src/app/extract_blocks/extract_blocks.ml
- src/app/rosetta/lib/block.ml
The subchain query for blocks, used when updating chain statuses, had not been updated to use the columns `min_window_density` and `total_currency`. Added those columns.
Tested by manually calling the subchain query.
This should fix the failure to decode text to int64 error seen by QA net users.
Also: changed some OCaml types to int64, to match `bigint` in the database schema. (Not really necessary; nonces are unsigned 32-bit quantities, so they won't fit in a Postgresql int, which are signed 32-bit values, so `bigint` is required. Fitting that back into OCaml only requires an `int`, which is 63-bits. But it's easier just to remember to always use int64 with `bigint`, which we often use for unsigned 64-bit values).
Closes #10892.
> Fix subchain query

- src/app/archive/archive_lib/dune
- src/app/archive/archive_lib/processor.ml
- src/app/archive/create_schema.sql
- src/app/rosetta/lib/account.ml
- src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
- src/lib/mina_base/dune
When starting the archive process, if a runtime config is provided, archive the genesis block into the `blocks` table, and the genesis accounts into the `accounts_accessed` table. The archive processor creates an internal ledger for this purpose, and its Merkle root is compared against the ledger hash stored for the genesis block.
Other changes:
- remove the `initial_balance` column of `timing_info`, it's redundant with the `accounts_accessed` balance
- remove the explicit index on `block(id)`, because it's a primary key
- log the commit info on the archive process startup
- hacks to get Rosetta to compile after these changes
Tested by running a local network, verifying that the accounts appear in `accounts_accessed`.
Closes #10912.
Closes #10904.
> Add genesis block, accounts at archive startup

- src/app/archive/archive_lib/processor.ml
- src/app/archive/create_schema.sql
- src/app/archive/drop_tables.sql
- src/app/archive/zkapp_tables.sql
- src/app/extract_blocks/extract_blocks.ml
- src/app/replayer/replayer.ml
- src/app/replayer/sql.ml
- src/app/replayer/test/archive_db.sql
In OCaml, `Fee_payer.t` refers to `Body.Fee_payer.t` and a signature. In the archive db, we don't store the signature, so the table `zkapp_fee_payer` referred to entries in `zkapp_fee_payer_body`, and contained no other information. Therefore, that table can be removed.
This change required small changes to `extract_blocks` and the `replayer`, and editing the SQL for the replayer test, which succeeded locally. Also tested that `extract_blocks` works on the data in the replayer test.
Closes #10916.
> Remove indirection table zkapp_fee_payer

- src/app/archive/archive_lib/processor.ml
- src/app/replayer/replayer.ml
- src/app/test_executive/payments_test.ml
- src/lib/integration_test_cloud_engine/kubernetes_network.ml
- src/lib/integration_test_lib/intf.ml
In the payments integration test, add an archive node, and as a final step, run the replayer on the archive db. Generate a hard error if the replayer creates `Error` or `Fatal` logs.
To run the replayer:
- use `jq` to pull out the accounts from `daemon.json` on the archive node
- create a local file as the replayer input, use `kubectl cp` to copy it back to the archive node
- run `mina-replayer` on the archive node with `--continue-on-error`
- look for offending logs in the output
In experiments, running the replayer added 10 seconds to the time for the test.
Restored code to save fee-transfers-via-coinbases in the archive processor, erroneously deleted during refactoring.
Improved some logs in the replayer.
If this approach is OK, we can add similar code to the delegation and zkApps …
> Run replayer in payments integration test

- graphql_schema.json
- src/lib/mina_graphql/mina_graphql.ml
A new graphql end point to query accounts for a token Id
```
tokenAccounts(tokenId: "wSHV2S4qX9jFsLjQo8r1BsMLH2ZRKsZx6EJd1sbozGPieEC4Jf") {
publicKey
}
```
Closes #10738
> token accounts graphql query

- src/app/cli/src/dune-project
- src/dune.flags.inc
- src/dune.linker.inc
- src/external/ocaml-rocksdb/dune
- src/external/ocaml-rocksdb/dune-project
- src/external/ocaml-rocksdb/rocks_linker_flags_gen.ml
Closes https://github.com/MinaProtocol/mina/issues/10761
We now detect if `lld` is installed via dune 3's `bin-available`stanza, and use it globally and in `ocaml-rocksdb` when available.
If not, we fall back on the default linker, BFD.
`ocaml-rocksdb` linker flags are slightly altered to be compatible with both `bfd` and `lld`, and the `dune lang` version is raised in places that make use of the linker detection.
> Detect LLD linker and use it if available

- src/app/cli/src/tests/coda_process.ml
- src/lib/prover/prover.ml
- src/lib/uptime_service/uptime_snark_worker.ml
- src/lib/verifier/prod.ml
- src/lib/vrf_evaluator/vrf_evaluator.ml
This updates the submodule to use the [upgraded version of `rpc_parallel`](https://github.com/MinaProtocol/rpc_parallel/pull/3).
As a result, it also fixes uses of the variant `Disconnect` that has been renamed to `Connection_closed` in the latest version.
> Use upgraded rpc_parallel

- buildkite/src/Jobs/Lint/Fast.dhall
Jobs currently named "optional" are in fact mandatory. Remove
confusing naming.
> buildkite: remove "optional" from job names

- src/lib/crypto/kimchi_bindings/js/chrome/dune
- src/lib/crypto/kimchi_bindings/js/node_js/dune
- src/lib/crypto/kimchi_bindings/stubs/dune
There is currently [an issue with `rustup`](https://github.com/rust-lang/rustup/issues/988) that can cause the
toolchain to fall into an unusable state if multiple instances are run
simultaneously. Since `cargo` may use `rustup` when
`rust-toolchain.toml` is specified, we need to make sure that there is
only 1 active `cargo` call at any time.
This adds a global `/cargo-lock` dune lock, which we can use to ensure
that only one of the offending commands can be running at a time. Most
importantly, this should remove the errors in the `dune runtest src/lib`
unit tests (e.g. [here](https://buildkite.com/o-1-labs-2/mina/builds/22966#12db5d05-1db0-479e-9b07-0d14969cd552)).
Checklist:
- Test …
> Attach `/cargo-lock` locks to all dune rules using rustup or cargo

- src/app/archive/archive_lib/load_data.ml
- src/app/archive/archive_lib/processor.ml
- src/app/archive/create_schema.sql
- src/app/archive/zkapp_tables.sql
- src/app/extract_blocks/extract_blocks.ml
- src/app/replayer/replayer.ml
- src/app/replayer/test/archive_db.sql
- src/app/rosetta/lib/account.ml
- src/app/rosetta/lib/block.ml
In the archive database, for columns representing OCaml unsigned 64-bit ints, use the Postgresql `text` type, to prevent any possibility of overflow. We retain the `bigint` type for values representing unsigned 32-bit values (slots and nonces).
Update the replayer and extract-blocks apps accordingly. For the replayer test data, ran `ALTER COLUMN .. TYPE text` on the affected columns, made sure the test succeeded locally.
Tested by running a local network, making sure payments and a zkApp were archived.
Part of #9182.
> Use text columns for OCaml unsigned 64-bit values

- .gitignore
- scripts/run_local_network.sh
* The real issue we address here is the way of `genesis_state_timestamp` updating.
* Using previous date-time formatting string `%Y-%m-%dT%H:%M:%S.%6NZ` (time-zone specifically) is not acceptable by Node at least on `macOS` (on `compatible` and `develop` branches).
* `BREAKING CHANGES` introduced, hence, targets `develop`:
* The `ledgerfolder` default path was changed in order to preserve `work-dir` after the OS restart.
* Everything else is just a usability/cosmetic improvements.
> Improvements for local network spinning up script

- buildkite/src/Jobs/Test/ArchiveNodeUnitTest.dhall
The dhall file to run the archive tests in CI was removed in #11109, because it ran `coda_archive_processor_test`, which was deleted in #11094.
But the same dhall file ran the archive unit test, which is still available.
So, restore the dhall file, modified to remove the invocation of the deleted test.
> Restore modified archive test in CI

- scripts/compare_versioned_items.py
The versioned type linter was detecting changes to at most one type in a module, because the Python script builds a dictionary where the key was a module path printed by `print_versioned_types`. That tool relies on the printer invoked by `deriving version`.
That mean that changes to `query` types in RPC modules were not being detected in CI; the dictionary entry was overwritten with an entry for the `response` type.
Modify the printer to append the type to the module path.
> Lint for multiple versioned types in module

- scripts/compare_versioned_items.py
Same as #11121, for `compatible`.
>  Lint for multiple versioned types in module (compatible)

- scripts/test.py
Remove mention of the deleted `coda-archive-processor-test` in `test.py`.
That was done in `compatible` in #11155, this is for `develop`.
> Remove archive-processor-test from test.py

- buildkite/src/Jobs/Test/ArchiveNodeUnitTest.dhall
- scripts/test.py
Remove mention of coda-archive-processor-test in `ArchiveNodeUnitTest.dhall` and `test.py`.
The actual test was removed in b26ecf36d2ba0a80fa8c11ed872c3fc560be3445.
> Remove vestiges of coda-archive-processor-test

- automation/README.md
- automation/scripts/generate-keys-and-ledger.sh
This PR is to update the README documentation used for deploying mina testnets using Google Cloud and Terraform infra-as-code. Additionally, this PR fixes a bug that prevented the `generate-keys-and-ledger.sh` script from properly outputing a testnet ledger. 
The change for the ledger gen script has been tested locally by running the `generate-key-and-ledger.sh` script locally on my machine, using a clean checkout from both develop and compatible to ensue compatibility. 
Checklist:
* Closes #11139
> Steven ledger gen fix

- dockerfiles/stages/3-toolchain
Adds dhall to Mina toolchain. Needed for https://github.com/MinaProtocol/mina/pull/10939
> Add dhall to toolchain

- src/config/features/dev.mlh
- src/config/features/mainnet.mlh
- src/config/features/public_testnet.mlh
- src/lib/mina_base/account.ml
- src/lib/staged_ledger/staged_ledger.ml
`feature_zkapps` was `true` for all configurations, so it wasn't useful.
`feature_tokens` was `false` for `public_testnet`, which meant that token transfers failed mysteriously in integration tests.
> Remove `feature_tokens`, `feature_zkapps` flags in configurations

- frontend/mina-signer/package-lock.json
- frontend/mina-signer/package.json
* I'd like to run `npm test` in CI, which depends on `jest`. This commit adds the `jest` executable to the dev dependencies of `mina-signer`
* `npm test`
Checklist:
>  frontend/mina-signer: add 'jest' dev-dependency to run tests in CI

- scripts/build-snarkyjs-node.sh
- src/dune.linker.inc
- src/lib/crypto/kimchi_bindings/dune
- src/lib/crypto/kimchi_bindings/js/chrome/dune
- src/lib/crypto/kimchi_bindings/js/node_js/dune
- src/lib/crypto/kimchi_bindings/stubs/Cargo.toml
- src/lib/crypto/kimchi_bindings/stubs/dune
- src/lib/crypto/kimchi_bindings/wasm/dune
- src/lib/dummy_values/gen_values/dune
- src/lib/pickles/plonk_checks/gen_scalars/dune
- src/lib/snarky_js_bindings/dune
This PR tinkers with some dune flags to allow us to compile SnarkyJS in `whole_program` mode. This reduces the size of `snarky_js_node.bc.js` to 5.1 MB.
This is the spiritual successor to #11103, but is actually in a mergeable state.
```bash
$ ls -Alh _build/default/src/lib/snarky_js_bindings/snarky_js_node.bc.js
-r--r--r-- 1 matthew matthew 5.1M Jun  3 04:48 _build/default/src/lib/snarky_js_bindings/snarky_js_node.bc.js
```
Checklist:
> Enable `whole_program` compilation for SnarkyJS

- src/app/test_executive/README.md
- src/app/test_executive/test_executive.ml
- src/lib/integration_test_cloud_engine/kubernetes_network.ml
- src/lib/integration_test_cloud_engine/mina_automation.ml
- src/lib/integration_test_lib/dsl.ml
- src/lib/integration_test_lib/intf.ml
- src/lib/integration_test_lib/malleable_error.ml
- src/lib/integration_test_lib/test_error.ml
- src/lib/integration_test_lib/util.ml
this way buildkite has more meaningful exit codes than simply just "1" for everything.  mostly in accordance to Matthew's suggestions
> Better intg test exit codes

- src/app/test_executive/dune
- src/app/test_executive/snarkyjs.ml
- src/app/test_executive/zkapps.ml
- src/app/test_executive/zkapps_timing.ml
- src/lib/integration_test_lib/dune
- src/lib/integration_test_lib/intf.ml
- src/lib/integration_test_lib/wait_condition.ml
Add token tests to the `zkApps` integration test.
These are the same as the tests in the transaction snark tokens tests, except that the token owner party has already been created. There's not a check for the post-transfer balances, which could be added.
Part of #9264.
> Token integration test

- src/external/ocaml-rocksdb/dune
- src/lib/mina_version/normal/dune
- src/lib/zexe_backend/zexe_backend_common/dune
* This PR has been split from https://github.com/MinaProtocol/mina/pull/11092 because of it's (codeowners/line) percentage.
* It adds support building these targets with `DUNE_SANDBOX=symlink`, which we want to start doing in CI in the future.
* companion `develop` PR #11174
* Built these targets with `dune b --sandbox=symlink`
Checklist:
> dune: add (sandbox none) to mina_version, ocaml-rocksdb

- src/external/ocaml-rocksdb/dune
- src/lib/mina_version/normal/dune
Merge `compatible` to `develop`.
When merging there was a conflict of `src/lib/zexe_backend/zexe_backend_common/dune` being absent in `develop` and present `compatible`, which was simply ignored.
> Merge `compatible` to `develop`

- src/lib/crypto/kimchi_backend/common/dune
Companion PR for https://github.com/MinaProtocol/mina/pull/11173
- dune: add (sandbox none) to mina_version, ocaml-rocksdb
- dune: add (sandbox none) to zexe_backend_common/version.ml
- dune: add (sandbox dune) to kimchi_backend/common/version.ml
> [develop] dune: add (sandbox none) to mina_version, ocaml-rocksdb

- src/dune.flags.inc
- src/dune.linker.inc
As per discussion with @mrmr1993:
- Lowering the `--ccopt` from `dune.flags.inc` into `dune.linker.inc` to fix the:
> Fix for `unknown flag -ccopt=ocamllsp`

- flake.lock
- flake.nix
Use a google cloud storage substituter instead of the cachix one.
> Nix: switch to google cloud storage substituter

- src/lib/crypto/kimchi_bindings/stubs/Cargo.toml
- src/lib/crypto/kimchi_bindings/stubs/dune
Fixes the building procedure on macOS by reverting commit which caused the issue.
> Fix for building procedure on macOS

- src/lib/crypto/kimchi_backend/common/bigint.ml
Add version number to the `Bin_prot` shape of the Kimchi bigint type.
That will allow detecting serialization changes by the version linter in types that include this type.
> Version Kimchi bigint type

- flake.lock
- flake.nix
- nix/checks.nix
- nix/modules/mina.nix
- nix/ocaml.nix
- src/lib/command_line_tests/command_line_tests.ml
This PR adds a NixOS module for running Mina Daemon (using systemd), and a way to generate a buildkite pipeline that builds Mina itself and some useful artifacts with Nix.
The buildkite agent to run this pipeline must have Nix >= 2.4 installed both for pipeline evaluation and the actual builds.
> Nix-based CI

- src/app/test_executive/zkapps.ml
This should force snark work to be purchased and a ledger proof to be emitted. With any luck, this will stop the zkApps integration test flakes we've been seeing.
> Triple number of transactions in zkapps test

- src/lib/crypto/kimchi_bindings/js/node_js/node_backend.js
Changes the number of workers in the node version of snarkyjs, from 3 (hard-coded) to # of CPU cores - 1
> More workers for faster proofs

- .gitmodules
- nix/overlay.nix
- src/lib/crypto/Cargo.lock
- src/lib/crypto/kimchi_bindings/js/chrome/dune
- src/lib/crypto/kimchi_bindings/js/node_js/dune
- src/lib/crypto/kimchi_bindings/stubs/dune
- src/lib/crypto/kimchi_bindings/wasm/Cargo.toml
* Change wasm-bindgen-rayon from a git submodule to a cargo git dep. Tracks the branch at o1-labs/wasm-bindgen-rayon/feature/nodejs-support. Update using `cargo generate-lockfile` or `cargo update`.
This dep is an excellent candidate for this because it's very infrequently updated.
cc @mrmr1993 
Part of #11212
> wasm-bindgen-rayon: change from submodule to cargo git dep

- scripts/update-snarkyjs-bindings.sh
- src/lib/snarky_js_bindings/dune
This syncs the snarkyjs submodule to latest `main`, which includes substantial recent changes.
Following up with the recent switch to `whole_program` compilation of the snarkyjs bindings, this also includes a tweak to the build process: Instead of minifying the bindings with JSOO, we do this step later with `esbuild`, the advantages of which are that
* a hack to get better error messages in snarkyjs is not broken by minifying
* we get unminified bindings during development, which makes debugging easier
> Update snarkyjs & tweak build

- nix/overlay.nix
Forgot a `cargoHashes`, and forgot to add `allRefs = true` to fetch certain refs.
> nix: fix error about wasm-bindgen-rayon

- README-dev.md
- flake.nix
- nix/README.md
- nix/ocaml.nix
Adds an easy way for developers to use the pure Nix build for LSP-enabled editing.
> Add nix lsp to devShell, improve nix/README.md

- src/lib/pickles/pickles.ml
- src/lib/pickles/pickles.mli
- src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
This PR reworks the conversion between SnarkyJS rules and Pickles' `Inductive_rules.t`. This now uses a GADT to hide the type variables that are unneeded.
Checklist:
> Make compilation of SnarkyJS inductive rules type-safe

- nix/impure-shell.nix
Previously the impure shell checked if there was any installed package on the current switch contained the string `mina`, which is not the right behavior (it matched the `terminal` package, for example).
Now we check if there is an existing switch named exactly `mina`.
> [nix] Correct check for impure switch

- buildkite/scripts/test-snarkyjs-bindings.sh
- src/lib/snarky_js_bindings/test_module/inductive-proofs.js
> Snarkyjs: add CI test for recursion

- src/dune.flags.inc
- src/dune.linker.inc
The changes of https://github.com/MinaProtocol/mina/pull/11259 cause a dependency cycle: `dune-linker` is now required to create `dune-linker`. If `lld` is installed, the build now just fails, and since it's removed from the main dune flags, lld would almost not be used at all anyway.
The `ccopt` was not lowered before because it is sometimes needed without the `ccopt` (for example when used in an `ocamlc_flags` stanza).
The `-ccopt=` (with nothing after =) is supposed to be accepted by `ocamlc` but if it is not on some platforms, I would rather put a no-op flag in this case (for example `-O2`, which is already passed by `ocamlc`).
@shimkiv please test if this solves your original problem
> Revert and adapt #11259

- flake.nix
We now run upload-daemon that signs and pushes paths automatically.
> Nix CI: don't sign or push (since we run a daemon that does that)

- flake.nix
For technical reasons, we've changed the binary cache private key. Therefore, the public key also has to be updated. Add the new key to `flake.nix`.
> Nix: change binary cache key

- flake.nix
We don't actually nix Mina to be checked out for building the derivations. Skip that.
> Nix CI: skip pointless checkouts

- buildkite/src/Command/Base.dhall
- buildkite/src/Command/MinaArtifact.dhall
This PR reinstates retries for all of the newly-added exit codes. This will make the integration tests perform more automatic retries, hopefully vastly improving the number of manual ones.
Checklist:
> Retry buildkite jobs at least once for all infra errors

- src/lib/crypto/kimchi_bindings/stubs/src/arkworks/pasta_fp.rs
- src/lib/crypto/kimchi_bindings/stubs/src/arkworks/pasta_fq.rs
> Improve rust error message for `Field.of_bigint`

- src/lib/snarky_js_bindings/lib/dune
- src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
- src/lib/snarky_js_bindings/tests/basic-circuit.mjs
- src/lib/snarky_js_bindings/tests/pickles-proof.mjs
* Mina companion for https://github.com/o1-labs/snarkyjs/pull/270
* Exposes hashing building blocks to give snarkyjs the power to implement the hashes it needs
* The alternative would have been exposing many custom hashing methods like `Event.hash` one-by-one. I think what we do here is much better in terms of amount of glue code, inspectability of snarkyjs, and decoupling from OCaml
> Snarkyjs hashing primitives

- flake.lock
- flake.nix
Upload nix-built containers to Google Artifact Registry using skopeo.
Also update flake-buildkite-pipeline to get some nice instructions on reproducing failures.
Closes #11125
> Nix CI: upload artifacts

- CONTRIBUTING.md
We should probably enable the "public" checkmark on https://www.notion.so/minaprotocol/Compatible-vs-Develop-branch-management-31c845b2924b4c518740eb9da4514dcc . I can do this but I'd like someone to approve.
* Update CONTRIBUTING.md to match reality a bit better
* Closes #10690
> CONTRIBUTING.md: update after rename, link to branching docs

- flake.nix
Fix for previous PR. This uploads only the compatible and develop branches, and also uploads the mina-daemon image.
Closes #11125
> nix: run docker image upload step only on main branches, add daemon

- nix/ocaml.nix
- nix/overlay.nix
- src/dune.alloc.inc
- src/dune.flags.inc
- src/lib/memory_stats/dune
- src/lib/memory_stats/memory_stats.ml
- src/lib/mina_metrics/prometheus_metrics/dune
- src/lib/mina_metrics/prometheus_metrics/mina_metrics.ml
- src/opam.export
Rip out all hard dependencies on jemalloc, and only use it as an
allocator if it is available.
Closes https://github.com/MinaProtocol/mina/issues/11491
> Make jemalloc an optional dependency

- src/lib/mina_generators/parties_generators.ml
- src/lib/transaction_snark/test/party_preconditions/party_preconditions.ml
In the parties generators, pass a set of "seen" account ids, so we can generate a receipt chain hash precondition for the first-occurrence of an account in a zkApp.
Closes #11454.
> Receipt chain hash precondition for 1st occurrence

- src/lib/mina_base/zkapp_precondition.ml
Remove V1 since there is no backwards compatibility after hard fork
Checklist:
* Closes #0000
> remove V1 of zkapp account precondition

- nix/ocaml.nix
Fixes the Nix build for aarch64-darwin, a.k.a M1 macs.
> Fix build on M1

- src/lib/mina_base/party.ml
- src/lib/mina_base/verification_key_wire.ml
- src/lib/mina_base/zkapp_account.ml
In zkApp accounts, don't serialize the hashes of verification keys. Send the unadorned key, compute the hash on receipt.
We may want to do something similar for other hashes that need to be trusted.
Update: do the same for verification keys in `Party.t`s.
Closes #11425.
> Don't serialize vk hashes

- .gitmodules
- nix/ocaml.nix
- scripts/pin-external-packages.sh
- src/opam.export
Get rid of three submodules, replacing them with opam pins.
Submodules slow down the checkout, and are often annoying when switching branches. Replace them with opam pins.
> Remove some submodules in favour of opam pins

- src/app/archive/archive_lib/diff.ml
- src/app/archive/archive_lib/processor.ml
There was code meant to archive transactions in the transaction pool, that was not called anywhere.  Remove that dead code.
Closes #11370.
> Remove code to archive pooled txns

- frontend/mina-signer/package-lock.json
- frontend/mina-signer/package.json
- frontend/mina-signer/src/MinaSigner.ts
- frontend/mina-signer/src/TSTypes.ts
- frontend/mina-signer/tests/party.test.ts
Adds a method on the MinaSigner Client class that gets the minimum fee for a parties transaction. The minimum fee for a parties transaction is defined as `0.001*numOfParties`, which is the default behavior of this new method. This method additionally adds an option for the developer to add their own fee amount per party.
Additionally, this PR adds a check for a valid fee amount when signing a parties transaction. If there is no fee available, an error is thrown. This is the same behavior as before, the only change is that we catch the error thrown from OCaml and give a more helpful message to the developer
Added unit tests to confirm the behavior
Closes #11566
> [mina-signer] - Add minimum fee for Party transactions

- src/lib/ppx_version/runtime/shapes.ml
- src/lib/ppx_version/versioned_module.ml
In `ppx_version`, instead of generating a duplicate registered shape check for every versioned type, do the check in the runtime library in the registration function. Benefit: less code to generate and compile.
Tested by building mina.exe.
> Check for dup shape in runtime library

- src/lib/consensus/proof_of_stake.ml
- src/lib/mina_networking/mina_networking.ml
- src/lib/ppx_version/versioned_module.ml
- src/lib/ppx_version/versioned_type.ml
- src/lib/ppx_version/versioned_util.ml
- src/lib/snark_worker/dune
- src/lib/snark_worker/snark_worker.ml
Add `%%versioned_rpc` to ppx_version library, for annotating versioned RPC modules.
When used with versioned RPCs:
- you no longer need to explicitly add `@@deriving bin_io, version { rpc }` to the query and response types
- there are checks that there are no duplicate versioned modules, and they're listed in decreasing order
- the shapes of the query and response types are registered
The ppx assumes that the versioned modules contain a module `T` as the first item, and that it contains the declarations for the query and response types. That's true for all the RPCs that exist in the codebase.
Applied this annotation to all the RPCs in `Mina_networking`, `Proof_of_stake`, and `Snark_worker` modules.
Verified that the shapes show up in the `internal dump-type-shapes` CLI command.
Closes …
> Add %%versioned_rpc to ppx_version

- src/lib/marlin_plonk_bindings/pasta_fp_urs/marlin_plonk_bindings_pasta_fp_urs.ml
- src/lib/marlin_plonk_bindings/pasta_fq_urs/marlin_plonk_bindings_pasta_fq_urs.ml
- src/lib/marlin_plonk_bindings/stubs/src/pasta_fp_urs.rs
- src/lib/marlin_plonk_bindings/stubs/src/pasta_fq_urs.rs
- src/lib/marlin_plonk_bindings/stubs/src/urs_utils.rs
- src/lib/pickles/opt_sponge.ml
- src/lib/pickles/pickles.ml
- src/lib/pickles/verify.ml
- src/lib/pickles/wrap_main_inputs.ml
> Lk86/merge in master 1.3.2

- src/lib/ppx_register_event/register_event.ml
The JSON parser generated by `register_event` could generate code in the wrong `Result` monad.
In one instance, the code generated was:
```
function
| `String time -> Ok (Time.Span.of_string time)
| _ -> Error "Snark_worker.Functor: Could not parse timespan"
```
The constructors `Ok` and `Error` build an instance of `Core_kernel.Result.t`, the stdlib's `result` type.
In another instance:
```
function
| `String x -> Result.Ok x
| _ -> Result.Error "src/lib/snark_worker/tester.ml.Test_type.x"
```
where  the opened module `Ppx_deriving_yojson_runtime` captures `Result`.
Because that code is used in a monadic fold over the `Core_kernel.Result` monad, we always want that monad. So generate: `let module Result = Core_kernel.Result` to avoid the capture.
Fixes an issue seen by @deepthiskumar …
> Fix Result module in register_event parser

- Makefile
- scripts/benchmarks.sh
- src/app/benchmarks/benchmarks.ml
- src/app/benchmarks/dune
- src/app/benchmarks/dune-project
Allow `make benchmarks` to work again.
Rename executable (`main.exe` isn't suggestive of purpose).
Tested by running `scripts/benchmarks.sh`.
> Fix bitrot in benchmarks

- src/app/cli/src/init/coda_run.ml
- src/app/test_executive/zkapps.ml
- src/lib/integration_test_lib/dune
- src/lib/integration_test_lib/event_type.ml
- src/lib/integration_test_lib/event_type.mli
- src/lib/mina_metrics/mina_metrics.mli
- src/lib/mina_metrics/no_metrics/mina_metrics.ml
- src/lib/mina_metrics/prometheus_metrics/mina_metrics.ml
- src/lib/snark_worker/dune
- src/lib/snark_worker/functor.ml
- src/lib/snark_worker/intf.ml
- src/lib/snark_worker/rpcs.ml
- src/lib/snark_worker/snark_worker.ml
- src/lib/snark_worker/snark_worker.mli
This PR
* adds an RPC for snark workers to inform the daemon that snark work has failed
* adds a structured log message that the daemon emits when it's informed about a snark failure
* adds a metric for the number of snark work failures seen
* consumes the structured log message in the integration test library to generate an event
* logs when snark work failures occur in the zkApps integration test
This will help us to determine whether snark work failures are the cause of failures in the zkApp integration test, as well as giving us better visibility into the reliability of snark workers and the existence of invalid work statements.
Checklist:
> Log snark work failures in the daemon, expose them in the test executive

- src/lib/pickles/pickles.ml
- src/lib/pickles/requests.ml
- src/lib/pickles/step.ml
- src/lib/pickles/verify.ml
- src/lib/pickles/wrap.ml
- src/lib/pickles/wrap_domains.ml
- src/lib/pickles/wrap_main.ml
- src/lib/pickles/wrap_verifier.ml
This PR builds upon #11616.
This PR changes the way that pickles determines the domains for side-loaded proofs, so that a proof built with a `max_proofs_verified` different from that provided to `Pickles.Side_loaded.create` can still be accepted.
For example, this is important for accepting proofs built with `max_proofs_verified: 0` (e.g. by SnarkyJS) in the transaction snark (which sets `max_proofs_verified: 2`).
Note that such a proof will pass `Pickles.verify`, but would render the wrap proof statement unsatisfiable, so this is a must-have!
Checklist:
> [Pickles] Allow side-loaded proofs to use different wrap domains

- src/lib/crypto/kimchi_bindings/wasm/src/pasta_fp_plonk_index.rs
- src/lib/crypto/kimchi_bindings/wasm/src/pasta_fq_plonk_index.rs
- src/lib/crypto/kimchi_bindings/wasm/src/plonk_proof.rs
this uses https://github.com/rustwasm/console_error_panic_hook to make Rust `panic` log messages with `console.error`, in Wasm. This makes error messages thrown in Rust much more useful. I checked that it doesn't harm prover performance
> Print Wasm errors in JS console

- src/lib/mina_base/zkapp_precondition.ml
- src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
allows SnarkyJS to pass in a custom network state and set custom network preconditions when evaluating transactions via `apply_json_transaction`
Instead of using a hard-coded network state, the state will now be maintained within SnarkyJS
accompanies https://github.com/o1-labs/snarkyjs/pull/329
> deriver for network state view, expose in snarkyjs

- flake.nix
The `shellHook` was overriden in the `devShells`, which prevented Mina from finding the libp2p helper. Fix that. Fixes https://github.com/MinaProtocol/mina/issues/11666
> Fix Nix devShells by reusing existing shellHook

- flake.nix
- nix/README.md
The nixos-container in the flake was sort of useless. Make it run the mina demo so that it can be used to sanity-check mina.
> Make the nixos-container run mina demo

- src/app/cli/src/init/transaction_snark_profiler.ml
In the transaction SNARK profiler, accounts for payments were initialized with 10,000 nanoMina, causing insufficient balance errors with larger values of `k` (log_2 of the number of payments).
Instead, initialize those accounts with the maximum `Int64.t`, which is plenty for any reasonable value of `k`. (Using `Balance.max_value` causes a "vanishing polynomial" error in the crypto code, even for small `k`).
Closes #11671.
> Larger init balances in SNARK profiler

- src/app/cli/src/cli_entrypoint/dune
- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
- src/app/cli/src/init/coda_run.ml
- src/app/cli/src/tests/coda_worker.ml
- src/lib/block_producer/block_producer.ml
- src/lib/block_producer/dune
- src/lib/mina_lib/dune
- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_lib/mina_lib.mli
- src/lib/node_error_service/dune
- src/lib/node_error_service/node_error_service.ml
- src/lib/node_error_service/node_error_service.mli
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/staged_ledger/staged_ledger.mli
- src/lib/transition_frontier/frontier_base/breadcrumb.ml
For #11272.
This PR updates the daemon to send error reports whenever it produces a block, but fails to include transactions into that block. In order to facilitate this change, the `Node_error_service` had to be refactored some to fix a circular dependency and to allow external code to generate error data based on the available space in the report. This logic is used to include as many failed transactions as we can in the error report without exceeding the maximum message size.
> Report failures to include transactions in blocks

- src/app/cli/src/cli_entrypoint/dune
- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
- src/app/cli/src/init/client.ml
- src/lib/daemon_rpcs/daemon_rpcs.ml
- src/lib/mina_commands/dune
- src/lib/mina_commands/mina_commands.ml
- src/lib/protocol_version/dune
- src/lib/protocol_version/protocol_version.ml
- src/lib/protocol_version/protocol_version.mli
Add the protocol major version to the chain id, by computing the MD5 digest of its string representation. Though the current protocol version is mutable (in theory), we use the compiled protocol version for this purpose.
Add the protocol major version to the chain id inputs shown via `advanced chain-id-inputs`. Tested that the protocol major version appears in that output by running a local network: 
```
$ mina advanced chain-id-inputs
Genesis state hash: 3NLfyLmMsATBkcR6kYYR7uyCJdgV6pZ6tY5kLSkDFxDSZY1YCkhi
Genesis_constants:
Protocol:          {"k":24,"slots_per_epoch":576,"slots_per_sub_window":2,"delta":0,"genesis_state_timestamp":"2022-08-25 16:09:55.000000Z"}
Txn pool max size: 3000
Num accounts:      250
Snark keys:
01a1b35830913fbac2036010ba1c805d
26a06100f7aecdec6b3d9cea1cfa37de …
```
> Add protocol major version to chain id

- src/lib/crypto/kimchi_bindings/stubs/dune
This PR tweaks the build of the rust bindings so that the optimisation flags can be enabled or disabled using the `RUST_TARGET_FEATURE_OPTIMISATIONS`.
Checklist:
> Make rust target-feature flag customisable with an env var

- src/lib/block_producer/block_producer.ml
- src/lib/mina_base/account.ml
- src/lib/mina_base/dune
- src/lib/mina_base/parties.ml
- src/lib/network_pool/dune
- src/lib/network_pool/indexed_pool.ml
- src/lib/network_pool/indexed_pool.mli
- src/lib/network_pool/intf.ml
- src/lib/network_pool/mocks.ml
- src/lib/network_pool/transaction_pool.ml
Closes #10879.
This PR addresses bugs in which the application of parties transactions can invalidate transactions enqueued by other fee payers within the transaction pool. To solve the bug, I took the approach to just simplify the transaction pool by having it perform revalidation on the pool whenever the frontier's best tip changes, instead of incrementally updating the pool. There is an increased performance cost to doing this, but we now have a higher degree of confidence that the implementation will correctly prune invalid transactions.
The increased performance cost comes from the fact that we now need to load account states from the ledger in order to process best tip diffs from the frontier, which was previously not necessary. However, since the accounts we request from the best …
> Revalidate transaction pool off of ledger state when updating best tip

- Makefile
This PR adds a better error message to the Makefile if the `check_opam_switch` tool is missing,
explaining that is is meant to be installed by running `opam switch import opam.export`.
> Better error message when check_opam_switch is missing

- src/config/protocol_version/current.mlh
Update protocol version to 3.0. The chain id uses the major version, 3.
Closes #11687.
> Protocol version 3.0

- src/app/test_executive/zkapps.ml
- src/lib/daemon_rpcs/daemon_rpcs.ml
- src/lib/mina_commands/mina_commands.ml
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/mina_lib/mina_lib.ml
- src/lib/mina_lib/mina_lib.mli
- src/lib/network_pool/batcher.ml
- src/lib/network_pool/indexed_pool.ml
- src/lib/network_pool/indexed_pool.mli
- src/lib/network_pool/intf.ml
- src/lib/network_pool/network_pool_base.ml
- src/lib/network_pool/pool_sink.ml
- src/lib/network_pool/snark_pool.ml
- src/lib/network_pool/snark_pool_diff.ml
- src/lib/network_pool/transaction_pool.ml
Closes #11393.
To fix this bug, I removed the asynchronous computation of indexed pool updates from the `verify` entirely. Instead, that logic is moved into `apply`, where all of the commands in a transaction pool diff are applied to the pool within a single scheduler cycle, preventing race conditions with `handle_transition_frontier_diff`. The `verify` function still runs asynchronously, but it is now only responsible for validating transactions in isolation to the pool state (validating proofs, signatures, and global restrictions such as minimum fee).
> Transaction pool parties async bug fix

- src/lib/transaction/transaction_hash.ml
Optimize parties transaction hashing by hashing the raw binable representation rather than the base58check encoded representation. TBD if we will also do the same for signed commands.
Addresses #11430
> Optimize parties transaction hashing

- src/lib/mina_generators/parties_generators.ml
- src/lib/mina_ledger/dune
- src/lib/mina_ledger/ledger.mli
- src/lib/transaction_logic/mina_transaction_logic.ml
- src/lib/transaction_logic/parties_logic.ml
In the Parties generator, there is code to update the sequence state in the same way as `Parties_logic`. The `Parties_logic` code was updated, but the generator code did not change to match it.
Factor out the sequence update logic into a new function `update_sequence_state` in `Parties_logic`. Make that function available in unchecked code from `Mina_transaction_logic` (which includes an instantiation of `Parties_logic`).  In turn, `Mina_ledger.Ledger` includes `Mina_transaction_logic`, so we can export `update_sequence_state` from it. And so the Parties generators can use that function, instead of duplicating the update logic.
That's all a bit circuitous, imports a lot of extra code into the generators, and perhaps funny to offer that functionality from `Ledger`, but perhaps OK.
Closes …
> Factor out sequence state update logic

- src/app/batch_txn_tool/dune
This PR adds the missing `mina_wire_types` dependency needed for `src/app/batch_txn_tool` to compile.
> Add missig dependency to batch_txn_tool

- nix/go.nix
The vend run has been removed accidentally from the packaging for
libp2p_helper. Add it back.
> Nix: Add back vend

- flake.nix
- src/app/libp2p_helper/src/codanet.go
- src/app/libp2p_helper/src/go.mod
- src/app/libp2p_helper/src/go.sum
- src/app/libp2p_helper/src/libp2p_helper/bitswap.go
- src/app/libp2p_helper/src/libp2p_helper/bitswap_downloader.go
- src/app/libp2p_helper/src/libp2p_helper/bitswap_downloader_test.go
- src/app/libp2p_helper/src/libp2p_helper/bitswap_test.go
Problem: when updating go-bitswap to v0.8.0, an integration was made improperly which led to TestBitswapSmoke failing.
Solution: fix the bug in integration, namely call
`bitswap.Server.NotifyNewBlocks` on every downloaded block.
Additionally, go-bitswap is bumped to v0.9.0 and a small fix is applied to flake.nix.
* `TestBitswapSmoke` is re-enabled and now passes
Checklist:
* Closes #0000
> Fix a bug and re-enable TestBitswapSmoke

- nix/libp2p_helper.json
- src/app/libp2p_helper/README.md
Fix for:
```
trace: warning: Below, you will find an error about a hash mismatch.
This is likely because you have updated go.mod and/or go.sum in libp2p_helper.
Please, locate the "got: " hash in the aforementioned error. If it's in SRI format (sha256-<...>), copy the entire hash, including the `sha256-'. Otherwise (if it's in the base32 format, like `sha256:<...>'), copy only the base32 part, without `sha256:'.
Then, run ./nix/update-libp2p-hashes.sh "<got hash here>"
error: hash mismatch in fixed-output derivation '/nix/store/sa5qm2j8ia34hp97kmvg7n7ry9f1wdc5-libp2p_helper-0.1-go-modules.drv':
specified: sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
got:    sha256-hY3Ym19Bj5qFbjXukrt/2l39yUB1/9KehM2dMoBSXVQ=
error: 1 dependencies of derivation …
```
> Fix for go.mod hash mismatch

- src/app/batch_txn_tool/batch_txn_tool.ml
- src/app/batch_txn_tool/dune
- src/app/batch_txn_tool/txn_tool_graphql.ml
This PR fixes the build of `src/app/batch_txn_tool`, which was affected by the update of the GraphQL schema.
Since `(preprocessor_deps ../../../graphql_schema.json)` was missing in the dune file, the code generated by the ppx was not invalidated and the executable seemed to build fine locally.
This PR:
- adds the preprocessor dependency on the GraphQL schema,
- uses the same graphql_ppx configuration as in the other folders,
- adapts the code, now that decoders are applied automatically.
> Update src/app/batch_txn_tool after GraphQL schema change

- src/lib/mina_base/permissions.ml
- src/lib/mina_base/permissions.mli
- src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
- exposes permissions of an account to SnarkyJS, required for https://github.com/o1-labs/snarkyjs/issues/391
- moves `auth_required_of_string`/`auth_required_from_string` under the Auth_required module as `to_string`/`of_string`
https://github.com/o1-labs/snarkyjs/pull/405
> exposes permissions to SnarkyJS

- automation/scripts/gen-keys-ledger.sh
- automation/scripts/generate-keys-and-ledger.sh
- automation/terraform/modules/google-cloud/coda-seed-node/main.tf
- automation/terraform/modules/kubernetes/testnet/helm.tf
- buildkite/scripts/unit-test.sh
- flake.nix
- helm/archive-node/Chart.yaml
- helm/archive-node/templates/archive.yaml
- helm/block-producer/Chart.yaml
- helm/block-producer/templates/block-producer.yaml
- helm/block-producer/values.yaml
- helm/seed-node/Chart.yaml
- helm/seed-node/templates/seed-node.yaml
- helm/seed-node/values.yaml
- helm/snark-worker/Chart.yaml
- helm/snark-worker/templates/snark-coordinator.yaml
- helm/snark-worker/values.yaml
- nix/modules/mina.nix
- scripts/mina-local-network/mina-local-network.sh
- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
- src/app/cli/src/init/client.ml
- src/app/cli/src/tests/coda_worker.ml
- src/lib/command_line_tests/command_line_tests.ml
- src/lib/command_line_tests/dune
- src/lib/gossip_net/libp2p.ml
:warning: After this PR is merged each node on every deployment should be configured with `--libp2p-keypair` flag :warning: 
* Rename `--discovery-keypair` to `--libp2p-keypair`
* Rename `mina advanced generate-libp2p-keypair` to `mina libp2p generate-keypair`
* existing unit and integration tests
Deployment update strategy:
* Rename `--discovery-keypair` to `--libp2p-keypair` whenever the former is used
* For each node in every deployment generate a libp2p keypair with `mina libp2p generate-keypair`
* Before generation, check if the key already exists
* The goal is to reuse the same keypair across restarts, if possible
* Pass libp2p keypair to the node with `--libp2p-keypair`
Checklist:
- Mention expected invariants, implicit …
> Specify libp2p-keypair explicitly

- graphql_schema.json
- src/app/cli/src/init/client.ml
- src/lib/cli_lib/arg_type.ml
- src/lib/codable/codable.ml
- src/lib/codable/dune
- src/lib/graphql_basic_scalars/graphql_basic_scalars.ml
- src/lib/integration_test_cloud_engine/kubernetes_network.ml
- src/lib/mina_base/signed_command.ml
- src/lib/mina_base/signed_command_intf.ml
- src/lib/mina_base/user_command.ml
- src/lib/mina_base/zkapp_command.ml
- src/lib/mina_graphql/mina_graphql.ml
- src/lib/transaction/transaction_id.ml
- src/lib/transaction/unix/graphql_scalars.ml
GraphQL returns transaction id's that were the Base58Check encoding of user commands. For zkApps especially, that's computationally expensive.
Instead, return a Base64 encoding derived from the `Bin_prot` serialization of the commands. Add a new functor to `Codable` for this purpose, which might be useful more generally.
In `Mina_graphql`, introduce a type `transaction_id` to perform the conversion, using the same pattern as the existing `transaction_hash`.
Closes #11505.
> Base64 for transaction ids

- src/lib/transaction/transaction_hash.ml
- src/lib/transaction_snark/test/account_timing/account_timing.ml
Use `Bin_prot` serialization of `Signed_command.t` to create transaction hashes, as was already done for zkApps. Factor out the common code to create transaction hashes.
Fix some spelling gaffes (hash_zkapp_command_command, oof!).
Closes #11430.
> Use serialized value for hashing signed commands

- src/app/reformat/reformat.ml
`.direnv` might contain arbitrary files, including ocaml files, used for caching. It is therefore useful to ignore it when reformatting or checking formatting.
> Add .direnv to reformat's trusted list

- src/app/zkapp_test_transaction/lib/commands.ml
It was taking more than 9 seconds to load `zkapp_test_transaction` just to get the help text. Making the verification key and prover load lazy reduces the load time to 0.1 second.
> Lazy verification key and prover in zkapp_test_transaction

- src/app/cli/src/init/client.ml
- src/graphql-ppx-config.inc
- src/lib/codable/codable.ml
- src/lib/integration_test_cloud_engine/kubernetes_network.ml
This PR configures `graphql_ppx` to automatically decode scalars of types `TransactionId` (which was recently added in #11749), as it is the case for other types. For now it is only useful for testing purpose, as we only decode this type to convert it back to a string, but in general it should be simpler and more type safe to always use the automatic decoders.
The PR also fixes an issue with the decoding function, which was incorrectly raising an exception (See [here](https://buildkite.com/o-1-labs-2/mina/builds/25104#01833d1f-99e0-47fa-9d70-c062f13b476a/64-155) for the CI error).
The reason was that the `Signed_command.of_base64` returns an `Or_error` type, but could also raise a `Bin_prot.Common.Read_error` exception. To avoid mixing both mechanisms, the exception is now captured and …
> Automatically deserialize TransactionId scalars with graphql_ppx

- src/lib/graphql_basic_scalars/graphql_basic_scalars.ml
> Fix  wrapping behaviour when parsing unsigned integers for GraphQL scalars 

- src/lib/genesis_constants/genesis_constants.ml
- src/lib/genesis_ledger_helper/lib/genesis_ledger_helper_lib.ml
- src/lib/integration_test_cloud_engine/mina_automation.ml
- src/lib/mina_base/zkapp_command.ml
- src/lib/mina_compile_config/mina_compile_config.ml
- src/lib/runtime_config/runtime_config.ml
- src/lib/transaction_snark/transaction_snark.ml
- src/lib/transaction_snark/transaction_snark.mli
Based on cost(in seconds) for proving a zkapp update with proof, a pair of updates with signatures/none and a single update with signature or none. 
The cost function was derived from the result transaction snark benchmark for zkapp transactions with different combinations of proof and signature updates
> Parties limit based on a cost function

- nix/ocaml.nix
This PR checks that the `batch_txn_tool` builds, using the nix CI.
> Build the `batch_txn_tool` binary in nix CI

- src/app/archive/archive_lib/load_data.ml
- src/app/archive/archive_lib/processor.ml
- src/lib/pickles/pickles_intf.ml
- src/lib/pickles/side_loaded_verification_key.ml
Make `to_base64`, `of_base64` available from `Pickles.Side_loaded.Verification_key`, using the `Coda.Make_base64` functor, instead of defining the code in the archive lib processor.
That will make the encoding available to other code that needs to serialize verification keys.
> Make Base64 coding available for verification keys

- src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
In `Snarky_js_bindings`, when calling `apply_zkapp_command_unchecked`, raise an exception containing the error string, in case of an error, instead of calling `Or_error.ok_exn`.
Not sure this will help a lot, because the error is derived from an exception in `Zkapp_command_logic.apply`, which might only be something like "Assertion failed". Still, that's an improvement.
> Raise with error string on application

- src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
Fix the output of `--version` to match the output of `version` and `-version`, instead of showing a weird `NO_VERSION_UTIL` message.
> Fix --version output

- flake.nix
There's already a warning in case you have forgotten to initialize submodules before running any Nix commands. However, that warning didn't trigger in some cases and wasn't colourful enough.
> Nix: Improve requireSubmodules warning

- src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
- src/lib/snarky_js_bindings/test_module/simple-zkapp-mina-signer-quick.js
- src/lib/snarky_js_bindings/test_module/simple-zkapp-mina-signer.js
- src/lib/snarky_js_bindings/test_module/simple-zkapp-mock-apply-quick.js
- src/lib/snarky_js_bindings/test_module/simple-zkapp-mock-apply.js
- src/lib/snarky_js_bindings/test_module/simple-zkapp.js
- src/lib/snarky_js_bindings/tests/basic-circuit.mjs
- src/lib/snarky_js_bindings/tests/pickles-proof.mjs
- companion to https://github.com/o1-labs/snarkyjs/pull/416
- changes methods on primitive types: `ofFields` -> `fromFields`, `ofBits` -> `fromBits`, to be compatible with the new generalized `typ` / CircuitValue in JS
- expose a more low-level variant of `exists` to JS, and define the public-facing `Circuit.witness` on the JS side instead, so that we can manage our CircuitValues in JS (the OCaml side will just witness an array of field elements)
> Support flexible circuit values

- src/app/cli/src/init/transaction_snark_profiler.ml
- src/lib/filtered_external_transition/filtered_external_transition.ml
- src/lib/mina_base/signed_command.ml
- src/lib/mina_base/signed_command_intf.ml
- src/lib/mina_base/signed_command_payload.ml
- src/lib/mina_base/signed_command_payload.mli
- src/lib/mina_base/user_command.ml
- src/lib/mina_base/zkapp_command.ml
- src/lib/mina_block/block.ml
- src/lib/mina_ledger/ledger.ml
- src/lib/network_pool/indexed_pool.ml
- src/lib/network_pool/transaction_pool.ml
- src/lib/staged_ledger/staged_ledger.ml
- src/lib/transaction/transaction.ml
- src/lib/transaction_logic/mina_transaction_logic.ml
- src/lib/transaction_snark/test/account_timing/account_timing.ml
- src/lib/transaction_snark/test/transaction_union/transaction_union.ml
- src/lib/transaction_snark/test/util.ml
- src/lib/transaction_snark/transaction_snark.ml
In `Block.account_ids_accessed`, filter out signed command receivers and zkApps account updates for failed transactions. We were getting errors looking up accounts in the staged ledger when creating precomputed blocks for account ids claimed to be accessed in blocks.
The function `accounts_accessed`, in `Signed_command`, `Zkapp_command`, `Transaction`, and `User_command`,  now takes a transaction status, to do the filtering needed. Add a new function `accounts_referenced` that does not filter out any account ids.
This may be a fix for #11861.
> Filter out account ids on failed transactions

- src/lib/transaction_logic/mina_transaction_logic.ml
- src/lib/transaction_logic/zkapp_command_logic.ml
- src/lib/transaction_snark/dune
- src/lib/transaction_snark/transaction_snark.ml
In `Zkapp_command_logic`, pass `__LOC__` to `assert_`, so we can know which assertion failed.
We trap both `Assert_failed`, generated by OCaml `assert` in unchecked code, and `Failure`, generated by Snarky, which calls `failwithf`, add the location information, then re-raise the exception.
@MartinMinkov tested this branch with a zkApp known to fail, and it gave a correct location of the assertion failure.
> Include location of assert_ failures

- src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
exposes a dummy pickles proof in base64 format to snarkyjs 
companion of https://github.com/o1-labs/snarkyjs/pull/462
> expose dummy proof to Snarkyjs

- src/lib/blockchain_snark/blockchain_snark_state.ml
- src/lib/consensus/constants.ml
- src/lib/consensus/global_slot.ml
- src/lib/consensus/proof_of_stake.ml
- src/lib/consensus/vrf/consensus_vrf.ml
- src/lib/crypto/kimchi_backend/tests.ml
- src/lib/crypto/kimchi_bindings/js/test/bindings_js_test.ml
- src/lib/mina_base/account.ml
- src/lib/mina_base/account_timing.ml
- src/lib/mina_base/epoch_ledger.ml
- src/lib/mina_base/pending_coinbase.ml
- src/lib/mina_base/protocol_constants_checked.ml
- src/lib/mina_base/staged_ledger_hash.ml
- src/lib/mina_base/transaction_union_payload.ml
- src/lib/mina_state/blockchain_state.ml
- src/lib/mina_state/protocol_state.ml
- src/lib/pickles/cache.ml
- src/lib/pickles/common.ml
- src/lib/pickles/fix_domains.ml
- src/lib/pickles/pickles.ml
- src/lib/pickles/side_loaded_verification_key.ml
- src/lib/pickles/step.ml
- src/lib/pickles/wrap.ml
- src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
- src/lib/snarky_js_bindings/tests/tests.ml
- src/lib/snarky_log/snarky_log.ml
- src/lib/transaction/transaction_union.ml
- src/lib/transaction_snark/transaction_snark.ml
- src/lib/vrf_lib/tests/integrated_test.ml
This PR is a companion to o1-labs/snarky#649, which modifies snarky to remove the `Data_spec.t` container for `Typ.t`s from the main API. This change makes the code significantly easier to follow for non-OCaml developers.
Checklist:
> Update snarky to remove `Data_spec.t` from API

- graphql_schema.json
- src/lib/mina_graphql/mina_graphql.ml
Use `tokenId` instead of `token`.
Closes #11948.
> Change argument name to tokenId

- helm/archive-node/templates/db-bootstrap.yaml
- src/lib/mina_graphql/mina_graphql.ml
In GraphQL, the `tokenAccounts` query was loading every account in the ledger, then filtering them by token id.  As reported in #11950, that could take a very long time.
Instead, obtain the account ids in the ledger, filter them by the token id, then lookup just those accounts.
Tested by applying these changes to the `release/2.0.0` branch, connecting to berkeley testnet. For the query mentioned in that issue, the time is reduced from minutes to less than a second.
Closes #11950.
> Lookup token accounts after filtering on token id

- src/lib/blockchain_snark/blockchain_snark_state.ml
- src/lib/consensus/proof_of_stake.ml
- src/lib/currency/currency.ml
- src/lib/data_hash_lib/data_hash.ml
- src/lib/mina_base/account.ml
- src/lib/mina_base/fee_excess.ml
- src/lib/mina_base/ledger_hash.ml
- src/lib/mina_base/pending_coinbase.ml
- src/lib/mina_base/transaction_union_tag.ml
- src/lib/mina_base/zkapp_call_forest.ml
- src/lib/mina_numbers/nat.ml
- src/lib/non_zero_curve_point/non_zero_curve_point.ml
- src/lib/pickles/composition_types/branch_data.ml
- src/lib/pickles/impls.ml
- src/lib/pickles/one_hot_vector/one_hot_vector.ml
- src/lib/pickles/pickles.ml
- src/lib/pickles/plonk_curve_ops.ml
- src/lib/pickles/scalar_challenge.ml
- src/lib/pickles/sponge_inputs.ml
- src/lib/pickles/wrap_verifier.ml
- src/lib/pickles_types/plonk_types.ml
- src/lib/sgn/sgn.ml
- src/lib/signature_lib/schnorr.ml
- src/lib/snark_bits/bits.ml
- src/lib/snarky_curves/snarky_curves.ml
- src/lib/transaction_snark/test/account_timing/account_timing.ml
- src/lib/transaction_snark/test/multisig_account/multisig_account.ml
- src/lib/transaction_snark/test/ring_sig.ml
- src/lib/transaction_snark/transaction_snark.ml
This PR is a companion to https://github.com/o1-labs/snarky/pull/650 https://github.com/o1-labs/snarky/pull/651 and https://github.com/o1-labs/snarky/pull/652, which make various small changes to simplify snarky, to ease the porting over to rust.
Checklist:
> Miscellaneous changes for snarky simplifications

- src/lib/base58_check/version_bytes.ml
- src/lib/mina_base/payment_payload.ml
- src/lib/mina_base/payment_payload.mli
- src/lib/mina_base/signed_command.ml
- src/lib/mina_base/signed_command_intf.ml
- src/lib/mina_base/signed_command_payload.ml
- src/lib/mina_base/signed_command_payload.mli
- src/lib/mina_base/unix/graphql_scalars.ml
- src/lib/mina_base/user_command.ml
- src/lib/mina_base/zkapp_command.ml
Add a top version tag to the `Bin_prot`-serialization of transaction ids, so that we can create transaction hashes for any extant transaction id (the hashing is not part of this PR).
Remove most of the Base58Check code for signed commands and zkApp commands, because we don't want to create any new such serializations.  
Restore `V1` of `Signed_command.Stable`, so that we can deserialize old, Base58Check transaction ids. Add `Signed_command.of_base58_check_exn_legacy` to deserialize to that type.  `Signed_command.t_legacy` is added as a name for that type. Rename `Version_bytes.user_command` to `signed_command_legacy`. Restoration required restoring a number of associated types; the `to_latest` functions are unimplemented, because there isn't need to coerce old transactions to the latest …
> Version-tag transaction ids

- src/lib/base58_check/base58_check.ml
Remove the chunking in Base58Check, which was introduced for zkApp transaction ids, which now use Base64 encoding.
An exception is raised if we try to encode a string that would have required chunking. That should never happen for the few types we still Base58Check-encode (public keys, hashes).
Close #11935.
> Remove Base58Check chunking

- flake.lock
- flake.nix
- nix/debian.nix
Build a deb package with Nix.
Caveat emptor:
> This package basically just wraps some nix store paths in the .deb format.
> It works, but has some problems.
> In particular, if there's already Nix installed on the target system, it won't work.
> Also, after this package is installed, installing Nix is likely to be wonky.
> We should fix it, e.g. by installing the nix store somewhere else, e.g. /opt/mina/nix/store, and use user namespaces to remap it to /nix/store.
We also might want to publish the package somewhere, but this can be done in the future. For now, it can be downloaded from the cache.
> Nix: build a deb package

- src/lib/mina_base/sparse_ledger_base.ml
- src/lib/transaction_logic/mina_transaction_logic.ml
For an account id not in a sparse ledger, `Sparse_ledger_base.location_of_account` returned the location of an account with the `empty` public key. Then, when calling `get`, that account was filtered out, which seems peculiar.
In `Mina_transaction_logic`, that behavior was relied upon. It seems undesirable for this code to have knowledge of the quirks of the sparse ledger.
Instead, in the sparse ledger, filter locations with the empty account, and in the transaction logic, raise an exception if there's no account corresponding to a location.
Closes #11934.
> Sparse ledger, no location for empty account

- flake.lock
- flake.nix
Allows to run the Nix CI on multiple builders
> Nix CI: Pre-fetch derivations from cache if missing

- src/lib/crypto/kimchi_bindings/stubs/src/linearization.rs
- src/lib/crypto/kimchi_bindings/stubs/src/oracles.rs
- src/lib/crypto/kimchi_bindings/wasm/Cargo.lock
- src/lib/crypto/kimchi_bindings/wasm/src/arkworks/pasta_fq.rs
- src/lib/crypto/kimchi_bindings/wasm/src/oracles.rs
- src/lib/pickles/step_verifier.ml
- src/lib/pickles/wrap_verifier.ml
This PR is the counterpart to https://github.com/o1-labs/proof-systems/pull/795, adding 'blinding' to the public input commitments in pickles, so that an all-zero public input can still be handled successfully.
Checklist:
This fixes https://github.com/MinaProtocol/mina/issues/11730
> Blind public input commitments to avoid zero commitments

- src/lib/transaction_logic/zkapp_command_logic.ml
This PR fixes the `Invalid_fee_excess` error that we've seen in zkApp transactions with empty account updates.
*
Checklist:
* Closes #0000
> don't check for fee excess for empty account update zkapp commands

- README-dev.md
- src/app/rosetta/README.md
I believe there is no instruction anywhere in the READMEs on how to run a manually compiled mina daemon and Rosetta server. I wanted to provide such an instruction, or at least a seed of it. For Mina daemon it only explains the seed mode, because that's what I figured out so far. As far as I understand, a seed deamon tries to initiate a new network of its ownand does not actively try to connect with peers. If that's inaccurate, please propose a correction.
This PR only touches READMEs.
> Add a README chapter on running the Mina in dev environment.

- src/app/rosetta/lib/block.ml
The SQL queries to the archive database contained in Rosetta API implementation have gone out of sync with the database schema, which makes it fail on virtually any request to `/block` endpoint. Errors are talking about inability to convert data types or even about unknown columns in queries. This PR aims to update the queries to conform to the current DB schema and cleans up the code meant to handle data that is no longer there.
I set up the Rosetta endpoint and queried for blocks by their height and state hashes as specified by the Rosetta API spec. These requests used to fail with SQL errors; now they return correct information on requested blocks. Tested on Berkeley testnet.
> Fix /block endpoint in Rosetta

- flake.nix
- nix/go.nix
- nix/impure-shell.nix
This PR adds the `rosetta-cli` tool to the nix development environments, the plan is to use this tool to test the implementation of the rosetta protocol.
I did not find it on nixpkgs so it is built using `buildGoModule`.
> Add `rosetta-cli` to the nix development shells.

- frontend/mina-signer/package.json
- frontend/mina-signer/tests/party.test.ts
- src/lib/mina_base/signature.ml
- src/lib/mina_base/signature_poly.ml
- src/lib/mina_block/sample_precomputed_block.ml
The Base58Check representation of signatures in `develop` differed from those in `compatible`, because version tags were removed in the serialization of the type `Signature_poly.Stable.V1.t`.
Add the tag back in using `@@@with_top_version_tag`. Use that `Bin_prot` serialization only for Base58Check.
Add a test to compare the Base58Check representation of the dummy signature with an expected result, obtained from serializing that signature in the `compatible` branch.
> Add top version tag for Base58Check signatures

- README-sandbox.md
It's essential for the developers to know how to set up such a network manually for testing purposes. Docker images and scripts are great for end-users and zkApp devs, but development of the node itself requires a more flexible setup.
It's a documentation-only PR.
> Add a README on setting up sandbox networks manually.

- src/app/cli/src/init/client.ml
- src/lib/cli_lib/commands.ml
- src/lib/mina_metrics/prometheus_metrics/mina_metrics.ml
- src/lib/snark_worker/standalone/run_snark_worker.ml
- src/lib/transaction_consistency_tests/transaction_consistency_tests.ml
- src/lib/transaction_snark/transaction_snark.ml
The `@.` indication  in  `Format` inserts a newline *and* flushes. When outputting multiple lines, you usually want to avoid flushing after every line.
Mainly, one just wants new lines inserted, e.g., with a single v-box to also benefit from Format's indenting capabilities (see https://caml.inria.fr/resources/doc/guides/format.en.html#boxes for the different kinds of boxes) and flush at the end only.
This PR refactors several occurrences of overuse of `@.`, sometimes going as far as grouping together within a single formatting string several consecutive calls to pretty-printers.
> Fix use of Format in printers

- flake.nix
- nix/README.md
This PR modifies the `#mina-with-lsp` target in 2 ways:
1. The first commit removes a call to `dune @check` that could take time
2. The second removes the dependency on `go` which looks unnecessary
This 2 changes makes the `#mina-with-lsp` like `#mina` but with the additional `ocaml-lsp-server` dependency.
Intuitively, the name indicates this is just what it should do.
> Minor updates for flake

- src/app/archive/lib/test.ml
- src/lib/mina_base/coinbase.ml
- src/lib/mina_base/coinbase_fee_transfer.ml
- src/lib/mina_base/coinbase_fee_transfer_intf.ml
- src/lib/transition_frontier/frontier_base/breadcrumb.ml
- src/lib/transition_frontier/frontier_base/breadcrumb.mli
- src/lib/transition_frontier/transition_frontier.ml
This commit patches the function triggering `warning 16` by adding an extra `()` argument.
Nothing else should change.
> Remove warning 16

- src/lib/mina_base/signed_command.ml
- src/lib/mina_base/zkapp_command.ml
Unit tests to confirm latest versions of `Signed_command` and `Zkapp_command`. Failure of these tests means there's a new version in town, and `hash_of_transaction_id` needs to accommodate that new version.
Followup to #12021.
> Tests for latest command versions

- src/lib/transaction_snark/test/zkapps_examples/calls/calls.ml
- src/lib/zkapps_examples/calls/dune
- src/lib/zkapps_examples/calls/zkapps_calls.ml
- src/lib/zkapps_examples/zkapps_examples.ml
This PR
* adds support for setting the `caller` separately from the `token_id` in the `Zkapp_examples` test API
* updates the current composability test to exercise delegate calls
Checklist:
This PR closes https://github.com/MinaProtocol/mina/issues/10825.
> Add `Zkapp_examples` tests for delegate calls

- flake.nix
- nix/ocaml.nix
- src/lib/mina_version/normal/gen.sh
- src/lib/mina_version/runtime/dune
- src/lib/mina_version/runtime/mina_version.ml
Nix store paths are input-addressed, meaning the build result will only be
reused from the existing cache if the inputs match exactly. The commit ID and
date used to be inputs to the build (as read by `mina_version.normal` during
build-time). This meant that on each commit, all the ocaml components of Mina
had to be rebuilt, regardless of the commits actually touching `src/`. This was
circumvented by a semi-hack that provided "fake" commit information, and then
that was substituted in the resulting executable in a separate derivation. That
derivation had to be rebuilt every time, but was a lot faster than rebuilding a
lot of ocaml. However, this is still somewhat slow and hacky.
Instead, introduce a `mina_version.runtime` implementation of `mina_version`,
that reads some environment …
> Add a mina_version.runtime library to make the Nix build less hacky

- src/lib/rosetta_lib/operation_types.ml
Add operation types introduced with ZKApps to Rosetta. This change is necessary for the hard fork so that Coinbase correctly displays operations created by ZKApps.
The code still compiles and passes the tests.
* Closes #11848
> Rosetta: add operation types related to zkApps.

- src/lib/pickles_base/domain.mli
- src/lib/pickles_base/domains.mli
- src/lib/pickles_base/proofs_verified.ml
- src/lib/pickles_base/proofs_verified.mli
- src/lib/pickles_base/side_loaded_verification_key.ml
- src/lib/pickles_base/side_loaded_verification_key.mli
This PR is a refactoring PR that adds interface files to all modules inside `lib/pickles_base`.
Whenever possible, this also adds some lightweight documentation inside these files.
Merge after #11858
> Add interface files to `lib/pickles_base`

- frontend/ci-build-me/src/index.js
This PR is to manually add specific external engineers to our CI trigger logic as a short term fix to enable them to manually trigger CI. This is a stop gap fix to unblock them quickly with better logic to be provided in the near future.
> Adding additional engineers to the CI trigger logic

- helm/cron_jobs/berkeley-dump-archive-cronjob.yml
- helm/cron_jobs/mainnet-dump-archive-cronjob.yaml
we don't have the cronnjob that dumps berkeley yet, so adding that
> latest gcloud version, dumping berkeley archive

- src/lib/crypto/kimchi_bindings/stubs/Cargo.lock
The `Cargo.lock` file has gone out of sync with `Cargo.toml`. This results in Nix crashing on building the environment. This PR fixes this issue.
> Update Cargo.lock in kimchi bindings.

- src/app/archive/drop_tables.sql
- src/app/archive/lib/processor.ml
- src/app/archive/zkapp_tables.sql
- src/app/replayer/replayer.ml
- src/lib/mina_base/account_update.ml
- src/lib/mina_base/control.ml
- src/lib/mina_wire_types/mina_base/mina_base_account_update.ml
In the archive db schema, drop the `authorization_kind` column from the `zkapp_account_update` table. That column represented the actual authorization (proof or signature) in the OCaml code, but the authorization kind already appears in the `zkapp_account_update_body` table.
Update the archive processor to accommodate this change.
Also: establish a type equality between `Control.Tag.t` and `Account_update.Authorization_kind.t`, by positing a an equality with the same wire type, since they represent the same notion. The constructors needed to be reordered to make that happen.  This change may trigger the version linter, but this code has not been released to mainnet, so that's OK.
Closes #12200.
> Remove redundant authorization kind
