src/app/decoder/BUILD.bazel
src/app/dhall_types/BUILD.bazel
src/app/display_public_key/BUILD.bazel
src/app/generate_keypair/BUILD.bazel

[Bazel] apps decoder, dhall_types, display_public_key,generate_keypair

---

src/app/logproc/BUILD.bazel
src/app/missing_blocks_auditor/BUILD.bazel
src/app/reformat/BUILD.bazel
src/app/replayer/BUILD.bazel
src/app/runtime_genesis_ledger/BUILD.bazel

* logproc
* missing_blocks_auditor
* reformat
* replayer
* runtime_genesis_ledger

[Bazel] apps: logproc etc.

---

src/app/rosetta/BUILD.bazel
src/app/rosetta/lib/BUILD.bazel
src/app/rosetta/ocaml-signer/BUILD.bazel
src/app/rosetta/test-agent/BUILD.bazel

src/app/rosetta app and subpkgs

[Bazel] app: rosetta

---

src/app/test_executive/BUILD.bazel

This is the last of the src/app PRs!

[Bazel] app: test_executive

---

src/lib/rocksdb/BUILD.bazel
src/lib/timeout_lib/BUILD.bazel
src/lib/transaction_snark/BUILD.bazel
src/lib/transaction_snark_scan_state/BUILD.bazel
src/lib/transaction_snark_work/BUILD.bazel
src/lib/transition_frontier_controller/BUILD.bazel
src/lib/vrf_lib/BUILD.bazel
src/lib/vrf_lib/tests/BUILD.bazel

These files were inadvertently omitted from the batch PRs yesterday.  Aside from these, the only remaining files are in #7177  and #7189

[Bazel] add build files inadvertently omitted from batch PRs

---

src/app/archive/archive_lib/processor.ml

After adding a block to the archive db, set the parent id of any block whose current parent id is `NULL`, and whose parent_hash matches the new block's state hash, to the new block's id.
Tested by running the Rosetta `start.sh` script to generate a new archive db.
Closes #7232.
Reviewer: do we have to worry about doing the same for pre-computed blocks?

Archive db, set block parent id if needed

---

src/lib/mina_base/account.ml
src/lib/mina_base/signed_command_payload.ml

This is  https://github.com/MinaProtocol/mina/pull/7004 but based on master

fix tokens

---

buildkite/src/Jobs/Release/ArchiveNodeArtifact.dhall
buildkite/src/Jobs/Release/MinaArtifact.dhall
buildkite/src/Jobs/Test/Nightly.dhall

Checklist:
Closes #0000
Closes #0000

Fix nightly dirtywhen bug in dhall

---

src/lib/merkle_mask/masking_merkle_tree.ml

Fix dangling mask error

---

automation/services/coda-network-services/make_report.py

Checklist:
Closes #0000
Closes #0000

Compatible

---

buildkite/scripts/connect-to-testnet-on-develop.sh
scripts/compare_ci_diff_types_develop.sh

Merge back to develop

---

buildkite/src/Jobs/Release/MinaToolchainArtifact.dhall

build toolchain image on xlarge agents (up from large)

---

dockerfiles/Dockerfile-toolchain

Checklist:
Closes #0000
Closes #0000

Add terraform to coda-toolchain

---

buildkite/src/Constants/ContainerImages.dhall

Checklist:
Closes #0000
Closes #0000

Update constants file for new coda toolchain

---

buildkite/src/Constants/ContainerImages.dhall

Checklist:
Closes #0000
Closes #0000

Use new pinned rust coda-toolchain

---

buildkite/src/Constants/ContainerImages.dhall
src/app/archive/archive_lib/processor.ml
src/app/cli/src/init/coda_run.ml
src/lib/error_json/error_json.ml

Checklist:
Closes #0000
Closes #0000

Fix coda-toolchain in develop

---

src/lib/network_pool/snark_pool_diff.ml

with min-fee delta. a node adds snarks only if the fee difference between the existing snark and the new snark is >= 0.5. Local snarks that are not significantly low are not added to the pool. However the work selection doesn't take this into account and distributes the same work again thinking it can undercut the one in snark pool. 
This was introduced to limit snarks per statement to mitigate an attack where nodes are made to verify invalid proofs for the same statement. #7484 would be a better solution for that
Closes #7437

remove min fee delta for snarks

---

src/lib/ledger_catchup/super_catchup.ml

[Trivial] Mownload -> Download

---

src/lib/mina_commands/mina_commands.ml
src/lib/network_pool/network_pool_base.ml

Checklist:
Closes #0000
Closes #0000

fix max observed block length

---

src/app/cli/src/init/client.ml

Tested locally with (for success) and without (for failure) an archive node running.
Checklist:

Add flags to log successful and failed blocks archive-precomputed-blocks

---

src/lib/ledger_catchup/super_catchup.ml

This PR fixes a bug @deepthiskumar found in super catchup in which passing the wrong parent hash caused us to try applying a block to the incorrect parent state, resulting in catchup looping forever. On the plus side this did demonstrate that the "re-download and retry" logic works correctly :sweat_smile:

fix for catchup issue

---

scripts/compare_pr_diff_items.py
src/lib/mina_lib/a_blank_file_to_test_ci.ml

Fix lints CI job

---

src/lib/downloader/downloader.ml

fix a bug in downloader

---

src/lib/rosetta_lib/errors.ml

Just updating some Rosetta error strings. No special testing makes sense.
Checklist:
Closes #6932

Update some Rosetta error copy

---

src/lib/consensus/proof_of_stake.ml

Update vrf threshold comment to mirror the code

---

src/lib/block_producer/block_producer.ml
src/lib/consensus/intf.ml
src/lib/consensus/proof_of_stake.ml

Make next_producer_timing calculations async

---

graphql_schema.json
src/app/rosetta/lib/construction.ml
src/lib/mina_graphql/mina_graphql.ml
src/lib/mina_lib/mina_lib.ml
src/lib/mina_lib/mina_lib.mli
src/lib/rosetta_lib/errors.ml

Add validatePayment command to GraphQL + validate signed payments in rosetta

---

src/app/test_executive/peers_test.ml
src/lib/integration_test_cloud_engine/coda_automation.ml

fixing the bug in accordance with deepthi's suggestions

fix intg timing bug

---

automation/scripts/testnet-keys.py
scripts/run_local_network.sh
src/config/dev.mlh

This is the same code as in #7556, but based on `compatible`.
See that (closed) PR for details.

Fix for local net script, redux

---

src/lib/error_json/dune
src/lib/error_json/error_json.ml

[Trivial] Add commit_id to error_to_json

---

src/lib/network_pool/indexed_pool.ml

Fix error when expired transactions are replaced in the pool

---

.mergify.yml
scripts/test.py

This makes the test officially required

Adds mina-pr-gating to required status in mergify.yml

---

src/lib/network_pool/transaction_pool.ml

This PR modifies transaction pool updates such that, when applying a diff, the pool is updated immediately before yielding to the async scheduler. This ensures that transactions aren't lost when multiple calls to `apply` are in-flight simultaneously, as laid out in #7651.
Checklist:
Closes #7651

Immediately update transaction pool when applying commands

---

automation/terraform/modules/kubernetes/testnet/helm.tf

Checklist:
Closes #0000
Closes #0000

Add static peers to initial peers for seed nodes

---

src/app/replayer/test/archive_db.sql
src/app/replayer/test/input.json
src/app/rosetta/bootstrap_balances.json
src/app/rosetta/docker-demo-start.sh
src/app/rosetta/make-runtime-genesis.sh
src/app/rosetta/run-demo.sh
src/app/rosetta/test-agent/agent.ml

Explain how you tested your changes here:
- Ran Rosetta `./start.sh`
Checklist:

Replace invalid test public key

---

src/app/libp2p_helper/src/codanet.go

This PR changes the peer exchange handler so that it doesn't add new peers if we already have enough.

hotfix: dont connect if we have enough peers

---

frontend/client_sdk/src/CodaSDK.d.ts
frontend/client_sdk/src/CodaSDK.re
frontend/client_sdk/test/Test.ts

- Exposes `validKeypair()` in client_sdk.ml to the SDK as `verifyKeypair()`
- Added a new test for `verifyKeypair()`

Client SDK: Added verifyKeypair()

---

frontend/ci-build-me/src/index.js

I was asked to add @bkase and @imeckler to the set of folks allowed to "allow for mainnet"

Adds more allowed-for-mainnet unblockers

---

src/lib/daemon_rpcs/types.ml
src/lib/mina_commands/mina_commands.ml
src/lib/mina_graphql/mina_graphql.ml
src/lib/mina_metrics/mina_metrics.ml
src/lib/transition_router/initial_validator.ml

Add max observed unvalidated block hight to metrics and status

---

src/app/archive/archive_lib/processor.ml

fix block user command query

---

src/config/fork_at_5187.mlh
src/config/testnet_postake_medium_curves.mlh

remove hard-fork logic (based on https://github.com/MinaProtocol/mina/pull/7790)

---

src/lib/trust_system/record.ml

Closes https://github.com/MinaProtocol/mina/issues/7740.

remove non-monotonic assertion

---

src/app/cli/src/init/client.ml

Create a single subcommand `ledger export` to print a staged ledger or an epoch ledger.
Replaces `ledger dump-ledger` and `ledger dump-staking-ledger`.
`coda ledger export -help`:
```
Print the specified ledger (default: staged ledger at the best tip)
coda.exe ledger export CURRENT-STAGED-LEDGER|STAKING-EPOCH-LEDGER|NEXT-EPOCH-LEDGER
=== flags ===
[--daemon-port HOST:PORT/LOCALHOST-PORT]  Client to local daemon
communication. If HOST is omitted,
then localhost is assumed to be
HOST. (examples: 8301,
154.97.53.97:8301) (default: 8301)
(alias: -daemon-port)
[--plaintext]                             Use plaintext output (default: JSON)
(alias: -plaintext)
[--state-hash STATE-HASH]                 State hash, if printing the current
staged ledger (default: state hash
for the best tip)
(alias: …
```

Consolidate ledger exports

---

src/app/missing_subchain/missing_subchain.ml
src/app/missing_subchain/sql.ml

Add an optional `--start-state-hash` flag to `missing_subchain` app. Rename the `--state-hash` flag to `--end-state-hash`.
If you provide both hashes, you get all blocks between start and end, and including the start and end.
If you provide just the end hash, you get all blocks starting with the unparented block closest to the end block, possibly the genesis block.
Tested against a Rosetta-generated archive db, with just the end hash, and with both start and end hashes, and with NULLing the parent id of a block in the middle.
Closes #7870.

Missing subchain, allow specified start block

---

src/app/cli/src/init/client.ml

Add a new command `ledger currency` that prints out the total amount of currency for each token in an exported ledger. 
The new command does not require a running daemon. Also, fixed `ledger hash` to not require a daemon.
Tested with ledgers and JSON and S-expression format.
Sample session:
```
$ coda ledger currency --ledger-file staking-epoch-ledger.json
MINA: 11616000.000065041
```
This PR is based on `feature/ledger-hash-command`, which should get merged into `develop` soon.

Print currency totals in exported ledgers

---

src/app/libp2p_helper/src/codanet.go
src/app/libp2p_helper/src/codanet_test.go
src/app/libp2p_helper/src/libp2p_helper/main.go
src/app/libp2p_helper/src/libp2p_helper/main_test.go

- implement telemetry protocol to allow for peers to query other peers for telemetry data, even if remote peer is at max connections.
`go test ./... -run TestGetTelemetry -v`
Checklist:
Closes #0000
Closes #0000

implement telemetry protocol, add test

---

genesis_ledgers/zenith.json
scripts/rebuild-deb.sh
src/config/testnet_postake_medium_curves.mlh

Add the genesis ledger and remove the hard fork

update for zenith

---

automation/terraform/modules/kubernetes/testnet/helm.tf
automation/terraform/modules/o1-testnet/testnet.tf
buildkite/src/Command/DeployTestnet.dhall

update testnet k8s module helm chart versions and refactor ci deploy steps

---

docs/uploading-genesis-proofs.md

Docs: Upload genesis proofs

---

automation/terraform/infrastructure/templates/testnet-alerts.yml.tpl
src/lib/consensus/intf.ml
src/lib/mina_metrics/mina_metrics.ml
src/lib/network_pool/snark_pool.ml
src/lib/network_pool/transaction_pool.ml
src/lib/transition_frontier/full_frontier/full_frontier.ml

Add prometheus metrics required for the majority of alerts described in this [issue](https://github.com/MinaProtocol/mina/issues/7728).

Alert metrics

---

.gitignore
src/app/test_executive/README.md
src/lib/integration_test_cloud_engine/coda_automation.ml

changes only to readme and comments

flesh out readme a bit

---

src/app/test_executive/test_executive.ml

addressing https://github.com/MinaProtocol/mina/issues/8038

fail intg test if any internal errors

---

src/lib/transition_router/initial_validator.ml

Checklist:
Closes #0000
Closes #0000

Adding logs when drop blocks

---

src/lib/transition_router/initial_validator.ml

We weren't logging anything for timeouts that trigger after we have started validation. This PR fixes that.
Checklist:

Catch and log all callback timeouts in Initial_validator

---

dockerfiles/Dockerfile-toolchain

fix mina toolchain dockerfile build

---

graphql_schema.json
src/lib/filtered_external_transition/filtered_external_transition.ml
src/lib/mina_graphql/mina_graphql.ml

The graphql `block` query should return the block at a given height from the best chain
Closes #8111

graphql retrieve block at a given height from the best chain

---

automation/services/watchdog/metrics.py
automation/services/watchdog/watchdog.py
automation/terraform/modules/testnet-alerts/templates/testnet-alert-rules.yml.tpl

This PR updates several of the alerts, and adds an alert to check if logs are being pushed to stack driver.

Fix alerts

---

Makefile
src/app/test_executive/test_executive.ml
src/lib/integration_test_cloud_engine/coda_automation.ml
src/lib/integration_test_cloud_engine/kubernetes_network.ml
src/lib/integration_test_cloud_engine/stack_driver_log_engine.ml
src/lib/integration_test_lib/intf.ml
src/lib/integration_test_lib/util.ml

check if a namespace of the same name already exists, if yes then tear it down

check existing namespace

---

graphql_schema.json
src/lib/filtered_external_transition/filtered_external_transition.ml
src/lib/mina_graphql/mina_graphql.ml
src/lib/mina_lib/coda_subscriptions.ml

This PR exposes transaction failure reason from graphQL (as mentioned here: https://github.com/MinaProtocol/mina/issues/8151)

Transaction failure in graphql api

---

src/lib/verifier/prod.ml

This PR fixes the issue described in #8166 around our handling of verifier process restarts.
Checklist:
Closes #8166

Handle verifier process exits safely

---

dockerfiles/Dockerfile-coda-daemon
dockerfiles/Dockerfile-coda-demo
scripts/rebuild-deb.sh

Checklist:
Closes #0000
Closes #0000

release/mainnet-v1.1.1 Fix dockerfiles for mainnet package

---

src/lib/mina_graphql/mina_graphql.ml

In GraphQL, the sync status reported by `syncStatus` differed from that contained in the  result of `daemonStatus", because they were computed in slightly different ways.
Change `syncStatus` to call `get_status` and pull out the sync status, so those computations agree.
(Possible that the results will still differ because of a data race.)
Tested with a local network.
Closes #8251.

GraphQL, use sync status from status

---

automation/terraform/modules/testnet-alerts/templates/testnet-alert-rules.yml.tpl

Add runbook to SeedListDown alert definition

---

automation/services/watchdog/scripts/network-utilities.py

add testnet age to integration test cleanup debug info

---

automation/terraform/modules/testnet-alerts/templates/testnet-alert-rules.yml.tpl

Checklist:
Closes #0000
Closes #0000

adding links to runbooks

---

src/app/libp2p_helper/src/codanet.go
src/app/libp2p_helper/src/libp2p_helper/main.go

Checklist:
Closes #0000
Closes #0000

[master-qa] increase timeout for nodeStatus

---

src/app/cli/src/mina.ml
src/lib/integration_test_cloud_engine/coda_automation.ml
src/lib/runtime_config/runtime_config.ml

Allow passing a peer-list-url in the runtime config

---

src/lib/mina_lib/coda_subscriptions.ml

I'm considering this as a possible source of the WNOHANG exceptions, especially since it is a (usually) short-running process that we run fairly regularly. [This graph for seed-3](https://o1testnet.grafana.net/explore?orgId=1&left=%5B%221616181820000%22,%221616527420000%22,%22grafanacloud-o1testnet-prom%22,%7B%22expr%22:%22Coda_Block_latency_upload_to_gcloud_blocks%7Btestnet%3D%5C%22mainnet%5C%22,%20app%3D%5C%22seed-3%5C%22%7D%22,%22interval%22:%22%22,%22datasource%22:%22grafanacloud-o1testnet-prom%22,%22requestId%22:%22Q-63b889d2-c6c2-414c-b924-9341285bffc8-0Q-8bb0ce71-08b0-4d67-bdb4-f96365e48dbe-1A%22,%22hide%22:false%7D,%7B%22expr%22:%22Coda_Transition_frontier_max_blocklength_observed%7Btestnet%3D%5C%22mainnet%5C%22,%20app%3D%5C%22seed-3%5C%22%7D%20%2F%202000%22,%22requestId%22:%22Q-63 …

[master-qa] Add aggressive exception handling around precomputed block uploads

---

scripts/clear-deb-s3-lockfile.sh

fix the build debian step in buildkite ci

fix buildkite build debian step

---

src/app/rosetta/lib/account.ml

Checklist:
Closes #0000
Closes #0000

Update TODO comment in Rosetta account.ml about edge case

---

src/lib/mina_lib/mina_lib.ml

fixes https://github.com/MinaProtocol/mina/issues/8246

next staking ledger fix

---

src/app/test_executive/README.md

improve intg test readme

---

buildkite/scripts/publish-deb.sh

Checklist:
Closes #0000
Closes #0000

hotfix/pre-release-debian-channel Fix typo

---

src/lib/merkle_ledger/README.md
src/lib/merkle_ledger/base_ledger_intf.ml
src/lib/merkle_mask/masking_merkle_tree.ml

Added a `README` for `src/lib/merkle_ledger`.
Added some comments to `Base_ledger_intf`. (The Notion doc mentioned `Any_ledger`, but that's just the virtual-method-like dispatch code.)
Opened an issue #8474 after examining the Merkle mask code.

Docs for ledgers

---

buildkite/scripts/publish-deb.sh
scripts/archive/build-release-archives.sh
src/app/archive/archive_lib/processor.ml
src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
src/app/cli/src/init/client.ml
src/app/cli/src/tests/coda_processes.ml
src/app/cli/src/tests/coda_worker.ml
src/app/cli/src/tests/full_test.ml
src/lib/child_processes/child_processes.ml
src/lib/child_processes/child_processes.mli
src/lib/child_processes/termination.ml
src/lib/gossip_net/libp2p.ml
src/lib/mina_net2/mina_net2.ml
src/lib/mina_net2/mina_net2.mli

Running CI to confirm that all is well, please do not merge until it's done.

Merge back to compatible

---

buildkite/src/Jobs/Release/ArchiveNodeArtifact.dhall
src/archive_blocks.opam

Rename build_archive to build_archive_all_sigs

---

src/lib/ppx_register_event/register_event.ml

Change structured event parser generator to use maps instead of alists

---

src/app/test_executive/common_prefix.ml
src/lib/integration_test_cloud_engine/kubernetes_network.ml
src/lib/integration_test_lib/intf.ml

reduce number of block producers from 4 to 3, reduce number of blocks we wait for from 6 to 4.  also some minor aesthetic changes

tweak common prefix test to make it slightly faster

---

README-dev.md
scripts/Brewfile.lock.json
scripts/macos-setup.sh
scripts/setup-opam.sh

I set up a fresh macOS laptop and the instructions (as tweaked below) surprisingly worked. I can successfully build `mina.exe` with no compiler or linker errors.

Slightly better macOS dev setup experience

---

automation/services/mina-bp-stats/sidecar/sidecar.py

This PR replaces #8368 and fixes #8365.
TL;DR nodes only keep ~290 blocks in memory at a time, so if we ever get into a situation where we're trying to fetch a block older than that, the sidecar will fail indefinitely until restarted (since it's checking for a block ID that will never successfully be fetched).
This PR fixes this issue by fetching the current block height every time an error is encountered (after ensuring that the node is fully synced). Originally we were also accepting the `CATCHUP` phase before interrogating for blocks, but we should really only be flushing stats on synced nodes so this waits for things to be fully synced before trying to pull down blocks or ship off stats.

Update sidecar to handle blocks outside the 290 block frontier

---

automation/terraform/modules/testnet-alerts/templates/testnet-alert-rules.yml.tpl

Checklist:
Closes #0000
Closes #0000

fix a typo in testnet-alert-rules

---

src/lib/merkle_ledger/README.md
src/lib/merkle_ledger/merkle_ledger_intf.ml
src/lib/merkle_ledger/merkle_path.ml
src/lib/merkle_ledger/util.ml
src/lib/syncable_ledger/syncable_ledger.ml

In `Merkle_ledger`, add descriptions for code in the `README`.
Also changed/removed some `open`s that don't affect functionality.

Merkle_ledger, code descriptions

---

src/app/test_executive/gossip_consistency.ml
src/app/test_executive/payments_timed_accounts_test.ml
src/lib/integration_test_cloud_engine/kubernetes_network.ml
src/lib/integration_test_lib/intf.ml

closes https://github.com/MinaProtocol/mina/issues/8429

remove graphql retry

---

automation/terraform/modules/testnet-alerts/templates/testnet-alert-rules.yml.tpl

Add runbook links. Some of these are still in progress but that can happen independently

Add missing runbooks

---

src/app/delegation_compliance/delegation_compliance.ml

For the `delegation_compliance` app, output a CSV file summarizing the compliance status for each payout address.
Also, only consider payments from slot 3501 onward in the chosen epoch.
Tested by generating CSV files for epochs 0, 1, and 2 for all the Foundation and O(1) delegators.

CSV file output for compliance

---

src/app/rosetta/lib/account.ml

Replaces responses like
```
"balances":[{"value":"7020000000000","currency":{"symbol":"CODA","decimals":9},"metadata":{}}]
``` 
with
```
"balances":[{"value":"7020000000000","currency":{"symbol":"CODA","decimals":9},"metadata":{"locked_balance":2980000000000,"total_balance":10000000000000}}]
```
which allows the client to see the locked and total balances and provides additional context for the existing liquid `value` field.
Tested changes by running the Rosetta integration tests, running `rosetta-cli`, and manually `curl`ing a local server.
Checklist:
Closes #8124

Add {locked,total}_balance to Rosetta account/balance response

---

src/lib/mina_networking/README.md

Put together some high level details around our protocol interface. Tracked down all the RPC messages and broadcast messages and gave them all descriptions. Because this is a document that we will share with external contributors and contractors (as a way to synchronize around what our protocol interface looks like), I have described the type interface in a psuedo type-system. Hopefully, it is less confusing to those who are unfamiliar with OCaml types, but isn't misleading for OCaml devs.

[DOCS] Protocol Interface

---

automation/terraform/infrastructure/us-central1.tf
automation/terraform/infrastructure/us-east1.tf
automation/terraform/infrastructure/us-east4.tf
automation/terraform/infrastructure/us-west1.tf

Add go/process/Mina metrics to prometheus via helm

---

src/lib/snarky_blake2/test/dune
src/lib/snarky_blake2/test/test.ml
src/lib/snarky_taylor/tests/dune
src/lib/snarky_taylor/tests/floating_point_test.ml
src/lib/snarky_taylor/tests/snarky_taylor_test.ml
src/lib/vrf_lib/tests/standalone_test.ml

This will make the new poseidon parameters available

snarky submodule updated

---

src/app/test_executive/payments_test.ml
src/app/test_executive/reliability_test.ml
src/lib/integration_test_lib/dsl.ml
src/lib/integration_test_lib/intf.ml
src/lib/integration_test_lib/malleable_error.ml

now you can use soft sections for when a subsequent sections don't depend on the section 
a part of https://github.com/MinaProtocol/mina/issues/8219

soft sections

---

.gitignore
dev/Makefile
dev/README.md
dev/docker-compose.yml
src/app/reformat/reformat.ml

I couldn't find an actual flow for building/dev'ing using Docker, and as I'm running into build issues on Mac I made this easy-to-set-up dev workflow.

[docker] added dev flow

---

dockerfiles/scripts/cron_job_dump_ledger.sh
helm/staking-ledger-cron/mainnet-dump-staking-ledger-cronjob.yaml

Restore cronjob to match the current production deployment

feature/dont-infinitely-restart-cronjob-on-failures.yaml 

---

src/lib/ledger_catchup/super_catchup.ml
src/lib/mina_commands/mina_commands.ml
src/lib/transition_frontier/full_catchup_tree.ml

Checklist:
Closes #0000
Closes #0000

Log/more logs for catchup 1.1.6

---

buildkite/src/Jobs/Test/TestnetIntegrationTests.dhall
src/app/test_executive/reliability_test.ml
src/app/test_executive/short_bootstrap.ml
src/app/test_executive/short_bootstrap.mli
src/app/test_executive/test_executive.ml

these changes are already in develop but we forgot to put them in compat

split flaky bootstrap stuff into short-bootstrap test

---

buildkite/src/Jobs/Test/TestnetIntegrationTests.dhall
src/app/libp2p_helper/src/libp2p_helper/main.go
src/app/test_executive/reliability_test.ml
src/app/test_executive/short_bootstrap.ml
src/app/test_executive/short_bootstrap.mli
src/app/test_executive/test_executive.ml
src/lib/mina_net2/mina_net2.ml

Addressing a simple bug that was (I think) introduced by a merge from compatible.

Fix libp2p_helper bug

---

src/app/test_executive/reliability_test.ml
src/app/test_executive/short_bootstrap.ml
src/app/test_executive/test_executive.ml

fix an important typo, must have gotten in messed up in a merge or something, or mb "problem was between keyboard and chair" idk

Fix short boot

---

src/app/libp2p_helper/src/libp2p_helper/main_test.go

use new enum instead of old one for unit test

---

src/app/libp2p_helper/src/libp2p_helper/main.go
src/lib/mina_net2/mina_net2.ml

Adds some logging to help confirm a theory regarding the offline status issue we are seeing on the beta release.

[DO NOT MERGE] Debug offline issue

---

frontend/wallet/src/main/DaemonProcess.re
src/app/rosetta/docker-demo-start.sh
src/app/rosetta/docker-start.sh
src/app/rosetta/docker-test-start.sh
src/lib/mina_net2/mina_net2.ml

Use `MINA_LIBP2P_HELPER_PATH` throughout the codebase.
Part of #9041.

Use MINA_LIBP2P_HELPER_PATH

---

src/fork_id.opam

Remove fork_id.opam

---

buildkite/scripts/publish-deb.sh
buildkite/src/Constants/ContainerImages.dhall
dockerfiles/Dockerfile-toolchain
scripts/clear-deb-s3-lockfile.sh
src/app/cli/src/init/coda_run.ml
src/lib/mina_lib/mina_lib.ml
src/lib/mina_lib/mina_lib.mli

Not the cleanest way to implement this, but should be effective for the time being.

 Crash if offline for 30min

---

rfcs/0042-node-status-collection.md

This PR creates the RFC for node status collection service, here's the link to the rfc: 
https://github.com/MinaProtocol/mina/blob/598d3564dec33dee4c4e924b463d22879bd5ba9e/rfcs/0042-node-status-collection.md

[RFC] Node status collection

---

src/app/rosetta/README.md

Add fixes in #9356 and #9366 to Changelog.

Update Rosetta README

---

src/lib/mina_net2/mina_net2.ml

Checklist:
Closes #0000
Closes #0000

ipc delay spam logs

---

src/lib/pipe_lib/strict_pipe.ml

Checklist:
Closes #0000
Closes #0000

retain pipe overflow behaviour

---

src/app/rosetta/README.md

Update readme to refer to rosetta-v1

lk86/rosetta-readme-referece-rosetta-v1 

---

src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
src/lib/mina_metrics/mina_metrics.ml
src/lib/mina_net2/mina_net2.ml

TODO: We may want get memory stats once in a while

Run Gc.stat in intervals 

---

dockerfiles/stages/5-production
src/app/rosetta/lib/account.ml

Reverts MinaProtocol/mina#9426
We want to revert for now because this (maybe) causes some sort of stampeding herd issue on Postgres

Revert "Rosetta, remove nonce from balance response"

---

src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
src/lib/mina_metrics/mina_metrics.ml

Reopens @deepthiskumar 's PR #9373 as github shows it as "merged" even though the commits from here were reverted. This PR reverts that commit thereby providing the same diff as #9373

Run GC Stat in intervals

---

src/lib/mina_commands/mina_commands.ml
src/lib/mina_lib/mina_lib.ml
src/lib/mina_lib/mina_lib.mli

Crash daemon when the uptime is between 40-48 hours.
The offline issue starts happening between 50 - 60 hrs

stop long running daemon

---

src/lib/mina_metrics/mina_metrics.ml
src/lib/transition_frontier/full_frontier/full_frontier.ml

Helps determine if a node is not processing blocks (post validation)
Closes #9091
Closes #7862

block height metric

---

src/app/rosetta/README.md

Use devnet in the example not dev

dev -> devnet in README example

---

src/app/rosetta/README.md

Move from rosetta-v1 to rosetta-v2 in the docs

Rosetta: Move versions to v2

---

buildkite/scripts/replayer-test.sh
dockerfiles/Dockerfile-mina-archive
dockerfiles/Dockerfile-rosetta
graphql_schema.json
src/config/features/mainnet.mlh
src/config/features/public_testnet.mlh
src/lib/mina_base/account.ml
src/lib/mina_base/snapp_account.ml
src/lib/mina_transition/external_transition_sample_precomputed_block.ml
src/lib/network_pool/transaction_pool.ml
src/lib/staged_ledger/staged_ledger.ml
src/lib/transaction_snark/transaction_snark.ml
src/nonconsensus/mina_numbers/snapp_version.ml
src/nonconsensus/mina_numbers/snapp_version.mli

Fixes for build failure and tests
Disabling the replayer test until we have a new archive database.
[This](https://buildkite.com/o-1-labs-2/mina/builds/18929#7548a955-444f-4109-8546-7bb4acfbb73a) ci run passed all but replayer test. Integration tests are being flaky

Fix tests in snapps branch

---

.github/ISSUE_TEMPLATE/1-BUG_REPORT.yml
.github/ISSUE_TEMPLATE/2-DOCUMENTATION.yml
.github/ISSUE_TEMPLATE/3-TEST_REPORT.yml
.github/ISSUE_TEMPLATE/config.yml

Updated the Discussions links that pointed to another repo
No tests were performed since we need GH to render the template to be sure it's looking alright.
Checklist:

Updated GH discussions link

---

buildkite/src/Constants/ContainerImages.dhall
dockerfiles/Dockerfile-toolchain
scripts/mina.service

Make an initial change to trigger ci
---
*
*
Checklist:
* Closes #0000

lk86/rebuild-dockerfile-toolchain 

---

src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
src/lib/secrets/keypair_common.ml
src/lib/secrets/privkey_error.ml
src/lib/secrets/wallets.ml
src/lib/secrets/wallets.mli

Fixes a bug with the backwards compatibility of the env var upgrade.

Fix env var backwards compatibility

---

src/app/rosetta/lib/account.ml
src/app/rosetta/lib/network.ml
src/lib/rosetta_lib/user_command_info.ml

* Fixes unit tests in rosetta_lib and src/app/rosetta
* dune runtest

Fixes rosetta unit tests

---

src/lib/crypto/kimchi_backend/common/plonk_constraint_system.ml

This fixes the `add_constraint` function ƒor the Poseidon's constraint to work like it used to.

[kimchi][backend] fix poseidon to take array of array of length 3

---

src/lib/mina_base/snapp_generators.ml

The Quickcheck generator `gen_parties_from` takes a ledger and a keymap, a map from public keys to private keys, as arguments. The keymap is used to find private keys for signatures.
An unstated invariant was that the keymap contains at least the keys in the ledger. It can also contain extra keys for new accounts that might be created.
That invariant wasn't being checked. With the change here, the generator will fail if the invariant isn't met.
Tested by running the unit tests we have in `Transaction_pool`, that rely on `gen_parties.from`.

Check the keymap contains ledger keys

---

src/app/libp2p_helper/src/codanet.go
src/app/libp2p_helper/src/libp2p_helper/config_msg.go
src/app/libp2p_helper/src/libp2p_helper/config_msg_test.go
src/app/libp2p_helper/src/libp2p_helper/peer_msg.go
src/app/libp2p_helper/src/libp2p_helper/util_test.go
src/lib/downloader/downloader.ml
src/lib/logger/impl.ml
src/lib/mina_net2/tests/all_ipc.ml

* Drop connections which become unwanted with the new gating config
* Uncomment part of Mina net2 / All IPC test which relies upon immediate ban of a banned peer
* Mina net2 / All IPC test
Checklist:

Modify the gating state application logic

---

automation/terraform/modules/o1-testnet/inputs.tf
automation/terraform/modules/o1-testnet/testnet.tf
automation/terraform/testnets/gossipqa/gossipqa-prom-pvc.yaml
automation/terraform/testnets/gossipqa/main.tf
automation/terraform/testnets/gossipqa/readme.md
automation/terraform/testnets/gossipqa/values-stack.yaml
automation/terraform/testnets/gossipqa/values.yaml

put some of the changes into variables

---

src/app/test_executive/README.md

Intgtest documentation

---

docs/specs/signatures/description.md

This PR updates Mina's signature algorithm RFC to match the actual implementation
* Closes #9901

Updated mina signature RFC for Pasta Pallas curves

---

src/lib/marlin_plonk_bindings/bigint_256/marlin_plonk_bindings_bigint_256.ml
src/lib/marlin_plonk_bindings/pasta_fp/marlin_plonk_bindings_pasta_fp.ml
src/lib/marlin_plonk_bindings/pasta_fp/vector/dune
src/lib/marlin_plonk_bindings/pasta_fp/vector/marlin_plonk_bindings_pasta_fp_vector.ml
src/lib/marlin_plonk_bindings/pasta_fp_index/marlin_plonk_bindings_pasta_fp_index.ml
src/lib/marlin_plonk_bindings/pasta_fp_proof/marlin_plonk_bindings_pasta_fp_proof.ml
src/lib/marlin_plonk_bindings/pasta_fq/marlin_plonk_bindings_pasta_fq.ml
src/lib/marlin_plonk_bindings/pasta_fq/vector/dune
src/lib/marlin_plonk_bindings/pasta_fq/vector/marlin_plonk_bindings_pasta_fq_vector.ml
src/lib/marlin_plonk_bindings/pasta_fq_index/marlin_plonk_bindings_pasta_fq_index.ml
src/lib/marlin_plonk_bindings/pasta_fq_proof/marlin_plonk_bindings_pasta_fq_proof.ml
src/lib/marlin_plonk_bindings/pasta_pallas/marlin_plonk_bindings_pasta_pallas.ml
src/lib/marlin_plonk_bindings/pasta_vesta/marlin_plonk_bindings_pasta_vesta.ml

These are the new unit tests from #9145, plus some equivalent tests where they were missing, separated out as their own PR.
Checklist:

[Crypto] Additional rust binding tests

---

graphql_schema.json
src/app/cli/src/init/client.ml
src/app/cli/src/init/graphql_client.ml
src/app/cli/src/init/graphql_queries.ml
src/lib/graphql_lib/decoders.ml
src/lib/mina_graphql/mina_graphql.ml

Snapp Transaction Pool: #9501

---

src/app/snapp_test_transaction/snapp_test_transaction.ml
src/lib/transaction_snark/transaction_snark.ml
src/lib/transaction_snark/transaction_snark.mli

continuation of  https://github.com/MinaProtocol/mina/pull/9861
1. transfer-funds
2. update-sequence-state
Checklist:
* Closes #0000

snapps test txns- part 3

---

src/lib/mina_base/ledger.ml
src/lib/mina_base/transaction_logic.ml
src/lib/transaction_snark/transaction_snark.ml

* fixed the todo to use the new `use_full_commitment` field
Checklist:
* Closes #0000

check for replays

---

src/lib/mina_base/transaction_logic.ml
src/lib/mina_base/transaction_status.ml
src/lib/mina_transition/external_transition_sample_precomputed_block.ml

Failure status specific to the update that failed
Checklist:
* Closes #0000

specific permission related errors

---

src/lib/block_producer/block_producer.ml

This PR tweaks the behaviour of the block producer to check that the best tip isn't at the slot that its currently trying to produce at.
This race condition shouldn't happen in practice on a full network, but arises in some of the snarkless integration tests in #10005 due to the change in timings of the new poseidon hash function for kimchi.
Checklist:

Fix block production race condition in integration test

---

Makefile

Update makefile with a small addition to `make clean`.
Checklist:

Update `make clean`

---

src/lib/mina_base/parties_logic.ml
src/lib/mina_base/party.ml
src/lib/mina_base/transaction_logic.ml
src/lib/transaction_snark/transaction_snark.ml

This PR replaces the `Party_token` effect with a function.
This is part of the work for #10033.
Checklist:

Replace Party_token effect with function

---

src/app/cli/src/init/transaction_snark_profiler.ml
src/lib/merkle_ledger/any_ledger.ml
src/lib/merkle_ledger/base_ledger_intf.ml
src/lib/merkle_ledger/database.ml
src/lib/merkle_ledger/null_ledger.ml
src/lib/merkle_mask/masking_merkle_tree.ml
src/lib/merkle_mask/masking_merkle_tree_intf.ml
src/lib/mina_base/dune
src/lib/mina_base/ledger.mli
src/lib/mina_base/pending_coinbase.ml
src/lib/mina_base/sparse_ledger.ml
src/lib/mina_base/sparse_ledger.mli
src/lib/mina_base/transaction_logic.ml
src/lib/sparse_ledger_lib/sparse_ledger.ml
src/lib/staged_ledger/staged_ledger.ml
src/lib/staged_ledger/staged_ledger.mli
src/lib/transaction_snark/transaction_snark.ml
src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
src/lib/transaction_snark_scan_state/transaction_snark_scan_state.mli
src/lib/transition_frontier/full_frontier/full_frontier.ml
src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml

Attempt to revert sparse ledger diff changes and ensure that the bug is contained in the changes from #9782

[DO NOT MERGE] Lk86/revert 9782

---

src/lib/fields_derivers_snapps/dune
src/lib/mina_base/dune
src/lib/mina_base/snapp_predicate.ml

* Adds the snapps derivers to Closed_interval
* Unit test

Adds derivers for close-intervals

---

src/app/snapp_test_transaction/lib/commands.ml
src/app/snapp_test_transaction/snapp_test_transaction.ml

* Allow password prompts for keyfiles
* Allow partial state update
* better descriptions
Checklist:
* Closes #0000

snapps test transaction tool ux improvements

---

scripts/archive/add_balance_nonce.sh
src/app/archive/archive_lib/processor.ml
src/app/archive/create_schema.sql
src/app/replayer/replayer.ml
src/app/replayer/sql.ml
src/app/rosetta/README.md
src/app/rosetta/lib/account.ml
src/lib/rosetta_lib/errors.ml

Merge of #10258 to resolve develop conflicts

Develop fix for #10258

---

rfcs/0044-node-status-and-node-error-backend.md
rfcs/res/aws_stack.png
rfcs/res/gcloud_logging.png
src/app/archive/archive_lib/processor.ml

This PR merges compatible into `develop`.
Checklist:

Merge compatible into develop

---

src/lib/mina_base/parties_logic.ml

This PR adds the missing checks for fee-payer success that were missed as part of the refactor.
Checklist:

Add missing checks for Local_state.success

---

genesis_ledgers/berkeley.json

update the timestamp for the new qa testnet deployment

update berkeley genesis ledger timestamp

---

automation/terraform/testnets/berkeley/README.md

trivial change, readme changes only

improve readme doc

---

buildkite/src/Jobs/Test/TestnetIntegrationTests.dhall
src/app/test_executive/delegation_test.ml
src/app/test_executive/delegation_test.mli
src/app/test_executive/gossip_consistency.ml
src/app/test_executive/payments_test.ml
src/app/test_executive/test_executive.ml
src/lib/integration_test_cloud_engine/kubernetes_network.ml
src/lib/integration_test_lib/dune
src/lib/integration_test_lib/intf.ml
src/lib/integration_test_lib/wait_condition.ml

same as https://github.com/MinaProtocol/mina/pull/10325 but into develop to make it merge clean

Delegation test develop

---

src/lib/transaction_snark/test/fee_payer/dune
src/lib/transaction_snark/test/fee_payer/fee_payer.ml

fee payer unit tests

---

src/lib/crypto/kimchi_backend/pasta/pallas_based_plonk.ml
src/lib/crypto/kimchi_backend/pasta/vesta_based_plonk.ml
src/lib/crypto/kimchi_bindings/stubs/kimchi.ml
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_proof.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_proof.rs
src/lib/crypto/rust-toolchain.toml

[crypto][kimchi] update proof-systems to latest

---

src/lib/network_pool/transaction_pool.ml

Tweak the code for the assertion that transactions in the transaction pool are given in decreasing fee/weight order (subject to nonce ordering).
Instead of creating a sorted list of transactions, and checking for equality with the original list, use `List.is_sorted` on the transaction list.
With this change, there's no concern that the tie-breaker that compares transaction hashes in `get_highest_fee`, which is called to create the list of transactions, might break the assertion.
Also, instead of negating the comparison on fee/weights, just swap the arguments, a bit more efficient.

Tweak fee/weight assertion

---

src/lib/fields_derivers_json/fields_derivers_json.ml
src/lib/fields_derivers_snapps/fields_derivers_snapps.ml

* Raise more descriptive exceptions than `failwith` and builtin exn functions
* Better errors experienced
Closes #10407

Derivers better errors

---

src/lib/crypto/kimchi_bindings/stubs/src/linearization.rs
src/lib/crypto/kimchi_bindings/stubs/src/oracles.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_index.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_proof.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_verifier_index.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_index.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_proof.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_verifier_index.rs
src/lib/crypto/kimchi_bindings/stubs/src/plonk_verifier_index.rs

[crypto][kimchi] update to latest version

---

src/lib/crypto/kimchi_bindings/js/test/bindings_js_test.ml
src/lib/crypto/kimchi_bindings/js/test/dune
src/lib/crypto/kimchi_bindings/js/test/nodejs/copy_over.sh
src/lib/crypto/kimchi_bindings/js/test/nodejs/dune

This fixes compilation of the node_js test bindings.
Checklist:

Fixup compilation of node_js tests for bindings

---

src/lib/crypto/kimchi_bindings/stubs/kimchi.ml
src/lib/crypto/kimchi_bindings/stubs/src/linearization.rs
src/lib/crypto/kimchi_bindings/stubs/src/oracles.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_index.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_proof.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_verifier_index.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_poseidon.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_index.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_proof.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_verifier_index.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_poseidon.rs
src/lib/crypto/kimchi_bindings/stubs/src/plonk_verifier_index.rs
src/lib/crypto/kimchi_bindings/wasm/src/arkworks/bigint_256.rs
src/lib/crypto/kimchi_bindings/wasm/src/arkworks/pasta_fp.rs
src/lib/crypto/kimchi_bindings/wasm/src/arkworks/pasta_fq.rs
src/lib/crypto/kimchi_bindings/wasm/src/oracles.rs
src/lib/crypto/kimchi_bindings/wasm/src/pasta_fp_plonk_index.rs
src/lib/crypto/kimchi_bindings/wasm/src/pasta_fq_plonk_index.rs
src/lib/crypto/kimchi_bindings/wasm/src/plonk_proof.rs
src/lib/crypto/kimchi_bindings/wasm/src/plonk_verifier_index.rs
src/lib/crypto/kimchi_bindings/wasm/src/poseidon.rs

Updating our proof system library to the latest version

[crypto][kimchi] update to the latest version

---

Makefile
src/app/test_executive/chain_reliability_test.ml
src/app/test_executive/peers_reliability_test.ml

Merge latest `georgeee/block-production-prio` into `develop`
Checklist:

Georgeee/merge georgeee/block production prio to develop 3

---

src/lib/transaction_snark/transaction_snark.ml

failure status in the proof statement had to be empty
Checklist:
* Closes #0000

fix snark worker failure in zkapp test

---

src/app/test_executive/test_common.ml
src/app/test_executive/zkapps.ml

fail zkapps test sooner

---

docs/specs/signatures/description.md

Update links to make them up-to-date with mina book.
Checklist:
* Closes #0000

Update links in description.md

---

src/lib/block_producer/block_producer.ml
src/lib/bootstrap_controller/bootstrap_controller.ml
src/lib/bootstrap_controller/bootstrap_controller.mli
src/lib/bootstrap_controller/dune
src/lib/mina_intf/transition_frontier_components_intf.ml
src/lib/mina_lib/mina_lib.ml
src/lib/mina_transition/external_transition.ml
src/lib/mina_transition/external_transition_intf.ml
src/lib/transition_frontier/frontier_base/breadcrumb.ml
src/lib/transition_frontier_controller/transition_frontier_controller.ml
src/lib/transition_handler/processor.ml
src/lib/transition_handler/validator.ml
src/lib/transition_router/initial_validator.ml
src/lib/transition_router/transition_router.ml

Merge of #10684 to `develop`
Checklist:

Merge georgeee/remove valid callback out of block to develop

---

src/app/test_executive/zkapps.ml

and seed node too
Checklist:
* Closes #0000

Wait for snark coordinator initialization in zkapps test

---

frontend/leaderboard/.npmignore
frontend/leaderboard/package.json
frontend/leaderboard/src/Bindings.re
frontend/leaderboard/yarn.lock
src/app/archive/archive_lib/diff.ml
src/app/archive/archive_lib/processor.ml
src/app/libp2p_helper/src/libp2p_helper/config_msg_test.go
src/lib/block_producer/block_producer.ml
src/lib/gossip_net/libp2p.ml
src/lib/gossip_net/message.ml
src/lib/mina_intf/transition_frontier_components_intf.ml
src/lib/mina_networking/mina_networking.ml
src/lib/mina_transition/block.ml
src/lib/mina_transition/block.mli
src/lib/mina_transition/body.ml
src/lib/mina_transition/body.mli
src/lib/mina_transition/body_reference.ml
src/lib/mina_transition/body_reference.mli
src/lib/mina_transition/external_transition.ml
src/lib/mina_transition/external_transition_intf.ml
src/lib/mina_transition/header.ml
src/lib/mina_transition/header.mli
src/lib/protocol_version/dune
src/lib/protocol_version/protocol_version.ml
src/lib/protocol_version/protocol_version.mli
src/lib/transition_frontier/frontier_base/breadcrumb.ml
src/lib/transition_frontier/persistent_frontier/database.ml
src/lib/uptime_service/uptime_service.ml

Merging PR #10727 to develop
Checklist:

Merge `georgeee/split-block-header-body` to `develop`

---

buildkite/scripts/connect-to-mainnet-on-compatible.sh
buildkite/scripts/replayer-test.sh

Merge fix replayer test to develop

---

buildkite/scripts/connect-to-mainnet-on-compatible.sh
buildkite/scripts/replayer-test.sh

Try to fix replayer and conenct to mainnet tests
Checklist:

Try to fix replayer and conenct to mainnet tests

---

src/app/archive/archive_lib/diff.ml
src/app/archive/archive_lib/processor.ml
src/lib/block_producer/block_producer.ml
src/lib/gossip_net/libp2p.ml
src/lib/gossip_net/message.ml
src/lib/mina_intf/transition_frontier_components_intf.ml
src/lib/mina_networking/mina_networking.ml
src/lib/mina_transition/block.ml
src/lib/mina_transition/block.mli
src/lib/mina_transition/body.ml
src/lib/mina_transition/body.mli
src/lib/mina_transition/body_reference.ml
src/lib/mina_transition/body_reference.mli
src/lib/mina_transition/external_transition.ml
src/lib/mina_transition/external_transition_intf.ml
src/lib/mina_transition/header.ml
src/lib/mina_transition/header.mli
src/lib/protocol_version/dune
src/lib/protocol_version/protocol_version.ml
src/lib/protocol_version/protocol_version.mli
src/lib/transition_frontier/frontier_base/breadcrumb.ml
src/lib/transition_frontier/persistent_frontier/database.ml
src/lib/uptime_service/uptime_service.ml

Introduce a block type which has separate sections of body and header.
Use this type everywhere, making necessary conversions to the old type.
Explain how you tested your changes: existing tests cover this refactoring well.
Checklist:

Introduce a new block type

---

src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
src/dune.flags.inc
src/external/ocaml-rocksdb/dune
src/external/ocaml-rocksdb/rocks_linker_flags_gen.ml

Companion PR for #10770 with similar changes. Merges #10770 into develop.

Temporarily revert LLD linking, develop

---

src/app/test_executive/block_production_priority.ml
src/app/test_executive/chain_reliability_test.ml
src/app/test_executive/delegation_test.ml
src/app/test_executive/gossip_consistency.ml
src/app/test_executive/payments_test.ml
src/app/test_executive/peers_reliability_test.ml
src/lib/integration_test_cloud_engine/kubernetes_network.ml
src/lib/integration_test_cloud_engine/mina_automation.ml
src/lib/integration_test_lib/intf.ml
src/lib/integration_test_lib/test_config.ml

extra_genesis_accounts replacing aux_accounts and the logic that deepthi wrote in develop

extra genesis accounts for intg test framework

---

src/lib/ledger_catchup/super_catchup.ml
src/lib/logger/impl.ml
src/lib/mina_net2/libp2p_helper.ml
src/lib/transition_frontier/full_frontier/full_frontier.ml

I hit the button on the wrong PR :man_facepalming:

Revert "Merge "Fix misc error logging issues" into develop"

---

CODEOWNERS

This updates the codeowners of some parts of the code:
* src/lib/snarky_js_bindings -> product-eng + @imeckler + @mrmr1993
* add product-eng to some other JS parts of the codebase
* src/lib/crypto -> crypto-eng

Update codeowners for JS / crypto

---

src/lib/snarky_js_bindings/test_module/simple-zkapp-mina-signer-quick.js

This PR bumps snarkyjs to the [reviewed PR](https://github.com/o1-labs/snarkyjs/pull/125) that will be merged into snarkyjs/main and become the next published version.

Finish snarkyjs transaction construction

---

docs/access-testnet-nodes-graphql.md

Adds some docs on port forwarding / remote execution on testnet nodes, so that I don't have to figure it out again every time :)
Checklist:

Port forwarding docs

---

graphql_schema.json
src/lib/fields_derivers_zkapps/fields_derivers_zkapps.ml

* Fix the `name` of the `public_key` deriver from "Field" to "PublicKey"
* Update graphql-schema.json

Fix graphql type of public key

---

nix/ocaml.nix

Adds lld to buildInputs of Mina, thus building Mina with lld. Should speed things up.

Nix: use lld

---

.github/ISSUE_TEMPLATE/1-BUG_REPORT.yml

* Added bug and triage labels to the bug template
* Previewed it online, but test can only happen after merging.

Added bug and triage labels to the bug template

---

flake.nix
nix/ocaml.nix
nix/overlay.nix
src/dune-project
src/lib/crypto/kimchi_bindings/stubs/dune

Nix packaging develop

---

flake.lock
nix/overlay.nix

_get 11111_
Fixes https://github.com/MinaProtocol/mina/issues/11080

[Nix] Fix macOS build

---

buildkite/src/Constants/ContainerImages.dhall
dockerfiles/stages/3-toolchain

Use MinaProtcol's repo for `deb-s3`

---

genesis_ledgers/berkeley.json

bump genesis timestamp for berk redeploy 2022-06-02

---

src/lib/crypto/Cargo.lock
src/lib/crypto/kimchi_backend/common/plonk_dlog_proof.ml
src/lib/crypto/kimchi_bindings/stubs/Cargo.toml
src/lib/crypto/kimchi_bindings/stubs/binding_generation/src/main.rs
src/lib/crypto/kimchi_bindings/stubs/kimchi_types.ml
src/lib/crypto/kimchi_bindings/stubs/src/linearization.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_index.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_proof.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_verifier_index.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_index.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_proof.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_verifier_index.rs
src/lib/crypto/kimchi_bindings/stubs/src/plonk_verifier_index.rs
src/lib/crypto/kimchi_bindings/wasm/Cargo.toml
src/lib/crypto/kimchi_bindings/wasm/src/arkworks/pasta_fp.rs
src/lib/crypto/kimchi_bindings/wasm/src/arkworks/pasta_fq.rs
src/lib/crypto/kimchi_bindings/wasm/src/pasta_fp_plonk_index.rs
src/lib/crypto/kimchi_bindings/wasm/src/pasta_fq_plonk_index.rs
src/lib/crypto/kimchi_bindings/wasm/src/plonk_proof.rs
src/lib/crypto/kimchi_bindings/wasm/src/plonk_verifier_index.rs
src/lib/pickles/verification_key.ml

This PR updates the `proof-systems` module to `master` and updates the bindings for those changes.
Checklist:

Bump proof systems

---

flake.lock
flake.nix
nix/checks.nix
nix/modules/mina.nix
nix/ocaml.nix
src/lib/command_line_tests/command_line_tests.ml

Nix CI (develop)

---

scripts/run_local_network.sh

Adds support of Archive Node spawning as part of local env. spinning up process.
- Introduces new CLI arguments;
- Formatting;
- Closes #11129.

Archive Node support for Local network runner

---

src/lib/network_pool/indexed_pool.ml
src/lib/network_pool/transaction_pool.ml

Minimize transaction replacement fee

---

src/app/test_executive/zkapps.ml
src/lib/parties_builder/parties_builder.ml

Add more tokens tests to the `zkApp` integration test, similar to those in #11213.

More tokens tests in zkApps integration test

---

src/lib/currency/currency.ml
src/lib/currency/dune
src/lib/mina_wire_types/currency.ml
src/lib/mina_wire_types/currency.mli
src/lib/mina_wire_types/dune
src/lib/mina_wire_types/index.mld
src/lib/mina_wire_types/utils.ml
src/mina_wire_types.opam
src/nonconsensus/currency/dune

Extract Currency.Amount.t into a separate, compatible library

---

genesis_ledgers/berkeley.json

bump berkeley genesis timestamp

---

src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml

This PR fixes a bug where the 'self' rule was failing to resolve when using recursion in SnarkyJS. This adds the special-casing required to look up the required `Typ.t`.
Checklist:

Special-case 'self' `Typ.t` in SnarkyJS bindings

---

nix/overlay.nix

Fixes nix build on x86_64-darwin

Nix: fix darwin build on develop

---

src/app/dump_blocks/dump_blocks.ml
src/app/dump_blocks/dune

Fixup compilation of dump_blocks tool

---

src/app/batch_txn_tool/Dockerfile_txn_burst
src/app/batch_txn_tool/batch_txn_tool.ml
src/app/batch_txn_tool/dune
src/app/batch_txn_tool/txn_tool_graphql.ml

- Simple fix for `batch_txn_tool` as the "getting familiar with the `OCaml`" steps.
- This PR only catches up the codebase to make the tool work again, there are still issues left.

Fix for `batch_txn_tool`

---

.gitignore
nix/README.md

- Different `dev-environment` configuration to make the experience better.

Nix related direnv information (compatible)

---

src/app/test_executive/README.md
src/app/test_executive/test_executive.ml

exit code 6 for integration test failure to create subscription

exit code 6 for failure to create subscription

---

.gitignore
nix/README.md

Replacement for https://github.com/MinaProtocol/mina/pull/11385

Nix related direnv information (develop)

---

buildkite/src/Jobs/Lint/Xrefcheck.dhall
src/app/test_executive/README.md

make it so that check references doesn't fail the whole entire PR

Bk check references COMP

---

src/lib/crypto/kimchi_backend/common/plonk_constraint_system.ml
src/lib/pickles/dummy.ml
src/lib/pickles/side_loaded_verification_key.ml
src/lib/pickles/step_verifier.ml
src/lib/pickles/verification_key.ml

Remove some build warnings due to missing labels on function arguments.

Remove some build warnings

---

default.nix
flake.nix
nix/modules/mina.nix
nix/ocaml.nix
nix/overlay.nix

- Nix: Get rid of static build remnants
- Nix: reformat files with nixfmt

Nix: clean-up

---

automation/terraform/modules/kubernetes/testnet/locals.tf
automation/terraform/modules/kubernetes/testnet/variables.tf
automation/terraform/modules/o1-integration/inputs.tf
automation/terraform/modules/o1-integration/testnet.tf
helm/archive-node/templates/archive.yaml
helm/archive-node/values.yaml
helm/block-producer/templates/block-producer.yaml
helm/block-producer/values.yaml
helm/plain-node/templates/plain-node.yaml
helm/plain-node/values.yaml
helm/seed-node/templates/seed-node.yaml
helm/seed-node/values.yaml
helm/snark-worker/templates/snark-coordinator.yaml
helm/snark-worker/templates/snark-worker.yaml
helm/snark-worker/values.yaml
src/app/test_executive/README.md
src/lib/integration_test_cloud_engine/cli_inputs.ml
src/lib/integration_test_cloud_engine/dune
src/lib/integration_test_cloud_engine/mina_automation.ml

https://github.com/MinaProtocol/mina/pull/11500

Intg test capacity check dev

---

automation/terraform/modules/kubernetes/testnet/locals.tf
automation/terraform/modules/kubernetes/testnet/variables.tf
automation/terraform/modules/o1-integration/inputs.tf
automation/terraform/modules/o1-integration/testnet.tf
buildkite/src/Jobs/Test/DeployTestnetAndDestroy.dhall
helm/archive-node/templates/archive.yaml
helm/archive-node/values.yaml
helm/block-producer/templates/block-producer.yaml
helm/block-producer/values.yaml
helm/plain-node/templates/plain-node.yaml
helm/plain-node/values.yaml
helm/seed-node/templates/seed-node.yaml
helm/seed-node/values.yaml
helm/snark-worker/templates/snark-coordinator.yaml
helm/snark-worker/templates/snark-worker.yaml
helm/snark-worker/values.yaml
src/app/test_executive/README.md
src/lib/integration_test_cloud_engine/cli_inputs.ml
src/lib/integration_test_cloud_engine/dune
src/lib/integration_test_cloud_engine/mina_automation.ml

capacity check before deploying intg test

---

src/app/test_executive/payments_test.ml
src/app/test_executive/test_common.ml
src/app/test_executive/test_executive.ml
src/lib/integration_test_cloud_engine/kubernetes_network.ml
src/lib/integration_test_lib/intf.ml

integration test sometimes has mysterious infra failures.  hopefully we have more transparency into it now

better infra failure debugging

---

src/lib/trust_system/peer_trust.ml
src/lib/trust_system/record.ml
src/lib/trust_system/record.mli

Some cleaner-syntax changes, while I was poring over the trust system code.

Make trust code nicer

---

src/lib/blockchain_snark/blockchain_snark_state.ml
src/lib/pickles/pickles.ml
src/lib/pickles/pickles.mli
src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
src/lib/transaction_snark/test/multisig_account/multisig_account.ml
src/lib/transaction_snark/test/ring_sig.ml
src/lib/transaction_snark/transaction_snark.ml
src/lib/zkapps_examples/zkapps_examples.ml

This PR simplifies the external API of pickles, and makes a small change to replace a use of `H4.T` with an explicit recursive function.
Checklist:

Minor pickles tidy-ups

---

src/app/client_sdk/tests/client_sdk.js

Fix flakiness of client_sdk unit tests

---

src/lib/parties_builder/parties_builder.ml

Remove debug prints from `Parties_builder`.

Remove 'generating' debug prints

---

src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml

- Mina companion of https://github.com/o1-labs/snarkyjs/pull/330

Snarkyjs: Compressed public key

---

src/lib/transaction_logic/parties_logic.ml

shift sequence events once per block and if there are events

---

src/lib/crypto/kimchi_bindings/wasm/Cargo.lock
src/lib/crypto/kimchi_bindings/wasm/Cargo.toml
src/lib/crypto/kimchi_bindings/wasm/src/pasta_fp_plonk_index.rs
src/lib/crypto/kimchi_bindings/wasm/src/pasta_fq_plonk_index.rs
src/lib/crypto/kimchi_bindings/wasm/src/plonk_proof.rs

https://github.com/o1-labs/snarkyjs/issues/348

[crypto] add base64 serialization methods to wasm

---

src/lib/bootstrap_controller/bootstrap_controller.ml
src/lib/mina_base/util/mina_base_util.ml
src/lib/mina_graphql/mina_graphql.ml

remove todo_zkapps

---

scripts/run_local_network.sh

To simplify comms within the controlled LAN.

Listen for GraphQL requests on all NICs (Compatible)

---

scripts/run_local_network.sh

To simplify comms within the controlled LAN.

Listen for GraphQL requests on all NICs (Develop)

---

src/app/libp2p_helper/src/libp2p_helper/bitswap.go
src/app/libp2p_helper/src/libp2p_helper/bitswap_block.go
src/app/libp2p_helper/src/libp2p_helper/config_msg_test.go
src/app/libp2p_helper/src/libp2p_helper/stream_msg.go

Fix a stream leak in the libp2p helper.

Fix libp2p stream leak

---

flake.nix
scripts/build-snarkyjs-node.sh
scripts/update-snarkyjs-bindings.sh
src/lib/snarky_js_bindings/test_module/package-lock.json

* companion of https://github.com/o1-labs/snarkyjs/pull/366

Make snarkyjs an ES module

---

flake.lock
flake.nix

Nix: update nix-npm-buildpackage [compatible]

---

dockerfiles/auxiliary_entrypoints/01-run-demo.sh

- Remove duplicated lines;
- Pass the `MINA_PRIVKEY_PASS` for the `exec` command.

Fix for Docker image Demo-mode (Develop).

---

dockerfiles/auxiliary_entrypoints/01-run-demo.sh

- Remove duplicated lines;
- Pass the `MINA_PRIVKEY_PASS` for the `exec` command;
- Closes #11798

Fix for Docker image Demo-mode

---

src/app/archive/archive_lib/load_data.ml
src/app/archive/archive_lib/processor.ml
src/app/archive/drop_tables.sql
src/app/archive/zkapp_tables.sql
src/app/replayer/test/archive_db.sql

rename zkapp_precondition_accounts -> account_precondition_values

---

automation/scripts/gen-keys-ledger.sh
automation/terraform/modules/o1-testnet/inputs.tf
automation/terraform/modules/o1-testnet/testnet.tf
automation/terraform/testnets/berkeley/main.tf

1. Add input variables to be able to specify cpu and ram for testnet nodes
2. Update berkeley configuration

Specify node resources for testnet nodes

---

src/lib/genesis_constants/genesis_constants.ml
src/lib/genesis_ledger_helper/lib/genesis_ledger_helper_lib.ml
src/lib/integration_test_cloud_engine/mina_automation.ml
src/lib/mina_base/zkapp_command.ml
src/lib/mina_compile_config/mina_compile_config.ml
src/lib/runtime_config/runtime_config.ml
src/lib/transaction_snark/transaction_snark.ml
src/lib/transaction_snark/transaction_snark.mli

Parties limit based on a cost function [develop]

---

src/lib/cli_lib/commands.ml

Fail with meaningful message once empty data passed to 'validate-transaction' (Compatible)

---

src/lib/marlin_plonk_bindings/stubs/Cargo.lock
src/lib/marlin_plonk_bindings/stubs/Cargo.toml
src/lib/marlin_plonk_bindings/stubs/dune

[crypto] pin once_cell to specific version (fix for compatible)

---

src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
src/lib/snarky_js_bindings/tests/pickles-proof.mjs

Companion of https://github.com/o1-labs/snarkyjs/pull/428

Snarkyjs: witness tweak

---

src/app/rosetta/lib/block.ml
src/app/rosetta/lib/network.ml

Currently the height of the genesis block is hard-coded in Rosetta to be `1`. However, this value will change with the hard fork. To avoid the need to keeping it in sync manually with what GraphQL thinks the genesis block is, let's make Rosetta fetch the value from GraphQL, so that only the single source of truth needs to be maintained.
GraphQL takes genesis block's metadata from fork configuration compiled into the daemon binary. Therefore once the fork is set up, GraphQL will automatically return the correct genesis block height.
I manually called the `/network/status` endpoint of the node to check if it still returns 1.
I verified that GraphQL returns genesis block height as defined by fork configuration compiled into the daemon binary. Therefore, when the hard fork is configured, …

Rosetta: Fetch genesis block height from GraphQL.

---

src/lib/crypto/kimchi_bindings/stubs/Cargo.lock

The kimchi_bindings lockfile didn't match the Cargo.toml file. Fix that.

Fix kimchi_bindings lockfile

---

flake.lock

Update opam-nix to fix some warnings.

Nix: fix findlib warnings & completions in utop

---

CONTRIBUTING.md

This aims to update some outdated statements in `CONTRIBUTING.md`. The changes are based on my understanding of the situation, which may not be entirely accurate.
This PR only modifies readmes.
Checklist:

Update the contribution guide.

---

src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml

Companion to https://github.com/o1-labs/snarkyjs/pull/501, exposes timing for accounts

Snarkyjs: expose timing

---

src/app/rosetta/lib/account.ml
src/app/rosetta/lib/network.ml

* 4 / 7 Unit Tests are failing for the Rosetta App. This PR fixes the failing Unit Tests
This is required before enabling them in the CI (https://github.com/MinaProtocol/mina/issues/9293)
* `dune runtest src/app/rosetta` is no longer returning errors 
Checklist:
- [*] All tests pass (CI will check this if you didn't)
* Closes #9332

9332 properly fix ci for rosetta ensure tests are running and passing on all prs

---

buildkite/src/Jobs/Test/RosettaUnitTest.dhall

Following PR [#12035](https://github.com/MinaProtocol/mina/pull/12035) I re-add the Rosetta Unit Tests to the CI
Checklist:
[Buildkite logs](https://buildkite.com/o-1-labs-2/mina/builds/25625#018411f5-d3d1-4826-998a-6ab78c05a138) shows the tests are passing successfully
[*] All tests pass (CI will check this if you didn't)
Closes https://github.com/MinaProtocol/mina/issues/9293

Add Rosetta Unit Tests

---

src/lib/pickles_base/domain.ml
src/lib/pickles_base/dune
src/lib/pickles_base/proofs_verified.ml
src/lib/pickles_base/proofs_verified.mli
src/lib/pickles_base/side_loaded_verification_key.ml

Activate warnings for library `Pickles_base`

---

README-dev.md

added some more info to the README about the opam.export file

[README] added steps to update ocaml dependencies

---

helm/cron_jobs/mainnet-dump-staking-ledger-cronjob.yaml

* specified resources
* changed the image to 1.3.1
Deployed it on mainnet
Checklist:
* Closes #0000

update cron job exporting staking ledgers

---

helm/cron_jobs/mainnet-dump-staking-ledger-cronjob.yaml

https://github.com/MinaProtocol/mina/pull/12157

add resources, update mina image in staking ledger export cron job

---

src/lib/ppx_version/versioned_type.ml

When printing type declarations for the existing version linter, don't print type manifests for non-abstract types. For those types, adding or removing a manifest would trigger a linter warning, even though the underlying type had not changed.
Closes #12169.

Don't print redundant type manifests

---

buildkite/src/Command/Base.dhall
buildkite/src/Jobs/Test/Libp2pUnitTest.dhall

minor change, just changing to a slightly sooner timeout

Libp2pbitswap ci timeout

---

src/lib/crypto/kimchi_bindings/stubs/kimchi_bindings.ml
src/lib/crypto/kimchi_bindings/stubs/kimchi_types.ml
src/lib/pickles/plonk_checks/scalars.ml

This PR just commits changes done automatically by the compilation process.

Update the generated code.

---

src/lib/crypto/kimchi_bindings/stubs/kimchi_bindings.ml
src/lib/crypto/kimchi_bindings/stubs/kimchi_types.ml
src/lib/pickles/plonk_checks/scalars.ml

I'm not sure why these were changed o_O I'm still confused
EDIT: found where it was done https://github.com/MinaProtocol/mina/pull/11958

[crypto] revert ocaml-gen bindings

---

src/app/test_executive/dune
src/app/test_executive/zkapps.ml
src/lib/pickles/pickles.ml
src/lib/pickles/step_main.ml
src/lib/pickles/unfinalized.ml

This is a follow-on to https://github.com/MinaProtocol/mina/pull/11698. This addresses the review comments left there.
Checklist:

Fixup review comments after pickles fix

---

src/app/rosetta/rosetta-cli-config/README.md
src/app/rosetta/rosetta-cli-config/config.json

This PR expands the instruction on how to run `rosetta-cli` testing tool developed by Coinbase with additional information on the workings of the tool.

Rosetta: Expand the documentation on running rosetta-cli tool.

---

genesis_ledgers/berkeley.json
src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml

Merge release/2.0.0 back to develop

---

buildkite/scripts/rosetta-integration-tests.sh

This is a PR providing a script to setup a Postgres / Archive Node / 2x Rosetta API / Rosetta CLI and run the integration tests script against it.
[#5886](https://github.com/MinaProtocol/mina/issues/5886) Will integrate this script as part of the CI.

12099 - Create Integration test scripts for Rosetta API

---

src/app/rosetta/lib/construction.ml

In rosetta a suggested fee is computed by taking the median of all the fees in recent blocks. This fails however on a newly created blockchain where this array of blocks is empty (as it can be the case for the `rosetta-cli` tests). 
This PR fixes this by returning the `minimum_fee` in that case.
* run the `rosetta-cli` construction test locally.

rosetta: fix suggested_fee for first transaction.

---

src/lib/integration_test_cloud_engine/kubernetes_network.ml
src/lib/integration_test_cloud_engine/mina_automation.ml
src/lib/integration_test_cloud_engine/stack_driver_log_engine.ml

trying to be better about cleaning up after the integration test framework is unexpectedly and uncleanly terminated.

Gcp cleanups

---

src/lib/crypto/kimchi_bindings/stubs/kimchi_types.ml
src/lib/crypto/kimchi_bindings/stubs/src/main.rs
src/lib/crypto/kimchi_bindings/stubs/src/plonk_verifier_index.rs
src/lib/pickles/verification_key.ml

This PR builds upon #12325, completing the update of the `proof-systems` submodule for the PR chain ending in https://github.com/o1-labs/proof-systems/pull/839.
Checklist:

Bump proof-systems for refactors

---

docs/specs/consensus/README.md
docs/specs/signatures/description.md

* A couple fixes to signature spec
* Fix to consensus spec security note
* Closes #12339

Fixes to specifications

---

flake.nix
nix/ocaml.nix

Run integration tests from the Nix CI
Closes https://github.com/MinaProtocol/mina/issues/11126

Nix CI: run integration tests

---

src/lib/mina_base/account_update.ml
src/lib/snarky_js_bindings/snarky_js_constants.ml

companion of https://github.com/o1-labs/snarkyjs/pull/643

SnarkyJS: support zkApp URI

---

nix/rust.nix

Let me know if you want me to revert the auto-reformat, my editor wanted to reformat everything on save

Adds libiconv dep

---

buildkite/src/Command/TestExecutive.dhall

Same as #12402, but for `release/2.0.0`.

Snarkysjs int test fix for release 2.0.0

---

src/lib/pickles/step_verifier.ml
src/lib/pickles/verify.ml

This is https://github.com/MinaProtocol/mina/pull/12416 against `release/2.0.0`.

Fix off-by-1 error, check domain size in verify

---

src/lib/crypto/kimchi_bindings/wasm/src/plonk_verifier_index.rs
src/lib/crypto/kimchi_bindings/wasm/src/srs.rs
src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml

The `nix` environment should now build properly

Update binding for plonk-wasm

---

src/lib/crypto/kimchi_bindings/stubs/kimchi_types.ml
src/lib/crypto/kimchi_bindings/stubs/src/linearization.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_verifier_index.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_verifier_index.rs
src/lib/crypto/kimchi_bindings/stubs/src/plonk_verifier_index.rs
src/lib/crypto/kimchi_bindings/wasm/src/plonk_verifier_index.rs
src/lib/pickles/plonk_checks/gen_scalars/gen_scalars.ml
src/lib/pickles/plonk_checks/plonk_checks.ml
src/lib/pickles/plonk_checks/scalars.ml

Closes #12453 
This version has (among other things)
* LookupPatterns et al
* Foreign field modulus moved to coeffs
* New foreign field multiplication lookup pattern
contributor.
don't want to forget to test the incomplete things whenever they are …

Update to latest proof-systems

---

src/lib/mina_numbers/intf.ml
src/lib/mina_numbers/nat.ml

Add Nat.to_field

---

src/lib/pickles/plonk_checks/plonk_checks.ml

Bugfix to pickles feature flags code
* Closes #12485

Bugfix to pickles features

---

src/lib/crypto/snarky_tests/snarky_tests.ml

This adds a simple test for snarky using the monadic API, and makes sure it's the same hash as the same one produced using the imperative API
building on top of https://github.com/MinaProtocol/mina/pull/12128

[crypto] added a snarky test for the monadic API

---

src/lib/mina_base/account_timing.ml
src/lib/transaction_snark/test/account_timing/account_timing.ml
src/lib/transaction_snark/test/account_timing/dune

* Refactor the tests for timed accounts in transaction_snark library.
* In addition to existing tests for specific edge cases, also provide generic quickcheck test.
* Ran the tests, made sure that they still pass.
Checklist:

Refactor timed-account tests in transaction_snark lib

---

src/lib/crypto/kimchi_bindings/stubs/kimchi_bindings.ml
src/lib/crypto/kimchi_bindings/stubs/src/main.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_proof.rs
src/lib/pickles/wrap.ml

This adds foreign field multiplication features/finalization tests to pickles 
* Closes #12223

Foreign field multiplication finalisation tests

---

buildkite/scripts/test-snarkyjs-bindings.sh

Use source maps in JS tests

---

buildkite/scripts/build-snarkyjs-bindings.sh
buildkite/scripts/rosetta-integration-tests.sh
buildkite/src/Jobs/Test/RosettaIntegrationTests.dhall
src/app/rosetta/lib/block.ml
src/app/rosetta/rosetta-cli-config/config.json

Adds recurring transactions, zkApp deployment, and interaction to the Rosetta integration test.
This is needed to have data on the chain for `check:data` to validate.
Integration tests run entirely and without errors.
Closes #12119

Add recurring transactions and zkApp deployment and interaction to Rosetta integration test.

---

scripts/testone.sh
src/lib/crypto/kimchi_bindings/stubs/kimchi_bindings.ml
src/lib/crypto/kimchi_bindings/stubs/src/linearization.rs
src/lib/crypto/kimchi_bindings/stubs/src/main.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_proof.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_proof.rs
src/lib/crypto/kimchi_bindings/stubs/src/urs_utils.rs
src/lib/pickles/plonk_checks/plonk_checks.ml
src/lib/pickles/wrap.ml
src/lib/pickles_types/plonk_types.ml
src/lib/pickles_types/plonk_types.mli

Re-opening https://github.com/MinaProtocol/mina/pull/12382 after manual revert

Finalization for custom gates (reborn)

---

src/lib/crypto/kimchi_bindings/stubs/kimchi_types.ml
src/lib/crypto/kimchi_bindings/stubs/src/linearization.rs
src/lib/crypto/kimchi_bindings/stubs/src/main.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_verifier_index.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_verifier_index.rs
src/lib/crypto/kimchi_bindings/stubs/src/plonk_verifier_index.rs
src/lib/crypto/kimchi_bindings/wasm/src/plonk_verifier_index.rs
src/lib/pickles/plonk_checks/gen_scalars/gen_scalars.ml
src/lib/pickles/plonk_checks/plonk_checks.ml
src/lib/pickles/plonk_checks/scalars.ml
src/lib/pickles/verification_key.ml

This PR bumps the proof-systems submodule to the commit used in #12342, but without any of the supporting changes, as a bare-minimum conversion.
This is part of the exercise to figure out the cause of the CI failure on that PR.
Checklist:

Bump proof-systems submodule for feature flags

---

scripts/testone.sh

This PR ports a small change from https://github.com/MinaProtocol/mina/pull/12342 to make the `testone.sh` script less brittle on some architectures.
Checklist:

Update testone script to be less brittle

---

src/lib/crypto/kimchi_bindings/stubs/kimchi_types.ml
src/lib/crypto/kimchi_bindings/stubs/src/linearization.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_verifier_index.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_verifier_index.rs
src/lib/crypto/kimchi_bindings/wasm/src/plonk_verifier_index.rs
src/lib/pickles/plonk_checks/scalars.ml

This PR is https://github.com/MinaProtocol/mina/pull/12546 without any of the supporting logic. The goal of this PR is to reduce the diff between develop and https://github.com/MinaProtocol/mina/pull/12342 to aid debugging.
Checklist:

Bump proof-systems for splitting of range_check feature flag

---

src/lib/crypto/kimchi_bindings/stubs/src/oracles.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_proof.rs
src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_proof.rs
src/lib/crypto/kimchi_bindings/wasm/src/oracles.rs
src/lib/crypto/kimchi_bindings/wasm/src/plonk_proof.rs

following https://github.com/o1-labs/proof-systems/pull/985

[crypto] update proof system

---

src/lib/crypto/kimchi_backend/common/plonk_constraint_system.ml

Expose the the `ForeignFieldMul` gate to snarky
Re https://github.com/MinaProtocol/mina/issues/12624

Add ForeignFieldMul custom gate

---

src/lib/crypto/kimchi_backend/common/plonk_constraint_system.ml

Expose the the `ForeignFieldAdd` gate to snarky
Re https://github.com/MinaProtocol/mina/issues/12624

Add ForeignFieldAdd custom gate

---

src/lib/crypto/kimchi_backend/common/plonk_constraint_system.ml

Expose the the `Rot64` gate to snarky
Re https://github.com/MinaProtocol/mina/issues/12624

Add Rot64 custom gate to snarky

---

src/lib/mina_base/account.ml
src/lib/transaction_logic/test/account_timing.ml
src/lib/transaction_logic/test/dune
src/lib/transaction_snark/test/account_timing/account_timing.ml

* Add property-based tests for account timing
* CI
Checklist:
* Closes #12586

Test transaction logic timed account

---

buildkite/scripts/connect-to-berkeley.sh

Update connect to berkeley test to add libp2p keys and to run the same way on the develop branch

lk86/update-connect-to-berkeley 

---

src/lib/transaction/transaction_hash.ml

ZkApps are too big to use the Base58Check-based transaction hashes we'd started with. We changed the hashing to use `Bin_prot`-derived strings, which is much faster to compute. We also changed signed commands to use `Bin_prot`.
This PR changes internal commands (coinbases and fee transfers) to use `Bin_prot`-based hashing. The change is not for speed so much, as for consistency.

`Bin_prot`-based hashing for internal commands

---

src/app/archive/lib/processor.ml

Allow no token owner in archive db (rampup)

---

src/app/cli/src/init/client.ml
src/app/cli/src/init/graphql_queries.ml
src/lib/mina_graphql/mina_graphql.ml

There are a numbers of warnings related to file `graphql_queries.ml` in the `cli` app. This PR aims at fixing them.
At this point, the binaries compile and it does not seem that test results have changed.

Fix warnings in `Cli` package

---

src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
src/lib/error_json/error_json.ml
src/lib/mina_net2/libp2p_helper.ml
src/lib/network_pool/intf.ml
src/lib/network_pool/network_pool_base.ml
src/lib/network_pool/pool_sink.ml
src/lib/network_pool/snark_pool_diff.ml
src/lib/network_pool/transaction_pool.ml
src/lib/transition_handler/block_sink.ml

This is https://github.com/MinaProtocol/mina/pull/12810 with some changes from https://github.com/MinaProtocol/mina/pull/12832 and some other extra tweaks that we don't want to merge.

[DO NOT REVIEW] Logging for low_fill_rate debugging

---

buildkite/src/Jobs/Lint/Merge.dhall

* This PR is to set a softfail status for the the CI test - "merges cleanly into compatible".
* This item is being tested with Buildkite CI before merging to confirm the test behaves as expected.
Checklist:
- NA Modified the current draft of release notes with details on what is completed or incomplete within this project
- NA Serialized types are in stable-versioned modules
* Closes #12958

merges into compatible softfail

---

src/lib/crypto/kimchi_backend/gadgets/dune
src/lib/crypto/kimchi_backend/gadgets/foreign_field.ml

minor ffmul gadget improvement

Open and use Core_kernel

---

src/lib/crypto/kimchi_backend/common/plonk_constraint_system.ml
src/lib/crypto/kimchi_backend/gadgets/common.ml
src/lib/crypto/kimchi_backend/gadgets/rot.ml

This PR creates the rotation gadget for 64-bits. 
Closes https://github.com/MinaProtocol/mina/issues/12884

Rotation gadget for Snarky

---

src/lib/crypto/kimchi_backend/common/plonk_constraint_system.ml

This PR adds a missing sign coefficient in the FFAdd gate.

Add sign coefficient in FFdd

---

.github/PULL_REQUEST_TEMPLATE.md
buildkite/src/Command/Base.dhall
helm/zkapps-dashboard/templates/db-cron.yaml
helm/zkapps-dashboard/values.yaml

* New checklist item added to PR template to confirm whether dependency versions have changed.
* Updated automated retry count within buildkite tests. All tests will now try to re-run up to 4 times if they do not succeed the first time. 
* Updated default username and postgres version used for zkapps dashboard.
* All changes are being testing within buildkite CI.
Checklist:
- NA Serialized types are in stable-versioned modules
- NA Does this close issues? List them
* Closes #0000

Buildkite - updated automated retry count

---

.github/PULL_REQUEST_TEMPLATE.md
buildkite/src/Command/Base.dhall

* New checklist item added to PR template to confirm whether dependency versions have changed.
* Updated automated retry count within buildkite tests. All tests will now try to re-run up to 4 times if they do not succeed the first time.
* All changes are being testing within buildkite CI.
Checklist:
- NA Modified the current draft of release notes with details on what is completed or incomplete within this project
- NA Serialized types are in stable-versioned modules
- NA Does this close issues? List them
* Closes #0000

Steven bump buildkite retries compat

---

.github/PULL_REQUEST_TEMPLATE.md
buildkite/src/Command/Base.dhall
helm/zkapps-dashboard/templates/db-cron.yaml
helm/zkapps-dashboard/values.yaml

* New checklist item added to PR template to confirm whether dependency versions have changed.
* Updated automated retry count within buildkite tests. All tests will now try to re-run up to 4 times if they do not succeed the first time.
* Updated default username and postgres version used for zkapps dashboard.
* All changes are being testing within buildkite CI.
Checklist:
- NA Modified the current draft of release notes with details on what is completed or incomplete within this project
- …

Steven bump buildkite retries berk

---

src/lib/mina_base/test/zkapp_command/dune
src/lib/mina_base/test/zkapp_command/nonce_related.ml

Property-Based Tests for functions `target_nonce_on_success`, `nonce_increments` and `check_authorization` in `zkapp_command.ml`
* Closes #12849

Property-Based Tests for functions target_nonce_on_success, nonce_increments and check_authorization

---

flake.nix
nix/javascript.nix
nix/rust.nix

- fix paths in rust.nix
- remove mina signer from nix

Fixing nix for JS build

---

src/lib/mina_base/account.ml

- Fix warnings 16 (see details of first commit)
- Remove unneeded monadic style

Mina_base: 2 simple fixes

---

flake.lock
flake.nix
nix/javascript.nix
nix/rust.nix
opam.export

- https://github.com/MinaProtocol/mina/pull/13131
- https://github.com/MinaProtocol/mina/pull/12931

SnarkyJS Nix fix and opam-repository update for Nix (rampup)

---

src/app/test_executive/payments_test.ml
src/app/test_executive/snark_test.ml
src/app/test_executive/zkapps.ml
src/app/test_executive/zkapps_nonce_test.ml
src/lib/integration_test_lib/intf.ml
src/lib/integration_test_lib/test_config.ml
src/lib/integration_test_lib/wait_condition.ml

this https://github.com/MinaProtocol/mina/pull/13027 for develop

Refactor snarked ledger timeout in tests

---

src/app/test_executive/payments_test.ml
src/app/test_executive/snark_test.ml
src/lib/integration_test_lib/intf.ml
src/lib/integration_test_lib/test_config.ml
src/lib/integration_test_lib/wait_condition.ml

same as https://github.com/MinaProtocol/mina/pull/13027, but merge to comp

Refactor snarked ledger timeout in tests (compatible)

---

automation/terraform/modules/testnet-alerts/templates/testnet-alert-rules.yml.tpl

compatible version of https://github.com/MinaProtocol/mina/pull/13132
Checklist:
* Closes #0000

update fill rate alert threshold for compatible

---

README-dev.md

Add more useful details on building and running a Mina node. In particular:
* Advise using Nix over manual dependency management.
* Show how to clone the repo over SSH.
* Provide more details on the genesis ledger configuration.
*
Checklist:

Elaborate on some details of building and running a node.

---

scripts/mina-local-network/README.md
scripts/mina-local-network/mina-local-network.sh
src/config/lightnet.mlh

- New Dune profile introduction: `lightnet`;
- Mina Local Network Manager scripts and README updates.

Lightweight Network configuration and documentation (rampup).

---

src/app/test_executive/zkapps_timing.ml

Add a zkApp that tries to create an account with a zero vesting period to the zkApps timing integration test. That zkApp should fail immediately from the well-formedness check added in #13266.
Closes #13337.

Zero vesting period in zkApp timing tests

---

src/app/heap_usage/values.ml
src/app/test_executive/zkapps_timing.ml
src/app/zkapp_test_transaction/zkapp_test_transaction.ml
src/lib/crypto/snarky_tests/snarky_tests.ml
src/lib/mina_block/sample_precomputed_block.ml
src/lib/mina_state/local_state.ml
src/lib/mina_state/snarked_ledger_state_intf.ml
src/lib/mina_wire_types/mina_transaction_logic/zkapp_command_logic.ml
src/lib/mina_wire_types/test/type_equalities.ml
src/lib/mina_wire_types/utils.ml
src/lib/transaction_logic/mina_transaction_logic.ml
src/lib/transaction_logic/zkapp_command_logic.ml
src/lib/transaction_snark/transaction_snark.ml
src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
src/lib/transaction_witness/transaction_witness.ml
src/lib/transaction_witness/transaction_witness.mli

Commits for #13370 to allow clean merge-to-develop.

Merge commit for #13370

---

src/app/replayer/dune
src/app/replayer/replayer.ml

This is a merge PR to allow #13406 to merge to develop cleanly.

Merge PR for #13406

---

src/app/batch_txn_tool/txn_tool_graphql.ml

Simple compilation fix for batch_txn_tool 
Built and executed app
Checklist:

Fix compilation issue on batch_txn_tool

---

src/lib/crypto/kimchi_backend/gadgets/common.ml
src/lib/crypto/kimchi_backend/gadgets/ecdsa.ml
src/lib/crypto/kimchi_backend/gadgets/foreign_field.ml
src/lib/crypto/kimchi_backend/gadgets/foreign_field.mli

Closes #12942
Correct `test_group_add_full` circuit + wiring
https://docs.google.com/spreadsheets/d/14T9Y6dYXY5FyAIcoJiCTFufPYBeq7bGNRXHQc49wL2c

Implement foreign field Affine EC point module and foreign field group addition

---

src/lib/crypto/kimchi_backend/gadgets/common.ml
src/lib/crypto/kimchi_backend/gadgets/ecdsa.ml
src/lib/crypto/kimchi_backend/gadgets/foreign_field.ml
src/lib/crypto/kimchi_backend/gadgets/foreign_field.mli

Non-native group double gadget
Closes #12943

Snarky ecdsa foreign field EC group double gadget

---

buildkite/scripts/connect-to-mainnet-on-compatible.sh
src/app/replayer/dune
src/app/replayer/replayer.ml

There were conflicts with the replayer, which has changed significantly to accomodate zkApps.
This PR pulls in some of the checkpointing code from compatible, but that is not completed. This PR is intended to allow clean merges to berkeley, and the checkpointing will need to be finished later.

Merge compatible to berkeley

---

buildkite/src/Jobs/Lint/Merge.dhall

Added new check for conflict against berkeley in compatible PRs
Checked CI results and validated that job is running
Checklist:
* Closes #13365

check conflict against berkeley in compatible PRs

---

Makefile
buildkite/scripts/test-snarkyjs-bindings-minimal.sh
buildkite/src/Jobs/Test/SnarkyJSTest.dhall

berkeley version of https://github.com/MinaProtocol/mina/pull/13430
snarkyjs: https://github.com/o1-labs/snarkyjs/pull/996
bindings: https://github.com/o1-labs/snarkyjs-bindings/pull/49

Blocking SnarkyJS CI tests (berkeley)

---

src/lib/crypto/kimchi_bindings/stubs/Cargo.lock

Cargo.lock of kimchi was breaking `nix develop mina` so the file was updated using `cargo update`

Update cargo lock

---

frontend/ci-build-me/src/index.js

These were part of the changes from `develop` that were reverted in https://github.com/MinaProtocol/mina/pull/13212
Checklist:
* Closes #0000

add back gate-keeper changes

---

genesis_ledgers/berkeley.json

updated genesis timestamp

---

README-ci-failures.md

Update README-ci-failure with instructions if no CI jobs started

---

src/app/cli/src/init/itn.ml
src/app/itn_orchestrator/Makefile
src/app/itn_orchestrator/src/data.go
src/app/itn_orchestrator/src/discovery.go
src/app/itn_orchestrator/src/fund.go
src/app/itn_orchestrator/src/gating.go
src/app/itn_orchestrator/src/generator/main.go
src/app/itn_orchestrator/src/graphql.go
src/app/itn_orchestrator/src/itn_orchestrator/main.go
src/app/itn_orchestrator/src/keyloader.go
src/app/itn_orchestrator/src/misc.go
src/app/itn_orchestrator/src/params.go
src/app/itn_orchestrator/src/payments.go
src/app/itn_orchestrator/src/restart.go
src/app/itn_orchestrator/src/slots_allocation.go
src/app/itn_orchestrator/src/slots_won.go
src/app/itn_orchestrator/src/stop.go
src/app/itn_orchestrator/src/zkapp.go

* Implement a generator of long-running experiments to be consumed by ITN orchestrator
* Update Orchestrator to support some new commands
* Change behavior of some existing Orchestrator commands
* Update `fund-keys` command of Mina node to use shorter time pauses, to enable better responsiveness on clusters with smaller slot duration
* Ran experiments on a private cluster
Checklist:

Implement generator of private testing experiments

---

src/app/test_executive/medium_bootstrap.ml
src/lib/integration_test_lib/event_type.ml
src/lib/integration_test_lib/event_type.mli
src/lib/integration_test_lib/intf.ml
src/lib/integration_test_lib/network_state.ml
src/lib/integration_test_lib/wait_condition.ml
src/lib/integration_test_lib/wait_condition.mli
src/lib/transition_frontier/transition_frontier.ml
src/lib/transition_frontier/transition_frontier.mli

New verification for medium-bootstrap regarding bootstrap from already existing storage. For this purpose I've added new structured log and new assertion.
Run medium-bootstrap test with new code
Checklist:
* Closes #6502

persistence test

---

src/lib/crypto/kimchi_bindings/stubs/kimchi_types.ml
src/lib/crypto/kimchi_bindings/stubs/src/plonk_verifier_index.rs
src/lib/gossip_net/any.ml
src/lib/gossip_net/dune
src/lib/gossip_net/fake.ml
src/lib/gossip_net/intf.ml
src/lib/gossip_net/libp2p.ml
src/lib/gossip_net/message.ml
src/lib/mina_lib/mina_lib.ml
src/lib/mina_networking/mina_networking.ml
src/lib/mina_networking/mina_networking.mli
src/lib/network_pool/intf.ml
src/lib/network_pool/network_pool_base.ml
src/lib/network_pool/pool_sink.ml
src/lib/network_pool/snark_pool.ml
src/lib/network_pool/snark_pool_diff.ml
src/lib/network_pool/test.ml
src/lib/network_pool/transaction_pool.ml
src/lib/network_pool/with_nonce.ml
src/lib/pickles/verification_key.ml
src/lib/transaction_inclusion_status/transaction_inclusion_status.ml

Merge berkeley into develop

---

src/lib/crypto/kimchi_backend/gadgets/ec_group.ml
src/lib/crypto/kimchi_backend/gadgets/ecdsa.ml
src/lib/crypto/kimchi_backend/gadgets/foreign_field.ml
src/lib/crypto/kimchi_backend/gadgets/foreign_field.mli

Reverts MinaProtocol/mina#13485

Revert "Extra safety in foreign field arithmetics" from this branch (will be merged to develop directly)

---

helm/cron_jobs/devnet-replayer-cronjob.yaml

Adding this job is meant to reveal whether the archive node fix for bad nonces is working.

Replayer cron job for devnet

---

scripts/mina-local-network/mina-local-network.sh

Fix URI syntax in local net script

---

buildkite/src/Jobs/Release/MinaToolchainArtifact.dhall
helm/cron_jobs/devnet-replayer-cronjob.yaml
src/app/replayer/replayer.ml
src/app/replayer/sql.ml

Allow clean merge of #13600 to `develop`.

Merge 13600 to develop

---

buildkite/src/Jobs/Release/MinaToolchainArtifact.dhall
helm/cron_jobs/devnet-replayer-cronjob.yaml
src/app/replayer/replayer.ml
src/app/replayer/sql.ml

Allow clean merge-to-berkeley for #13600.

Merge 13600 to berkeley

---

helm/cron_jobs/berkeley-replayer-cronjob.yaml

Merge PR to allow clean merge-to-develop for #13838.

Merge 13838 to develop

---

README.md

Added nightly badges to readme

Add nightly badges to Readme.md

---

buildkite/src/Jobs/Lint/Fast.dhall
buildkite/src/Jobs/Lint/Merge.dhall
scripts/merged-to-proof-systems.sh

Fixed lints for system proofs commit ancestor. Currently script takes into consideration lack of base branch setting and default condition

Fix lints for system proofs [berk]

---

docs/README.md

* update the docs readme to remove coda and link to active docs repository
* text changes and link checks
Checklist:
- [x ] Dependency versions are unchanged
- [ x] Document code purpose, how to use it

update README to remove coda and link to docs2

---

src/lib/pickles_types/plonk_types.ml

This PR ports the fix from #13858. This is a breaking change, and as such must be included in the berkeley hard-fork.
Checklist:

[berkeley] Fixup feature flag validation for modified ffmul

---

automation/terraform/monitoring/README.md

Add monitoring and alerting README

---

nix/go.nix
nix/libp2p_helper.json

Fix error in building nix shells.

Nix: Update go dependencies

---

automation/terraform/monitoring/README.md

Porting @barriebyron remarks from berkeley to compatible. I've mistakenly opened two prs: one for compatible one for berkeley. Barries comments were applied to berkeley PR while all code should go into compatible (code will be eventually merged to berkeley in the future, so no need for two Prs) 
Closes #14000

[Alerts readme] Poting review remarks from berkeley

---

src/lib/crypto/kimchi_backend/common/plonk_constraint_system.ml

* Typo fixes from @querolita in https://github.com/MinaProtocol/mina/pull/13939#pullrequestreview-1613817836.
Checklist:
* Closes #0000

Plonk_constraint_system: typo

---

src/lib/pickles_base/dune
src/lib/pickles_base/side_loaded_verification_key.ml
src/lib/pickles_base/test/dune
src/lib/pickles_base/test/main.ml
src/lib/pickles_base/test/test_side_loaded_verification_key.ml

Same as #13707 targeting `develop`

Migrate test in pickles_base to alcotest

---

frontend/ci-build-me/src/index.js

Add !ci-nightly-me command to run nightly jobs on a PR

---

src/lib/pickles_types/dune
src/lib/pickles_types/pcs_batch.ml
src/lib/pickles_types/pcs_batch.mli
src/lib/pickles_types/test/dune
src/lib/pickles_types/test/main.ml
src/lib/pickles_types/test/test_pcs_batch.ml

resolves https://github.com/MinaProtocol/mina/issues/13709

Pickles_types: extract tests into own directory

---

src/lib/pickles_types/opt.ml
src/lib/pickles_types/opt.mli

* Add `Opt.iter`
*
Checklist:
* Closes #0000

Pickles_types: add Opt.iter

---

src/lib/pickles/common.ml
src/lib/pickles/common.mli
src/lib/pickles/compile.ml
src/lib/pickles/composition_types/composition_types.ml
src/lib/pickles/composition_types/composition_types.mli
src/lib/pickles/impls.ml
src/lib/pickles/impls.mli
src/lib/pickles/per_proof_witness.ml
src/lib/pickles/pickles.ml
src/lib/pickles/side_loaded_verification_key.ml
src/lib/pickles/step.ml
src/lib/pickles/step_branch_data.ml
src/lib/pickles/step_main.ml
src/lib/pickles/step_verifier.ml
src/lib/pickles/step_verifier.mli
src/lib/pickles/unfinalized.ml
src/lib/pickles/wrap.ml
src/lib/pickles/wrap_main.ml

This cleans up the newly introduced warnings by the PRs fixing #13482

Fix warning on Pickles

---

buildkite/scripts/rosetta-integration-tests.sh
buildkite/src/Jobs/Test/RosettaIntegrationTests.dhall
genesis_ledgers/berkeley.json

* Make the job work again.
* Run the CI.
The intent is to make this job blocking the CI shortly after this is merged.
Checklist:
* Closes #14028

Fix "Rosetta integration tests" CI job.

---

buildkite/src/Jobs/Test/CoverageTearDown.dhall
buildkite/src/Monorepo.dhall
buildkite/src/Pipeline/JobSpec.dhall
buildkite/src/Pipeline/Mode.dhall
buildkite/src/Pipeline/Stage.dhall
buildkite/src/Prepare.dhall

Introduce coverage gathering - COMP

---

nix/go.nix
nix/libp2p_helper.json

Merge #14109 from berkeley to develop

---

src/app/test_executive/block_production_priority.ml

* Cleaner variable names and strings to understand integration test
* If it compiles, it works

Cleaner names for block production priority

---

src/lib/network_pool/snark_pool_diff.ml

Disable rate limitting for snark works
* Tested on a cluster
Checklist:
* Closes #14141

Disable rate limitting for snark works

---

src/app/test_executive/archive_node_test.ml
src/app/test_executive/block_production_priority.ml
src/app/test_executive/chain_reliability_test.ml
src/app/test_executive/delegation_test.ml
src/app/test_executive/gossip_consistency.ml
src/app/test_executive/medium_bootstrap.ml
src/app/test_executive/payments_test.ml
src/app/test_executive/peers_reliability_test.ml
src/app/test_executive/test_common.ml
src/app/test_executive/test_executive.ml
src/lib/integration_test_cloud_engine/graphql_polling_log_engine.ml
src/lib/integration_test_cloud_engine/kubernetes_network.ml
src/lib/integration_test_cloud_engine/mina_automation.ml
src/lib/integration_test_lib/event_router.ml
src/lib/integration_test_lib/intf.ml
src/lib/integration_test_lib/network_state.ml

changing the names of some functions and variables within lucy for better clarity

Naming changes

---

src/lib/pickles/common.ml
src/lib/pickles/common.mli
src/lib/pickles/step_verifier.ml
src/lib/pickles/wrap_main.mli
src/lib/pickles/wrap_verifier.ml
src/lib/pickles_types/test/main.ml
src/lib/pickles_types/test/test_vector.ml
src/lib/pickles_types/vector.mli

Some suggestions + additional tests.

Suggestions to "Expose chunks in Plonk_verification_evals.t"

---

nix/rust.nix

Update to something that works :-D

Nix: update rust nightly hash

---

src/lib/pickles/README.md

Pickles: fix broken link

---

buildkite/src/Jobs/Test/BerkeleyCompatibility.dhall
buildkite/src/Jobs/Test/DevelopCompatibility.dhall

Tag newly created compatibility jobs with proper tags. This will sort out problem in which they are hanging around when using FastOnly filter

[CI][Fix] tag compatibility jobs

---

src/app/archive/lib/load_data.ml
src/app/archive/lib/processor.ml

Add comments to `Processor` and `Load_data` in `Archive_lib`.
There are no code changes, so making the PR against `berkeley`.

Add docs for Processor, Load_data

---

src/lib/crypto/kimchi_bindings/stubs/pasta_bindings.ml
src/lib/crypto/kimchi_bindings/stubs/src/arkworks/pasta_fp.rs
src/lib/crypto/kimchi_bindings/stubs/src/arkworks/pasta_fq.rs
src/lib/crypto/kimchi_bindings/stubs/src/main.rs

These helpers are essential to my pickles debugging workflow; checking them in here to help with current pickles debugging.
Checklist:

[berkeley] Add crypto debugging helpers

---

src/lib/gossip_net/libp2p.ml
src/lib/o1trace/o1trace.ml
src/lib/pickles/fix_domains.ml
src/lib/pickles/step.ml

This is https://github.com/MinaProtocol/mina/pull/14402 for o1js-main, plus the temporary hack from https://github.com/MinaProtocol/mina/pull/14405 to unblock work with custom gates

[o1js] Reset feature flags before assertion

---

src/lib/pickles/test/optional_custom_gates/test_fix_domains.ml

* Fix https://github.com/MinaProtocol/mina/issues/14567
*
Checklist:
* Closes #0000

Add new tests for fix_domains

---

src/lib/pickles/step_main_inputs.ml
src/lib/pickles/test/main.ml
src/lib/pickles/test/test_sponge.ml
src/lib/pickles/test/test_step.ml

Part of #13711.
This PR has 2 test files since they cover fairly different subjects.

Pickles: use Alcotest for unit tests of module `Step_main_inputs`

---

src/lib/pickles/side_loaded_verification_key.ml
src/lib/pickles/step_main_inputs.ml
src/lib/pickles/test/main.ml
src/lib/pickles/test/test_side_loaded_verification_key.ml
src/lib/pickles/test/test_sponge.ml
src/lib/pickles/test/test_step.ml

Pickles: use Alcotest for unit tests of module `Side_loaded_verification_key`

---

scripts/archive/split_precomputed_log.sh
scripts/mina-local-network/mina-local-network.sh

[Berk] Enabled logging precomputed blocks in mina local network

---

automation/terraform/testnets/ci-net/main.tf
buildkite/scripts/terraform-test.sh
buildkite/src/Jobs/Test/TerraformNetworkTest.dhall

Since we want to remove integration test from Pull request we lost a test of our infra code. This pr introduce isolated test for our helm/terraform tests. Small adjsutments for ci-net testnet was necessary as file is out of date
Checked CI and run locally one lucy test using my terraform files

add ci check for terraform files

---

src/lib/pickles/test/main.ml
src/lib/pickles/test/test_wrap_hack.ml
src/lib/pickles/wrap_hack.ml

Pickles: use Alcotest for unit tests in module Wrap_hack

---

src/lib/pickles/step_verifier.ml
src/lib/pickles/step_verifier.mli
src/lib/pickles/test/main.ml
src/lib/pickles/test/test_step_verifier.ml

Pickles: use Alcotest for unit tests in module `Step_verifier`

---

automation/terraform/modules/kubernetes/testnet/variables.tf
automation/terraform/modules/o1-testnet/files.tf
automation/terraform/modules/o1-testnet/inputs.tf
automation/terraform/modules/o1-testnet/locals.tf
automation/terraform/modules/o1-testnet/scripts.tf
automation/terraform/modules/o1-testnet/testnet.tf
automation/terraform/modules/testworld-logging/README.md
automation/terraform/modules/testworld-logging/main.tf
automation/terraform/modules/testworld-logging/output.tf
automation/terraform/modules/testworld-logging/templates/docker-compose-build.tpl
automation/terraform/modules/testworld-logging/templates/docker-mounts/fe-config.tpl
automation/terraform/modules/testworld-logging/templates/docker-mounts/keys.tpl
automation/terraform/modules/testworld-logging/templates/docker-mounts/names-data.tpl
automation/terraform/modules/testworld-logging/templates/docker-mounts/postgres.tpl
automation/terraform/modules/testworld-logging/templates/docker-script-build.tpl
automation/terraform/modules/testworld-logging/templates/execute-shell.tpl
automation/terraform/modules/testworld-logging/vars.tf
automation/terraform/testnets/berkeley/main.tf
automation/terraform/testnets/ci-net/main.tf
automation/terraform/testnets/testworld-2-0/main.tf
buildkite/scripts/connect-to-berkeley.sh
buildkite/scripts/connect-to-mainnet-on-compatible.sh
buildkite/src/Jobs/Test/TerraformNetworkTest.dhall
helm/block-producer/values.yaml
helm/seed-node/values.yaml

This PR merges is to port the following changes from the `develop` branch, to `berkeley`:
* PR [14576](https://github.com/MinaProtocol/mina/pull/14576): Repair terraform module compatibility
* PR [14647](https://github.com/MinaProtocol/mina/pull/14647): Updated `berkeley` deployment terraform
* PR [14652](https://github.com/MinaProtocol/mina/pull/14652): ITN3 testnet and logging configurations
Additionally, this PR ports over CI test repairs from `rampup`:
* Commit [6a5b112](https://github.com/MinaProtocol/mina/commit/6a5b1123740c72328f4842c71c9c176318b89dfd): Increase test timeout time to accommodate for node needing more time to boot with larger ledger files.  
Finally, a single CI test has been disabled that was failing and blocking this PR from merging into …

Steven merge itn infra berkeley

---

buildkite/scripts/build-artifact.sh
buildkite/src/Jobs/Release/ReceiptChainHashFixArtifact.dhall
dockerfiles/Dockerfile-mina-receipt-chain-hash-fix
scripts/migrate-itn-data.sh
scripts/rebuild-deb.sh
scripts/release-docker.sh

Deploy receipt chain hash fix script in form:
- debian package
- docker image

Deploy mina-receipt-chain-hash-fix

---

src/lib/pickles/test/optional_custom_gates/pickles_test_optional_custom_gates.ml

The `main_runtime_table_cfg` is failing in https://github.com/MinaProtocol/mina/pull/14725 after a minor change, so in this PR it's improved before it's used in https://github.com/MinaProtocol/mina/pull/14725.
The changes are only done to the runtime tables test (the fixed lookups test is just refactored a bit  for readability). Basically, now runtime tables are much more randomized.

Improving the rutime table test

---

scripts/compare_ci_diff_binables.sh
scripts/compare_ci_diff_types.sh

[compatible] Default to compatibility checks being compatible with compatible

---

buildkite/src/Jobs/Test/ConnectToTestworld-2-0.dhall

Soft fail for testworld 2.0 connectivity test

---

src/lib/mina_metrics/prometheus_metrics/dune
src/lib/mina_metrics/prometheus_metrics/mina_metrics.ml

* Handle an error of contacting a metrics server requested by forward URI
* Testing to be done
Checklist:
* Closes #14432

Handle inability to contact metrics server on forwarding

---

automation/package.json

May as well head off any potential  issues.

old package.json: avoid link to scammer site

---

src/app/archive/lib/processor.ml
src/lib/mina_caqti/dune
src/lib/mina_caqti/mina_caqti.ml

[TESTING] add timing logs to various functions

---

src/lib/genesis_ledger_helper/dune
src/lib/genesis_ledger_helper/genesis_ledger_helper.ml

Use the `File_system` module and some inline syntax

chore: small cleanups to genesis_ledger_helper

---

src/lib/pickles_types/test/main.ml
src/lib/pickles_types/test/test_vector.ml
src/lib/pickles_types/vector.mli

Add documentation and add tests.
*
*
Checklist:
* Closes #0000

Pickles: Vector.split - Add documentation and tests.

---

docs/docker.md
docs/specs/consensus/README.md
docs/specs/types_and_structures/serialized_srs.md
docs/tracing.md

Find a few typos while reading the docs. Hope I could be of any help.

chore(docs): proofreading the docs

---

LICENSE

Updating placeholder values for year and copyright owner in LICENSE to 2024, Mina Foundation.

Update LICENSE year and copyright owner

---

src/app/archive/add_indexes.sql

Migration was wrong, need to add unique trait to the index
* Tested by archive node operators and Dariusz, before the fix there was a blocking issue for archive nodes
Checklist:
* Closes #14865

Fix migration file add_indexes.sql

---

src/app/ledger_export_bench/README.md
src/app/ledger_export_bench/dune
src/app/ledger_export_bench/ledger_export_benchmark.ml
src/app/test_executive/hard_fork.ml
src/lib/genesis_ledger_helper/lib/genesis_ledger_helper_lib.ml
src/lib/mina_graphql/dune
src/lib/mina_graphql/mina_graphql.ml
src/lib/runtime_config/dune
src/lib/runtime_config/runtime_config.ml

PR versions:
* `compatible`: #14266
* `berkeley`: #14864
* `develop`: #14868
* This PR is to remove conflicts #14266 has with `berkeley`, so that the original PR could get in.
* CI
Checklist:

Improve fork config generation develop

---

src/lib/o1trace/o1trace.ml

Reverts #14397, closes #14694.

[rampup] Revert  #14397

---

src/lib/mina_stdlib/deferred.ml
src/lib/mina_stdlib/deferred.mli
src/lib/mina_stdlib/dune
src/lib/mina_stdlib/list.ml
src/lib/mina_stdlib/list.mli
src/lib/mina_stdlib/nonempty_list.ml
src/lib/mina_stdlib/nonempty_list.mli
src/lib/mina_stdlib/result.ml
src/lib/mina_stdlib/result.mli
src/lib/mina_stdlib/sigs.mli

These functions keep being recreated in PRs against compatible. Lets just import the stdlib.

Add Mina_stdlib

---

src/app/rosetta/docker-start.sh
src/app/rosetta/init-db.sh
src/app/rosetta/lib/block.ml
src/app/rosetta/lib/network.ml
src/app/rosetta/rosetta-cli-config/README.md
src/app/rosetta/rosetta-cli-config/config.json
src/app/rosetta/rosetta-cli-config/mina-no-delegation-test.ros
src/app/rosetta/rosetta-cli-config/mina-with-return-funds.ros

Merge Rosetta fixes from rampup into berkeley.

Merge rampup into berkeley

---

src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
src/lib/mina_lib/tests/tests.ml
src/lib/trust_system/peer_trust.ml
src/lib/trust_system/peer_trust.mli

This PR revives #14982, which was merged into a PR train in error.

 Remove the trust system DB if it is corrupted

---

scripts/prepare-test-ledger.sh

Just a merge, no conflicts arose (git merged automatically)
Checklist:
* Closes #0000

Merge rampup to berkeley (30 jan 2024)

---

scripts/prepare-test-ledger.sh
src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
src/app/replayer/replayer.ml
src/lib/cache_dir/cache_dir.mli
src/lib/cache_dir/native/cache_dir.ml
src/lib/genesis_ledger_helper/dune
src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
src/lib/integration_test_cloud_engine/mina_automation.ml
src/lib/integration_test_local_engine/mina_docker.ml
src/lib/mina_lib/tests/tests.ml
src/lib/runtime_config/runtime_config.ml
src/lib/transaction_snark/test/ring_sig.ml
src/lib/trust_system/peer_trust.ml
src/lib/trust_system/peer_trust.mli

Merge performed automatically with git, no conflicts.
Checklist:
* Closes #0000

Merge berkeley to develop (30 Jan 2024)

---

buildkite/scripts/test-nix.sh
buildkite/src/Jobs/Test/NixBuildTest.dhall

[develop] Fix nix CI test issue with directory ownership

---

helm/cron_jobs/berkeley-migration-phase-1-cronjob/files/migration-phase-1.sh
helm/cron_jobs/berkeley-migration-phase-2-cronjob/files/migration-phase-2.sh
src/app/archive/lib/processor.ml
src/app/archive/lib/test.ml

Small adjustments to migration jobs and fix for replayer

minor compilation fixes & fixing replayer

---

src/lib/mina_lib/mina_lib.ml

prevent more restarts when is_seed

---

src/lib/mina_graphql/mina_graphql.ml
src/lib/runtime_config/runtime_config.ml

This PR builds upon https://github.com/MinaProtocol/mina/pull/15107, allowing us to update compatible without unnecessary changes to the rampup branch.
This PR is a combination of #15077 and a backport of #15094. This PR will be merged into #15094 in due course.

Fix fork_config graphql logic

---

graphql_schema.json
src/lib/mina_graphql/mina_graphql.ml

This PR builds on #15109 as part of a PR chain.
This is a backport of https://github.com/MinaProtocol/mina/pull/15104, and will be merged into there in due course.
Closes https://github.com/MinaProtocol/mina/issues/15096

[compatible] Select the correct block for the fork config export

---

buildkite/src/Command/TestExecutive.dhall

attempt at repairing CI

---

src/lib/transaction/transaction_hash.mli

o1js: https://github.com/o1-labs/o1js/pull/1422

Expose `hash_zkapp_command`

---

src/lib/transition_router/transition_router.ml

Makes some scripts slightly quicker.

Skip 60s sleep when is_seed

---

src/app/replayer/replayer.ml

This PR makes the replayer load the ledger properly if it's specified as a hash value.
*
Checklist:
* Closes #0000

let replayer to load genesis ledger

---

buildkite/scripts/build-hardfork-package.sh

public-read acl for the uploaded ledgers

---

dockerfiles/Dockerfile-mina-rosetta
src/app/rosetta/README.md
src/app/rosetta/docker-berkeley-start.sh
src/app/rosetta/docker-compose/docker-compose.yml
src/app/rosetta/docker-compose/example.env
src/app/rosetta/docker-demo-start.sh
src/app/rosetta/docker-devnet-start.sh
src/app/rosetta/docker-start.sh
src/app/rosetta/init-db.sh

This pull request includes updates to the Rosetta Docker image and scripts and documentation. It refactors the start scripts, adds an example Docker Compose file, and updates the Rosetta README. PostgreSQL version was upgraded to 15 and a missing binary was added in the Rosetta Docker image.

[Rosetta] Update Docker image and scripts and documentation

---

src/app/rosetta/lib/block.ml

This pull request fixes the treatment of the genesis block. Previous implementation assumed the genesis block was the first block of the chain, which is not the case anymore after hard-fork. The issue was related to the handling of the parent block and the validation of the block's identifier. This implementation now handles the genesis block the same way as any other block and sets the parent block of a block with not `parent_block_id` as itself.

Fix genesis block treatment

---

buildkite/scripts/unit-test.sh

This PR is an alternative to https://github.com/MinaProtocol/mina/pull/15299. I prefer to outright revert the bad PR https://github.com/MinaProtocol/mina/pull/13673, since I also don't agree with the principle.

Put unit tests back as they should be

---

buildkite/scripts/build-artifact.sh
scripts/deb-builder-helpers.sh
src/app/berkeley_migration_verifier/Readme.md
src/app/berkeley_migration_verifier/berkeley_migration_verifier.ml
src/app/berkeley_migration_verifier/dune
src/app/berkeley_migration_verifier/sql.ml
src/dune-project

Introduced berkeley_migration_verifier app, which automates checks for archive migration after during and before fork. Please see readme for more details

Berkeley archive migration verifier

---

src/app/replayer/replayer.ml

Porting to develop https://github.com/MinaProtocol/mina/pull/15302

[Develop] Port Replayer: convert global slots to avoid to hashes in order to support devnet

---

buildkite/src/Jobs/Test/TestnetIntegrationTests.dhall
buildkite/src/Pipeline/Filter.dhall
src/app/replayer/replayer.ml

Fixed issues with replayer compilation after applying review suggestion. It turns out also that some jobs were not triggered on such change while they should

Replayer fix for applied suggesion and job triage 

---

src/app/replayer/replayer.ml

This PR modifies the replayer to ignore the nonce check in balances table
*
Checklist:
* Closes #0000

ignore nonce check in balances table

---

nix/ocaml.nix

Merge `berkeley` -> `develop` (no conflicts)
Checklist:

Merge berkeley to develop (mar19 2024)

---

buildkite/scripts/build-hardfork-package.sh
src/app/archive/patch_migrated_db.sql
src/app/berkeley_migration/berkeley_migration.ml
src/config/berkeley_archive_migration.mlh
src/config/protocol_version/current.mlh
src/config/protocol_version/version1.mlh
src/config/protocol_version/version2.mlh

it should have always been like this on berkeley

txn version 2->3

---

src/app/berkeley_migration_verifier/berkeley_migration_verifier.ml
src/app/berkeley_migration_verifier/sql.ml

This PR adds the check for `accounts_created` table to berkeley_migration_verifier
*
Checklist:
* Closes #0000

Berkeley migration verifier/check accounts_created

---

scripts/archive/missing-blocks-guardian.sh

Porting new missing guardian script #15384

port new missing block guardian script dev

---

buildkite/src/Constants/DebianChannel.dhall

dhall/PromotePackage: acknowledge Devnet

---

scripts/archive/migration/mina-berkeley-migration-script

Fix the bug in mina-berkeley-migration-script
*
Checklist:
* Closes #0000

fix the incremental migration

---

buildkite/src/Jobs/Release/MinaArtifactMigrationBuster.dhall

Added new archive migration debian and docker for buster codename

Added support for buster in archive migration

---

buildkite/src/Jobs/Release/MinaArtifactMigrationBuster.dhall
scripts/archive/migration/mina-berkeley-migration-script

Just merge (mo conflicts)
Checklist:

Berkeley to develop (April 03, 2024)

---

src/config/devnet.mlh

Tentative devnet HF stop slots for April 9th 2024 9 am UTC
Checklist:
* Closes #0000

Devnet HF stop slots

---

src/lib/mina_graphql/mina_graphql.ml

Simple renaming of variable to avoid confusion.
*
Checklist:
* Closes #0000

target_height -> txn_stop_slot

---

src/lib/mina_graphql/mina_graphql.ml

renaming to avoid confusion
*
Checklist:
* Closes #0000

[develop] target_height -> txn_stop_slot

---

scripts/archive/missing-blocks-guardian.sh

* Added check for MINA_NETWORK
* Added check for exit codes of missing-blocks-auditor
* Changed newline printing
* Tested each change on the command line individually
* Made the script crash with a broken DB and checked results
Checklist:

Improve and fix loging of missing-blocks-guardian

---

scripts/archive/migration/README.md

Small package of fixes for README.md for berkeley migration

Fix grammar for berkeley migration Readme.dm

---

buildkite/src/Jobs/Test/SingleNodeTest.dhall
scripts/archive/migration/mina-berkeley-migration-script
src/app/berkeley_migration/berkeley_migration.ml
src/app/berkeley_migration/precomputed_block.ml

Port Expose chechkpoint_output_path and precomputed blocks local path do develop

---

src/lib/mina_graphql/mina_graphql.ml

**Important** :warning: use of global slot since genesis is replaced with the use of genesis slot since hardfork.
* Use slot_tx_end_or_default in fork_config Graphql
Checklist:

Use slot_tx_end_or_default in fork_config Graphql

---

dune
src/config/dune

Simplify src/config/dune with use of built-in dune functionality. Plus minor change for root-based dune file
Checklist:

Simplify `src/config/dune`, `dune` files

---

scripts/archive/missing-blocks-guardian.sh

* The logging logic was faulty so some arrangements needed to be done.
* Executed each command on the command line
Checklist:

Fix missing-blocks-guardian logging

---

buildkite/scripts/export-git-env-vars.sh
dockerfiles/scripts/daemon-entrypoint.sh
scripts/archive/migration/mina-berkeley-migration-script
scripts/release-docker.sh
src/app/berkeley_migration/berkeley_migration.ml
src/app/berkeley_migration/precomputed_block.ml
src/lib/exit_handlers/exit_handlers.ml
src/lib/mina_graphql/mina_graphql.ml
src/lib/mina_lib/conf_dir.ml

Port expose_precomputed_and_checkpoint_output folders to develop

---

scripts/archive/missing-blocks-guardian.sh
src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml

Merge berkeley to develop apr17 2024

---

scripts/archive/missing-blocks-guardian.sh
src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml

Just a merge
Also includes a warning fix (that should have happened in one of previous merges)

Merge compatible to berkeley apr17 2024

---

src/app/archive/lib/processor.ml

resolve conflict in the #15541
*
Checklist:
* Closes #0000

[develop] update parent_id at the very last

---

src/app/cli/src/init/mina_run.ml

Use only git commit
Checklist:

Remove git branch from summary

---

src/app/archive/lib/processor.ml
src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml

Print only git commit
Checklist:

Do not log verbose git info on startup

---

src/lib/internal_tracing/internal_tracing.ml

Use only git commit
Checklist:

Omit branch in internal tracing

---

buildkite/src/Constants/DebianChannel.dhall

New `umt-mainnet` channel for umt test with mainnet signatures event

New UmtMainnet channel variant

---

buildkite/src/Command/MinaArtifact.dhall
scripts/deb-builder-helpers.sh
scripts/mina-verify-packaged-fork-config

Fix verification of fork package.
Develop version: #15599
Checklist:
* Closes #15577

Fix verification in dry runs: alternative take

---

buildkite/scripts/build-hardfork-package.sh

print out s3 data hash after we search in s3 bucket
*
Checklist:
* Closes #0000

print out the s3 data hash later

---

buildkite/scripts/promote-docker.sh
buildkite/src/Command/PromotePackage.dhall
buildkite/src/Constants/Artifacts.dhall
buildkite/src/Entrypoints/PromotePackage.dhall

Add mechanism to remove profile from docker as well

[Promote job] remove profile from docker

---

src/app/print_blockchain_snark_vk/dune
src/lib/crypto/kimchi_bindings/dune
src/lib/crypto/kimchi_bindings/js/node_js/dune
src/lib/crypto/kimchi_bindings/js/web/dune
src/lib/crypto/kimchi_bindings/stubs/dune
src/lib/generated_graphql_queries/dune

Explicitly mention a few implicit file dependencies in dune files.
Also contains some changes to how bash scripts are called from Dune (via explicit Bash call), this simplifies usage in nix wrapping and seems to do no harm to default flow.
* Mina compiles
Checklist:

Mention some file dependencies of dune files explicitly

---

src/app/ledger_export_bench/ledger_export_benchmark.ml

Fix the warning
* App compiles
Checklist:

Fix warning in ledger_export_bench

---

buildkite/scripts/debian/install.sh
buildkite/scripts/debian/start_local_repo.sh
buildkite/src/Command/DockerImage.dhall
scripts/publish-deb.sh

Fix for my recent push which undercover new issues (lock when publishing debians is still a problem) + aptly need to be installed silently

[DEV] Install aptly silently & retry publishing

---

buildkite/src/Constants/ContainerImages.dhall
opam.export
src/app/rosetta/.ocamlformat
src/app/rosetta/indexer_test/dune
src/app/rosetta/indexer_test/indexer_test.ml
src/app/rosetta/lib/account.ml
src/app/rosetta/lib/block.ml
src/app/rosetta/lib/commands_common.ml
src/app/rosetta/lib/dune
src/app/rosetta/lib/rosetta.ml
src/app/rosetta/lib/search.ml
src/app/rosetta/ocaml-signer/signer.ml
src/app/rosetta/ocaml-signer/signer_cli.ml
src/app/rosetta/ocaml-signer/signer_mainnet_signatures.ml
src/app/rosetta/ocaml-signer/signer_testnet_signatures.ml
src/lib/rosetta_lib/operation_statuses.ml
src/lib/rosetta_lib/operation_types.ml

[develop] Add indexer feature to Rosetta

---

scripts/archive/migration/mina-berkeley-migration-script

Fix final migration part
I did an end to end test on a vm
Checklist:
* Closes #0000

fix `find_most_recent_checkpoint`

---

buildkite/src/Jobs/Test/EmergencyHfTest.dhall
scripts/archive/emergency_hf/convert_chain_to_canonical.sh
scripts/archive/emergency_hf/test/runner.sh
scripts/archive/emergency_hf/test/test_fork_on_canonical_in_the_middle.sql
scripts/archive/emergency_hf/test/test_fork_on_last_canonical.sql
scripts/archive/emergency_hf/test/test_fork_on_new_network.sql
scripts/archive/emergency_hf/test/test_fork_on_orphaned.sql
scripts/archive/emergency_hf/test/test_fork_on_pending.sql
scripts/archive/emergency_hf/test/test_surrounded_by_pendings.sql
scripts/archive/migration/berkeley_migration.sh
src/lib/genesis_ledger_helper/genesis_ledger_helper.ml

fix the merge conflict in #15659
*
Checklist:
* Closes #0000

Fix tarball develop

---

docs/upgrading-to-berkeley.md

adding a reminder that this needs to be run as root right now

adding root reminder

---

buildkite/src/Command/TestExecutive.dhall

This PR merges master to berkeley, the final step before landing the `berkeley` branch as `master` for the berkeley upgrade.

Merge master to berkeley

---

buildkite/scripts/export-git-env-vars.sh

This is autogenerated Pull Request for porting #15754 to develop

[Merge Conflict Fix] port 'Properly use MINA_BUILD_MAINNET flag' to develop

---

buildkite/scripts/export-git-env-vars.sh
buildkite/src/Jobs/Lint/Merge.dhall
scripts/deb-builder-helpers.sh

This is autogenerated Pull Request for porting #15772 to develop

[Merge Conflict Fix] port Master nightly CI fix  to develop

---

buildkite/scripts/export-git-env-vars.sh
buildkite/src/Jobs/Lint/Merge.dhall
scripts/deb-builder-helpers.sh

Another fix in build debian script. Added suggested deps for mina-devnet

Master nightly CI fix 

---

src/lib/pickles/plonk_checks/dune

This follows the convention used elsewhere in the codebase.
* Mina project builds successfully
Checklist:

Use explicit gen_scalars.exe dependency

---

buildkite/src/Jobs/Test/RosettaIntegrationTests.dhall
src/app/rosetta/indexer_test/indexer_test.ml

[Rosetta] Fix indexer integration test in develop

---

buildkite/src/Command/DockerImage.dhall
buildkite/src/Command/HardforkPackageGeneration.dhall
buildkite/src/Command/MinaArtifact.dhall
buildkite/src/Jobs/Release/ItnOrchestratorArtifact.dhall
scripts/release-docker.sh

Fixed docker suffixes. Added profile to daemon tag and added check not to allow override docker tag.

Add suffix to lightnet docker tag

---

README.md

Port https://github.com/MinaProtocol/mina/pull/15889 to develop

[Develop] Update badges and logo

---

src/app/cli/src/init/client.ml

Fix `compile-time-constants` command

---

src/lib/crypto/kimchi_backend/common/dune
src/lib/crypto/kimchi_backend/dune
src/lib/mina_base/account_update.ml
src/lib/mina_wire_types/snark_params.ml
src/lib/snark_params/snark_params.ml

same as #15723 but for compatible

unifying snarky backend serializers

---

.gitignore
Makefile
dune
scripts/update-opam-switch.sh

Port of #15953 Maintain concurrent switches locally to `compatible`

[Compatible] Maintain concurrent switches locally

---

src/app/replayer/replayer.ml
src/lib/cli_lib/flag.ml
src/lib/cli_lib/flag.mli
src/lib/logger/file_system/logger_file_system.ml
src/lib/logger/file_system/logger_file_system.mli

Port https://github.com/MinaProtocol/mina/pull/15961 to develop

Port CI changes from 3.0.1 to develop

---

buildkite/scripts/build-hardfork-package.sh
buildkite/src/Command/DockerImage.dhall
buildkite/src/Command/HardforkPackageGeneration.dhall
buildkite/src/Command/MinaArtifact.dhall
buildkite/src/Command/ReplayerTest.dhall
buildkite/src/Command/RunWithPostgres.dhall
buildkite/src/Constants/Artifacts.dhall
buildkite/src/Constants/DockerVersions.dhall
buildkite/src/Jobs/Test/ConnectToBerkeley.dhall
buildkite/src/Jobs/Test/ReplayerTest.dhall
buildkite/src/Jobs/Test/RosettaIntegrationTests.dhall
buildkite/src/Jobs/Test/RosettaIntegrationTestsLong.dhall
buildkite/src/Jobs/Test/TestnetIntegrationTests.dhall
buildkite/src/Jobs/Test/TestnetIntegrationTestsLong.dhall
genesis_ledgers/devnet.json
genesis_ledgers/mainnet.json
scripts/mina-verify-packaged-fork-config
scripts/publish-pvkeys.sh
scripts/release-docker.sh
scripts/upload-genesis.sh
src/app/replayer/replayer.ml
src/lib/cache_dir/fake/cache_dir.ml
src/lib/cache_dir/native/cache_dir.ml
src/lib/cli_lib/flag.ml
src/lib/cli_lib/flag.mli
src/lib/logger/file_system/logger_file_system.ml
src/lib/logger/file_system/logger_file_system.mli
src/lib/rosetta_lib/transaction.ml

Port https://github.com/MinaProtocol/mina/pull/15961 to compatible

Port CI changes from release 3.0.1 to compatible

---

buildkite/src/Jobs/Test/TestnetIntegrationTests.dhall

Port https://github.com/MinaProtocol/mina/pull/16016 to develop

Port compatible ci fix to develop

---

buildkite/scripts/unit-test.sh

* Reduced Dune's simultaneous compilations 50%
* This measure aims at increasing stability in highly resource-constrained environments, such as our CI.
* PR run

Adjusting Dune's simultaneous compilations to new Infra

---

src/lib/ledger_catchup/normal_catchup.ml
src/lib/ledger_catchup/super_catchup.ml
src/lib/transition_handler/validator.ml

refactor transition handler validator

---

src/app/cli/src/init/client.ml

Slightly reorganize ledger-related test commands for greater clarity.
Checklist:

Add command subgroup 'mina ledger test'

---

buildkite/scripts/build-release.sh
buildkite/scripts/export-git-env-vars.sh
scripts/debian/build.sh
scripts/export-git-env-vars.sh

Porting https://github.com/MinaProtocol/mina/pull/16050

Porting HEAD issue fix to compatible

---

buildkite/scripts/export-git-env-vars.sh
buildkite/scripts/run-test-executive-local.sh
scripts/export-git-env-vars.sh

Porting https://github.com/MinaProtocol/mina/pull/16062 to compatible

Fix debian branch name calculation

---

src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml

adding back the limit verifier flag as an auxiliary to the bit-catchup work

adding limit flag to verifier

---

src/lib/crypto/kimchi_bindings/stubs/Cargo.lock
src/lib/crypto/kimchi_bindings/wasm/Cargo.lock

This PR corresponds to proof-system's PR: https://github.com/o1-labs/proof-systems/pull/2561 (which hopefully does not change much).

Update proof-systems to use single cargo lock dependencies

---

scripts/debian/build.sh

port https://github.com/MinaProtocol/mina/pull/16087 to compatible

Port head fix to compatible

---

src/lib/crypto/kimchi_bindings/stubs/README.md

Only for readability
*
*
Checklist:
* Closes #0000

[no-op] README: simple reformat at 80 characters limit + del trailing wspace

---

src/lib/crypto/kimchi_bindings/stubs/README.md

Only for readability.
Reapply #16122
On top of #16140
*
*
Checklist:
* Closes #0000

README: simple reformat at 80 characters limit + del trailing wspace

---

src/lib/cli_lib/arg_type.ml
src/lib/work_selector/random_offset.ml

This PR addresses @mrmr1993 comments on the random offset work selection PR (https://github.com/MinaProtocol/mina/pull/15981#discussion_r1757608130 & https://github.com/MinaProtocol/mina/pull/15981#discussion_r1757610675)

Nit: follow-up on random offset PR

---

buildkite/scripts/rosetta-integration-tests.sh

Fixes Rosetta CI integration test.

Rosetta CI fix

---

scripts/prepare-test-ledger-hf-dryrun.sh
scripts/prepare-test-ledger.sh
src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml
src/lib/runtime_config/dune
src/lib/runtime_config/runtime_config.ml

Update some scripts and `runtime_genesis_ledger` to be able to generate a runtime configuration for a custom testnet cluster.
* Followed the [steps ](https://gist.github.com/georgeee/e7af96231cff67add8cd30667979627e) to generate a runtime config with a custom genesis
Checklist:

Fix tooling to generate a test ledger

---

buildkite/src/Command/FuzzyZkappTest.dhall
buildkite/src/Constants/Profiles.dhall
buildkite/src/Jobs/Test/FuzzyZkappTestQuick.dhall

port https://github.com/MinaProtocol/mina/pull/16178 to compatible

[comp] split Fuzzy zkapp tests into two: quick and long

---

buildkite/src/Command/FuzzyZkappTest.dhall
buildkite/src/Constants/Profiles.dhall
buildkite/src/Jobs/Test/FuzzyZkappTestQuick.dhall

Port https://github.com/MinaProtocol/mina/pull/16178 to develop

[Dev] split Fuzzy zkapp tests into two: quick and long

---

buildkite/src/Command/MinaArtifact.dhall
buildkite/src/Jobs/Test/RosettaIntegrationTests.dhall
buildkite/src/Jobs/Test/RosettaIntegrationTestsLong.dhall
scripts/debian/build.sh

Porting PR: https://github.com/MinaProtocol/mina/pull/16156  from compatible allowing to build rosetta mainnet

Build rosetta mainnet/devnet docker

---

src/lib/mina_graphql/mina_graphql.ml
src/lib/mina_lib/mina_lib.ml
src/lib/work_selector/intf.ml
src/lib/work_selector/random.ml
src/lib/work_selector/random_offset.ml
src/lib/work_selector/sequence.ml
src/lib/work_selector/test.ml
src/lib/work_selector/work_lib.ml
src/lib/work_selector/work_selector.ml
src/lib/work_selector/work_selector.mli

This PR cleans up Work_selector a bit, by gathering function & simplifying functors.

Work_selector: small cleanup

---

scripts/publish-deb.sh

Correctly limiting debian  packages checks. Failing build if not found

Limit publishing deb attempts

---

src/lib/block_producer/block_producer.ml

This PR correspond to the first commits of [this PR](https://github.com/MinaProtocol/mina/pull/16181)

Block_producer: move code outside of run

---

src/lib/mina_block/block.ml
src/lib/mina_block/block.mli

A trivial PR that removes a function that isn't used anywhere.
Checklist:

Remove unused Mina_block.payments function

---

README.md

Port https://github.com/MinaProtocol/mina/pull/15889 to compatible

Port update badges and new README.md

---

scripts/mina-local-network/memory_monitor.py

Helpful script to monitor memory usage for all mina processes and subprocesses (verifier/prover) spawned under mina local network script

Memory monitor script for local network

---

scripts/snark_transaction_profiler.py

port https://github.com/MinaProtocol/mina/pull/16165 to develop

[DEV] Fail the build on error match in output

---

buildkite/scripts/debian/promote.sh
buildkite/scripts/promote-docker.sh
buildkite/src/README.md
dockerfiles/Dockerfile-mina-daemon
helm/cron_jobs/README.md
scripts/debian/publish.sh
scripts/debian/reversion.sh
src/app/rosetta/README.md

Port https://github.com/MinaProtocol/mina/pull/16311 to develop

[DEV] Remove berkeley reference from various docs and guides

---

README.md
buildkite/scripts/build-release.sh
buildkite/scripts/debian/promote.sh
buildkite/scripts/promote-docker.sh
buildkite/src/README.md
dockerfiles/Dockerfile-mina-daemon
helm/cron_jobs/README.md
scripts/debian/aptly.sh
scripts/debian/publish.sh
scripts/debian/reversion.sh
src/app/rosetta/README.md

Removes all berkeley codename mentions in docs

Remove berkeley reference from various docs and guides

---

buildkite/src/Jobs/Lint/Xrefcheck.dhall

Fix issues with markdown

---

buildkite/scripts/setup-database-for-archive-node.sh
buildkite/src/Jobs/Test/ArchiveNodeUnitTest.dhall

Another issue after updating toolchain image, which cause that port for postgres changed. Porting fix from compatible to fix it once for all

Fix nightly by porting compatible fix for ArchiveNodeUnitTests.dhall

---

buildkite/scripts/build-release.sh
buildkite/scripts/debian/promote.sh
buildkite/scripts/promote-docker.sh
buildkite/scripts/setup-database-for-archive-node.sh
buildkite/src/Jobs/Lint/Merge.dhall
buildkite/src/Jobs/Lint/Rust.dhall
buildkite/src/Jobs/Lint/ValidationService.dhall
buildkite/src/Jobs/Lint/Xrefcheck.dhall
buildkite/src/README.md
dockerfiles/Dockerfile-mina-daemon
helm/cron_jobs/README.md
scripts/debian/aptly.sh
scripts/debian/builder-helpers.sh
scripts/debian/publish.sh
scripts/debian/reversion.sh
src/app/rosetta/README.md

merge master to compatible 15 11 24

---

buildkite/scripts/debian/install.sh
buildkite/scripts/tests/ledger_test_apply.sh
buildkite/src/Jobs/Test/LedgerTestApplyTx.dhall
scripts/tests/ledger_test_apply.sh
src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml

porting https://github.com/MinaProtocol/mina/pull/16236 to develop

implement test ledger apply dev

---

README-dev.md

This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected `mina-devet` to `mina-devnet`
Please review the changes and let me know if any additional changes are needed.

fix: typos in documentation files

---

src/app/zkapps_examples/tokens/zkapps_tokens.ml
src/app/zkapps_examples/zkapps_examples.ml
src/lib/blockchain_snark/blockchain_snark_state.ml
src/lib/mina_base/account.ml
src/lib/mina_base/account_update.ml
src/lib/mina_base/data_as_hash.ml
src/lib/mina_base/data_as_hash.mli
src/lib/mina_base/prover_value.ml
src/lib/pickles/compile.ml
src/lib/pickles/inductive_rule.ml
src/lib/pickles/inductive_rule.mli
src/lib/pickles/pickles.ml
src/lib/pickles/pickles_intf.mli
src/lib/pickles/step_main.ml
src/lib/pickles/test/chunked_circuits/chunks2.ml
src/lib/transaction_snark/test/multisig_account/multisig_account.ml
src/lib/transaction_snark/test/util.ml
src/lib/transaction_snark/transaction_snark.ml

This PR updates the Mina repo for the interface simplifications in https://github.com/o1-labs/snarky/pull/850. This PR is a no-op.

Update code for simplified snarky interface

---

src/lib/pickles/scalar_challenge.mli

Simple comment as I'm going through protocol code. There might be more small coming.
*
*
Checklist:
* Closes #0000

[trivial] Pickles: document to_field_checked'

---

src/lib/pickles/scalar_challenge.ml

Cleaning a bit letfovers/commented code. More probably coming.
*
*
Checklist:
* Closes #0000

[trivial] Pickles/scalar_challenge: remove old comment

---

scripts/check-snarky-submodule.sh

We do not use the other branches.

CI: snarky - only checking against master

---

src/app/rosetta/lib/search.ml

Rosetta - indexer test is failing on internal commands search method. This PR reverts part of the code which was removed during refactoring

Fix indexer test

---

src/lib/crypto/kimchi_bindings/wasm/src/arkworks/bigint_256.rs
src/lib/crypto/kimchi_bindings/wasm/src/pasta_fp_plonk_index.rs
src/lib/crypto/kimchi_bindings/wasm/src/pasta_fq_plonk_index.rs
src/lib/crypto/kimchi_bindings/wasm/src/plonk_verifier_index.rs
src/lib/crypto/kimchi_bindings/wasm/src/poseidon.rs
src/lib/crypto/kimchi_bindings/wasm/src/srs.rs

Chery-picking from https://github.com/MinaProtocol/mina/pull/16464/

[Trivial] Kimchi-bindings/wasm: make clippy a bit happier

---

src/lib/crypto/kimchi_bindings/stubs/src/lagrange_basis.rs

Cherry-picking from https://github.com/MinaProtocol/mina/pull/16464/

[Trivial] kimchi-bindings/stubs: make clippy happier

---

src/lib/integration_test_lib/test_config.ml

[DEV] reset fork config (in case there is magic config file with fork defined)

---

src/lib/network_pool/indexed_pool.ml

porting https://github.com/MinaProtocol/mina/pull/16514 to develop

port merge of release/3.0.3.1 to develop

---

src/lib/network_pool/indexed_pool.ml

merge release branch to master

merge Release/3.0.3.1 to master

---

buildkite/scripts/bench/run.sh
scripts/benchmarks/__main__.py
scripts/benchmarks/lib/influx.py

Housekeeping changes after the initial version. Fix typo in a compatible branch name, preventing from uploading data to influxdb. Fixing properly the uploading values setup (handling lack of Https:// in influx env var host. I also added some debug printout

Benchmarks - fix upload on compatible branch

---

src/lib/disk_cache/filesystem/disk_cache.ml
src/lib/disk_cache/filesystem/dune
src/lib/disk_cache/identity/disk_cache.ml
src/lib/disk_cache/identity/dune
src/lib/disk_cache/test_lib/disk_cache_test_lib.ml
src/lib/disk_cache/test_lib/dune
src/lib/disk_cache/utils.ml

Next step towards proof cache implementation. Adding disk cache test  functor and provide mock implementation for now

[Proof cache] disk cache - introduce test lib

---

buildkite/scripts/connect/connect-to-network.sh

Enhanced connectivity test with additional check for verifying that deamon is connected to proper network, by validating graphql response.
Also make shell checks happy for this script

add additional quick check for network

---

src/lib/mina_lib/mina_lib.ml

We currently poll every 20 ms to check whether we have received the 'new top block' before we fetch the completed snark work. While the polling interval may be appropriate, a torrent of log messages every 20 ms is not. This changes the logging to occur every ~10 s, determined by the number of iterations rather than explicit wall-clock time.

Log WAITING spam less frequently, only log when we are waiting

---

src/lib/pickles/dune
src/lib/transaction_snark/test/README.md
src/lib/transaction_snark/transaction_snark_intf.ml

This PR includes the small changes from the (already approved) PRs https://github.com/MinaProtocol/mina/pull/16428, https://github.com/MinaProtocol/mina/pull/16430, and https://github.com/MinaProtocol/mina/pull/16431.

Small tidy-ups of Transaction_snark and Pickles

---

nix/misc.nix

remove obsolete validation service from nix

remove validation service from nix

---

buildkite/scripts/debian/promote.sh
buildkite/scripts/run_promote_build_job.sh
buildkite/scripts/run_verify_promoted_build_job.sh
buildkite/src/Command/Promotion/PromotePackages.dhall
buildkite/src/Command/Promotion/VerifyDebian.dhall
buildkite/src/Command/Promotion/VerifyPackages.dhall
buildkite/src/Entrypoints/PromotePackage.dhall
scripts/debian/reversion.sh
scripts/debian/verify.sh

porting https://github.com/MinaProtocol/mina/pull/16622 to compatible

[COMP] Port fixing promotion job

---

scripts/debian/reversion.sh
scripts/docker/verify.sh

PR which fixes two small nits discovered during development for other improvements. Rename env vars to uppercase and set new_repo based on source (REPO) not by suite.

[Promotion] fix two small nits

---

buildkite/src/Jobs/TearDown/PublishDebians.dhall

porting https://github.com/MinaProtocol/mina/pull/16641 to develop

[CI][Develop] Disable publishing debians on nightly

---

src/lib/mina_intf/transition_frontier_components_intf.ml

Removes some unused code.
Checklist:

Remove dead code

---

src/lib/ledger_proof/ledger_proof.ml
src/lib/ledger_proof/ledger_proof.mli
src/lib/ledger_proof/ledger_proof_intf.ml

These functions are needed for the follow-up work.
_Step toward #16582_
Checklist:

Add functions in Ledger_proof.Cached

---

buildkite/scripts/bench/run.sh
buildkite/src/Jobs/Bench/PersistentFrontierStable.dhall
buildkite/src/Jobs/Bench/PersistentFrontierUnstable.dhall
scripts/benchmarks/__main__.py
scripts/benchmarks/lib/bench.py
scripts/benchmarks/requirements.txt
src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
src/app/cli/src/init/test_persistent_frontier.ml

Implement persistent-frontier benchmark in CI

[CI] run test in CI 

---

src/dune-project
src/lib/mina_lib/mina_lib.ml
src/lib/mina_lib/tests/tests.ml
src/lib/network_pool/dune
src/lib/network_pool/intf.ml
src/lib/network_pool/transaction_pool.ml
src/lib/transaction_inclusion_status/transaction_inclusion_status.ml
src/lib/zkapp_vk_cache_tag/dune
src/lib/zkapp_vk_cache_tag/zkapp_vk_cache_tag.ml
src/lib/zkapp_vk_cache_tag/zkapp_vk_cache_tag.mli

porting https://github.com/MinaProtocol/mina/pull/16674 to develop

[DEV] Introduce zkapp_vk_cache_tag project for caching zkapp verification keys

---

buildkite/src/Constants/ContainerImages.dhall
buildkite/src/Jobs/Test/ArchiveNodeUnitTest.dhall

Fixing container version for release hot fix

Fix CI for sai hot fix

---

flake.nix

port develop change in flake.nix to compatible

[Sync] flake.nix 

---

automation/k8s/nonpreempting-priority-class.yml

Remove not used k8s folder which was used for workaround which is now obsolete

[Repo Cleaning]  Remove not used k8s folder 

---

src/lib/mina_wire_types/mina_transaction.ml
src/lib/mina_wire_types/test/type_equalities.ml

* Remove unused types
* Simple refactoring, no changes to runtime
Checklist:

Remove Mina_wire_types.Mina_transaction.Valid

---

dockerfiles/scripts/healthcheck-utilities.sh

Porting https://github.com/MinaProtocol/mina/pull/16649 to `compatible`

Decoupling Daemon External Port from healthcheck script

---

buildkite/scripts/check-compatibility.sh

Porting compatibility script improvement to compatible  branch. Basically it help debug why we cannot find docker image for given sha

[Sync] Port compatibility script fix to comp

---

src/app/cli/src/init/client.ml
src/app/cli/src/init/test_genesis_creation.ml
src/lib/prover/intf.ml
src/lib/prover/prover.ml
src/lib/prover/prover.mli

Adds an utility that measures time to create a genesis block.
* Ran the utility on two machines, interpreted results
Checklist:

Genesis block creation benchmark

---

src/lib/mina_base/zkapp_command.ml

Simple refactoring, only types changed.
* Test pass
Checklist:

Polymorphize some funs in Zkapp_command

---

src/lib/staged_ledger/staged_ledger.mli
src/lib/transaction_logic/transaction_applied.ml
src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
src/lib/transaction_snark_scan_state/transaction_snark_scan_state.mli

Define stable and regular types separately
* No behavior changes, a refactoring
Checklist:

Split Transaction_applied.Varying.t

---

src/lib/transaction_logic/test/helpers.ml
src/lib/transaction_logic/test/transaction_logic/transaction_logic.ml
src/lib/transaction_logic/transaction_applied.ml

Define stable and regular types separately
* Simple refactoring, no code changes
Checklist:

Split Transaction_applied.Zkapp_command_applied.t

---

buildkite/src/Jobs/Lint/Merge.dhall

Counterparty of https://github.com/MinaProtocol/mina/pull/16749/

[develop] CI/buildkite: remove old branches of proof-systems

---

buildkite/src/Command/Base.dhall
buildkite/src/Command/Bench/Base.dhall

In order to stabilize measurements Luis introduced new group of agents exclusively for performance benchmarks. This PR is using them in performance tests

Use Size=Performance for Benches 

---

src/app/archive/lib/processor.ml
src/app/archive/lib/test.ml
src/app/cli/src/init/itn.ml
src/lib/integration_test_lib/wait_condition.ml
src/lib/mina_graphql/mina_graphql.ml
src/lib/mina_graphql/zkapps.ml
src/lib/transaction/transaction_hash.ml
src/lib/transaction/transaction_hash.mli
src/lib/transition_frontier/transition_frontier.ml

Simple refactoring of how `Transaction_hash`'s functions are exposed.
Useful for some future work.
Checklist:

Update Transaction_hash's use of zkapp command

---

scripts/archive/emergency_hf/test/runner.sh

port https://github.com/MinaProtocol/mina/pull/16883

port changelog logs removal  to compatible

---

src/lib/mina_base/account_update.ml
src/lib/mina_base/zkapp_command.ml

Just moving the function, no other change.
Checklist:

Move check_authorization to Account_update

---

src/lib/crypto/kimchi_bindings/stubs/Cargo.lock

- https://github.com/MinaProtocol/mina/pull/17015
- https://github.com/o1-labs/proof-systems/pull/3184
- https://github.com/MinaProtocol/kimchi-stubs-vendors/pull/9

Bump up once_cell to 1.21.3

---

src/app/archive/cli/dune
src/app/archive/dune
src/app/archive/dune-project
src/app/archive/lib/dune
src/app/archive/lib/dune-project
src/dune-project

Changes I would like to suggest, noticed while reviewing https://github.com/MinaProtocol/mina/pull/16965/

Remove redundant useless dune-project

---

buildkite/src/Jobs/Test/RosettaIntegrationTests.dhall
scripts/debian/build.sh
scripts/debian/builder-helpers.sh
scripts/debian/reversion.sh

another small brick to syncing develop and compatible. Porting mostly import order changes and some lints

[CI] Porting develop CI changes

---

nix/README.md

Removed broken openvsix link:

---

src/lib/crypto/kimchi_pasta_snarky_backend/bigint.ml
src/lib/crypto/kimchi_pasta_snarky_backend/field.ml
src/lib/crypto/kimchi_pasta_snarky_backend/kimchi_pasta_snarky_backend.ml
src/lib/crypto/kimchi_pasta_snarky_backend/test/dune
src/lib/crypto/kimchi_pasta_snarky_backend/test/test_bigint.ml
src/lib/crypto/kimchi_pasta_snarky_backend/test/test_field.ml

First steps to add more unit tests for https://github.com/MinaProtocol/mina/pull/17099.

Kimchi_pasta_snarky_backend: move to Alcotest

---

src/lib/crypto/kimchi_pasta_snarky_backend/field.ml
src/lib/crypto/kimchi_pasta_snarky_backend/test/test_field.ml

Focusing on of_yojson.
This PR does not aim to change any semantic of the codebase, but mostly checking the current behavior.
If the semantic must be changed, it is out of the scope of this PR.

Kimchi_pasta_snarky_backend: add more tests and improve documentation

---

src/app/cli/src/init/mina_run.ml

Coda -> Mina

---

src/lib/crypto/kimchi_pasta_snarky_backend/bigint.ml
src/lib/crypto/kimchi_pasta_snarky_backend/field.ml
src/lib/crypto/kimchi_pasta_snarky_backend/kimchi_pasta_snarky_backend.ml
src/lib/crypto/kimchi_pasta_snarky_backend/test/dune
src/lib/crypto/kimchi_pasta_snarky_backend/test/test_bigint.ml
src/lib/crypto/kimchi_pasta_snarky_backend/test/test_field.ml

- https://github.com/MinaProtocol/mina/pull/17104
- https://github.com/MinaProtocol/mina/pull/17105
- https://github.com/MinaProtocol/mina/pull/17104

Porting tests on fields to 3.1.1

---

changes/17091.md
src/lib/mina_intf/transition_frontier_components_intf.ml
src/lib/mina_lib/mina_lib.ml
src/lib/mina_lib/tests/tests.ml
src/lib/transition_frontier_controller/dune
src/lib/transition_frontier_controller/transition_frontier_controller.ml
src/lib/transition_handler/dune
src/lib/transition_handler/processor.ml
src/lib/transition_router/dune
src/lib/transition_router/transition_router.ml

This PR reverts #17091, as that PR breaks CI nightly

FIX(CI Nightly): Revert PR 17091

---

CODEOWNERS

- https://github.com/MinaProtocol/mina/pull/17151
- https://github.com/MinaProtocol/mina/pull/17150
- https://github.com/MinaProtocol/mina/pull/17152

CODEOWNERS: add Deepthi, George and Danny

---

src/lib/lmdb_storage/generic.ml

increased test coverage for `src/lib/lmd_storage/generic.ml` module by filling TODOs left by George +  Rw.remove function.
Second test was challenging in form of quickcheck test, so i decided to write simple unit.
I see a potential to remove some duplication (i.e in building db phase), but it is small batch of tests so far I don't know if this is worth it. However, i can add it if reviewer requires it :)

[Proof cache] increased test coverage for lmdb_storage lib

---

Makefile

Makefile: wrap long dune commands and silent the command

---

buildkite/src/Constants/ContainerImages.dhall
buildkite/src/Jobs/Test/ArchiveNodeUnitTest.dhall
dockerfiles/stages/1-build-deps
nix/rust.nix
src/lib/crypto/kimchi_bindings/stubs/rust-toolchain.toml
src/lib/crypto/kimchi_bindings/wasm/rust-toolchain.toml
src/lib/graph_algorithms/dune
src/lib/graph_algorithms/graph_algorithms.ml
src/lib/graph_algorithms/test/dune
src/lib/graph_algorithms/test/graph_algorithms_test.ml

See https://github.com/MinaProtocol/mina/pull/17156
The commands are the following:
```
git checkout develop
git fetch origin
git reset --hard origin/develop
git checkout -b dw/port-bump-up-to-rust-181-develop
git merge dw/bump-up-to-rust-1.81
```

Port 17156 to develop

---

src/lib/snark_work_lib/dune

This is a no-op, no test needed.

Snark Work Lib: order dune dependencies alphabetically

---

src/lib/ledger_proof/ledger_proof.ml
src/lib/ledger_proof/ledger_proof_intf.ml

Ledger Proof: remove function {sok_digest, Cached.sok_digest}, unused

---

src/app/cli/src/init/mina_run.ml
src/lib/integration_test_lib/event_type.ml
src/lib/snark_worker/events.ml
src/lib/snark_worker/functor.ml
src/lib/snark_worker/snark_worker.ml
src/lib/snark_worker/snark_worker.mli

As title, this is a simple noop.

Snark Worker: collect all structured log events in a new module

---

src/dune-project
src/lib/work_partitioner/dune

This is a noop. We're setting up the new Work Partitioner module

Work Partitioner: set up library

---

dockerfiles/Dockerfile-mina-rosetta

Port rosetta signer issue to compatible https://github.com/MinaProtocol/mina/pull/17209

[Comp] port rosetta signer fix

---

dockerfiles/Dockerfile-mina-rosetta

Port rosetta fix to develop https://github.com/MinaProtocol/mina/pull/17209

[Develop] Port rosetta fix to develop 

---

src/lib/snark_worker/prod.ml

This is some simple no-op refactor. I recommend review this with semantically aware `difft`.
This PR is part of the project Snark Worker Rework.

Prod Snark Worker: some minor refactor

---

src/lib/cache_dir/native/cache_dir.ml

This commit is part of an attempt to synchronize `develop` and
`compatible`.
* Simple change in logging, no testing is required
Checklist:

Update log line with more information

---

src/lib/snark_work_lib/partitioned_spec.ml
src/lib/snark_work_lib/partitioned_spec.mli

This PR defines the spec to be sent to snark worker by the coordinator after the snark worker rework.

Snark Work Lib: define partitioned spec

---

src/lib/snark_worker/rpc_failed_to_generate_snark.ml
src/lib/snark_worker/rpc_submit_work.ml
src/lib/snark_worker/rpcs.ml
src/lib/snark_worker/snark_worker.ml

This PR lifts RPC submit work and RPC failed to generate snark to its own module.

Snark Worker: lift rest 2 RPCs

---

src/lib/snark_work_lib/partitioned_result.ml
src/lib/snark_work_lib/partitioned_result.mli

As title. This is going to be the type `query` for Submit_work RPC in snark worker.

Snark Work Lib: define partitioned result

---

buildkite/scripts/debian/install.sh
dockerfiles/Dockerfile-mina-daemon

Removing obsolete debian from mina docker and from cache reader

remove mina create genesis debian from docker

---

src/lib/crypto/kimchi_bindings/stubs/Cargo.lock

- https://github.com/o1-labs/proof-systems/pull/3246
- https://github.com/MinaProtocol/kimchi-stubs-vendors/pull/12
- https://github.com/MinaProtocol/mina/pull/17329

Bump up proof-systems for arkworks 0.5

---

buildkite/scripts/setup-database-for-archive-node.sh
buildkite/scripts/tests/archive-node-unit-tests.sh
buildkite/src/Jobs/Test/ArchiveNodeUnitTest.dhall

After numerous issue where postgres port changes after we upload new toolchain, this PR is intend to fix it once for all

[archive unit tests] dynamically fetch port from postgres instead of hardcode it

---

nix/rust.nix

Credit to @L-as at https://github.com/MinaProtocol/mina/pull/17331
This is a rebase so we can pass CI on other tests.

Fix rust hash mismatch for nix

---

Makefile

It generates automatically using ## next to the target, and order alphabetically.
Inspired from [proof-systems](https://github.com/o1-labs/proof-systems/blob/master/Makefile)
Depends on https://github.com/MinaProtocol/mina/pull/17352 and https://github.com/MinaProtocol/mina/pull/17351

Makefile: improve help

---

buildkite/src/Constants/ContainerImages.dhall
buildkite/src/Constants/DockerVersions.dhall
buildkite/src/Jobs/Release/MinaArtifactNobleDevnet.dhall
dockerfiles/Dockerfile-mina-archive
dockerfiles/Dockerfile-mina-daemon
dockerfiles/Dockerfile-mina-rosetta
dockerfiles/Dockerfile-zkapp-test-transaction
dockerfiles/stages/1-build-deps-noble
dockerfiles/stages/3-toolchain
opam.export
scripts/debian/builder-helpers.sh
scripts/debian/verify.sh

Status: 
toolchain needs to be regenerated if https://github.com/MinaProtocol/mina/pull/17373 is merged first

Noble Playground Jun 10th no python-readchar

---

buildkite/src/Command/DockerImage.dhall
buildkite/src/Command/HardforkPackageGeneration.dhall
buildkite/src/Command/MinaArtifact.dhall

Small refactoring in dhall. Shouldn't introduce any functional changes. I replaced all premature convertion to string with Network.Type

use Network.Type instead of Text 

---

scripts/debian/builder-helpers.sh

Document the use of `-Zgzip` in debian build helpers

---

buildkite/src/Command/PatchArchiveTest.dhall
buildkite/src/Command/Promotion/PromoteDocker.dhall
buildkite/src/Command/Promotion/VerifyDocker.dhall
buildkite/src/Command/ReplayerTest.dhall
buildkite/src/Command/RunWithPostgres.dhall
buildkite/src/Constants/Artifacts.dhall
buildkite/src/Constants/DockerRepo.dhall
buildkite/src/Jobs/Test/RosettaIntegrationTests.dhall
buildkite/src/Jobs/Test/RosettaIntegrationTestsLong.dhall

Small refactoring needed for https://github.com/MinaProtocol/mina/pull/17166. Decoupling Artifacts with RunWIthPostgres command as we need to pass too many arguments to generate final docker tag. 
I also introduced DockerRepo type which holds addresses for our public and internal docker repositories.

[CI][Dhall] Decoupling Artifacts with RunWithPostgres

---

buildkite/src/Jobs/Release/MinaArtifactNobleDevnet.dhall
buildkite/src/Jobs/Release/MinaArtifactNobleDevnetLegacy.dhall
buildkite/src/Jobs/Release/MinaArtifactNobleMainnet.dhall
buildkite/src/Jobs/Release/MinaArtifactNobleMainnetLegacy.dhall
changes/17425.md

Build mina-devnet-legacy and mina-mainnet-legacy packages for noble codename

[CI] Build legacy package for noble

---

buildkite/src/Jobs/Test/TestnetIntegrationTests.dhall
src/app/test_executive/test_executive.ml

Test executive: order specs on both end so they largely 1-1 matchup

---

.gitignore

Stop ignoring CLAUDE.md

---

Makefile
dockerfiles/stages/1-build-deps
flake.lock
flake.nix
opam.export
scripts/docker/build.sh
scripts/update-opam-switch.sh

Following https://github.com/MinaProtocol/mina/pull/17450/files

Update non-nix setup with opam-repository commit

---

buildkite/src/Constants/ContainerImages.dhall
dockerfiles/stages/3-toolchain

Major bump up. Unsure what could be the consequences.

Dockerfile: bump up Docker from 19.03 to 28.3

---

src/lib/disk_cache/lmdb/disk_cache.ml

LMDB Cache: set `get` log level to spam

---

src/lib/disk_cache/lmdb/disk_cache.ml

LMDB Cache: remove all spam logs

---

buildkite/scripts/changelog.sh

Removed matthew from that list meanwhile since he left our company

Buildkite: grant Christian bypass changelog permission

---

buildkite/scripts/changelog.sh

This is the develop ported dual PR for https://github.com/MinaProtocol/mina/pull/17542

Buildkite: grant Christian bypass changelog permission - dev

---

buildkite/scripts/release/manager.sh
scripts/debian/builder-helpers.sh

When doing apt list on client os our mina-* packagaes has unknown suffix:
mina-daemon/unknown
This small Pr intedns to fix this issue and provide vendor part of debian package. As A result it will be presented like:
mina-daemon/minaProtocol etc.
Also added pull operation release/manager.sh, which was useful when testing

Add neccessary debian package properties. To fix unknown suffix

---

buildkite/scripts/release/manager.sh

Optionally removes network suffix from debian name. This feature is required only for archive, that's why i didn't introduce it globally and made it only applicable to archive artifact.
If enabled mina-archive debian will be named mina-archive instead of mina-archive-devnet or mina-archive-mainnet. 
Tested while publishing artifacts for release 3.2.0 . Example usage:
```
./buildkite/scripts/release/manager.sh publish --artifacts mina-archive --networks mainnet  --source-version 3.2.0-master-49b523c --target-version 3.2.0-49b523c --codenames noble --verify --channel stable --buildkite-build-id 0198557f-e9ab-497c-8562-f8b8fdb7b120 --backend hetzner --only-debians --strip-network-from-archive
```

optionally strip network suffix from archive

---

buildkite/src/Command/Bench/Base.dhall
buildkite/src/Jobs/Test/ArchiveNodeTest.dhall
buildkite/src/Jobs/Test/HFTest.dhall
buildkite/src/Jobs/Test/RosettaIntegrationTestsLong.dhall

Remove soft fail for several tests including:
- hard fork test
- rosetta integration test
- all performance tests

remove soft fail for performance tests/hardfork and rosetta

---

src/lib/transaction_snark/transaction_snark.ml
src/lib/transaction_snark/transaction_snark_intf.ml
src/lib/work_partitioner/snark_worker_shared.ml
src/lib/work_partitioner/work_partitioner.ml
src/lib/work_partitioner/work_partitioner.mli

Along with pushing sig kind, I also added it to txn snark so we can retrieve it from txn snark.

Push sig kind out of work partitioner

---

src/test/archive/archive_node_tests/load_genesis_ledger.ml

Avoiding memory increase measurement as it is so sudden that even on fixed archive version it expolodes. 
Stick to threshold checking only (4gb)
Example of failure after fix: https://buildkite.com/o-1-labs-2/mina-o-1-labs/builds/38767#01989ebb-b9ba-4af9-beb5-7554fc2da2fb/147-1446

[Archive node tests] do not measure psql mem increase just threshold

---

src/lib/string_sign/tests/test_string_sign.ml

This will be useful for https://github.com/o1-labs/proof-systems/pull/3302 and https://github.com/o1-labs/o1js/pull/2331

String_sign: add regression tests for signatures

---

src/lib/mina_stdlib/nonempty_list.ml
src/lib/mina_stdlib/nonempty_list.mli
src/lib/snark_work_lib/id.ml
src/lib/snark_work_lib/id.mli
src/lib/work_partitioner/pending_zkapp_command.ml
src/lib/work_partitioner/pending_zkapp_command.mli
src/lib/work_partitioner/work_partitioner.ml

Rebased and applied review comments on https://github.com/MinaProtocol/mina/pull/17589
TODO: ensure merging is balanced in follow up PRs. this could be delivered out of HF though.

 Fix merge of zkapp proof in work partitioner V3

---

src/lib/mina_graphql/mina_graphql.ml
src/lib/mina_lib/mina_lib.ml
src/lib/user_command_input/user_command_input.ml
src/lib/user_command_input/user_command_input.mli

As title, simple signature kind pushing PR

Push sig kind out of user command input

---

src/lib/staged_ledger/pre_diff_info.ml
src/lib/staged_ledger/staged_ledger.ml
src/lib/staged_ledger/test/txn_application_test.ml
src/lib/transaction_snark/transaction_validator.ml
src/lib/transaction_snark/transaction_validator.mli

A simple signature kind pushing PR, pushed signature kind out of txn validator

Txn Snark: push sig kind out of txn validator

---

src/lib/sparse_ledger_lib/sparse_ledger.ml

Simple top level doc comment generate by ChatGPT.

Sparse Ledger Lib: document Sparse_ledger

---

src/lib/merkle_ledger/converting_merkle_tree.ml
src/lib/merkle_ledger/converting_merkle_tree.mli
src/lib/mina_ledger/ledger.ml
src/lib/mina_ledger/ledger.mli
src/lib/mina_ledger/root.ml
src/lib/mina_ledger/root.mli

As title. there's no functional change. 
Last in train: https://github.com/MinaProtocol/mina/pull/17667
Next in train: https://github.com/MinaProtocol/mina/pull/17669

Make Converting Ledgers & Unstable DB input to Root.Make

---

src/lib/snark_work_lib/partitioned_result.ml
src/lib/snark_work_lib/partitioned_result.mli
src/lib/snark_work_lib/partitioned_spec.ml
src/lib/snark_work_lib/partitioned_spec.mli

As title, these would be needed for future Snark Worker Protocol update

Various helper functions in Snark Work Lib

---

buildkite/src/Command/Packages/Publish.dhall
buildkite/src/Constants/DebianChannel.dhall
buildkite/src/Jobs/Promote/AutoPromoteNightly.dhall

[Develop] porting nightly fix to develop

---

buildkite/src/Command/Packages/Publish.dhall
buildkite/src/Constants/DebianChannel.dhall
buildkite/src/Jobs/Promote/AutoPromoteNightly.dhall

[Compatible] Porting nightly publishing fix 

---

src/app/cli/src/init/test_ledger_application.ml
src/lib/block_producer/block_producer.ml
src/lib/bootstrap_controller/bootstrap_controller.ml
src/lib/mina_block/validation.ml
src/lib/staged_ledger/staged_ledger.ml
src/lib/staged_ledger/staged_ledger.mli
src/lib/transition_frontier/frontier_base/breadcrumb.ml
src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
src/lib/transition_frontier/transition_frontier.ml

This noop PR pushes signature kind out of staged ledger

Push signature kind out of staged ledger

---

buildkite/scripts/debian/update.sh
buildkite/src/Constants/ContainerImages.dhall
dockerfiles/Dockerfile-mina-test-suite
dockerfiles/stages/3-toolchain
scripts/tests/archive-node-test.sh

Repository is unreachable, besides, we do not use Helm in our toolchain.

Removing helm tools

---

src/lib/merkle_ledger/test/test_mask.ml

A test that the new `all_accounts_on_masks` collects the expected account updates from a chain of masks has been added to the ledger mask tests.

Add a test for all_accounts_on_masks

---

scripts/mina-local-network/mina-local-network.sh

Remove sudo when changing chown., This script is also meant to be used in non sudo context

[Mina-local-network] do not use sudo

---

buildkite/scripts/bench/install.sh
buildkite/scripts/connect/connect-to-network.sh
buildkite/scripts/debian/start_local_repo.sh
buildkite/scripts/debian/update.sh
buildkite/scripts/dump-mina-type-shapes.sh
buildkite/scripts/run-test-executive-local.sh
buildkite/scripts/single-node-tests.sh
buildkite/scripts/tests/ledger_test_apply.sh
buildkite/scripts/version-linter.sh
buildkite/src/Command/DockerImage.dhall
buildkite/src/Constants/ContainerImages.dhall
buildkite/src/Jobs/Lint/Bash.dhall
dockerfiles/Dockerfile-mina-test-suite
dockerfiles/stages/3-toolchain
flake.lock
scripts/debian/builder-helpers.sh
scripts/tests/archive-node-test.sh

Porting 3 prs to master in order to solve helms repository decommission and nix issue

Fix master nightly

---

src/lib/bootstrap_controller/bootstrap_controller.ml
src/lib/bootstrap_controller/bootstrap_controller.mli
src/lib/mina_stdlib/time.ml

As title, this is a simple noop refactor

move time span related fns from bootstrap controller -> stdlib

---

nix/pin.sh

As title. This is a simple qol improvement

nix/pin.sh: init submodule with depth 1
